export default [
  "contortuplicate - Plaited lengthwise and twisted in addition, as the bud of the morning-glory. Gray.",
  "urination - The act or process of voiding urine; micturition.",
  "micrography - The description of microscopic objects.",
  "valueless - Being of no value; having no worth.",
  "gerocomical - Pertaining to gerocomy. Dr. John Smith.",
  "approvance - Approval. [Archaic] Thomson.",
  "worthwhile - Worth the time or effort spent. See worth while. worthy. -- worthwhileness.",
  "moschine - Of or pertaining to Moschus, a genus including the musk deer.",
  "perplexiveness - The quality of being perplexing; tendency to perplex. [Obs.] Dr. H. More.",
  "concessionist - One who favors concession.",
  "fice - A small dog; -- written also fise, fyce, fiste, etc. [Southern U.S.]",
  "madefaction - The act of madefying, or making wet; the state of that which is made wet. [R.] Bacon.",
  "temblor - An earthquake. [Western U. S.]",
  "deuteropathic - Pertaining to deuteropathy; of the nature of deuteropathy.",
  "bottle-nosed - Having the nose bottleshaped, or large at the end. Dickens.",
  "inoculability - The qual ity or state of being inoculable.",
  "hazily - In a hazy manner; mistily; obscurely; confusedly.",
  "soboliferous - Producing soboles. See Illust. of Houseleek.",
  "synecphonesis - A contraction of two syllables into one; synizesis.",
  "frothing - Exaggerated declamation; rant.",
  "farmost - Most distant; farthest. A spacious cave within its farmost part. Dryden.",
  "thricecock - The missel thrush. [Prov. Eng.]",
  "barley-bree - Liquor made from barley; strong ale. [Humorous] [Scot.] Burns.",
  "bowelless - Without pity. Sir T. Browne.",
  "bitstock - A stock or handle for holding and rotating a bit; a brace.",
  "impureness - The quality or condition of being impure; impurity. Milton.",
  "church modes - The modes or scales used in ancient church music. See Gregorian.",
  "welldoing - A doing well; right performance of duties. Also used adjectively.",
  "gangrenescent - Tending to mortification or gangrene.",
  "sterrometal - Any alloy of copper, zinc, tin, and iron, of which cannon are sometimes made.",
  "ommateum - A compound eye, as of insects and crustaceans.",
  "guffaw - A loud burst of laughter, a horse laugh. \"A hearty low guffaw.\" Carlyle.",
  "intwinement - The act of twinning, or the state of being intwined.",
  "perlustration - The act of viewing all over. [Archaic] Howell.",
  "deconcentration - Act of deconcentrating. [R.]",
  "gangue - The mineral or earthy substance associated with metallic ore.",
  "water plantain - A kind of plant with acrid leaves. See under 2d Plantain.",
  "illegitimately - In a illegitimate manner; unlawfully.",
  "stillicide - A continual falling or succession of drops; rain water falling from the eaves. Bacon.",
  "fasciation - The act or manner of binding up; bandage; also, the condition of being fasciated.",
  "tool-rest - the part that supports a tool-post or a tool.",
  "precel - To surpass; to excel; to exceed. [Obs.] Howell.",
  "boroughholder - A headborough; a borsholder.",
  "orchidology - The branch of botany which treats of orchids.",
  "bulse - A purse or bag in which to carry or measure diamonds, etc. [India] Macaulay.",
  "condyloid - Shaped like or pertaining to a condyle.",
  "costean - To search after lodes. See Costeaning.",
  "electrogenic - Of or pertaining to electrogenesis; as, an electrogenic condition.",
  "ovotesttis - An organ which produces both ova and spermatozoids; an hermaphrodite gland.",
  "sea feather - Any gorgonian which branches in a plumelike form.",
  "jub - A vessel for holding ale or wine; a jug. [Obs.] Chaucer.",
  "podical - Anal; -- applied to certain organs of insects.",
  "surgeoncy - The office or employment of a surgeon, as in the naval or military service.",
  "bifacial - Having the opposite surfaces alike.",
  "scalawag - A scamp; a scapegrace. [Spelt also scallawag.] [Slang, U.S.] Bartlett.",
  "unsaturation - The quality or state of being unsaturated.",
  "lettrure - See Letterure. [Obs.] Chaucer.",
  "tridimensional - Having three dimensions; extended in three different directions.",
  "enteropathy - Disease of the intestines.",
  "recto-vesical - Of or pertaining to both the rectum and the bladder.",
  "burry - Abounding in burs, or containing burs; resembling burs; as, burry wool.",
  "autoplastic - Of or pertaining to autoplasty.",
  "smothered mate - Checkmate given when movement of the king is completely obstructed by his own men.",
  "disaffirmation - The act of disaffirming; negation; refutation.",
  "casemented - Having a casement or casements.",
  "ambigu - An entertainment at which a medley of dishes is set on at the same time.",
  "telotrocha - An annelid larva having telotrochal bands of cilia.",
  "laveer - To beat against the wind; to tack. [Obs.] Dryden.",
  "postscenium - The part of a theater behind the scenes; the back part of the stage of a theater.",
  "mammaliferous - Containing mammalian remains; -- said of certain strata.",
  "teenful - Full of teen; harmful; grievous; grieving; afflicted. [Obs.] Piers Plowman.",
  "groper - One who gropes; one who feels his way in the dark, or searches by feeling.",
  "disconsolation - Dejection; grief. [R.] Bp. Hall.",
  "mercable - Capable of being bought or sold. [Obs.]",
  "terbic - Of, pertaining to, or containing, terbium; also, designating certain of its compounds.",
  "neurospast - A puppet. [R.] Dr. H. More.",
  "disprovable - Capable of being disproved or refuted. Boyle.",
  "pretibial - Situated in front of the tibia.",
  "sulphury - Resembling, or partaking of the nature of, sulphur; having the qualities of sulphur.",
  "manifolded - Having many folds, layers, or plates; as, a manifolded shield. [Obs.]",
  "rarebit - A dainty morsel; a Welsh rabbit. See Welsh rabbit, under Rabbit.",
  "tanglefish - The sea adder, or great pipefish of Europe.",
  "complice - An accomplice. [Obs.] To quell the rebels and their complices. Shak.",
  "infurcation - A forked exlpansion or divergence; a bifurcation; a branching. Craig.",
  "patela - A large flat-bottomed trading boat peculiar to the river Ganges; -- called also puteli.",
  "plantless - Without plants; barren of vegetation.",
  "earth flax - A variety of asbestus. See Amianthus.",
  "tenthredinides - A group of Hymneoptera comprising the sawflies.",
  "granger - 1. A farm steward. [Obs.] 2. A member of a grange. [U. S.]",
  "eglomerate - To unwind, as a thread from a ball. [R.]",
  "prospicience - The act of looking forward.",
  "absinthin - The bitter principle of wormwood (Artemisia absinthium). Watts.",
  "reforestize - To convert again into a forest; to plant again with trees.",
  "antestature - A small intrenchment or work of palisades, or of sacks of earth.",
  "unlimber - To detach the limber from; as, to unlimber a gun.",
  "affronte - Face to face, or front to front; facing.",
  "overtime - Time beyond, or in excess of, a limit; esp., extra working time.",
  "roundheaded - Having a round head or top.",
  "caddy - A small box, can, or chest to keep tea in.",
  "tallowish - Having the qualities of tallow.",
  "vecture - The act of carrying; conveyance; carriage. [Obs.] Bacon.",
  "agatize - To convert into agate; to make resemble agate. Dana.",
  "discerning - Acute; shrewd; sagacious; sharp-sighted. Macaulay.",
  "shad-waiter - A lake whitefish; the roundfish. See Roundfish.",
  "obesity - The state or quality of being obese; incumbrance of flesh.",
  "micromillimeter - The millionth part of a meter.",
  "phthongometer - An instrument for measuring vocal sounds. Whewell.",
  "antemetic - Tending to check vomiting. -- n.  A remedy to check or allay vomiting.",
  "resumable - Capable of, or admitting of, being resumed. Sir M. HAle.",
  "belly-god - One whose great pleasure it is to gratify his appetite; a glutton; an epicure.",
  "cymric - Welsh. -- n.  The Welsh language. [Written also Kymric.]",
  "photometry - That branch of science which treats of the measurement of the intensity of light.",
  "heptine - Any one of a series of unsaturated metameric hydrocarbons, C7H12, of the acetylene series.",
  "dysmenorrhea - Difficult and painful menstruation.",
  "frangent - Causing fracture; breaking. [R.] H. Walpole.",
  "aftercrop - A second crop or harvest in the same year. Mortimer.",
  "helium - A gaseous element found in the atmospheres of the sun and earth and in some rare minerals.",
  "portpane - A cloth for carrying bread, so as not to touch it with the hands. [Obs.]",
  "incog - Incognito. [Colloq.] Depend upon it -- he'll remain incog. Addison.",
  "gentleship - The deportment or conduct of a gentleman. [Obs.] Ascham.",
  "suzerain - A superior lord, to whom fealty is due; a feudal lord; a lord paramount.",
  "hipshot - Having the hip dislocated; hence, having one hip lower than the other. L'Estrange.",
  "basipterygoid - Applied to a protuberance of the base of the sphenoid bone.",
  "trimembral - Having, or consisting of, three members.",
  "gullish - Foolish; stupid. [Obs.] Gull\"ish*ness, n. [Obs.]",
  "osteopathist - One who practices osteopathy; an osteopath.",
  "sky-blue - Having the blue color of the sky; azure; as, a sky-blue stone. Wordsworth.",
  "missit - To sit badly or imperfectly upon; to misbecome. [Obs.] Chaucer.",
  "safe-pledge - A surety for the appearance of a person at a given time. Bracton.",
  "pneumometry - Measurement of the capacity of the lungs for air. Dunglison.",
  "dentiform - Having the form of a tooth or of teeth; tooth-shaped.",
  "ogganition - Snarling; grumbling. [R.] Bp. Montagu.",
  "chemiglyphic - Engraved by a voltaic battary.",
  "rubify - To redden. [R.] \"Waters rubifying.\" Chaucer.",
  "ostracea - A division of bivalve mollusks including the oysters and allied shells.",
  "morology - Foolish talk; nonsense; folly. [Obs.]",
  "shoulder-shotten - Sprained in the shoulder, as a horse. Shak.",
  "gavelock - 1. A spear or dart. [R. & Obs.] 2. An iron crow or lever. [Scot. & North of Eng.]",
  "smoterlich - Dirty foul. [Obs.] Chaucer.",
  "cross-tie - A sleeper supporting and connecting the rails, and holding them in place.",
  "bonasus - The aurochs or European bison. See Aurochs.",
  "defensibility - Capability of being defended.",
  "crowstone - The top stone of the gable end of a house. Halliwell.",
  "unsluice - To sluice; to open the sluice or sluices of; to let flow; to discharge. Dryden.",
  "gloriole - An aureole. [R.] Msr. Browning.",
  "czar - A king; a chief; the title of the emperor of Russia. [Written also tzar.]",
  "pacer - One who, or that which, paces; especially, a horse that paces.",
  "assizer - An officer who has the care or inspection of weights and measures, etc.",
  "calyciform - Having the form or appearance of a calyx.",
  "transprint - To transfer to the wrong place in printing; to print out of place. [R.] Coleridge.",
  "implacableness - The quality of being implacable; implacability.",
  "bibliopolism - The trade or business of selling books.",
  "lorgnette - An opera glass; pl.  elaborate double eyeglasses.",
  "galletyle - A little tile of glazed earthenware. [Obs.] \"The substance of galletyle.\" Bacon.",
  "zinkenite - A steel-gray metallic mineral, a sulphide of antimony and lead.",
  "intranquillity - Unquietness; restlessness. Sir W. Temple.",
  "knawel - A low, spreading weed (Scleranthus annuus), common in sandy soil.",
  "hemionus - A wild ass found in Thibet; the kiang. Darwin.",
  "jauntiness - The quality of being jaunty. That jauntiness of air I was once master of. Addison.",
  "unwork - To undo or destroy, as work previously done.",
  "targeteer - One who is armed with a target or shield. [Written also targetier.]",
  "favonian - Pertaining to the west wind; soft; mild; gentle.",
  "christmastide - The season of Christmas.",
  "corruptness - The quality of being corrupt.",
  "bona roba - A showy wanton; a courtesan. Shak",
  "appetizer - Something which creates or whets an appetite.",
  "subterfluent - Running under or beneath. [R.]",
  "technologist - One skilled in technology; one who treats of arts, or of the terms of arts.",
  "trumpet-tongued - Having a powerful, far-reaching voice or speech.",
  "tutorage - The office or occupation of a tutor; tutorship; guardianship.",
  "exacervation - The act of heaping up. [Obs.] Bailey.",
  "catholicness - The quality of being catholic; universality; catholicity.",
  "pelfish - Of or pertaining to pelf. Stanyhurst.",
  "resipiscence - Wisdom derived from severe experience; hence, repentance. [R.] Bp. Montagu.",
  "favoredly - In a favored or a favorable manner; favorably. [Obs.] Deut. xvii. 1. Arscham.",
  "unpleasive - Unpleasant. [Obs.] \"An unpleasive passion.\" Bp. Hall.",
  "conjointly - In a conjoint manner; untitedly; jointly; together. Sir T. Browne.",
  "tonnish - In the ton; fashionable; modish. -- Ton\"nish*ness, n.",
  "praepubis - Same as Preoral, Prepubis, Prescapula, etc.",
  "hybridization - The act of hybridizing, or the state of being hybridized.",
  "feather-heeled - Light-heeled; gay; frisky; frolicsome. [Colloq.]",
  "abolitionist - A person who favors the abolition of any institution, especially negro slavery.",
  "effervescive - Tending to produce effervescence. \"An effervescive force.\" Hickok.",
  "austrine - Southern; southerly; austral. [Obs.] Bailey.",
  "feudalization - The act of reducing to feudal tenure.",
  "ancille - A maidservant; a handmaid. [Obs.] Chaucer.",
  "gigantology - An account or description of giants.",
  "compressibleness - The quality of being compressible; compressibility.",
  "pekoe - A kind of black tea. [Written also pecco.]",
  "tzarina - The empress of Russia. See Czarina.",
  "incocted - Raw; indigestible. [Obs.] Bp. Hall.",
  "cantion - A song or verses. [Obs.] Spenser.",
  "aphetize - To shorten by aphesis. These words . . . have been aphetized. New Eng. Dict.",
  "ilkoon - Each one; every one. [Obs.] Chaucer.",
  "septinsular - Consisting of seven islands; as, the septinsular republic of the Ionian Isles.",
  "portingal - Of or pertaining to Portugal; Portuguese. [Obs.] -- n.  A Portuguese. [Obs.]",
  "leprosity - The state or quality of being leprous or scaly; also, a scale. Bacon.",
  "eruct - To eject, as wind, from the stomach; to belch. [R.] Howell.",
  "merkin - Originally, a wig; afterwards, a mop for cleaning cannon.",
  "decomplex - Repeatedly compound; made up of complex constituents.",
  "indomite - Not tamed; untamed; savage; wild. [Obs.] J. Salkeld.",
  "hoemother - The basking or liver shark; -- called also homer. See Liver shark, under Liver.",
  "prideful - Full of pride; haughty. Tennyson. -- Pride\"ful*ly, adv. -- Pride\"ful-ness, n.",
  "pomposo - Grand and dignified; in grand style.",
  "pyrogallate - A salt of pyrogallic acid; an ether of pyrogallol.",
  "remodification - The act of remodifying; the state of being remodified.",
  "ectopic - Out of place; congenitally displaced; as, an ectopic organ.",
  "trestlework - A viaduct, pier, scaffold, or the like, resting on trestles connected together.",
  "subtrahend - The sum or number to be subtracted, or taken from another.",
  "pipemouth - Any fish of the genus Fistularia; -- called also tobacco pipefish. See Fistularia.",
  "dev - A god; a deity; a divine being; an idol; a king.",
  "unreasoned - Not supported by reason; unreasonable. \"Unreasoned habits.\" Burke.",
  "ornithodelphia - Same as Monotremata. -- Or`ni*tho*del\"phid, a.",
  "redhibitory - Of or pertaining to redhibition; as, a redhibitory action or fault.",
  "sheath-winged - Having elytra, or wing cases, as a beetle.",
  "foremeant - Intended beforehand; premeditated. [Obs.] Spenser.",
  "priestess - A woman who officiated in sacred rites among pagans. Abp. Potter.",
  "sternway - The movement of a ship backward, or with her stern foremost.",
  "satisfyingly - So as to satisfy; satisfactorily.",
  "potsure - Made confident by drink. [Obs.]",
  "busto - A bust; a statue. With some antick bustoes in the niches. Ashmole.",
  "misform - To make in an ill form. Spenser.",
  "aiguille - 1. A needle-shaped peak. 2. An instrument for boring holes, used in blasting.",
  "dearworth - Precious. [Obs.] Piers Plowman.",
  "two-cleft - Divided about half way from the border to the base into two segments; bifid.",
  "water gate - A gate, or valve, by which a flow of water is permitted, prevented, or regulated.",
  "gabert - A lighter, or vessel for inland navigation. [Scot.] Jamieson.",
  "fostress - A woman who feeds and cherishes; a nurse. B. Jonson.",
  "jocantry - The act or practice of jesting. [Obs.]",
  "horror-struck - Horror-stricken; horrified. M. Arnold.",
  "pseudo-romantic - Falsely romantic. The false taste, the pseudo-romantic rage. De Quincey.",
  "grapy - Composed of, or resembling, grapes. The grapy clusters. Addison.",
  "cryptical - Hidden; secret; occult. \"Her [nature's] more cryptic ways of working.\" Glanvill.",
  "adays - By day, or every day; in the daytime. [Obs.] Fielding.",
  "constrainable - Capable of being constrained; liable to constraint, or to restraint. Hooker.",
  "clumsily - In a clumsy manner; awkwardly; as, to walk clumsily.",
  "couveuse - An incubator for sickly infants, esp. those prematurely born.",
  "torcher - One who gives light with a torch, or as if with a torch. [Obs.] Shak.",
  "decameter - A measure of length in the metric system; ten meters, equal to about 393.7 inches.",
  "thlipsis - Compression, especially constriction of vessels by an external cause.",
  "seppuku - Same as Hara-kiri. Seppuku, or hara-kiri, also came into vogue. W. E. Griffis.",
  "countreplete - To counterplead. [Obs.] Chaucer.",
  "immixture - Freedom from mixture; purity. [R.] W. Montagu.",
  "nonsensitive - Not sensitive; wanting sense or perception; not easily affected.",
  "asbestiform - Having the form or structure of asbestus.",
  "filiferous - Producing threads. Carpenter.",
  "allatrate - To bark as a dog. [Obs.] Stubbes.",
  "anthophilous - Lit., fond of flowers; hence, feeding upon, or living among, flowers.",
  "protuberation - The act of swelling beyond the surrounding surface. Cooke (1615).",
  "cousinage - Relationship; kinship. [Obs.] Wyclif.",
  "high-handed - Overbearing; oppressive; arbitrary; violent; as, a high-handed act.",
  "salsamentarious - Salt; salted; saline. [R.]",
  "subpericardial - Situated under the cardiac pericardium.",
  "opinionator - An opinionated person; one given to conjecture. [Obs.] South.",
  "degradement - Deprivation of rank or office; degradation. [R.] Milton.",
  "cuban - Of or pertaining to Cuba or its inhabitants. -- n.  A native or an inhabitant of Cuba.",
  "ophiomancy - Divination by serpents, as by their manner of eating, or by their coils.",
  "sequestrable - Capable of being sequestered; subject or liable to sequestration.",
  "mewl - To cry, as a young child; to squall. [Written also meawl.] Shak.",
  "overmaster - To overpower; to subdue; to vanquish; to govern.",
  "commemoratory - Serving to commemorate; commomerative. Bp. Hooper.",
  "ovato-rotundate - Same as Ovate-rotundate.",
  "butyl - A compound radical, regarded as butane, less one atom of hydrogen.",
  "antimoniated - Combined or prepared with antimony; as, antimoniated tartar.",
  "ecclesial - Ecclesiastical. [Obs.] Milton.",
  "equiponderance - Equality of weight; equipoise.",
  "contributable - Capable of being contributed.",
  "denotement - Sign; indication. [R.] Note: A word found in some editions of Shakespeare.",
  "agminal - Pertaining to an army marching, or to a train. [R.]",
  "statistical - Of or pertaining to statistics; as, statistical knowledge, statistical tabulation.",
  "miniaceous - Of the color of minium or red lead; miniate.",
  "readmittance - Allowance to enter again; a second admission.",
  "gamely - In a plucky manner; spiritedly.",
  "unsuspicion - The quality or state of being unsuspecting. Dickens.",
  "steganopodous - Having all four toes webbed together.",
  "salique - Salic. Shak. She fulmined out her scorn of laws salique. Tennyson.",
  "sea-maid - 1. The mermaid. 2. A sea nymph.",
  "lionel - The whelp of a lioness; a young lion.",
  "pelecaniformes - Those birds that are related to the pelican; the Totipalmi.",
  "kneecap - 1. (Anat.)  The kneepan. 2. A cap or protection for the knee.",
  "retrorse - Bent backward or downward. -- Re*trorse\"ly, adv.",
  "bawdyhouse - A house of prostitution; a house of ill fame; a brothel.",
  "kalium - Potassium; -- so called by the German chemists.",
  "biggon - A cap or hood with pieces covering the ears.",
  "proventriulus - The glandular stomach of birds, situated just above the crop.",
  "stonebow - A kind of crossbow formerly used for shooting stones. Shak.",
  "intransigent - Refusing compromise; uncompromising; irreconcilable. Lond. Sat. Rev.",
  "nacreous - Consisting of, or resembling, nacre; pearly.",
  "pronouncement - The act of pronouncing; a declaration; a formal announcement.",
  "levin - Lightning. [Obs.] Spenser. Levin brand, a thunderbolt. [Obs.] Spenser.",
  "inaccordant - Not accordant; discordant.",
  "intermediacy - Interposition; intervention. Derham.",
  "literalization - The act of literalizing; reduction to a literal meaning.",
  "trois point - The third point from the outer edge on each player's home table.",
  "antisacerdotal - Hostile to priests or the priesthood. Waterland.",
  "clan-na-gael - A secret society of Irish Fenians founded in Philadelphia in 1881.",
  "detrect - To refuse; to decline. [Obs.] \"To detrect the battle.\" Holinshed.",
  "pygopodous - Of or pertaining to the Pygopodes.",
  "otic - Of, pertaining to, or in the region of, the ear; auricular; auditory.",
  "chiliarch - The commander or chief of a thousand men.",
  "taha - The African rufous-necked weaver bird (Hyphantornis texor).",
  "hortation - The act of exhorting, inciting, or giving advice; exhortation. [R.]",
  "laminating - Forming, or separating into, scales or thin layers.",
  "caducary - Relating to escheat, forfeiture, or confiscation.",
  "humpy - Full of humps or bunches; covered with protuberances; humped.",
  "onstead - A single farmhouse; a steading. [Prov.Eng. & Scot.] Grose. Jamieson.",
  "hessite - A lead-gray sectile mineral. It is a telluride of silver.",
  "petro- - A combining form from Gr. rock, stone; as, petrology, petroglyphic.",
  "llanero - One of the inhabitants of the llanos of South America.",
  "wallower - 1. One who, or that which, wallows. 2. (Mach.)  A lantern wheel; a trundle.",
  "sanctified - Made holy; also, made to have the air of sanctity; sanctimonious.",
  "globiferous - Having a round or globular tip.",
  "olivenite - An olive-green mineral, a hydrous arseniate of copper; olive ore.",
  "torchbearer - One whose office it is to carry a torch.",
  "barracoon - A slave warehouse, or an inclosure where slaves are quartered temporarily. Du Chaillu.",
  "imputableness - Quality of being imputable.",
  "reprune - To prune again or anew. Yet soon reprunes her wing to soar anew. Young.",
  "hippolith - A concretion, or kind of bezoar, from the intestines of the horse.",
  "rhinencephalic - Of or pertaining to the rhinencephalon.",
  "bordel - A brothel; a bawdyhouse; a house devoted to prostitution. [Obs.] B. Jonson.",
  "scabby - 1. Affected with scabs; full of scabs. 2. Diseased with the scab, or mange; mangy. Swift.",
  "smokiness - The quality or state of being smoky.",
  "overtempt - To tempt exceedingly, or beyond the power of resistance. Milton.",
  "mesonasal - Of or pertaining to the middle portion of the nasal region.",
  "recalcitration - A kicking back again; opposition; repugnance; refractoriness.",
  "tricksiness - The quality or state of being tricksy; trickiness. G. Eliot.",
  "siphonifer - Any cephalopod having a siphonate shell.",
  "pathetical - Pathetic. [R.] -- Pa*thet\"ic*al*ly, adv. -- Pa*thet\"ic*al*ness, n.",
  "madbrain - Hot-headed; rash. Shak. -- n.  A rash or hot-headed person.",
  "mendinant - A mendicant or begging friar. [Obs.] Chaucer.",
  "purposeless - Having no purpose or result; objectless. Bp. Hall. -- Pur\"pose*less*ness, n.",
  "epigraphist - A student of, or one versed in, epigraphy.",
  "downstairs - Down the stairs; to a lower floor. -- a.  Below stairs; as, a downstairs room.",
  "overmuchness - The quality or state of being in excess; superabundance. [R.] B. Jonson.",
  "sheriat - The sacred law of the Turkish empire.",
  "routously - With that violation of law called a rout. See 5th Rout, 4.",
  "sordidness - The quality or state of being sordid.",
  "metachloral - A white, amorphous, insoluble substance regarded as a polymeric variety of chloral.",
  "capriped - Having feet like those of a goat.",
  "endostoma - A plate which supports the labrum in certain Crustacea.",
  "vallum - A rampart; a wall, as in a fortification.",
  "hectocotylized - Changed into a hectocotylus; having a hectocotylis.",
  "nonnecessity - Absence of necessity; the quality or state of being unnecessary.",
  "diomedea - A genus of large sea birds, including the albatross. See Albatross.",
  "untempter - One who does not tempt, or is not a tempter. [Obs.] Wyclif.",
  "cathedrated - Relating to the chair or office of a teacher. [Obs.]",
  "inseminate - To sow; to impregnate. [Obs.]",
  "ensigncy - The rank or office of an ensign.",
  "palestinian - Of or pertaining to Palestine.",
  "devotor - A worshiper; one given to devotion. [Obs.] Beau. & Fl.",
  "aepyornis - A gigantic bird found fossil in Madagascar.",
  "mesmerize - To bring into a state of mesmeric sleep.",
  "traipse - To walk or run about in a slatternly, careless, or thoughtless manner. [Colloq.] Pope.",
  "imposturous - Impostrous; deceitful. Strictness fales and impostrous. Beau. & Fl.",
  "gastroscopic - Of or pertaining to gastroscopy.",
  "pleurobrachia - A genus of ctenophores having an ovate body and two long plumose tentacles.",
  "following surface - See Advancing-surface, above.",
  "cervix - The neck; also, the necklike portion of any part, as of the womb. See Illust. of Bird.",
  "lunulate - Resembling a small crescent. Gray.",
  "unpray - To revoke or annul by prayer, as something previously prayed for. [R.] Sir M. Hale.",
  "polyhistor - One versed in various learning. [R.]",
  "valvata - A genus of small spiral fresh-water gastropods having an operculum.",
  "uretic - Of or pertaining to the urine; diuretic; urinary; as, uretic medicine.",
  "ferruginated - Having the color or properties of the rust of iron.",
  "pallor - Paleness; want of color; pallidity; as, pallor of the complexion. Jer. Taylor.",
  "starless - Being without stars; having no stars visible; as, a starless night. Milton.",
  "turonian - One of the subdivisions into which the Upper Cretaceous formation of Europe is divided.",
  "piscatorial - Of or pertaining to fishes or fishing. Addison.",
  "xenodochy - Reception of strangers; hospitality. [R.]",
  "deathfulness - Appearance of death. Jer. Taylor.",
  "septentrionate - To tend or point toward the north; to north. Sir T. Browne.",
  "deductively - By deduction; by way of inference; by consequence. Sir T. Browne.",
  "weatherworn - Worn by the action of, or by exposure to, the weather.",
  "gradino - A step or raised shelf, as above a sideboard or altar. Cf. Superaltar, and Gradin.",
  "destemper - A kind of painting. See Distemper.",
  "vitrifaction - The act, art, or process of vitrifying; also, the state of being vitrified.",
  "recuperatory - Of or pertaining to recuperation; tending to recovery.",
  "areopagitic - Pertaining to the Areopagus. Mitford.",
  "uppricked - Upraised; erect; -- said of the ears of an animal. Mason.",
  "elementariness - The state of being elementary; original simplicity; uncompounded state.",
  "bigamist - One who is guilty of bigamy. Ayliffe.",
  "dodecasyllable - A word consisting of twelve syllables.",
  "lancely - Like a lance. [R.] Sir P. Sidney.",
  "scurviness - The quality or state of being scurvy; vileness; meanness.",
  "cup-moss - A kind of lichen, of the genus Cladonia.",
  "damaskin - A sword of Damask steel. No old Toledo blades or damaskins. Howell",
  "advisable-ness - The quality of being advisable or expedient; expediency; advisability.",
  "plunket - A kind of blue color; also, anciently, a kind of cloth, generally blue.",
  "dibbler - One who, or that which, dibbles, or makes holes in the ground for seed.",
  "bogle - A goblin; a specter; a frightful phantom; a bogy; a bugbear. [Written also boggle.]",
  "taurocol - Glue made from a bull's hide.",
  "chambertin - A red wine from Chambertin near Dijon, in Burgundy.",
  "condemner - One who condemns or censures.",
  "zymological - Of or pertaining to zymology.",
  "irreparableness - Quality of being irreparable.",
  "reintroduce - To introduce again. -- Re*in`tro*duc\"tion (-d, n.",
  "by-drinking - A drinking between meals. [Obs.]",
  "scutcheoned - Emblazoned on or as a shield. Scutcheoned panes in cloisters old. Lowell.",
  "caledonia - The ancient Latin name of Scotland; -- still used in poetry.",
  "yeastiness - The quality or state of being yeasty, or frothy.",
  "confusability - Capability of being confused.",
  "littery - Covered or encumbered with litter; consisting of or constituting litter.",
  "metallurgist - One who works in metals, or prepares them for use; one who is skilled in metallurgy.",
  "mollusk - One of the Mollusca. [Written also mollusc.]",
  "testudinated - Resembling a tortoise shell in appearance or structure; roofed; arched; vaulted.",
  "macropodal - Having long or large feet, or a long stem.",
  "hiver - One who collects bees into a hive.",
  "treacly - Like, or composed of, treacle.",
  "crotaline - Resembling, or pertaining to, the Crotalidae, or Rattlesnake family.",
  "fertilitate - To fertilize; to fecundate. Sir T. Browne.",
  "entwist - To twist or wreathe round; to intwine. Shak.",
  "almshouse - A house appropriated for the use of the poor; a poorhouse.",
  "dextrousness - Same as Dexterous, Dexterously, etc.",
  "clouterly - Clumsy; awkward. [Obs.] Rough-hewn, cloutery verses. E. Phillips.",
  "statant - In a standing position; as, a lion statant.",
  "allicient - That attracts; attracting. -- n.  That attracts. [Rare or Obs.]",
  "depeculation - A robbing or embezzlement. [Obs.] Depeculation of the public treasure. Hobbes.",
  "ledgy - Abounding in ledges; consisting of a ledge or reef; as, a ledgy island.",
  "chokedar - A watchman; an officer of customs or police. [India]",
  "retinulate - Having, or characterized by, retinul",
  "evigilation - A waking up or awakening. [Obs.]",
  "disbud - To deprive of buds or shoots, as for training, or economizing the vital strength of a tree.",
  "lioncel - A small lion, especially one of several borne in the same coat of arms.",
  "handmade - Manufactured by hand; as, handmade shoes.",
  "unjustice - Want of justice; injustice. [Obs.] Hales.",
  "overdare - To dare too much or rashly; to be too daring.",
  "hagiolatry - The invocation or worship of saints.",
  "antifriction - Something to lessea. Tending to lessen friction.",
  "buck-eyed - Having bad or speckled eyes. \"A buck-eyed horse.\" James White.",
  "cytogeny - Cell production or development; cytogenesis.",
  "ductless - Having to duct or outlet; as, a ductless gland.",
  "farmyard - The yard or inclosure attached to a barn, or the space inclosed by the farm buildings.",
  "oxidation - The act or process of oxidizing, or the state or result of being oxidized.",
  "blandly - In a bland manner; mildly; suavely.",
  "smolt - A young salmon two or three years old, when it has acquired its silvery color.",
  "salvia - A genus of plants including the sage. See Sage.",
  "biliverdin - A green pigment present in the bile, formed from bilirubin by oxidation.",
  "palsical - Affected with palsy; palsied; paralytic. [R.] Johnson.",
  "lasciviency - Lasciviousness; wantonness. [Obs.]",
  "bedazzle - To dazzle or make dim by a strong light. \"Bedazzled with the sun.\" Shak.",
  "anteposition - The placing of a before another, which, by ordinary rules, ought to follow it.",
  "ruricolist - An inhabitant of the country. [R.] Bailey.",
  "circumforanean - Going about or abroad; walking or wandering from house to house. Addison.",
  "sombreness - The quality or state of being somber; gloominess.",
  "rawhide - A cowhide, or coarse riding whip, made of untanned (or raw) hide twisted.",
  "savioress - A female savior. [Written also saviouress.] [R.] Bp. Hall.",
  "narragansetts - A tribe of Indians who formerly inhabited the shores of Narragansett Bay.",
  "triturium - A vessel for separating liquids of different densities. [Written also tritorium.]",
  "epithetical - Pertaining to, or abounding with, epithets. \"In epithetic measured prose.\" Lloyd.",
  "deglutitious - Pertaining to deglutition. [R.]",
  "bifronted - Having two fronts. \"Bifronted Janus.\" Massinger.",
  "omnipercipiency - Perception of everything.",
  "chieftaincy - The rank, dignity, or office of a chieftain.",
  "theosophistical - Of or pertaining to theosophy; theosophical.",
  "cognoscence - Cognizance. [R.] Dr. H. More.",
  "membraniform - Having the form of a membrane or of parchment.",
  "scheming - Given to forming schemes; artful; intriguing. -- Schem\"ing*ly, adv.",
  "smithing - The act or art of working or forging metals, as iron, into any desired shape. Moxon.",
  "gadsman - One who uses a gad or goad in driving.",
  "medicable - Capable of being medicated; admitting of being cured or healed.",
  "polyoptron - A glass through which objects appear multiplied, but diminished in size. [R.]",
  "floweriness - The state of being flowery.",
  "bracketing - A series or group of brackets; brackets, collectively.",
  "displat - To untwist; to uncurl; to unplat. [Obs.] Hakewill.",
  "tesseraic - Diversified by squares; done in mosaic; tessellated. [Obs.] Sir R. Atkyns (1712).",
  "bisexous - Bisexual. [Obs.] Sir T. Browne.",
  "ballotin - An officer who has charge of a ballot box. [Obs.] Harrington.",
  "lock-down - A contrivance to fasten logs together in rafting; -- used by lumbermen. [U.S.]",
  "subpoenal - Required or done under penalty. Gauden.",
  "indiaman - A large vessel in the India trade. Macaulay.",
  "venefice - The act or practice of poisoning. [Obs.]",
  "kavass - An armed constable; also, a government servant or courier. [Turkey]",
  "tetrandrian - Belonging to the class Tetrandria.",
  "acclimate - To habituate to a climate not native; to acclimatize. J. H. Newman.",
  "devotionist - One given to devotion, esp. to excessive formal devotion.",
  "angiospermous - Having seeds inclosed in a pod or other pericarp.",
  "livelily - In a lively manner. [Obs.] Lamb.",
  "lycanthropist - One affected by the disease lycanthropy.",
  "vedantic - Of or pertaining to the Vedas.",
  "burgh - A borough or incorporated town, especially, one in Scotland. See Borough.",
  "martyrology - A history or account of martyrs; a register of martyrs. Bp. Stillingfleet.",
  "scrutineer - A scrutinizer; specifically, an examiner of votes, as at an election.",
  "schizocarp - A dry fruit which splits at maturity into several closed one- seeded portions.",
  "guttated - Besprinkled with drops, or droplike spots. Bailey.",
  "enterology - The science which treats of the viscera of the body.",
  "opsimathy - Education late in life. [R.] Hales.",
  "superinvestiture - An outer vestment or garment. [R.] Bp. Horne.",
  "penology - The science or art of punishment. [Written also poenology.]",
  "groat - 1. An old English silver coin, equal to four pence. 2. Any small sum of money.",
  "wolfkin - A little or young wolf. Tennyson.",
  "disassenter - One who disassents; a dissenter. [Obs.] State Trials (1634).",
  "ad infinitum - Without limit; endlessly.",
  "opinator - One fond of his own opinious; one who holds an opinion. [Obs.] Glanvill.",
  "phacellus - One of the filaments on the inner surface of the gastric cavity of certain jellyfishes.",
  "ambrosia beetle - A bark beetle that feeds on ambrosia.",
  "screechers - The picarian birds, as distinguished from the singing birds.",
  "pue - To make a low whistling sound; to chirp, as birds. Halliwell.",
  "decalogist - One who explains the decalogue. J. Gregory.",
  "siserara - A hard blow. [Prov. Eng.] Halliwell.",
  "taurocolla - Glue made from a bull's hide.",
  "semidemiquaver - A demisemiquaver; a thirty-second note.",
  "piscine - Of or pertaining to a fish or fishes; as, piscine remains.",
  "laughterless - Not laughing; without laughter.",
  "tuberculosed - Affected with tuberculosis.",
  "synthesist - One who employs synthesis, or who follows synthetic methods.",
  "lunular - Having a form like that of the new moon; shaped like a crescent.",
  "staw - To be fixed or set; to stay. [Prov. Eng.]",
  "fattiness - State or quality of being fatty.",
  "trilobita - An extinct order of arthropods comprising the trilobites.",
  "dickens - The devil. [A vulgar euphemism.] I can not tell what the dickens his name is. Shak.",
  "remunerable - Admitting, or worthy, of remuneration. -- Re*mu`ner*a*bil\"i*ty (r, n.",
  "indifuscin - A brown amorphous powder, obtained from indican.",
  "deglaze - To remove the glaze from, as pottery or porcelain, so as to give a dull finish.",
  "mangy - Infected with the mange; scabby.",
  "pilser - An insect that flies into a flame.",
  "bipennis - An ax with an edge or blade on each side of the handle.",
  "emphyteutic - Of or pertaining to an emphyteusis; as, emphyteutic lands.",
  "speakership - The office of speaker; as, the speakership of the House of Representatives.",
  "gonorrhoeal - Of or pertaining to gonorrhea; as, gonorrheal rheumatism.",
  "rubell - A red color used in enameling. Weale.",
  "malversation - Evil conduct; fraudulent practices; misbehavior, corruption, or extortion in office.",
  "monodactylous - Having but one finger or claw.",
  "a-sea - On the sea; at sea; toward the sea.",
  "devisee - One to whom a devise is made, or real estate given by will.",
  "appraisal - A valuation by an authorized person; an appraisement.",
  "confusely - Confusedly; obscurely. [Obs.]",
  "smugness - The quality or state of being smug.",
  "marvelously - In a marvelous manner; wonderfully; strangely.",
  "papillote - a small piece of paper on which women roll up their hair to make it curl; a curl paper.",
  "brawniness - The quality or state of being brawny.",
  "releasement - The act of releasing, as from confinement or obligation. Milton.",
  "viticultural - Of or pertaining to viticulture.",
  "sea-built - Built at, in, or by the sea.",
  "mome - A dull, silent person; a blockhead. [Obs.] Spenser.",
  "sight-hole - A hole for looking through; a peephole. \"Stop all sight-holes.\" Shak.",
  "expectedly - In conformity with expectation. [R.] Walpole.",
  "preadvertise - To advertise beforehand; to preannounce publicly.",
  "lifestring - A nerve, or string, that is imagined to be essential to life. Daniel.",
  "cnidocil - The fine filiform process of a cnidoblast.",
  "flyman - The driver of a fly, or light public carriage.",
  "demibastion - A half bastion, or that part of a bastion consisting of one face and one flank.",
  "yaguarundi - Same as Jaguarondi. [Written also yaguarondi, and yagouarondi.]",
  "after-glow - A glow of refulgence in the western sky after sunset.",
  "cessant - Inactive; dormant [Obs.] W. Montagu.",
  "patagonian - Of or pertaining to Patagonia. -- n.  A native of Patagonia.",
  "materialness - The state of being material.",
  "locum tenens - A substitute or deputy; one filling an office for a time.",
  "yarrish - Having a rough, dry taste. [Prov. Eng.]",
  "forwot - pres. indic. 1st & 3d pers. sing. of Forwete. [Obs.] Chaucer.",
  "keelivine - A pencil of black or red lead; -- called also keelyvine pen. [Scot.] Sir W. Scott.",
  "polisher - One who, or that which, polishes; also, that which is used in polishing. Addison.",
  "natatorial - Inclined or adapted to swim; swimming; as, natatorial birds.",
  "tonsilitic - Tonsilar. [Written also tonsillitic.]",
  "inoxidize - To prevent or hinder oxidation, rust, or decay; as, inoxidizing oils or varnishes.",
  "archegony - Spontaneous generation; abiogenesis.",
  "gabeler - A collector of gabels or taxes.",
  "pointingstock - An object of ridicule or scorn; a laughingstock. Shak.",
  "bitterwort - The yellow gentian (Gentiana lutea), which has a very bitter taste.",
  "rhythming - Writing rhythm; verse making. \"The rhythming monk.\" Fuller.",
  "implausibility - Want of plausibility; the quality of being implausible.",
  "laurite - A rare sulphide of osmium and ruthenium found with platinum in Borneo and Oregon.",
  "prelumbar - Situated immediately in front of the loins;- applied to the dorsal part of the abdomen.",
  "drudger - 1. One who drudges; a drudge. 2. A dredging box.",
  "unmember - To deprive of membership, as in a church.",
  "chulan - The fragrant flowers of the Chloranthus inconspicuus, used in China for perfuming tea.",
  "hornotine - A yearling; a bird of the year.",
  "multipresent - Being, or having the power to be, present in two or more places at once.",
  "ichthyologic - Of or pertaining to ichthyology.",
  "doctrinable - Of the nature of, or constituting, doctrine. [Obs.] Sir P. Sidney.",
  "systasis - A political union, confederation, or league. [R.] Burke.",
  "devirgination - A deflouring. [R.] Feltham.",
  "calcified - Consisting of, or containing, calcareous matter or lime salts; calcareous.",
  "kummel - A Russian and German liqueur, consisting of a sweetened spirit flavored with caraway seeds.",
  "huffer - A bully; a blusterer. Hudibras.",
  "detruncation - The act of lopping or cutting off, as the head from the body.",
  "intermuscular - Between muscles; as, intermuscular septa.",
  "cabalistically - In a cabalistic manner.",
  "obsecratory - Expressing, or used in, entreaty; supplicatory. [R.] Bp. Hall.",
  "shrieval - Of or pertaining to a sheriff.",
  "widual - Of or pertaining to a widow; vidual. [Obs.] Bale.",
  "multi- - A prefix signifying much or many; several; more than one; as, multiaxial, multocular.",
  "self-explaining - Explaining itself; capable of being understood without explanation.",
  "enchannel - To make run in a channel. \"Its waters were enchanneled.\" Sir D. Brewster.",
  "tributariness - The quality or state of being tributary.",
  "terzetto - A composition in three voice parts; a vocal (rarely an instrumental) trio.",
  "discriminatively - With discrimination or distinction. J. Foster.",
  "apothegmatist - A collector or maker of apothegms. Pope.",
  "cypsela - A one-seeded, one-called, indehiscent fruit; an achene with the calyx tube adherent.",
  "disengaging - Loosing; setting free; detaching. Disengaging machinery. See under Engaging.",
  "statistician - One versed in statistics; one who collects and classifies facts for statistics.",
  "dowered - Furnished with, or as with, dower or a marriage portion. Shak.",
  "expositive - Serving to explain; expository. Bp. Pearson.",
  "chromatin - Tissue which is capable of being stained by dyes.",
  "serigraph - An autographic device to test the strength of raw silk.",
  "scarious - Thin, dry, membranous, and not green. Gray.",
  "pentaphyllous - Having five leaves or leaflets.",
  "alfenide - An alloy of nickel and silver electroplated with silver.",
  "siziness - The quality or state of being sizy; viscousness.",
  "suborbitar - Situated under or below the orbit.",
  "anchor shot - A shot made with the object balls in an anchor space.",
  "upstreet - Toward the higher part of a street; as, to walk upstreet. G. W. Gable.",
  "vapored - 1. Wet with vapors; moist. 2. Affected with the vapors. See Vapor, n., 5.",
  "phylacterical - Of or pertaining to phylacteries.",
  "curler - 1. One who, or that which, curls. 2. A player at the game called curling. Burns.",
  "untune - To make incapable of harmony, or of harmonious action; to put out of tune. Shak.",
  "evirate - To emasculate; to dispossess of manhood. [Obs.] Bp. Hall.",
  "peristrephic - Turning around; rotatory; revolving; as, a peristrephic painting (of a panorama).",
  "subacromial - Situated beneath the acromial process of the scapula.",
  "temporarily - In a temporary manner; for a time.",
  "lordliness - The state or quality of being lordly. Shak.",
  "scorer - One who, or that which, scores.",
  "unbooked - Not written in a book; unrecorded. \"UnbookedEnglish life.\" Masson.",
  "shoplifting - Larceny committed in a shop; the stealing of anything from a shop.",
  "tricrotic - Of or pertaining to tricrotism; characterized by tricrotism.",
  "jotter - 1. One who jots down memoranda. 2. A memorandum book.",
  "comparate - One of two things compared together.",
  "macrology - Long and tedious talk without much substance; superfluity of words.",
  "reneye - To deney; to reject; to renounce. [Obs.] For he made every man reneye his law. Chaucer.",
  "somatics - The science which treats of the general properties of matter; somatology.",
  "janizarian - Of or pertaining to the janizaries, or their government. Burke.",
  "illiberalness - The state of being illiberal; illiberality.",
  "mahoohoo - The African white two-horned rhinoceros (Atelodus simus).",
  "versable - Capable of being turned. [R.]",
  "foreremembered - Called to mind previously. Bp. Montagu.",
  "mistime - To time wrongly; not to adapt to the time.",
  "wonder-working - Doing wonders or surprising things.",
  "pedimana - A division of marsupials, including the opossums.",
  "interdictory - Belonging to an interdiction; prohibitory.",
  "treasuress - A woman who is a treasurer. [R.]",
  "pedometrical - Pertaining to, or measured by, a pedometer.",
  "intermicate - To flash or shine between or among. [R.] Blount.",
  "gourdworm - The fluke of sheep. See Fluke.",
  "supertonic - The note next above the keynote; the second of the scale. Busby.",
  "archiepiscopate - The office of an archbishop; an archbishopric.",
  "baobab - A gigantic African tree (Adansonia digitata), also naturalized in India. See Adansonia.",
  "riffler - A curved file used in carving wool and marble.",
  "countour - A merchant's office; a countinghouse. [Obs.] Chaucer.",
  "coal works - A place where coal is dug, including the machinery for raising the coal.",
  "asteridian - Of or pertaining to the Asterioidea. -- n.  A starfish; one of the Asterioidea.",
  "promanation - The act of flowing forth; emanation; efflux. [Obs.] Dr. H. More.",
  "culvertailed - United or fastened by a dovetailed joint.",
  "welcomer - One who welcomes; one who salutes, or receives kindly, a newcomer. Shak.",
  "fenestrule - One of the openings in a fenestrated structure.",
  "proctorial - Of or pertaining to a proctor, esp. an academic proctor; magisterial.",
  "glutinative - Having the quality of cementing; tenacious; viscous; glutinous.",
  "acorned - 1. Furnished or loaded with acorns. 2. Fed or filled with acorns. [R.] Shak.",
  "basic steel - Steel produced by the basic process.",
  "scribable - Capable of being written, or of being written upon. [R.]",
  "ostentous - Ostentatious. [Obs.] Feltham.",
  "purger - One who, or that which, purges or cleanses; especially, a cathartic medicine.",
  "interdash - To dash between or among; to intersperse. Cowper.",
  "propione - The ketone of propionic acid, obtained as a colorless fragrant liquid.",
  "premerit - To merit or deserve beforehand. [Obs.] Eikon Basi",
  "honeyed - 1. Covered with honey. 2. Sweet, as, honeyed words. Milton.",
  "epitrochoid - A kind of curve. See Epicycloid, any Trochoid.",
  "kookoom - The oryx or gemsbok. [Written also kookaam.]",
  "hornblendic - Composed largely of hornblende; resembling or relating to hornblende.",
  "mimeograph - An autographic stencil copying device invented by Edison.",
  "mainpernable - Capable of being admitted to give surety by mainpernors; able to be mainprised.",
  "dynamically - In accordance with the principles of dynamics or moving forces. J. Peile.",
  "euchite - One who resolves religion into prayer. [Obs.] Gauden.",
  "turmerol - Turmeric oil, a brownish yellow, oily substance extracted from turmeric by ligroin.",
  "pamperer - One who, or that which, pampers. Cowper.",
  "osteocranium - The bony cranium, as distinguished from the cartilaginous cranium.",
  "groundedly - In a grounded or firmly established manner. Glanvill.",
  "calaboose - A prison; a jail. [Local, U. S.]",
  "apocynin - A bitter principle obtained from the dogbane (Apocynum cannabinum).",
  "terebration - The act of terebrating, or boring. [R.] Bacon.",
  "yoicks - A cry of encouragement to foxhounds.",
  "diapophysis - The dorsal transverse, or tubercular, process of a vertebra. See Vertebra.",
  "unproficiency - Want of proficiency or improvement. Bp. Hall.",
  "ornithological - Of or pertaining to ornithology.",
  "hubby - Full of hubs or protuberances; as, a road that has been frozen while muddy is hubby. [U.S.]",
  "anythingarian - One who holds to no particular creed or dogma.",
  "slicer - One who, or that which, slices; specifically, the circular saw of the lapidary.",
  "incircumscription - Condition or quality of being incircumscriptible or limitless. Jer. Taylor.",
  "mouldable - Capable of being molded or formed.",
  "polishment - The act of polishing, or the state of being polished. [R.]",
  "apparaillyng - Preparation. [Obs.] Chaucer.",
  "incompleteness - The state of being incomplete; imperfectness; defectiveness. Boyle.",
  "dumous - 1. Abounding with bushes and briers. 2. (Bot.)  Having a compact, bushy form.",
  "under-garment - A garment worn below another.",
  "caballero - A knight or cavalier; hence, a gentleman.",
  "homomorphic - Characterized by homomorphism.",
  "effrontit - Marked by impudence. [Obs.] Jer. Taylor.",
  "tautologize - To repeat the same thing in different words.",
  "justicer - One who administers justice; a judge. [Obs.] \"Some upright justicer.\" Shak.",
  "confab - Familiar talk or conversation. [Colloq.]",
  "preachman - A preacher; -- so called in contempt. [Obs.] Howell.",
  "cater-cousin - A remote relation. See Quater-cousin. Shak.",
  "ant-hill - A mound thrown up by ants or by termites in forming their nests.",
  "inconditionate - Not conditioned; not limited; absolute. [Obs.] Boyle.",
  "indefatigation - Indefatigableness; unweariedness. [Obs.] J. Gregory.",
  "counterplead - To plead the contrary of; to plead against; to deny.",
  "smithcraft - The art or occupation of a smith; smithing. [R.] Sir W. Raleigh.",
  "rheumatismal - Of or pertaining to rheumatism.",
  "cajuputene - A colorlees or greenish oil extracted from cajuput.",
  "immute - To change or alter. [Obs.] J. Salkeld.",
  "saxonite - See Mountain soap, under Mountain.",
  "wicke - Wicked. [Obs.] Piers Plowman. \"With full wikke intent.\" Chaucer.",
  "ing - A pasture or meadow; generally one lying low, near a river. [Obs. or Prov. Eng.]",
  "florilege - The act of gathering flowers.",
  "malodor - An Offensive to the sense of smell; ill-smelling. -- Mal*o\"dor*ous*ness. n. Carlyle.",
  "righten - To do justice to. [Obs.] Relieve [marginal reading, righten] the opressed. Isa. i. 17.",
  "lengthways - In the direction of the length; in a longitudinal direction.",
  "engarland - To encircle with a garland, or with garlands. Sir P. Sidney.",
  "bubbly - Abounding in bubbles; bubbling. Nash.",
  "obduce - To draw over, as a covering. [Obs.] Sir M. Hale.",
  "congressive - Encountering, or coming together. Sir T. Browne.",
  "inclip - To clasp; to inclose. Whate'er the ocean pales, or sky inclips. Shak.",
  "outspan - To unyoke or disengage, as oxen from a wagon. [S. Africa]",
  "orchilla weed - The lichen from which archil is obtained. See Archil.",
  "belluine - Pertaining to, or like, a beast; brutal. [R.] Animal and belluine life. Atterbury.",
  "disforestation - The act of clearing land of forests. Daniel.",
  "emeership - The rank or office of an Emir.",
  "haliographer - One who writes about or describes the sea.",
  "libeler - One who libels. [Written also libeller.] \" Libelers of others.\" Buckkminster.",
  "lagopous - Having a dense covering of long hair, like the foot of a hare.",
  "hierarchal - Pertaining to a hierarch. \"The great hierarchal standard.\" Milton.",
  "muchwhat - Nearly; almost; much. [Obs.] \"Muchwhat after the same manner.\" Glanvill.",
  "participative - Capable of participating.",
  "underbrace - To brace, fasten, or bind underneath or below. Cowper.",
  "thysanurous - Of or pertaining to the Thysanura.",
  "entorganism - An internal parasitic organism.",
  "pretentative - Fitted for trial beforehand; experimental. [R.] Sir H. Wotton.",
  "tutrix - A female guardian; a tutoress. [R.] Smollett.",
  "wallhick - The lesser spotted woodpecker (Dryobates minor). [Prov. Eng.]",
  "pleading - The act of advocating, defending, or supporting, a cause by arguments.",
  "monotheistic - Of or pertaining to monotheism.",
  "encephalitis - Inflammation of the brain. -- En`ceph*a*lit\"ic, a.",
  "gastroscopy - Examination of the abdomen or stomach, as with the gastroscope.",
  "tachydidaxy - A short or rapid method of instructing. [R.]",
  "nouch - An ouch; a jewel. [Obs.] Chaucer.",
  "sclerogen - The thickening matter of woody cells; lignin.",
  "cognati - Relatives by the mother's side. Wharton.",
  "monandrous - Of or pertaining to the monandria; having but one stamen.",
  "preominate - To ominate beforehand; to portend. [Obs.] Sir T. Browne.",
  "rejectable - Capable of being, or that ought to be, rejected.",
  "monaxial - Having only one axis; developing along a single line or plane; as, monaxial development.",
  "cassumunar - A pungent, bitter, aromatic, gingerlike root, obtained from the East Indies.",
  "diligency - Diligence; care; persevering endeavor. [Obs.] Milton.",
  "vegetability - The quality or state of being vegetable. [Obs.] Sir T. Browne.",
  "polytungstate - A salt of polytungstic acid.",
  "sphenographer - One skilled in sphenography; a sphenographist.",
  "tractator - One who writes tracts; specif., a Tractarian. [R.] C. Kingsley.",
  "inaction - Want of action or activity; forbearance from labor; idleness; rest; inertness. Berkeley.",
  "lallation - An imperfect enunciation of the letter r, in which it sounds like l.",
  "troco - An old English game; -- called also lawn billiards.",
  "tridented - Having three prongs; trident; tridentate; as, a tridented mace. [R.] Quarles.",
  "handsomely - 1. In a handsome manner. 2. (Naut.)  Carefully; in shipshape style.",
  "rapturist - An enthusiast. [Obs.] J. Spencer.",
  "protureter - The duct of a pronephros. Haeckel.",
  "sportsman - One who pursues the sports of the field; one who hunts, fishes, etc.",
  "druidic - Pertaining to, or resembling, the Druids. Druidical circles. See under Circle.",
  "bridgeless - Having no bridge; not bridged.",
  "presagious - Foreboding; ominous. [Obs.]",
  "duodecahedron - See Dodecahedral, and Dodecahedron.",
  "dysuric - Pertaining to, or afflicted with, dysury.",
  "vapory - 1. Full of vapors; vaporous. 2. Hypochondriacal; splenetic; peevish.",
  "creatureless - Without created beings; alone. God was alone And creatureless at first. Donne.",
  "clericity - The state of being a clergyman.",
  "coolung - The great gray crane of India (Grus cinerea). [Also written coolen and cullum.]",
  "yokelet - A small farm; -- so called as requiring but one yoke of oxen to till it. [Prov. Eng.]",
  "contriteness - Deep sorrow and penitence for sin; contrition.",
  "detort - To turn form the original or plain meaning; to pervert; to wrest. Hammond.",
  "incoalescence - The state of not coalescing.",
  "nebulization - The act or process of nebulizing; atomization.",
  "uniocular - Of, pertaining to, or seated in, one eye; monocular.",
  "leed - A caldron; a copper kettle. [Obs.] \"A furnace of a leed.\" Chaucer.",
  "palliobranchiate - Having the pallium, or mantle, acting as a gill, as in brachiopods.",
  "peavey - A cant hook having the end of its lever armed with a spike.",
  "hygeist - One skilled in hygiena; a hygienist.",
  "dissimule - To dissemble. [Obs.] Chaucer.",
  "panhandle state - West Virginia; -- a nickname.",
  "vestiarian - Of or pertaining to a vestiary or vestments.",
  "longitudinally - In the direction of length.",
  "benefiter - One who confers a benefit; -- also, one who receives a benefit.",
  "incalescence - The state of being incalescent, or of growing warm. Sir T. Browne.",
  "mastodyny - Pain occuring in the mamma or female breast, -- a form of neuralgia.",
  "profligateness - The quality of being profligate; an abandoned course of life; profligacy.",
  "diffusibility - The quality of being diffusible; capability of being poured or spread out.",
  "cerulific - Producing a blue or sky color. [R.]",
  "potoo - A large South American goatsucker (Nyctibius grandis).",
  "condensable - Capable of being condensed; as, vapor is condensable.",
  "matriculation - The act or process of matriculating; the state of being matriculated.",
  "fascinous - Caused or acting by witchcraft. [Obs.] \"Fascinous diseases.\" Harvey.",
  "bedclothes - Blankets, sheets, coverlets, etc., for a bed. Shak.",
  "malevolous - Malevolent. [Obs.] Bp. Warburton.",
  "persis - A kind of coloring matter obtained from lichens.",
  "allwork - Domestic or other work of all kinds; as, a maid of allwork, that is, a general servant.",
  "constablewick - The district to which a constable's power is limited. [Obs.] Sir M. Hale.",
  "sacalait - A kind of fresh-water bass; the crappie. [Southern U.S.]",
  "spadroon - A sword, especially a broadsword, formerly used both to cut and thrust.",
  "coloradoite - Mercury telluride, an iron-black metallic mineral, found in Colorado.",
  "roon - Vermilion red; red. [R.] Her face was like the lily roon. J. R. Drake.",
  "evolutionism - The theory of, or belief in, evolution. See Evolution, 6 and 7.",
  "nonregent - A master of arts whose regency has ceased. See Regent.",
  "vaporizable - Capable of being vaporized into vapor.",
  "hamesucken - The felonious seeking and invasion of a person in his dwelling house. Bouvier.",
  "estre - The inward part of a building; the interior. [Obs.] Chaucer.",
  "gambet - Any bird of the genuis Totanus. See Tattler.",
  "gentoo - A native of Hindostan; a Hindoo. [Archaic]",
  "pedicellate - Having a pedicel; supported by a pedicel.",
  "habiliment - 1. A garment; an article of clothing. Camden. 2. pl.  Dress, in general. Shak.",
  "hyemate - To pass the winter. [Obs. & R.]",
  "sculptile - Formed by carving; graven; as, sculptile images. [Obs.] Sir T. Browne.",
  "epanthous - Growing upon flowers; -- said of certain species of fungi.",
  "enforceable - Capable of being enforced.",
  "piperylene - A hydrocarbon obtained by decomposition of certain piperidine derivatives.",
  "apogeotropism - The apogeotropic tendency of some leaves, and other parts.",
  "inconnexedly - Not connectedly; without connection. [Obs.] Sir T. Browne.",
  "sexfid - Six-cleft; as, a sexfid calyx or nectary.",
  "citharistic - Pertaining, or adapted, to the cithara.",
  "zetetics - A branch of algebra which relates to the direct search for unknown quantities. [R.]",
  "shay - A chaise. [Prov. Eng. & Local, U.S.]",
  "buckler-headed - Having a head like a buckler.",
  "obelize - To designate with an obelus; to mark as doubtful or spirituous. [R.]",
  "brassicaceous - Related to, or resembling, the cabbage, or plants of the Cabbage family.",
  "perscrutation - A thorough searching; a minute inquiry or scrutiny. Carlyle",
  "acred - Possessing acres or landed property; -- used in composition; as, large-acred men.",
  "meeken - To make meek; to nurture in gentleness and humility. [Obs.] Chaucer.",
  "signora - Madam; Mrs; -- a title of address or respect among the Italians.",
  "jinn - See Jinnee. \"Solomon is said to have had power over the jin.\" Balfour (Cyc. of India).",
  "internuncioship - The office or function of an internuncio. Richardson.",
  "intercommunication - Mutual communication. Owen.",
  "sucket - A sweetmeat; a dainty morsel. Jer. Taylor.",
  "furial - Furious; raging; tormenting. [Obs.] Chaucer.",
  "serpent-tongued - Having a forked tongue, like a serpent.",
  "unseeming - Unbeseeming; not fit or becoming.",
  "pentahedral - Having five sides; as, a pentahedral figure.",
  "braminic - , etc. See Brahman, Brachmanic, etc.",
  "feetless - Destitute of feet; as, feetless birds.",
  "pellage - A customs duty on skins of leather.",
  "plumassary - A plume or collection of ornamental feathers.",
  "electrolier - A branching frame, often of ornamental design, to support electric illuminating lamps.",
  "pulverable - Capable of being reduced to fine powder. Boyle.",
  "alkoran - The Mohammedan Scriptures. Same as Alcoran and Koran.",
  "evangelically - In an evangelical manner.",
  "impreparation - Want of preparation. [Obs.] Hooker.",
  "recurve - To curve in an opposite or unusual direction; to bend back or down.",
  "blackheart - A heart-shaped cherry with a very dark-colored skin.",
  "inscribableness - Quality of being inscribable.",
  "nunciate - One who announces; a messenger; a nuncio. [Obs.] Hoole.",
  "chronometrical - Pertaining to a chronometer; measured by a chronometer.",
  "entortilation - A turning into a circle; round figures. [Obs.] Donne.",
  "impartialness - Impartiality. Sir W. Temple.",
  "cartographer - One who make charts or maps.",
  "poser - One who, or that which, puzzles; a difficult or inexplicable question or fact. Bacon.",
  "epanalepsis - A figure by which the same word or clause is repeated after intervening matter. Gibbs.",
  "surinam toad - A species of toad native of Surinam. See Pipa.",
  "indagative - Searching; exploring; investigating. [Obs.] Jer. Taylor.",
  "overproportion - To make of too great proportion.",
  "brokerly - Mean; servile. [Obs.] B. Jonson.",
  "distributable - Capable of being distributed. Sir W. Jones.",
  "scrog - A stunted shrub, bush, or branch. [Prov. Eng. & Scot.]",
  "unstack - To remove, or take away, from a stack; to remove, as something constituting a stack.",
  "fifthly - In the fifth place; as the fifth in order.",
  "temperamental - Of or pertaining to temperament; constitutional. [R.] Sir T. Browne.",
  "tussive - Pertaining to a cough; caused by coughing.",
  "pellagrous - Pertaining to, or affected with, or attendant on, pellagra; as, pellagrous insanity.",
  "diesinking - The process of engraving dies.",
  "misconsecrate - To consecrate amiss. \"Misconsecrated flags.\" Bp. Hall.",
  "semilogical - Half logical; partly logical; said of fallacies. Whately.",
  "pleuritical - (a) Of or pertaining to pleurisy; as, pleuritic symptoms. (b) Suffering from pleurisy.",
  "nomothetic - Legislative; enacting laws; as, a nomothetical power. [R.] Bp. Barlow.",
  "alength - At full length; lenghtwise. Chaucer.",
  "gourde - A silver dollar; -- so called in Cuba, Hayti, etc. Simmonds.",
  "epiphyllospermous - Bearing fruit on the back of the leaves, as ferns. Harris (1710).",
  "filibeg - Same as Kilt. [Written also philibeg.]",
  "affuse - To pour out or upon. [R.] I first affused water upon the compressed beans. Boyle.",
  "evacuator - One who evacuates; a nullifier. \"Evacuators of the law.\" Hammond.",
  "plug board - A switchboard in which connections are made by means of plugs.",
  "integumentary - Belonging to, or composed of, integuments.",
  "cynegetics - The art of hunting with dogs.",
  "chitty - 1. Full of chits or sprouts. 2. Childish; like a babe. [Obs.]",
  "paramiographer - A collector or writer of proverbs. [R.]",
  "rabatine - A collar or cape. [Obs.]  Sir W. Scott.",
  "abactor - One who steals and drives away cattle or beasts by herds or droves. [Obs.]",
  "replaceability - The quality, state, or degree of being replaceable.",
  "chiroplast - An instrument to guid the hands and fingers of pupils in playing on the piano, etc.",
  "broomstick - A stick used as a handle of a broom.",
  "insensitive - Not sensitive; wanting sensation, or wanting acute sensibility. Tillotson. Ruskin.",
  "misadvised - Ill advised. -- Mis`ad*vis\"ed*ly, adv.",
  "tun-great - Having the circumference of a tun. [Obs.] Chaucer.",
  "emblanch - To whiten. See Blanch. [Obs.] Heylin.",
  "insubordination - The quality of being insubordinate; disobedience to lawful authority.",
  "sea hare - Any tectibranchiate mollusk of the genus Aplysia. See Aplysia.",
  "iciness - The state or quality of being icy or very cold; frigidity.",
  "apporter - A bringer in; an importer. [Obs.] Sir M. Hale.",
  "antechapel - The outer part of the west end of a collegiate or other chapel. Shipley.",
  "bromanil - A substance analogous to chloranil but containing bromine in place of chlorine.",
  "millistere - A liter, or cubic decimeter.",
  "propendent - Inclining forward or toward. South.",
  "batule - A springboard in a circus or gymnasium; -- called also batule board.",
  "sea beast - Any large marine mammal, as a seal, walrus, or cetacean.",
  "cauline - Growing immediately on a caulis; of or pertaining to a caulis.",
  "unscutcheoned - Destitute of an escutcheon. [R.] Pollock.",
  "christian scientist - A believer in Christian Science; one who practices its teachings.",
  "worrel - An Egyptian fork-tongued lizard, about four feet long when full grown.",
  "universology - The science of the universe, and the relations which it involves.",
  "inexecution - Neglect of execution; nonperformance; as, the inexecution of a treaty. Spence.",
  "primely - 1. At first; primarily. [Obs.] South. 2. In a prime manner; excellently.",
  "myxinoid - Like, or pertaining to, the genus Myxine. -- n.  A hagfish.",
  "nethermost - Lowest; as, the nethermost abyss. Milton.",
  "odontology - The science which treats of the teeth, their structure and development.",
  "decurrence - The act of running down; a lapse. [R.] Gauden.",
  "self-wrong - Wrong done by a person himself. Shak.",
  "intactable - Not perceptible to the touch.",
  "gastronomy - The art or science of good eating; epicurism; the art of good cheer.",
  "fayalite - A black, greenish, or brownish mineral of the chrysolite group. It is a silicate of iron.",
  "appropriately - In an appropriate or proper manner; fitly; properly.",
  "retroduction - A leading or bringing back.",
  "collected - 1. Gathered together. 2. Self-possessed; calm; composed.",
  "nayword - A byword; a proverb; also, a watchword. [Obs.] hak.",
  "aspiratory - Of or pertaining to breathing; suited to the inhaling of air",
  "bireme - An ancient galley or vessel with two banks or tiers of oars.",
  "densimeter - An instrument for ascertaining the specific gravity or density of a substance.",
  "tool-post - The part of a toolrest in which a cutting tool is clamped.",
  "contractedness - The state of being contracted; narrowness; meannes; selfishness.",
  "high-churchman - One who holds high-church principles.",
  "wounder - One who, or that which, wounds.",
  "dissettlement - The act of unsettling, or the state of being unsettled. Marvell.",
  "vairy - Charged with vair; variegated with shield-shaped figures. See Vair.",
  "ecclesiologist - One versed in ecclesiology.",
  "misanthrope - A hater of mankind; a misanthropist.",
  "petar - See Petard. [Obs.] \"Hoist with his own petar.\" Shak.",
  "sociologist - One who treats of, or devotes himself to, the study of sociology. J. S. Mill.",
  "nickle - The European woodpecker, or yaffle; -- called also nicker pecker.",
  "plectospondylous - Of or pertaining to the Plectospondyli.",
  "toddler - One who toddles; especially, a young child. Mrs. Gaskell.",
  "biliment - A woman's ornament; habiliment. [Obs.]",
  "intermediae - The middle pair of tail feathers, or middle rectrices.",
  "spadille - The ace of spades in omber and quadrille.",
  "toswink - To labor excessively. [Obs.] Chaucer.",
  "hosiery - 1. The business of a hosier. 2. Stockings, in general; goods knit or woven like hose.",
  "tarlatan - A kind of thin, transparent muslin, used for dresses.",
  "intangibility - The quality or state of being intangible; intangibleness.",
  "centare - A measure of area, the hundredth part of an are; one square meter, or about 1",
  "parvenu - An upstart; a man newly risen into notice.",
  "readjournment - The act of readjourning; a second or repeated adjournment.",
  "measled - Infected or spotted with measles, as pork. -- Mea\"sled*ness, n.",
  "corrivation - The flowing of different streams into one. [Obs.] Burton.",
  "ferryman - One who maintains or attends a ferry.",
  "inescation - The act of baiting; allurement. [Obs.] Hallywell.",
  "cytogenic - Of or pertaining to cytogenesis or cell development.",
  "psilanthropic - Pertaining to, or embodying, psilanthropy. \"A psilanthropic explanation.\" Coleridge.",
  "inarticulateness - The state or quality of being inarticulate.",
  "phonotypical - Of or pertaining to phonotypy; as, a phonotypic alphabet.",
  "adact - To compel; to drive. [Obs.] Fotherby.",
  "funambulo - A ropewalker or ropedancer. [Obs.] Bacon.",
  "basaltiform - In the form of basalt; columnar.",
  "madid - Wet; moist; as, a madid eye. [R.] Beaconsfield.",
  "sepiment - Something that separates; a hedge; a fence. [R.] Bailey.",
  "rakestale - The handle of a rake. That tale is not worth a rakestele. Chaucer.",
  "aidless - Helpless; without aid. Milton.",
  "uronology - That part of medicine which treats of urine. Dunglison.",
  "deterge - To cleanse; to purge away, as foul or offending matter from the body, or from an ulcer.",
  "docible - Easily taught or managed; teachable. Milton.",
  "poetics - The principles and rules of the art of poetry. J. Warton.",
  "slantwise - In an inclined direction; obliquely; slopingly.",
  "glossolaly - The gift of tongues. Farrar.",
  "gyronny - Covered with gyrons, or divided so as to form several gyrons; - - said of an escutcheon.",
  "substant - Substantial; firm. [R.] \"[The glacier's] substant ice.\" The Century.",
  "suicidism - The quality or state of being suicidal, or self-murdering. [R.]",
  "segnity - Sluggishness; dullness; inactivity. [Obs.]",
  "hypnagogic - Leading to sleep; -- applied to the illusions of one who is half asleep.",
  "electrolyte - A compound decomposable, or subjected to decomposition, by an electric current.",
  "enlacement - The act of enlacing, or state of being enlaced; a surrounding as with a lace.",
  "vicarage - 1. The benefice of a vicar. 2. The house or residence of a vicar.",
  "loadstone - A piece of magnetic iron ore possessing polarity like a magnetic needle. See Magnetite.",
  "fusibility - The quality of being fusible.",
  "masty - Full of mast; abounding in acorns, etc.",
  "convexo-plane - Convex on one side, and flat on the other; plano-convex.",
  "bourree - An old French dance tune in common time.",
  "toxoid - An altered form of a toxin, possessing little or no toxic power.",
  "psychal - Of or pertaining to the soul; psychical. Bayne.",
  "disjointly - In a disjointed state. Sandys.",
  "blastomere - One of the segments first formed by the division of the ovum. Balfour.",
  "procerity - Height of stature; tallness. [R.] Johnson.",
  "reposition - The act of repositing; a laying up.",
  "antimeter - A modification of the quadrant, for measuring small angles. [Obs.]",
  "pamprodactylous - Having all the toes turned forward, as the colies.",
  "riden - imp. pl. & p. p. of Ride. Chaucer.",
  "horny-handed - Having the hands horny and callous from labor.",
  "cardioinhibitory - Checking or arresting the heart's action.",
  "aurocyanide - A double cyanide of gold and some other metal or radical; -- called also cyanaurate.",
  "ensile - To store (green fodder) in a silo; to prepare as silage. -- En\"si*list (#), n.",
  "shrap - A place baited with chaff to entice birds. [Written also scrap.] [Obs.] Bp. Bedell.",
  "marabout - A Mohammedan saint; especially, one who claims to work cures supernaturally.",
  "wanderer - One who wanders; a rambler; one who roves; hence, one who deviates from duty.",
  "neuromere - A metameric segment of the cerebro-spinal nervous system.",
  "calando - (Mus.) Gradually diminishing in rapidity and loudness.",
  "inquisiturient - Inquisitorial. [Obs.] \"Our inquisiturient bishops.\" Milton.",
  "giganticide - The act of killing, or one who kills, a giant. Hallam.",
  "subofficer - An under or subordinate officer.",
  "mateotechny - Any unprofitable science. [Obs.]",
  "lancination - A tearing; laceration. \"Lancinations of the spirit.\" Jer. Taylor.",
  "radiant engine - A semiradial engine. See Radial engine, above.",
  "paragenesis - The science which treats of minerals with special reference to their origin.",
  "deka- - A prefix signifying ten. See Deca-."
]