export default [
  "glycocholate - A salt of glycocholic acid; as, sodium glycocholate.",
  "thoracostraca - An extensive division of Crustacea, having a dorsal shield or carapec",
  "octonary - Of or pertaining to the number eight. Dr. H. More.",
  "rubific - Making red; as, rubific rays. Grew.",
  "lingot - A linget or ingot; also, a mold for casting metals. See Linget.",
  "symphonize - To agree; to be in harmony. [R.] Boyle.",
  "dareful - Full af daring or of defiance; adveturous. [R.] Shak.",
  "carotin - A red crystallizable tasteless substance, extracted from the carrot.",
  "high-embowed - Having lofty arches. \"The high-embowed roof.\" Milton.",
  "aethogen - A compound of nitrogen and boro",
  "teapot - A vessel with a spout, in which tea is made, and from which it is poured into teacups.",
  "engravement - 1. Engraving. 2. Engraved work. [R.] Barrow.",
  "viscosimeter - An instrument for measuring the degree of viscosity of liquids, as solutions of gum.",
  "amianthus - Earth flax, or mountain flax; a soft silky variety of asbestus.",
  "cack - To ease the body by stool; to go to stool. Pope.",
  "notobranchiate - Of or pertaining to the Notobranchiata.",
  "eyespotted - Marked with spots like eyes. Junno's bird, in her eye-spotted train. Spenser.",
  "haemal - Pertaining to the blood or blood vessels; also, ventral. See Hemal.",
  "incircumscriptible - Incapable of being circumscribed or limited. Cranmer.",
  "duck-billed - Having a bill like that of a duck..",
  "tetel - A large African antelope (Alcejaphus tora). It has widely divergent, strongly ringed horns.",
  "findable - Capable of beong found; discoverable. Fuller.",
  "flockmel - In a flock; in a body. [Obs.] That flockmel on a day they to him went. Chaucer.",
  "diminutiveness - The quality of being diminutive; smallness; littleness; minuteness.",
  "folklore - . Tales, legends, or superstitions long current among the people. Trench.",
  "trousse - A case for small implements; as, a surgeon's trousse.",
  "micro-geological - Of or pertaining to micro-geology.",
  "transvertible - Capable of being transverted. [R.] Sir T. Browne.",
  "mountainousness - The state or quality of being mountainous.",
  "pinpatch - The common English periwinkle. [Prov. Eng.]",
  "deathliness - The quality of being deathly; deadliness. Southey.",
  "archer - A bowman, one skilled in the use of the bow and arrow.",
  "etnean - Pertaining to Etna, a volcanic mountain in Sicily.",
  "father longlegs - See Daddy longlegs, 2.",
  "granule - A little grain a small particle; a pellet.",
  "antidysenteric - Good against dysentery. -- n.  A medicine for dysentery.",
  "serpette - A pruning knife with a curved blade. Knight.",
  "glyptography - The art or process of engraving on precious stones. [R.]",
  "crustaceological - Pertaining to crustaceology.",
  "stripper - One who, or that which, strips; specifically, a machine for stripping cards.",
  "colluctancy - A struggling to resist; a striving against; resistance; opposition of nature. [Obs.]",
  "laccic - Pertaining to lac, or produced from it; as, laccic acid.",
  "shipmaster - The captain, master, or commander of a ship. Jonah i. 6.",
  "mediastinal - Of or pertaining to a mediastinum.",
  "dentalium - A genus of marine mollusks belonging to the Scaphopoda, having a tubular conical shell.",
  "dodecagynous - Of or pertaining to the Dodecagynia; having twelve styles.",
  "sneaksby - A paltry fellow; a sneak. [Obs.] \"Such a bashful sneaksby.\" Barrow.",
  "carbamide - The technical name for urea.",
  "accombination - A combining together. [R.]",
  "rowan - Rowan tree. Rowan barry, a barry of the rowan tree.",
  "rememorate - To recall something by means of memory; to remember. [Obs.] Bryskett.",
  "halved - Appearing as if one side, or one half, were cut away; dimidiate.",
  "infralapsarianism - The doctrine, belief, or principles of the Inralapsarians.",
  "sunlike - Like or resembling the sun. \"A spot of sunlike brilliancy.\" Tyndall.",
  "indiscriminative - Making no distinction; not discriminating.",
  "purifier - One who, or that which, purifies or cleanses; a cleanser; a refiner.",
  "indigotin - See Indigo blue, under Indigo.",
  "jubilation - A triumphant shouting; rejoicing; exultation. \"Jubilations and hallelujahs.\" South.",
  "prothalamion - A song in celebration of a marriage. Drayton.",
  "boreas - The north wind; -- usually a personification.",
  "guildhall - The hall where a guild or corporation usually assembles; a townhall.",
  "reimpregnate - To impregnate again or anew. Sir T. Browne.",
  "wryness - The quality or state of being wry, or distorted. W. Montagu.",
  "recolonization - A second or renewed colonization.",
  "circumspectly - In a circumspect manner; cautiously; warily.",
  "umbellet - A small or partial umbel; an umbellule.",
  "grainfield - A field where grain is grown.",
  "spathed - Having a spathe or calyx like a sheath.",
  "imbreed - To generate within; to inbreed. [Obs.] Hakewill.",
  "indelibility - The quality of being indelible. Bp. Horsley.",
  "boastless - Without boasting or ostentation.",
  "indemonstrable - Incapable of being demonstrated. -- In`de*mon\"stra*ble*ness, n.",
  "rei - A portuguese money of account, in value about one tenth of a cent. [Spelt also ree.]",
  "wisher - One who wishes or desires; one who expresses a wish. Shak.",
  "gulosity - Excessive appetite; greediness; voracity. [R.] Sir T. Browne.",
  "faultiness - Quality or state of being faulty. Round, even to faultiness. Shak.",
  "vulcanizer - One who, or that which, vulcanizes; esp., an apparatus for vulcanizing caoutchouc.",
  "fossilization - The process of converting, or of being converted, into a fossil.",
  "trade-unionist - A member of a trades union, or a supporter of trades unions.",
  "hask - A basket made of rushes or flags, as for carrying fish. [Obs.] Spenser.",
  "incultivated - Uncultivated. [Obs.] Sir T. Herbert.",
  "horticultural - Of or pertaining to horticulture, or the culture of gardens or orchards.",
  "nomothetical - Legislative; enacting laws; as, a nomothetical power. [R.] Bp. Barlow.",
  "antherozooid - One of the mobile male reproductive bodies in the antheridia of cryptogams.",
  "savant - A man of learning; one versed in literature or science; a person eminent for acquirements.",
  "telelectric - Of or pertaining to transmission, as of music, to a distance by electricity.",
  "overgaze - To gaze; to overlook. [Poetic] \"Earth's o'ergazing mountains.\" Byron.",
  "alluminor - An illuminator of manuscripts and books; a limner. [Obs.] Cowell.",
  "backworm - A disease of hawks. See Filanders. Wright.",
  "tataupa - A South American tinamou (Crypturus tataupa).",
  "forelend - See Forlend. [Obs.] As if that life to losse they had forelent. Spenser.",
  "rainless - Destitute of rain; as, a rainless region.",
  "good-humored - Having a cheerful spirit and demeanor; good-tempered. See Good- natured.",
  "phassachate - The lead-colored agate; -- so called in reference to its color.",
  "oedematous - Pertaining to, or of the nature of, edema; affected with edema.",
  "sperling - (a) A smelt; a sparling. [Prov. Eng.] (b) A young herring. [Local, U.S.]",
  "withinside - In the inner parts; inside. [Obs.] Graves.",
  "spoliator - One who spoliates; a spoiler.",
  "instructress - A woman who instructs; a preceptress; a governess. Johnson.",
  "wooingly - In a wooing manner; enticingly; with persuasiveness. Shak.",
  "decimalism - The system of a decimal currency, decimal weights, measures, etc.",
  "irresponsibility - Want of, or freedom from, responsibility or accountability.",
  "uninteressed - Uninterested; unaffected. [Obs.] Glanvill.",
  "enneagon - A polygon or plane figure with nine sides and nine angles; a nonagon.",
  "mellifluence - A flow of sweetness, or a sweet, smooth flow.",
  "necropsy - A post-mortem examination or inspection; an autopsy. See Autopsy.",
  "ringbolt - An eyebolt having a ring through the eye.",
  "gimcrack - A trivial mechanism; a device; a toy; a pretty thing. Arbuthnot.",
  "streaky - Same as Streaked, 1. \"The streaky west.\" Cowper.",
  "taxidermist - A person skilled in taxidermy.",
  "manifoldness - 1. Multiplicity. Sherwood. 2. (Math.)  A generalized concept of magnitude.",
  "polarizable - Susceptible of polarization.",
  "alsike - A species of clover with pinkish or white flowers; Trifolium hybridum.",
  "rattletrap - Any machine or vehicle that does not run smoothly. [Colloq.] A. Trollope.",
  "by-election - An election held by itself, not at the time of a general election.",
  "lachrymae christi - A rich, sweet, red Neapolitan wine.",
  "suppeditation - Supply; aid afforded. [Obs.] Bacon.",
  "culminant - Being vertical, or at the highest point of altitude; hence, predominant. [R.]",
  "ecclesiasticism - Strong attachment to ecclesiastical usages, forms, etc.",
  "exogyra - A genus of Cretaceous fossil shells allied to oysters.",
  "cephaloid - Shaped like the head. Craing.",
  "supercarpal - Situated above, or in the upper part of, the carpus.",
  "trunkwork - Work or devices suitable to be concealed; a secret stratagem. [Obs.]",
  "cocciferous - Bearing or producing berries; bacciferous; as, cocciferrous trees or plants.",
  "monodrame - A drama acted, or intended to be acted, by a single person.",
  "imitancy - Tendency to imitation. [R.] Carlyle.",
  "landreeve - A subordinate officer on an extensive estate, who acts as an assistant to the steward.",
  "camper - One who lodges temporarily in a hut or camp.",
  "scient - Knowing; skillful. [Obs.] Cockeram.",
  "subtranslucent - Not perfectly translucent.",
  "hippocampal - Of or pertaining to the hippocampus.",
  "signeted - Stamped or marked with a signet.",
  "gallature - The tread, treadle, or chalasa of an egg.",
  "glossarial - Of or pertaining to glosses or to a glossary; containing a glossary.",
  "five-leaved - Having five leaflets, as the Virginia creeper.",
  "enervous - Lacking nerve or force; enervated. [R.]",
  "forenotice - Notice or information of an event before it happens; forewarning. [R.] Rymer.",
  "amblygon - An obtuse-angled figure, esp. and obtuse-angled triangle. [Obs.]",
  "supportress - A female supporter. [R.] You are my gracious patroness and supportress. Massinger.",
  "crusted - Incrusted; covered with, or containing, crust; as, old, crusted port wine.",
  "combattant - In the position of fighting; -- said of two lions set face to face, each rampant.",
  "petiolule - A small petiole, or the petiole of a leaflet.",
  "tubulate - Tubular; tubulated; tubulous.",
  "diapasm - Powdered aromatic herbs, sometimes made into little balls and strung together. [Obs.]",
  "seminate - To sow; to spread; to propagate. [R.] Waterhouse.",
  "vinic - Of or pertaining to wine; as, vinic alcohol.",
  "dreinte - p. p. of Drench to drown. [Obs.] Chaucer.",
  "ectad - Toward the outside or surface; -- opposed to entad. B. G. Wilder.",
  "coition - A coming together; sexual intercourse; copulation. Grew.",
  "spired - Having a spire; being in the form of a spire; as, a spired steeple. Mason.",
  "warmthless - Being without warmth; not communicating warmth; cold. [R.] Coleridge.",
  "febrifacient - Febrific. Dunglison. -- n.  That which causes fever. Beddoes.",
  "faugh - An exclamation of contempt, disgust, or abhorrence.",
  "verditure - The faintest and palest green.",
  "bald-faced - Having a white face or a white mark on the face, as a stag.",
  "impetratory - Containing or expressing entreaty. [Obs.] Jer. Taylor.",
  "self-reproaching - Reproaching one's self. -- Self`-re*proach\"ing*ly, adv.",
  "emissitious - Looking, or narrowly examining; prying. [Obs.] \"Those emissitious eyes.\" Bp. Hall.",
  "illy - Etym: [A word not fully approved, but sometimes used for the adverb ill.]",
  "stilliform - Having the form of a drop. Owen.",
  "flare-up - A sudden burst of anger or passion; an angry dispute. [Colloq.]",
  "accosted - Supported on both sides by other charges; also, side by side.",
  "tureenful - As much as a tureen can hold; enough to fill a tureen.",
  "theophanic - Of or pertaining to a theopany; appearing to man, as a god.",
  "dispunishable - Without penal restraint; not punishable. [R.] Swift.",
  "reconvertible - Capable of being reconverted; convertible again to the original form or condition.",
  "foot candle - The amount of illumination produced by a standard candle at a distance of one foot.",
  "cristallology - The science of the crystalline structure of inorganic bodies.",
  "homager - One who does homage, or holds land of another by homage; a vassal. Bacon.",
  "concreteness - The quality of being concrete.",
  "umble pie - A pie made of umbles. See To eat humble pie, under Humble.",
  "quadrel - 1. A square piece of turf or peat. [Prov. Eng.] 2. A square brick, tile, or the like.",
  "plumiliform - Having the of a plume or feather. [R.]",
  "sickleman - One who uses a sickle; a reaper. You sunburned sicklemen, of August weary. Shak.",
  "ultramontanist - One who upholds ultramontanism.",
  "bufo - A genus of Amphibia including various species of toads.",
  "untemper - To deprive of temper, or of the proper degree of temper; to make soft.",
  "leasy - Flimsy; vague; deceptive. [Obs.] Ascham.",
  "acoustically - In relation to sound or to hearing. Tyndall.",
  "storer - One who lays up or forms a store.",
  "consortable - Suitable for association or companionship. [Obs.] Sir H. Wotton.",
  "engraff - To graft; to fix deeply. [Obs.]",
  "earthfork - A pronged fork for turning up the earth.",
  "fastener - One who, or that which, makes fast or firm.",
  "hypoplastron - The third lateral plate in the plastron of turtles; -- called also hyposternum.",
  "aston - To stun; to astonish; to stupefy. [Obs.] Chaucer.",
  "ametabolous - Not undergoing any metamorphosis; as, ametabolic insects.",
  "byzant - A gold coin, so called from being coined at Byzantium. See Bezant.",
  "litholatry - The worship of a stone or stones.",
  "puseyistic - Of or pertaining to Puseyism.",
  "tumulous - Full of small hills or mounds; hilly; tumulose. [R.] Bailey.",
  "frequentation - The act or habit of frequenting or visiting often; resort. Chesterfield.",
  "unnecessity - The state of being unnecessary; something unnecessary. [Obs.]",
  "subingression - Secret entrance. [R.] Boyle.",
  "ichnological - Of or pertaining to ichnology.",
  "limbous - With slightly overlapping borders; -- said of a suture.",
  "hegemonic - Leading; controlling; ruling; predominant. \"Princelike and hegemonical.\" Fotherby.",
  "psilosopher - A superficial or narrow pretender to philosophy; a sham philosopher.",
  "bespawl - To daub, soil, or make foul with spawl or spittle. [Obs.] Milton.",
  "centumvirate - The office of a centumvir, or of the centumviri.",
  "laniariform - Shaped like a laniary, or canine, tooth. Owen.",
  "water poa - Meadow reed grass. See under Reed.",
  "appertainment - That which appertains to a person; an appurtenance. [Obs. or R.] Shak.",
  "gyratory - Moving in a circle, or spirally; revolving; whirling around.",
  "mutessarifat - In Turkey, a sanjak whose head is a mutessarif.",
  "carnalism - The state of being carnal; carnality; sensualism. [R.]",
  "perimorph - A crystal of one species inclosing one of another species. See Endomorph.",
  "innutrition - Want of nutrition; failure of nourishment. E. Darwin.",
  "nickar nut - Same as Nicker nut, Nicker tree.",
  "carelessness - The quality or state of being careless; heedlessness; negligenece; inattention.",
  "oryctology - 1. An old name for paleontology. 2. An old name for mineralogy and geology.",
  "fissural - Pertaining to a fissure or fissures; as, the fissural pattern of a brain.",
  "conscienced - Having a conscience. [R.] \"Soft-conscienced men.\" Shak.",
  "signiorship - State or position of a signior.",
  "volta-electrometer - An instrument for the exact measurement of electric currents.",
  "slither - To slide; to glide. [Prov. Eng.]",
  "donator - One who makes a gift; a donor; a giver.",
  "spender - One who spends; esp., one who spends lavishly; a prodigal; a spendthrift.",
  "adjectional - Pertaining to adjection; that is, or may be, annexed. [R.] Earle.",
  "tosspot - A toper; one habitually given to strong drink; a drunkard. Shak.",
  "disedify - To fail of edifying; to injure. [R.]",
  "setose - Thickly set with bristles or bristly hairs.",
  "subscribable - Capable of being subscribed. [R.]",
  "socome - A custom of tenants to grind corn at the lord's mill. Cowell.",
  "nonelect - A person or persons not elected, or chosen, to salvation.",
  "valency - (a) See Valence. (b) A unit of combining power; a so-called bond of affinity.",
  "nutbreaker - (a) The European nuthatch. (b) The nutcracker.",
  "dopplerite - A brownish black native hydrocarbon occurring in elastic or jellylike masses.",
  "esquisse - The first sketch of a picture or model of a statue.",
  "chuffy - 1. Fat or puffed out in the cheeks. 2. Rough; clownish; surly.",
  "torch race - A race by men carrying torches, as in ancient Greece.",
  "abreuvoir - The joint or interstice between stones, to be filled with mortar. Gwilt.",
  "ahold - Near the wind; as, to lay a ship ahold. [Obs.] Shak.",
  "fioriture - Little flowers of ornament introduced into a melody by a singer or player.",
  "palindromic - Of, pertaining to, or like, a palindrome.",
  "sea ape - (a) The thrasher shark. (b) The sea otter.",
  "graniferous - Bearing grain, or seeds like grain. Humble.",
  "corrodiate - To eat away by degrees; to corrode. [Obs.] Sandys.",
  "germinant - Sprouting; sending forth germs or buds.",
  "mesothoracic - Of or pertaining to the mesothorax.",
  "remittal - A remitting; a giving up; surrender; as, the remittal of the first fruits. Swift.",
  "sergeantry - See Sergeanty. [R.] [Written also serjeantry.]",
  "prefixion - The act of prefixing. [R.] Bailey.",
  "mudwall - The European bee-eater. See Bee-eater. [Written also modwall.]",
  "ceremonialness - Quality of being ceremonial.",
  "nonaged - Having the quality of nonage; being a minor; immature. W. Browne.",
  "molendinarious - Resembling the sails of a windmill.",
  "turtler - One who catches turtles or tortoises. \"The Jamaica turtlers.\" Dampier.",
  "terreity - Quality of being earthy; earthiness. [Obs.] B. Jonson.",
  "diapase - Same as Diapason. [Obs.] A tuneful diapase of pleasures. Spenser.",
  "multipotent - Having manifold power, or power to do many things. \"Jove multipotent.\" Shak.",
  "flunkydom - The place or region of flunkies. C. Kingsley.",
  "intercepter - One who, or that which, intercepts. Shak.",
  "pumicate - To make smooth with pumice. [R.]",
  "myogram - See Muscle curve, under Muscle.",
  "mitriform - Having the form of a miter, or a peaked cap; as, a mitriform calyptra. Gray.",
  "jubbeh - A long outer garment worn by both sexes of Mohammedans of the better class.",
  "diphthongization - The act of changing into a diphthong. H. Sweet.",
  "pokebag - The European long-tailed titmouse; -- called also poke-pudding. [Prov. Eng.]",
  "auriculars - A circle of feathers surrounding the opening of the ear of birds.",
  "lovee - One who is loved. [Humorous] \"The lover and lovee.\" Richardson.",
  "neologically - , adv. In a neological manner.",
  "locusta - The spikelet or flower cluster of grasses. Gray.",
  "conchitic - Composed of shells; containing many shells.",
  "headmost - Most advanced; most forward; as, the headmost ship in a fleet.",
  "capitellate - Having a very small knoblike termination, or collected into minute capitula.",
  "hook-nosed - Having a hooked or aquiline nose. Shak.",
  "kine - Cows. \"A herd of fifty or sixty kine.\" Milton.",
  "star-bowlines - The men in the starboard watch. [Obs.] R. H. Dana, Jr.",
  "hyponasty - Downward convexity, or convexity of the inferior surface.",
  "circumferential - Pertaining to the circumference; encompassing; encircling; circuitous. Parkhurst.",
  "durity - 1. Hardness; firmness. Sir T. Browne. 2. Harshness; cruelty. Cockeram.",
  "counter-courant - Running in opposite directions; -- said of animals borne in a coast of arms.",
  "ratiocinate - To reason, esp. deductively; to offer reason or argument.",
  "pennage - Feathery covering; plumage. [Obs.] Holland.",
  "spondee - A poetic foot of two long syllables, as in the Latin word leges.",
  "adaunt - To daunt; to subdue; to mitigate. [Obs.] Skelton.",
  "bayardly - Blind; stupid. [Obs.] \"A formal and bayardly round of duties.\" Goodman.",
  "aurigraphy - The art of writing with or in gold.",
  "fibroma - A tumor consisting mainly of fibrous tissue, or of same modification of such tissue.",
  "dispositioned - Having (such) a disposition; -- used in compounds; as, well- dispositioned.",
  "self-uned - One with itself; separate from others. [Obs.] Sylvester.",
  "groined - Built with groins; as, a groined ceiling; a groined vault.",
  "myriophyllous - Having an indefinitely great or countless number of leaves.",
  "logged - Made slow and heavy in movement; water-logged. Beaconsfield.",
  "glabriate - To make smooth, plain, or bare. [Obs.]",
  "unsufficiency - Insufficiency. [Obs.] Hooker.",
  "fireproof - Proof against fire; incombustible.",
  "arrogative - Making undue claims and pretension; prone to arrogance. [R.] Dr. H. More.",
  "tinctorial - Of or relating to color or colors; imparting a color; as, tinctorial matter. Ure.",
  "weleful - Producing prosperity or happiness; blessed. [Obs.] Chaucer.",
  "zoophaga - An artificial group comprising various carnivorous and insectivorous animals.",
  "lutheranism - The doctrines taught by Luther or held by the Lutheran Church.",
  "tumidity - The quality or state of being tumid.",
  "sedentariness - Quality of being sedentary.",
  "paramagnetism - Magnetism, as opposed to diamagnetism. Faraday.",
  "disintricate - To disentangle. [R.] \"To disintricate the question.\" Sir W. Hamilton.",
  "dragoman - An interpreter; -- so called in the Levant and other parts of the East.",
  "frontage - The front part of an edifice or lot; extent of front.",
  "planetule - A little planet. [R.] Conybeare.",
  "zeuglodont - Any species of Zeuglodonta.",
  "cartoonist - One skilled in drawing cartoons.",
  "disquisitional - Pertaining to disquisition; of the nature of disquisition.",
  "galei - That division of elasmobranch fishes which includes the sharks.",
  "uncharm - To release from a charm, fascination, or secret power; to disenchant. Beau. & Fl.",
  "hackee - The chipmunk; also, the chickaree or red squirrel. [U.S.]",
  "appropinquity - Nearness; propinquity. [R.] J. Gregory.",
  "exsolution - Relaxation. [R.] Richardson (Dict. ).",
  "circumferentially - So as to surround or encircle.",
  "regnancy - The condition or quality of being regnant; sovereignty; rule. Coleridge.",
  "lieger - A resident ambassador. [Obs.] See Leger. Denham.",
  "caimacam - The governor of a sanjak or district in Turkey.",
  "pari- - A combining form signifying equal; as, paridigitate, paripinnate.",
  "cardiometry - Measurement of the heart, as by percussion or auscultation.",
  "anatreptic - Overthrowing; defeating; -- applied to Plato's refutative dialogues. Enfield.",
  "primitiveness - The quality or state of being primitive; conformity to primitive style or practice.",
  "juratory - Relating to or comprising an oath; as, juratory caution. Ayliffe.",
  "dioecism - The condition of being dioecious.",
  "questionably - In a questionable manner.",
  "formulation - The act, process, or result of formulating or reducing to a formula.",
  "refossion - The act of digging up again. [Obs.] Bp. Hall.",
  "geodesical - Of or pertaining to geodetic.",
  "sensist - One who, in philosophy, holds to sensism.",
  "englishwoman - Fem. of Englishman. Shak.",
  "hogger - A stocking without a foot, worn by coal miners at work.",
  "jezebel - A bold, vicious woman; a termagant. Spectator.",
  "tremella - A genus of gelatinous fungi found in moist grounds.",
  "make-belief - A feigning to believe; make believe. J. H. Newman.",
  "unprinciple - To destroy the moral principles of. [R.]",
  "interpetiolar - Being between petioles. Cf. Intrapetiolar.",
  "editorship - The office or charge of an editor; care and superintendence of a publication.",
  "loy - A long, narrow spade for stony lands.",
  "noyful - Full of annoyance. [Obs.] Chaucer.",
  "emissaryship - The office of an emissary.",
  "expressionless - Destitute of expression.",
  "humect - To moisten; to wet. [Obs.] Howell.",
  "dandyism - The manners and dress of a dandy; foppishness. Byron.",
  "osteocope - Pain in the bones; a violent fixed pain in any part of a bone. -- Os`te*o*cop\"ic, a.",
  "foreconceive - To preconceive; to imagine beforehand. [Obs.] Bacon.",
  "angulated - Having angles or corners; angled; as, angulate leaves.",
  "factioner - One of a faction. Abp. Bancroft.",
  "soritical - Of or pertaining to a sorites; resembling a sorites.",
  "peafowl - The peacock or peahen; any species of Pavo.",
  "shoggle - To joggle. [Obs. or Prov. Eng. & Scot.] Pegge.",
  "incultivation - Want of cultivation. [Obs.] Berington.",
  "sectionality - The state or quality of being sectional; sectionalism.",
  "pavonian - Of or pertaining to a peacock. [R.] Southey.",
  "androides - A machine or automaton in the form of a human being.",
  "osmate - A salt of osmic acid. [Formerly written also osmiate.]",
  "unparched - Dried up; withered by heat. [Obs.] \"My tongue . . . unparched.\" Crashaw.",
  "self-worship - The idolizing of one's self; immoderate self-conceit.",
  "apartness - The quality of standing apart.",
  "lacteally - Milkily; in the manner of milk.",
  "campestral - Relating to an open fields; drowing in a field; growing in a field, or open ground.",
  "badgerer - 1. One who badgers. 2. A kind of dog used in badger baiting.",
  "diacatholicon - A universal remedy; -- name formerly to a purgative electuary.",
  "obscurely - In an obscure manner. Milton.",
  "cretinous - Having the characteristics of a cretin. \"Cretinous stupefaction.\" Ruskin.",
  "incumbrous - Cumbersome; troublesome. [Written also encombrous.] [Obs.] Chaucer.",
  "icelander - A native, or one of the Scandinavian people, of Iceland.",
  "percomorphi - A division of fishes including the perches and related kinds.",
  "quillet - Subtilty; nicety; quibble. \"Nice, sharp quillets of the law.\" Shak.",
  "unplausive - Not approving; disapproving. [Obs.] Shak.",
  "beclap - To catch; to grasp; to insnare. [Obs.] Chaucer.",
  "noncondensible - Not condensible; incapable of being liquefied; -- said of gases.",
  "white slaving - The action of one who procures or holds a woman or women for unwilling prostitution.",
  "misentry - An erroneous entry or charge, as of an account.",
  "transfretation - The act of passing over a strait or narrow sea. [Obs.] Sir J. Davies.",
  "blushet - A modest girl. [Obs.] B. Jonson.",
  "tephramancy - Divination by the ashes of the altar on which a victim had been consumed in sacrifice.",
  "oxygon - A triangle having three acute angles.",
  "satyriasis - Immoderate venereal appetite in the male. Quain.",
  "illecebrous - Alluring; attractive; enticing. [Obs.] Sir T. Elyot.",
  "copsy - Characterized by copses. \"Copsy villages.\" \"Copsy banks.\" J. Dyer.",
  "antiperistatic - Pertaining to antiperistasis.",
  "gauger - One who gauges; an officer whose business it is to ascertain the contents of casks.",
  "procreative - Having the power to beget; generative. Sir M. Hale.",
  "extraordinarily - In an extraordinary manner or degree.",
  "ornithoscopy - Observation of birds and their habits. [R.] De Quincey.",
  "telfordize - To furnish (a road) with a telford pavement.",
  "exsuscitation - A stirring up; a rousing. [Obs.] Hallywell.",
  "camphene - One of a series of substances C10H16, resembling camphor, regarded as modified terpenes.",
  "eminency - State of being eminent; eminence. \"Eminency of estate.\" Tillotson.",
  "commeasure - To be commensurate with; to equal. Tennyson.",
  "ignote - Unknown. [Obs.] Sir E. Sandys. -- n.  One who is unknown. Bp. Hacket.",
  "laterad - Toward the side; away from the mesial plane; -- opposed to mesiad.",
  "krakowiak - A lively Polish dance. See Cracovienne.",
  "diatomic - (a) Containing two atoms. (b) Having two replaceable atoms or radicals.",
  "othergates - In another manner. [Obs.] He would have tickled you othergates. Shak.",
  "numismatography - A treatise on, or description of, coins and medals.",
  "endosmometric - Pertaining to, or designed for, the measurement of endosmotic action.",
  "uncart - To take from, or set free from, a cart; to unload.",
  "recruitment - The act or process of recruiting; especially, the enlistment of men for an army.",
  "haematinometric - Same as Hematinometric.",
  "monamine - A basic compound containing one amido group; as, methyl amine is a monamine.",
  "yester-evening - The evening of yesterday; the evening last past.",
  "spleenless - Having no spleen; hence, kind; gentle; mild. [Obs.] Chapman.",
  "actinostome - The mouth or anterior opening of a coelenterate animal.",
  "conjointness - The qquality of being conjoint.",
  "puncturation - The act or process of puncturing. See Acupuncture.",
  "overharden - To harden too much; to make too hard. Boyle.",
  "metacinnabarite - Sulphide of mercury in isometric form and black in color.",
  "japannish - After the manner of the Japanese; resembling japanned articles. Carlyle.",
  "brushy - Resembling a brush; shaggy; rough.",
  "forswornness - State of being forsworn. [R.]",
  "prothoracic - Of or pertaining to the prothorax.",
  "midmost - Middle; middlemost. Ere night's midmost, stillest hour was past. Byron.",
  "barbellulate - Barbellate with diminutive hairs or barbs.",
  "tylopoda - A tribe of ungulates comprising the camels.",
  "disusage - Gradual cessation of use or custom; neglect of use; disuse. [R.] Hooker.",
  "separatical - Of or pertaining to separatism in religion; schismatical. [R.] Dr. T. Dwight.",
  "ploughtail - The hind part or handle of a plow.",
  "undulationist - One who advocates the undulatory theory of light. Whewell.",
  "indeficiency - The state or quality of not being deficient. [Obs.] Strype.",
  "yachting - Sailing for pleasure in a yacht.",
  "doughfaceism - The character of a doughface; truckling pliability.",
  "squint-eye - An eye that squints. Spenser.",
  "norlander - A northener; a person from the north country.",
  "rangement - Arrangement. [Obs.] Waterland.",
  "lion-hearted - Very brave; brave and magnanimous. Sir W. Scott.",
  "isosporic - Producing but one kind of spore, as the ferns and Equiseta. Cf. Heterosporic.",
  "enepidermic - Applied to the skin without friction; -- said of medicines.",
  "stylohyoid - Of or pertaining to the styloid process and the hyoid bone.",
  "preterlegal - Exceeding the limits of law. [R.]",
  "inventibleness - Quality of being inventible.",
  "phytochemistry - Chemistry in its relation to vegetable bodies; vegetable chemistry. R. Hunt.",
  "wearable - Capable of being worn; suitable to be worn.",
  "delibation - Act of tasting; a slight trial. [Obs.] Berkeley.",
  "pomposity - The quality or state of being pompous; pompousness. Thackeray.",
  "agitato - Sung or played in a restless, hurried, and spasmodic manner.",
  "validly - In a valid manner; so as to be valid.",
  "halotrichite - An iron alum occurring in silky fibrous aggregates of a yellowish white color.",
  "openness - The quality or state of being open.",
  "anthozoan - Pertaining to the Anthozoa. -- n.  One of the Anthozoa.",
  "magnetization - The act of magnetizing, or the state of being magnetized.",
  "murth - Plenty; abundance. [Obs. or Prov. Eng.]",
  "exhausting - Producing exhaustion; as, exhausting labors. -- Ex*haust\"ing, adv.",
  "mansionary - Resident; residentiary; as, mansionary canons.",
  "genesial - Of or relating to generation.",
  "wheel-worn - Worn by the action of wheels; as, a wheel-worn road.",
  "prosocoele - The entire cavity of the prosencephalon. B. G. Wilder.",
  "nounize - To change (an adjective, verb, etc.) into a noun. Earle.",
  "semi crustaceous - Half crustaceous; partially crustaceous.",
  "sea toad - (a) A sculpin. (b) A toadfish. (c) The angler.",
  "erythrean - Red in color. \"The erythrean main.\" Milton.",
  "overprovoke - To provoke excessively. Bp. Hall.",
  "straw-cutter - An instrument to cut straw for fodder.",
  "impuration - Defilement; obscuration. [Obs.] Bp. Hall.",
  "uglify - To disfigure; to make ugly. [R.] Mad. D'Arblay.",
  "langridge - See Langrage. Note: [Sometimes compounded with shot.]",
  "tensioned - Extended or drawn out; subjected to tension. \"A highly tensioned string.\" Tyndall.",
  "cultus cod - See Cod, and Buffalo cod, under Buffalo.",
  "exanguious - Bloodless. [Obs.] See Exsanguious. Sir T. Browne.",
  "imaginer - One who forms ideas or conceptions; one who contrives. Bacon.",
  "subcompressed - Not fully compressed; partially or somewhat compressed.",
  "stethoscopy - The art or process of examination by the stethoscope.",
  "amplificate - To amplify. [Obs.] Bailey.",
  "pedotrophy - The art of nourishing children properly.",
  "wanderment - The act of wandering, or roaming. [Obs.] Bp. Hall.",
  "duettino - A duet of short extent and concise form.",
  "greffier - A registrar or recorder; a notary. [Obs.] Bp. Hall.",
  "insusceptive - Not susceptive or susceptible. [R.] Rambler.",
  "interfollicular - Between follicles; as, the interfollicular septa in a lymphatic gland.",
  "leeway - The lateral movement of a ship to the leeward of her course; drift.",
  "pardoner - 1. One who pardons. Shak. 2. A seller of indulgences. [Obs.] Chaucer.",
  "lanate - Wooly; covered with fine long hair, or hairlike filaments.",
  "indenization - The act of naturalizing; endenization. [R.] Evelyn.",
  "reclusive - Affording retirement from society. \"Some reclusive and religious life.\" Shak.",
  "cassonade - Raw sugar; sugar not refined. Mc Elrath.",
  "temulentive - Somewhat temulent; addicted to drink. [R.] R. Junius.",
  "sweigh - Sway; movement. [Obs.] Chaucer.",
  "bibliographer - One who writes, or is versed in, bibliography.",
  "detergency - A cleansing quality or power. De Foe.",
  "sternmost - Farthest in the rear; farthest astern; as, the sternmost ship in a convoy.",
  "obumbration - Act of darkening or obscuring. [R.] Sir T. More.",
  "semaphoric - Of or pertaining to a semaphore, or semaphores; telegraphic.",
  "verbalist - A literal adherent to, or a minute critic of, words; a literalist.",
  "hedgeborn - Born under a hedge; of low birth. Shak.",
  "endo- - A combining form signifying within; as, endocarp, endogen, endocuneiform, endaspidean.",
  "psychopomp - A leader or guide of souls . J. Fiske.",
  "pentecoster - An officer in the Spartan army commanding fifty men. Mitford.",
  "nicagua - The laughing falcon. See under laughing.",
  "pauperize - To reduce to pauperism; as, to pauperize the peasantry.",
  "pizzle - The penis; -- so called in some animals, as the bull. Shak.",
  "tricennarious - Of or pertaining to thirty years; tricennial. [R.]",
  "formularistic - Pertaining to, or exhibiting, formularization. Emerson.",
  "puppetish - Resembling a puppet in appearance or action; of the nature of a puppet.",
  "cordwainer - A worker in cordwain, or cordovan leather; a shoemaker. [Archaic.]",
  "vaginati - A tribe of birds comprising the sheathbills.",
  "flagstaff - A staff on which a flag is hoisted.",
  "timbering - The act of furnishing with timber; also, timbers, collectively; timberwork; timber.",
  "zincky - , Pertaining to zinc, or having its appearance. [Written also zinky.]",
  "laminal - In, or consisting of, thin plates or layers; having the form of a thin plate or lamina.",
  "undersheriffry - Undershrievalty. [Obs.]",
  "ectethmoid - External to the ethmoid; prefrontal.",
  "hething - Contempt; scorn. [Obs.] Chaucer.",
  "tangun - A piebald variety of the horse, native of Thibet.",
  "abodement - A foreboding; an omen. [Obs.] \"Abodements must not now affright us.\" Shak.",
  "mockingstock - A butt of sport; an object of derision. [R.]",
  "brigose - Contentious; quarrelsome. [Obs.] Puller.",
  "jentling - A fish of the genus Leuciscus; the blue chub of the Danube.",
  "combless - Without a comb or crest; as, a combless ceck.",
  "cauf - A chest with holes for keeping fish alive in water. Philips.",
  "reportorial - Of or pertaining to a reporter or reporters; as, the reportorial staff of a newspaper.",
  "strangler - One who, or that which, strangles. \"The very strangler of their amity.\" Shak.",
  "sodaic - Pertaining to, or containing, soda. \"Sodaic powder.\" Ure.",
  "philogyny - Fondness for women; uxoriousness; -- opposed to Ant: misogyny. [R.] Byron.",
  "effray - To frighten; to scare. [Obs.] Spenser.",
  "idio- - . A combining form from the Greek private, personal, peculiar, distinct.",
  "zwanziger - Am Austrian silver coin equivalent to 20 kreutzers, or about 10 cents.",
  "malmbrick - A kind of brick of a light brown or yellowish color, made of sand, clay, and chalk.",
  "epipolic - Producing, or relating to, epipolism or fluorescence. [R.]",
  "lepidote - Having a coat of scurfy scales, as the leaves of the oleaster.",
  "eccaleobion - A contrivance for hatching eggs by artificial heat.",
  "unbaned - Wanting a band or string; unfastened. [Obs.] Shak.",
  "nondeposition - A failure to deposit or throw down.",
  "barefacedness - The quality of being barefaced; shamelessness; assurance; audaciousness.",
  "laicality - The state or quality of being laic; the state or condition of a layman.",
  "santees - One of the seven confederated tribes of Indians belonging to the Sioux, or Dakotas.",
  "usherless - Destitute of an usher. Marston.",
  "superexcellence - Superior excellence; extraordinary excellence.",
  "coercible - Capable of being coerced. -- Co*er\"ci*ble*ness, n.",
  "chancellorship - The office of a chancellor; the time during which one is chancellor.",
  "racemiferous - Bearing racemes, as the currant.",
  "pansied - Covered or adorned with pansies. \"The pansied grounds.\" Darwin.",
  "lifetime - The time that life continues.",
  "meute - A cage for hawks; a mew. See 4th Mew, 1. Milman.",
  "inhalation - The act of inhaling; also, that which is inhaled.",
  "missuggestion - Wrong or evil suggestion. [Obs.] Bp. Hall.",
  "explainer - One who explains; an expounder or expositor; a commentator; an interpreter.",
  "liver-grown - Having an enlarged liver. Dunglison.",
  "attemptable - Capable of being attempted, tried, or attacked. Shak.",
  "protectoral - Of or pertaining to a protector; protectorial; as, protectoral power.",
  "subdean - An under dean; the deputy or substitute of a dean. Ayliffe.",
  "heliacally - In a heliacal manner. De Quincey.",
  "euchrone - A substance obtained from euchroic acid. See Eychroic.",
  "abdominalia - A group of cirripeds having abdominal appendages.",
  "toshred - To cut into shreads or pieces. [Obs.] Chaucer.",
  "rhizophaga - A division of marsupials. The wombat is the type.",
  "wellwisher - One who wishes another well; one who is benevolently or friendlily inclined.",
  "hortensial - Fit for a garden. [Obs.] Evelyn.",
  "tumulter - A maker of tumults. [Obs.] He severely punished the tumulters. Milton.",
  "apocalyptically - By revelation; in an apocalyptic manner.",
  "intelligibility - The quality or state of being intelligible; clearness; perspicuity; definiteness.",
  "cogitabund - Full of thought; thoughtful. [R.] Leigh Hunt.",
  "disdained - Disdainful. [Obs.] Revenge the jeering and disdained contempt Of this proud king. Shak.",
  "incorporealist - One who believes in incorporealism. Cudworth.",
  "deflectionize - To free from inflections. Deflectionized languages are said to be analytic. Earle.",
  "psitta-co-fulvine - A yellow pigment found in the feathers of certain parrots.",
  "chappy - Full of chaps; cleft; gaping; open.",
  "alphabetarian - A learner of the alphabet; an abecedarian. Abp. Sancroft.",
  "polyembryonate - Consisting of, or having, several embryos; polyembryonic.",
  "macropteres - A division of birds; the Longipennes.",
  "coleopterist - One versed in the study of the Coleoptera.",
  "folk lore - . Tales, legends, or superstitions long current among the people. Trench.",
  "syndesmosis - An articulation formed by means of ligaments.",
  "diminute - Small; diminished; diminutive. [Obs.] Jer. Taylor.",
  "recipiency - The quality or state of being recipient; a receiving; reception; receptiveness.",
  "nost - Wottest not; knowest not. [Obs.] Chaucer.",
  "decubitus - An attitude assumed in lying down; as, the dorsal decubitus.",
  "dockyard - A yard or storage place for all sorts of naval stores and timber for shipbuilding.",
  "drovy - Turbid; muddy; filthy. [Obs.] Chaucer.",
  "libratory - Balancing; moving like a balance, as it tends to an equipoise or level.",
  "styliform - Having the form of, or resembling, a style, pin, or pen; styloid.",
  "trispermous - Containing three seeds; three-seeded; as, a trispermous capsule.",
  "podrida - A miscellaneous dish of meats. See Olla-podrida.",
  "reapportionment - A second or a new apportionment.",
  "disquietly - In a disquiet manner; uneasily; as, he rested disquietly that night. [R.] Wiseman.",
  "ferro- - A prefix, or combining form, indicating ferrous iron as an ingredient; as, ferrocyanide.",
  "dismastment - The act of dismasting; the state of being dismasted. [R.] Marshall.",
  "cryptogam - A plant belonging to the Cryptogamia. Henslow.",
  "sauce-alone - Jack-by-the-hedge. See under Jack.",
  "refluence - The quality of being refluent; a flowing back.",
  "praise-meeting - A religious service mainly in song. [Local, U. S.]",
  "remediable - Capable of being remedied or cured. -- Re*me\"di*a*ble*ness, n. -Re*me\"di*a*bly, adv.",
  "convincer - One who, or that which, convinces; one who wins over by proof.",
  "wreckful - Causing wreck; involving ruin; destructive. \"By wreckful wind.\" Spenser.",
  "flurried - Agitated; excited. -- Flur\"ried*ly adv.",
  "doucet - 1. A custard. [Obs.] 2. A dowcet, or deep's testicle.",
  "cotyla - A cuplike cavity or organ. Same as Acetabulum.",
  "revolutioner - One who is engaged in effecting a revolution; a revolutionist. Smollett.",
  "misgovern - To govern ill; as, to misgovern a country. Knolles.",
  "heliometric - Of or pertaining to the heliometer, or to heliometry.",
  "splendidly - In a splendid manner; magnificently.",
  "tolt - A writ by which a cause pending in a court baron was removed into a country court. Cowell.",
  "tubuliform - Having the form of a small tube.",
  "uraeum - The posterior half of an animal.",
  "pugilistic - Of or pertaining to pugillism.",
  "inauguratory - Suitable for, or pertaining to, inauguration. Johnson.",
  "scissor - To cut with scissors or shears; to prepare with the aid of scissors. Massinger.",
  "staminal - Of or pertaining to stamens or stamina; consisting in stamens.",
  "debaucher - One who debauches or corrupts others; especially, a seducer to lewdness.",
  "butter-fingered - Apt to let things fall, or to let them slip away; slippery; careless.",
  "immomentous - Not momentous; unimportant; insignificant. [R.] A. Seward.",
  "ischiopodite - The third joint of the typical appendages of Crustacea.",
  "statistic - Of or pertaining to statistics; as, statistical knowledge, statistical tabulation.",
  "sheeny - Bright; shining; radiant; sheen. \"A sheeny summer morn.\" Tennyson.",
  "foothill - A low hill at the foot of highe",
  "gibfish - The male of the salmon. [Prov. Eng.] Wright.",
  "convictible - Capable of being convicted. [R.] Ash.",
  "reit - Sedge; seaweed. [Obs. or Prov. Eng.]",
  "hypostatically - In a hypostatic manner.",
  "ruminative - Inclined to, or engaged in, rumination or meditation.",
  "trackman - One employed on work on the track; specif., a trackwalker.",
  "pectize - To congeal; to change into a gelatinous mass. [R.] H. Spencer.",
  "savableness - Capability of being saved.",
  "orthodoxness - The quality or state of being orthodox; orthodoxy. Waterland.",
  "unchaplain - To remove from a chaplaincy.",
  "hesitant - 1. Not prompt in deciding or acting; hesitating. 2. Unready in speech. Baxter.",
  "felicitation - The act of felicitating; a wishing of joy or happiness; congratulation.",
  "machiner - One who or operates a machine; a machinist. [R.]",
  "daphnetin - A colorless crystalline substance, C9H6O4, extracted from daphnin.",
  "gallegan - A native or inhabitant of Galicia, in Spain; a Galician.",
  "elevatedness - The quality of being elevated.",
  "starchy - Consisting of starch; resembling starch; stiff; precise.",
  "boilery - A place and apparatus for boiling, as for evaporating brine in salt making.",
  "monochromic - Made, or done, with a single color; as, a monochromic picture.",
  "thanksgive - To give or dedicate in token of thanks. [Obs. or R.] Mede.",
  "tritone - A superfluous or augmented fourth. [R.]",
  "epicerastic - Lenient; assuaging. [Obs.]",
  "nasion - The middle point of the nasofrontal suture.",
  "strippet - A small stream. [Obs.] \"A little brook or strippet.\" Holinshed.",
  "uzema - A Burman measure of twelve miles.",
  "verdine - A commercial name for green aniline dye.",
  "allantoic - Pertaining to, or contained in, the allantois. Allantoic acid. (Chem.) See Allantoin.",
  "gusto - Nice or keen appreciation or enjoyment; relish; taste; fancy. Dryden.",
  "actless - Without action or spirit. [R.]",
  "cacodemon - 1. An evil spirit; a devil or demon. Shak. 2. (Med.)  The nightmare. Dunaglison.",
  "writhen - Having a twisted distorted from. A writhen staff his step unstable guides. Fairfax.",
  "lucullite - A variety of black limestone, often polished for ornamental purposes.",
  "reflexity - The state or condition of being reflected. [R.]",
  "auld - Old; as, Auld Reekie (old smoky), i. e., Edinburgh. [Scot. & Prov. Eng.]",
  "apprehensively - In an apprehensive manner; with apprehension of danger.",
  "phlegmagogue - A medicine supposed to expel phlegm.",
  "cotyledonary - Having a cotyledon; tufted; as, the cotyledonary placenta of the cow.",
  "gallow - To fright or terrify. See Gally, v. t. [Obs.] Shak.",
  "snattock - A chip; a alice. [Prov. Eng.] Gayton.",
  "impressor - One who, or that which, impresses. Boyle.",
  "hot-mouthed - Headstrong. That hot-mouthed beast that bears against the curb. Dryden.",
  "scrawler - One who scrawls; a hasty, awkward writer.",
  "marquisate - The seigniory, dignity, or lordship of a marquis; the territory governed by a marquis.",
  "methodistic - Of or pertaining to methodists, or to the Methodists. -- Meth`o*dis\"tic*al*ly, adv.",
  "self-preservation - The preservation of one's self from destruction or injury.",
  "calendric - Of or pertaining to a calendar.",
  "antrorse - Forward or upward in direction. Gray.",
  "cordy - Of, or like, cord; having cords or cordlike parts.",
  "rosewort - (a) Roseroot. (b) Any plant nearly related to the rose. Lindley.",
  "extractiform - Having the form, appearance, or nature, of an extract.",
  "boohoe - To bawl; to cry loudly. [Low] Bartlett.",
  "loadmanage - Pilotage; skill of a pilot or loadsman. [Obs.] Chaucer.",
  "vow-fellow - One bound by the same vow as another. [R.] Shak.",
  "head-lugged - Lugged or dragged by the head. [R.] \"The head-lugged bear.\" Shak.",
  "forfeiter - One who incurs a penalty of forfeiture.",
  "pulseless - Having no pulsation; lifeless.",
  "macedonianism - The doctrines of Macedonius.",
  "gutty - Charged or sprinkled with drops.",
  "dreariness - 1. Sorrow; wretchedness. [Obs.] 2. Dismalness; gloomy solitude.",
  "ornithoidichnite - A fossil track resembling that of a bird. Hitchcock.",
  "diaphanometer - An instrument for measuring the transparency of the air.",
  "cymophanous - Having a wavy, floating light; opalescent; chatoyant.",
  "imbellic - Not warlike or martial. [Obs.] R. Junius.",
  "abaction - Stealing cattle on a large scale. [Obs.]",
  "outsweeten - To surpass in sweetness. [R.] Shak.",
  "ayah - A native nurse for children; also, a lady's maid. [India]",
  "triple-headed - Having three heads; three-headed; as, the triple-headed dog Cerberus.",
  "recureless - Incapable of cure. [Obs.] Bp. Hall.",
  "enchondroma - A cartilaginous tumor growing from the interior of a bone. Quain.",
  "chidingly - In a chiding or reproving manner.",
  "soupe-maigre - Soup made chiefly from vegetables or fish with a little butter and a few condiments.",
  "water furrow - A deep furrow for conducting water from the ground, and keeping the surface soil dry.",
  "evaporable - Capable of being converted into vapor, or dissipated by evaporation.",
  "ichnographic - Of or pertaining to ichonography; describing a ground plot.",
  "atazir - The influence of a star upon other stars or upon men. [Obs.] Chaucer.",
  "subsextuple - Having the ratio of one to six; as, a subsextuple proportion. Bp. Wilkins.",
  "supra-ethmoid - Above, or on the dorsal side of, the ethmoid bone or cartilage.",
  "ralph - A name sometimes given to the raven.",
  "vedantist - One versed in the doctrines of the Vedantas.",
  "infiltrative - Of or pertaining to infiltration. Kane.",
  "-morphous - A combining form denoting form, shape; as, isomorphous.",
  "appendicular - Relating to an appendicle; appendiculate. [R.]",
  "centistere - The hundredth part of a stere, equal to .353 cubic feet.",
  "kat - An Arabian shrub Catha edulis) the leaves of which are used as tea by the Arabs.",
  "stratographical - Of or pertaining to stratography.",
  "obequitate - To ride about. [Obs.] -- Ob*eq`ui*ta\"tion, n. [Obs.] Cockerman.",
  "fumarine - An alkaloid extracted from fumitory, as a white crystalline substance.",
  "bellycheat - An apron or covering for the front of the person. [Obs.] Beau. & Fl.",
  "prelusory - Introductory; prelusive. Bacon.",
  "expositor - One who, or that which, expounds or explains; an expounder; a commentator. Bp. Horsley.",
  "collectivist - An advocate of collectivism. -- a.  Relating to, or characteristic of, collectivism.",
  "blastodermic - Of or pertaining to the blastoderm.",
  "theophany - A manifestation of God to man by actual appearance, usually as an incarnation.",
  "ogdoastich - A poem of eight lines. [Obs.] Selden",
  "digenous - Sexually reproductive. Digenous reproduction. (Biol.) Same as Digenesis.",
  "swordplayer - A fencer; a gladiator; one who exhibits his skill in the use of the sword.",
  "phyto- - A combining form from Gr. fyto`n a plant; as, phytochemistry, phytography.",
  "pneumophora - A division of holothurians having an internal gill, or respiratory tree.",
  "prensation - The act of seizing with violence. [Obs.] Barrow .",
  "uncontroversory - Not involving controversy. [Obs.] Bp. Hall.",
  "explorement - The act of exploring; exploration. [R.] Sir T. Browne.",
  "appension - The act of appending. [Obs.]",
  "presageful - Full of presages; ominous. Dark in the glass of some presageful mood. Tennyson.",
  "suspired - Ardently desired or longed for; earnestly coveted. [Obs.] Sir H. Wotton.",
  "variolation - Inoculation with smallpox.",
  "vindemiation - The operation of gathering grapes. [Obs.] Bailey.",
  "regrede - To go back; to retrograde, as the apsis of a planet's orbit. [R.] Todhunter.",
  "circumagitate - To agitate on all sides. Jer. Taylor.",
  "chessman - A piece used in the game of chess.",
  "mopsey - 1. A moppet. 2. A slatternly, untidy woman. Halliwell.",
  "emperished - Perished; decayed. [Obs.] I deem thy brain emperished be. Spenser.",
  "panderous - , Of or relating to a pander; characterizing a pander.",
  "reduplicative - Double; formed by reduplication; reduplicate. I. Watts.",
  "lummox - A fat, ungainly, stupid person; an awkward bungler. [Law.]",
  "presumably - In a presumable manner; by, or according to, presumption.",
  "pock-broken - Broken out, or marked, with smallpox; pock-fretten.",
  "peavy - A cant hook having the end of its lever armed with a spike.",
  "pestiduct - That which conveys contagion or infection. [Obs.] Donne.",
  "spa - A spring or mineral water; -- so called from a place of this name in Belgium.",
  "imperseverant - Not persevering; fickle; thoughtless. [Obs.]",
  "syderolite - A kind of Bohemian earthenware resembling the Wedgwood ware.",
  "despisal - A despising; contempt. [R.] A despisal of religion. South.",
  "full-sailed - Having all its sails set,; hence, without restriction or reservation. Massinger.",
  "annelidan - Of or pertaining to the Annelida. -- n.  One of the Annelida.",
  "capitatim - Of so much per head; as, a capitatim tax; a capitatim grant.",
  "northwards - Toward the north, or toward a point nearer to the north than to the east or west point.",
  "alcoranic - Of or pertaining to the Koran.",
  "salter - One who makes, sells, or applies salt; one who salts meat or fish.",
  "telepolariscope - A polariscope arranged to be attached to a telescope. Lockyer.",
  "sextonry - Sextonship. [Obs.] Ld. Bernes.",
  "repleviable - Capable of being replevied.",
  "unattire - To divest of attire; to undress.",
  "prothalamium - A song in celebration of a marriage. Drayton.",
  "mullar - A die, cut in intaglio, for stamping an ornament in relief, as upon metal.",
  "napha water - A perfume distilled from orange flowers.",
  "corrosibility - Corrodibility. \"Corrosibility . . . answers corrosiveness.\" Boyle.",
  "disanimate - 1. To deprive of life. [R.] Cudworth. 2. To deprive of spirit; to dishearten. Shak.",
  "alimentally - So as to serve for nourishment or food; nourishing quality. Sir T. Browne.",
  "ingrapple - To seize; to clutch; to grapple. [Obs.] Drayton.",
  "phallism - The worship of the generative principle in nature, symbolized by the phallus.",
  "desponsory - A written pledge of marriage. Clarendon.",
  "grapery - A building or inclosure used for the cultivation of grapes.",
  "dietarian - One who lives in accordance with prescribed rules for diet; a dieter.",
  "pretendingly - As by right or title; arrogantly; presumptuously. Collier.",
  "heydeguy - A kind of country-dance or round. [Obs.] Spenser.",
  "cafeneh - A humble inn or house of rest for travelers, where coffee is sold. [Turkey]",
  "tartufe - A hypocritical devotee. See the Dictionary of Noted Names in Fiction.",
  "homodermy - Homology of the germinal layers.",
  "inglobe - To infix, as in a globe; to fix or secure firmly. [Obs.] Milton.",
  "recurvirostral - Having the beak bent upwards.",
  "garreting - Small splinters of stone inserted into the joints of coarse masonry. Weale.",
  "sightliness - The state of being sightly; comeliness; conspicuousness.",
  "trunk engine - An engine having a trunk piston, as most internal combustion engines.",
  "ventriculus - (a) One of the stomachs of certain insects. (b) The body cavity of a sponge.",
  "slopseller - One who sells slops, or ready-made clothes. See 4th Slop, 3.",
  "cometography - A description of, or a treatise concerning, comets.",
  "browspot - A rounded organ between the eyes of the frog; the interocular gland.",
  "envie - To vie; to emulate; to strive. [Obs.] Spenser.",
  "antidotary - Antidotal. -- n. Antidote; also, a book of antidotes.",
  "intermication - A shining between or among. [R.] Smart.",
  "aggrandizer - One who aggrandizes, or makes great.",
  "ohmmeter - An instrument for indicating directly resistance in ohms.",
  "squamellate - Furnished or covered with little scales; squamulose.",
  "accendibility - Capacity of being kindled, or of becoming inflamed; inflammability.",
  "endothelial - Of, or relating to, endothelium.",
  "self-interest - Private interest; the interest or advantage of one's self.",
  "spermatize - To yield seed; to emit seed, or sperm. [Obs.] Sir T. Browne.",
  "wotest - 2d pers. sing. pres. of Wit, to know. [Obs.]",
  "trifluctuation - A concurrence of three waves. [Obs.] \"A trifluctuation of evils.\" Sir T. Browne.",
  "seminality - The quality or state of being seminal. Sir T. Browne.",
  "pudic - Of or pertaining to the external organs of generation.",
  "arthromere - One of the body segments of Arthropods. See Arthrostraca. Packard.",
  "isosceles - Having two legs or sides that are equal; -- said of a triangle.",
  "vice-regal - Of or pertaining to a viceroy or viceroyalty. Macaulay.",
  "sincipital - Of or pertaining to the sinciput; being in the region of the sinciput.",
  "testone - A silver coin of Portugal, worth about sixpence sterling, or about eleven cents. Homans.",
  "jeofail - An oversight in pleading, or the acknowledgment of a mistake or oversight. Blackstone.",
  "cierge - A wax candle used in religous rites.",
  "hypaspist - A shield-bearer or armor-bearer. Mitford.",
  "hauteur - Haughty manner or spirit; haughtiness; pride; arrogance.",
  "reiteration - The act of reiterating; that which is reiterated.",
  "suboctuple - Containing one part of eight; having the ratio of one to eight. Bp. Wilkins.",
  "provable - Capable of being proved; demonstrable. -- Prov\"a*ble*ness, n. -- Prov\"a*bly, adv.",
  "entomophagan - Relating to the Entomophaga. -- n.  One of the Entomophaga.",
  "gangliac - Relating to a ganglion; ganglionic.",
  "adambulacral - Next to the ambulacra; as, the adambulacral ossicles of the starfish.",
  "tompon - An inking pad used in lithographic printing.",
  "hemiopia - A defect of vision in consequence of which a person sees but half of an object looked at.",
  "fremitus - Palpable vibration or thrill; as, the rhonchial fremitus.",
  "self-delation - Accusation of one's self. [R.] Milman.",
  "pseudonavicella - Same as Pseudonavicula.",
  "archprimate - The chief primate. Milton.",
  "conjecturer - One who conjectures. Hobbes.",
  "disguising - A masque or masquerade. [Obs.]",
  "projecture - A jutting out beyond a surface.",
  "gag law - A law or ruling prohibiting proper or free debate, as in closure. [Colloq. or Cant]",
  "lixt - 2d pers. sing. pres. of Lige, to lie, to tell lies, -- contracted for ligest. Chaucer.",
  "misreckon - To reckon wrongly; to miscalculate. Swift.",
  "miscontinuance - Discontinuance; also, continuance by undue process.",
  "apiology - The scientific or systematic study of honey bees.",
  "remittor - One who makes a remittance; a remitter.",
  "sustre - Sister. [Obs.] Chaucer. There are seven sustren, that serve truth ever. Piers Plowman.",
  "tendry - A tender; an offer. [Obs.] Heylin.",
  "jingler - One who, or that which, jingles.",
  "jaggy - Having jags; set with teeth; notched; uneven; as, jaggy teeth. Addison.",
  "instructor - One who instructs; one who imparts knowledge to another; a teacher.",
  "renaissant - Of or pertaining to the Renaissance.",
  "intervenue - Interposition. [Obs.] Sir H. Blount.",
  "extenuatory - Tending to extenuate or palliate. Croker.",
  "hypinosis - A diminution in the normal amount of fibrin present in the blood.",
  "underkeep - To keep under, or in subjection; to suppress. [Obs.] Spenser.",
  "monogamist - One who practices or upholds monogamy. Goldsmith.",
  "paromology - A concession to an adversary in order to strengthen one's own argument.",
  "bewildered - Greatly perplexed; as, a bewildered mind.",
  "disrespectability - Want of respectability. Thackeray.",
  "castellan - A goveror or warden of a castle.",
  "unsquire - To divest of the title or privilege of an esquire. Swift.",
  "bachelordom - The state of bachelorhood; the whole body of bachelors.",
  "spindle-shanked - Having long, slender legs. Addison.",
  "undergrove - A grove of shrubs or low trees under taller ones. Wordsworth.",
  "unrein - To loosen the reins of; to remove restraint from. Addison.",
  "advertiser - One who, or that which, advertises.",
  "sexangled - Having six angles; hexagonal. [R.] Dryden.",
  "transferee - The person to whom a transfer in made.",
  "turbaned - Wearing a turban. \" A malignant and a turbaned Turk.\" Shak.",
  "radiotelephone - A wireless telephone. -- Ra`di*o*te*leph\"o*ny (#), n.",
  "theurgist - One who pretends to, or is addicted to, theurgy. Hallywell.",
  "tolsey - A tollbooth; also, a merchants' meeting place, or exchange. [Obs.] Halliwell.",
  "ambrosiac - Having the qualities of ambrosia; delicious. [R.]\"Ambrosiac odors.\" B. Jonson.",
  "asymmetral - Incommensurable; also, unsymmetrical. [Obs.] D. H. More.",
  "diallel - Meeting and intersecting, as lines; not parallel; -- opposed to parallel. [Obs.] Ash.",
  "sentimentalist - One who has, or affects, sentiment or fine feeling.",
  "undersetter - One who, or that which, undersets or supports; a prop; a support; a pedestal.",
  "bachelorship - The state of being a bachelor.",
  "polygynian - Having many styles; belonging to the order Polygynia.",
  "unmartyr - To degrade from the rank of a martyr. [Obs.] Fuller.",
  "lurker - 1. One who lurks. 2. A small fishing boat. [Prov. Eng.]",
  "estrich - 1. Ostrich. [Obs.] Massinger. 2. (Com.)  The down of the ostrich. Brande & C.",
  "hoult - A piece of woodland; a small wood. [Obs.] See Holt.",
  "miscalculate - To calculate erroneously; to judge wrongly. -- Mis*cal`cu*la\"tion, n.",
  "tumefacient - Producing swelling; tumefying.",
  "bemuse - To muddle, daze, or partially stupefy, as with liquor. A parson much bemused in beer. Pope.",
  "psammite - A species of micaceous sandstone. -- Psam*mit\"ic, a.",
  "amidol - A salt of a diamino phenol, C6H3(OH)(NH2)2, used as a developer.",
  "lary - A guillemot; -- called also lavy. [Prov. Eng.]",
  "caecias - A wind from the northeast. Milton.",
  "octandrous - Of or pertaining to the Octandria; having eight distinct stamens.",
  "duddery - A place where rags are bought and kept for sale. [Eng.]",
  "systemizer - One who systemizes, or reduces to system; a systematizer.",
  "morosity - Moroseness. [R.] Jer. Taylor.",
  "disseveration - The act of disserving; disseverance. [Obs.]",
  "evil eye - . See Evil eye under Evil, a.",
  "ramigerous - Bearing branches; branched.",
  "catapeltic - Of or pertaining to a catapult.",
  "reconvene - To convene or assemble again; to call or come together again.",
  "touchable - Capable of being touched; tangible. -- Touch\"a*ble*ness, n.",
  "fly-bitten - Marked by, or as if by, the bite of flies. Shak.",
  "amianthiform - Resembling amianthus in form.",
  "norium - A supposed metal alleged to have been discovered in zircon.",
  "customable - 1. Customary. [Obs.] Sir T. More. 2. Subject to the payment of customs; dutiable.",
  "untomb - To take from the tomb; to exhume; to disinter. Fuller.",
  "ornately - In an ornate manner. Sir T. More.",
  "thumbed - 1. Having thumbs. 2. Soiled by handling.",
  "irreplevisable - Not capable of being replevied.",
  "aethiops mineral - Same as Ethiops mineral. [Obs.]",
  "stinginess - The quality or state of being stingy.",
  "illision - The act of dashing or striking against. Sir T. Browne.",
  "glariness - A dazzling luster or brilliancy.",
  "ligniferous - Yielding or producing wood.",
  "stenciler - One who paints or colors in figures by means of stencil. [Written also stenciller.]",
  "archebiosis - To origination of living matter from non-living. See Abiogenesis. Bastian.",
  "promissive - Making a promise; implying a promise; promising. [R.]",
  "cageling - A bird confined in a cage; esp. a young bird. [Poetic] Tennyson.",
  "alloo - To incite dogs by a call; to halloo. [Obs.]",
  "gastro- - A combining form from the Gr. gastrocolic, gastrocele, gastrotomy.",
  "oppugner - One who opposes or attacks; that which opposes. Selden.",
  "gamekeeper - One who has the care of game, especially in a park or preserve. Blackstone.",
  "depilate - To strip of hair; to husk. Venner.",
  "cuckoopint - A plant of the genus Arum (A. maculatum); the European wake- robin.",
  "scutelliform - 1. Scutellate. 2. (Bot.)  Having the form of a scutellum.",
  "southwestern - Of or pertaining to the southwest; southwesterly; as, to sail a southwestern course.",
  "incharitable - Uncharitable; unfeeling. [Obs.] Shak.",
  "peliom - A variety of iolite, of a smoky blue color; pelioma.",
  "sea whip - A gorgonian having a simple stem.",
  "wind-fertilized - Anemophilous; fertilized by pollen borne by the wind.",
  "oceanography - A description of the ocean.",
  "experimenter - One who makes experiments; one skilled in experiments. Faraday.",
  "hellespontine - Of or pertaining to the Hellespont. Mitford.",
  "dogate - The office or dignity of a doge.",
  "inalterability - The quality of being unalterable or unchangeable; permanence.",
  "affriended - Made friends; reconciled. [Obs.] \"Deadly foes . . . affriended.\" Spenser.",
  "inc - A Japanese measure of length equal to about two and one twelfth yards. [Written also ink.]",
  "imitational - Pertaining to, or employed in, imitation; as, imitational propensities.",
  "bo - An exclamation used to startle or frighten. [Spelt also boh and boo.]",
  "pastorling - An insignificant pastor. [R.]",
  "cornshuck - The husk covering an ear of Indian corn. [Colloq. U.S.]",
  "uni- - A prefix signifying one, once; as in uniaxial, unicellular.",
  "proke - To poke; to thrust. [Obs.] Holland.",
  "infatigable - Indefatigable. [Obs.] Daniel.",
  "benim - To take away. [Obs.] Ire . . . benimeth the man fro God. Chaucer.",
  "experimentative - Experimental; of the nature of experiment. [R.]",
  "infatuated - Overcome by some foolish passion or desire; affected by infatuation.",
  "negress - A black woman; a female negro.",
  "knotwort - A small, herbaceous, trailing plant, of the genus Illecebrum (I. verticillatum.)",
  "imbecilitate - To weaken, as to the body or the mind; to enfeeble. [R.] A. Wilson.",
  "creatureship - The condition of being a creature.",
  "unshroud - To remove the shroud from; to uncover. P. Fletcher.",
  "unsucceedable - Not able or likely to succeed. [Obs.] Sir T. Browne.",
  "lithesome - Pliant; limber; flexible; supple; nimble; lissom. -- Lithe\"some*ness, n.",
  "bambocciade - A representation of a grotesque scene from common or rustic life.",
  "desophisticate - To clear from sophism or error. [R.] Hare.",
  "fuscin - A brown, nitrogenous pigment contained in the retinal epithelium; a variety of melanin.",
  "gymnolaemata - An order of Bryozoa, having no epistome.",
  "tyronism - The state of being a tyro, or beginner. [Written also tironism.]",
  "oenomania - (a) Delirium tremens. Rayer. (b) Dipsomania.",
  "decapod - A crustacean with ten feet or legs, as a crab; one of the Decapoda. Also used adjectively.",
  "cyclosis - The circulation or movement of protoplasmic granules within a living vegetable cell.",
  "unsophisticate - Not sophisticated; pure; innocent; genuine. -- Un`so*phis\"ti*ca`ted*ness, n.",
  "napless - Without nap; threadbare. Shak.",
  "fabaceous - Having the nature of a bean; like a bean.",
  "horticultor - One who cultivates a garden.",
  "blasty - 1. Affected by blasts; gusty. 2. Causing blast or injury. [Obs.] Boyle.",
  "linnaea borealis - The twin flower which grows in cold northern climates.",
  "moralism - A maxim or saying embodying a moral truth. Farrar.",
  "allotheism - The worship of strange gods. Jer. Taylor.",
  "defensibleness - Capability of being defended; defensibility. Priestley.",
  "uncalled-for - Not called for; not required or needed; improper; gratuitous; wanton.",
  "wielding - Power; authority; rule. [Obs.] To have them in your might and in your wielding. Chaucer.",
  "fulgurant - Lightening. [R.] Dr. H. More.",
  "petrostearine - A solid unctuous material, of which candles are made.",
  "water-ret - To ret, or rot, in water, as flax; to water-rot.",
  "concludingly - Conclusively. [R.] Digby.",
  "phraseologist - A collector or coiner of phrases.",
  "elementality - The condition of being composed of elements, or a thing so composed.",
  "foreby - Near; hard by; along; past. See Forby. Spenser.",
  "mesosternal - Of or pertaining to the mesosternum.",
  "ingression - Act of entering; entrance. Sir K. Digby.",
  "slogger - A hard hitter; a slugger. [Cant or Slang]  T. Hughes.",
  "veal - The flesh of a calf when killed and used for food.",
  "excecation - The act of making blind. [Obs.] Bp. Richardson.",
  "nonda - The edible plumlike fruit of the Australian tree, Parinarium Nonda.",
  "thor - The god of thunder, and son of Odin.",
  "relievable - Capable of being relieved; fitted to recieve relief. Sir M. Hale.",
  "vinaigrous - 1. Resembling vinegar; sour. 2. Fig.: Unamiable; morose. Carlyle.",
  "strick - A bunch of hackled flax prepared for drawing into slivers. Knight.",
  "talcous - Of or pertaining to talc; composed of, or resembling, talc.",
  "transparence - The quality or state of being transparent; transparency.",
  "pes - The distal segment of the hind limb of vertebrates, including the tarsus and foot.",
  "hyetographic - Of or pertaining to to hyetography.",
  "latitudinous - Having latitude, or wide extent.",
  "pinchem - The European blue titmouse. [Prov. Eng.]",
  "hersillon - A beam with projecting spikes, used to make a breach impassable.",
  "exossation - A depriving of bone or of fruit stones. [Obs.] Bacon.",
  "glitterand - Glittering. [Obs.] Spenser.",
  "spaewife - A female fortune teller. [Scot.]",
  "free-tongued - Speaking without reserve. Bp. Hall.",
  "griseous - Of a light color, or white, mottled with black or brown; grizzled or grizzly. Maunder.",
  "beneficialness - The quality of being beneficial; profitableness.",
  "dealbation - Act of bleaching; a whitening. [Obs.]",
  "hobnailed - See with hobnails, as a shoe.",
  "brevirostrate - Short-billed; having a short beak.",
  "gonocalyx - The bell of a sessile gonozooid.",
  "embitter - To make bitter or sad. See Imbitter.",
  "groundage - A local tax paid by a ship for the ground or space it occupies while in port. Bouvier.",
  "recordation - Remembrance; recollection; also, a record. [Obs.] Shak.",
  "devisor - One who devises, or gives real estate by will; a testator; -- correlative to devisee.",
  "distributer - One who, or that which, distributes or deals out anything; a dispenser. Addison.",
  "micmacs - A tribe of Indians inhabiting Nova Scotia and New Brunswick. [Written also Mikmaks.]",
  "sinopis - A red pigment made from sinopite.",
  "blastemal - Relating to the blastema; rudimentary.",
  "waucht - A large draught of any liquid. [Scot.] Jamieson.",
  "precogitation - Previous cogitation. [R.] Bailey.",
  "bassoonist - A performer on the bassoon. Busby.",
  "tachometry - Measurement by a tachometer; the science or use of tachometers.",
  "aweary - Weary. [Poetic] \"I begin to be aweary of thee.\" Shak.",
  "earliness - The state of being early or forward; promptness.",
  "enigmatology - The art of making or of solving enigmas.",
  "intellectually - In an intellectual manner.",
  "aliethmoidal - Pertaining to expansions of the ethmoid bone or",
  "ankled - Having ankles; -- used in composition; as, well-ankled. Beau. & Fl.",
  "hairworm - A nematoid worm of the genus Gordius, resembling a hair. See Gordius.",
  "totalness - The quality or state of being total; entireness; totality.",
  "alem - The imperial standard of the Turkish Empire.",
  "transfund - To pour from one vessel into another; to transfuse. [Obs.] Barrow.",
  "kentledge - Pigs of iron used for ballast. [Written also kintlidge.]",
  "phasel - The French bean, or kidney bean.",
  "paucispiral - Having few spirals, or whorls; as, a paucispiral operculum or shell.",
  "percarbide - A compound containing a relatively large amount of carbon. [R.]",
  "resinaceous - Having the quality of resin; resinous.",
  "gaucherie - An awkward action; clumsiness; boorishness.",
  "viduage - The state of widows or of widowhood; also, widows, collectively.",
  "leucoma - A white opacity in the cornea of the eye; -- called also albugo.",
  "sigaultian - Pertaining to Sigault, a French physician. See Symphyseotomy.",
  "devotionally - In a devotional manner; toward devotion.",
  "whitester - A bleacher of lines; a whitener; a whitster. [Prov. Eng.]",
  "emboweler - One who takes out the bowels. [Written also emboweller.]",
  "unremorseless - Utterly remorseless. [Obs. & R.] \"Unremorseless death.\" Cowley.",
  "misproportion - To give wrong proportions to; to join without due proportion.",
  "asphyxiate - To bring to a state of asphyxia; to suffocate. Note: [Used commonly in the past pple.]",
  "transcriber - One who transcribes, or writes from a copy; a copier; a copyist.",
  "hyperbatic - Of or pertaining to an hyperbaton; transposed; inverted.",
  "chatoyment - Changeableness of color, as in a mineral; play of colors. Cleaceland."
]