export default [
  "corrugator - A muscle which contracts the skin of the forehead into wrinkles.",
  "anacardium - A genus of plants including the cashew tree. See Cashew.",
  "knurly - Full of knots; hard; tough; hence, capable of enduring or resisting much.",
  "jolty - That jolts; as, a jolty coach. [Colloq.]",
  "proterandry - The condition of being proterandrous.",
  "petrescence - The process of changing into stone; petrification.",
  "bathos - A ludicrous descent from the elevated to the low, in writing or speech; anticlimax.",
  "oblectation - The act of pleasing highly; the state of being greatly pleased; delight. [R.] Feltham.",
  "blazer - One who spreads reports or blazes matters abroad. \"Blazers of crime.\" Spenser.",
  "elegist - A write of elegies. T. Warton.",
  "conspirator - One who engages in a conspiracy; a plotter. 2 Sam. xv. 31.",
  "quinze - A game at cards in which the object is to make fifteen points.",
  "hempen - 1. Made of hemp; as, a hempen cord. 2. Like hemp. \"Beat into a hempen state.\" Cook.",
  "solisequious - Following the course of the sun; as, solisequious plants. [R.] Sir T. Browne.",
  "grumose - Clustered in grains at intervals; grumous.",
  "sex- - A combining form meaning six; as, sexdigitism; sexennial.",
  "rheumides - The class of skin disease developed by the dartrous diathesis. See under Dartrous.",
  "athletism - The state or practice of an athlete; the characteristics of an athlete.",
  "advocacy - The act of pleading for or supporting; work of advocating; intercession.",
  "reflectible - Capable of being reflected, or thrown back; reflexible.",
  "enfect - Contaminated with illegality. [Obs.] Chaucer.",
  "outnoise - To exceed in noise; to surpass in noisiness. [R.] Fuller.",
  "self-torture - The act of inflicting pain on one's self; pain inflicted on one's self.",
  "sunniness - The quality or state of being sunny.",
  "inalienably - In a manner that forbids alienation; as, rights inalienably vested.",
  "relaxative - Having the quality of relaxing; laxative. -- n.  A relaxant. B. Jonson.",
  "cheap-jack - A seller of low-priced or second goods; a hawker.",
  "manequin - An artist's model of wood or other material.",
  "plowboy - A boy that drives or guides a team in plowing; a young rustic.",
  "alloxanate - A combination of alloxanic acid and a base or base or positive radical.",
  "antapoplectic - Good against apoplexy. -- n.  A medicine used against apoplexy.",
  "vinometer - An instrument for determining the strength or purity of wine by measuring its density.",
  "baccarat - A French game of cards, played by a banker and punters.",
  "questorship - The office, or the term of office, of a questor.",
  "shallow-brained - Weak in intellect; foolish; empty-headed. South.",
  "temporizingly - In a temporizing or yielding manner.",
  "diastolic - Of or pertaining to diastole.",
  "traditionally - In a traditional manner.",
  "disrealize - To divest of reality; to make uncertain. [Obs.] Udall.",
  "spinnerule - One of the numerous small spinning tubes on the spinnerets of spiders.",
  "brewer - One who brews; one whose occupation is to prepare malt liquors.",
  "noctilucine - Of or pertaining to Noctiluca.",
  "sunken - Lying on the bottom of a river or other water; sunk.",
  "fisetic - Pertaining to fustet or fisetin.",
  "moonbeam - A ray of light from the moon.",
  "impleader - One who prosecutes or sues another.",
  "stelleridan - A starfish, or brittle star.",
  "triens - A Roman copper coin, equal to one third of the as. See 3d As, 2.",
  "anthropical - Like or related to man; human. [R.] Owen.",
  "phyle - A local division of the people in ancient Athens; a clan; a tribe.",
  "assentator - An obsequious; a flatterer. [R.]",
  "grapplement - A grappling; close fight or embrace. [Obs.] Spenser.",
  "appropinquation - A drawing nigh; approach. [R.] Bp. Hall.",
  "immusical - Inharmonious; unmusical; discordant. Bacon.",
  "trashiness - The quality or state of being trashy.",
  "xenotime - A native phosphate of yttrium occurring in yellowish-brown tetragonal crystals.",
  "exportable - Suitable for exportation; as, exportable products.",
  "stolid - Hopelessly insensible or stupid; not easily aroused or excited; dull; impassive; foolish.",
  "monopathy - Suffering or sensibility in a single organ or function. -- Mon`o*path\"ic, a.",
  "instableness - Instability; unstableness.",
  "equivalue - To put an equal value upon; to put (something) on a par with another thing. W. Taylor.",
  "abstractedness - The state of being abstracted; abstract character.",
  "copyist - A copier; a transcriber; an imitator; a plagiarist.",
  "gorcock - The moor cock, or red grouse. See Grouse. [Prov. Eng.]",
  "holorhinal - Having the nasal bones contiguous.",
  "apothegmatical - Pertaining to, or in the manner of, an apotghem; sententious; pithy.",
  "drasty - Filthy; worthless. [Obs.] \"Drasty ryming.\" Chaucer.",
  "unpaganize - To cause to cease to be pagan; to divest of pagan character. [R.] Cudworth.",
  "prelector - A reader of lectures or discourses; a lecturer. Sheldon.",
  "revocability - The quality of being revocable; as, the revocability of a law.",
  "bibitory - Of or pertaining to drinking or tippling.",
  "futurism - A movement or phase of post-impressionism (which see, below).",
  "reciprocornous - Having horns turning backward and then forward, like those of a ram. [R.] Ash.",
  "subastral - Beneath the stars or heavens; terrestrial. Bp. Warburton.",
  "surrogation - The act of substituting one person in the place of another. [R.] Killingbeck.",
  "monovalent - Having a valence of one; univalent. See Univalent.",
  "podge - 1. A puddle; a plash. Skinner. 2. Porridge. [Prov. Eng.] Halliwell.",
  "mustahfiz - See Army organization, above.",
  "inexorably - In an inexorable manner; inflexibly. \"Inexorably firm.\" Thomson.",
  "reduit - A central or retired work within any other work.",
  "skua - Any jager gull; especially, the Megalestris skua; -- called also boatswain.",
  "misproud - Viciously proud. [Obs.] Shak.",
  "spermatooen - A spermoblast. -- Sper`ma*to\"al, a. Owen.",
  "neuraxis - See Axis cylinder, under Axis.",
  "kickable - Capable or deserving of being kicked. \"A kickable boy.\" G. Eliot.",
  "bleareyedness - The state of being blear-eyed.",
  "resuscitable - Capable of resuscitation; as, resuscitable plants. Boyle.",
  "exurgent - Arising; coming to light. [Obs.]",
  "eggnog - A drink consisting of eggs beaten up with sugar, milk, and (usually) wine or spirits.",
  "effund - To pour out. [Obs.] Dr. H. More.",
  "oylet - 1. See Eyelet. 2. (Arch.)  Same as Oillet.",
  "huttoning - Forcible manipulation of a dislocated, stiff, or painful joint.",
  "canaliculated - Having a channel or groove, as in the leafstalks of most palms.",
  "retex - To annual, as orders. [Obs.] Bp. Hacket.",
  "adrian - Pertaining to the Adriatic Sea; as, Adrian billows.",
  "clinoid - Like a bed; -- applied to several processes on the inner side of the sphenoid bone.",
  "inscriptive - Bearing inscription; of the character or nature of an inscription.",
  "subpellucid - Somewhat pellucid; nearly pellucid.",
  "sortable - 1. Capable of being sorted. 2. Suitable; befitting; proper. [Obs.] con.",
  "rhabdophora - An extinct division of Hydrozoa which includes the graptolities.",
  "antherozoid - One of the mobile male reproductive bodies in the antheridia of cryptogams.",
  "uncreatedness - The quality or state of being uncreated.",
  "scringe - To cringe. [Prov. Eng. & Local, U.S.]",
  "reintegration - A renewing, or making whole again. See Redintegration.",
  "gairish - Same as Garish, Garishly, Garishness.",
  "mestling - A kind of brass. See Maslin. [Obs.]",
  "fenks - The refuse whale blubber, used as a manure, and in the manufacture of Prussian blue. Ure.",
  "rhamphotheca - The horny covering of the bill of birds.",
  "parka - An outer garment made of the skins of birds or mammals, worn by Eskimos, etc.",
  "variformed - Formed with different shapes; having various forms; variform.",
  "stainer - 1. One who stains or tarnishes. 2. A workman who stains; as, a stainer of wood.",
  "supplementation - The act of supplementing. C. Kingsley.",
  "gallipoli oil - An inferior kind of olive oil, brought from Gallipoli, in Italy.",
  "procuress - A female procurer, or pander.",
  "explate - To explain; to unfold. [Obs.] Like Solon's self explatest the knotty laws. B. Jonson.",
  "acroterial - Pertaining to an acroterium; as, ornaments. P. Cyc.",
  "febrifugal - Having the quality of mitigating or curing fever. Boyle.",
  "submentum - The basal part of the labium of insects. It bears the mentum.",
  "illusory - Deceiving, or tending of deceive; fallacious; illusive; as, illusory promises or hopes.",
  "russification - The act or process of being Russified.",
  "compressive - Compressing, or having power or tendency to compress; as, a compressive force.",
  "telephote - A telelectric apparatus for producing images of visible objects at a distance.",
  "mooner - One who abstractedly wanders or gazes about, as if moonstruck. [R.] Dickens.",
  "caranx - A genus of fishes, common on the Atlantic coast, including the yellow or goldon mackerel.",
  "consolidant - Serving to unite or consolidate; having the quality of consolidating or making firm.",
  "infantine - Infantile; childish. A degree of credulity next infantine. Burke.",
  "defatigation - Weariness; fatigue. [R.] Bacon.",
  "baboonery - Baboonish behavior. Marryat.",
  "diarrheal - Of or pertaining to diarrhea; like diarrhea.",
  "supercretaceous - Same as Supracretaceous.",
  "omniscious - All-knowing. [Obs.] Hakewill.",
  "shikaree - A sportsman; esp., a native hunter. [India]",
  "cizar - To clip with scissors. [Obs.] Beau. & Fl.",
  "inaffability - Want of affability or sociability; reticence.",
  "anemonin - An acrid, poisonous, crystallizable substance, obtained from some species of anemone.",
  "blazonment - The act or blazoning; blazoning; emblazonment.",
  "grubble - To feel or grope in the dark. [Obs.] Dryden.",
  "overinform - To inform, fill, or animate, excessively. [R.] Johnson.",
  "able-minded - Having much intellectual power. -- A`ble-mind\"ed*ness, n.",
  "gestant - Bearing within; laden; burdened; pregnant. [R.] \"Clouds gestant with heat.\" Mrs. Browning.",
  "healthlessness - The state of being health",
  "crustaceousness - The state or quality of being crustaceous or having a crustlike shell.",
  "freckledness - The state of being freckled.",
  "wonderly - Wonderfully; wondrously. [Obs.] Chaucer.",
  "wels - The sheatfish; -- called also waller.",
  "doretree - A doorpost. [Obs.] \"As dead as a doretree.\" Piers Plowman.",
  "greasiness - The quality or state of being greasy, oiliness; unctuousness; grossness.",
  "tom - The knave of trumps at gleek. [Obs.]",
  "dipsomaniacal - Of or pertaining to dipsomania.",
  "regratery - The act or practice of regrating.",
  "railingly - With scoffing or insulting language.",
  "subcorneous - (a) Situated under a horny part or layer. (b) Partially horny.",
  "instrumentalness - Usefulness or agency, as means to an end; instrumentality. [R.] Hammond.",
  "untrained - 1. Not trained. Shak. 2. Not trainable; indocile. [Obs.] Herbert.",
  "unintelligence - Absence or lack of intelligence; unwisdom; ignorance. Bp. Hall.",
  "cicisbeism - The state or conduct of a cicisbeo.",
  "allottee - One to whom anything is allotted; one to whom an allotment is made.",
  "pinacoid - A plane parallel to two of the crystalline axes.",
  "weeping-ripe - Ripe for weeping; ready to weep. [Obs.] Shak.",
  "palaeographic - See Paleographer, Paleographic, etc.",
  "pithsome - Pithy; robust. [R.] \"Pithsome health and vigor.\" R. D. Blackmore.",
  "tuille - In plate armor, a suspended plate in from of the thigh. See Illust. of Tasses.",
  "disentomb - To take out from a tomb; a disinter.",
  "dispensableness - Quality of being dispensable.",
  "scrolled - Formed like a scroll; contained in a scroll; adorned with scrolls; as, scrolled work.",
  "mooress - A female Moor; a Moorish woman.",
  "stochastic - Conjectural; able to conjecture. [Obs.] Whitefoot.",
  "huck - To higgle in trading. [Obs.] Holland.",
  "ilmenite - Titanic iron. See Menaccanite.",
  "amplectant - Clasping a support; as, amplectant tendrils. Gray.",
  "denitrify - To deprive of, or free from, nitrogen.",
  "obumbrate - To shade; to darken; to cloud. [R.] Howell.",
  "wilfully - See Willful, Willfully, and Willfulness.",
  "turbant - A turban. [Obs.] Milton. I see the Turk nodding with his turbant. Howell.",
  "recrystallize - To crystallize again. Henry.",
  "fissipation - Reproduction by fission; fissiparism.",
  "ulmic - Pertaining to ulmin; designating an acid obtained from ulmin.",
  "unreverend - 1. Not reverend. 2. Disrespectful; irreverent. [Obs.] Shak.",
  "bibliothecal - Belonging to a library. Byrom.",
  "preventative - That which prevents; -- incorrectly used instead of preventive.",
  "suprascalpular - Situated above, or on the anterior side of, the scapula.",
  "sonship - The state of being a son, or of bearing the relation of a son; filiation. Dr. H. More.",
  "egad - An exclamation expressing exultation or surprise, etc.",
  "docimology - A treatise on the art of testing, as in assaying metals, etc.",
  "acritochromacy - Color blindness; achromatopsy.",
  "trifloral - Three-flowered; having or bearing three flowers; as, a triflorous peduncle.",
  "virent - Green; not withered. [R.] Sir T. Browne.",
  "odontiasis - Cutting of the teeth; dentition.",
  "hemself - Themselves; -- used reflexively. [Obs.] Chaucer.",
  "desidiousness - The state or quality of being desidiose, or indolent. [Obs.] N. Bacon.",
  "fondon - A large copper vessel used for hot amalgamation.",
  "musketoon - 1. A short musket. 2. One who is armed with such a musket.",
  "meditatist - One who is given to meditation.",
  "dispair - To separate (a pair). [R.] I have . . . dispaired two doves. Beau. & Fl.",
  "packhouse - Warehouse for storing goods.",
  "volutation - A rolling of a body; a wallowing. [R.] Sir T. Browne.",
  "linget - An ingot. [Written also lingot.]",
  "mechanician - One skilled in the theory or construction of machines; a machinist. Boyle.",
  "outbuild - To exceed in building, or in durability of building.",
  "entoblast - The inner germ layer; endoderm. See Nucleolus.",
  "hypozoic - Anterior in age to the lowest rocks which contain organic remains. Lyell.",
  "sursolid - The fifth power of a number; as, a is the sursolid of a, or 32 that of 2. [R.] Hutton.",
  "actinolitic - Of the nature of, or containing, actinolite.",
  "teleost - One of the Teleosti. Also used adjectively.",
  "heroical - Heroic. [R.] Spectator. -- He*ro\"ic*al*ly, adv. -- He*ro\"ic*al*ness, n.",
  "sizy - Sizelike; viscous; glutinous; as, sizy blood. Arbuthnot.",
  "julaceous - Like an ament, or bearing aments; amentaceous.",
  "boots - A servant at a hotel or elsewhere, who cleans and blacks the boots and shoes.",
  "barbarousness - The quality or state of being barbarous; barbarity; barbarism.",
  "turriculated - Furnished with, or formed like, a small turret or turrets; somewhat turreted.",
  "interjoin - To join mutually; to unite. [R.] Shak.",
  "ethnological - Of or pertaining to ethnology.",
  "chert - An impure, massive, flintlike quartz or hornstone, of a dull color.",
  "provect - Carried forward; advanced. [Obs.] \"Provect in years.\" Sir T. Flyot.",
  "chemisette - An under-garment, worn by women, usually covering the neck, shoulders, and breast.",
  "clubhand - A short, distorted hand; also, the deformity of having such a hand.",
  "manageability - The state or quality of being manageable; manageableness.",
  "infrugiferous - Not bearing fruit; not fructiferous.",
  "blote - To cure, as herrings, by salting and smoking them; to bloat. [Obs.]",
  "occursion - A meeting; a clash; a collision. [Obs.] Boyle.",
  "serjeantcy - See Sergeant, Sergeantcy, etc. Serjeant-at-arms. See Sergeant- at-arms, under Sergeant.",
  "prevoyant - Foreseeing; prescient. [R.] Mrs. Oliphant.",
  "tightly - In a tight manner; closely; nearly.",
  "flibustier - A buccaneer; an American pirate. See Flibuster. [Obs.]",
  "monopneumona - A suborder of Dipnoi, including the Ceratodus. [Written also monopneumonia.]",
  "subsecutive - Following in a train or succession. [R.]",
  "stern-wheel - Having a paddle wheel at the stern; as, a stern-wheel steamer.",
  "unreeve - To withdraw, or take out, as a rope from a block, thimble, or the like.",
  "cinemograph - An integrating anemometer.",
  "executorship - The office of an executor.",
  "prophasis - Foreknowledge of a disease; prognosis.",
  "billbug - A weevil or curculio of various species, as the corn weevil. See Curculio.",
  "fabrile - Pertaining to a workman, or to work in stone, metal, wood etc.; as, fabrile skill.",
  "typification - The act of typifying, or representing by a figure.",
  "sea squirt - An ascidian. See Illust. under Tunicata.",
  "beggarliness - The quality or state of being beggarly; meanness.",
  "fop - One whose ambition it is to gain admiration by showy dress; a coxcomb; an inferior dandy.",
  "tapiser - A maker of tapestry; an upholsterer. [R.] Chaucer.",
  "hydrosulphureted - Combined with hydrogen sulphide.",
  "prosoma - The anterior of the body of an animal, as of a cephalopod; the thorax of an arthropod.",
  "skeletogenous - Forming or producing parts of the skeleton.",
  "fatherlessness - The state of being without a father.",
  "iracund - Irascible; choleric. \"Iracund people.\" Carlyle.",
  "bepowder - To sprinkle or cover with powder; to powder.",
  "preferability - The quality or state of being preferable; preferableness. J. S. Mill.",
  "efflate - To fill with breath; to puff up. Sir T. Herbert.",
  "tough-head - The ruddy duck. [ Local U.S. ]",
  "wardenship - The office or jurisdiction of a warden.",
  "wooer - One who wooes; one who courts or solicits in love; a suitor. \"A thriving wooer.\" Gibber.",
  "corfute - A native or inhabitant of Corfu, an island in the Mediterranean Sea.",
  "catholicon - A remedy for all diseases; a panacea.",
  "footmark - A footprint; a track or vestige. Coleridge.",
  "lauriol - Spurge laurel. [Obs.] Chaucer.",
  "domiciliation - The act of domiciliating; permanent residence; inhabitancy. Milman.",
  "stipulator - One who stipulates, contracts, or covenants.",
  "petuntse - Powdered fledspar, kaolin, or quartz, used in the manufacture of porcelain.",
  "gairishly - Same as Garish, Garishly, Garishness.",
  "engregge - To aggravate; to make worse; to lie heavy on. [Obs.] Chaucer.",
  "ichnoscopy - The search for the traces of anything. [R.]",
  "param - A white crystalline nitrogenous substance (C2H4N4); -- called also dicyandiamide.",
  "ablegation - The act of sending abroad. [Obs.] Jer. Taylor.",
  "maculated - Having spots or blotches; maculate.",
  "enteradenography - A treatise upon, or description of, the intestinal glands.",
  "sacculo-utricular - Pertaining to the sacculus and utriculus of the ear.",
  "monochronic - Existing at the same time; contemporaneous.",
  "plugging - 1. The act of stopping with a plug. 2. The material of which a plug or stopple is made.",
  "pilled - Stripped of hair; scant of hair; bald. [Obs.] \"Pilled beard.\" Chaucer.",
  "wych-hazel - The wych-elm; -- so called because its leaves are like those of the hazel.",
  "labyrinthal - Pertaining to, or resembling, a labyrinth; intricate; labyrinthian.",
  "logically - In a logical manner; as, to argue logically.",
  "combined - United closely; confederated; chemically united.",
  "pantology - A systematic view of all branches of human knowledge; a work of universal information.",
  "hilted - Having a hilt; -- used in composition; as, basket-hilted, cross-hilted.",
  "whirl-blast - A whirling blast or wind. A whirl-blast from behind the hill. Wordsworth.",
  "bawsin - 1. A badger. [Obs.] B. Jonson. 2. A large, unwieldy person. [Obs.] Nares.",
  "gemmeous - Pertaining to gems; of the nature of gems; resembling gems. Pennant.",
  "cookroom - A room for cookery; a kitchen; the galley or caboose of a ship. Sir W. Raleigh.",
  "trapstick - A stick used in playing the game of trapball; hence, fig., a slender leg. Addison.",
  "similary - Similar. [Obs.] Rhyming cadences of similarly words. South.",
  "myosis - Long-continued contraction of the pupil of the eye.",
  "obligor - The person who binds himself, or gives his bond to another. Blackstone.",
  "epignathous - Hook-billed; having the upper mandible longer than the lower.",
  "halmas - The feast of All Saints; Hallowmas. [Obs.]",
  "masseteric - Of or pertaining to the masseter.",
  "lifelong - Lasting or continuing through life. Tennyson.",
  "subumbrella - The integument of the under surface of the bell, or disk-shaped body, of a jellyfish.",
  "smitt - Fine clay or ocher made up into balls, used for marking sheep. [Eng.] Woodsward.",
  "revealable - Capable of being revealed. -- Re*veal\"a*ble*ness, n.",
  "excrementitious - Pertaining to, or consisting of, excrement; of the nature of excrement.",
  "seedcake - A sweet cake or cooky containing aromatic seeds, as caraway. Tusser.",
  "laxness - The state of being lax; laxity.",
  "sickless - Free from sickness. [R.] Give me long breath, young beds, and sickless ease. Marston.",
  "piapec - A West African pie (Ptilostomus Senegalensis).",
  "incipiency - Beginning; commencement; incipient state.",
  "inuloid - A substance resembling inulin, found in the unripe bulbs of the dahila.",
  "bellwort - A genus of plants (Uvularia) with yellowish bell-shaped flowers.",
  "tarantulated - Bitten by a tarantula; affected with tarantism.",
  "oxybenzene - Hydroxy benzene. Same as Phenol.",
  "indirected - Not directed; aimless. [Obs.]",
  "untrowable - Incredible. [Obs.] \"Untrowable fairness.\" Wyclif.",
  "crossbow - A weapon, used in discharging arrows, formed by placing a bow crosswise on a stock.",
  "excommunicant - One who has been excommunicated.",
  "areometer - An instrument for measuring the specific gravity of fluids; a form hydrometer.",
  "silvas - Vast woodland plains of South America.",
  "partitionment - The act of partitioning.",
  "unseam - To open the seam or seams of; to rip; to cut; to cut open. Shak.",
  "trichiurus - A genus of fishes comprising the hairtails. See Hairtail.",
  "principiate - To begin; to initiate. [Obs.] Sir M. Hale.",
  "semiamplexicaul - Partially amplexicaul; embracing the stem half round, as a leaf.",
  "rubbly - Relating to, or containing, rubble.",
  "langteraloo - An old game at cards. See Loo (a) Tatler.",
  "recompensive - Of the nature of recompense; serving to recompense. Sir T. Browne.",
  "contemporariness - Existence at the same time; contemporaneousness. Howell.",
  "doublehearted - Having a false heart; deceitful; treacherous. Sandys.",
  "occultism - A certain Oriental system of theosophy. A. P. Sinnett.",
  "ploughable - Capable of being plowed; arable.",
  "ichthyophagist - One who eats, or subsists on, fish.",
  "clash gear - A change-speed gear in which the gears are changed by sliding endwise.",
  "catheterization - The operation of introducing a catheter.",
  "carvol - One of a species of aromatic oils, resembling carvacrol.",
  "aerugo - The rust of any metal, esp. of brass or copper; verdigris.",
  "asystolism - The state or symptoms characteristic of asystole.",
  "madge - (a) The barn owl. (b) The magpie.",
  "preambulation - 1. A walking or going before; precedence. [R.] 2. A preamble. [Obs.] Chaucer.",
  "nonunionist - One who does not belong, or refuses to belong, to a trades union.",
  "bestad - Beset; put in peril. [Obs.] Chaucer.",
  "disrudder - To deprive of the rudder, as a ship.",
  "blockheadism - That which characterizes a blockhead; stupidity. Carlyle.",
  "charitableness - The quality of being charitable; the exercise of charity.",
  "burler - One who burls or dresses cloth.",
  "acarus - A genus including many species of small mites.",
  "pirrie - A rough gale of wind. [Obs.] Sir T. Elyot.",
  "lithargyrum - Crystallized litharge, obtained by fusion in the form of fine yellow scales.",
  "prescindent - Cutting off; abstracting. [R.] Cheyne.",
  "husbandable - Capable of being husbanded, or managed with economy. Sherwood.",
  "naufrage - Shipwreck; ruin. [Obs.] acon.",
  "postoral - Situated behind, or posterior to, the mouth.",
  "heterostylism - The condition of being heterostyled.",
  "forlese - To lose utterly. [Obs.] haucer.",
  "auntre - To venture; to dare. [Obs.] Chaucer.",
  "unshout - To recall what is done by shouting. [Obs.] Shak.",
  "chargeableness - The quality of being chargeable or expensive. [Obs.] Whitelocke.",
  "aurigation - The act of driving a chariot or a carriage. [R.] De Quincey.",
  "gobioid - Like, or pertaining to, the goby, or the genus Gobius. -- n.  A gobioid fish.",
  "canonicity - The state or quality of being canonical; agreement with the canon.",
  "inditement - The act of inditing. Craig.",
  "handspring - A somersault made with the assistance of the hands placed upon the ground.",
  "bettor - One who bets; a better. Addison.",
  "carolinian - A native or inhabitant of north or South Carolina.",
  "errancy - A wandering; state of being in error.",
  "operous - Operose. [Obs.] Holder. -- Op\"er*ous*ly, adv. [Obs.]",
  "olecranal - Of or pertaining to the olecranon.",
  "geometrically - According to the rules or laws of geometry.",
  "gladius - The internal shell, or pen, of cephalopods like the squids.",
  "bean trefoil - A leguminous shrub of southern Europe, with trifoliate leaves (Anagyris foetida).",
  "fosterage - The care of a foster child; the charge of nursing. Sir W. Raleigh.",
  "jeoparder - One who puts in jeopardy. [R.]",
  "strigine - Of or pertaining to owls; owl-like.",
  "boltrope - A rope stitched to the edges of a sail to strengthen the sail.",
  "amateurship - The quality or character of an amateur.",
  "secreness - Secrecy; privacy. [Obs.] Chaucer.",
  "puzzel - A harlot; a drab; a hussy. [Obs.] Shak.",
  "cutlet - A piece of meat, especially of veal or mutton, cut for broiling.",
  "unpracticable - Impracticable; not feasible.",
  "disclamation - A disavowing or disowning. Bp. Hall.",
  "chaldaic - Of or pertaining to Chaldes. -- n.  The language or dialect of the Chaldeans; Chaldee.",
  "myoma - A tumor consisting of muscular tissue.",
  "sparge - To sprinkle; to moisten by sprinkling; as, to sparge paper.",
  "totipalmi - A division of swimming birds including those that have totipalmate feet.",
  "polynucleolar - Having more than one nucleolus.",
  "characterless - Destitute of any distinguishing quality; without character or force.",
  "honey-bag - The receptacle for honey in a honeybee. Shak. Grew.",
  "whirler - One who, or that which, whirls.",
  "babyhood - The state or period of infancy.",
  "leporine - Of or pertaining to a hare; like or characteristic of, a hare.",
  "bemaze - To bewilder. Intellects bemazed in endless doubt. Cowper.",
  "sagenite - Acicular rutile occurring in reticulated forms imbedded in quartz.",
  "shingler - 1. One who shingles. 2. A machine for shingling puddled iron.",
  "cornetcy - The commission or rank of a cornet.",
  "enguard - To surround as with a guard. [Obs.] Shak.",
  "ultion - The act of taking vengeance; revenge. [Obs.] Sir T. Browne.",
  "curvilinead - An instrument for drawing curved lines.",
  "imperturbable - Incapable of being disturbed or disconcerted; as, imperturbable gravity.",
  "duet - A composition for two performers, whether vocal or instrumental.",
  "huffingly - Blusteringly; arrogantly. [R.] And huffingly doth this bonny Scot ride. Old Ballad.",
  "endamageable - Capable of being damaged, or injured; damageable. [Obs.]",
  "kistvaen - A Celtic monument, commonly known as a dolmen.",
  "coafforest - To convert into, or add to, a forest. Howell.",
  "comminatory - Threatening or denouncing punishment; as, comminatory terms. B. Jonson.",
  "tramontana - A dry, cold, violent, northerly wind of the Adriatic.",
  "underreckon - To reckon below what is right or proper; to underrate. Bp. Hall.",
  "passim - Here and there; everywhere; as, this word occurs passim in the poem.",
  "shufflecap - ,.A play performed by shaking money in a hat or cap. [R.] Arbuthnot.",
  "bleacher - One who whitens, or whose occupation is to whiten, by bleaching.",
  "tallower - An animal which produces tallow.",
  "mulierose - Fond of woman. [R.] Charles Reade.",
  "mauvaniline - See Mauve aniline, under Mauve.",
  "atmologic - Of or pertaining to atmology. \"Atmological laws of heat.\" Whewell.",
  "reprobationer - One who believes in reprobation. See Reprobation,2. South.",
  "reassume - To assume again or anew; to resume. -- Re`as*sump\"tion, n.",
  "circumambulate - To walk round about. -- Cir`cum*am`bu*la\"tion, n.",
  "tuitionary - Of or pertaining to tuition.",
  "obitual - Of or pertaining to obits, or days when obits are celebrated; as, obitual days. Smart.",
  "cimbrian - Of or pertaining to the Cimbri. -- n.  One of the Cimbri. See Cimbric.",
  "benthamic - Of or pertaining to Bentham or Benthamism.",
  "haliography - Description of the sea; the science that treats of the sea.",
  "talmudism - The teachings of the Talmud, or adherence to them.",
  "omnipercipience - Perception of everything.",
  "intervenience - Intervention; interposition. [R.]",
  "asperne - To spurn; to despise. [Obs.] Sir T. More.",
  "incomity - Want of comity; incivility; rudeness. [R.]",
  "defedation - The act of making foul; pollution. [Obs.]",
  "questionability - The state or condition of being questionable. Stallo.",
  "homoeomery - Same as Homoeomeria. [Obs.] Cudworth.",
  "brandling - Same as Branlin, fish and worm.",
  "archonship - The office of an archon. Mitford.",
  "yoit - The European yellow-hammer. [Prov. Eng.]",
  "disparager - One who disparages or dishonors; one who vilifies or disgraces.",
  "heartswelling - Rankling in, or swelling, the heart. \"Heartswelling hate.\" Spenser.",
  "diarrhoetic - Producing diarrhea, or a purging.",
  "cosignificative - Having the same signification. Cockerham.",
  "metagenetic - Of or pertaining to metagenesis.",
  "auscultate - To practice auscultation; to examine by auscultation.",
  "companiable - Companionable; sociable. [Obs.] Bacon.",
  "sculler - 1. A boat rowed by one man with two sculls, or short oars. [R.] Dryden. 2. One who sculls.",
  "elliptic-lanceolate - Having a form intermediate between elliptic and lanceolate.",
  "tenantless - Having no tenants; unoccupied; as, a tenantless mansion. Shak.",
  "redde - obs. imp. of Read, or Rede. Chaucer.",
  "prudentialist - One who is governed by, or acts from, prudential motives. [R.] Coleridge.",
  "orphanotrophism - The care and support of orphans. [R.] Cotton Mather (1711).",
  "mountance - Amount; sum; quantity; extent. [Obs.] Chaucer.",
  "alienist - One who treats diseases of the mind. Ed. Rev.",
  "heam - The afterbirth or secundines of a beast.",
  "viminal - Of or pertaining to twigs; consisting of twigs; producing twigs.",
  "tiddlywinks - Same as Tiddledywinks.  Kipling.",
  "sirdar - A native chief in Hindostan; a headman. Malcom.",
  "unconcludent - Inconclusive. [Obs.] Locke. -- Un`con*clud\"ing*ness, n. [Obs.] Jer. Taylor.",
  "penang nut - The betel nut. Balfour (Cyc. of India).",
  "monarchical - Of or pertaining to a monarch, or to monarchy. Burke. -- Mo*nar\"chic*al*ly, adv.",
  "horrific - Causing horror; frightful. Let . . . nothing ghastly or horrific be supposed. I. Taylor.",
  "mesosiderite - See the Note under Meteorite.",
  "disrespective - Showing want of respect; disrespectful. [Obs.] Bp. Hall.",
  "pearlins - A kind of lace of silk or thread. [Scot.] Sir W. Scott.",
  "platting - Plaited strips or bark, cane, straw, etc., used for making hats or the like.",
  "tussal - Pertaining to, or manifested by, cough.",
  "inadherent - 1. Not adhering. 2. (Bot.)  Free; not connected with the other organs.",
  "fenny - Pertaining to, or inhabiting, a fen; abounding in fens; swampy; boggy. \"Fenny snake.\" Shak.",
  "crispness - The state or quality of being crisp.",
  "sutlership - The condition or occupation of a sutler.",
  "high steel - Steel containing a high percentage of carbon; high-carbon steel.",
  "variometer - An instrument for comparing magnetic forces, esp. in the earth's magnetic field.",
  "skulker - One who, or that which, skulks.",
  "misfaith - Want of faith; distrust. \"[Anger] born of your misfaith.\" Tennyson.",
  "chaussure - A foot covering of any kind.",
  "septal - Of or pertaining to a septum or septa, as of a coral or a shell.",
  "fatherland - One's native land; the native land of one's fathers or ancestors.",
  "dambonite - A white crystalline, sugary substance obtained from an African caotchouc.",
  "symmetrician - Same as Symmetrian. [R.] Holinshed.",
  "consubstantially - In a consubstantial manner; with identity of substance or nature.",
  "definiteness - The state of being definite; determinateness; precision; certainty.",
  "dewret - To ret or rot by the process called dewretting.",
  "debutant - A person who makes his (or her) first appearance before the public.",
  "preadministration - Previous administration. Bp. Pearson.",
  "bitternut - The swamp hickory (Carya amara). Its thin-shelled nuts are bitter.",
  "cotton seed - The seed of the cotton plant.",
  "affreight - To hire, as a ship, for the transportation of goods or freight.",
  "gelid - Cold; very cold; frozen. \"Gelid founts.\" Thompson.",
  "disimprovement - Reduction from a better to a worse state; as, disimprovement of the earth.",
  "frolicly - In a frolicsome manner; with mirth and gayety. [Obs.] Beau. & Fl.",
  "coagency - Agency in common; joint agency or agent. Coleridge.",
  "nakoo - The gavial. [Written also nako.]",
  "henrietta cloth - A fine wide wooled fabric much used for women's dresses.",
  "heteromera - A division of Coleoptera, having heteromerous tarsi.",
  "refractometer - A contrivance for exhibiting and measuring the refraction of light.",
  "comet-seeker - A telescope of low power, having a large field of view, used for finding comets.",
  "gregge - To make heavy; to increase. [Obs.] Wyclif.",
  "inequivalve - Having unequal valves, as the shell of an oyster.",
  "incanting - Enchanting. [Obs.] Sir T. Herbert.",
  "pistillody - The metamorphosis of other organs into pistils.",
  "muticous - Without a point or pointed process; blunt.",
  "barehead - Having the head uncovered; as, a bareheaded girl.",
  "deutoplastic - Pertaining to, or composed of, deutoplasm.",
  "southerliness - The quality or state of being southerly; direction toward the south.",
  "caparro - A large South American monkey (Lagothrix Humboldtii), with prehensile tail.",
  "tymp - A hollow water-cooled iron casting in the upper part of the archway in which the dam stands.",
  "semiconscious - Half conscious; imperfectly conscious. De Quincey.",
  "vermicide - A medicine which destroys intestinal worms; a worm killer. Pereira.",
  "resplendishant - Resplendent; brilliant. [R. & Obs.] Fabyan.",
  "manducate - To masticate; to chew; to eat. [R.] Jer. Taylor.",
  "beaupere - 1. A father. [Obs.] Wyclif. 2. A companion. [Obs.] Spenser.",
  "erythraean - Red in color. \"The erythrean main.\" Milton.",
  "grudgeful - Full of grudge; envious. \"Grudgeful discontent.\" Spenser.",
  "laryngologist - One who applies himself to laryngology.",
  "seabeach - A beach lying along the sea. \"The bleak seabeach.\" Longfellow.",
  "vanquisher - One who, or that which, vanquishes. Milton.",
  "sphenogram - A cuneiform, or arrow-headed, character.",
  "misgovernance - Misgovernment; misconduct; misbehavior. [Obs.] Chaucer. Spenser.",
  "thymene - A liquid terpene obtained from oil of thyme.",
  "youl - To yell; to yowl. [Obs.] Chaucer.",
  "gemitores - A division of birds including the true pigeons.",
  "dismayedness - A state of being dismayed; dejection of courage; dispiritedness.",
  "hierocracy - Government by ecclesiastics; a hierarchy. Jefferson.",
  "incongruence - Want of congruence; incongruity. Boyle.",
  "conscionableness - The quality of being conscionable; reasonableness. Johnson.",
  "digladiation - Act of digladiating. [Obs.] \"Sore digladiations and contest.\" Evelyn.",
  "anthropophagous - Feeding on human flesh; cannibal.",
  "lucimeter - an instrument for measuring the intensity of light; a photometer.",
  "smartness - The quality or state of being smart.",
  "streaminess - The state of being streamy; a trailing. R. A. Proctor.",
  "depurgatory - Serving to purge; tending to cleanse or purify. [Obs.] Cotgrave.",
  "underniceness - A want of niceness; indelicacy; impropriety.",
  "evangely - Evangel. [Obs.] The sacred pledge of Christ's evangely. Spenser.",
  "matanza - A place where animals are slaughtered for their hides and tallow. [Western U. S.]",
  "awhape - To confound; to terrify; to amaze. [Obs.] Spenser.",
  "semicope - A short cope, or an inferier kind of cope. [Obs.] Chaucer.",
  "plesh - A pool; a plash. [Obs.] Spenser.",
  "cinch - 1. A strong saddle girth, as of canvas. [West. U. S.] 2. A tight grip. [Colloq.]",
  "onionskin - A kind of thin translucent paper with a glossy finish.",
  "sithens - Since. See Sith, and Sithen. [Obs.] Piers Plowman.",
  "sequacity - Quality or state of being sequacious; sequaciousness. Bacon.",
  "columbary - A dovecote; a pigeon house. Sir T. Browne.",
  "conspectus - A general sketch or outline of a subject; a synopsis; an epitome.",
  "pleomorphous - Having the property of pleomorphism.",
  "inviolateness - The state of being inviolate.",
  "omphalo- - A combining form indicating connection with, or relation to, the umbilicus, or navel.",
  "ingravidate - To impregnate. [Obs.] Fuller.",
  "paraxial - On either side of the axis of the skeleton.",
  "reformative - Forming again; having the quality of renewing form; reformatory. Good.",
  "perfunctoriness - The quality or state of being perfunctory.",
  "sybarite - A person devoted to luxury and pleasure; a voluptuary.",
  "achromatically - In an achromatic manner.",
  "tuesday - The third day of the week, following Monday and preceding Wednesday.",
  "supervive - To survive; to outlive. [Obs.]",
  "fortifier - One who, or that which, fortifies, strengthens, supports, or upholds.",
  "oxymethylene - Formic aldehyde, regarded as a methylene derivative.",
  "neutrally - In a neutral manner; without taking part with either side; indifferently.",
  "justiciable - Proper to be examined in a court of justice. Bailey.",
  "imrigh - A peculiar strong soup or broth, made in Scotland. [Written also imrich.]",
  "imprevalence - Want of prevalence. [Obs.]",
  "gainly - Handily; readily; dexterously; advantageously. [Obs.] Dr. H. More.",
  "microform - A microscopic form of life; an animal or vegetable organism microscopic size.",
  "bacterioscopic - Relating to bacterioscopy; as, a bacterioscopic examination.",
  "sententiosity - The quality or state of being sententious. [Obs.] Sir T. Browne.",
  "nightertale - period of night; nighttime. [Obs.] Chaucer.",
  "unpitied - 1. Not pitied. 2. Pitiless; merciless. [Obs.] Shak.",
  "binaural - Of or pertaining to, or used by, both ears.",
  "mucamide - The acid amide of mucic acid, obtained as a white crystalline substance.",
  "leucocytogenesis - The formation of leucocytes.",
  "manubrial - Of or pertaining to a manubrium; shaped like a manubrium; handlelike.",
  "aphetism - An aphetized form of a word. New Eng. Dict.",
  "paleozooelogy - The science of extinct animals, a branch of paleontology.",
  "enneapetalous - Having nine petals, or flower leaves.",
  "enthrill - To pierce; to thrill. [Obs.] Sackville.",
  "recarnify - To convert again into flesh. [Obs.] Howell.",
  "physograde - Any siphonophore which has an air sac for a float, as the Physalia.",
  "oviparity - Generatuon by means of ova. See Generation.",
  "direption - The act of plundering, despoiling, or snatching away. [R.] Speed.",
  "lyken - To please; -- chiefly used impersonally. [Obs.] \" Sith it lyketh you.\" Chaucer.",
  "puckish - Resembling Puck; merry; mischievous. \"Puckish freaks.\" J. R. Green.",
  "basined - Inclosed in a basin. \"Basined rivers.\" Young.",
  "bejade - To jade or tire. [Obs.] Milton.",
  "racket-tailed - Having long and spatulate, or racket-shaped, tail feathers.",
  "premial - Serving to reward; rewarding. [R.] Baxter.",
  "cuish - Defensive armor for the thighs. [ Written also cuisse, and quish.]",
  "refiner - One who, or that which, refines.",
  "bicycling - The use of a bicycle; the act or practice of riding a bicycle.",
  "anonymously - In an anonymous manner; without a name. Swift.",
  "abaxial - Away from the axis or central line; eccentric. Balfour.",
  "redressless - Not having redress; such as can not be redressed; irremediable. Sherwood.",
  "clarty - Sticky and foul; muddy; filthy; dirty. [Prov. Eng.] Halliwell.",
  "deliciate - To delight one's self; to indulge in feasting; to revel. [Obs.]",
  "metallization - The act or process of metallizing. [R.]",
  "ixtil - The fine, soft fiber of the bromeliaceous plant Bromelia sylvestris.",
  "ensober - To make sober. [Obs.] Sad accidents to ensober his spirits. Jer. Taylor.",
  "elucidative - Making clear; tending to elucidate; as, an elucidative note.",
  "unlooked-for - Not looked for; unexpected; as, an unlooked-for event.",
  "cauponize - To sell wine or victuals. [Obs.] Warburfon.",
  "poor-willie - The bar-tailed godwit. [Prov. Eng.]",
  "nombles - The entrails of a deer; the umbles. [Written also numbles.] Johnson.",
  "albinism - The state or condition of being an albino: abinoism; leucopathy.",
  "organical - Organic. The organical structure of human bodies, whereby they live and move. Bentley.",
  "faradization - The treatment with faradic or induced currents of electricity for remedial purposes.",
  "narcosis - Privation of sense or consciousness, due to a narcotic.",
  "half seas over - Half drunk. [Slang: used only predicatively.] Spectator.",
  "avengement - The inflicting of retributive punishment; satisfaction taken. [R.] Milton.",
  "antihydrophobic - Counteracting or preventing hydrophobia. -- n.  A remedy for hydrophobia.",
  "underfollow - To follow closely or immediately after. [Obs.] Wyclif.",
  "eyereach - The range or reach of the eye; eyeshot. \"A seat in eyereach of him.\" B. Jonson.",
  "succussation - 1. A trot or trotting. [Obs.] Sir T. Browne. 2. A shaking; succussion.",
  "parfourn - To perform. [Obs.] Chaucer. Piers Plowman.",
  "staurolitic - Of or pertaining to staurolite; resembling or containing staurolite.",
  "self-reprovingly - In a self-reproving way.",
  "uraniscorrhaphy - Suture of the palate. See Staphyloraphy.",
  "lexiconist - A writer of a lexicon. [R.]",
  "maenad - 1. A Bacchante; a priestess or votary of Bacchus. 2. A frantic or frenzied woman.",
  "belle-lettrist - One versed in belleslettres.",
  "hard-shell - Unyielding; insensible to argument; uncompromising; strict. [Collog., U.S.]",
  "adventurously - In an adventurous manner; venturesomely; boldly; daringly.",
  "heliochromy - The art of producing photographs in color.",
  "saintess - A female saint. [R.] Bp. Fisher.",
  "radiculose - Producing numerous radicles, or rootlets.",
  "dentile - A small tooth, like that of a saw.",
  "curialism - The wiew or doctrins of the ultramontane party in the Latin Church. Gladstone.",
  "christless - Without faith in Christ; unchristian. Tennyson.",
  "cheesemonger - One who deals incheese. B. Jonson.",
  "onerate - To load; to burden. [Obs.] Becon.",
  "cringeling - One who cringes meanly; a fawner.",
  "dallop - A tuft or clump. [Obs.] Tusser.",
  "undying - Not dying; imperishable; unending; immortal; as, the undying souls of men.",
  "zooegeny - The doctrine of the formation of living beings.",
  "tacket - A small, broad-headed nail. [Scot.] Jamieson.",
  "moltable - Capable of assuming a molten state; meltable; fusible. [Obs.]",
  "cannoned - Furnished with cannon. [Poetic] \"Gilbralter's cannoned steep.\" M. Arnold.",
  "adosculation - Impregnation by external contact, without intromission.",
  "brabantine - Pertaining to Brabant, an ancient province of the Netherlands.",
  "chrysopa - A genus of neuropterous insects. See Lacewing.",
  "aceric - Pertaining to, or obtained from, the maple; as, aceric acid. Ure.",
  "storminess - The state of being stormy; tempestuousness; biosteruousness; impetuousness.",
  "arbored - Furnished with an arbor; lined with trees. \"An arboreal walk.\" Pollok.",
  "matzoth - A cake of unleavened bread eaten by the Jews at the feast of the Passover.",
  "deturbate - To evict; to remove. [Obs.] Foxe.",
  "paynize - To treat or preserve, as wood, by a process resembling kyanizing.",
  "irrecognition - A failure to recognize; absence of recognition. Lamb.",
  "ostreaculture - The artificial cultivation of oysters.",
  "moonish - Like the moon; variable. Being but a moonish youth. Shak.",
  "abbatial - Belonging to an abbey; as, abbatial rights.",
  "gainpain - Bread-gainer; -- a term applied in the Middle Ages to the sword of a hired soldier.",
  "pegm - A sort of moving machine employed in the old pageants. [Obs.] B. Jonson.",
  "endocardium - The membrane lining the cavities of the heart.",
  "hegelianism - The system of logic and philosophy set forth by Hegel, a German writer (1770-1831).",
  "disaccommodate - To put to inconvenience; to incommode. [R.] Bp. Warburton.",
  "top-draining - The act or practice of drining the surface of land.",
  "galacta-gogue - An agent exciting secretion of milk.",
  "leatherneck - The sordid friar bird of Australia (Tropidorhynchus sordidus).",
  "zincographic - Of or pertaining to zincography; as, zincographic processes.",
  "amenability - The quality of being amenable; amenableness. Coleridge.",
  "interponent - One who, or that which, interposes; an interloper, an opponent. [R.] Heywood.",
  "decipherable - Capable of being deciphered; as, old writings not decipherable.",
  "cortege - A train of attendants; a procession.",
  "surmisable - Capable of being surmised; as, a surmisable result.",
  "herderite - A rare fluophosphate of glucina, in small white crystals.",
  "prefectorial - Of or pertaining to a prefect.",
  "scuddle - To run hastily; to hurry; to scuttle.",
  "nigromancien - A necromancer. [Obs.] These false enchanters or nigromanciens. Chaucer.",
  "helmsman - The man at the helm; a steersman.",
  "capelle - The private orchestra or band of a prince or of a church.",
  "grimness - Fierceness of look; sternness; crabbedness; forbiddingness.",
  "lacteously - In a lacteous manner; after the manner of milk.",
  "neuropathy - An affection of the nervous system or of a nerve.",
  "silverless - Having no silcver; hence, without money; impecunious. Piers Plowman.",
  "vagrantness - State of being vagrant; vagrancy.",
  "merluce - The European hake; -- called also herring hake and sea pike.",
  "iatric - Of or pertaining to medicine, or to medical men.",
  "quirked - Having, or formed with, a quirk or quirks.",
  "avena - A genus of grasses, including the common oat (Avena sativa); the oat grasses.",
  "antizymotic - Preventing fermentation or decomposition. -- n.  An agent so used.",
  "fair-leader - A block, or ring, serving as a guide for the running rigging or for any rope.",
  "enrank - To place in ranks or in order. [R.] Shak.",
  "bemock - To mock; to ridicule. Bemock the modest moon. Shak.",
  "cobby - 1. Headstrong; obstinate. [Obs.] Brockett. 2. Stout; hearty; lively. [Obs.]",
  "nimbiferous - Serving to bring clouds or stormy weather.",
  "brotherliness - The state or quality of being brotherly.",
  "ophthalmia - An inflammation of the membranes or coats of the eye or of the eyeball.",
  "perturbance - Disturbance; perturbation. [R.] \"Perturbance of the mind.\" Sharp.",
  "geological - Of or pertaining to geology, or the science of the earth.",
  "snowslip - A large mass or avalanche of snow which slips down the side of a mountain, etc.",
  "causelessness - The state of being causeless.",
  "pocketful - As much as a pocket will hold; enough to fill a pocket; as, pocketfuls of chestnuts.",
  "congeneric - Belonging to the same genus; allied in origin, nature, or action.  R. Owen.",
  "upupa - A genus of birds which includes the common hoopoe.",
  "zaim - A Turkish chief who supports a mounted militia bearing the same name. Smart.",
  "farfet - Farfetched. [Obs.] York with his farfet policy. Shak.",
  "verecundity - The quality or state of being verecund; modesty. [Obs.]",
  "rambling - Roving; wandering; discursive; as, a rambling fellow, talk, or building.",
  "foot guards - Infantry soldiers belonging to select regiments called the Guards. [Eng.]",
  "nonchalant - Indifferent; careless; cool.",
  "sightful - Easily or clearly seen; distinctly visible; perspicuous. [Obs.] Testament of Love.",
  "postnuptial - Being or happening after marriage; as, a postnuptial settlement on a wife. Kent.",
  "deil - Devil; -- spelt also deel. [Scot.] Deil's buckie. See under Buckie.",
  "undercreep - To creep secretly or privily. [Obs.] Wyclif.",
  "clupeoid - Of or pertaining to the Herring family.",
  "damp off - To decay and perish through excessive moisture.",
  "inantherate - Not bearing anthers; -- said of sterile stamens.",
  "synonymicon - A dictionary of synonyms. C. J. Smith.",
  "glochidiate - Having barbs; as, glochidiate bristles. Gray.",
  "placation - The act of placating. [R.] Puttenham (1589).",
  "inactose - A variety of sugar, found in certain plants. It is optically inactive.",
  "trihoral - Occurring once in every three hours.",
  "areometric - Pertaining to, or measured by, an areometer.",
  "faddle - To trifle; to toy. -- v. t.  To fondle; to dandle. [Prov. Eng.] Halliwell.",
  "hungered - Hungry; pinched for food. [Obs.] Milton.",
  "plateresque - Resembling silver plate; -- said of certain architectural ornaments.",
  "whirtle - A perforated steel die through which wires or tubes are drawn to form them.",
  "tropically - In a tropical manner; figuratively; metaphorically.",
  "try cock - A cock for withdrawing a small quantity of liquid, as for testing.",
  "involucred - Having an involucre, as umbels, heads, etc. Martyn.",
  "lockram - A kind of linen cloth anciently used in England, originally imported from Brittany. Shak.",
  "brassage - A sum formerly levied to pay the expense of coinage; -- now called seigniorage.",
  "hestern - Pertaining to yesterday. [Obs.] See Yester, a. Ld. Lytton.",
  "lenify - To assuage; to soften; to Bacon. Dryden.",
  "sylleptic - Of or pertaining to a syllepsis; containing syllepsis. -- Syl*lep\"tic*al*ly, adv.",
  "lardon - A bit of fat pork or bacon used in larding.",
  "prorhinal - Situated in front of the nasal chambers.",
  "morian - A Moor. [Obs.] In vain the Turks and Morians armed be. Fairfax.",
  "post-abdomen - That part of a crustacean behind the cephalothorax; -- more commonly called abdomen.",
  "coextension - The act of extending equally, or the state of being equally extended.",
  "hydrencephsloid - Same as Hydrocephaloid.",
  "puler - One who pules; one who whines or complains; a weak person.",
  "depudicate - To deflour; to dishonor. [Obs.]",
  "wealthily - In a wealthy manner; richly. I come to wive it wealthily in Padua. Shak.",
  "teetotally - Entirely; totally. [Colloq.]",
  "overshade - To cover with shade; to render dark or gloomy; to overshadow. Shak.",
  "madisterium - An instrument to extract hairs.",
  "irresponsive - Not responsive; not able, ready, or inclined to respond.",
  "frontiered - Placed on the frontiers. [R.]",
  "unmew - To release from confinement or restraint. Keats.",
  "alternator - An electric generator or dynamo for producing alternating currents.",
  "rappee - A pungent kind of snuff made from the darker and ranker kinds of tobacco leaves.",
  "electrophone - An instrument for producing sound by means of electric currents.",
  "feuar - One who holds a feu. Sir W. Scott.",
  "geotropic - Relating to, or showing, geotropism.",
  "annalize - To record in annals. Sheldon.",
  "trieterics - Festival games celebrated once in three years. [R.] May.",
  "prothetic - Of or pertaining to prothesis; as, a prothetic apparatus.",
  "contriver - One who contrives, devises, plans, or schemas. Swift.",
  "conditionality - The quality of being conditional, or limited; limitation by certain terms.",
  "untaste - To deprive of a taste for a thing. [R.] Daniel.",
  "wharp - A kind of fine sand from the banks of the Trent, used as a polishing powder. [Eng.]",
  "hoddydoddy - An awkward or foolish person. [Obs.] B. Jonson.",
  "impostrous - Characterized by imposture; deceitful. \"Impostrous pretense of knowledge.\" Grote.",
  "verruculose - Minutely verrucose; as, a verruculose leaf or stalk.",
  "importunator - One who importunes; an importuner. [Obs.] Sir E. Sandys.",
  "frigerate - To make cool. [Obs.] Blount.",
  "reilluminate - To enlighten again; to reillumine.",
  "negativeness - The quality or state of being negative.",
  "disguisedness - The state of being disguised.",
  "septemvirate - The office of septemvir; a government by septimvirs.",
  "decarbonization - The action or process of depriving a substance of carbon.",
  "palmister - One who practices palmistry Bp. Hall.",
  "telescopy - The art or practice of using or making telescopes.",
  "enmesh - To catch or entangle in, or as in, meshes. Shak. My doubts enmesh me if I try. Lowell.",
  "unruffle - To cease from being ruffled or agitated. Dryden.",
  "sloggy - Sluggish. [Obs.] Somnolence that is sloggy slumbering Chaucer.",
  "cornstarch - Starch made from Indian corn, esp. a fine white flour used for puddings, etc.",
  "necroscopical - Or or relating to post-mortem examinations.",
  "sixpenny - Of the value of, or costing, sixpence; as, a sixpenny loaf.",
  "disassiduity - Want of as siduity or care. [R.] Sir H. Wotton.",
  "poiser - The balancer of dipterous insects.",
  "vakeel - A native attorney or agent; also, an ambassador. [India]",
  "xylographer - One who practices xylography.",
  "blatteroon - A senseless babbler or boaster. [Obs.] \"I hate such blatteroons.\" Howell.",
  "bluefin - A species of whitefish (Coregonus nigripinnis) found in Lake Michigan.",
  "trafficker - One who traffics, or carries on commerce; a trader; a merchant.",
  "accurately - In an accurate manner; exactly; precisely; without error or defect.",
  "latitat - A writ based upon the presumption that the person summoned was hiding. Blackstone.",
  "postulatory - Of the nature of a postulate. Sir T. Browne.",
  "trifoliate - Having three leaves or leaflets, as clover. See Illust. of Shamrock.",
  "diapophysical - Pertaining to a diapophysis.",
  "piation - The act of making atonement; expiation. [Obs.]",
  "laudation - The act of lauding; praise; high commendation.",
  "perclose - 1. (Eccl. Arch.)  Same as Parclose. 2. Conclusion; end. [Obs.] Sir W. Raleigh.",
  "cassolette - a box, or vase with a perforated cover to emit perfumes.",
  "bamboozler - A swindler; one who deceives by trickery. [Colloq.] Arbuthnot.",
  "glossal - Of or pertaining to the tongue; lingual.",
  "chimerically - Wildy; vainly; fancifully.",
  "primy - Being in its prime. [Obs.] \"The youth of primy nature.\" Shak.",
  "sternson - The end of a ship's keelson, to which the sternpost is bolted; -- called also stern knee.",
  "full-butt - With direct and violentop position; with sudden collision. [Colloq.] L'Estrange.",
  "circumstantiable - Capable of being circumstantiated. [Obs.] Jer Taylor.",
  "laureled - Crowned with laurel, or with a laurel wreath; laureate. [Written also laurelled.]",
  "implicatively - By implication. Sir G. Buck.",
  "polypean - Of or pertaining to a polyp, or polyps.",
  "liberalistic - Pertaining to, or characterized by, liberalism; as, liberalistic opinions.",
  "acinaceous - Containing seeds or stones of grapes, or grains like them.",
  "inextricably - In an inextricable manner.",
  "taupie - A foolish or thoughtless young person, esp. a slothful or slovenly woman. [Scot.]  Burns.",
  "bombilation - A humming sound; a booming. To . . . silence the bombilation of guns. Sir T. Browne.",
  "desirableness - The quality of being desirable. The desirableness of the Austrian alliance. Froude.",
  "tormenting - Causing torment; as, a tormenting dream. -- Tor*ment\"ing*ly, adv.",
  "gambogic - Pertaining to, resembling, or containing, gamboge.",
  "nighted - 1. Darkness; clouded. [R.] Shak. 2. Overtaken by night; belated. Beau. & Fl.",
  "umbery - Of or pertaining to umber; like umber; as, umbery gold.",
  "rowable - That may be rowed, or rowed upon. \"That long barren fen, once rowable.\" B. Jonson.",
  "welldoer - One who does well; one who does good to another; a benefactor.",
  "alexipyretic - Serving to drive off fever; antifebrile. -- n.  A febrifuge.",
  "bell-faced - Having the striking surface convex; -- said of hammers.",
  "calicular - Relating to, or resembling, a cup; also improperly used for calycular, calyculate.",
  "photophony - The art or practice of using the photophone.",
  "self-affairs - One's own affairs; one's private business. [Obs.] Shak.",
  "periscope - A general or comprehensive view. [R.]",
  "ceterach - A species of fern with fronds (Asplenium Ceterach).",
  "overdelighted - Delighted beyond measure.",
  "transportant - Transporting; as, transportant love. [Obs.] Dr. H. More.",
  "halometer - An instrument for measuring the forms and angles of salts and crystals; a goniometer.",
  "seafarer - One who follows the sea as a business; a mariner; a sailor.",
  "xanthomatous - Of or pertaining to xanthoma.",
  "lapstreak - Made with boards whose edges lap one over another; clinker- built; -- said of boats.",
  "hexametrist - One who writes in hexameters. \"The Christian hexametrists.\" Milman.",
  "tressed - 1. Having tresses. 2. Formed into ringlets or braided; braided; curled. Spenser. Drayton.",
  "ronyon - A mangy or scabby creature. \"Aroint thee, with!\" the rump-fed ronyon cries. Shak.",
  "exsertile - Capable of being thrust out or protruded. J. Fleming.",
  "blink-eyed - Habitually winking. Marlowe.",
  "contraversion - A turning to the opposite side; antistrophe. Congreve.",
  "fluxibility - The quality of being fluxible. Hammond.",
  "brimless - Having no brim; as, brimless caps.",
  "low-churchman - One who holds low-church principles.",
  "pliform - In the form of a ply, fold, or doubling. [Obs.] Pennant.",
  "divinization - A making divine. M. Arnold.",
  "endosmometer - An instrument for measuring the force or amount of endosmotic action.",
  "isagon - A figure or polygon whose angles are equal.",
  "uraniscoplasty - The process of forming an artificial palate.",
  "tollman - One who receives or collects toll; a toll gatherer. Cowper.",
  "infamize - To make infamous; to defame. [R.] Coleridge.",
  "orthophony - The art of correct articulation; voice training.",
  "hydrostatically - According to hydrostatics, or to hydrostatic principles. Bentley.",
  "preachership - The office of a preacher. \"The preachership of the Rolls.\" Macaulay.",
  "hamated - Hooked, or set with hooks; hamate. Swift.",
  "puffiness - The quality or state of being puffy.",
  "pistillaceous - Growing on, or having nature of, the pistil; of or pertaining to a pistil. Barton.",
  "expiatorious - Of an expiatory nature; expiatory. Jer. Taylor.",
  "vaishnava - A worshiper of the god Vishnu in any of his incarnations.",
  "hirundine - Like or pertaining to the swallows.",
  "dynamism - The doctrine of Leibnitz, that all substance involves force.",
  "bescratch - To tear with the nails; to cover with scratches.",
  "phylacteric - Of or pertaining to phylacteries.",
  "uncharnel - To remove from a charnel house; to raise from the grave; to exhume. Byron.",
  "circumscriptible - Capable of being circumscribed or limited by bounds.",
  "tarsectomy - The operation of excising one or more of the bones of the tarsus.",
  "melancholious - Melancholy. [R.] Milton.",
  "practico - A guide. [Cuba & Phil. Islands]  D. C. Worcester.",
  "royalism - the principles or conduct of royalists.",
  "vintry - A place where wine is sold. [Obs.] Ainsworth.",
  "evaluate - To fix the value of; to rate; to appraise.",
  "natantly - In a floating manner; swimmingly.",
  "hospitium - 1. An inn; a lodging; a hospice. [Obs.] 2. (Law)  An inn of court.",
  "planimetrical - Of or pertaining to planimetry.",
  "paleothere - Any species of Paleotherium.",
  "synteretic - Preserving health; prophylactic. [Obs.]",
  "shintiyan - A kind of wide loose drawers or trousers worn by women in Mohammedan countries.",
  "bawson - 1. A badger. [Obs.] B. Jonson. 2. A large, unwieldy person. [Obs.] Nares.",
  "toyish - 1. Sportive; trifling; wanton. 2. Resembling a toy. --Toy\"ish*ly, dv.-Toy\"ish*ness, n.",
  "tricky - Given to tricks; practicing deception; trickish; knavish.",
  "defectible - Liable to defect; imperfect. [R.] \"A defectible understanding.\" Jer. Taylor.",
  "uninucleated - Possessed of but a single nucleus; as, a uninucleated cell.",
  "lazarly - Full of sores; leprous. Shak. Bp. Hall.",
  "pannikel - The brainpan, or skull; hence, the crest. [Obs.] Spenser.",
  "bull terrier - A breed of dogs obtained by crossing the bulldog and the terrier.",
  "rhonchisonant - Making a snorting noise; snorting. [R.]",
  "deforest - To clear of forests; to dis U. S. Agric. Reports.",
  "numismatical - Of or pertaining to coins; relating to the science of coins or medals.",
  "declarable - Capable of being declared. Sir T. Browne.",
  "bonchretien - A name given to several kinds of pears. See Bartlett.",
  "starosty - A castle and domain conferred on a nobleman for life. [Poland] Brande & C.",
  "syringotome - A small blunt-pointed bistoury, -- used in syringotomy.",
  "dioptra - An optical instrument, invented by Hipparchus, for taking altitudes, leveling, etc.",
  "scepticism - etc. See Skeptic, Skeptical, Skepticism, etc.",
  "buccaneerish - Like a buccaneer; piratical.",
  "panacean - Having the properties of a panacea. [R.] \"Panacean dews.\" Whitehead.",
  "hailshot - Small shot which scatter like hailstones. [Obs.] Hayward.",
  "infester - One who, or that which, infests.",
  "red-riband - The European red band fish, or fireflame. See Rend fish.",
  "decidence - A falling off. [R.] Sir T. Browne.",
  "cicala - A cicada. See Cicada. \"At eve a dry cicala sung.\" Tennison.",
  "lapis lazuli - An albuminous mineral of a rich blue color. Same as Lazuli, which see.",
  "insubstantial - Unsubstantial; not real or strong. \"Insubstantial pageant.\" [R.] Shak.",
  "temporaneous - Temporarity. [Obs.] Hallywell.",
  "unsubstantialize - To make unsubstantial. [R.]",
  "cochleate - Having the form of a snail shell; spiral; turbinated.",
  "homelike - Like a home; comfortable; cheerful; cozy; friendly.",
  "moroxite - A variety of apatite of a greenish blue color.",
  "slitter - One who, or that which, slits.",
  "monal - Any Asiatic pheasant of the genus Lophophorus, as the Impeyan pheasant.",
  "tubulidentate - Having teeth traversed by canals; -- said of certain edentates.",
  "vitalist - A believer in the theory of vitalism; -- opposed to physicist.",
  "assecuration - Assurance; certainty. [Obs.]",
  "intermetacarpal - Between the metacarpal bones.",
  "procacity - Forwardness; pertness; petulance. [R.] Burton.",
  "suprapubian - Situated above, or anterior to, the pubic bone.",
  "vivency - Manner of supporting or continuing life or vegetation. [Obs.] Sir T. Browne.",
  "scraffle - To scramble or struggle; to wrangle; also, to be industrious. [Prov. Eng.] Halliwell.",
  "aggrievance - Oppression; hardship; injury; grievance. [Archaic]",
  "desecate - To cut, as with a scythe; to mow. [Obs.]",
  "difficultness - Difficulty. [R.] Golding.",
  "brahmo-somaj - A modern reforming theistic sect among the Hindos. [Written also Brahma-samaj.]",
  "enclavement - The state of being an enclave. [Recent]",
  "rescussee - The party in whose favor a rescue is made. Crabb.",
  "compassless - Having no compass. Knowles.",
  "revestture - Vesture. [Obs.] Richrevesture of cloth of gold. E. Hall.",
  "bookbinder - One whose occupation is to bind books.",
  "flashiness - The quality of being flashy.",
  "functionate - To execute or perform a function; to transact one's regular or appointed business.",
  "leathery - Resembling leather in appearance or consistence; tough. \"A leathery skin.\" Grew.",
  "protozooen - (a) One of the Protozoa. (b) A single zooid of a compound protozoan.",
  "isabella color - A brownish yellow color.",
  "subcontract - A contract under, or subordinate to, a previous contract.",
  "patriarchship - A patriarchate. Ayliffe.",
  "podotheca - The scaly covering of the foot of a bird or reptile.",
  "unshackle - To loose from shackles or bonds; to set free from restraint; to unfetter. Addison.",
  "bolivian - Of or pertaining to Bolivia. -- n.  A native of Bolivia.",
  "obtrusionist - One who practices or excuses obtrusion. [R.] Gent. Mag.",
  "illiterature - Want of learning; illiteracy. [R.] Ayliffe. Southey.",
  "quater-cousin - A cousin within the first four degrees of kindred.",
  "bipalmate - Palmately branched, with the branches again palmated.",
  "alum stone - A subsulphate of alumina and potash; alunite.",
  "wispen - Formed of a wisp, or of wisp; as, a wispen broom. [Obs.]",
  "generability - Capability of being generated. Johnstone.",
  "meagerness - The state or quality of being meager; leanness; scantiness; barrenness.",
  "matronly - 1. Advanced in years; elderly. 2. Like, or befitting, a matron; grave; sedate.",
  "elfishness - The quality of being elfish.",
  "melanagogue - A medicine supposed to expel black bile or choler. [Obs.]",
  "bettermost - Best. [R.] \"The bettermost classes.\" Brougham.",
  "squirter - One who, or that which, squirts.",
  "thanatopsis - A view of death; a meditation on the subject of death. Bryant.",
  "gradely - Decent; orderly. [Prov. Eng.] Halliwell. -- adv.  Decently; in order. [Prov. Eng.]",
  "ceorl - A freeman of the lowest class; one not a thane or of the servile classes; a churl.",
  "abbotship - The state or office of an abbot.",
  "eumenides - A euphemistic name for the Furies of Erinyes.",
  "presbyterial - Presbyterian. \"Presbyterial government.\" Milton.",
  "relevation - A raising or lifting up. [Obs.]",
  "tentful - As much, or as many, as a tent will hold.",
  "ebrious - Inclined to drink to excess; intoxicated; tipsy. [R.] M. Collins.",
  "halteres - Balancers; the rudimentary hind wings of Diptera.",
  "user - 1. One who uses. Shak. 2. (Law)  Enjoyment of property; use. Mozley & W.",
  "youngth - Youth. [Obs.] Youngth is a bubble blown up with breath. Spenser.",
  "unreproachable - Not liable to be reproached; irreproachable.",
  "palmcrist - The palma Christi. (Jonah iv. 6, margin, and Douay version, note.)",
  "unempirically - Not empirically; without experiment or experience.",
  "acrobatic - Pertaining to an acrobat. -- Ac`ro*bat\"ic*al*ly, adv.",
  "hardener - One who, or that which, hardens; specif., one who tempers tools.",
  "nittings - The refuse of good ore. Raymond.",
  "rawhead - A specter mentioned to frighten children; as, rawhead and bloodybones.",
  "sugarless - Without sugar; free from sugar.",
  "trickery - The art of dressing up; artifice; stratagem; fraud; imposture.",
  "croisado - A holy war; a crusade. [Obs.] Bacon.",
  "cledge - The upper stratum of fuller's earth.",
  "foolhardise - Foolhardiness. [Obs.] Spenser.",
  "hoosier state - Indiana; -- a nickname of obscure origin.",
  "needscost - Of necessity. [Obs.] Chaucer.",
  "slumberless - Without slumber; sleepless.",
  "slapping - Very large; monstrous; big. [Slang.]",
  "altimetry - The art of measuring altitudes, or heights.",
  "bow-pen - Bow-compasses carrying a drawing pen. See Bow-compass.",
  "entablement - See Entablature. [R.] Evelyn.",
  "lectica - A kind of litter or portable couch.",
  "teinture - Color; tinge; tincture. [Obs.] Holland.",
  "cephalocercal - Relating to the long axis of the body.",
  "bruin - A bear; -- so called in popular tales and fables.",
  "brittleness - Aptness to break; fragility.",
  "quiritation - A crying for help. [Obs.] Bp. Hall.",
  "trapezate - Having the form of a trapezium; trapeziform.",
  "personalism - The quality or state of being personal; personality. [R.]",
  "misreform - To reform wrongly or imperfectly.",
  "elaiodic - Derived from castor oil; ricinoleic; as, elaiodic acid. [R.]",
  "subtriangular - Nearly, but not perfectly, triangular. Darwin.",
  "romanticist - One who advocates romanticism in modern literature. J. R. Seeley.",
  "easy-chair - An armichair for ease or repose. \"Laugh . . . in Rabelais' easy-chair.\" Pope.",
  "ilmenium - A supposed element claimed to have been discovered by R.Harmann.",
  "duumviral - Of or belonging to the duumviri or the duumvirate.",
  "polliniferous - Producing pollen; polleniferous.",
  "pronged - Having prongs or projections like the tines of a fork; as, a three-pronged fork.",
  "strombite - A fossil shell of the genus Strombus.",
  "omination - The act of ominating; presaging. [Obs.] Fuller.",
  "overgrassed - Overstocked, or overgrown, or covered, with grass. [Obs.] Spenser.",
  "anorthopia - Distorted vision, in which straight lines appear bent.",
  "supradecompound - More than decompound; divided many times.",
  "appropre - To appropriate. [Obs.] Fuller.",
  "wagon-roofed - Having a roof, or top, shaped like an inverted U; wagon-headed.",
  "zebrule - A cross between a male zebra and a female horse.",
  "lunged - Having lungs, or breathing organs similar to lungs.",
  "elan - Ardor inspired by passion or enthusiasm.",
  "passableness - The quality of being passable.",
  "rinser - One who, or that which, rinses.",
  "overcount - To rate too high; to outnumber. Shak.",
  "excisable - Liable or subject to excise; as, tobacco in an excisable commodity.",
  "abiogenous - Produced by spontaneous generation.",
  "poikilothermic - Having a varying body temperature. See Homoiothermal.",
  "misinformation - Untrue or incorrect information. Bacon.",
  "seether - A pot for boiling things; a boiler. Like burnished gold the little seether shone. Dryden.",
  "anabaptistic - Relating or attributed to the Anabaptists, or their doctrines. Milton. Bp. Bull.",
  "thaneship - The state or dignity of a thane; thanehood; also, the seignioralty of a thane.",
  "derailment - The act of going off, or the state of being off, the rails of a railroad.",
  "foots - The settlings of oil, molasses, etc., at the bottom of a barrel or hogshead. Simmonds.",
  "inconsonancy - Want of consonance or harmony of sound, action, or thought; disagreement.",
  "domiciliate - 1. To establish in a permanent residence; to domicile. 2. To domesticate. Pownall.",
  "stubbedness - The quality or state of being stubbed.",
  "antilogy - A contradiction between any words or passages in an author. Sir W. Hamilton.",
  "mactation - The act of killing a victim for sacrifice. [Obs.]",
  "teemful - 1. Pregnant; prolific. [Obs.] 2. Brimful. [Obs.] Ainsworth.",
  "penniform - Having the form of a feather or plume.",
  "compositive - Having the quality of entering into composition; compounded. [R.]",
  "razzia - A plundering and destructive incursion; a foray; a rai",
  "timberman - A man employed in placing supports of timber in a mine. Weale.",
  "hackbolt - The greater shearwater or hagdon. See Hagdon.",
  "constabulatory - A constabulary. [Obs.] Bp. Burnet.",
  "encrinitical - Pertaining to encrinites; encrinal.",
  "cackling - The broken noise of a goose or a hen.",
  "rawness - The quality or state of being raw.",
  "sophistication - The act of sophisticating; adulteration; as, the sophistication of drugs. Boyle.",
  "intransmissible - Not capable of being transmitted.",
  "aviseful - Watchful; circumspect. [Obs.] With sharp, aviseful eye. Spenser."
]