export default [
  "slipes - Sledge runners on which a skip is dragged in a mine.",
  "inflexure - An inflection; a bend or fold. [R.] Sir T. Browne.",
  "subdeposit - That which is deposited beneath something else.",
  "eyewater - A wash or lotion for application to the eyes.",
  "foxly - Foxlike. [Obs.] \"Foxly craft.\" Latimer.",
  "neem tree - An Asiatic name for Melia Azadirachta, and M. Azedarach. See Margosa.",
  "bidarkee - A portable boat made of skins stretched on a frame. [Alaska] The Century.",
  "odize - To charge with od. See Od. [Archaic]",
  "plenarty - The state of a benefice when occupied. Blackstone.",
  "lorication - The act of loricating; the protecting substance put on; a covering of scales or plates.",
  "intellectuality - Intellectual powers; possession of intellect; quality of being intellectual.",
  "entombment - The act of entombing or burying, or state of being entombed; burial. Barrow.",
  "arrenotokous - Producing males from unfertilized eggs, as certain wasps and bees.",
  "minish - To diminish; to lessen. The living of poor men thereby minished. Latimer.",
  "historically - In the manner of, or in accordance with, history.",
  "tutenag - (a) Crude zinc. [India] (b) Packfong. [Written also tutenague.]",
  "mormo - A bugbear; false terror. [Obs.] Jonhson.",
  "electrotyping - The act or the process of making electrotypes.",
  "heterodactylae - A group of birds including the trogons.",
  "arist - of Arise, for ariseth. [Obs.] Chaucer.",
  "anticontagious - Opposing or destroying contagion.",
  "electorship - The office or status of an elector.",
  "tradeswoman - A woman who trades, or is skilled in trade.",
  "ornateness - The quality of being ornate.",
  "iconophilist - A student, or lover of the study, of iconography.",
  "sabal - A genus of palm trees including the palmetto of the Southern United States.",
  "misappreciated - Improperly appreciated.",
  "mesobronchium - The main bronchus of each lung.",
  "eigh - An exclamation expressing delight.",
  "patentee - One to whom a grant is made, or a privilege secured, by patent. Bacon.",
  "indefensive - Defenseless. [Obs.] The sword awes the indefensive villager. Sir T. Herbert.",
  "mavis - The European throstle or song thrush (Turdus musicus).",
  "sterrink - The crab-eating seal (Lobodon carcinophaga) of the Antarctic Ocean.",
  "knabble - To bite or nibble. [Obs.] Horses will knabble at walls, and rats gnaw iron. Sir T. Browne.",
  "diphthongalize - To make into a diphthong; to pronounce as a diphthong.",
  "cynicalness - The quality of being cynical.",
  "hoody - The hooded crow; also, in Scotland, the hooded gull.",
  "kie - Kine; cows. [Prov. Eng.] Halliwell.",
  "weet-bird - The wryneck; -- so called from its cry. [Prov. Eng.]",
  "phytophagous - Feeding on plants; herbivorous; as, a phytophagous animal.",
  "passman - One who passes for a degree, without honors. See Classman, 2. [Eng. Univ.]",
  "unpathwayed - Pathless. [R.] \"The smooth, unpathwayed plain.\" Wordsworth.",
  "bonapartist - One attached to the policy or family of Bonaparte, or of the Bonapartes.",
  "biological - Of or relating to biology. -- Bi`o*log\"ic*al*ly, adv.",
  "retrogenerative - Begetting young by retrocopulation.",
  "stallman - One who keeps a stall for the sale of merchandise, especially books. Sterne.",
  "capilliform - In the shape or form of, a hair, or of hairs.",
  "illuminize - To initiate the doctrines or principles of the Illuminati.",
  "spermatophyte - Any plant of the phylum Spermatophyta. -- Sper`ma*to*phyt\"ic (#), a.",
  "milden - To make mild, or milder. Lowell.",
  "antistrophic - Of or pertaining to an antistrophe.",
  "weightless - Having no weight; imponderable; hence, light. Shak.",
  "arthroderm - The external covering of an Arthropod.",
  "nubble - To beat or bruise with the fist. [Obs.] Ainsworth.",
  "olympionic - An ode in honor of a victor in the Olympic games. [R.] Johnson.",
  "abstrusion - The act of thrusting away. [R.] Ogilvie.",
  "incensement - Fury; rage; heat; exasperation; as, implacable incensement. Shak.",
  "lingeringly - With delay; slowly; tediously.",
  "transubstantiator - One who maintains the doctrine of transubstantiation. Barrow.",
  "muzziness - The state or quality of being muzzy.",
  "warrioress - A female warrior. [Obs.] Spenser.",
  "greenhorn - A raw, inexperienced person; one easily imposed upon. W. Irving.",
  "yardstick - A stick three feet, or a yard, in length, used as a measure of cloth, etc.",
  "panhellenium - An assembly or association of Greeks from all the states of Greece.",
  "windhover - The kestrel; -- called also windbibber, windcuffer, windfanner. [Prov. Eng.]",
  "black-faced - Having a black, dark, or gloomy face or aspect.",
  "israelitic - Of or pertaining to Israel, or to the Israelites; Jewish; Hebrew.",
  "dreariment - Dreariness. [Obs.] Spenser.",
  "concionatory - Of or pertaining to preaching or public addresses. [Obs.] Howell.",
  "colonelcy - The office, rank, or commission of a colonel.",
  "convulsional - Pertaining to, or having, convulsions; convulsionary. [R.] Lamb.",
  "protense - Extension.[Obs.] \" By due degrees and long protense.\" Spenser.",
  "technicalness - The quality or state of being technical; technicality.",
  "tumultuate - To make a tumult. [Obs.] \"He will murmur and tumultuate.\" South.",
  "inculture - Want or neglect of cultivation or culture. [Obs.] Feltham.",
  "gravitational - Of or pertaining to the force of gravity; as, gravitational units.",
  "ladify - To make a lady of; to make ladylike. [Obs.] Massinger.",
  "bearing cloth - A cloth with which a child is covered when carried to be baptized. Shak.",
  "perjenet - A kind of pear. [Obs.] Chaucer.",
  "dentiloquist - One who speaks through the teeth, that is, with the teeth closed.",
  "fortunateness - The condition or quality of being fortunate; good luck; success; happiness.",
  "praseo- - A combining form signifying green; as, praseocobalt, a green variety of cobalt.",
  "chloriodic - Compounded of chlorine and iodine; containing chlorine and iodine.",
  "disencharm - To free from the influence of a charm or spell; to disenchant. [R.] Jer. Taylor.",
  "phaenogamous - Having true flowers with with distinct floral organs; flowering.",
  "inexcusableness - The quality of being inexcusable; enormity forgiveness. South.",
  "commensurability - The quality of being commersurable. Sir T. Browne.",
  "cantred - A district comprising a hundred villages, as in Wales. [Written also kantry.]",
  "monkly - Like, or suitable to, a monk. [R.]",
  "lass - A youth woman; a girl; a sweetheart.",
  "proportionment - The act or process of dividing out proportionally.",
  "forestry - The art of forming or of cultivating forests; the management of growing timber.",
  "galvanocaustic - Relating to the use of galvanic heat as a caustic, especially in medicine.",
  "infumate - To dry by exposing to smoke; to expose to smoke.",
  "overconfident - Confident to excess. -- O\"ver*con\"fi*dent*ly, adv.",
  "tritovum - An embryonic insect which has twice cast its skin previous to hatching from the egg.",
  "femerell - A lantern, or louver covering, placed on a roof, for ventilation or escape of smoke.",
  "teaseler - One who uses teasels for raising a nap on cloth. [Written also teaseller, teasler.]",
  "sourish - Somewhat sour; moderately acid; as, sourish fruit; a sourish taste.",
  "corocore - A kind of boat of various forms, used in the Indian Archipelago.",
  "amphicarpous - Producing fruit of two kinds, either as to form or time of ripening.",
  "etymologicon - an etymological dictionary or manual.",
  "spareful - Sparing; chary. [Obs.] Fairfax. -- Spare\"ful*ness, n. [Obs.] Sir P. Sidney.",
  "kitchener - A kitchen servant; a cook. Carlyle.",
  "ice-built - 1. Composed of ice. 2. Loaded with ice. \"Ice-built mountains.\" Gray.",
  "gatehouse - A house connected or associated with a gate.",
  "endurer - One who, or that which, endures or lasts; one who bears, suffers, or sustains.",
  "semitism - A Semitic idiom; a word of Semitic origin. [Written also Shemitism.]",
  "arse - The buttocks, or hind part of an animal; the posteriors; the fundament; the bottom.",
  "callose - Furnished with protuberant or hardened spots.",
  "scoliosis - A lateral curvature of the spine.",
  "emigrator - One who emigrates; am emigrant. [R.]",
  "piment - Wine flavored with spice or honey. See Pigment, 3. [Obs.]",
  "salination - The act of washing with salt water. [R. & Obs..] Greenhill.",
  "metrorrhagia - Profuse bleeding from the womb, esp. such as does not occur at the menstrual period.",
  "hepatocystic - Of or pertaining to the liver and gall bladder; as, the hepatocystic ducts.",
  "rugging - A coarse kind of woolen cloth, used for wrapping, blanketing, etc.",
  "inerudite - Not erudite; unlearned; ignorant.",
  "slakeless - Not capable of being slaked.",
  "transflux - A flowing through, across, or beyond. [R.]",
  "aposteme - An abscess; a swelling filled with purulent matter. [Written corruptly imposthume.]",
  "spastic - Of or pertaining to spasm; spasmodic; especially, pertaining to tonic spasm; tetanic.",
  "biflorous - Bearing two flowers; two-flowered.",
  "dulcamara - A plant (Solanum Dulcamara). See Bittersweet, n., 3 (a).",
  "oxygenium - The technical name of oxygen. [R.]",
  "idyllic - Of or belonging to idyls. I. E. I. e.  Abbreviation of Latin id est, that is.",
  "obstination - Obstinacy; stubbornness. [Obs.] Jer. Taylor.",
  "devitalize - To deprive of life or vitality. -- De*vi`tal*i*za\"tion, n.",
  "litraneter - An instrument for ascertaining the specific gravity of liquids.",
  "superflux - Superabundance; superfluity; an overflowing. [R.] Shak.",
  "hemachate - A species of agate, sprinkled with spots of red jasper.",
  "ectypography - A method of etching in which the design upon the plate is produced in relief.",
  "enchest - To inclose in a chest. Vicars.",
  "constantia - A superior wine, white and red, from Constantia, in Cape Colony.",
  "brevier - A size of type between bourgeous and minion. Note: This line is printed in brevier type.",
  "disinfection - The act of disinfecting; purification from infecting matter.",
  "spiring - Shooting up in a spire or spires. \"The spiring grass.\" Dryton.",
  "choker - 1. One who, or that which, chokes. 2. A stiff wide cravat; a stock. [Slang]",
  "crotchety - Given to crotchets; subject to whims; as, a crotchety man.",
  "hydropathic - Of or pertaining to hydropathy.",
  "adorableness - The quality of being adorable, or worthy of adoration. Johnson.",
  "improbative - Implying, or tending to, improbation.",
  "reasonableness - Quality of being reasonable.",
  "coraled - Having coral; covered with coral.",
  "low-thoughted - Having one's thoughts directed toward mean or insignificant subjects.",
  "discerption - The act of pulling to pieces, or of separating the parts. Bp. Hall.",
  "sublimable - Capable of being sublimed or sublimated. -- Sub*lim\"a*ble*ness, n. Boyle.",
  "chih tai - A Chinese governor general; a tsung tu (which see).",
  "autocoherer - A self-restoring coherer, as a microphonic detector.",
  "granuliform - Having a granular structure; granular; as, granuliform limestone.",
  "denseness - The quality of being dense; density.",
  "reebok - The peele. [Written also rehboc and rheeboc.]",
  "requirable - Capable of being required; proper to be required. Sir M. Hale.",
  "stupefier - One who, or that which, stupefies; a stupefying agent.",
  "annelidous - Of the nature of an annelid.",
  "deoxidation - The act or process of reducing from the state of an oxide.",
  "suable - Capable of being sued; subject by law to be called to answer in court. Story.",
  "videlicet - To wit; namely; -- often abbreviated to viz.",
  "syngraph - A writing signed by both or all the parties to a contract or bond.",
  "preconceit - An opinion or notion formed beforehand; a preconception. Hooker.",
  "desmine - Same as Stilbite. It commonly occurs in bundles or tufts of crystals.",
  "propugn - To contend for; to defend; to vindicate. [Obs.] Hammond.",
  "regeneracy - The state of being regenerated. Hammond.",
  "symbolistical - Characterized by the use of symbols; as, symbolistic poetry.",
  "thunderfish - A large European loach (Misgurnus fossilis).",
  "antrum - A cavern or cavity, esp. an anatomical cavity or sinus. Huxley.",
  "warine - A South American monkey, one of the sapajous.",
  "hystrix - A genus of rodents, including the porcupine.",
  "meteyard - A yard, staff, or rod, used as a measure. [Obs.] Shak.",
  "truth-teller - One who tells the truth. Truth-teller was our England's Alfred named. Tennyson.",
  "siser - Cider. See Sicer. [Obs.] Chaucer.",
  "conchite - A fossil or petrified conch or shell.",
  "garnisher - One who, or that which, garnishes.",
  "statistically - In the way of statistics.",
  "polenta - Pudding made of Indian meal; also, porridge made of chestnut meal. [Italy]",
  "renovel - To renew; to renovate. [Obs.] Chaucer.",
  "characterization - The act or process of characterizing.",
  "interbastation - Patchwork. [Obs.] Dr. J. Smith.",
  "poorness - The quality or state of being poor (in any of the senses of the adjective). Bacon.",
  "salification - The act, process, or result of salifying; the state of being salified.",
  "mesoplast - The nucleus of a cell; mesoblast. Agassix.",
  "actionist - A shareholder in joint-stock company. [Obs.]",
  "thimblerigger - One who cheats by thimblerigging, or tricks of legerdemain.",
  "enharmonically - In the enharmonic style or system; in just intonation.",
  "plumassier - One who prepares or deals in ornamental plumes or feathers.",
  "bushless - Free from bushes; bare. O'er the long backs of the bushless downs. Tennyson.",
  "unaquit - Unrequited. [R. & Obs.] Gower.",
  "eachwhere - Everywhere. [Obs.] The sky eachwhere did show full bright and fair. Spenser.",
  "thereof - Of that or this. In the day that thou eatest thereof, thou shalt surely die. Gen. ii. 17.",
  "lampoonry - The act of lampooning; a lampoon, or lampoons.",
  "balize - A pole or a frame raised as a sea beacon or a landmark.",
  "doggedly - In a dogged manner; sullenly; with obstinate resolution.",
  "campanologist - One skilled in campanology; a bell ringer.",
  "dissimilation - The act of making dissimilar. H. Sweet.",
  "gnarly - Full of knots; knotty; twisted; crossgrained.",
  "envyned - Stored or furnished with wine. [Obs.] Chaucer.",
  "nearly - In a near manner; not remotely; closely; intimately; almost.",
  "decampment - Departure from a camp; a marching off.",
  "colocolo - A South American wild cat (Felis colocolo), of the size of the ocelot.",
  "incharity - Want of charity. [Obs.] Evelyn.",
  "castorite - A variety of the mineral called petalite, from Elba.",
  "whiggarchy - Government by Whigs. [Cont] Swift.",
  "commiserative - Feeling or expressing commiseration. Todd.",
  "catheterize - To operate on with a catheter. Dunglison.",
  "bimaculate - Having, or marked with, two spots.",
  "shelvy - Sloping gradually; shelving. The shore was shelving and shallow. Shak.",
  "lepidopterous - Of or pertaining to the Lepidoptera.",
  "mutilous - Mutilated; defective; imperfect. [Obs.]",
  "acrotic - Pertaining to or affecting the surface.",
  "yellow-golds - A certain plant, probably the yellow oxeye. B. Jonson.",
  "eatage - Eatable growth of grass for horses and cattle, esp. that of aftermath.",
  "misjudge - To judge erroneously or unjustly; to err in judgment; to misconstrue.",
  "stipes - (a) The second joint of a maxilla of an insect or a crustacean. (b) An eyestalk.",
  "skunkish - Like the skunk, especially in odor.",
  "nephridial - of or pertaining to a nephridium.",
  "gallooned - Furnished or adorned with galloon.",
  "immaterialness - The state or quality of being immaterial; immateriality.",
  "monothalmic - Formed from one pistil; -- said of fruits. R. Brown.",
  "resiance - Residence; abode. [Obs.] Bacon.",
  "glead - A live coal. See Gleed. [Archaic]",
  "mistaught - Wrongly taught; as, a mistaught youth. L'Estrange.",
  "bepraise - To praise greatly or extravagantly. Goldsmith.",
  "billposter - One whose occupation is to post handbills or posters in public places.",
  "staminiferous - Bearing or having stamens.",
  "astrotheology - Theology founded on observation or knowledge of the celestial bodies. Derham.",
  "metrometer - An instrument for measuring the size of the womb. Knight.",
  "counterfaisance - See Counterfesance. [Obs.]",
  "ganocephalous - Of or pertaining to the Ganocephala.",
  "permians - A tribe belonging to the Finnic race, and inhabiting a portion of Russia.",
  "pardonably - In a manner admitting of pardon; excusably. Dryden.",
  "opplete - Filled; crowded. [Obs.] Johnson.",
  "subnascent - Growing underneath. [R.] Evelyn.",
  "unthink - To recall or take back, as something thought. Shak.",
  "vicegerency - The office of a vicegerent. South.",
  "overabound - To be exceedingly plenty or superabundant. Pope.",
  "beneficently - In a beneficent manner; with beneficence.",
  "unflinching - Not flinching or shrinking; unyielding. -- Un*flinch\"ing*ly, adv.",
  "vetturino - 1. One who lets or drives a vettura. 2. A vettura.",
  "disauthorize - To deprive of credit or authority; to discredit. [R.] W. Wotton.",
  "gentrie - Nobility of birth or of character; gentility. [Obs.] Chaucer.",
  "stableboy - A boy or man who attends in a stable; a groom; a hostler.",
  "determined - Decided; resolute. \"Adetermined foe.\"\" Sparks.",
  "exciseman - An officer who inspects and rates articles liable to excise duty. Macaulay.",
  "ruralness - The quality or state of being rural.",
  "rostrulum - A little rostrum, or beak, as of an insect.",
  "diminishable - Capable of being diminished or lessened.",
  "gastriloquy - A voice or utterance which appears to proceed from the stomach; ventriloquy.",
  "quantitively - So as to be measurable by quantity; quantitatively.",
  "underskirt - A petticoat; the foundation skirt of a draped dress.",
  "intensiveness - The quality or state of being intensive; intensity. Sir M. Hale.",
  "streite - Narrowly; strictly; straitly. [Obs.]",
  "perispomenon - A word which has the circumflex accent on the last syllable. Goodwin.",
  "scopate - Having the surface closely covered with hairs, like a brush.",
  "obligatoriness - The quality or state of being obligatory.",
  "unnumerable - Innumerable. [Obs.] \"An unnumerable multitude.\" Udall.",
  "allegorization - The act of turning into allegory, or of understanding in an allegorical sense.",
  "incursive - Making an incursion; invasive; aggressive; hostile.",
  "codefendant - A joint defendant. Blackstone.",
  "spatangus - A genus of heart-shaped sea urchins belonging to the Spatangoidea.",
  "unbank - To remove a bank from; to open by, or as if by, the removal of a bank. H. Taylor.",
  "fogyism - The principles and conduct of a fogy. [Colloq.]",
  "serpentiform - Having the form of a serpent.",
  "ludibund - Sportive. [Obs.] -- Lu\"di*bund*ness, n. [Obs.] Dr. H. More.",
  "notopodium - The dorsal lobe or branch of a parapodium. See Parapodium.",
  "biodynamics - The doctrine of vital forces or energy.",
  "odontographic - Of or pertaining to odontography.",
  "beroe - A small, oval, transparent jellyfish, belonging to the Ctenophora.",
  "incorporeity - The quality of being incorporeal; immateriality. Berkeley.",
  "reascent - A returning ascent or ascension; acclivity. Cowper.",
  "accompanist - The performer in music who takes the accompanying part. Busby.",
  "minatorially - In a minatory manner; with threats.",
  "mousquetaire glove - A woman's glove with a long, loosely fitting wrist.",
  "swaip - To walk proudly; to sweep along. [Prov. Eng.] Todd.",
  "rechange - To change again, or change back.",
  "sowbane - The red goosefoot (Chenopodium rubrum), -- said to be fatal to swine.",
  "microphytal - Pertaining to, or of the nature of, microphytes.",
  "unideal - 1. Not ideal; real; unimaginative. 2. Unideaed. [R.] Johnson.",
  "coagulatory - Serving to coagulate; produced by coagulation; as, coagulatory effects. Boyle.",
  "injuriously - In an injurious or hurtful manner; wrongfully; hurtfully; mischievously.",
  "heroelogist - One who treats of heroes. [R.] T. Warton.",
  "fortuneless - Luckless; also, destitute of a fortune or portion. Spenser.",
  "wernerite - The common grayish or white variety of soapolite.",
  "liturgist - One who favors or adheres strictly to a liturgy. Milton.",
  "phytonomy - The science of the origin and growth of plants.",
  "pnyx - The place at Athens where the meetings of the people were held for making decrees, etc.",
  "unburrow - To force from a burrow; to unearth.",
  "blattering - Senseless babble or boasting.",
  "merle - The European blackbird. See Blackbird. Drayton.",
  "water spaniel - A curly-haired breed of spaniels, naturally very fond of the water.",
  "fortunize - To regulate the fortune of; to make happy. [Obs.] Spenser.",
  "subsulphate - A sulphate with an excess of the base.",
  "trifistulary - Having three pipes. Sir T. Browne.",
  "effectless - Without effect or advantage; useless; bootless. Shak. -- Ef*fect\"less*ly, adv.",
  "relicly - In the manner of relics. [Obs.]",
  "centrolinead - An instrument for drawing lines through a point, or lines converging to a center.",
  "trachoma - Granular conjunctivitis due to a specific micrococcus. -- Tra*chom\"a*tous (#), a.",
  "generalia - Generalities; general terms. J. S. Mill.",
  "hordeolum - A small tumor upon the eyelid, resembling a grain of barley; a sty.",
  "inconsistently - In an inconsistent manner.",
  "lordlike - 1. Befitting or like a lord; lordly. 2. Haughty; proud; insolent; arrogant.",
  "neuropteral - Of or pertaining to the Neuroptera.",
  "dimensionless - Without dimensions; having no appreciable or noteworthy extent. Milton.",
  "medicament - Anything used for healing diseases or wounds; a medicine; a healing application.",
  "scutibranchia - Same as Scutibranchiata.",
  "dazzlement - Dazzling flash, glare, or burst of light. Donne.",
  "satanophany - An incarnation of Satan; a being possessed by a demon. [R.] O. A. Brownson.",
  "concurrentness - The state or quality of being concurrent; concurrence.",
  "deperdition - Loss; destruction. [Archaic] Sir T. Browne.",
  "binate - Double; growing in pairs or couples. Gray.",
  "steeplechasing - The act of riding steeple chases.",
  "diverseness - The quality of being diverse.",
  "prelal - Of or pertaining to printing; typographical. [Obs.] Fuller.",
  "erythrolein - A red substance obtained from litmus.",
  "levee en masse - See Levy in mass, under Levy, n.",
  "hayrake - A rake for collecting hay; especially, a large rake drawn by a horse or horses.",
  "satanism - The evil and malicious disposition of Satan; a diabolical sprit. [R.]",
  "sackless - Quiet; peaceable; harmless; innocent. [Obs. or Prov. Eng.]",
  "transanimation - The conveyance of a soul from one body to another. [R.] Fuller.",
  "reshipment - The act of reshipping; also, that which is reshippped.",
  "misdemean - To behave ill; -- with a reflexive pronoun; as, to misdemean one's self.",
  "epilogical - Of or pertaining to an epilogue.",
  "sinological - Relating to the Chinese language or literature.",
  "doorstep - The stone or plank forming a step before an outer door.",
  "dynamometry - The art or process of measuring forces doing work.",
  "bateless - Not to be abated. [Obs.] Shak.",
  "grassation - A wandering about with evil intentions; a rioting. [Obs. & R.] Feltham.",
  "humbuggery - The practice of imposition.",
  "exampless - Exampleless. [Wrongly formed.] B. Jonson.",
  "eikosylene - A liquid hydrocarbon, C20H38, of the acetylene series, obtained from brown coal.",
  "legalism - Strictness, or the doctrine of strictness, in conforming to law.",
  "centime - The hundredth part of a franc; a small French copper coin and money of account.",
  "dureless - Not lasting. [Obs.] Sir W. Raleigh.",
  "succise - Appearing as if a part were cut off at the extremity.",
  "blubbery - 1. Swollen; protuberant. 2. Like blubber; gelatinous and quivering; as, a blubbery mass.",
  "toadyism - The practice of meanly fawning on another; base sycophancy; servile adulation.",
  "leister - A spear armed with three or more prongs, for striking fish. [Scotland]",
  "riverside - The side or bank of a river.",
  "antipathic - Belonging to antipathy; opposite; contrary; allopathic.",
  "enflower - To cover or deck with flowers. [Poetic] These odorous and enflowered fields. B. Jonson.",
  "haytian - Of pertaining to Hayti. -- n.  A native of Hayti. [Written also Haitian.]",
  "salebrosity - Roughness or ruggedness. [Obs.] Feltham.",
  "vibrant - Vibrating; tremulous; resonant; as, vibrant drums. Longfellow.",
  "noctivagant - Going about in the night; night-wandering.",
  "aleuronic - Having the nature of aleurone. D. C. Eaton.",
  "gormandizer - A greedy, voracious eater; a gormand; a glutton.",
  "stonesmickle - The stonechat; -- called also stonesmitch. [Prov. Eng.]",
  "intermediately - In an intermediate manner; by way of intervention.",
  "remble - To remove. [Prov.Eng.] Grose. Tennyson.",
  "hypertrophied - Excessively developed; characterized by hypertrophy.",
  "padge - The barn owl; -- called also pudge, and pudge owl. [Prov. Eng.]",
  "pungy - A small sloop or shallop, or a large boat with sails.",
  "becard - A South American bird of the flycatcher family. (Tityra inquisetor).",
  "gazehound - A hound that pursues by the sight rather than by the scent. Sir W. Scott.",
  "supracretaceous - Lying above the chalk; Supercretaceous.",
  "synomocy - Sworn brotherhood; a society in ancient Greece nearly resembling a modern political club.",
  "searcer - 1. One who sifts or bolts. [Obs.] 2. A searce, or sieve. [Obs.] Holland.",
  "indomitable - Not to be subdued; untamable; invincible; as, an indomitable will, courage, animal.",
  "menthyl - A compound radical forming the base of menthol.",
  "ardassine - A very fine sort of Persian silk.",
  "echinodermatous - Relating to Echinodermata; echinodermal.",
  "nonsane - Unsound; not perfect; as, a person of nonsane memory. Blackstone.",
  "halsening - Sounding harshly in the throat; inharmonious; rough. [Obs.] Carew.",
  "kakistocracy - Government by the worst men.",
  "luteo- - A combining form signifying orange yellow or brownish yellow.",
  "acquisitively - In the way of acquisition.",
  "cupreous - Consisting of copper or resembling copper; coppery.",
  "pistillate - Having a pistil or pistils; -- usually said of flowers having pistils but no stamens.",
  "devicefully - In a deviceful manner. [R.]",
  "mage - A magician. [Archaic] Spenser. Tennyson.",
  "scoppet - To lade or dip out. [Obs.] Bp. Hall.",
  "scrannel - Slight; thin; lean; poor. Having Grate on their scranned pipes of wretched straw. Milton.",
  "osnaburg - A species of coarse linen, originally made in Osnaburg, Germany.",
  "polemy - Warfare; war; hence, contention; opposition. [Obs.]",
  "affranchise - To make free; to enfranchise. Johnson.",
  "slightly - 1. In a slight manner. 2. Slightingly; negligently. [Obs.] Shak.",
  "contrapuntist - One skilled in counterpoint. L. Mason.",
  "consignificant - Having joint or equal signification; synonymous. [R.] Spelman.",
  "tergeminate - Thrice twin; having three pairs of leaflets.",
  "tib-cat - A female cat. [Prov. Eng.] Halliwell.",
  "carefulness - Quality or state of being careful.",
  "priestery - Priests, collectively; the priesthood; -- so called in contempt. [R.] Milton.",
  "cessment - An assessment or tax. [Obs.] Johnson.",
  "sageness - The quality or state of being sage; wisdom; sagacity; prudence; gravity. Ascham.",
  "inmacy - The state of being an inmate. [R.] Craig.",
  "delighter - One who gives or takes delight.",
  "imperspicuity - Want of perspicuity or clearness; vaguness; ambiguity.",
  "probal - Approved; probable. [Obs.] Shak.",
  "voussoir - One of the wedgelike stones of which an arch is composed.",
  "serrator - The ivory gull (Larus eburneus).",
  "dearborn - A four-wheeled carriage, with curtained sides.",
  "infestuous - Mischievous; harmful; dangerous. [Obs.] \"Infestuous as serpents.\" Bacon.",
  "unextricable - Not extricable; inextricable. [Obs.] Dr. H. More.",
  "campestrian - Relating to an open fields; drowing in a field; growing in a field, or open ground.",
  "stoner - 1. One who stones; one who makes an assault with stones. 2. One who walls with stones.",
  "aggrandizable - Capable of being aggrandized.",
  "discoverability - The quality of being discoverable. [R.] Carlyle.",
  "spheroidicity - The quality or state of being spheroidal.",
  "enascent - Coming into being; nascent. [Obs.] Bp. Warburton.",
  "phycography - A description of seaweeds.",
  "meniscal - Pertaining to, or having the form of, a meniscus.",
  "whinock - The small pig of a litter. [Local, U. S.]",
  "bonassus - The aurochs or European bison. See Aurochs.",
  "reprobative - Of or pertaining to reprobation; expressing reprobation.",
  "misquote - To quote erroneously or incorrectly. Shak.",
  "painstaker - One who takes pains; one careful and faithful in all work. Gay.",
  "poitrel - The breastplate of the armor of a horse. See Peytrel. [Obs.] Chaucer.",
  "moplah - One of a class of Mohammedans in Malabar.",
  "props - A game of chance, in which four sea shells, each called a prop, are used instead of dice.",
  "readability - The state of being readable; readableness.",
  "rani - A queen or princess; the wife of a rajah. [Written also ranee.] [India]",
  "immobile - Incapable of being moved; immovable; fixed; stable. Prof. Shedd.",
  "doloroso - Plaintive; pathetic; -- used adverbially as a musical direction.",
  "enlute - To coat with clay; to lute. [Obs.] Chaucer.",
  "induement - The act of induing, or state of being indued; investment; endowment. W. Montagu.",
  "dialyzate - The material subjected to dialysis.",
  "span-new - Quite new; brand-new; fire-new. \"A span-new archbishop's chair.\" Fuller.",
  "bemuffle - To cover as with a muffler; to wrap up. Bemuffled with the externals of religion. Sterne.",
  "anglophobia - Intense dread of, or aversion to, England or the English. -- An\"glo*phobe, n.",
  "eupatorine - A principle or mixture of principles extracted from various species of Eupatorium.",
  "upheaped - Piled up; accumulated. God, which shall repay all with upheaped measure. Udall.",
  "negativity - The quality or state of being negative.",
  "acquiescently - In an acquiescent manner.",
  "stadtholdership - The office or position of a stadtholder.",
  "re-ferment - To ferment, or cause to ferment, again. Blackmore.",
  "amphibiously - Like an amphibious being.",
  "spermatogenesis - The development of the spermatozoids.",
  "raptores - Same as Accipitres. Called also Raptatores.",
  "entomostracous - Belonging to the Entomostracans.",
  "lithologist - One who is skilled in lithology.",
  "jogging - The act of giving a jog or jogs; traveling at a jog.",
  "secernment - The act or process of secreting.",
  "ale silver - A duty payable to the lord mayor of London by the sellers of ale within the city.",
  "oviform - Having the form or figure of an egg; egg-shaped; as, an oviform leaf.",
  "mole-eyed - Having eyes like those of the mole; having imperfect sight.",
  "thearchic - Divinely sovereign or supreme. [R.] He [Jesus] is the thearchic Intelligence. Milman.",
  "nutritial - Pertaining to, or connected with, nutrition; nutritious. [Obs.] Chapman.",
  "regiminal - Of or relating to regimen; as, regiminal rules.",
  "marimonda - A spider monkey (Ateles belzebuth) of Central and South America.",
  "priceite - A hydrous borate of lime, from Oregon.",
  "eruptional - Eruptive. [R.] R. A. Proctor.",
  "septical - Having power to promote putrefaction.",
  "air-drawn - Drawn in air; imaginary. This is the air-drawn dagger. Shak.",
  "corrugation - The act corrugating; contraction into wrinkles or alternate ridges and grooves.",
  "pelican state - Louisiana; -- a nickname alluding to the device on its seal.",
  "capitalization - The act or process of capitalizing.",
  "highmen - Loaded dice so contrived as to turn up high numbers. [Obs] Sir J. Harrington.",
  "oast - A kiln to dry hops or malt; a cockle. Mortimer.",
  "polyrhizous - Having numerous roots, or rootlets.",
  "hinderest - Hindermost; -- superl. of Hind, a. [Obs.] Chaucer.",
  "epipedometry - The mensuration of figures standing on the same base. [Obs.]",
  "salver-shaped - Tubular, with a speading border. See Hypocraterimorphous.",
  "wolfberry - An American shrub (Symphoricarpus occidentalis) which bears soft white berries.",
  "immarcescible - Unfading; lasting. [Obs.] Bp. Hall.",
  "sermoner - A preacher; a sermonizer. [Derogative or Jocose.] Thackeray.",
  "rinker - One who skates at a rink. [Colloq.]",
  "amboyna pine - The resiniferous tree Agathis Dammara, of the Moluccas.",
  "salse - A mud volcano, the water of which is often impregnated with salts, whence the name.",
  "goldie - (a) The European goldfinch. (b) The yellow-hammer.",
  "vatful - As much as a vat will hold; enough to fill a vat.",
  "mansuetude - Tameness; gentleness; mildness. [Archaic]",
  "alfione - An edible marine fish of California (Rhacochilus toxotes).",
  "uniflorous - Bearing one flower only; as, a uniflorous peduncle.",
  "somniloquy - A talking in sleep; the talking of one in a state of somnipathy. [R.] Coleridge.",
  "unproper - Not proper or peculiar; improper. [Obs.] -- Un*prop\"er*ly, adv. [Obs.]",
  "occasionate - To occasion. [Obs.] The lowest may occasionate much ill. Dr. H. More.",
  "senecio - A very large genus of composite plants including the groundsel and the golden ragwort.",
  "typifier - One who, or that which, typifies. Bp. Warburton.",
  "ambrein - A fragrant substance which is the chief constituent of ambergris.",
  "gular - Pertaining to the gula or throat; as, gular plates. See Illust. of Bird, and Bowfin.",
  "funeration - The act of burying with funeral rites. [Obs.] Knatchbull.",
  "tea-saucer - A small saucer in which a teacup is set.",
  "misbileve - Misbelief; unbelief; suspicion. [Obs.] Chaucer.",
  "-arch - A suffix meaning a ruler, as in monarch (a sole ruler).",
  "apologizer - One who makes an apology; an apologist.",
  "hoggerpipe - The upper terminal pipe of a mining pump. Raymond.",
  "somal - A Hamitic people of East Central Africa.",
  "uranometry - A chart or catalogue of fixed stars, especially of stars visible to the naked eye.",
  "snow-white - White as snow; very white. \"Snow-white and rose-red\" Chaucer.",
  "malexecution - Bad execution. D. Webster.",
  "negatory - Expressing denial; belonging to negation; negative. Carlyle.",
  "obsign - To seal; to confirm, as by a seal or stamp. [Obs.] Bradford.",
  "socratism - The philosophy or the method of Socrates.",
  "demonstrability - The quality of being demonstrable; demonstrableness.",
  "glycidic - Pertaining to, or derived from, glycide; as, glycidic acid.",
  "scapiform - Resembling scape, or flower stm.",
  "aheap - In a heap; huddled together. Hood.",
  "creaze - The tin ore which collects in the central part of the washing pit or buddle.",
  "dueling - e act or practice of fighting in single combat. Also adj. [Written also duelling.]",
  "shorage - Duty paid for goods brought on shore. Grabb.",
  "officiant - The officer who officiates or performs an office, as the burial office. Shipley.",
  "scrutoire - A escritoire; a writing desk.",
  "nodding - Curved so that the apex hangs down; having the top bent downward.",
  "dogdraw - The act of drawing after, or pursuing, deer with a dog. Cowell.",
  "unsympathy - Absence or lack of sympathy.",
  "ewry - An office or place of household service where the ewers were formerly kept. [Enq.] Parker.",
  "thankworthiness - The quality or state of being thankworthy.",
  "coroneted - Wearing, or entitled to wear, a coronet; of noble birth or rank.",
  "zoonic - Of or pertaining to animals; obtained from animal substances.",
  "emersed - Standing out of, or rising above, water. Gray.",
  "plication - A folding or fold; a plait. Richardson.",
  "disyoke - To unyoke; to free from a yoke; to disjoin. [Poetic] R. Browning.",
  "rain-tight - So tight as to exclude rain as, a rain-tight roof.",
  "unambiguity - Absence of ambiguity; clearness; perspicuity.",
  "cliented - Supplied with clients. [R.] The least cliented pettifiggers. R. Carew.",
  "scrapepenny - One who gathers and hoards money in trifling sums; a miser.",
  "visored - Wearing a visor; masked. Visored falsehood and base forgery. Milton.",
  "dishouse - To deprive of house or home. \"Dishoused villagers.\" James White.",
  "pilcrow - a paragraph mark, . [Obs.] Tusser.",
  "birkie - A lively or mettlesome fellow. [Jocular, Scot.] Burns.",
  "quietsome - Calm; still. [Obs.] Spenser.",
  "provisionally - By way of provision for the time being; temporarily. Locke.",
  "duncish - Somewhat like a dunce. [R.] -- Dun\"cish*ness, n. [R.]",
  "curviserial - Distributed in a curved line, as leaves along a stem.",
  "gluey - Viscous; glutinous; of the nature of, or like, glue.",
  "syriacism - A Syrian idiom; a Syrianism.",
  "shippen - A stable; a cowhouse. [Obs. or Prov.Eng.]",
  "mispronunciation - Wrong or improper pronunciation.",
  "writability - Ability or capacity to write. [R.] Walpole.",
  "calligrapher - One skilled in calligraphy; a good penman.",
  "uranyl - The radical UO2, conveniently regarded as a residue of many uranium compounds.",
  "fissuration - The act of dividing or opening; the state of being fissured.",
  "nidget - A fool; an idiot, a coward. [Obs.] Camden.",
  "athink - To repent; to displease; to disgust. [Obs.] Chaucer.",
  "belling - A bellowing, as of a deer in rutting time. Johnson.",
  "pyrexical - Of or pertaining to fever; feverish.",
  "acoustician - One versed in acoustics. Tyndall.",
  "homefield - Afield adjacent to its owner's home. Hawthorne.",
  "conoidical - Pertaining to a conoid; having the form of a conoid.",
  "diverting - Amusing; entertaining. -- Di*vert\"ing*ly, adv. -- Di*vert\"ing*ness, n.",
  "pterygopalatine - Of or pertaining to the pterygoid processes and the palatine bones.",
  "axled - Having an axle; -- used in composition. Merlin's agate-axled car. T. Warton.",
  "ragtime - Time characterized by syncopation, as in many negro melodies. [Colloq.]",
  "drawee - The person on whom an order or bill of exchange is drawn; -- the correlative of drawer.",
  "dramatically - In a dramatic manner; theatrically; vividly.",
  "ogdoad - A thing made up of eight parts. Milman.",
  "piacularity - The quality or state of being piacular; criminality; wickedness. De Quincey.",
  "japer - A jester; a buffoon. [Obs.] Chaucer.",
  "belive - Forthwith; speedily; quickly. [Obs.] Chaucer.",
  "waterscape - A sea view; -- distinguished from landscape. [Jocose] Fairholt.",
  "satisfactive - Satisfactory. [Obs.] Satisfactive discernment of fish. Sir T. Browne.",
  "multicolor - Having many, or several, colors.",
  "overleaven - To leaven too much; hence, to change excessively; to spoil. [Obs.]",
  "underwriting - The business of an underwriter,",
  "generable - Capable of being generated or produced. Bentley.",
  "flowerlessness - State of being without flowers.",
  "mockish - Mock; counterfeit; sham. [Obs.]",
  "urethritis - Inflammation of the urethra.",
  "monocarpellary - Consisting of a single carpel, as the fruit of the pea, cherry, and almond.",
  "spirometry - The act or process of measuring the chest capacity by means of a spirometer.",
  "spaniard - A native or inhabitant of Spain.",
  "coverside - A region of country having covers; a hunting country.",
  "optate - To choose; to wish for; to desire. [Obs.] Cotgrave.",
  "blite - A genus of herbs (Blitum) with a fleshy calyx. Blitum capitatum is the strawberry blite.",
  "monarchizer - One who monarchizes; also, a monarchist.",
  "cestode - Of or pertaining to the Cestoidea. -- n.  One of the Cestoidea.",
  "endodermic - Of or pertaining to the endoderm.",
  "chalcography - The act or art of engraving on copper or brass, especially of engraving for printing.",
  "quinologist - One who is versed in quinology.",
  "panorpian - Like, or pertaining to, the genus Panorpa. -- n.  Same as Panorpid.",
  "deprecative - Serving to deprecate; deprecatory. -- Dep\"re*ca*tive*ly, adv.",
  "fluoborate - A salt of fluoboric acid; a fluoboride.",
  "incirclet - A small circle. [Obs.] Sir P. Sidney.",
  "log-ship - A part of the log. See Log-chip, and 2d Log, n., 2.",
  "bilabiate - Having two lips, as the corols of certain flowers.",
  "unregeneracy - The quality or state of being unregenerate. Glanvill.",
  "impest - To affict with pestilence; to infect, as with plague. [Obs.]",
  "twinner - One who gives birth to twins; a breeder of twins. Tusser.",
  "epexegetical - Relating to epexegesis; explanatory; exegetical.",
  "springhalt - A kind of lameness in horse. See Stringhalt. Shak.",
  "vulneration - The act of wounding, or the state of being wounded. [Obs.]",
  "loge - A lodge; a habitation. [Obs.] Chaucer.",
  "posology - The science or doctrine of doses; dosology.",
  "pentagraphical - Pantographic. See Pantograph.",
  "begum - In the East Indies, a princess or lady of high rank. Malcom.",
  "noils - Waste and knots of wool removed by the comb; combings.",
  "simulatory - Simulated, or capable of being simulated. Bp. Hall.",
  "crushing - That crushes; overwhelming. \"The blow must be quick and crushing.\" Macualay.",
  "reconfort - To recomfort; to comfort. [Obs.] Chaucer.",
  "omened - Attended by, or containing, an omen or omens; as, happy-omened day.",
  "metallurgic - Of or pertaining to metallurgy.",
  "good-naturedly - With maldness of temper.",
  "pustulous - Resembling, or covered with, pustules; pustulate; pustular.",
  "unweighing - Not weighing or pondering; inconsiderate. Shak.",
  "analecta - A collection of literary fragments.",
  "misconstruction - Erroneous construction; wrong interpretation. Bp. Stillingfleet.",
  "fortuity - Accident; chance; casualty. D. Forbes (1750).",
  "fetation - The formation of a fetus in the womb; pregnancy.",
  "ectocyst - The outside covering of the Bryozoa.",
  "preputial - Of or pertaining to the prepuce.",
  "propylon - The porch, vestibule, or entrance of an edifice.",
  "experimentation - The act of experimenting; practice by experiment. J. S. Mill.",
  "relationist - A relative; a relation. [Obs.]",
  "snecket - A door latch, or sneck. [Prov. Eng.]",
  "tricoccous - Having three cocci, or roundish carpels. Gray.",
  "mensurability - The quality of being mensurable.",
  "shirtless - Not having or wearing a shirt. Pope. -- Shirt\"less*ness, n.",
  "arrhizous - Destitute of a true root, as a parasitical plant.",
  "garreteer - One who lives in a garret; a poor author; a literary hack. Macaulay.",
  "half-length - Of half the whole or ordinary length, as a picture.",
  "everlastingness - The state of being everlasting; endless duration; indefinite duration.",
  "anabaptism - The doctrine of the Anabaptists.",
  "occision - A killing; the act of killing. [Obs.] Sir M. Hale.",
  "coumarou - The tree (Dipteryx odorata) which bears the tonka bean; also, the bean itself.",
  "micron - A measure of length; the thousandth part of one millimeter; the millionth part of a meter.",
  "overempty - To make too empty; to exhaust. [R.] Carew.",
  "dishcloth - A cloth used for washing dishes.",
  "mountain state - Montana; -- a nickname.",
  "romekin - A drinking cup. [Written also romkin.] [Obs.] Halliwell.",
  "epiphyseal - Pertaining to, or having the nature of, an epiphysis.",
  "wisket - A whisket, or basket. [Prov. Eng.] Ainsworth.",
  "lungoor - A long-tailed monkey (Semnopithecus schislaceus), from the mountainous districts of India.",
  "assident - Usually attending a disease, but not always; as, assident signs, or symptoms.",
  "pernot furnace - A reverberatory furnace with a circular revolving hearth, -- used in making steel.",
  "fiendly - Fiendlike; monstrous; devilish. [Obs.] Chaucer.",
  "xylobalsamum - The dried twigs of a Syrian tree (Balsamodendron Gileadense). U. S. Disp.",
  "icteritous - Yellow; of the color of the skin when it is affected by the jaundice.",
  "exstipulate - Having no stipules. Martyn.",
  "opisthotonos - A tetanic spasm in which the body is bent backwards and stiffened.",
  "hailse - To greet; to salute. [Obs.] P. Plowman.",
  "ascidian - One of the Ascidioidea, or in a more general sense, one of the Tunicata. Also as an adj.",
  "collectiveness - A state of union; mass.",
  "mappery - The making, or study, of maps. [Obs.] Shak.",
  "wing-leaved - Having pinnate or pinnately divided leaves.",
  "prehension - The act of taking hold, seizing, or grasping, as with the hand or other member.",
  "aboral - Situated opposite to, or away from, the mouth.",
  "octolocular - Having eight cells for seeds.",
  "apiologist - A student of bees. [R.] Emerson.",
  "phrenological - Of or pertaining to phrenology. -- Phren`o*log\"ic*al*ly, adv.",
  "withstander - One who withstands, or opposes; an opponent; a resisting power.",
  "trebleness - The quality or state of being treble; as, the trebleness of tones. Bacon.",
  "sejungible - Capable of being disjoined. [Obs.] Bp. Pearson.",
  "cabree - The pronghorn antelope. [Also written cabrit, cabret.]",
  "postscapular - Of or pertaining to the postscapula; infraspinous.",
  "experientialist - One who accepts the doctrine of experientialism. Also used adjectively.",
  "prolegate - The deputy or substitute for a legate.",
  "encomiast - One who praises; a panegyrist. Locke.",
  "chalybite - Native iron carbonate; -- usually called siderite.",
  "dacoity - The practice of gang robbery in India; robbery committed by dacoits.",
  "supernaturally - In a supernatural manner.",
  "aerometer - An instrument for ascertaining the weight or density of air and gases.",
  "tip-up - The spotted sandpiper; -- called also teeter-tail. See under Sandpiper.",
  "luxuriation - The act or process luxuriating.",
  "pegasean - Of or pertaining to Pegasus, or, figuratively, to poetry.",
  "incension - The act of kindling, or the state of being kindled or on fire. Bacon.",
  "underyoke - To subject to the yoke; to make subject. Wyclif.",
  "profluence - Quality of being profluent; course. [R.] Sir H. Wotton.",
  "machinal - Of or pertaining to machines.",
  "randall grass - The meadow fescue (Festuca elatior). See under Grass.",
  "mobocratic - Of, or relating to, a mobocracy.",
  "zincing - The act or process of applying zinc; galvanization.",
  "obduction - .The act of drawing or laying over, as a covering. [Obs.]",
  "disvaluation - Disesteem; depreciation; disrepute. Bacon.",
  "landsturm - That part of the reserve force in Germany which is called out last.",
  "cryptogamic - Of or pertaining to the series Cryptogamia, or to plants of that series.",
  "chirognomy - The art of judging character by the shape and apperance of the hand.",
  "spulzie - Plunder, or booty. [Written also spuilzie, and spulye.] Sir W. Scott.",
  "frigidly - In a frigid manner; coldly; dully; without affection.",
  "remonetize - To restore to use as money; as, to remonetize silver.",
  "decard - To discard. [Obs.] You have cast those by, decarded them. J. Fletcher.",
  "unliken - To make unlike; to dissimilate. [Obs.] Wyclif.",
  "awned - Furnished with an awn, or long bristle-shaped tip; bearded. Gray.",
  "toxicity - The quality or state of being toxic or poisonous; poisonousness.",
  "flagellator - One who practices flagellation; one who whips or scourges.",
  "extuberance - A swelling or rising; protuberance. [R.] Moxon.",
  "self-reproved - Reproved by one's own conscience or one's own sense of guilt.",
  "hyetal - Of or pertaining to rain; descriptive of the distribution of rain, or of rainy regions.",
  "lullingly - In a lulling manner; soothingly.",
  "marketstead - A market place. [Obs.] Drayton.",
  "borborygm - A rumbling or gurgling noise produced by wind in the bowels. Dunglison.",
  "anility - The state of being and old woman; old-womanishness; dotage. \"Marks of anility.\" Sterne.",
  "trochilos - The crocodile bird, or trochil.",
  "hymnal - A collection of hymns; a hymn book.",
  "michery - Theft; cheating. [Obs.] Gower.",
  "metacarpal - Of or pertaining to the metacarpus. -- n.  A metacarpal bone.",
  "saltly - With taste of salt; in a salt manner.",
  "fallax - Cavillation; a caviling. [Obs.] Cranmer.",
  "demonstrableness - The quality of being demonstrable; demonstrability.",
  "internasal - Between the nasal cavities; as, the internasal cartilage.",
  "diastasic - Pertaining to, or consisting of, diastase; as, diastasic ferment.",
  "hulver - Holly, an evergreen shrub or tree.",
  "spiciness - The quality or state of being spicy.",
  "hunk - A large lump or piece; a hunch; as, a hunk of bread. [Colloq.]",
  "wilfulness - See Willful, Willfully, and Willfulness.",
  "immorigerous - Rude; uncivil; disobedient. [Obs.] -- Im`mo*rig\"er*ous*ness, n. [Obs.] Jer. Taylor.",
  "avens - A plant of the genus Geum, esp. Geum urbanum, or herb bennet.",
  "formicary - The nest or dwelling of a swarm of ants; an ant-hill.",
  "myrosin - A ferment, resembling diastase, found in mustard seeds.",
  "fumado - A salted and smoked fish, as the pilchard.",
  "floccular - Of or pertaining to the flocculus.",
  "stentorin - A blue coloring matter found in some stentors. See Stentor, 2.",
  "choiceness - The quality of being of particular value or worth; nicely; excellence.",
  "croustade - Bread baked in a mold, and scooped out, to serve minces upon. Bishop.",
  "cylindrometric - Belonging to a scale used in measuring cylinders.",
  "researchful - Making researches; inquisitive. [R.] Coleridge.",
  "eophyte - A fossil plant which is found in the lowest beds of the Silurian age.",
  "syllogization - A reasoning by syllogisms. [Obs. or R.] Harris.",
  "macrography - Examination or study with the naked eye, as distinguished from micrography.",
  "minishment - The act of diminishing, or the state of being diminished; diminution. [Obs.]",
  "doomsman - A judge; an umpire. [Obs.] Hampole.",
  "extralogical - Lying outside of the domain of logic. -- Ex`tra*log\"ic*al*ly, adv.",
  "ontological - Of or pertaining to ontology.",
  "oscillating current - A current alternating in direction.",
  "octostichous - In eight vertical ranks, as leaves on a stem.",
  "scise - To cut; to penetrate. [Obs.] The wicked steel scised deep in his right side. Fairfax.",
  "rodsman - One who carries and holds a leveling staff, or rod, in a surveying party. G. W. Cable.",
  "detractive - 1. Tending to detractor draw. [R.] 2. Tending to lower in estimation; depreciative.",
  "asset - Any article or separable part of one's assets.",
  "ramollescence - A softening or mollifying. [R.]",
  "dicotyledonous - Having two cotyledons or seed lobes; as, a dicotyledonous plant.",
  "plumery - Plumes, collectively or in general; plumage. [R.] Southey.",
  "strap-shaped - Shaped like a strap; ligulate; as, a strap-shaped corolla.",
  "inverisimilitude - Want of verisimilitude or likelihood; improbability.",
  "revertible - Capable of, or admitting of, reverting or being reverted; as, a revertible estate.",
  "ergat - To deduce logically, as conclusions. [Obs.] Hewyt.",
  "irian - Of or pertaining to the iris. \"Irian nerves.\" Dunglison.",
  "miscomprehend - To get a wrong idea of or about; to misunderstand.",
  "gablet - A small gable, or gable-shaped canopy, formed over a tabernacle, niche, etc.",
  "orchotomy - The operation of cutting out or removing a testicle by the knife; castration.",
  "tangent spoke - A tension spoke of a bicycle or similar wheel, secured tangentially to the hub.",
  "rubidic - Of or pertaining to rubidium; containing rubidium.",
  "pangenetic - Of or pertaining to pangenesis.",
  "pentacron - A solid having five summits or angular points.",
  "chorepiscopal - Pertaining to a chorepiscopus or his change or authority.",
  "cotyledonous - Of or pertaining to a cotyledon or cotyledons; having a seed lobe.",
  "glossologist - One who defines and explains terms; one who is versed in glossology.",
  "refreshful - Full of power to refresh; refreshing. -- Re*fresh\"ful*ly, adv.",
  "country bank - A national bank not in a reserve city. [Colloq., U. S.]",
  "ingulfment - The act of ingulfing, or the state of being ingulfed.",
  "transferrible - Capable of being transferred; transferable.",
  "monomyarian - Of or pertaining to the Monomya. -- n.  One of the Monomya.",
  "physiognomize - To observe and study the physiognomy of. [R.] Southey.",
  "oxidulated - Existing in the state of a protoxide; -- said of an oxide. [R.]",
  "polyiodide - A iodide having more than one atom of iodine in the molecule.",
  "overlaying - A superficial covering; a coating.",
  "bine - The winding or twining stem of a hop vine or other climbing plant.",
  "semipellucidity - The qualiti or state of being imperfectly transparent.",
  "submarshal - An under or deputy marshal.",
  "chloritic - Pertaining to, or containing, chlorite; as, chloritic sand.",
  "omostegite - The part of the carapace of a crustacean situated behind the cervical groove.",
  "soporate - To lay or put to sleep; to stupefy. [Obs.] Cudworth.",
  "seor - A Spanish title of courtesy corresponding to the English Mr. or Sir; also, a gentleman.",
  "quinquefoliate - Having five leaves or leaflets. Gray.",
  "myological - Of or pertaining to myology.",
  "tractility - The quality of being tractile; ductility. Derham.",
  "inorganized - Not having organic structure; devoid of organs; inorganic.",
  "responsorial - Responsory; antiphonal. J. H. Newman.",
  "ganglioform - Having the form of a ganglion.",
  "middle-earth - The world, considered as lying between heaven and hell. [Obs.] Shak.",
  "inaccurately - In an inaccurate manner; incorrectly; inexactly.",
  "discalceation - The act of pulling off the shoes or sandals. [Obs.] Sir T. Browne.",
  "serpentry - 1. A winding like a serpent's. 2. A place inhabited or infested by serpents.",
  "niste - Wist not; knew not. [Obs.] Chaucer.",
  "oscule - One of the excurrent apertures of sponges.",
  "wammel - To move irregularly or awkwardly; to wamble, or wabble. [Prov. Eng.]",
  "undersaturated - Not fully saturated; imperfectly saturated.",
  "shendship - Harm; ruin; also, reproach; disgrace. [Obs.] Chaucer.",
  "cicero - Pica type; -- so called by French printers.",
  "top-tackle - A tackle used in hoisting and lowering the topmast.",
  "befittingly - In a befitting manner; suitably.",
  "lastly - 1. In the last place; in conclusion. 2. at last; finally.",
  "latinitaster - One who has but a smattering of Latin. Walker.",
  "racemulose - Growing in very small racemes.",
  "cherisher - One who cherishes. The cherisher of my flesh and blood. Shak.",
  "deposer - 1. One who deposes or degrades from office. 2. One who testifies or deposes; a deponent.",
  "expiatory - Having power, or intended, to make expiation; atoning; as, an expiatory sacrifice.",
  "nautiform - Shaped like the hull of a ship.",
  "self-exposure - The act of exposing one's self; the state of being so exposed.",
  "convexedly - In a convex form; convexly. Sir T. Browne.",
  "untenant - To remove a tenant from. [R.] Coleridge.",
  "woodless - Having no wood; destitute of wood. Mitford. -- Wood\"less*ness, n.",
  "albanian - Of or pertaining to Albania, a province of Turkey. -- n.  A native of Albania.",
  "pantophagous - Eating all kinds of food.",
  "lay reader - A layman authorized to read parts of the public service of the church.",
  "archaist - 1. Am antiquary. 2. One who uses archaisms.",
  "woolenet - A thin, light fabric of wool. [Written also woollenet, woolenette, and woollenette.]",
  "drearihead - Affliction; dreariness. [Obs.] Spenser.",
  "attestive - Attesting; furnishing evidence.",
  "trickster - One who tricks; a deceiver; a tricker; a cheat.",
  "funky - Pertaining to, or characterized by, great fear, or funking. [Colloq. Eng.]",
  "unedge - To deprive of the edge; to blunt. J. Fletcher.",
  "antihypnotic - Tending to prevent sleep. -- n.  An antihypnotic agent.",
  "pilfery - Petty theft. [R.] Sir T. North.",
  "numismatic - Of or pertaining to coins; relating to the science of coins or medals.",
  "undersleeve - A sleeve of an under-garment; a sleeve worn under another,",
  "quinch - To stir; to wince. [Obs.] Spenser.",
  "cramoisie - Crimson. [Obs.] A splendid seignior, magnificent in cramoisy velevet. Motley.",
  "doting - That dotes; silly; excessively fond. -- Dot\"ing*ly, adv. -- Dot\"ing*ness, n.",
  "praescutum - Same as Preoral, Prepubis, Prescapula, etc.",
  "paronomastical - Of or pertaining to paronomasia; consisting in a play upon words.",
  "scolding - a. & n. from Scold, v. Scolding bridle, an iron frame. See Brank, n., 2.",
  "fanal - A lighthouse, or the apparatus placed in it for giving light.",
  "paleornithology - The branch of paleontology which treats of fossil birds.",
  "disembarkation - The act of disembarking.",
  "arpine - An arpent. [Obs.] Webster (1623).",
  "wronger - One who wrongs or injures another. Shak. \"Wrongers of the world.\" Tennyson.",
  "floran - Tin ore scarcely perceptible in the stone; tin ore stamped very fine. Pryce.",
  "homonomy - The homology of parts arranged on transverse axes. Haeckel.",
  "oxygenic - Pertaining to, containing, or resembling, oxygen; producing oxygen.",
  "aurigal - Of or pertaining to a chariot. [R.]",
  "silure - A fish of the genus Silurus, as the sheatfish; a siluroid.",
  "big-wigged - characterized by pomposity of manner. [Eng.]",
  "outmeasure - To exceed in measure or extent; to measure more than. Sir T. Browne.",
  "entophyte - A vegetable parasite subsisting in the interior of the body.",
  "spongeous - Resembling sponge; having the nature or qualities of sponge.",
  "injucundity - Unpleassantness; disagreeableness. [Obs.] Cockeram.",
  "dysaesthesia - Impairment of any of the senses, esp. of touch.",
  "mother-in-law - The mother of one's husband or wife.",
  "deintevous - Rare; excellent; costly. [Obs.] Chaucer.",
  "dipyrenous - Containing two stones or nutlets.",
  "trinoctial - Lasting during three nights; comprising three nights.",
  "preorder - To order to arrange beforehand; to foreordain. Sir W. Hamilton.",
  "stableness - The quality or state of being stable, or firmly established; stability.",
  "foolhardiness - Courage without sense or judgment; foolish rashness; recklessness. Dryden.",
  "fowler - A sportsman who pursues wild fowl, or takes or kills for food.",
  "humanization - The act of humanizing. M. Arnold.",
  "barken - Made of bark. [Poetic] Whittier.",
  "helicine - Curled; spiral; helicoid; -- applied esp. to certain arteries of the penis.",
  "seizer - One who, or that which, seizes.",
  "mumpish - Sullen, sulky. -- Mump\"ish*ly, adv. -- Mump\"ish*ness, n.",
  "pollinctor - One who prepared corpses for the funeral.",
  "litigiousness - The state of being litigious; disposition to engage in or carry on lawsuits.",
  "legator - A testator; one who bequeaths a legacy. Dryden.",
  "misobedience - Mistaken obedience; disobedience. [Obs.] Milton.",
  "fiddlewood - The wood of several West Indian trees, mostly of the genus Citharexylum.",
  "heterophemist - One liable to the fault of heterophemy.",
  "storybook - A book containing stories, or short narratives, either true or false.",
  "siling - from Sile to strain. [Obs. or Prov.Eng.] Siling dish, a colander. [Obs. or Prov. Eng.]",
  "lepidopteral - Of or pertaining to the Lepidoptera.",
  "afflation - A blowing or breathing on; inspiration.",
  "defibrinate - To deprive of fibrin, as fresh blood or lymph by stirring with twigs.",
  "dispreader - One who spreads abroad. Dispreaders both of vice and error. Milton.",
  "heuristic - Serving to discover or find out.",
  "endoplastica - A group of Rhizopoda having a distinct nucleus, as the am",
  "tubivalve - A shell or tube formed by an annelid, as a serpula.",
  "trammeler - 1. One who uses a trammel net. Nares. 2. One who, or that which, trammels or restrains.",
  "jubilar - Pertaining to, or having the character of, a jubilee. [R.] Bp. Hall.",
  "deedful - Full of deeds or exploits; active; stirring. [R.] \"A deedful life.\" Tennyson.",
  "piny - Abounding with pines. [Written also piney.] \"The piny wood.\" Longfellow.",
  "repetitional - Of the nature of, or containing, repetition. [R.]",
  "antanagoge - A figure which consists in answering the charge of an adversary, by a counter charge.",
  "pericystitis - Inflammation of the tissues surrounding the bladder.",
  "humph - An exclamation denoting surprise, or contempt, doubt, etc.",
  "didactics - The art or science of teaching.",
  "recoct - To boil or cook again; hence, to make over; to vamp up; to reconstruct. [Obs.] Jer. Taylor.",
  "swanny - Swanlike; as, a swanny glossiness of the neck. Richardson.",
  "equipedal - Equal-footed; having the pairs of feet equal.",
  "unlikeliness - The quality or state of being unlikely.",
  "mesquite bean - The pod or seed of the mesquite.",
  "hereabouts - 1. About this place; in this vicinity. 2. Concerning this. [Obs.]",
  "intercondyloid - Between condyles; as, the intercondylar fossa or notch of the femur.",
  "interrelated - Having a mutual or reciprocal relation or parallelism; correlative.",
  "endecagon - A plane figure of eleven sides and angles.",
  "typolite - A stone or fossil which has on it impressions or figures of plants and animals.",
  "underside - The lower or lowest side of anything. Paley.",
  "redisseize - To disseize anew, or a second time. [Written also redisseise.]",
  "woodness - Anger; madness; insanity; rage. [Obs.] Spenser. Woodness laughing in his rage. Chaucer.",
  "medicinable - Medicinal; having the power of healing. [Obs.] Shak.",
  "quitter - 1. One who quits. 2. A deliverer. [Obs.] Ainsworth.",
  "nousel - To insnare; to entrap. [Obs.] Johnson.",
  "chloasma - A cutaneous affection characterized by yellow or yellowish brown pigmented spots.",
  "disinsure - To render insecure; to put in danger. [Obs.] Fanshawe.",
  "whaleboat - A long, narrow boat, sharp at both ends, used by whalemen.",
  "inconscionable - Unconscionable. [Obs.] Spenser.",
  "arbitrarious - Arbitrary; despotic. [Obs.] -- Ar`bi*tra\"*ri*ous*ly, adv. [Obs.]",
  "conterraneous - Of or belonging to the same country. Howell.",
  "clergeon - A chorister boy. [Obs.] Chaucer.",
  "inauthoritative - Without authority; not authoritative.",
  "slanderer - One who slanders; a defamer; a calumniator. Jer. Taylor.",
  "soaking - Wetting thoroughly; drenching; as, a soaking rain. -- Soak\"ing*ly, adv.",
  "redhoop - The male of the European bullfinch. [Prov. Eng.]",
  "fraken - A freckle. [Obs.] A few fraknes in his face. Chaucer.",
  "pickaninny - A small child; especially, a negro or mulatto infant. [U.S. & West Indies]",
  "milestone - A stone serving the same purpose as a milepost.",
  "melaphyre - Any one of several dark-colored augitic, eruptive rocks allied to basalt.",
  "fathership - The state of being a father; fatherhood; paternity.",
  "recumbence - The act of leaning, resting, or reclining; the state of being recumbent.",
  "doorstead - Entrance or place of a door. [Obs. or Local] Bp. Warburton.",
  "miscensure - To misjudge. [Obs.] Daniel. -- n.  Erroneous judgment. [Obs.] Sylvester.",
  "insole - The inside sole of a boot or shoe; also, a loose, thin strip of leather, felt, etc., placed",
  "monothalaman - A foraminifer having but one chamber.",
  "sparpiece - The collar beam of a roof; the spanpiece. Gwilt.",
  "parentation - Something done or said in honor of the dead; obsequies. [Obs.] Abp. Potter.",
  "self-depraved - Corrupted or depraved by one's self. Milton.",
  "boastingly - Boastfully; with boasting. \"He boastingly tells you.\" Burke.",
  "trawler - 1. One who, or that which, trawls. 2. A fishing vessel which trails a net behind it.",
  "sweet-sop - A kind of custard apple (Anona squamosa). See under Custard.",
  "anemometry - The act or process of ascertaining the force or velocity of the wind.",
  "chillness - Coolness; coldness; a chill. Death is the chillness that precedes the dawn. Longfellow.",
  "immensurability - The quality of being immensurable.",
  "seaside - The land bordering on, or adjacent to, the sea; the seashore. Also used adjectively.",
  "asitia - Want of appetite; loathing of food.",
  "underdealing - Crafty, unfair, or underhand dealing; unfair practice; trickery. Milton.",
  "oxysulphuret - An oxysulphide. [Obsolescent]",
  "pansclavism - See Panslavic, Panslavism, etc.",
  "airman - A man who ascends or flies in an aircraft; a flying machine pilot.",
  "unleash - To free from a leash, or as from a leash; to let go; to release; as, to unleash dogs.",
  "rappel - The beat of the drum to call soldiers to arms.",
  "evangelicism - Evangelical principles; evangelism.",
  "immix - To mix; to mingle. [R.] Amongst her tears immixing prayers meek. Spenser.",
  "tercel - See Tiercel. Called also tarsel, tassel. Chaucer.",
  "outstrike - To strike out; to strike faster than. Shak.",
  "lathy - Like a lath; long and slender. A lathy horse, all legs and length. R. Browning.",
  "photo - A contraction of Photograph. [Colloq.]",
  "contemptuousness - Disposition to or manifestion of contempt; insolence; haughtiness.",
  "handbreadth - A space equal to the breadth of the hand; a palm. Ex. xxxvii. 12.",
  "geophagism - The act or habit of eating earth. See Dirt eating, under Dirt. Dunglison.",
  "water pepper - (a) Smartweed. (b) Waterwort.",
  "schetic - Of or pertaining to the habit of the body; constitutional. [Obs.] Cudworth.",
  "phonascetics - Treatment for restoring or improving the voice.",
  "quarterpace - A platform of a staircase where the stair turns at a right angle only. See Halfpace.",
  "tsung-li yamen - The board or department of foreign affairs in the Chinese government. See Yamen.",
  "mediative - Pertaining to mediation; used in mediation; as, mediative efforts. Beaconsfield.",
  "highflier - One who is extravagant in pretensions, opinions, or manners. Swift.",
  "speckledness - The quality of being speckled.",
  "nosethirl - Nostril. [Obs.] [Written also nosethurl, nosthrill.] Chaucer.",
  "deteriority - Worse state or quality; inferiority. \"The deteriority of the diet.\" [R.] Ray.",
  "renard - A fox; -- so called in fables or familiar tales, and in poetry. [Written also reynard.]",
  "propodial - Of or pertaining to the propodialia, or the parts of the limbs to which they belong.",
  "oligarchist - An advocate or supporter of oligarchy.",
  "allice - The European shad (Clupea vulgaris); allice shad. See Alose.",
  "heliogram - A message transmitted by a heliograph.",
  "freemasonry - The institutions or the practices of freemasons.",
  "raider - One who engages in a raid. [U.S.]",
  "aswail - The sloth bear (Melursus labiatus) of India.",
  "threnode - A threne, or threnody; a dirge; a funeral song.",
  "decarbonizer - He who, or that which, decarbonizes a substance.",
  "canzonet - A short song, in one or more parts.",
  "sororicide - The murder of one's sister; also, one who murders or kills one's own sister. Johnson.",
  "hindmost - Furthest in or toward the rear; last. \"Rachel and Joseph hindermost.\" Gen. xxxiii. 2.",
  "holoblast - an ovum composed entirely of germinal matter. See Meroblast.",
  "septisyllable - A word of seven syllables.",
  "ophthalmological - Of or pertaining to ophthalmology.",
  "nemoral - Of or pertaining to a wood or grove. [R.]",
  "polymorphy - Existence in many forms; polymorphism.",
  "upshoot - To shoot upward. \"Trees upshooting high.\" Spenser.",
  "mausoleum - A magnificent tomb, or stately sepulchral monument.",
  "cronel - The iron head of a tilting spear.",
  "overscrupulousness - The quality or state of being overscrupulous; excess of scrupulousness.",
  "infringer - One who infringes or violates; a violator. Strype.",
  "disappendency - A detachment or separation from a former connection. [R.]",
  "fungin - A name formerly given to cellulose found in certain fungi and mushrooms.",
  "proscriber - One who, or that which, proscribes, denounces, or prohibits.",
  "extancy - The state of rising above others; a projection. Evelyn. Boyle.",
  "inturgescence - A swelling; the act of swelling, or state of being swelled. [Obs.] Sir T. Browne.",
  "knightage - To body of knights, taken collectively.",
  "carper - One who carps; a caviler. Shak.",
  "pot-sure - Made confident by drink. [Obs.]",
  "dolichocephaly - The quality or condition of being dolichocephalic.",
  "gastrulation - The process of invagination, in embryonic development, by which a gastrula is formed.",
  "indivisibility - The state or property of being indivisible or inseparable; inseparability. Locke.",
  "tachograph - A recording or registering tachometer; also, its autographic record.",
  "poematic - Pertaining to a poem, or to poetry; poetical. [R.] Coleridge.",
  "corcle - The heart of the seed; the embryo or germ. [Obs.]",
  "unsuit - Not to suit; to be unfit for. [Obs.] Quarles.",
  "lepidoted - Having a coat of scurfy scales, as the leaves of the oleaster.",
  "vaimure - An outer, or exterior. wall. See Vauntmure. [Obs.] Hakluyt.",
  "anemographic - Produced by an anemograph; of or pertaining to anemography.",
  "onomantic - Of or pertaining to onomancy. [R.]",
  "autochthony - An aboriginal or autochthonous condition.",
  "floweret - A small flower; a floret. Shak.",
  "alehouse - A house where ale is retailed; hence, a tippling house. Macaulay.",
  "crustated - Covered with a crust; as, crustated basalt.",
  "simulator - One who simulates, or feigns. De Quincey.",
  "directorate - The office of director; also, a body of directors taken jointly.",
  "commark - The frontier of a country; confines. [Obs.] Shelton.",
  "periostracum - A chitinous membrane covering the exterior of many shells; -- called also epidermis.",
  "shard-borne - Borne on shards or scaly wing cases. \"The shard-borne beetle.\" Shak.",
  "lavishness - The quality or state of being lavish.",
  "lapstone - A stone for the lap, on which shoemakers beat leather.",
  "bonitary - Beneficial, as opposed to statutory or civil; as, bonitary dominion of land.",
  "frolicky - Frolicsome. [Obs.] Richardson.",
  "misbear - To carry improperly; to carry (one's self) wrongly; to misbehave. [Obs.] Chaucer.",
  "isotrimorphism - Isomorphism between the three forms, severally, of two trimorphous substances.",
  "steeliness - The quality of being steely.",
  "barranca - A ravine caused by heavy rains or a watercourse. [Texas & N. Mex.]",
  "overfly - To cross or pass over by flight. Byron.",
  "grandiosity - The state or quality of being grandiose,",
  "whort - The whortleberry, or bilberry. See Whortleberry (a).",
  "misdemeanant - One guilty of a misdemeanor. Sydney Smith.",
  "frustrative - Tending to defeat; fallacious. [Obs.] Ainsworth.",
  "petroglyphy - The art or operation of carving figures or inscriptions on rock or stone.",
  "canonicalness - The quality of being canonical; canonicity. Bp. Burnet.",
  "peroxidation - Act, process, or result of peroxidizing; oxidation to a peroxide.",
  "politicaster - A petty politician; a pretender in politics. Milton.",
  "vandalic - Of or pertaining to the Vandals; resembling the Vandals in barbarism and destructiveness.",
  "superchemical - Above or beyond chemistry; inexplicable by chemical laws. J. Le Conte.",
  "isosulphocyanate - A salt of isosulphocyanic acid.",
  "scarcement - An offset where a wall or bank of earth, etc., retreats, leaving a shelf or footing.",
  "pectoriloquial - Pertaining to, or of the nature of, pectoriloquy.",
  "colloquialism - A colloquial expression, not employed in formal discourse or writing.",
  "spineback - A fish having spines in, or in front of, the dorsal fins.",
  "dunderhead - A dunce; a numskull; a blockhead. Beau. & Fl.",
  "farcilite - Pudding stone. [Obs.] Kirwan.",
  "sea-walled - Surrounded, bounded, or protected by the sea, as if by a wall. Shak.",
  "puerileness - The quality of being puerile; puerility.",
  "diffinitive - Definitive; determinate; final. [Obs.] Sir H. Wotton.",
  "bon - Good; valid as security for something.",
  "ularburong - A large East Indian nocturnal tree snake (Dipsas dendrophila). It is not venomous.",
  "bitake - To commend; to commit. [Obs.] Chaucer.",
  "postzygapophysis - A posterior zygapophysis."
]