export default [
  "apocrustic - Astringent and repellent. -- n.  An apocrustic medicine.",
  "swaggy - Inclined to swag; sinking, hanging, or leaning by its weight. Sir T. Browne.",
  "massagist - One who practices massage; a masseur or masseuse.",
  "petroleuse - One who makes use of petroleum for incendiary purposes.",
  "outlustre - To excel in brightness or luster. Shak.",
  "synovitis - Inflammation of the synovial membrane.",
  "attempter - 1. One who attempts; one who essays anything. 2. An assailant; also, a temper. [Obs.]",
  "recombination - Combination a second or additional time.",
  "asepsis - State of being aseptic; the methods or processes of asepticizing.",
  "limitaneous - Of or pertaining to a limit. [Obs.]",
  "boracic - Pertaining to, or produced from, borax; containing boron; boric; as, boracic acid.",
  "eagle-sighted - Farsighted and strong-sighted; sharp-sighted. Shak.",
  "barbaresque - Barbaric in form or style; as, barbaresque architecture. De Quincey.",
  "sciolous - Knowing superficially or imperfectly. Howell.",
  "economically - With economy; with careful management; with prudence in expenditure.",
  "approachableness - The quality or state of being approachable; accessibility.",
  "casemated - Furnished with, protected by, or built like, a casemate. Campbell.",
  "vernicose - Having a brilliantly polished surface, as some leaves.",
  "deaf-mutism - The condition of being a deaf-mute.",
  "inirritative - Not accompanied with excitement; as, an inirritative fever. E. Darwin.",
  "pediculus - A genus of wingless parasitic Hemiptera, including the common lice of man. See Louse.",
  "viperoid - Like or pertaining to the vipers.",
  "contributive - Contributing, or tending to contribute. Fuller.",
  "loller - 1. One who lolls. 2. An idle vagabond. [Obs.] Piers Plowman. 3. A Lollard.",
  "hook-billed - Having a strongly curved bill.",
  "detonize - To explode, or cause to explode; to burn with an explosion; to detonate.",
  "high-mindedness - The quality of being highminded; nobleness; magnanimity.",
  "deglutinate - To loosen or separate by dissolving the glue which unties; to unglue.",
  "dissolvability - Capacity of being dissolved; solubility. Richardson.",
  "candidness - The quality of being candid.",
  "corruptly - In a corrupt manner; by means of corruption or corrupting influences; wronfully.",
  "lichenographical - Of or pertaining to lichenography.",
  "overskirt - An upper skirt, shorter than the dress, and usually draped.",
  "redressive - Tending to redress. Thomson.",
  "coscoroba - A large, white, South American duck, of the genus Cascoroba, resembling a swan.",
  "excusation - Excuse; apology. [Obs.] Bacon.",
  "unwares - Unawares; unexpectedly; -- sometimes preceded by at. [Obs.] Holinshed.",
  "nonvascular - Destitute of vessels; extravascular.",
  "towser - A familiar name for a dog. [ Written also Towzer. ]",
  "daglock - A dirty or clotted lock of wool on a sheep; a taglock.",
  "erasement - The act of erasing; a rubbing out; expunction; obliteration. Johnson.",
  "graveclothes - The clothes or dress in which the dead are interred.",
  "gnomonically - According to the principles of the gnomonic projection.",
  "philatelic - Of or pertaining to philately.",
  "gemmiflorate - Having flowers like buds.",
  "tumular - Consisting in a heap; formed or being in a heap or hillock. Pinkerton.",
  "nempne - To name or call. [Obs.] Chaucer.",
  "acataleptic - Incapable of being comprehended; incomprehensible.",
  "misreckoning - An erroneous computation.",
  "substantials - Essential parts. Ayliffe.",
  "noncommunion - Neglect or failure of communion.",
  "rhymester - A rhymer; a maker of poor poetry. Bp. Hall. Byron.",
  "steerless - Having no rudder. [Obs.] Chaucer.",
  "sciolism - The knowledge of a sciolist; superficial knowledge.",
  "symmetrist - One eminently studious of symmetry of parts. Sir H. Wotton.",
  "condisciple - A schoolfellow; a fellow-student. [R.]",
  "altitudinarian - Lofty in doctrine, aims, etc. [R.] Coleridge.",
  "socially - In a social manner; sociably.",
  "bijugate - Having two pairs, as of leaflets.",
  "conterminate - Having the same bounds; conterminous. [Obs.] B. Jonson.",
  "drumble - 1. To be sluggish or lazy; to be confused. [Obs.] Shak. 2. To mumble in speaking. [Obs.]",
  "oscillancy - The state of oscillating; a seesaw kind of motion. [R.]",
  "scampish - Of or like a scamp; knavish; as, scampish conduct.",
  "bumblepuppy - 1.  The old game of nineholes. 2.  (Card Playing) Whist played in an unscientific way.",
  "demonomy - The dominion of demons. [R.] Sir T. Herbert.",
  "conspirer - One who conspires; a conspirator.",
  "madbrained - Disordered in mind; hot-headed. Shak.",
  "pterodactyl - An extinct flying reptile; one of the Pterosauria. See Illustration in Appendix.",
  "sharpshooter - One skilled in shooting at an object with exactness; a good marksman.",
  "rumorer - A teller of news; especially, one who spreads false reports. Shak.",
  "lienteric - Of or pertaining to, or of the nature of, a lientery. -- n. (Med.)  A lientery. Grew.",
  "inustion - The act of burning or branding. [Obs.] T. Adams.",
  "animist - One who maintains the doctrine of animism.",
  "pantofle - A slipper for the foot. [Written also pantable and pantoble.]",
  "rectus - A straight muscle; as, the recti of the eye.",
  "phoebus - 1. (Class. Myth.)  Apollo; the sun god. 2. The sun. \"Phoebus 'gins arise.\" Shak.",
  "impecunious - Not having money; habitually without money; poor. An impecunious creature. B. Jonson.",
  "covenable - Fit; proper; suitable. [Obs.] \"A covenable day.\" Wyclif (Mark vi. 21).",
  "objectivation - Converting into an object.",
  "marmolite - A thin, laminated variety of serpentine, usually of a pale green color.",
  "after-witted - Characterized by afterwit; slow-witted. Tyndale.",
  "abusion - Evil or corrupt usage; abuse; wrong; reproach; deception; cheat. Chaucer.",
  "predation - The act of pillaging. E. Hall.",
  "spelunc - A cavern; a cave. [Obs.] Piers Plowman.",
  "unprayable - Not to be influenced or moved by prayers; obdurate. [R.] Wyclif.",
  "pedi- - Combining forms from L. pes, pedis, foot, as pedipalp, pedireme, pedometer.",
  "spottedness - State or quality of being spotted.",
  "entomb - To deposit in a tomb, as a dead body; to bury; to inter; to inhume. Hooker.",
  "newsboy - A boy who distributes or sells newspaper.",
  "phytogeny - The doctrine of the generation of plants.",
  "senatusconsult - A decree of the Roman senate.",
  "broken-winded - Having short breath or disordered respiration, as a horse.",
  "misestimate - To estimate erroneously. J. S. Mill.",
  "cuneal - Relating to a wedge; wedge-shaped.",
  "equiponderous - Having equal weight. Bailey.",
  "inhold - To have inherent; to contain in itself; to possess. [Obs.] Sir W. Raleigh.",
  "elocular - Having but one cell, or cavity; not divided by a septum or partition.",
  "quakiness - The state of being quaky; liability to quake.",
  "lithoidal - Like a stone; having a stony structure.",
  "bock beer - A strong beer, originally made in Bavaria. [Also written buck beer.]",
  "laryngoscopy - The art of using the laryngoscope; investigations made with the laryngoscope.",
  "estrangedness - State of being estranged; estrangement. Prynne.",
  "palmatisect - Divided, as a palmate leaf, down to the midrib, so that the parenchyma is interrupted.",
  "swordman - A swordsman. \"Sinewy swordmen.\" Shak.",
  "ogive - The arch or rib which crosses a Gothic vault diagonally.",
  "saturday - The seventh or last day of the week; the day following Friday and preceding Sunday.",
  "egremoin - Agrimony (Agrimonia Eupatoria). [Obs.] Chaucer.",
  "infective - Infectious. Beau. & Fl. True love . . . hath an infective power. Sir P. Sidney.",
  "demirelief - Half relief. See Demi-rilievo.",
  "monopolist - One who monopolizes; one who has a monopoly; one who favors monopoly.",
  "terpin - A white crystalline substance regarded as a hydrate of oil of turpentine.",
  "deathsman - An executioner; a headsman or hangman. [Obs.] Shak.",
  "unreserve - Absence of reverse; frankness; freedom of communication. T. Warton.",
  "turribant - A turban. [Obs.] With hundred turrets like a turribant. Spenser.",
  "demiwolf - A half wolf; a mongrel dog, between a dog and a wolf.",
  "prostyle - Having columns in front. -- n.  A prostyle portico or building.",
  "solidare - A small piece of money. [Obs.] Shak.",
  "revisit - 1. To visit again. Milton. 2. To revise. [Obs.] Ld. Berners.",
  "vinegary - Having the nature of vinegar; sour; unamiable.",
  "necronite - Fetid feldspar, a mineral which, when struck, exhales a fetid odor.",
  "playing - a. & vb. n. of Play. Playing cards. See under Card.",
  "accendible - Capable of being inflamed or kindled; combustible; inflammable. Ure.",
  "sadducaic - Pertaining to, or like, the Sadducees; as, Sadducaic reasonings.",
  "glassiness - The quality of being glassy.",
  "commemorable - Worthy to be commemorated.",
  "extance - Outward existence. [Obs.] Sir T. Browne.",
  "inconcinnous - Not concinnous; unsuitable; discordant. [Obs.] Cudworth.",
  "thyrotomy - The operation of cutting into the thyroid cartilage.",
  "disinterestedly - In a disinterested manner; without bias or prejudice.",
  "runghead - The upper end of a floor timber in a ship.",
  "sarcotic - Producing or promoting the growth of flesh. [R.] -- n.  A sarcotic medicine. [R.]",
  "somali - A Hamitic people of East Central Africa.",
  "rhabarbarate - Impregnated or tinctured with rhubarb. Floyer.",
  "profoundly - In a profound manner. Why sigh you so profoundly Shak.",
  "suffraganship - The office of a suffragan.",
  "amylometer - Instrument for determining the amount of starch in a substance.",
  "histolysis - The decay and dissolution of the organic tissues and of the blood.",
  "phyllopod - One of the Phyllopoda. Note: [Also used adjectively.]",
  "grammaticize - To render grammatical. Fuller.",
  "trierarchy - The office duty of a trierarch.",
  "substitutionary - Of or pertaining to substitution; substitutional.",
  "minacity - Disposition to threaten. [R.]",
  "irreparability - The quality or state of being irreparable; irreparableness. Sterne.",
  "stork-billed - Having a bill like that of the stork.",
  "exaggerating - That exaggerates; enlarging beyond bounds. -- Ex*ag\"ger*a`ting*ly, adv.",
  "absently - In an absent or abstracted manner.",
  "climatize - To acclimate or become acclimated.",
  "lighterman - A person employed on, or who manages, a lighter.",
  "undoer - One who undoes anything; especially, one who ruins another.",
  "bengali - The language spoken in Bengal.",
  "horribly - In a manner to excite horror; dreadfully; terribly.",
  "abrogator - One who repeals by authority.",
  "subjectist - One skilled in subjective philosophy; a subjectivist.",
  "spado - 1. Same as Spade, 2. 2. (Law)  An impotent person.",
  "vivisect - To perform vivisection upon; to dissect alive. [Colloq.] Pop. Sci. Monthly.",
  "ignigenous - Produced by the action of fire, as lava. [R.]",
  "ailantus - A genus of beautiful trees, natives of the East Indies. The tree imperfectly di",
  "confervoid - Like, or related to, the confervae. Loudon.",
  "arched - Made with an arch or curve; covered with an arch; as, an arched door.",
  "reichsstand - A free city of the former German empire.",
  "galpe - To gape,; to yawn. [Obs.] Chaucer.",
  "bipeltate - Having a shell or covering like a double shield.",
  "unvisard - To take the vizard or mask from; to unmask. [Written also unvizard.] [Obs.] Milton.",
  "orthopedist - One who prevents, cures, or remedies deformities, esp. in children.",
  "decidable - Capable of being decided; determinable.",
  "syphilitically - In a syphilitic manner; with venereal disease.",
  "cyanophyll - A blue coloring matter supposed by some to be one of the component parts ofchlorophyll.",
  "kingship - The state, office, or dignity of a king; royalty. Landor.",
  "spermaphore - That part of the ovary from which the ovules arise; the placenta.",
  "pillowcase - A removable case or covering for a pillow, usually of white linen or cotton cloth.",
  "prudentiality - The quality or state of being prudential. Sir T. Browne.",
  "drusy - Covered with a large number of minute crystals.",
  "expeditely - In expedite manner; expeditiously.",
  "inexecrable - That can not be execrated enough. [R.]",
  "agonist - One who contends for the prize in public games. [R.]",
  "dies non - A day on which courts are not held, as Sunday or any legal holiday.",
  "osteosclerosis - Abnormal hardness and density of bone.",
  "lithotomy - The operation, art, or practice of cutting for stone in the bladder.",
  "cressy - Abounding in cresses. The cressy islets white in flower. Tennyson.",
  "tramble - To wash, as tin ore, with a shovel in a frame fitted for the purpose. Smart.",
  "yliche - Like; alike. [Obs.] \"All . . . yliche good.\" Chaucer.",
  "guimpe - A kind of short chemisette, worn with a low-necked dress.",
  "unsonsy - Not soncy (sonsy); not fortunate. [Scot.]",
  "ungenitured - Destitute of genitals; impotent. [R.] Shak.",
  "howlet - An owl; an owlet. [Written also houlet.] R. Browning.",
  "thomas process - Same as Basic process, above.",
  "corporature - The state of being embodied; bodily existence. [Obs.] Dr. H. More.",
  "agazed - Gazing with astonishment; amazed. [Obs.] The whole army stood agazed on him. Shak.",
  "alburnous - Of or pertaining to alburnum; of the alburnum; as, alburnous substances.",
  "perflable - Capable of being blown through. [Obs.]",
  "polyperythrin - A coloring matter found in many simple Anthozoa and some hydroids.",
  "habilatory - Of or pertaining to clothing; wearing clothes. Ld. Lytton.",
  "incremable - Incapable of being burnt; incombustibe. Sir T. Browne.",
  "uncorruptible - Incorruptible. \"The glory of the uncorruptible God.\" Rom. i. 23.",
  "extra-official - Not prescribed by official duty.",
  "malty - Consisting, or like, malt. Dickens.",
  "ovate-subulate - Having an ovate form, but with a subulate tip or extremity.",
  "swan-hopping - A corruption of Swan-upping. [Eng.] Encyc. Brit.",
  "overcarry - To carry too far; to carry beyond the proper point. Hayward.",
  "thegn - Thane. See Thane. E. A. Freeman.",
  "sojourning - The act or state of one who sojourns.",
  "scrawny - Meager; thin; rawboned; bony; scranny.",
  "wardsman - A man who keeps ward; a guard. [R.] Sydney Smith.",
  "mesotartaric - Pertaining to, or designating, an acid called also inactive tartaric acid.",
  "disinvolve - To uncover; to unfold or unroll; to disentangle. [R.] Dr. H. More.",
  "electrometry - The art or process of making electrical measurements.",
  "decumbency - The act or posture of lying down. The ancient manner of decumbency. Sir T. Browne.",
  "acetarious - Used in salads; as, acetarious plants.",
  "polydipsia - Excessive and constant thirst occasioned by disease.",
  "exspoliation - Spoliation. [Obs. or R.] Bp. Hall.",
  "scantlet - A small pattern; a small quantity. [Obs.] Sir M. Hale.",
  "carvel - 1. Same as Caravel. 2. A species of jellyfish; sea blubber. Sir T. Herbert.",
  "drowsiness - State of being drowsy. Milton.",
  "lichenographic - Of or pertaining to lichenography.",
  "scoffery - The act of scoffing; scoffing conduct; mockery. Holinshed.",
  "dedentition - The shedding of teeth. [R.] Sir T. Browne.",
  "recusancy - The state of being recusant; nonconformity. Coke.",
  "biotic - Relating to life; as, the biotic principle.",
  "brackishness - The quality or state of being brackish, or somewhat salt.",
  "chorally - In the manner of a chorus; adapted to be sung by a choir; in harmony.",
  "bewrayer - One who, or that which, bewrays; a revealer. [Obs. or Archaic] Addison.",
  "geomancer - One who practices, or is versed in, geomancy.",
  "sectist - One devoted to a sect; a soetary. [R.]",
  "ulnar - Of or pertaining to the ulna, or the elbow; as, the ulnar nerve.",
  "disconsent - To differ; to disagree; to dissent. [Obs.] Milton.",
  "suberin - A material found in the cell walls of cork. It is a modification of lignin.",
  "dactyliomancy - Divination by means of finger rings.",
  "shapeliness - The quality or state of being shapely.",
  "interrelation - Mutual or reciprocal relation; correlation.",
  "vaginervose - Having the nerves, or veins, placed in apparent disorder.",
  "reverberator - One who, or that which, produces reverberation.",
  "increpate - To chide; to rebuke; to reprove. [Obs.]",
  "mean-spirited - Of a mean spirit; base; groveling. -- Mean\"-spir`it*ed*ness, n.",
  "melaena - A discharge from the bowels of black matter, consisting of altered blood.",
  "ferret-eye - The spur-winged goose; -- so called from the red circle around the eyes.",
  "cleaning - 1. The act of making clean. 2. The afterbirth of cows, ewes, etc. Gardner.",
  "jolif - Joyful; merry; pleasant; jolly. [Obs.] Chaucer.",
  "crantara - The fiery cross, used as a rallying signal in the Highlands of Scotland.",
  "nudibranch - Of or pertaining to the Nudibranchiata. -- n.  One of the Nudibranchiata.",
  "granolithic - A kind of hard artificial stone, used for pavements.",
  "self-destruction - The destruction of one's self; self-murder; suicide. Milton.",
  "walm - To roll; to spout; to boil up. [Obs.] Holland.",
  "berylline - Like a beryl; of a light or bluish green color.",
  "arthritis - Any inflammation of the joints, particularly the gout.",
  "weatherliness - The quality of being weatherly.",
  "antiseptically - By means of antiseptics.",
  "undertenant - The tenant of a tenant; one who holds lands or tenements of a tenant or lessee.",
  "pommette - Having two balls or protuberances at each end; -- said of a cross.",
  "miscorrect - To fail or err in attempting to correct. \"Scaliger miscorrects his author.\" Dryden.",
  "esoterics - Mysterious or hidden doctrines; secret science.",
  "cubicalness - The quality of being cubical.",
  "retinoid - Resinlike, or resinform; resembling a resin without being such.",
  "top-rope - A rope used for hoisting and lowering a topmast, and for other purposes.",
  "flavored - Having a distinct flavor; as, high-flavored wine.",
  "orgillous - Proud; haughty. [Obs.] Shak.",
  "califate - Same as Caliph, Caliphate, etc.",
  "taintworm - A destructive parasitic worm or insect larva.",
  "beauish - Like a beau; characteristic of a beau; foppish; fine. \"A beauish young spark.\" Byrom.",
  "appointor - The person who selects the appointee. See Appointee, 2.",
  "parallelogrammatic - Of or pertaining to a parallelogram; parallelogrammic.",
  "churchless - Without a church. T. Fuller.",
  "accoucheur - A man who assists women in childbirth; a man midwife; an obstetrician.",
  "supratemporal - Situated above the temporal bone or temporal fossa. -- n.  A supratemporal bone.",
  "straightener - One who, or that which, straightens.",
  "confectory - Pertaining to the art of making sweetmeats. [Obs.] Beaumont.",
  "jolterhead - A dunce; a blockhead. Sir T. North.",
  "vespiary - A nest, or habitation, of insects of the wasp kind.",
  "midnight sun - The sun shining at midnight in the arctic or antarctic summer.",
  "stupefactive - Same as Stupefacient. [Written also stupifactive.]",
  "sheep-shearer - One who shears, or cuts off the wool from, sheep.",
  "benthal - Relating to the deepest zone or region of the ocean.",
  "oiler - 1. One who deals in oils. 2. One who, or that which, oils.",
  "pilular - Of or pertaining to pills; resembling a pill or pills; as, a pilular mass.",
  "elohistic - Relating to Elohim as a name of God; -- said of passages in the Old Testament.",
  "herdman - The owner or keeper of a herd or of herds; one employed in tending a herd of cattle.",
  "mealiness - The quality or state of being mealy.",
  "recurvation - The act of recurving, or the state of being recurved; a bending or flexure backward.",
  "vortiginous - Moving rapidly round a center; vortical. [R.] Cowper.",
  "vitalistic - Pertaining to, or involving, vitalism, or the theory of a special vital principle.",
  "dyehouse - A building in which dyeing is carried on.",
  "electro-chemical - Of or pertaining to electro-chemistry. Ure.",
  "oppositive - Capable of being put in opposition. Bp. Hall.",
  "primogenitureship - The state or privileges of the firstborn. Burke.",
  "imitableness - The state or quality of being imitable; worthness of imitation.",
  "semispherical - Having the figure of a half sphere. Kirwan.",
  "chylous - Consisting of, or similar to, chyle.",
  "decipiency - State of being deceived; hallucination. [Obs.] Sir T. Browne.",
  "tideland - Land that is overflowed by tide water; hence, land near the sea.",
  "diverter - One who, or that which, diverts, turns off, or pleases.",
  "acutorsion - The twisting of an artery with a needle to arrest hemorrhage.",
  "rubicund - Inclining to redness; ruddy; red. \"His rubicund face.\" Longfellow.",
  "vaticide - The murder, or the murderer, of a prophet. \"The caitiff vaticide.\" Pope.",
  "pervial - Pervious. [Obs.] -- Per\"vi*al*ly, adv. [Obs.] Chapman.",
  "diffract - To break or separate into parts; to deflect, or decompose by deflection, a",
  "amortise - Same as Amortize, Amortization, etc.",
  "finiteless - Infinite. [Obs.] Sir T. browne.",
  "bebleed - To make bloody; to stain with blood. [Obs.] Chaucer.",
  "inexistant - Inexistent; not existing. [Obs.] Gudworth.",
  "aberrational - Characterized by aberration.",
  "orsedue - Leaf metal of bronze; Dutch metal. See under Dutch.",
  "assuring - That assures; tending to assure; giving confidence. -- As*sur\"ing*ly, adv.",
  "wheelbird - The European goatsucker. [Prov. Eng.]",
  "uncanny - Not canny; unsafe; strange; weird; ghostly. Sir W. Scott. -- Un*can\"ni*ness, n. G. Eliot.",
  "spekehouse - The parlor or reception room of a convent. [Obs.]",
  "apanthropy - An aversion to the company of men; a love of solitude.",
  "countrify - To give a rural appearance to; to cause to appear rustic. Lamb.",
  "fireflame - The European band fish (Cepola rubescens).",
  "nowd - The European gray gurnard (Trigla gurnardus). [Written also knoud.]",
  "ferous - Wild; savage. [R.] Arthur Wilson.",
  "grass-green - 1. Green with grass. 2. Of the color of grass; clear and vivid green.",
  "gravel-stone - A pebble, or small fragment of stone; a calculus.",
  "fibriform - Having the form of a fiber or fibers; resembling a fiber.",
  "simple-hearted - Sincere; inguenuous; guileless. Sir W. Scott.",
  "supercrescent - Growing on some other growing thing. [R.] Johnson.",
  "polyonym - 1. An object which has a variety of names. 2. A polynomial name or term.",
  "blackmailer - One who extorts, or endeavors to extort, money, by black mailing.",
  "extraught - Extracted; descended. [Obs.] Knowing whence thou art extraught Shak.",
  "epilogation - A summing up in a brief account. [Obs.] Udall.",
  "screable - Capable of being spit out. [Obs.] Bailey.",
  "distrait - Absent-minded; lost in thought; abstracted.",
  "fruiterer - One who deals in fruit; a seller of fruits.",
  "sternutation - The act of sneezing. Quincy.",
  "intentive - Attentive; intent. [Obs.] Spenser.",
  "maceration - The act or process of macerating.",
  "zizania - A genus of grasses including Indian rice. See Indian rice, under Rice.",
  "opposer - One who opposes; an opponent; an antagonist; an adversary.",
  "pudenda - The external organs of generation.",
  "boxkeeper - An attendant at a theater who has charge of the boxes.",
  "iguanodont - Like or pertaining to the genus Iguanodon.",
  "atokous - Producing only asexual individuals, as the eggs of certain annelids.",
  "elixate - To boil; to seethe; hence, to extract by boiling or seething. [Obs.] Cockeram.",
  "iodal - An oily liquid, Cl3.CHO, analogous to chloral and bromal.",
  "mytacism - Too frequent use of the letter m, or of the sound represented by it.",
  "thaumaturgical - Of or pertaining to thaumaturgy; magical; wonderful. Burton.",
  "ortive - Of or relating to the time or act of rising; eastern; as, the ortive amplitude of a planet.",
  "mobbish - Like a mob; tumultuous; lawless; as, a mobbish act. Bp. Kent.",
  "pharyngolaryngeal - Of or pertaining both to pharynx and the larynx.",
  "keratome - An instrument for dividing the cornea in operations for cataract.",
  "refocillate - To refresh; to revive. [Obs.] Aubrey.",
  "fenowed - Corrupted; decayed; moldy. See Vinnewed. [Obs.] Dr. Favour.",
  "snithe - Sharp; piercing; cutting; -- applied to the wind. [Prov. Eng.]",
  "coruscant - Glittering in flashes; flashing. Howell.",
  "smeltery - A house or place for smelting.",
  "hydropathist - One who practices hydropathy; a water-cure doctor.",
  "tripersonality - The state of existing as three persons in one Godhead; trinity.",
  "ectropion - An unnatural eversion of the eyelids.",
  "intertrochanteric - Between the trochanters of the femur.",
  "inconformity - Want of conformity; nonconformity. [Obs.]",
  "quadrisulcate - Having four hoofs; as, a quadrisulcate foot; a quadrisulcate animal.",
  "culex - A genus of dipterous insects, including the gnat and mosquito.",
  "wrappage - 1. The act of wrapping. 2. That which wraps; envelope; covering.",
  "kantianism - The doctrine or theory of Kant; the Kantian philosophy.",
  "orderless - Being without order or regularity; disorderly; out of rule.",
  "frapping - A lashing binding a thing tightly or binding things together.",
  "irrevocability - The state or quality of being irrevocable; irrevocableness.",
  "surmounter - One who, or that which, surmounts.",
  "costliness - The quality of being costy; expensiveness; sumptuousness.",
  "lumpy - Full of lumps, or small compact masses.",
  "furfuraceous - Made of bran; like bran; scurfy.",
  "antinomianism - The tenets or practice of Antinomians. South.",
  "lightful - Full of light; bright. [R.] \"Lightful presence.\" Marston.",
  "multipliable - Capable of being multiplied. -- Mul\"ti*pli`a*ble*ness, n.",
  "stalely - 1. In a state stale manner. 2. Of old; long since. [Obs.] B. Jonson.",
  "misbelieve - To believe erroneously, or in a false religion. \"That misbelieving Moor.\" Shak.",
  "absonant - Discordant; contrary; -- opposed to consonant. \"Absonant to nature.\" Quarles.",
  "hypercriticise - To criticise with unjust severity; to criticise captiously.",
  "skedaddle - To betake one's self to flight, as if in a panic; to flee; to run away. [Slang, U. S.]",
  "serape - A blanket or shawl worn as an outer garment by the Spanish Americans, as in Mexico.",
  "stratagemical - Containing stratagem; as, a stratagemical epistle. [R.] Swift.",
  "quich - To stir. [Obs.] He could not move nor quich at all. Spenser.",
  "superscript - Superscription. [Obs.] \"I will overglance the superscript.\" Shak.",
  "defier - One who dares and defies; a contemner; as, a defier of the laws.",
  "whetile - The green woodpecker, or yaffle. See Yaffle. [Prov. Eng.]",
  "interneural - Between the neural arches or neural spines. -- n.  An interneural spine or cartilage.",
  "disangelical - Not angelical. [R.] \"Disangelical nature.\" Coventry.",
  "despotat - The station or government of a despot; also, the domain of a despot. Freeman.",
  "muciform - Resembling mucus; having the character or appearance of mucus.",
  "cuticular - Pertaining to the cuticle, or external coat of the skin; epidermal.",
  "astrognosy - The science or knowledge of the stars, esp. the fixed stars. Bouvier.",
  "enfoldment - The act of infolding. See Infoldment.",
  "fashionist - An obsequious follower of the modes and fashions. [R.] Fuller.",
  "housage - A fee for keeping goods in a house. [R.] Chambers.",
  "unition - The act of uniting, or the state of being united; junction. [Obs.] Wiseman.",
  "ungive - To yield; to relax; to give way. [Obs.]",
  "snugly - In a snug manner; closely; safely.",
  "anthracoid - Resembling anthrax in action; of the nature of anthrax; as, an anthracoid microbe.",
  "cicatricial - Relating to, or having the character of, a cicatrix. Dunglison.",
  "corrivalship - Corivalry. [R.] By the corrivalship of Shager his false friend. Sir T. Herbert.",
  "replum - The framework of some pods, as the cress, which remains after the valves drop off. Gray.",
  "bandoline - A glutinous pomatum for the fair.",
  "puff-legged - Having a conspicuous tuft of feathers on the legs.",
  "disparates - Things so unequal or unlike that they can not be compared with each other.",
  "myelitis - Inflammation of the spinal marrow or its membranes.",
  "irreproachably - In an irreproachable manner; blamelessly.",
  "obdiplostemony - The condition of being obdiplostemonous.",
  "ruching - A ruche, or ruches collectively.",
  "angiomonospermous - Producing one seed only in a seed pod.",
  "confragose - Broken; uneven. [Obs.] \"Confragose cataracts.\"  Evelyn.",
  "pottain - Old pot metal. [Obs.] Holland.",
  "benzal - A transparent crystalline substance,",
  "procinct - A state of complete readiness for action. [Obs.] \"War in procinct.\" Milton.",
  "diestock - A stock to hold the dies used for cutting screws.",
  "barytum - The metal barium. See Barium. [R.]",
  "foregut - The anterior part of the alimentary canal, from the mouth to the intestine, o",
  "vaward - The fore part; van. [Obs.] Since we have the vaward of the day. Shak.",
  "wet-shod - Having the feet, or the shoes on the feet, wet.",
  "anonymousness - The state or quality of being anonymous. Coleridge.",
  "wistit - A small South American monkey; a marmoset. [Written also wistiti, and ouistiti.]",
  "inhumanly - In an inhuman manner; cruelly; barbarously.",
  "extraordinariness - The quality of being extraordinary. [R.] Gov. of the Tongue.",
  "approximately - With approximation; so as to approximate; nearly.",
  "handcart - A cart drawn or pushed by hand.",
  "california jack - A game at cards, a modification of seven-up, or all fours.",
  "asperser - One who asperses; especially, one who vilifies another.",
  "chafferer - One who chaffers; a bargainer.",
  "feudality - The state or quality of being feudal; feudal form or constitution. Burke.",
  "metempiricism - The science that is concerned with metempirics.",
  "drawlatch - A housebreaker or thief. [Obs.] Old Play (1631).",
  "prasinous - Grass-green; clear, lively green, without any mixture. Lindley.",
  "doloriferous - Producing pain. Whitaker.",
  "cuminil - A substance, analogous to benzil, obtained from oil of caraway.",
  "carrow - A strolling gamester. [Ireland] Spenser.",
  "lool - A vessel used to receive the washings of ores of metals.",
  "philological - Of or pertaining to philology. -- Phil`o*log\"ic*al*ly, adv.",
  "springiness - The state or quality of being springly. Boyle.",
  "northness - A tendency in the end of a magnetic needle to point to the north. Faraday.",
  "homostyled - Having only one form of pistils; -- said of the flowers of some plants. Darwin.",
  "oncograph - An instrument for registering the changes observable with an oncometer.",
  "peptogen - A substance convertible into peptone.",
  "munting - Same as Mullion; -- especially used in joiner's work.",
  "asininity - The quality of being asinine; stupidity combined with obstinacy.",
  "weld steel - A compound of iron, such as puddled steel, made without complete fusion.",
  "east-insular - Relating to the Eastern Islands; East Indian. [R.] Ogilvie.",
  "hellene - A native of either ancient or modern Greece; a Greek. Brewer.",
  "tetravalence - The quality or state of being tetravalent; quadrivalence.",
  "demobilize - To disorganize, or disband and send home, as troops which have been mobilized.",
  "faunist - One who describes the fauna of country; a naturalist. Gilbert White.",
  "somniferous - Causing or inducing sleep; soporific; dormitive; as, a somniferous potion. Walton.",
  "aristotelianism - The philosophy of Aristotle, otherwise called the Peripatetic philosophy.",
  "chromophotography - The art of producing photographs in colors.",
  "yarnen - Made of yarn; consisting of yarn. [Obs.] \"A pair of yarnen stocks.\" Turbervile.",
  "jolliness - Jollity; noisy mirth. Chaucer.",
  "burletta - A comic operetta; a music farce. Byron.",
  "vacillant - Vacillating; wavering; fluctuating; irresolute.",
  "self-will - One's own will, esp. when opposed to that of others; obstinacy.",
  "bolo - A kind of large knife resembling a machete. [Phil. Islands]",
  "yate - A gate. See 1st Gate. [Obs. or Prov. Eng.] Spenser.",
  "lusus naturae - Sport or freak of nature; a deformed or unnatural production.",
  "counternatural - Contrary to nature. [R.] Harvey.",
  "chambering - Lewdness. [Obs.] Rom. xiii. 13.",
  "envault - To inclose in a vault; to entomb. [R.] Swift.",
  "helispheric - Spiral. Helispherical line (Math.). the rhomb line in navigation. [R.]",
  "protervity - Peevishness; petulance. [Obs.] Fuller.",
  "aroph - A barbarous word used by the old chemists to designate various medical remedies. [Obs.]",
  "archangelic - Of or pertaining to archangels; of the nature of, or resembling, an archangel. Milton.",
  "ichnology - The branch of science which treats of fossil footprints.",
  "undersailed - Inadequately equipped with sails. [Obs.]",
  "cardo - (a) The basal joint of the maxilla in insects. (b) The hinge of a bivalve shell.",
  "overcanopy - To cover as with a canopy. Shak.",
  "spitous - Having spite; spiteful. [Obs.]",
  "disopinion - Want or difference of belief; disbelief. [Obs.] Bp. Reynolds.",
  "propylaeum - Any court or vestibule before a building or leading into any inclosure.",
  "semidiatessaron - An imperfect or diminished fourth. [R.]",
  "pulpitry - The teaching of the pulpit; preaching. [R. & Obs.] \" Mere pulpitry.\" Milton.",
  "doctrinarian - A doctrinaire. J. H. Newman.",
  "trickment - Decoration. [Obs.] \" No trickments but my tears.\" Beau. & Fl.",
  "unwarm - To lose warmth; to grow cold. [R.]",
  "savoriness - The quality of being savory.",
  "spectrogram - A photograph, map, or diagram of a spectrum.",
  "nationalization - The act of nationalizing, or the state of being nationalized.",
  "passeriform - Like or belonging to the Passeres.",
  "pedimane - A pedimanous marsupial; an opossum.",
  "solipsism - 1. (Ethics)  Egotism. Krauth-Fleming. 2. (Metaph.)  Egoism. Krauth-Fleming.",
  "humicubation - The act or practice of lying on the ground. [Obs.] Abp. Bramhall.",
  "cerebrology - The science which treats of the cerebrum or brain.",
  "introsume - To draw in; to swallow. [Obs.] Evelyn.",
  "potentness - The quality or state of being potent; powerfulness; potency; efficacy.",
  "cast steel - See Cast steel, under Steel.",
  "mangonel - A military engine formerly used for throwing stones and javelins.",
  "caburn - A small line made of spun yarn, to bind or worm cables, seize tackles, etc.",
  "kickshaw - See Kickshaws, the correct singular.",
  "archiblastula - A hollow blastula, supposed to be the primitive form; a c",
  "manifestable - Such as can be manifested.",
  "euphuistic - Belonging to the euphuists, or euphuism; affectedly refined.",
  "guttiform - Drop-shaped, as a spot of color.",
  "agonistics - The science of athletic combats, or contests in public games.",
  "temperateness - The quality or state of being temperate; moderateness; temperance.",
  "nimious - Excessive; extravagant; inordinate. [Obs.]",
  "telpherage - The conveyance of vehicles or loads by means of electricity. Fleeming Jenkin.",
  "fordwine - To dwindle away; to disappear. [Obs.] Rom of R.",
  "bowshot - The distance traversed by an arrow shot from a bow.",
  "hybodus - An extinct genus of sharks having conical, compressed teeth.",
  "superconsequence - Remote consequence. [Obs.] Sir T. Browne.",
  "awlwort - A plant (Subularia aquatica), with awl-shaped leaves.",
  "angelet - A small gold coin formerly current in England; a half angel. Eng. Cyc.",
  "feuillemort - Having the color of a faded leaf. Locke.",
  "chirping - Cheering; enlivening. He takes his chirping pint, he cracks his jokes. Pope.",
  "quatuor - A quartet; -- applied chiefly to instrumental compositions.",
  "fleecy - Covered with, made of, or resembling, a fleece. \"Fleecy flocks.\" Prior.",
  "elucidator - One who explains or elucidates; an expositor.",
  "malinger - To act the part of a malingerer; to feign illness or inability.",
  "amnicolist - One who lives near a river. [Obs.] Bailey.",
  "anacamptically - By reflection; as, echoes are sound produced anacamptically. Hutton.",
  "endeavorer - One who makes an effort or attempt. [Written also endeavourer.]",
  "playday - A day given to play or diversion; a holiday. Swift.",
  "adversifolious - Having opposite leaves, as plants which have the leaves so arranged on the stem.",
  "nonusance - Neglect of using; failure to use. [R.] Sir T. Browne.",
  "bigness - The state or quality of being big; largeness; size; bulk.",
  "solvency - The quality or state of being solvent.",
  "cheap-john - A seller of low-priced or second goods; a hawker.",
  "sorrage - The blades of green or barley. [Obs.] Bailey.",
  "catastrophic - Of a pertaining to a catastrophe. B. Powell.",
  "bordraging - An incursion upon the borders of a country; a raid. [Obs.] Spenser.",
  "trifallow - To plow the third time before sowing, as land. Mortimer.",
  "tzaritza - The empress of Russia. See Czarina.",
  "penwiper - A cloth, or other material, for wiping off or cleaning ink from a pen.",
  "teratological - Of or pertaining to teratology; as, teratological changes.",
  "thysanuran - One of the Thysanura. Also used adjectively.",
  "papyraceous - Made of papyrus; of the consistency of paper; papery.",
  "proplastics - The art of making molds for castings. [R.]",
  "telephonically - By telephonic means or processes; by the use of the telephone.",
  "protractile - Capable of being protracted, or protruded; protrusile.",
  "intort - To twist in and out; to twine; to wreathe; to wind; to wring. Pope.",
  "glutinosity - The quality of being glutinous; viscousness. [R.]",
  "haemoglobinometer - Same as Hemochromometer.",
  "pantamorph - That which assumes, or exists in, all forms.",
  "ponghee - A Buddhist priest of the higher orders in Burmah. Malcom.",
  "unsister - To separate, as sisters; to disjoin. [Poetic & R.] Tennyson.",
  "transmittible - Capable of being transmitted; transmissible.",
  "aphony - Loss of voice or vocal utterance.",
  "acotyledon - A plant which has no cotyledons, as the dodder and all flowerless plants.",
  "tritozooid - A zooid of the third generation in asexual reproduction.",
  "unitively - In a unitive manner. Cudworth.",
  "cephalopodic - Belonging to, or resembling, the cephalopods.",
  "prover - One who, or that which, proves.",
  "opacous - Opaque. [R.] Milton. -- O*pa\"cous*ness, n. [R.]",
  "haematachometry - The measurement of the velocity of the blood.",
  "nixie clerk - A post-office clerk in charge of the nixies.",
  "oreades - A group of butterflies which includes the satyrs. See Satyr, 2.",
  "fusome - Handy; reat; handsome; notable. [Prov. Eng.] Halliwell.",
  "rhodopsin - The visual purple. See under Visual.",
  "semivitrified - Half or imperfectly vitrified; partially converted into glass.",
  "bedight - To bedeck; to array or equip; to adorn. [Archaic] Milton.",
  "rafting - The business of making or managing rafts.",
  "chainless - Having no chain; not restrained or fettered. \"The chainless mind.\" Byron.",
  "bigaroon - The large white-heart cherry.",
  "boatmanship - The art of managing a boat.",
  "cryer - The female of the hawk; a falcon-gentil.",
  "privatively - In a privative manner; by the absence of something; negatively. [R.] Hammond.",
  "pricket - A buck in his second year. See Note under 3d Buck. Shak.",
  "septimole - A group of seven notes to be played in the time of four or six.",
  "discarnate - Stripped of flesh. [Obs.] \"Discarnate bones.\" Glanvill.",
  "phoenician - Of or pertaining to Phoenica. -- n.  A native or inhabitant of Phoenica.",
  "pandar - Same as Pander. \"Seized by the pandar of Appius.\" Macaulay.",
  "unbosomer - One who unbosoms, or discloses. [R.] \"An unbosomer of secrets.\" Thackeray.",
  "brancard - A litter on which a person may be carried. [Obs.] Coigrave.",
  "courtlike - After the manner of a court; elegant; polite; courtly.",
  "deignous - Haughty; disdainful. [Obs.] Chaucer.",
  "totalization - Act of totalizing, or state of being totalized.",
  "hermaphrodeity - Hermaphrodism. B. Jonson.",
  "trifoly - Sweet trefoil. [Obs.] She was crowned with a chaplet of trifoly. B. Jonson.",
  "tractitious - Treating of; handling. [R.]",
  "torsion indicator - An autographic torsion meter.",
  "adipsous - Quenching thirst, as certain fruits.",
  "dysnomy - Bad legislation; the enactment of bad laws. Cockeram.",
  "conceptible - Capable of being conceived; conceivable. Sir M. Hale.",
  "excoction - The act of excocting or boiling out. [Obs.] Bacon.",
  "terrigenous - Earthborn; produced by the earth.",
  "monadical - Of, pertaining to, or like, a monad, in any of its senses. See Monad, n. Dr. H. More.",
  "smudginess - The quality or state of being smudged, soiled, or blurred. C. A. Young.",
  "gymnocarpous - Naked-fruited, the fruit either smooth or not adherent to the perianth. Gray.",
  "psalmographer - A writer of psalms, or sacred songs and hymns.",
  "cloven-footed - Having the foot or hoof divided into two parts, as the ox.",
  "assessorial - Of or pertaining to an assessor, or to a court of assessors. Coxe.",
  "pooler - A stick for stirring a tan vat.",
  "dragantine - A mucilage obtained from, or containing, gun tragacanth.",
  "instillation - The of instilling; also, that which is instilled. Johnson.",
  "knitster - A woman who knits. [Prov. Eng.] Halliwell.",
  "hypertrophic - Of or pertaining to hypertrophy; affected with, or tending to, hypertrophy.",
  "flotant - Represented as flying or streaming in the air; as, a banner flotant.",
  "split-tongued - Having a forked tongue, as that of snakes and some lizards.",
  "sulphocarbonate - A salt of sulphocarbonic acid; a thiocarbonate.",
  "gemmipara - Animals which increase by budding, as hydroids.",
  "hendecatoic - Undecylic; pertaining to, or derived from, hendecane; as, hendecatoic acid.",
  "flocky - Abounding with flocks; floccose.",
  "flowerpot - A vessel, commonly or earthenware, for earth in which plants are grown.",
  "omphalopsychite - A name of the Hesychasts, from their habit of gazing upon the navel.",
  "influxive - Having a tendency to flow in; having influence; influential. [R.] Holdsworth.",
  "driftbolt - A bolt for driving out other bolts.",
  "neurological - Of or pertaining to neurolgy.",
  "typewriting - The act or art of using a typewriter; also, a print made with a typewriter.",
  "ozonic - Pertaining to, resembling, or containing, ozone.",
  "esotery - Mystery; esoterics; -- opposed to exotery. A. Tucker.",
  "pikelet - A light, thin cake or muffin. [Prov. Eng.] Wright.",
  "gynander - A plant having the stamens inserted in the pistil.",
  "blastment - A sudden stroke or injury produced by some destructive cause. [Obs.] Shak.",
  "ascidiozooid - One of the individual members of a compound ascidian. See Ascidioidea.",
  "homogene - Homogeneous. [Obs.] B. Jonson.",
  "boneblack - See Bone black, under Bone, n.",
  "occurse - Same as Occursion. [Obs.] Bentley.",
  "untread - To tread back; to retrace. Shak.",
  "locomotivity - The power of changing place.",
  "devourer - One who, or that which, devours.",
  "amylate - A compound of the radical amyl with oxygen and a positive atom or radical.",
  "paralyzation - The act or process of paralyzing, or the state of being paralyzed.",
  "osteologic - Of or pertaining to osteology. -- Os`te*o*log\"ic*al*ly, adv.",
  "updive - To spring upward; to rise. [R.] Davies (Microcosmos).",
  "inconvertibly - In an inconvertible manner.",
  "antichronism - Deviation from the true order of time; anachronism. [R.] Selden.",
  "logger - One engaged in logging. See Log, v. i. [U.S.] Lowell.",
  "monopolistic - Of or pertaining to a monopolist. North Am. Rev.",
  "edenite - A variety of amphibole. See Amphibole.",
  "extimulate - To stimulate. [Obs.] Sir T. Browne.",
  "yawd - A jade; an old horse or mare. [Written also yaud.] [Prov. Eng. & Scot.] Grose.",
  "cherty - Like chert; containing chert; flinty.",
  "effervescent - Gently boiling or bubbling, by means of the disengagement of gas",
  "dilucidate - To elucidate. [Obs.] Boyle.",
  "autotoxaemia - Self-intoxication. See Auto-intoxication.",
  "obliteration - The act of obliterating, or the state of being obliterated; extinction. Sir. M. Hale.",
  "vermifugal - Tending to prevent, destroy, or expel, worms or vermin; anthelmintic.",
  "parasital - Of or pertaining to parasites; parasitic.",
  "trusteeship - The office or duty of a trustee.",
  "angleworm - A earthworm of the genus Lumbricus, frequently used by anglers for bait. See Earthworm.",
  "offish - Shy or distant in manner. [Colloq. U.S.]",
  "tewed - Fatigued; worn with labor or hardship. [Obs. or Local] Mir. for Mag.",
  "clodpoll - A stupid fellow; a dolt. [Written also clodpole.] Shak.",
  "subah - A province; a government, as of a viceroy; also, a subahdar. [India]",
  "gluttonize - To eat to excess; to eat voraciously; to gormandize. Hallywell.",
  "discounsel - To dissuade. [Obs.] Spenser.",
  "collatable - Capable of being collated. Coleridge.",
  "ecru - Having the color or appearance of unbleached stuff, as silk, linen, or the like.",
  "chemosmosis - Chemical action taking place through an intervening membrane.",
  "subtriple - Containing a third, or one part to three. Bp. Wilkins.",
  "thranite - One of the rowers on the topmost of the three benches in a trireme.",
  "garde civique - See Army organization, above.",
  "boulter - A long, stout fishing line to which many hooks are attached.",
  "mikado - The popular designation of the hereditary sovereign of Japan.",
  "hectorism - The disposition or the practice of a hector; a bullying. [R.]",
  "supravulgar - Being above the vulgar or common people. [R.] Collier.",
  "suburbial - Suburban. [Obs.] \"Suburbial fields.\" Warton. \"Suburbian muse.\" Dryden.",
  "lamented - Mourned for; bewailed. This humble praise,lamented shade ! receive. Pope.",
  "fantastical - Fanciful; unreal; whimsical; capricious; fantastic.",
  "adjunctly - By way of addition or adjunct; in connection with.",
  "galore - Plenty; abundance; in abundance.",
  "hoodman - The person blindfolded in the game called hoodman-blind. [Obs.] Shak.",
  "headship - Authority or dignity; chief place.",
  "osteological - Of or pertaining to osteology. -- Os`te*o*log\"ic*al*ly, adv.",
  "periosteal - Situated around bone; of or pertaining to the periosteum.",
  "arboricultural - Pertaining to arboriculture. Loudon.",
  "rotiform - 1. Wheel-shaped; as, rotiform appendages. 2. (Bot.)  Same as Rotate.",
  "arthrozoic - Of or pertaining to the Articulata; articulate.",
  "unturn - To turn in a reserve way, especially so as to open something; as, to unturn a key. Keats.",
  "mesomyodian - A bird having a mesomyodous larynx.",
  "unforeskinned - Deprived of the foreskin; circumcised. [R.] Milton.",
  "diffide - To be distrustful. [Obs.] Dr. H. More.",
  "inerringly - Without error, mistake, or deviation; unerringly. Glanvill.",
  "multilocular - Having many or several cells or compartments; as, a multilocular shell or capsule.",
  "three-flowered - Bearing three flowers together, or only three flowers.",
  "cryptographal - Pertaining to cryptography; cryptographical. Boyle.",
  "advoutress - An adulteress. [Obs.] Bacon.",
  "crankbird - A small European woodpecker (Picus minor).",
  "syringotomy - The operation of cutting for anal fistula.",
  "thrapple - Windpipe; throttle. [Prov. Eng. & Scot.]",
  "euphuize - To affect excessive refinement in language; to be overnice in expression.",
  "knobbing - Rough dressing by knocking off knobs or projections.",
  "covetable - That may be coveted; desirable.",
  "olusatrum - An umbelliferous plant, the common Alexanders of Western Europe (Smyrnium Olusatrum).",
  "reheat - 1. To heat again. 2. To revive; to cheer; to cherish. [Obs.] Rom. of R.",
  "interwoven - imp. & p. p. of Interweave.",
  "longimetry - The art or practice of measuring distances or lengths. Cheyne.",
  "irremittable - Not capable of being remitted; irremissible. Holinshed.",
  "oblatration - The act of oblatrating; a barking or snarling. Bp. Hall.",
  "inlagation - The restitution of an outlawed person to the protection of the law; inlawing. Bouvier.",
  "masterliness - The quality or state of being masterly; ability to control wisely or skillfully.",
  "gentlesse - Gentilesse; gentleness. [Obs.]",
  "pupillarity - The period before puberty, or from birth to fourteen in males, and twelve in females.",
  "macrame lace - A coarse lace made of twine, used especially in decorating furniture.",
  "bedye - To dye or stain. Briton fields with Sarazin blood bedyed. Spenser.",
  "bedizenment - That which bedizens; the act of dressing, or the state of being dressed, tawdrily.",
  "adulatress - A woman who flatters with servility.",
  "benjamite - A descendant of Benjamin; one of the tribe of Benjamin. Judg. iii. 15.",
  "ebullience - A boiling up or over; effervescence. Cudworth.",
  "cymbling - A scalloped or \"pattypan\" variety of summer squash.",
  "hoarstone - A stone designating the Halliwell.",
  "belzebuth - A spider monkey (Ateles belzebuth) of Brazil.",
  "liegeman - Same as Liege, n., 2. Chaucer. Spenser.",
  "meliboean - Alternately responsive, as verses.",
  "gossamery - Like gossamer; flimsy. The greatest master of gossamery affectation. De Quincey.",
  "equiform - Having the same form; uniform. -- E`qui*for\"mi*ty, n. Sir T. Browne.",
  "oppilate - To crowd together; to fill with obstructions; to block up. [Obs.] Cockeram.",
  "re-ally - To bring together again; to compose or form anew. Spenser.",
  "manic - Of or pert. to, or characterized by, mania, or excitement.",
  "somnolency - Sleepiness; drowsiness; inclination to sleep.",
  "tummals - A great quantity or heap. Weale.",
  "haematophilina - A division of Cheiroptera, including the bloodsucking bats. See Vampire.",
  "uglily - In an ugly manner; with deformity.",
  "velleity - The lowest degree of desire; imperfect or incomplete volition. Locke.",
  "restinguish - To quench or extinguish. [Obs.] R. Field.",
  "theistical - Of or pertaining to theism, or a theist; according to the doctrine of theists.",
  "jaunce - To ride hard; to jounce. [Obs.] Spurr'd, galled and tired by jauncing Bolingbroke. Shak.",
  "lepidodendroid - Allied to, or resembling, Lepidodendron. -- n.  A lepidodendrid.",
  "rome scot - See Peter pence, under Peter.",
  "peculiarly - In a peculiar manner; particulary; in a rare and striking degree; unusually.",
  "fumarole - A hole or spot in a volcanic or other region, from which fumes issue.",
  "anaphrodisia - Absence of sexual appetite.",
  "putty-faced - White-faced; -- used contemptuously. Clarke.",
  "isolator - One who, or that which, isolates.",
  "hemicrania - A pain that affects only one side of the head.",
  "autoclave - A kind of French stewpan with a steamtight lid. Knight.",
  "puddly - Consisting of, or resembling, puddles; muddy; foul. \"Thick puddly water.\" Carew.",
  "overcarking - Too anxious; too full of care. [Archaic] Fuller.",
  "reezed - Grown rank; rancid; rusty. [Obs.] \"Reezed bacon.\" Marston.",
  "fancied - Formed or conceived by the fancy; unreal; as, a fancied wrong.",
  "crabbish - Somewhat sour or cross. The wips of the most crabbish Satyristes. Decker.",
  "post-tragus - A ridge within and behind the tragus in the ear of some animals.",
  "desolateness - The state of being desolate.",
  "supravaginal - Situated above or outside a sheath or vaginal membrane.",
  "ballarag - To bully; to threaten. [Low] T. Warton.",
  "reconditory - A repository; a storehouse. [Obs.] Ash.",
  "immensurable - Immeasurable. What an immensurable space is the firmament. Derham.",
  "concernedly - In a concerned manner; solicitously; sympathetically.",
  "edibility - Suitableness for being eaten; edibleness.",
  "describable - That can be described; capable of description.",
  "inspirator - A kind of injector for forcing water by steam. See Injector, n., 2.",
  "vanner - A machine for concentrating ore. See Frue vanner.",
  "cyanin - The blue coloring matter of flowers; -- called also anthokyan and anthocyanin.",
  "recuperative - Of or pertaining to recuperation; tending to recovery.",
  "embrew - To imbrue; to stain with blood. [Obs.] Spenser.",
  "inhabitiveness - See Inhabitativeness. What the phrenologists call inhabitiveness. Lowell.",
  "jawed - Having jaws; -- chiefly in composition; as, lantern-jawed. \"Jawed like a jetty.\" Skelton.",
  "headline - 1. (Print.)  The line at the head or top of a page. 2. (Naut.)  See Headrope.",
  "acetol - Methyl ketol; also, any of various homologues of the same.",
  "swarve - 1. To swerve. [Obs. or Scot.] Spenser. Jamieson. 2. To climb. [Prov. Eng.] Halliwell.",
  "dragbolt - A coupling pin. See under Coupling. [U. S.]",
  "impolarily - Not according to or in, the direction of the poles. [Obs.] Sir T. Browne.",
  "roux - A thickening, made of flour, for soups and gravies.",
  "pharology - The art or science which treats of lighthouses and signal lights.",
  "thrushel - The song thrush. [Prov. Eng.]",
  "qualifiable - Capable of being qualified; abatable; modifiable. Barrow.",
  "manorial - Of or pertaining to a manor. \" Manorial claims.\" Paley.",
  "orfgild - Restitution for cattle; a penalty for taking away cattle. Cowell.",
  "sigillated - Decorated by means of stamps; -- said of pottery.",
  "ronco - See Croaker, n., 2. (a). [Texas]",
  "hunkerism - Excessive conservatism; hostility to progress. [Political Cant, U.S.]",
  "panivorous - Eating bread; subsisting on bread.",
  "zooetomy - The dissection or the anatomy of animals; -- distinguished from androtomy.",
  "restinction - Act of quenching or extingishing. [Obs.]",
  "swooning - from Swoon, v. -- Swoon\"ing*ly, adv.",
  "weedless - Free from weeds or noxious matter.",
  "piste - The track or tread a horseman makes upon the ground he goes over. Johnson.",
  "night-eyed - Capable of seeing at night; sharp-eyed. \"Your night-eyed Tiberius.\" B. Jonson.",
  "disglory - Dishonor. [Obs.] To the disglory of God's name. Northbrooke.",
  "transmigrator - One who transmigrates. J. Ellis.",
  "fumify - To subject to the action of smoke. [Obs.] Sir T. Browne.",
  "meteorograph - An instrument which registers meteorologic phases or conditions.",
  "antenumber - A number that precedes another. [R.] Bacon.",
  "glaring - Clear; notorious; open and bold; barefaced; as, a glaring crime. -- Glar\"ing*ly, adv.",
  "noseband - That part of the headstall of a bridle which passes over a horse's nose.",
  "immartial - Not martial; unwarlike. [Obs.]",
  "jointress - A woman who has a jointure. [Written also jointuress.] Blackstone.",
  "quaintness - The quality of being quaint. Pope.",
  "enteritis - An inflammation of the intestines. Hoblyn.",
  "groanful - Agonizing; sad. [Obs.] Spenser.",
  "helleborism - The practice or theory of using hellebore as a medicine.",
  "alkalinity - The quality which constitutes an alkali; alkaline property. Thomson.",
  "phloramine - A basic amido derivative of phloroglucin, having an astringent taste.",
  "duomo - A cathedral. See Dome, 2. Of tower or duomo, sunny sweet. Tennyson.",
  "predominantly - In a predominant manner.",
  "opalize - To convert into opal, or a substance like opal. Lyell.",
  "canniness - Caution; crafty management. [N. of Eng. & Scot.]",
  "driller - One who, or that which, drills.",
  "sadduceeism - The tenets of the Sadducees.",
  "duo - A composition for two performers; a duet.",
  "hairbreadth - Having the breadth of a hair; very narrow; as, a hairbreadth escape.",
  "philhellene - A friend of Greece, or of the Greeks; a philhellenist. Emerson.",
  "angiospermatous - Same as Angiospermous.",
  "candite - A variety of spinel, of a dark color, found at Candy, in Ceylon.",
  "charnico - A sort of sweet wine. [Obs.] Shak.",
  "impriming - A begining. [Obs.] \"Their springings and imprimings.\" Sir H. Wotton.",
  "idolum - Appearance or image; a phantasm; a spectral image; also, a mental image or idea.",
  "befortune - To befall. [Poetic] I wish all good befortune you. Shak.",
  "humorsomeness - Quality of being humorsome.",
  "fuff - To puff. [Prov. Eng. A Local, U. S.] Halliwel.",
  "seership - The office or quality of a seer.",
  "superplant - A plant growing on another, as the mistletoe; an epiphyte. [Obs.] Bacon.",
  "vessicnon - A soft swelling on a horse's leg; a windgall.",
  "circumundulate - To flow round, as waves. [R.]",
  "huffcap - A blusterer; a bully. [Obs.] -- a.  Blustering; swaggering. [Obs.] Bp. Hall.",
  "water gavel - A gavel or rent paid for a privilege, as of fishing, in some river or water.",
  "isouric - Pertaining to, or designating, a complex nitrogenous acid, isomeric with uric acid.",
  "uncurtain - To remove a curtain from; to reveal. Moore.",
  "ineradicable - Incapable of being The bad seed thus sown was ineradicable. Ld. Lytton.",
  "awarder - One who awards, or assigns by sentence or judicial determination; a judge.",
  "bolling - A tree from which the branches have been cut; a pollard.",
  "tacky - Sticky; adhesive; raw; -- said of paint, varnish, etc., when not well dried. [U. S.]",
  "losengerie - Flattery; deceit; trickery. [Obs.] Chaucer.",
  "resinously - By means, or in the manner, of resin.",
  "occidentals - Western Christians of the Latin rite. See Orientals. Shipley.",
  "suspected - Distrusted; doubted. -- Sus*pect\"ed*ly, adv. -- Sus*pect\"ed*ness, n.",
  "pyrheliometer - An instrument for measuring the direct heating effect of the sun's rays.",
  "amazedly - In amazement; with confusion or astonishment. Shak.",
  "inferiorly - In an inferior manner, or on the inferior part.",
  "hyperdicrotism - A hyperdicrotic condition.",
  "leucoryx - A large antelope of North Africa (Oryx leucoryx), allied to the gemsbok.",
  "meleagrine - Of or pertaining to the genus Meleagris.",
  "attritus - Matter pulverized by attrition.",
  "pythagorize - To speculate after the manner of Pythagoras.",
  "succinurate - A salt of succinuric acid.",
  "unfleshly - Not pertaining to the flesh; spiritual.",
  "relbun - The roots of the Chilian plant Calceolaria arachnoidea, -- used for dyeing crimson.",
  "squadroned - Formed into squadrons, or squares. [R.] Milton.",
  "transitorily - In a transitory manner; with brief continuance.",
  "bequeathable - Capable of being bequeathed.",
  "phagedena - (a) A canine appetite; bulimia. [Obs.] (b) Spreading, obstinate ulceration.",
  "phrenosin - A nitrogenous body, related to cerebrin, supposed to exist in the brain.",
  "toltec - One of a race which formerly occupied Mexico. -- Tol\"te*can, a.",
  "incoherently - In an incoherent manner; without due connection of parts.",
  "apocryphalist - One who believes in, or defends, the Apocrypha. [R.]",
  "epiblast - The outer layer of the blastoderm; the ectoderm. See Blastoderm, Delamination.",
  "plexiform - Like network; complicated. Quincy.",
  "untappice - to come out of concealment. [Obs.] Massinger.",
  "overmorrow - The day after or following to-morrow. [Obs.] Bible (1551).",
  "ecclesiast - 1. An ecclesiastic. Chaucer. 2. The Apocryphal book of Ecclesiasticus. [Obs.]",
  "unbar - To remove a bar or bars from; to unbolt; to open; as, to unbar a gate. Heber.",
  "singlet - An unlined or undyed waistcoat; a single garment; -- opposed to doublet. [Prov. Eng.]",
  "voltaplast - A form of voltaic, or galvanic, battery suitable for use electrotyping. G. Francis.",
  "interpone - To interpose; to insert or place between. [R.] Cudworth.",
  "conducibly - In a manner to promote. [R.]",
  "fornicated - 1. Vaulted like an oven or furnace; arched. 2. (Bot.)  Arching over; overarched. Gray.",
  "quakeress - A woman who is a member of the Society of Friends.",
  "herrenhaus - See Legislature, Austria, Prussia.",
  "utriculoid - Resembling a bladder; utricular; utriculate. Dana.",
  "syngenesious - Having the stamens united by the anthers; of or pertaining to the Syngenesia.",
  "outland - Foreign; outlandish. [Obs.] Strutt.",
  "paviage - A contribution or a tax for paving streets or highways. Bouvier.",
  "governail - Management; mastery. [Obs.] Chaucer. Spenser.",
  "yttro-columbite - A tantalate of uranium, yttrium, and calcium, of a brown or black color.",
  "antalgic - Alleviating pain. -- n.  A medicine to alleviate pain; an anodyne. [R.]",
  "electrine - 1. Belonging to, or made of, amber. 2. Made of electrum, an alloy used by the ancients.",
  "subarachnoidal - Situated under the arachnoid membrane.",
  "natter - To find fault; to be peevish. [Prov. Eng. or Scot.]",
  "mormonism - The doctrine, system, and practices of the Mormons.",
  "quitture - A discharge; an issue. [Obs.] To cleanse the quitture from thy wound. Chapman.",
  "cartman - One who drives or uses a cart; a teamster; a carter.",
  "conceitedly - 1. In an egotistical manner. 2. Fancifully; whimsically.",
  "bedright - The duty or privilege of the marriage bed. Shak.",
  "heathenness - State of being heathen or like the heathen.",
  "phocine - Of or pertaining to the seal tribe; phocal.",
  "alamire - The lowest note but one in Guido Aretino's scale of music.",
  "trajetry - See Treget, Tregetour, and Tregetry. [Obs.]",
  "sea goddess - A goddess supposed to live in or reign over the sea, or some part of the sea.",
  "enharbor - To find harbor or safety in; to dwell in or inhabit. W. Browne.",
  "crocketing - Ornamentation with crockets. Ruskin.",
  "finedraw - To sew up, so nicely that the seam is not perceived; to renter. Marryat.",
  "gardon - A European cyprinoid fish; the id.",
  "interaxal - Situated in an interaxis. Gwilt.",
  "monophthongal - Consisting of, or pertaining to, a monophthong.",
  "checkroll - A list of servants in a household; -- called also chequer roll.",
  "rackwork - Any mechanism having a rack, as a rack and pinion.",
  "tepid - Moderately warm; lukewarm; as, a tepid bath; tepid rays; tepid vapors. -- Tep\"id*ness, n.",
  "fraughting - Constituting the freight or cargo. [Obs.] \"The fraughting souls within her.\" Shak.",
  "scarlatina - Scarlet fever. -- Scar`la*ti\"nal, a. -- Scar*lat\"i*nous (# or #), a.",
  "humanate - Indued with humanity. [Obs.] Cranmer.",
  "gripsack - A traveler's handbag. [Colloq.]",
  "meridionally - In the direction of the meridian.",
  "capitalness - The quality of being capital; preeminence. [R.]",
  "octonocular - Having eight eyes. Derham.",
  "debarrass - To disembarrass; to relieve. [R.]",
  "arctoidea - A group of the Carnivora, that includes the bears, weasels, etc.",
  "eophytic - Of or pertaining to eophytes.",
  "stiff-neckedness - The quality or state of being stiff-necked; stubbornness.",
  "lutulence - The state or quality of being lutulent.",
  "prestigiator - A juggler; prestidigitator. [Obs.] Dr. H. More.",
  "endospore - The thin inner coat of certain spores.",
  "tampan - A venomous South African tick. Livingstone.",
  "mordicancy - A biting quality; corrosiveness. [R.] Evelyn.",
  "panic-stricken - Struck with a panic, or sudden fear. Burke.",
  "exoticism - The state of being exotic; also, anything foreign, as a word or idiom; an exotic.",
  "wheeled - Having wheels; -- used chiefly in composition; as, a four- wheeled carriage.",
  "breedbate - One who breeds or originates quarrels. [Obs.] \"No telltale nor no breedbate.\" Shak.",
  "brenne - To burn. [Obs.] Chaucer. Consuming fire brent his shearing house or stall. W. Browne.",
  "immoderation - Want of moderation. Hallywell.",
  "madrepore - Any coral of the genus Madrepora; formerly, often applied to any stony coral.",
  "mangcorn - A mixture of wheat and rye, or other species of grain. [Prov Eng.]",
  "mecate - A rope of hair or of maguey fiber, for tying horses, etc. [Southwestern U. S.]",
  "gastroduodenal - Pertaining to the stomach and duodenum; as, the gastroduodenal artery.",
  "presentimental - Of nature of a presentiment; foreboding. [R.] Coleridge.",
  "sceptral - Of or pertaining to a scepter; like a scepter.",
  "infeasibility - The state of being infeasible; impracticability.",
  "entrammel - To trammel; to entangle. Bp. Hacket.",
  "yaksha - A kind of demigod attendant on Kuvera, the god of wealth.",
  "adnascent - Growing to or on something else. \"An adnascent plant.\" Evelyn.",
  "pleuropericardial - Of or pertaining to the pleura and pericardium.",
  "cerographical - Of or pertaining to cerography.",
  "endecaphyllous - Composed of eleven leaflets; -- said of a leaf.",
  "misproceeding - Wrong or irregular proceding.",
  "suspectiousness - Suspiciousness; cause for suspicion. [Obs. & R.] Ld. Berners.",
  "prismatically - In the form on manner of a prism; by means of a prism.",
  "aperitive - Serving to open; aperient. Harvey.",
  "psychogenesis - Genesis through an internal force, as opposed to natural selection.",
  "untruism - Something not true; a false statement. [Recent & R.] A. Trollope.",
  "furbisher - One who furbishes; esp., a sword cutler, who finishes sword blades and similar weapons.",
  "hyperdicrotic - Excessive dicrotic; as, a hyperdicrotic pulse.",
  "indistinctible - Indistinguishable. [Obs.] T. Warton.",
  "buffoonish - Like a buffoon; consisting in low jests or gestures. Blair.",
  "terebenthene - Oil of turpentine. See Turpentine.",
  "viewiness - The quality or state of being viewy, or of having unpractical views.",
  "dishabited - Rendered uninhabited. \"Dishabited towns.\" R. Carew.",
  "salvationist - An evangelist, a member, or a recruit, of the Salvation Army.",
  "entozooelogist - One versed in the science of the Entozoa.",
  "atomist - One who holds to the atomic philosophy or theory. Locke.",
  "minionship - State of being a minion. [R.]",
  "caprid - Of or pertaining to the tribe of ruminants of which the goat, or genus Capra, is the type.",
  "clubroom - The apartment in which a club meets. Addison.",
  "acanthopteri - A group of teleostean fishes having spiny fins. See Acanthopterygii.",
  "horticulturist - One who practices horticulture.",
  "contently - In a contented manner. [Obs.]",
  "dialectician - One versed in dialectics; a logician; a reasoner.",
  "desertlessly - Undeservedly. [R.] Beau. & Fl.",
  "tachygraph - An example of tachygraphy; esp., an ancient Greek or Roman tachygraphic manuscript.",
  "urson - The Canada porcupine. See Porcupine.",
  "andesine - A kind of triclinic feldspar found in the Andes.",
  "aviation - The art or science of flying.",
  "tohew - To hew in pieces. [Obs.] Chaucer.",
  "divertissement - A short ballet, or other entertainment, between the acts of a play. Smart.",
  "exiccate - See Exsiccate. [Obs.] Holland.",
  "skyrocket - A rocket that ascends high and burns as it flies; a species of fireworks.",
  "newfashioned - Made in a new form, or lately come into fashion.",
  "deified - Honored or worshiped as a deity; treated with supreme regard; godlike.",
  "excernent - Connected with, or pertaining to, excretion.",
  "anthesis - The period or state of full expansion in a flower. Gray.",
  "overreacher - One who overreaches; one who cheats; a cheat.",
  "promiscuousness - The quality or state of being promiscuous.",
  "profiting - Gain; advantage; profit. That thy profiting may appear to all. 1 Tim. iv. 15.",
  "big-bellied - Having a great belly; as, a big-bellied man or flagon; advanced in pregnancy.",
  "loiterer - 1. One who loiters; an idler. 2. An idle vagrant; a tramp. [Obs.] Bp. Sanderson.",
  "kinkhaust - Whooping cough. [Obs.or Prov. Eng.]",
  "cursitating - Moving about slightly. [R.] H. Bushnell.",
  "forethoughtful - Having forethought. [R.]",
  "emporetical - Pertaining to an emporium; relating to merchandise. [Obs.] Johnson.",
  "promorphologist - One versed in the science of promorphology.",
  "infraclavicular - Below the clavicle; as, the infraclavicular fossa.",
  "absist - To stand apart from; top leave off; to desist. [Obs.] Raleigh.",
  "paleobotany - That branch of paleontology which treats of fossil plants.",
  "dispensatorily - In the way of dispensation; dispensatively.",
  "propugnacle - A fortress. [Obs.] Howell.",
  "quirt - A rawhide whip plaited with two thongs of buffalo hide T. Roosevelt.",
  "acetable - An acetabulum; or about one eighth of a pint. [Obs.] Holland.",
  "arsesmart - Smartweed; water pepper. Dr. Prior.",
  "shroffage - The examination of coins, and the separation of the good from the debased. [East Indies]",
  "assistantly - In a manner to give aid. [R.]",
  "ojo - A spring, surrounded by rushes or rank grass; an oasis. [Southwestern U.S.] Bartlett.",
  "factive - Making; having power to make. [Obs.] \"You are . . . factive, not destructive.\" Bacon.",
  "urnal - Of or pertaining to an urn; effected by an urn or urns. \"Urnal interments.\" Sir T. Browne.",
  "aguilt - To be guilty of; to offend; to sin against; to wrong. [Obs.] Chaucer.",
  "missound - To sound wrongly; to utter or pronounce incorrectly. E,Hall.",
  "precis - A concise or abridged statement or view; an abstract; a summary.",
  "coadjust - To adjust by mutual adaptations. R. Owen.",
  "luteous - Yellowish; more or less like buff.",
  "equivalve - Having the valves equal in size and from, as in most bivalve shells.",
  "stinter - One who, or that which, stints.",
  "neuvaines - Prayers offered up for nine successive days.",
  "brothel - A house of lewdness or ill fame; a house frequented by prostitutes; a bawdyhouse.",
  "whopping - Very large; monstrous; astonishing; as, a whapping story. [Colloq.]",
  "midwinter - The middle of winter. Dryden.",
  "clonic - Having an irregular, convulsive motion. Dunglison. Clonic spasm. (Med.) See under Spasm.",
  "placability - The quality or state of being placable or appeasable; placable disposition.",
  "underact - To perform inefficiently, as a play; to act feebly.",
  "decerp - To pluck off; to crop; to gather. [Obs.]",
  "guttate - Spotted, as if discolored by drops.",
  "wellat - The king parrakeet See under King.",
  "sauropsida - A comprehensive group of vertebrates, comprising the reptiles and birds.",
  "bisegment - One of tow equal parts of a line, or other magnitude.",
  "paviin - A glucoside found in species of the genus Pavia of the Horse- chestnut family.",
  "grumpily - In a surly manner; sullenly. [Colloq.]",
  "photology - The doctrine or science of light, explaining its nature and phenomena; optics.",
  "swich - Such. [Obs.] Swich things as that I know I will declare. Chaucer.",
  "etruscan - Of or relating to Etruria. -- n.  A native or inhabitant of Etruria.",
  "disputison - Dispute; discussion. [Obs.] Chaucer.",
  "epistolical - Pertaining to letters or epistles; in the form or style of letters; epistolary.",
  "aponeurotic - Of or pertaining to an aponeurosis.",
  "swanherd - One who tends or marks swans; as, the royal swanherd of England.",
  "metayage - A system of farming on halves. [France & Italy]",
  "lyriferous - Having a lyre-shaped shoulder girdle, as certain fishes.",
  "workbasket - A basket for holding materials for needlework, or the like.",
  "orc - The grampus. [Written also ork and orch.] Milton.",
  "euphorbin - A principle, or mixture of principles, derived from various species of Euphorbia.",
  "matricidal - Of or pertaining to matricide.",
  "penknife - A small pocketknife; formerly, a knife used for making and mending quill pens.",
  "atwirl - Twisted; distorted; awry. [R.] Halliwell.",
  "priestliness - The quality or state of being priestly. R. Browning.",
  "stayship - A remora, -- fabled to stop ships by attaching itself to them.",
  "collectible - Capable of being collected.",
  "kayles - A game; ninepins. [Prov Eng.] Carew.",
  "suscitability - Capability of being suscitated; excitability. [Obs.] B. Jonson.",
  "lymphate - Frightened into madness; raving. [Obs.]",
  "boothale - To forage for booty; to plunder. [Obs.] Beau. & Fl.",
  "synthetize - To combine; to unite in regular structure. [R.]",
  "commixtion - Commixture; mingling. [R.] An exact commixtion of the ingredients. Boyle.",
  "cosmoramic - Of or pertaining to a cosmorama."
]