export default [
  "firer - One who fires or sets fire to anything; an incendiary. [R.] R. Carew.",
  "brachyptera - A group of Coleoptera having short wings; the rove beetles.",
  "homoplastic - Of or pertaining to homoplasty; as, homoplasticorgans; homoplastic forms.",
  "allogeneous - Different in nature or kind. [R.]",
  "cronian - Saturnian; -- applied to the North Polar Sea. [R.] Milton.",
  "wordbook - A collection of words; a vocabulary; a dictionary; a lexicon.",
  "bibbe - To drink; to tipple. [Obs.] This miller hath . . . bibbed ale. Chaucer.",
  "melissa - A genus of labiate herbs, including the balm, or bee balm (Melissa officinalis).",
  "forbruise - To bruise sorely or exceedingly. [Obs.] All forbrosed, both back and side. Chaucer.",
  "splotch - A spot; a stain; a daub. R. Browning.",
  "turfman - A turfite; a votary of the turf, or race course. [Colloq.]",
  "abdal - A religious devotee or dervish in Persia.",
  "inferential - Deduced or deducible by inference. \"Inferential proofs.\" J. S. Mill.",
  "ophiomorphous - Having the form of a serpent.",
  "incorrodible - Incapable of being corroded, consumed, or eaten away.",
  "capeline - A hood-shaped bandage for the head, the shoulder, or the stump of an amputated limb.",
  "anagrammatical - Pertaining to, containing, or making, anagram. -- An`a*gram*mat\"ic*al*ly, adv.",
  "auchenium - The part of the neck nearest the back.",
  "subsequently - At a later time; afterwards.",
  "gems-horn - An organ stop with conical tin pipes.",
  "mesopodium - The middle portion of the foot in the Gastropoda and Pteropoda.",
  "washhouse - An outbuilding for washing, esp. one for washing clothes; a laundry.",
  "sea hen - the common guillemot; -- applied also to various other sea birds.",
  "tac - A kind of customary payment by a tenant; -- a word used in old records. Cowell. Burrill.",
  "sarcophagy - The practice of eating flesh.",
  "fluoranthene - A white crystalline hydrocarbon C",
  "exect - To cut off or out. [Obs.] See Exsect. Harvey.",
  "theophilanthropism - The doctrine of the theophilanthropists; theophilanthropy.",
  "anientise - To frustrate; to bring to naught; to annihilate. [Obs.] Chaucer.",
  "chemically - According to chemical principles; by chemical process or operation.",
  "unrebukable - Not deserving rebuke or censure; blameless. 1 Tim. vi. 14.",
  "offerer - One who offers; esp., one who offers something to God in worship. Hooker.",
  "recontinuance - The act or state of recontinuing.",
  "dimission - Leave to depart; a dismissing. [Obs.] Barrow.",
  "alumnus - A pupil; especially, a graduate of a college or other seminary of learning.",
  "castor bean - The bean or seed of the castor-oil plant (Ricinus communis, or Palma Christi.)",
  "obeseness - Quality of being obese; obesity.",
  "phytogeographical - Of or pertaining to phytogeography.",
  "barbellate - Having short, stiff hairs, often barbed at the point. Gray.",
  "disembarrassment - Freedom or relief from impediment or perplexity.",
  "geordie - A name given by miners to George Stephenson's safety lamp. Raymond.",
  "casings - Dried dung of cattle used as fuel. [Prov. Eng.] Waterland.",
  "labipalpus - One of the labial palpi of an insect. See Illust. under Labium.",
  "rivose - Marked with sinuate and irregular furrows.",
  "inermis - Unarmed; destitute of prickles or thorns, as a leaf. Gray.",
  "addressee - One to whom anything is addressed.",
  "subindicate - To indicate by signs or hints; to indicate imperfectly. [R.] Dr. H. More.",
  "horrification - That which causes horror. [R.] Miss Edgeworth.",
  "papaverine - An alkaloid found in opium. It has a weaker therapeutic action than morphine.",
  "fassaite - A variety of pyroxene, from the valley of Fassa, in the Tyrol.",
  "bat printing - A mode of printing on glazed ware.",
  "sphygmographic - Relating to, or produced by, a sphygmograph; as, a sphygmographic tracing.",
  "comboloio - A Mohammedan rosary, consisting of ninety-nine beads. Byron.",
  "megalopolis - A chief city; a metropolis. [R.]",
  "lovelily - In manner to excite love; amiably. [R.] Otway.",
  "reminder - One who, or that which, reminds; that which serves to awaken remembrance.",
  "jill - A young woman; a sweetheart. See Gill. Beau. & Fl.",
  "ronne - obs. imp. pl., and Ron\"nen (,  obs. p. p. of Renne, to run. Chaucer.",
  "crummable - Capable of being crumbed or broken into small pieces.",
  "incloister - To confine as in a cloister; to cloister. Lovelace.",
  "partly - In part; in some measure of degree; not wholly. \"I partly believe it.\" 1 Cor. xi. 18.",
  "gerbe - A kind of ornamental firework. Farrow.",
  "ozonize - (a) To convert into ozone, as oxygen. (b) To treat with ozone.",
  "haemacytometer - An apparatus for determining the number of corpuscles in a given quantity of blood.",
  "impressionless - Having the quality of not being impressed or affected; not susceptible.",
  "boshbok - A kind of antelope. See Bush buck.",
  "debosh - To debauch. [Obs.] \"A deboshed lady.\" Beau. & Fl.",
  "endocyst - The inner layer of the cells of Bryozoa.",
  "superfice - A superficies. [Obs.] Dryden.",
  "water partridge - The ruddy duck. [Local, U. S.]",
  "roughness - The quality or state of being rough.",
  "crebrous - Frequent; numerous. [Obs.] Goodwin.",
  "squitee - The squeteague; -- called also squit.",
  "electricalness - The state or quality of being electrical.",
  "ladrone - A robber; a pirate; hence, loosely, a rogue or rascal.",
  "luxation - The act of luxating, or the state of being luxated; a dislocation.",
  "unpure - Not pure; impure. -- Un*pure\"ly, adv. -- Un*pure\"ness, n.",
  "crinoid - Crinoidal. -- n.  One of the Crinoidea.",
  "scentless - Having no scent. The scentless and the scented rose. Cowper.",
  "philanderer - One who hangs about women; a male flirt. [R.] C. Kingsley.",
  "eyeservant - A servant who attends faithfully to his duty only when watched.",
  "ignifluous - Flowing with fire. [Obs.] Cockerman.",
  "solere - A loft or garret. See Solar, n. Sir W. Scott.",
  "premonitor - One who, or that which, gives premonition.",
  "spinstress - A woman who spins. T. Brown.",
  "streaked - 1. Marked or variegated with stripes. 2. Uncomfortable; out of sorts. [Local, U.S.]",
  "consentingly - With consent; in a compliant manner. Jer. Taylor.",
  "ferretto - Copper sulphide, used to color glass. Hebert.",
  "flavorous - Imparting flavor; pleasant to the taste or smell; sapid. Dryden.",
  "earth-tongue - A fungus of the genus Geoglossum.",
  "strophiole - A crestlike excrescence about the hilum of certain seeds; a caruncle.",
  "subperitoneal - Situated under the peritoneal membrane.",
  "chameleonize - To change into various colors. [R.]",
  "corticiform - Resembling, or having the form of, bark or rind.",
  "boulevardier - A frequenter of a city boulevard, esp. in Paris.  F. Harrison.",
  "rigol - A circle; hence, a diadem. [Obs.] Shak.",
  "entend - To attend to; to apply one's self to. [Obs.] Chaucer.",
  "sustentacle - Sustenance. [Obs.] Dr. H. More.",
  "mittent - Sending forth; emitting. [Obs.] Wiseman.",
  "dephlegmatory - Pertaining to, or producing, dephlegmation.",
  "forweary - To weary extremely; to dispirit. [Obs.] Spenser.",
  "tetricity - Crabbedness; perverseness. [Obs.]",
  "misrepresentative - Tending to convey a wrong impression; misrepresenting.",
  "scintilla - A spark; the least particle; an iota; a tittle. R. North.",
  "hoistaway - A mechanical lift. See Elevator.",
  "atomism - The doctrine of atoms. See Atomic philosophy, under Atomic.",
  "extoller - One who extols; one who praises.",
  "reedless - Destitute of reeds; as, reedless banks.",
  "transcalency - The quality or state of being transcalent.",
  "effrontuously - Impudently. [Obs.] R. North.",
  "pedantism - The office, disposition, or act of a pedant; pedantry. [Obs.]",
  "diaphote - An instrument designed for transmitting pictures by telegraph. Fallows.",
  "annelid - Of or pertaining to the Annelida. -- n.  One of the Annelida.",
  "incandescence - A white heat, or the glowing or luminous whiteness of a body caused by intense heat.",
  "co-lessor - A partner in giving a lease.",
  "volage - Light; giddy. [Obs.] They wroughten all their lust volage. Chaucer.",
  "planarian - One of the Planarida, or Dendrocoela; any turbellarian worm. -- Pla*na\"ri*an, a.",
  "sailable - Capable of being sailed over; navigable; as, a sailable river.",
  "accessarily - In the manner of an accessary.",
  "overstep - To step over or beyond; to transgress. Shak.",
  "schistosity - The quality or state of being schistose.",
  "allower - 1. An approver or abettor. [Obs.] 2. One who allows or permits.",
  "confinity - Community of limits; contiguity. [R.] Bailey.",
  "remasticate - To chew or masticate again; to chew over and over, as the cud.",
  "heptone - A liquid hydrocarbon, C7H10, of the valylene series.",
  "chaunterie - See Chantry. [Obs.] Chaucer.",
  "stibiconite - A native oxide of antimony occurring in masses of a yellow color.",
  "indiretin - A dark brown resinous substance obtained from indican.",
  "longevous - Living a long time; of great age. Sir T. Browne.",
  "interganglionic - Between and uniting the nervous ganglions; as, interganglionic cords.",
  "thinner - One who thins, or makes thinner.",
  "hatchery - A house for hatching fish, etc.",
  "padelion - A plant with pedately lobed leaves; the lady's mantle.",
  "trolley car - A motor car to which the current is conveyed by means of a trolley.",
  "cramponee - Having a cramp or square piece at the end; -- said of a cross so furnished.",
  "zizel - The suslik. [Written also zisel.]",
  "double-dye - To dye again or twice over. To double-dye their robes in scarlet. J. Webster.",
  "democratical - Democratic. The democratical was democratically received. Algernon Sidney.",
  "chordee - A painful erection of the penis, usually with downward curvature, occurring in gonorrhea.",
  "clapperclaw - 1. To fight and scratch. C. Smart. 2. To abuse with the tongue; to revile; to scold.",
  "petitionee - A person cited to answer, or defend against, a petition.",
  "overweather - To expose too long to the influence of the weather. [Obs.] Shak.",
  "thwartingly - In a thwarting or obstructing manner; so as to thwart.",
  "motioner - One who makes a motion; a mover. Udall.",
  "aphorist - A writer or utterer of aphorisms.",
  "dissyllabize - To form into two syllables; to dyssyllabify.",
  "exhibiter - One who exhibits; one who presents a petition, charge or bill. Shak.",
  "domanial - Of or relating to a domain or to domains.",
  "polyacoustics - The art of multiplying or magnifying sounds.",
  "semiological - Same as Semeiography, Semeiology, Semeiological.",
  "ineptness - Unfitness; ineptitude. The feebleness and miserable ineptness of infancy. Dr. H. More.",
  "astarboard - Over to the starboard side; -- said of the tiller.",
  "debarb - To deprive of the beard. [Obs.] Bailey.",
  "microtomist - One who is skilled in or practices microtomy.",
  "bookstall - A stall or stand where books are sold.",
  "almightiness - Omnipotence; infinite or boundless power; unlimited might. Jer. Taylor.",
  "doomage - A penalty or fine for neglect. [Local, New England]",
  "semilens - The half of a lens divided along a plane passing through its axis.",
  "herpetologic - Pertaining to herpetology.",
  "applausive - Expressing applause; approbative. -- Ap*plau\"sive*ly, adv.",
  "unperfection - Want of perfection; imperfection. [Obs.] Wyclif.",
  "mustiness - The quality or state of being musty.",
  "dieter - One who diets; one who prescribes, or who partakes of, food, according to hygienic rules.",
  "illustratively - By way of illustration or elucidation. [R.] Sir T. Browne.",
  "precontrive - To contrive or plan beforehand.",
  "mechanograph - One of a number of copies of anything multiplied mechanically.",
  "scoffingly - In a scoffing manner. Broome.",
  "ropily - In a ropy manner; in a viscous or glutinous manner.",
  "annuloid - Of or pertaining to the Annuloida.",
  "spearhead - The pointed head, or end, of a spear.",
  "transpassable - Capable of being transpassed, or crossed over. [Obs.]",
  "chafeweed - The cudweed (Gnaphalium), used to prevent or cure chafing.",
  "featherstitch - A kind of embroidery stitch producing a branching zigzag line.",
  "heterodactylous - Having the first and second toes turned backward, as in the trogons.",
  "incitingly - So as to incite or stimulate.",
  "masterless - Destitute of a master or owner; ungoverned or ungovernable. -- Mas\"ter*less*ness, n.",
  "glandulosity - Quality of being glandulous; a collection of glands. [R.] Sir T. Browne.",
  "absinthism - The condition of being poisoned by the excessive use of absinth.",
  "ministrative - Serving to aid; ministering.",
  "entobronchium - One of the main bronchi in the lungs of birds.",
  "fly-fish - To angle, using flies for bait. Walton.",
  "causidical - Pertaining to an advocate, or to the maintenance and defense of suits.",
  "ankerite - A mineral closely related to dolomite, but containing iron.",
  "longheaded - Having unusual foresight or sagacity. -- Long\"-head`ed*ness, n.",
  "coaction - Force; compulsion, either in restraining or impelling. Sojth.",
  "priesting - The office of a priest. [Obs.] Milton.",
  "yeara - The California poison oak (Rhus diversiloba). See under Poison, a.",
  "passement - Lace, gimp, braid etc., sewed on a garment. Sir W. Scott.",
  "outbounds - The farthest or exterior bounds; extreme limits; boundaries. Spenser.",
  "compatibleness - Compatibility; consistency; fitness; agreement.",
  "ditation - The act of making rich; enrichment. [Obs.] Bp. Hall.",
  "timeful - Seasonable; timely; sufficiently early. [Obs.] Sir W. Raleigh.",
  "matachin - An old dance with swords and bucklers; a sword dance.",
  "short-wited - Having little wit; not wise; having scanty intellect or judgment.",
  "vitiously - See Vicious, Viciously, Viciousness.",
  "pantheologist - One versed in pantheology.",
  "fecks - A corruption of the word faith. Shak.",
  "deltaic - Relating to, or like, a delta.",
  "aphanipterous - Of or pertaining to the Aphaniptera.",
  "pathopoela - A speech, or figure of speech, designed to move the passion. Smart.",
  "hierapicra - A warming cathartic medicine, made of aloes and canella bark. Dunglison.",
  "crapefish - Salted codfish hardened by pressure. Kane.",
  "niblick - A kind of golf stick used to lift the ball out of holes, ruts, etc.",
  "half-hourly - Done or happening at intervals of half an hour.",
  "slewth - Sloth; idleness. [Obs.] Chaucer.",
  "nomenclatural - Pertaining or according to a nomenclature.",
  "hyperspace - An imagined space having more than three dimensions.",
  "diamido- - A prefix or combining form of Diamine. Note: [Also used adjectively.]",
  "middle-ground - That part of a picture between the foreground and the background.",
  "conjunctiveness - The state or quality of being conjunctive. Johnson.",
  "stulty - Foolish; silly. [Obs.] Testament of Love.",
  "whisperingly - In a whisper, or low voice; in a whispering manner; with whispers. Tennyson.",
  "patibulary - Of or pertaining to the gallows, or to execution. [R.] Carlyle.",
  "laird - A lord; a landholder, esp. one who holds land directly of the crown. [Scot.]",
  "tragedious - Like tragedy; tragical. [Obs.] \"Tragedious history.\" Fabyan.",
  "imbenching - A raised work like a bench. [Obs.] Parkhurst.",
  "cayuse - An Indian pony. [Northw. U. S.]",
  "inexact - Not exact; not precisely correct or true; inaccurate.",
  "superstitionist - One addicted to superstition. [Obs.] \"Blind superstitionists.\" Dr. H. More.",
  "hard-featured - Having coarse, unattractive or stern features. Smollett.",
  "bruteness - 1. Brutality. [Obs.] Spenser. 2. Insensibility. \"The bruteness of nature.\" Emerson.",
  "propodite - The sixth joint of a typical leg of a crustacean; usually, the penultimate joint.",
  "arriswise - Diagonally laid, as tiles; ridgewise.",
  "myosotis - A genus of plants. See Mouse-ear.",
  "swallower - One who swallows; also, a glutton. Tatler.",
  "sweeting - 1. A sweet apple. Ascham. 2. A darling; -- a word of endearment. Shak.",
  "toat - The handle of a joiner's plane. Knight.",
  "excalfactory - Heating; warming. [Obs.] Holland.",
  "tetraschistic - Characterized by division into four parts.",
  "capellane - The curate of a chapel; a chaplain. [Obs.] Fuller.",
  "compellatory - Serving to compel; compulsory. [R.]",
  "insheathe - To insert as in a sheath; to sheathe. Hughes.",
  "bent grass - Same as Bent, a kind of grass.",
  "passive aeroplane - One unprovided with motive power.",
  "undividual - Indivisible. [Obs.] True courage and courtesy are undividual companions. Fuller.",
  "savorless - Having no savor; destitute of smell or of taste; insipid.",
  "effluviate - To give forth effluvium. [R.] \"An effluviating power.\" Boyle.",
  "scomm - 1. A bufoon. [Obs.] L'Estrange. 2. A flout; a jeer; a gibe; a taunt. [Obs.] Fortherby.",
  "lending - 1. The act of one who lends. 2. That which is lent or furnished.",
  "siphonic - Of or pertaining to a siphon.",
  "repentingly - With repentance; penitently.",
  "umbellar - Of or pertaining to an umbel; having the form of an umbel.",
  "bearward - A keeper of bears. See Bearherd. [R.] Shak.",
  "tridentine - Of or pertaining to Trent, or the general church council held in that city.",
  "diglyph - A projecting face like the triglyph, but having only two channels or grooves sunk in it.",
  "anthemis - Chamomile; a genus of composite, herbaceous plants.",
  "capra - A genus of ruminants, including the common goat.",
  "egyptology - The science or study of Egyptian antiquities, esp. the hieroglyphics.",
  "yogi - A follower of the yoga philosophy; an ascetic. [Spelt also yokin.] Whitworth.",
  "gery - Changeable; fickle. [Obs.] Chaucer.",
  "floorwalker - One who walks about in a large retail store as an overseer and director. [U.S.]",
  "plectognath - Of or pertaining to the Plectognathi. -- n.  One of the Plectognathi.",
  "circumjacence - Condition of being circumjacent, or of bordering ou every side.",
  "saiva - One of an important religious sect in India which regards Siva with peculiar veneration.",
  "outroad - An excursion. [Obs.] \"Outrodes by the ways of Judea.\" Macc. xv. 41 (Geneva Bible).",
  "perquisited - Supplied with perquisites. [Obs.] \"Perquisited varlets frequent stand.\" Savage.",
  "cootfoot - The pharalope; -- so called because its toes are like the coot's.",
  "mycoprotein - The protoplasmic matter of which bacteria are composed.",
  "playbook - A book of dramatic compositions; a book of the play. Swift.",
  "maleficiate - To bewitch; to harm. [Obs.] Burton.",
  "hyoganoidei - A division of ganoid fishes, including the gar pikes and bowfins. -- Hy`o*ga\"noid, a.",
  "missemblance - False resemblance or semblance. [Obs.]",
  "glump - To manifest sullenness; to sulk. [Colloq.]",
  "exsufflate - To exorcise or renounce by blowing.",
  "picnicker - One who takes part in a picnic.",
  "rope-yarn - the yarn or thread of any stuff of which the strands of a rope are made.",
  "nonexecution - Neglect or failure of execution; nonperformance.",
  "disdainous - Disdainful. [Obs.] Rom. of R.",
  "flintiness - The state or quality of being flinty; hardness; cruelty. Beau. & Fl.",
  "bareheaded - Having the head uncovered; as, a bareheaded girl.",
  "rustiness - The quality or state of being rusty.",
  "spiranthy - The occasional twisted growth of the parts of a flower.",
  "faux pas - A false step; a mistake or wrong measure.",
  "temporofacial - Of or pertaining to both the temple and the face.",
  "metabolize - To change by a metabolic process. See Metabolism.",
  "bawrel - A kind of hawk. [Obs.] Halliwell.",
  "chronogrammatist - A writer of chronograms.",
  "traceable - Capable of being traced. -- Trace\"a*ble*ness, n. -- Trace\"a/bly, adv.",
  "disarmed - 1. Deprived of arms. 2. (Her.)  Deprived of claws, and teeth or beaks. Cussans.",
  "epicardiac - Of or relating to the epicardium.",
  "pasteurian - Of or pertaining to Pasteur.",
  "bloatedness - The state of being bloated.",
  "hist - Hush; be silent; -- a signal for silence. Milton.",
  "triduan - Lasting three lays; also, happening every third day. [R.] Blount.",
  "filigrane - Filigree. [Archaic] With her head . . . touches the crown of filigrane. Longfellow.",
  "hards - The refuse or coarse part of fiax; tow.",
  "carunculous - Of, pertaining to, or like, a caruncle; furnished with caruncles.",
  "insanableness - The state of being insanable; insanability; incurableness.",
  "fasciculus - 1. A little bundle; a fascicle. 2. A division of a book.",
  "indicatively - In an indicative manner; in a way to show or signify.",
  "predictor - One who predicts; a foreteller.",
  "tautozonal - Belonging to the same zone; as, tautozonal planes.",
  "round-backed - Having a round back or shoulders; round-shouldered.",
  "teleozoic - Having tissued composed of cells.",
  "zenana - The part of a dwelling appropriated to women. [India]",
  "aimless - Without aim or purpose; as, an aimless life. -- Aim\"less*ly, adv. -- Aim\"less*ness, n.",
  "nestful - As much or many as will fill a nest.",
  "fusiform - Shaped like a spindle; tapering at each end; as, a fusiform root; a fusiform cell.",
  "resourceless - Destitute of resources. Burke. -- Re*source\"less*ness, n. R. Browning.",
  "dipneumona - A group of spiders having only two lunglike organs. [Written also Dipneumones.]",
  "forgivable - Capable of being forgiven; pardonable; venial. Sherwood.",
  "furacity - Addictedness to theft; thievishness. [Obs.]",
  "volubility - The quality or state of being voluble (in any of the senses of the adjective).",
  "roborant - Strengthening. -- n. (Med.)  A strengthening medicine; a tonic.",
  "troopship - A vessel built or fitted for the conveyance of troops; a transport. [Eng.]",
  "indiminishable - Incapable of being diminished. [R.] Milton.",
  "villanella - An old rustic dance, accompanied with singing.",
  "cyanosed - Rendered blue, as the surface of the body, from cyanosis or deficient a",
  "subsacral - Situated under, or on the ventral side of, the sacrum.",
  "porthook - One of the iron hooks to which the port hinges are attached. J. Knowles.",
  "temporomaxillary - Of or pertaining to both the temple or the temporal bone and the maxilla.",
  "pitchstone - An igneous rock of semiglassy nature, having a luster like pitch.",
  "cervicide - The act of killing deer; deer-slaying. [R.]",
  "taborine - A small, shallow drum; a tabor.",
  "inobservance - Want or neglect of observance. Bacon.",
  "overspin - To spin out to too great length; to protract unduly. W. Cartwright.",
  "idealogic - Of or pertaining to an idealogue, or to idealization.",
  "lithomarge - A clay of a fine smooth texture, and very sectile.",
  "oughtness - The state of being as a thing ought to be; rightness. [R.] N. W. Taylor.",
  "unchristen - To render unchristian. [Obs. & R.] Milton.",
  "outmaneuver - To surpass, or get an advantage of, in maneuvering; to outgeneral.",
  "unrespect - Disrespect. [Obs.] \"Unrespect of her toil.\" Bp. Hall.",
  "immesh - To catch or entangle in, or as in, the meshes of a net. or in a web; to insnare.",
  "melain - The dark coloring matter of the liquid of the cuttlefish.",
  "decemlocular - Having ten cells for seeds.",
  "shaffler - A hobbler; one who limps; a shuffer. [Obs. or Prov.Eng.]",
  "corrigendum - A fault or error to be corrected.",
  "saliniform - Having the form or the qualities of a salt, especially of common salt.",
  "governorship - The office of a governor.",
  "hemathermal - Warm-blooded; hematothermal. [R]",
  "hydrophanous - Made transparent by immersion in water.",
  "peristeria - A genus of orchidaceous plants. See Dove plant.",
  "kamsin - A hot southwesterly wind in Egypt, coming from the Sahara. [Written also Khamseen.]",
  "lichened - Belonging to, or covered with, lichens. Tennyson.",
  "perrie - Precious stones; jewels. [Obs.] [Written also perre, perrye, etc.] Chaucer.",
  "flaily - Acting like a flail. [Obs.] Vicars.",
  "taoism - One of the popular religions of China, sanctioned by the state. -- Ta\"o*ist, a. & n.",
  "admiring - Expressing admiration; as, an admiring glance. -- Ad*mir\"ing*ly, adv. Shak.",
  "facetiae - Witty or humorous writings or saying; witticisms; merry conceits.",
  "dicyemid - Like or belonging to the Dicyemata. -- n.  One of the Dicyemata.",
  "certainly - Without doubt or question; unquestionably.",
  "nursemaid - A girl employed to attend children.",
  "knowableness - The state or quality of being knowable. Locke.",
  "superexcellent - Excellent in an uncommon degree; very excellent. Drayton.",
  "episepalous - Growing on the sepals or adnate to them.",
  "micrococcal - Of or pertaining to micrococci; caused by micrococci. Nature.",
  "cirsocele - The varicose dilatation of the spermatic vein.",
  "imbroccata - A hit or thrust. [Obs.] B. Jonson.",
  "presentoir - An ornamental tray, dish, or the like, used as a salver.",
  "axiomatically - By the use of axioms; in the form of an axiom.",
  "respectant - Placed so as to face one another; -- said of animals.",
  "anergia - Lack of energy; inactivity. -- An*er\"gic (#), a.",
  "discouraging - Causing or indicating discouragement. -- Dis*cour\"a*ging*ly, adv.",
  "adject - To add or annex; to join. Leland.",
  "incriminate - To accuse; to charge with a crime or fault; to criminate.",
  "balneotherapy - The treatment of disease by baths.",
  "skinker - One who serves liquor; a tapster.",
  "precipitately - In a precipitate manner; headlong; hastily; rashly. Swift.",
  "biplicate - Twice folded together. Henslow.",
  "assiduate - Unremitting; assiduous. [Obs.] \"Assiduate labor.\" Fabyan.",
  "shasta sam - A game like California Jack, except that the pack drawn from is turned face down.",
  "offension - Assault; attack. [Obs.] Chaucer.",
  "burhel - The wild Himalayan, or blue, sheep (Ovis burrhel).",
  "ordinable - Capable of being ordained or appointed. [Obs.]",
  "juxtaposit - To place in close connection or contiguity; to juxtapose. Derham.",
  "baby farmer - One who keeps a baby farm.",
  "yeomanlike - Resembling, or suitable to, a yeoman; yeomanly.",
  "gambison - A defensive garment formerly in use for the body, made of cloth stuffed and quilted.",
  "bimuscular - Having two adductor muscles, as a bivalve mollusk.",
  "omphalotomy - The operation of dividing the navel-string.",
  "abashment - The state of being abashed; confusion from shame.",
  "churchmanly - Pertaining to, or becoming, a churchman. Milman.",
  "erumpent - Breaking out; -- said of certain fungi which burst through the texture of leaves.",
  "plumosity - The quality or state of being plumose.",
  "emule - To emulate. [Obs.] \"Emuled of many.\" Spenser.",
  "ctenostomata - A suborder of Bryozoa, usually having a circle of bristles below the tentacles.",
  "adolescency - The quality of being adolescent; youthfulness.",
  "urocele - A morbid swelling of the scrotum due to extravasation of urine into it.",
  "caducous - Dropping off or disappearing early, as the calyx of a poppy, or the gills of a tadpole.",
  "sclerodermata - The stony corals; the Madreporaria.",
  "apiculated - Terminated abruptly by a small, distinct point, as a leaf.",
  "resublime - To sublime again. Newton. -- Re*sub`li*ma\"tion, n.",
  "urosome - The abdomen, or post-abdomen, of arthropods.",
  "reassimilate - To assimilate again. -- Re`as*sim`i*la\"tion, n.",
  "gastronomer - One fond of good living; an epicure. Sir W. Scott.",
  "ovato-cylindraceous - Same as Ovate-cylindraceous.",
  "confalon - One of a fraternity of seculars, also called Penitents.",
  "noninflectional - Not admitting of, or characterized by, inflection.",
  "saltatoria - A division of Orthoptera including grasshoppers, locusts, and crickets.",
  "maturing - Approaching maturity; as, maturing fruits; maturing notes of hand.",
  "hairstreak - A butterfly of the genus Thecla; as, the green hairstreak (T. rubi).",
  "matabele - A warlike South African Kaffir tribe.",
  "annotinous - A year old; in Yearly growths.",
  "illuminous - Bright; clear. [R.] H. Taylor.",
  "exciple - The outer part of the fructification of most lichens.",
  "yachtsman - One who owns or sails a yacht; a yachter.",
  "obligatorily - In an obligatory manner; by reason of obligation. Foxe.",
  "quadrifoliate - Four-leaved; having the leaves in whorls of four.",
  "submental - Situated under the chin; as, the submental artery.",
  "dispansion - Act of dispanding, or state of being dispanded. [Obs.]",
  "hexylic - Pertaining to, or derived from, hexyl or hexane; as, hexylic alcohol.",
  "well-willer - One who wishes well, or means kindly. [R.] \"A well-willer of yours.\" Brydges.",
  "herdswoman - A woman who tends a herd. Sir W. Scott.",
  "approachability - The quality of being approachable; approachableness.",
  "dateless - Without date; having no fixed time.",
  "revolutive - Inclined to revolve things in the mind; meditative. [Obs.] Feltham.",
  "uxoricide - 1. The murder of a wife by her husband. 2. One who murders his wife.",
  "victress - A woman who wins a victory; a female victor.",
  "pamperos - A tribe of Indians inhabiting the pampas of South America.",
  "counterstroke - A stroke or blow in return. Spenser.",
  "samaroid - Resembling a samara, or winged seed vessel.",
  "plerophory - Fullness; full persuasion. \"A plerophory of assurance.\" Bp. Hall.",
  "empire state of the south - Georgia; -- a nickname.",
  "syncopist - One who syncopates. Addison.",
  "cypriot - A native or inhabitant of Cyprus.",
  "custodian - One who has care or custody, as of some public building; a keeper or superintendent.",
  "illacrymable - Incapable of weeping. [Obs.] Bailey.",
  "equangular - Having equal angles; equiangular. [R.] Johnson.",
  "paraldehyde - A polymeric modification of aldehyde obtained as a white crystalline substance.",
  "impertransible - Incapable of being passed through. [R.]",
  "participable - Capable of being participated or shared. [R.] Norris.",
  "vomitive - Causing the ejection of matter from the stomach; emetic.",
  "viceroyalty - The dignity, office, or jurisdiction of a viceroy.",
  "cyriologic - Relating to capital letters.",
  "mho - A unit of conductivity, being the reciprocal of the ohm.",
  "herein - In this. Herein is my Father glorified, that ye bear much fruit. John xv. 8.",
  "aproned - Wearing an apron. A cobbler aproned, and a parson gowned. Pope.",
  "czarowitz - The title of the eldest son of the czar of Russia.",
  "evacuative - Serving of tending to evacuate; cathartic; purgative.",
  "costage - Expense; cost. [Obs.] Chaucer.",
  "theopathy - Capacity for religious affections or worship.",
  "revisory - Having the power or purpose to revise; revising. Story.",
  "cash railway - A form of cash carrier in which a small carrier or car travels upon a kind of track.",
  "eurite - A compact feldspathic rock; felsite. See Felsite.",
  "mistranslate - To translate erroneously.",
  "odic - Of or pertaining to od. See Od. [Archaic] -- Od\"ic*al*ly, adv.",
  "strude - A stock of breeding mares. [Written also strode.] [Obs.] Bailey.",
  "deltidium - The triangular space under the beak of many brachiopod shells.",
  "unharbor - To drive from harbor or shelter.",
  "capriccioso - In a free, fantastic style.",
  "steaminess - The quality or condition of being steamy; vaporousness; mistness.",
  "macrobiotics - The art of prolonging life.",
  "tawniness - The quality or state of being tawny.",
  "prefinite - Prearranged. [Obs.] \" Set and prefinite time.\" Holland.",
  "sustainer - One who, or that which, sustains. Waterland.",
  "recoveree - The person against whom a judgment is obtained in common recovery.",
  "stonehatch - The ring plover, or dotterel. [Prov. Eng.]",
  "rivaless - A female rival. [Obs.] Richardson.",
  "photoscopic - Of or pertaining to the photoscope or its uses.",
  "handily - In a handy manner; skillfully; conveniently.",
  "hinderer - One who, or that which, hinders.",
  "thoracotomy - The operation of opening the pleural cavity by incision.",
  "mesorectum - The fold of peritoneum, or mesentery, attached to the rectum. -- Mes`o*rec\"tal, a.",
  "irresolubleness - The state or quality of being irresoluble; insolubility.",
  "rerefief - A fief held of a superior feudatory; a fief held by an under tenant. Blackstone.",
  "romanticness - The state or quality of being romantic; widness; fancifulness. Richardson.",
  "undersell - To sell the same articles at a lower price than; to sell cheaper than.",
  "regretful - Full of regret; indulging in regrets; repining. -- Re*gret\"ful*ly, adv.",
  "sanies - A thin, serous fluid commonly discharged from ulcers or foul wounds.",
  "swive - To copulate with (a woman). [Obs.] Chaucer.",
  "symbology - The art of expressing by symbols.",
  "torquate - Collared; having a torques, or distinct colored ring around the neck.",
  "extimulation - Stimulation. [Obs.] Things insipid, and without any extimulation. Bacon.",
  "forswonk - Overlabored; exhausted; worn out. [Obs.] Spenser.",
  "scytheman - One who uses a scythe; a mower. Macaulay.",
  "wifeless - Without a wife; unmarried. Chaucer.",
  "ourebi - A small, graceful, and swift African antelope, allied to the klipspringer.",
  "sachem - A chief of a tribe of the American Indians; a sagamore.",
  "czechic - Of or pertaining to the Czechs. \"One Czechic realm.\" The Nation.",
  "spellable - Capable of being spelt. Carlyle.",
  "vacuousness - The quality or state of being vacuous; emptiness; vacuity. W. Montagu.",
  "interveined - Intersected, as with veins.",
  "geminous - Double; in pairs. Sir T. Browne.",
  "unmold - To change the form of; to reduce from any form. \"Unmolding reason's mintage.\" Milton.",
  "peephole - A hole, or crevice, through which one may peep without being discovered.",
  "well-read - Of extensive reading; deeply versed; -- often followed by in.",
  "quinquelocular - Having five cells or loculi; five-celled; as, a quinquelocular pericarp.",
  "agrammatist - A illiterate person. [Obs.] Bailey.",
  "recently - Newly; lately; freshly; not long since; as, advices recently received.",
  "linearensate - Having the form of a sword, but very long and narrow.",
  "rejectitious - Implying or requiring rejection; rejectable. Cudworth.",
  "disnatured - Deprived or destitute of natural feelings; unnatural. [Obs.] Shak.",
  "head gear - 1. Headdress. 2. Apparatus above ground at the mouth of a mine or deep well.",
  "sutling - Belonging to sutlers; engaged in the occupation of a sutler. Addison.",
  "turbillion - A whirl; a vortex. Spectator.",
  "editorially - In the manner or character of an editor or of an editorial article.",
  "screw-cutting - Adapted for forming a screw by cutting; as, a screw-cutting lathe.",
  "distinguishment - Observation of difference; distinction. Graunt.",
  "jacent - Lying at length; as, the jacent posture. [R.] Sir H. Wotton.",
  "simperer - One who simpers. Sir W. Scott. A simperer that a court affords. T. Nevile.",
  "jack-a-dandy - A little dandy; a little, foppish, impertinent fellow.",
  "bicarbureted - Containing two atoms or equivalents of carbon in the molecule. [Obs. or R.]",
  "lampooner - The writer of a lampoon. \"Libelers, lampooners, and pamphleteers.\" Tatler.",
  "gymnorhinal - Having unfeathered nostrils, as certain birds.",
  "drainer - One who, or that which, drains.",
  "concessive - Implying concession; as, a concessive conjunction. Lowth.",
  "hud - A huck or hull, as of a nut. [Prov. Eng.] Wright.",
  "vituperrious - Worthy of vituperation; shameful; disgraceful. [Obs.]",
  "jackpudding - A merry-andrew; a buffoon. Milton.",
  "niched - Placed in a niche. \"Those niched shapes of noble mold.\" Tennyson.",
  "botchery - A botching, or that which is done by botching; clumsy or careless workmanship.",
  "harmaline - An alkaloid found in the plant Peganum harmala. It forms bitter, yellow salts.",
  "suborbicular - Almost orbiculate or orbicular.",
  "cracker state - Georgia; -- a nickname. See Cracker, n. 5.",
  "atrede - To surpass in council. [Obs.] Men may the olde atrenne, but hat atrede. Chaucer.",
  "goniometric - Pertaining to, or determined by means of, a goniometer; trigonometric.",
  "monitorship - The post or office of a monitor.",
  "aesthesodic - Conveying sensory or afferent impulses; -- said of nerves.",
  "scobiform - Having the form of, or resembling, sawdust or raspings.",
  "habilitation - Equipment; qualification. [Obs.] Bacon.",
  "subjectivity - The quality or state of being subjective; character of the subject.",
  "accrescent - 1. Growing; increasing. Shuckford. 2. (Bot.)  Growing larger after flowering. Gray.",
  "crummy - 1. Full of crumb or crumbs. 2. Soft, as the crumb of bread is; not crusty.",
  "retrousse - Turned up; -- said of a pug nose.",
  "donnism - Self-importance; loftiness of carriage. [Cant, Eng. Universities]",
  "pulsatory - Capable of pulsating; throbbing. Sir H. Wotton. .",
  "acondylous - Being without joints; jointless.",
  "polliwog - A tadpole; -- called also purwiggy and porwigle.",
  "abiological - Pertaining to the study of inanimate things.",
  "adipoma - A mass of fat found internally; also, a fatty tumor. -- Ad`i*pom\"a*tous, a.",
  "disshiver - To shiver or break in pieces. [Obs.]",
  "trickiness - The quality of being tricky.",
  "funge - A blockhead; a dolt; a fool. [Obs.] Burton.",
  "grame - 1. Anger; wrath; scorn. [Obs.] Chaucer. 2. Sorrow; grief; misery. [Obs.] Chaucer.",
  "ouakari - Any South American monkey of the genus Brachyurus, especially B. ouakari.",
  "instinctively - In an instinctive manner; by force of instinct; by natural impulse.",
  "adhort - To exhort; to advise. [Obs.] Feltham.",
  "pedo- - Combining forms from L. pes, pedis, foot, as pedipalp, pedireme, pedometer.",
  "polyacron - A solid having many summits or angular points; a polyhedron.",
  "tricorporal - Represented with three bodies conjoined to one head, as a lion.",
  "querele - A complaint to a court. See Audita Querela. [Obs.] Ayliffe.",
  "carpetbag - A portable bag for travelers; -- so called because originally made of carpet.",
  "cyrtostyle - A circular projecting portion.",
  "utro- - - (connection with, or relation to, the uterus; as in utro- ovarian.",
  "belibel - To libel or traduce; to calumniate. Fuller.",
  "pice - A small copper coin of the East Indies, worth less than a cent. Malcom.",
  "cauterism - The use or application of a caustic; cautery. Ferrand.",
  "recollective - Having the power of recollecting. J. Foster.",
  "gleen - To glisten; to gleam. [Obs.] Prior.",
  "myalgia - Pain in the muscles; muscular rheumatism or neuralgia.",
  "avenaceous - Belonging to, or resembling, oats or the oat grasses.",
  "featureless - Having no distinct or distinctive features.",
  "lucriferous - Gainful; profitable. [Obs.] Boyle.",
  "imponderous - Imponderable. [Obs.] Sir T. Browne. -- Im*pon\"der*ous*ness, n. [Obs.]",
  "polymathic - Pertaining to polymathy; acquainted with many branches of learning.",
  "trifarious - Facing three ways; arranged in three vertical ranks, as the leaves of veratrum.",
  "conite - A magnesian variety of dolomite.",
  "unbuild - To demolish; to raze. \"To unbuild the city.\" Shak.",
  "unfile - To remove from a file or record.",
  "water oat - Indian rice. See under Rice.",
  "displaceable - Capable of being displaced.",
  "congressman - A member of the Congress of the United States, esp. of the House of Representatives.",
  "biodynamic - Of or pertaining to biodynamics, or the doctrine of vital forces or energy.",
  "historicize - To record or narrate in the manner of a history; to chronicle. [R.]",
  "aport - On or towards the port or left side; -- said of the helm.",
  "hygrophthalmic - Serving to moisten the eye; -- sometimes applied to the lachrymal ducts.",
  "workroom - Any room or apartment used especially for labor.",
  "berried - Furnished with berries; consisting of a berry; baccate; as, a berried shrub.",
  "usurpant - Usurping; encroaching. [Obs.] Gauden.",
  "oleosity - The state or quality of being oily or fat; fatness. [R.] B. Jonson.",
  "undertaxed - Taxed too little, or at a lower rate than others.",
  "jaculate - To throw or cast, as a dart; to throw out; to emit.",
  "limbate - Bordered, as when one color is surrounded by an edging of another.",
  "excalceate - To deprive of shoes. [Obs.] Chambers.",
  "coursey - A space in the galley; a part of the hatches. Ham. Nav. Encyc.",
  "opaqueness - The state or quality of being impervious to light; opacity. Dr. H. More.",
  "supposure - Supposition; hypothesis; conjecture. [Obs.] Hudibras.",
  "fumidity - The state of being fumid; smokiness.",
  "cruset - A goldsmith's crucible or melting pot.",
  "unparented - Having no parent, or no acknowledged parent. [R.]",
  "bedspread - A bedquilt; a counterpane; a coverlet. [U. S.]",
  "surfeit-water - Water for the cure of surfeits. [Obs.] Locke.",
  "peperine - A volcanic rock, formed by the cementing together of sand, scoria, cinders, etc.",
  "retrocopulation - Copulation from behind. Sir T. Browne.",
  "fault-finder - One who makes a practice off discovering others' faults and censuring them; a scold.",
  "intervisit - To exchange visits. [R.] Evelyn.",
  "vocabulist - The writer or maker of a vocabulary; a lexicographer.",
  "bushfighter - One accustomed to bushfighting. Parkman.",
  "assessorship - The office or function of an assessor.",
  "dissertator - One who writers a dissertation; one who discourses. Boyle.",
  "laughingly - With laughter or merriment.",
  "intermodillion - The space between two modillions.",
  "vineal - Of or pertaining to vines; containing vines. [R.] Sir T. Browne.",
  "tactician - One versed in tactics; hence, a skillful maneuverer; an adroit manager.",
  "pelagianism - The doctrines of Pelagius.",
  "iliolumbar - Pertaining to the iliac and lumbar regions; as, the iliolumbar artery.",
  "sart - An assart, or clearing. [Obs.] Bailey.",
  "coverchief - A covering for the head. [Obs.] Chaucer.",
  "mesosperm - A membrane of a seed. See Secundine.",
  "precondemn - To condemn beforehand. -- Pre*con`dem*na\"tion, n.",
  "anacoluthic - Lacking grammatical sequence. -- An`a*co*lu\"thic*al*ly, adv.",
  "lithodomous - Like, or pertaining to, Lithodomus; lithophagous.",
  "deoxygenation - The act or operation of depriving of oxygen.",
  "fitment - The act of fitting; that which is proper or becoming; equipment. [Obs.] Shak.",
  "affectionated - Disposed; inclined. [Obs.] Affectionated to the people. Holinshed.",
  "lousiness - The state or quality of being lousy.",
  "eriach - A recompense formerly given by a murderer to the relatives of the murdered person.",
  "unpaint - To remove the paint from; to efface, as a painting. Parnell.",
  "bookselling - The employment of selling books.",
  "indivertible - Not to be diverted or turned aside. [R.] Lamb.",
  "slovenness - Slovenliness. [Obs.] Fuller.",
  "absterse - To absterge; to cleanse; to purge away. [Obs.] Sir T. Browne.",
  "antibillous - Counteractive of bilious complaints; tending to relieve biliousness.",
  "silverfin - A small North American fresh-water cyprinoid fish (Notropis Whipplei).",
  "nihility - Nothingness; a state of being nothing.",
  "nosed - Having a nose, or such a nose; -- chieflay used in composition; as, pug-nosed.",
  "dischevele - Disheveled. [Obs.] Chaucer.",
  "gauging rod - See Gauge rod, under Gauge, n.",
  "agitable - Capable of being agitated, or easily moved. [R.]",
  "dolcino - A small bassoon, formerly much used. Simmonds.",
  "horse-litter - A carriage hung on poles, and borne by and between two horses. Milton.",
  "knotless - Free from knots; without knots. \"Silver firs with knotless trunks.\" Congreve.",
  "anisic - Of or derived from anise; as, anisic acid; anisic alcohol.",
  "pile-worn - Having the pile worn off; threadbare.",
  "pound-breach - The breaking of a public pound for releasing impounded animals. Blackstone.",
  "merman - The male corresponding to mermaid; a sea man, or man fish.",
  "shoer - One who fits shoes to the feet; one who furnishes or puts on shoes; as, a shoer of horses.",
  "administerial - Pertaining to administration, or to the executive part of government.",
  "capuccio - A capoch or hood. [Obs.] Spenser.",
  "pedestrial - Of or pertaining to the feet; employing the foot or feet.",
  "omoplate - The shoulder blade, or scapula.",
  "gummous - 1. Gumlike, or composed of gum; gummy. 2. (Med.)  Of or pertaining to a gumma.",
  "millwright - A mechanic whose occupation is to build mills, or to set up their machinery.",
  "athetosis - A variety of chorea, marked by peculiar tremors of the fingers and toes.",
  "conducent - Conducive; tending. Conducent to the good success of this business. Abp. Laud.",
  "picturize - 1. To picture. 2. To adorn with pictures.",
  "enubilate - To clear from mist, clouds, or obscurity. [R.] Bailey.",
  "inworn - Worn, wrought, or stamped in. [R.] Milton.",
  "compossible - Able to exist with another thing; consistent. [R.] Chillingworth.",
  "intermezzo - An interlude; an intermede. See Intermede.",
  "butane - An inflammable gaseous hydrocarbon, C4H10, of the marsh gas, or paraffin, series.",
  "hornwrack - A bryozoan of the genus Flustra.",
  "anathematization - The act of anathematizing, or denouncing as accursed; imprecation. Barrow.",
  "disdainishly - Disdainfully. [Obs.] Vives.",
  "blastoderm - The germinal membrane in an ovum, from which the embryo is developed.",
  "wickerwork - A texture of osiers, twigs, or rods; articles made of such a texture.",
  "metagraphic - By or pertaining to metagraphy.",
  "subarcuate - Having a figure resembling that of a bow; somewhat curved or arched.",
  "erythematic - Characterized by, or causing, a morbid redness of the skin; relating to erythema.",
  "capricioso - In a free, fantastic style.",
  "tinman - A manufacturer of tin vessels; a dealer in tinware.",
  "dog fancier - One who has an unusual fancy for, or interest in, dogs; also, one who deals in dogs.",
  "pridian - Of or pertaining to the day before, or yesterday. [R.] Thackeray.",
  "scirrhosity - A morbid induration, as of a gland; stste of being scirrhous.",
  "transpatronize - To transfer the patronage of. [Obs.] Warner.",
  "anacanthous - Spineless, as certain fishes.",
  "blemishless - Without blemish; spotless. A life in all so blemishless. Feltham.",
  "knowingness - The state or quality of being knowing or intelligent; shrewdness; skillfulness.",
  "acquaintedness - State of being acquainted; degree of acquaintance. [R.] Boyle.",
  "spectatrix - A female beholder or looker-on. \"A spectatress of the whole scene.\" Jeffrey.",
  "ubiquitariness - Quality or state of being ubiquitary, or ubiquitous. [R.] Fuller.",
  "lowish - Somewhat low. [Colloq.] Richardson.",
  "expurgatorial - Tending or serving to expurgate; expurgatory. Milman.",
  "inexertion - Want of exertion; want of effort; defect of action; indolence; laziness.",
  "progenitorship - The state of being a progenitor.",
  "anencephalic - Without a brain; brainless. Todd & B.",
  "renovator - One who, or that which, renovates. Foster.",
  "unacceptability - The quality of being unacceptable; unacceptableness.",
  "larghetto - Somewhat slow or slowly, but not so slowly as largo, and rather more so than andante.",
  "anomura - A group of decapod Crustacea, of which the hermit crab in an example.",
  "choric - Of or pertaining to a chorus. I remember a choric ode in the Hecuba. Coleridge.",
  "expeller - One who. or that which, expels.",
  "disgraduate - To degrade; to reduce in rank. [Obs.] Tyndale.",
  "baccara - A French game of cards, played by a banker and punters.",
  "frogged - Provided or ornamented with frogs; as, a frogged coat. See Frog, n., 4. Ld. Lytton.",
  "insufficiently - In an insufficient manner or degree; unadequately.",
  "tchawytcha - The quinnat salmon. [Local, U.S.]",
  "omohyoid - Of or pertaining to the shoulder and the hyoid bone; as, the omohyoid muscle.",
  "unmechanize - 1. To undo the mechanism of; to unmake; as, to unmechanize a structure. [Obs.] Sterne.",
  "attle - Rubbish or refuse consisting of broken rock containing little or no ore. Weale.",
  "maying - The celebrating of May Day. \"He met her once a-Maying.\" Milton.",
  "taglock - An entangled lock, as of hair or wool. Nares.",
  "deletive - Adapted to destroy or obliterate. [R.] Evelyn.",
  "zincograph - A zinc plate prepared for printing by zincography; also, a print from such a plate.",
  "sheathless - Without a sheath or case for covering; unsheathed.",
  "procreate - To generate and produce; to beget; to engender.",
  "wailful - Sorrowful; mournful. \" Like wailful widows.\" Spenser. \"Wailful sonnets.\" Shak.",
  "interdependency - Mutual dependence; as, interdependency of interests. De Quincey.",
  "daddock - The rotten body of a tree. [Prov. Eng.] Wright.",
  "forcibleness - The quality of being forcible.",
  "cornuted - 1. Bearing horns; horned; horn-shaped. 2. Cuckolded. [R.] \"My being cornuted.\" LEstrange.",
  "tenebrose - Characterized by darkness or gloom; tenebrous.",
  "bepurple - To tinge or dye with a purple color.",
  "scabrousness - The quality of being scabrous.",
  "bucranium - A sculptured ornament, representing an ox skull adorned with wreaths, etc.",
  "inapt - Unapt; not apt; unsuitable; inept. -- In*apt\"ly, adv. -- In*apt\"ness, n.",
  "platy - Like a plate; consisting of plates.",
  "appeaser - One who appeases; a pacifier.",
  "sparrowwort - An evergreen shrub of the genus Erica (E. passerina).",
  "stative - Of or pertaining to a fixed camp, or military posts or quarters. [Obs. or R.]",
  "impasture - To place in a pasture; to foster. [R.] T. Adams.",
  "aft - Near or towards the stern of a vessel; astern; abaft.",
  "sea purse - The horny egg case of a skate, and of certain sharks.",
  "crosshatch - To shade by means of crosshatching.",
  "chevet - The extreme end of the chancel or choir; properly the round or polygonal part.",
  "kind-heartedness - The state or quality of being kind-hearted; benevolence.",
  "coadunate - United at the base, as contiguous lobes of a leaf.",
  "superfineness - The state of being superfine.",
  "rightfully - According to right or justice.",
  "unconsequential - Inconsequential. Johnson.",
  "pickpocket - One who steals purses or other articles from pockets. Bentley.",
  "wrongless - Not wrong; void or free from wrong. [Obs.] -- Wrong\"less*ly, adv. [Obs.] Sir P. Sidney.",
  "insanable - Not capable of being healed; incurable; irremediable.",
  "disinteress - To deprive or rid of interest in, or regard for; to disengage. [Obs.]",
  "abjudge - To take away by judicial decision. [R.]",
  "cryptographer - One who writes in cipher, or secret characters.",
  "pneumatometer - An instrument for measuring the amount of force exerted by the lungs in respiration.",
  "subsellium - One of the stalls of the lower range where there are two ranges. See Illust. of Stall.",
  "ty-all - Something serving to tie or secure. [Obs.] Latimer.",
  "gyrostatics - The doctrine or theory of the gyrostat, or of the phenomena of rotating bodies.",
  "subpurchaser - A purchaser who buys from a purchaser; one who buys at second hand.",
  "suprascalpulary - Situated above, or on the anterior side of, the scapula.",
  "fingle-fangle - A trifle. [Low] Hudibras.",
  "acidification - The act or process of acidifying, or changing into an acid.",
  "marrubium - A genus of bitter aromatic plants, sometimes used in medicine; hoarhound.",
  "pectorally - As connected with the breast.",
  "sociableness - The quality of being sociable.",
  "obviation - The act of obviating, or the state of being obviated."
]