export default [
  "ritualist - One skilled un, or attached to, a ritual; one who advocates or practices ritualism.",
  "titan - Titanic. The Titan physical difficulties of his enterprise. I. Taylor.",
  "bleck - To blacken; also, to defile. [Obs. or Dial.] Wyclif.",
  "ichthyophthalmite - See Apophyllite. [R.]",
  "anidiomatical - Not idiomatic. [R.] Landor.",
  "soi-disant - Calling himself; self-styled; pretended; would-be.",
  "infelonious - Not felonious, malignant, or criminal. G. Eliot.",
  "declensional - Belonging to declension. Declensional and syntactical forms. M. Arnold.",
  "ectosteal - Of or pertaining to ectostosis; as, ectosteal ossification.",
  "burdenous - Burdensome. [Obs.] \"Burdenous taxations.\" Shak.",
  "blandiloquious - Fair-spoken; flattering.",
  "adoor - At the door; of the door; as, out adoors. Shak. I took him in adoors. Vicar's Virgil (1630).",
  "fulminant - Thundering; fulminating. [R.] Bailey.",
  "relativity - The state of being relative; as, the relativity of a subject. Coleridge.",
  "smore - To smother. See Smoor. [Obs.] Some dying vomit blood, and some were smored. Du Bartas.",
  "top-drain - To drain the surface of, as land; as, to top-drain a field or farm.",
  "parelcon - The addition of a syllable or particle to the end of a pronoun, verb, or adverb.",
  "gauzy - Pertaining to, or resembling, gauze; thin and slight as gauze.",
  "greenroom - The retiring room of actors and actresses in a theater.",
  "falculate - Curved and sharppointed, like a falcula, or claw of a falcon.",
  "percolator - One who, or that which, filters. \"[Tissues] act as percolators.\" Henfrey.",
  "stopship - A remora. It was fabled to stop ships by attaching itself to them. Sylvester.",
  "ornithorhynchus - See Duck mole, under Duck.",
  "cadent - Falling. [R.] \"Cadent tears.\" Shak.",
  "perivisceral - Around the viscera; as, the perivisceral cavity.",
  "polypragmatical - Overbusy; officious. [R.] Heywood.",
  "curtal friar - A friar who acted as porter at the gate of a monastery. Sir W. Scott.",
  "eternalist - One who holds the existence of matter to be from eternity. T. Burnet.",
  "mandibulated - Provided with mandibles adapted for biting, as many insects.",
  "altercative - Characterized by wrangling; scolding. [R.] Fielding.",
  "wooled - Having (such) wool; as, a fine-wooled sheep.",
  "coaxingly - In a coaxing manner; by coaxing.",
  "foreadmonish - To admonish beforehand, or before the act or event. Bp. Hall.",
  "milady - Lit., my lady; hence (as used on the Continent), an English noblewoman or gentlewoman.",
  "horselaugh - A loud, boisterous laugh; a guffaw. Pope.",
  "spicated - Having the form of a spike, or ear; arranged in a spike or spikes. Lee.",
  "lenticularly - In the manner of a lens; with a curve.",
  "agronomic - Pertaining to agronomy, of the management of farms.",
  "souther - A strong wind, gale, or storm from the south.",
  "belligerently - In a belligerent manner; hostilely.",
  "vermifuge - A medicine or substance that expels worms from animal bodies; an anthelmintic.",
  "air-slacked - Slacked, or pulverized, by exposure to the air; as, air-slacked lime.",
  "hogsty - A pen, house, or inclosure, for hogs.",
  "splenocele - Hernia formed by the spleen.",
  "disquisitive - Relating to disquisition; fond discussion or investigation; examining; inquisitive.",
  "unbefool - To deliver from the state of a fool; to awaken the mind of; to undeceive.",
  "thurification - The act of fuming with incense, or the act of burning incense.",
  "scrouge - To crowd; to squeeze. [Prov. Eng. & Colloq. U.S.]",
  "ramal - Of or pertaining to a ramus, or branch; rameal.",
  "shovel-nosed - Having a broad, flat nose; as, the shovel-nosed duck, or shoveler.",
  "praisable - Fit to be praised; praise-worthy; laudable; commendable. Wyclif (2 Tim. ii. 15).",
  "emotive - Attended by, or having the character of, emotion. H. Brooke. -- E*mo\"tive*ly, adv.",
  "piler - One who places things in a pile.",
  "cururo - A Chilian burrowing rodent of the genus Spalacopus.",
  "morigeration - Obsequiousness; obedience. [Obs.] Evelyn.",
  "visite - A light cape or short cloak of silk or lace worn by women in summer.",
  "promulgator - One who promulgates or publishes. Dr. H. More.",
  "knight-er-ratic - Pertaining to a knight-errant or to knight-errantry. [R.] Quart. Rev.",
  "phosphorus steel - A steel in which the amount of phosphorus exceeds that of carbon.",
  "self-originating - Beginning wwith, or springing from, one's self.",
  "excurse - To journey or pass thought. [R.]",
  "disgradation - Degradation; a stripping of titles and honors.",
  "chinche - Parsimonious; niggardly. [Obs.] Chaucer.",
  "oxidability - Capability of being converted into an oxide.",
  "splaymouthed - Having a splaymouth. T. Brown.",
  "asymmetrous - Asymmetrical. [Obs.] Barrow.",
  "gye - To guide; to govern. [Obs.] Discreet enough his country for to gye. Chaucer.",
  "banat - The territory governed by a ban.",
  "subsign - To sign beneath; to subscribe. [R.] Camden.",
  "volow - To baptize; -- used in contempt by the Reformers. [Obs.] Tyndale.",
  "dibs - A sweet preparation or treacle of grape juice, much used in the East. Johnston.",
  "cartist - In Spain and Portugal, one who supports the constitution.",
  "mucousness - The quality or state of being mucous; sliminess.",
  "scleroma - Induration of the tissues. See Sclerma, Scleroderma, and Sclerosis.",
  "cushewbird - The galeated curassow. See Curassow.",
  "hesternal - Pertaining to yesterday. [Obs.] See Yester, a. Ld. Lytton.",
  "shooi - The Richardson's skua (Stercorarius parasiticus);- so called from its cry. [Prov. Eng.]",
  "deciare - A measure of area, the tenth part of an are; ten square meters.",
  "hypoblastic - Relating to, or connected with, the hypoblast; as, the hypoic sac.",
  "remigrate - To migrate again; to go back; to return. Boyle.",
  "coarse-grained - Having a coarse grain or texture, as wood; hence, wanting in refinement.",
  "warpage - The act of warping; also, a charge per ton made on shipping in some harbors.",
  "clarence - A close four-wheeled carriage, with one seat inside, and a seat for the driver.",
  "cecutiency - Partial blindness, or a tendency to blindness. [R.] Sir T. Browne.",
  "inventful - Full of invention. J. Gifford.",
  "succorable - Capable of being succored or assisted; admitting of relief.",
  "subserviently - In a subservient manner.",
  "midrib - A continuation of the petiole, extending from the base to the apex of the lamina of a leaf.",
  "drawhead - The flanged outer end of a drawbar; also, a name applied to the drawgear.",
  "disbind - To unbind; to loosen. [Obs.] Mede.",
  "rhynchocoela - Same as Nemertina. -- Rhyn`cho*coe\"lous, a.",
  "constablery - 1. The constabulary. [Obs.] 2. The distrit or jurisdiction of a constable. [Obs.]",
  "urbanize - To render urban, or urbane; to refine; to polish. Howell.",
  "toyer - One who toys; one who is full of trifling tricks; a trifler.",
  "crotched - 1. Having a crotch; forked. 2. Cross; peevish. [Prov. Eng.] Halliwell.",
  "factotum - A person employed to do all kinds of work or business. B. Jonson.",
  "reamputation - The second of two amputations performed upon the same member.",
  "alchymic - See Alchemic, Alchemist, Alchemistic, Alchemy.",
  "impaint - To paint; to adorn with colors. [R.] \"To impaint his cause.\" Shak.",
  "outbuilding - A building separate from, and subordinate to, the main house; an outhouse.",
  "inlayer - One who inlays, or whose occupation it is to inlay.",
  "neoterism - An innovation or novelty; a neoteric word or phrase.",
  "hybernate - See Hibernacle, Hibernate, Hibernation.",
  "loutou - A crested black monkey (Semnopithecus maurus) of Java.",
  "oryctological - Of or pertaining to oryctology. [Obs.]",
  "courageousness - The quality of being courageous; courage.",
  "deontological - Pertaining to deontology.",
  "deplantation - Act of taking up plants from beds.",
  "plumpness - The quality or state of being plump.",
  "re sign - Resignation. [Obs.] Beau & Fl.",
  "eventilation - The act of eventilating; discussion. [Obs.] Bp. Berkely.",
  "alegar - Sour ale; vinegar made of ale. Cecil.",
  "coadunition - Coadunation. [R.] Sir M. Hale.",
  "onomantical - Of or pertaining to onomancy. [R.]",
  "friation - The act of breaking up or pulverizing.",
  "nomography - A treatise on laws; an exposition of the form proper for laws.",
  "chronometric - Pertaining to a chronometer; measured by a chronometer.",
  "elritch - Ghastly; preternatural. Same as Eldritch. [Scot. & Local, Eng.]",
  "slatterpouch - A dance or game played by boys, requiring active exercise. [Obs.] Gayton.",
  "whaleman - A man employed in the whale fishery.",
  "noctule - A large European bat (Vespertilio, or Noctulina, altivolans).",
  "parenthetically - In a parenthetical manner; by way of parenthesis; by parentheses.",
  "catechuic - Of or pertaining to catechu or its derivatives. See catechin.",
  "nesh - Soft; tender; delicate. [Obs. or Prov. Eng.]",
  "niggardship - Niggardliness. [Obs.] Sir T. Elyot.",
  "down-share - A breastplow used in paring off turf on downs. [Eng.] Knight.",
  "cappeak - The front piece of a cap; -- now more commonly called visor.",
  "perchant - A bird tied by the foot, to serve as decoy to other birds by its fluttering.",
  "tedge - The gate of a mold, through which the melted metal is poured; runner, geat.",
  "pyroueric - Pertaining to, or designating, an acid now called cyanuric acid. See Cyanuric.",
  "endospermic - Relating to, accompanied by, or containing, endosperm.",
  "clerk-ale - A feast for the benefit of the parish clerk. [Eng.] T. Warton.",
  "acology - Materia medica; the science of remedies.",
  "simoniac - One who practices simony, or who buys or sells preferment in the church. Ayliffe.",
  "reassemblage - Assemblage a second time or again.",
  "moro - A small abscess or tumor having a resemblance to a mulberry. Dunglison.",
  "indecisiveness - The state of being indecisive; unsettled state.",
  "haught - High; elevated; hence, haughty; proud. [Obs.] Shak.",
  "pyroxenic - Containing pyroxene; composed chiefly of pyroxene.",
  "teapoy - An ornamental stand, usually with three legs, having caddies for holding tea.",
  "outfling - A gibe; a contemptuous remark.",
  "misrehearse - To rehearse or quote incorrectly. Sir T. More.",
  "equitably - In an equitable manner; justly; as, the laws should be equitably administered.",
  "familistical - Pertaining to Familists. Baxter.",
  "sodic - Of or pertaining to sodium; containing sodium.",
  "oversum - A sum or quantity over; surplus. [Obs.] Holinshed.",
  "idolastre - An idolater. [Obs.] Chaucer.",
  "mumbling - Low; indistinct; inarticulate. -- Mum\"bling*ly, adv.",
  "glyphograph - A plate made by glyphography, or an impression taken from such a plate.",
  "bacciferous - Producing berries. \" Bacciferous trees.\" Ray.",
  "seignioralty - The territory or authority of a seignior, or lord. Milman.",
  "thermophilic - Heat-loving; -- applied esp. to certain bacteria.",
  "presumptively - By presumption, or supposition grounded or probability; presumably.",
  "retentiveness - The quality of being retentive.",
  "ill-lived - Leading a wicked life. [Obs.]",
  "vivary - A vivarium. \"That . . . vivary of fowls and beasts.\" Donne.",
  "preternaturalness - The quality or state of being preternatural.",
  "notchweed - A foul-smelling weed, the stinking goosefoot (Chenopodium Vulvaria).",
  "snipper-snaper - A small, insignificant fellow. [Colloq.]",
  "adductive - Adducing, or bringing towards or to something.",
  "danaite - A cobaltiferous variety of arsenopyrite.",
  "hereafterward - Hereafter. [Obs.] Thou shalt hereafterward . . . come. Chaucer.",
  "deflectionization - The act of freeing from inflections. Earle.",
  "hardily - 1. Same as Hardly. [Obs.] Chaucer. 2. Boldly; stoutly; resolutely. Wyclif.",
  "anticausotic - Good against an inflammatory fever. -- n.  A remedy for such a fever.",
  "metopic - Of or pertaining to the forehead or frontal bones; frontal; as, the metopic suture.",
  "blocage - The roughest and cheapest sort of rubblework, in masonry.",
  "occipitoaxial - Of or pertaining to the occipital bone and second vertebra, or axis.",
  "avid - Longing eagerly for; eager; greedy. \"Avid of gold, yet greedier of renown.\" Southey.",
  "bondwoman - A woman who is a slave, or in bondage. He who was of the bondwoman. Gal. iv. 23.",
  "sternebra - One of the segments of the sternum. -- Ster\"ne*bral, a.",
  "metasternal - Of or pertaining to the metasternum.",
  "antiparalytic - Good against paralysis. -- n.  A medicine for paralysis.",
  "rompish - Given to rude play; inclined to romp. --- Romp\"ish, adv. -- Romp\"ish*ness, n.",
  "harder - A South African mullet, salted for food.",
  "myology - That part of anatomy which treats of muscles.",
  "perradial - Situated around the radii, or radial tubes, of a radiate.",
  "defibrination - The act or process of depriving of fibrin.",
  "manstealing - The act or business of stealing or kidnaping human beings, especially with a view to e",
  "dustless - Without dust; as a dustless path.",
  "gastronomical - Pertaining to gastromony.",
  "lutation - The act or method of luting vessels.",
  "henhouse - A house or shelter for fowls.",
  "pseudo-metallic - Falsely or imperfectly metallic; -- said of a kind of luster, as in minerals.",
  "toilful - Producing or involving much toil; laborious; toilsome; as, toilful care. Mickle.",
  "professorial - Of or pertaining to a professor; as, the professional chair; professional interest.",
  "utterness - The quality or state of being utter, or extreme; extremity; utmost; uttermost. [R.]",
  "preoral - Situated in front of, or anterior to, the mouth; as, preoral bands.",
  "mesenchyma - The part of the mesoblast which gives rise to the connective tissues and blood.",
  "classicist - One learned in the classics; an advocate for the classics.",
  "discerpible - Capable of being discerped. [R.]",
  "authentically - In an authentic manner; with the requisite or genuine authority.",
  "weeviled - Infested by weevils; as, weeviled grain. [Written also weevilled.]",
  "izard - A variety of the chamois found in the Pyrenees.",
  "metalliform - Having the form or structure of a metal.",
  "hunchback - A back with a hunch or hump; also, a hunchbacked person.",
  "florification - The act, process, or time of flowering; florescence.",
  "adipoceriform - Having the form or appearance of adipocere; as, an adipoceriform tumor.",
  "fidejussor - A surety; one bound for another, conjointly with him; a guarantor. Blackstone.",
  "labiose - Having the appearance of being labiate; -- said of certain polypetalous corollas.",
  "haaf - The deepsea fishing for cod, ling, and tusk, off the Shetland Isles.",
  "facework - The material of the outside or front side, as of a wall or building; facing.",
  "piscivorous - Feeding or subsisting on fish.",
  "sepaloid - Like a sepal, or a division of a calyx.",
  "deduit - Delight; pleasure. [Obs.] Chaucer.",
  "gastrotomy - A cutting into, or opening of, the abdomen or the stomach.",
  "sleaved - Raw; not spun or wrought; as, sleaved thread or silk. Holinshed.",
  "blissless - Destitute of bliss. Sir P. Sidney.",
  "osteocomma - A metamere of the vertebrate skeleton; an osteomere; a vertebra. Owen.",
  "unisonant - Being in unison; having the same degree of gravity or acuteness; sounded alike in pitch.",
  "barratrous - Tainter with, or constituting, barratry. -- Bar\"ra*trous*ly, adv. Kent.",
  "intercessional - Pertaining to, of the nature of, or characterized by, intercession or entreaty.",
  "disembellish - To deprive of embellishment; to disadorn. Carlyle.",
  "lapboard - A board used on the lap as a substitute for a table, as by tailors.",
  "parapleura - A chitinous piece between the metasternum and the pleuron of certain insects.",
  "potboy - A boy who carries pots of ale, beer, etc.; a menial in a public house.",
  "insiccation - The act or process of drying in.",
  "quoter - One who quotes the words of another.",
  "casualness - The quality of being casual.",
  "bipinnaria - The larva of certain starfishes as developed in the free- swimming stage.",
  "episperm - The skin or coat of a seed, especially the outer coat. See Testa.",
  "aflame - Inflames; glowing with light or passion; ablaze. G. Eliot.",
  "seamless - Without a seam. Christ's seamless coat, all of a piece. Jer. Taylor.",
  "wall-plat - The spotted flycatcher. It builds its nest on walls. [Prov. Eng.]",
  "aphonia - Loss of voice or vocal utterance.",
  "prease - To press; to crowd. [Obs.] -- n.  A press; a crowd. [Obs.] Spenser.",
  "planoblast - Any free-swimming gonophore of a hydroid; a hydroid medusa.",
  "wringstaff - A strong piece of plank used in applying wringbolts.",
  "exquire - To search into or out. [Obs.] Chapman.",
  "reverter - 1. One who, or that which, reverts. 2. (Law) Reversion. Burrill.",
  "letterure - Letters; literature. [Obs.] \"To teach him letterure and courtesy.\" Chaucer.",
  "tamias - A genus of ground squirrels, including the chipmunk.",
  "stayedness - 1. Staidness. [Archaic] W. Whately. 2. Solidity; weight. [R.] Camden.",
  "coachfellow - One of a pair of horses employed to draw a coach; hence (Fig.), a comrade. Shak.",
  "staminodium - An abortive stamen, or any organ modified from an abortive stamen.",
  "anglomaniac - One affected with Anglomania.",
  "inne - In. [Obs.] And eke in what array that they were inne. Chaucer.",
  "con- - - (cum, signifying with, together, etc. See Com-.",
  "corer - That which cores; an instrument for coring fruit; as, an apple corer.",
  "profection - A setting out; a going forward; advance; progression. [Obs.] Sir T. Browne.",
  "nobilitation - The act of making noble. [Obs.] Dr. H. More.",
  "bedewer - One who, or that which, bedews.",
  "prodigence - Waste; profusion; prodigality. [R.] Bp. Hall.",
  "heptahedron - A solid figure with seven sides.",
  "outrive - To river; to sever. [Obs.] Fairfax.",
  "squabbler - One who squabbles; a contentious person; a brawler.",
  "monecious - See Monoecian, and Monoecious.",
  "band fish - A small red fish of the genus Cepola; the ribbon fish.",
  "explicitness - The quality of being explicit; clearness; directness. Jer. Taylor.",
  "appendicitis - Inflammation of the vermiform appendix.",
  "urticate - To sting with, or as with, nettles; to irritate; to annoy. G. A. Sala.",
  "vendition - The act of vending, or selling; sale.",
  "victimate - To make a victim of; to sacrifice; to immolate. [Obs.] Bullokar.",
  "sprenge - To sprinkle; to scatter. [Obs.] Wyclif (1 Pet. i. 2).",
  "excorticate - To strip of bark or skin; to decorticate. [Obs.] \"Excorticate the tree.\" Evelyn.",
  "apothegmatic - Pertaining to, or in the manner of, an apotghem; sententious; pithy.",
  "tantrism - The system of doctrines and  rites taught in the tantras. -- Tan\"trist (#), n.",
  "idoloclast - A breaker of idols; an iconoclast.",
  "muck rake - A rake for scraping up muck or dung. See Muckrake, v. i., below.",
  "sallyman - The velella; -- called also saleeman.",
  "iconical - Pertaining to, or consisting of, images, pictures, or representations of any kind.",
  "davidic - Of or pertaining to David, the king and psalmist of Israel, or to his family.",
  "guerdonless - Without reward or guerdon.",
  "malacology - The science which relates to the structure and habits of mollusks.",
  "tienda - In Cuba, Mexico, etc., a booth, stall, or shop where merchandise is sold.",
  "unpeace - Absence or lack of peace. [Obs.] Testament of Love.",
  "cacuminate - To make sharp or pointed. [Obs.]",
  "culpon - A shered; a fragment; a strip of wood. [Obs.] Chaucer.",
  "corollated - Having a corolla or corollas; like a corolla.",
  "glabrate - Becoming smooth or glabrous from age. Gray.",
  "maguey - The century plant, a species of Agave (A. Americana). See Agave.",
  "self-deceit - The act of deceiving one's self, or the state of being self- deceived; self-deception.",
  "enterocele - A hernial tumor whose contents are intestine.",
  "inflexibleness - The quality or state of being inflexible; inflexibility; rigidity; firmness.",
  "doable - Capable of being done. Carlyle.",
  "phrenologist - One versed in phrenology; a craniologist.",
  "doughy - Like dough; soft and heavy; pasty; crude; flabby and pale; as, a doughy complexion.",
  "outstreet - A street remote from the center of a town. Johnson.",
  "cepevorous - Feeding upon onions. [R.] Sterling.",
  "threnetical - Pertaining to a threne; sorrowful; mournful.",
  "asphyxiation - The act of causing asphyxia; a state of asphyxia.",
  "polianite - Manganese dioxide, occurring in tetragonal crystals nearly as hard as quartz.",
  "wizen-faced - Having a shriveled, thin, withered face.",
  "diselenide - A selenide containing two atoms of selenium in each molecule.",
  "rhinotheca - The sheath of the upper mandible of a bird.",
  "leverwood - The American hop hornbeam (Ostrya Virginica), a small tree with very tough wood.",
  "veniable - Venial; pardonable. [Obs.] Sir T. Browne. -- Ve\"ni*a*bly, adv. [Obs.] Sir T. Browne.",
  "femalist - A gallant. [Obs.] Courting her smoothly like a femalist. Marston.",
  "basion - The middle of the anterior margin of the great foramen of the skull.",
  "codical - Ralating to a codex, or a code.",
  "prescious - Foreknowing; having foreknowledge; as, prescious of ills. [R.] Dryden.",
  "solanoid - Resembling a potato; -- said of a kind of cancer.",
  "low-necked - Cut low in the neck; decollete; -- said of a woman's dress.",
  "bartholomew tide - Time of the festival of St. Bartholomew, August 24th. Shak.",
  "grammatication - A principle of grammar; a grammatical rule. [Obs.] Dalgarno.",
  "simplician - One who is simple. [Obs.] Arnway.",
  "farness - The state of being far off; distance; remoteness. [R.] Grew.",
  "likeliness - 1. Likelihood; probability. 2. Suitableness; agreeableness. [Obs.]",
  "tarsel - A male hawk. See Tercel. [Obs.]",
  "collaret - A small collar; specif., a woman's collar of lace, fur, or other fancy material.",
  "hydrocephalous - Having hydrocephalus. \"Hydrocephalous offspring.\" G. Eliot.",
  "suspicable - Liable to suspicion; suspicious. [Obs.] It is a very suspicable business. Dr. H. more.",
  "schoolgirl - A girl belonging to, or attending, a school.",
  "attemperance - Temperance; attemperament. [Obs.] Chaucer.",
  "clarigate - To declare war with certain ceremonies. [Obs.] Holland.",
  "gorgelet - A small gorget, as of a humming bird.",
  "eventide - The time of evening; evening. [Poetic.] Spenser.",
  "knopped - Having knops or knobs; fastened as with buttons. [Obs.] Rom. of R.",
  "stibialism - Antimonial intoxication or poisoning. Dunglison.",
  "daedalous - Having a variously cut or incised margin; -- said of leaves.",
  "formate - A salt of formic acid. [Written also formiate.]",
  "fissiparous - Reproducing by spontaneous fission. See Fission. -- Fis*sip\"a*rous*ly, adv.",
  "artlessness - The quality of being artless, or void of art or guile; simplicity; sincerity.",
  "hydrolysis - A chemical process involving the addition of the elements of water.",
  "tynd - To shut; to close. [Obs.] Wyclif.",
  "schoolboy - A boy belonging to, or attending, a school.",
  "diurnalness - The quality of being diurnal.",
  "interne - That which is within; the interior. [Poetic] Mrs. Browning.",
  "discordable - That may produce discord; disagreeing; discordant. [R.] Halliwell.",
  "antipyic - Checking or preventing suppuration. -- n.  An antipyic medicine.",
  "berthage - A place for mooring vessels in a dock or harbor.",
  "intermigration - Reciprocal migration; interchange of dwelling place by migration. [R.] Sir M. Hale.",
  "textually - In a textual manner; in the text or body of a work; in accordance with the text.",
  "marquise - The wife of a marquis; a marchioness.",
  "proception - Preoccupation. [Obs.] Eikon Basilik",
  "pinniped - (a) One of the Pinnipedia; a seal. (b) One of the Pinnipedes.",
  "byplay - Action carried on aside, and commonly in dumb show, while the main action proceeds.",
  "direness - Terribleness; horror; woefulness. Shak.",
  "anointment - The act of anointing, or state of being anointed; also, an ointment. Milton.",
  "floutingly - With flouting; insultingly; as, to treat a lover floutingly.",
  "disprovide - Not to provide; to fail to provide. [Obs.] Boyle.",
  "viceman - A smith who works at the vice instead of at the anvil.",
  "towpath - A path traveled by men or animals in towing boats; -- called also towing path.",
  "colliquative - Causing rapid waste or exhaustion; melting; as, collequative sweats.",
  "multipartite - Divided into many parts; having several parts.",
  "out-patient - A patient who is outside a hospital, but receives medical aid from it.",
  "commendatary - One who holds a living in commendam.",
  "refashionment - The act of refashioning, or the state of being refashioned. [R.] Leigh Hunt.",
  "incruental - Unbloody; not attended with blood; as, an incruental sacrifice. [Obs.] Brevint.",
  "fickleness - The quality of being fickle; instability; inconsonancy. Shak.",
  "rock staff - An oscillating bar in a machine, as the lever of the bellows of a forge.",
  "foothold - A holding with the feet; firm L'Estrange.",
  "honvedseg - See Army organization, above.",
  "razed - Slashed or striped in patterns. [Obs.] \"Two Provincial roses on my razed shoes.\" Shak.",
  "saponifier - That which saponifies; any reagent used to cause saponification.",
  "pronouncer - One who pronounces, utters, or declares; also, a pronouncing book.",
  "repleteness - The state of being replete.",
  "exorbitantly - In an exorbitant, excessive, or irregular manner; enormously.",
  "enthronement - The act of enthroning, or state of being enthroned. [Recent]",
  "trachytic - Of, pertaining to, or resembling, trachyte.",
  "landlordry - The state of a landlord. [Obs.]",
  "hydrological - Of or pertaining to hydrology.",
  "manciple - A steward; a purveyor, particularly of a college or Inn of Court. Chaucer.",
  "architector - An architect. [Obs.] North.",
  "archaical - Archaic. [R.] -- Ar*cha\"ic*al*ly, adv.",
  "bottle green - A dark shade of green, like that of bottle glass. -- Bot\"tle-green`, a.",
  "mycologic - Of or relating to mycology, or the fungi.",
  "commorse - Remorse. [Obs.] \"With sad commorse.\" Daniel.",
  "nyctophile - Any Australian bat of the genus Nyctophilus, having a very simple nasal appendage.",
  "blitheful - Gay; full of gayety; joyous.",
  "take-off - An imitation, especially in the way of caricature.",
  "threadbareness - The state of being threadbare.",
  "bequethen - old p. p. of Bequeath. [Obs.] Chaucer.",
  "blacklead - To coat or to polish with black lead.",
  "empuzzle - To puzzle. [Archaic] Sir T. Browne.",
  "crucifier - One who crucifies; one who subjects himself or another to a painful trial.",
  "baldpated - Destitute of hair on the head; baldheaded. Shak.",
  "pileous - Consisting of, or covered with, hair; hairy; pilose.",
  "gainstrive - To strive or struggle against; to withstand. [Obs.] Spenser.",
  "vaultage - Vaulted work; also, a vaulted place; an arched cellar. [Obs.] Shak.",
  "rad - imp. & p. p. of Read, Rede. Spenser.",
  "discriminately - In a discriminating manner; distinctly.",
  "bon vivant - A good fellow; a jovial companion; a free liver.",
  "cultrate - Sharp-edged and pointed; shaped like a pruning knife, as the beak of certain birds.",
  "miscegenation - A mixing of races; amalgamation, as by intermarriage of black and white.",
  "endometritis - Inflammation of the endometrium.",
  "complexionally - Constitutionally. [R.] Though corruptible, not complexionally vicious. Burke.",
  "electro-stereotype - Same as Electrotype.",
  "venatic - Of or pertaining to hunting; used in hunting. [R.] \" Venatical pleasure.\" Howell.",
  "contagiousness - Quality of being contagious.",
  "improvisator - An improviser, or improvvisatore.",
  "buccinator - A muscle of the cheek; -- so called from its use in blowing wind instruments.",
  "honorless - Destitute of honor; not honored. Bp. Warburton.",
  "windlace - See Windlass. [Obs.] Two arblasts, . . . with windlaces and quarrels. Sir W. Scott.",
  "orthoscope - An instrument designed to show the condition of the superficial portions of the eye.",
  "torridness - The quality or state of being torrid or parched.",
  "salamandrina - A suborder of Urodela, comprising salamanders.",
  "minimize - To reduce to the smallest part or proportion possible; to reduce to a minimum. Bentham.",
  "uncustomed - Uncustomable; also, not having paid duty or customs. Smollett.",
  "divinatory - Professing, or relating to, divination. \"A natural divinatory instinct.\" Cowley.",
  "imber-goose - The loon. See Ember-goose.",
  "cumbent - Lying down; recumbent. J. Dyer.",
  "findfault - A censurer or caviler. [Obs.]",
  "repiningly - With repening or murmuring.",
  "jessant - Springing up or emerging; -- said of a plant or animal.",
  "unossified - Destitute of a bony structure.",
  "epicureanism - Attachment to the doctrines of Epicurus; the principles or belief of Epicurus.",
  "entermewer - A hawk gradually changing the color of its feathers, commonly in the second year.",
  "stelene - Resembling, or used as, a stela; columnar. [R.]",
  "ministryship - The office of a minister. Swift.",
  "thermograph - An instrument for automatically recording indications of the variation of temperature.",
  "consultatory - Formed by, or resulting from, consultation; advisory. Bancroft.",
  "freeholder - The possessor of a freehold.",
  "tribunary - Of or pertaining to tribunes; as, tribunary powers or authority.",
  "birdcatching - The art, act, or occupation or catching birds or wild fowls.",
  "wappet - A small yelping cur. [Prov. Eng.]",
  "rosery - A place where roses are cultivated; a nursery of roses. See Rosary, 1.",
  "ingenerable - Incapble of being engendered or produced; original. Holland.",
  "torsk - (a) The cusk. See Cusk. (b) The codfish. Called also tusk.",
  "periergy - 1. Excessive care or diligence. [Obs.] 2. (Rhet.)  A bombastic or labored style. [R.]",
  "internity - State of being within; interiority. [R.] H. Brooke.",
  "rampallian - A mean wretch. [Obs.] Shak.",
  "sea green - The green color of sea water.",
  "underkeeper - A subordinate keeper or guardian. Gray.",
  "falcongentil - The female or young of the goshawk (Astur palumbarius).",
  "headstall - That part of a bridle or halter which encompasses the head. Shak.",
  "blowze - A ruddy, fat-faced woman; a wench. [Obs.] Shak.",
  "tychonic - Of or pertaining to Tycho Brahe, or his system of astronomy.",
  "lathereeve - Formerly, the head officer of a lathe. See 1st Lathe.",
  "indevirginate - Not devirginate. [Obs.] Chapman.",
  "graphitoid - Resembling graphite or plumbago.",
  "flagitation - Importunity; urgent demand. [Archaic] Carlyle.",
  "unnear - Not near; not close to; at a distance from. [Obs.] Davies (Muse's Sacrifice).",
  "fisc - A public or state treasury. Burke.",
  "loculous - Divided by internal partitions into cells, as the pith of the pokeweed.",
  "geologist - One versed in the science of geology.",
  "prejudgment - The act of prejudging; decision before sufficient examination.",
  "sinecural - Of or pertaining to a sinecure; being in the nature of a sinecure.",
  "exultancy - Exultation. [Obs.] Burton. Hammond.",
  "cojoin - To join; to conjoin. [R.] Shak.",
  "disacknowledge - To refuse to acknowledge; to deny; to disown. [Obs.] South.",
  "appraisable - Capable of being appraised.",
  "viviparousness - The quality of being viviparous; viviparity.",
  "confiscable - Capable of being confiscated; liable to forfeiture.",
  "bicrenate - Twice crenated, as in the case of leaves whose crenatures are themselves crenate.",
  "earthdrake - A mythical monster of the early Anglo-Saxon literature; a dragon. W. Spalding.",
  "tumulosity - The quality or state of being tumulous; hilliness. [R.] Bailey.",
  "agronomy - The management of land; rural economy; agriculture.",
  "orthographer - One versed in orthography; one who spells words correctly.",
  "vermination - 1. The generation or breeding of vermin. Derham. 2. A griping of the bowels.",
  "calorification - Production of heat, esp. animal heat.",
  "inition - Initiation; beginning. [Obs.] Sir R. Naunton.",
  "unringed - Not having a ring, as in the nose. \"Pigs unringed.\" Hudibras.",
  "diriment - Absolute. Diriment impediment (R. C. Ch.), an impediment that nullifies marriage.",
  "crepusculine - Crepuscular. [Obs.] Sprat.",
  "bolstered - 1. Supported; upheld. 2. Swelled out.",
  "celidography - A description of apparent spots on the disk of the sun, or on planets.",
  "morosoph - A philosophical or learned fool. [Obs.]",
  "platten - To flatten and make into sheets or plates; as, to platten cylinder glass.",
  "undergraduateship - The position or condition of an undergraduate.",
  "foreholding - Ominous foreboding; superstitious prognostication. [Obs.] L'Estrange.",
  "galvanometric - Of, pertaining to, or measured by, a galvanometer.",
  "forwaste - To desolate or lay waste utterly. [Obs.] Spenser.",
  "cothurnate - 1. Wearing a cothurn. 2. Relating to tragedy; solemn; grave.",
  "paleous - Chaffy; like chaff; paleaceous. [R.] Sir T. Browne.",
  "wileful - Full of wiles; trickish; deceitful.",
  "rhynchota - Same as Hemiptera. [Written also Rhyncota.]",
  "epenthetic - Inserted in the body of a word; as, an epenthetic letter or sound.",
  "demisability - The state of being demisable.",
  "untimeously - Untimely; unseasonably. [R.]",
  "chylifactive - Producing, or converting into, chyle; having the power to form chyle.",
  "craniofacial - Of or pertaining to the cranium and face; as, the craniofacial angle.",
  "attired - Provided with antlers, as a stag.",
  "unhasp - To unloose the hasp of; to unclose.",
  "malbrouck - A West African arboreal monkey (Cercopithecus cynosurus).",
  "geophila - The division of Mollusca which includes the land snails and slugs.",
  "bierbalk - A church road (e. g., a path across fields) for funerals. [Obs.] Homilies.",
  "artificialness - The quality of being artificial.",
  "infuser - One who, or that which, infuses.",
  "crusading - Of or pertaining to a crusade; as, a crusading spirit.",
  "prediastolic - Preceding the diastole of the heart; as, a prediastolic friction sound.",
  "disdiapason - An interval of two octaves, or a fifteenth; -- called also bisdiapason.",
  "propulse - To repel; to drive off or away. [Obs.] Cotgrave.",
  "engraftment - The act of ingrafting; ingraftment. [R.]",
  "bemaul - To maul or beat severely; to bruise. \"In order to bemaul Yorick.\" Sterne.",
  "pustulant - Producing pustules. -- n.  A medicine that produces pustules, as croton oil.",
  "enfeloned - Rendered fierce or frantic. [Obs.] \"Like one enfeloned or distraught.\" Spenser.",
  "homoplasty - The formation of homologous tissues.",
  "rightless - Destitute of right. Sylvester.",
  "subdepartment - A subordinate department; a bureau. See the Note under Bureau.",
  "designless - Without design. [Obs.] -- De*sign\"less*ly, adv. [Obs.]",
  "herborization - 1. The act of herborizing. 2. The figure of plants in minerals or fossils.",
  "burying place - The ground or place for burying the dead; burial place.",
  "pedomancy - Divination by examining the soles of the feet.",
  "lyterian - Termination a disease; indicating the end of a disease.",
  "disproportionality - The state of being disproportional. Dr. H. More.",
  "starkness - The quality or state of being stark.",
  "calcareo-siliceous - Consisting of, or containing calcareous and siliceous earths.",
  "seamanlike - Having or showing the skill of a practical seaman.",
  "refractoriness - The quality or condition of being refractory.",
  "ventricular - Of or pertaining to a ventricle; bellied.",
  "mullingong - See Duck mole, under Duck. [Written also mollingong.]",
  "unifromness - The quality or state of being uniform; uniformity.",
  "linkboy - A boy or man that carried a link or torch to light passengers.",
  "air pipe - A pipe for the passage of air; esp. a ventilating pipe.",
  "gentlemanliness - The state of being gentlemanly; gentlemanly conduct or manners.",
  "jointless - Without a joint; rigid; stiff.",
  "contrarily - (adv. In a contrary manner; in opposition; on the other side; in opposite ways.",
  "stalker - 1. One who stalks. 2. A kind of fishing net.",
  "tradeful - Full of trade; busy in traffic; commercial. Spenser.",
  "ambidextrously - In an ambidextrous manner; cunningly.",
  "antepenultimate - Of or pertaining to the last syllable but two. -- n.  The antepenult.",
  "avolation - The act of flying; flight; evaporation. [Obs.]",
  "sextain - A stanza of six lines; a sestine.",
  "cultirostres - A tribe of wading birds including the stork, heron, crane, etc.",
  "monogenous - Of or pertaining to monogenesis; as, monogenous, or asexual, reproduction.",
  "pencillate - Shaped like a pencil; penicillate.",
  "lector - A reader of lections; formerly, a person designated to read lessons to the illiterate.",
  "benignancy - Benignant quality; kindliness.",
  "ornithichnite - The footmark of a bird occurring in strata of stone. Hitchcock.",
  "mucosity - The quality or state of being mucous or slimy; mucousness.",
  "microtomic - Of or pert. to the microtome or microtomy; cutting thin slices.",
  "housemate - One who dwells in the same house with another. R. Browning.",
  "farantly - Orderly; comely; respectable. [Obs.] Halliwell.",
  "duodecimfid - Divided into twelve parts.",
  "evenfall - Beginning of evening. \"At the quiet evenfall.\" Tennyson.",
  "cremationist - One who advocates the practice of cremation.",
  "montanic - Of or pertaining to mountains; consisting of mountains.",
  "punster - One who puns, or is skilled in, or given to, punning; a quibbler; a low wit.",
  "disobediently - In a disobedient manner.",
  "hottentotism - A term employed to describe one of the varieties of stammering. Tylor.",
  "retroact - To act backward, or in return; to act in opposition; to be retrospective.",
  "myopathic - Of or pertaining to myopathia.",
  "draggle-tailed - Untidy; sluttish; slatternly. W. Irving.",
  "contractible - Capable of contraction. Small air bladders distable and contractible. Arbuthnot.",
  "uttermore - Further; outer; utter. [Obs. & R.] Holland.",
  "heteropod - One of the Heteropoda. -- a.  Heteropodous.",
  "hummum - A sweating bath or place for sweating. Sir T. Herbert.",
  "shogunate - The office or dignity of a Shogun. [Written also Siogoonate.]",
  "albyn - Scotland; esp. the Highlands of Scotland. T. Cambell.",
  "sarcosis - (a) Abnormal formation of flesh. (b) Sarcoma.",
  "bannered - Decorated with a banner or banners \"bannered host.\" Milton.",
  "outbreaking - 1. The act of breaking out. 2. That which bursts forth.",
  "zarathustric - Of or pertaining to Zarathustra, or Zoroaster; Zoroastrian. Tylor.",
  "allowedly - By allowance; admittedly. Shenstone.",
  "monotheist - One who believes that there is but one God.",
  "swarded - Covered with sward. Mrs. Browning.",
  "decurt - To cut short; to curtail. [Obs.] Bale.",
  "playgoing - Frequenting playhouses; as, the playgoing public. -- n.  The practice of going to plays.",
  "blastide - A small, clear space in the segments of the ovum, the precursor of the nucleus.",
  "requester - One who requests; a petitioner.",
  "bowstringed - 1. Furnished with bowstring. 2. Put to death with a bowstring; strangled.",
  "pharaonic - Of or pertaining to the Pharaohs, or kings of ancient Egypt.",
  "scrimer - A fencing master. [Obs.] Shak.",
  "organophyly - The tribal history of organs, -- a branch of morphophyly. Haeckel.",
  "tonguefish - A flounder (Symphurus plagiusa) native of the southern coast of the United States.",
  "viridescence - Quality or state of being viridescent.",
  "semitransept - The half of a transept; as, the north semitransept of a church.",
  "proemial - Introductory; prefatory; preliminary. [R.] Hammond.",
  "glycogenesis - The production or formation of sugar from gycogen, as in the liver.",
  "peremptoriness - The quality of being peremptory; positiveness.",
  "repaster - One who takes a repast. [Obs.]",
  "subterrany - Subterranean. [Obs.] Bacon. -- n.  A subterranean place. [Obs.]",
  "attendment - An attendant circumstance. [Obs.] The uncomfortable attendments of hell. Sir T. Browne.",
  "limature - 1. The act of filing. 2. That which is filed off; filings. Johnson.",
  "disutilize - To deprive of utility; to render useless. [R.] Mrs. Browning.",
  "ulcerative - Of or pertaining to ulcers; as, an ulcerative process.",
  "plumpy - Plump; fat; sleek. \"Plumpy Bacchus.\" Shak.",
  "dansker - A Dane. [Obs.] Inquire me first what Danskers are in Paris. Shak.",
  "manu - One of a series of progenitors of human beings, and authors of human wisdom.",
  "kingliness - The state or quality of being kingly.",
  "spicosity - The state of having, or being full of, ears like corn. [R.] Bailey.",
  "subcrystalline - Imperfectly crystallized.",
  "erythrodextrin - A dextrin which gives a red color with iodine. See Dextrin.",
  "aspiring - That aspires; as, an Aspiring mind. -- As*pir\"ing*ly, adv. -- As*pir\"ing*ness, n.",
  "fittable - Suitable; fit. [Obs.] Sherwood.",
  "apothegmatize - To utter apothegms, or short and sententious sayings.",
  "convexness - The state of being convex; convexity.",
  "oleamen - A soft ointment prepared from oil. Dunglison.",
  "buffin - A sort of coarse stuff; as, buffin gowns. [Obs.]",
  "newfanglist - One who is eager for novelties or desirous of change. [Obs.] Tooker.",
  "unreally - In an unreal manner; ideally.",
  "forelook - To look beforehand or forward. [Obs.] Spenser.",
  "instinction - Instinct; incitement; inspiration. [Obs.] Sir T. Elyot.",
  "aruspice - A soothsayer of ancient Rome. Same as Aruspex. [Written also haruspice.]",
  "teel - Sesame. [Sometimes written til.] Teel oil, sesame oil.",
  "brown race - The Malay or Polynesian race; -- loosely so called.",
  "sessional - Of or pertaining to a session or sessions.",
  "aucht - Property; possession. [Scot.] Sir W. Scott.",
  "exuperance - Superiority; superfluity. [Obs.] Sir K. Digby.",
  "durably - In a lasting manner; with long continuance.",
  "wigg - A kind of raised seedcake. \"Wiggs and ale.\" Pepys.",
  "bramin - , etc. See Brahman, Brachmanic, etc.",
  "mammalogy - The science which relates to mammals or the Mammalia. See Mammalia.",
  "miscellanea - A collection of miscellaneous matters; matters of various kinds.",
  "lactage - The produce of animals yielding milk; milk and that which is made from it.",
  "bosomed - Having, or resembling, bosom; kept in the bosom; hidden.",
  "peludo - The South American hairy armadillo (Dasypus villosus).",
  "amorphozoa - Animals without a mouth or regular internal organs, as the sponges.",
  "nimbly - In a nimble manner; with agility; with light, quick motion.",
  "parallel vise - A vise with jaws so guided as to remain parallel.",
  "polarily - In a polary manner; with polarity. [R.] Sir T. Browne.",
  "nias - A young hawk; an eyas; hence, an unsophisticated person. [Obs.]",
  "overfond - , Milton. -- O\"ver*fond\"ly, adv. -- O\"ver*fond\"ness, n.",
  "autogamous - Characterized by autogamy; self-fertilized.",
  "ozonification - The act or process of producing, or of subjecting to the action of, ozone.",
  "bescrawl - To cover with scrawls; to scribble over. Milton.",
  "unfret - To smooth after being fretted. [Obs.]",
  "secretive - Tending to secrete, or to keep secret or private; as, a secretive disposition.",
  "recommendative - That which recommends; a recommendation. [Obs.]",
  "graveolent - Having a rank smell. [R.] Boyle.",
  "cartography - The act business of forming chart's or maps.",
  "dejecture - That which is voided; excrements. Arbuthnot.",
  "sanctiloquent - Discoursing on heavenly or holy things, or in a holy manner.",
  "archegonial - Relating to the archegonium.",
  "thermodynamics - The science which treats of the mechanical action or relations of heat.",
  "consummately - In a consummate manner; completely. T. Warton.",
  "saintism - The character or quality of saints; also, hypocritical pretense of holiness. Wood.",
  "darwinism - The theory or doctrines put forth by Darwin. See above. Huxley.",
  "byssolite - An olive-green fibrous variety of hornblende.",
  "treasonous - Treasonable. Shak. The treasonous book of the Court of King James. Pepys.",
  "epiblastic - Of or relating to, or consisting of, the epiblast.",
  "nightshirt - A kind of nightgown for men.",
  "hypochondrium - Either of the hypochondriac regions.",
  "paragnathous - Having both mandibles of equal length, the tips meeting, as in certain birds.",
  "trepanner - One who trepans. \" Pitiful trepanners and impostors.\" Gauden.",
  "revengeable - Capable of being revenged; as, revengeable wrong. Warner.",
  "seismological - Of or pertaining to seismology. -- Seis`mo*log\"ic*al*ly, adv.",
  "drent - Drenched; drowned. [Obs.] \"Condemned to be drent.\" Spenser.",
  "gloominess - State of being gloomy. Addison.",
  "haveless - Having little or nothing. [Obs.] Gower.",
  "patronization - The act of patronizing; patronage; support. [R.]",
  "contender - One who contends; a contestant.",
  "floridity - The quality of being florid; floridness. Floyer.",
  "adrip - In a dripping state; as, leaves all adrip. D. G. Mitchell.",
  "incircumspection - Want of circumspection. Sir T. Browne.",
  "hinduism - The religious doctrines and rites of the Hindoos; Brahmanism.",
  "compassable - Capable of being compassed or accomplished. Burke.",
  "apair - To impair or become impaired; to injure. [Obs.] Chaucer.",
  "vibrancy - The state of being vibrant; resonance.",
  "calfskin - The hide or skin of a calf; or leather made of the skin.",
  "arkite - Belonging to the ark. [R.] Faber.",
  "conventicler - One who supports or frequents conventicles. Dryden.",
  "governal - Management; mastery. [Obs.] Chaucer. Spenser.",
  "single-minded - Having a single purpose; hence, artless; guileless; single- hearted.",
  "scovel - A mop for sweeping ovens; a malkin.",
  "brushiness - The quality of resembling a brush; brushlike condition; shagginess. Dr. H. More.",
  "chartaceous - Resembling paper or parchment; of paper-like texture; papery.",
  "cantref - A district comprising a hundred villages, as in Wales. [Written also kantry.]",
  "hostless - Inhospitable. [Obs.] \"A hostless house.\" Spenser.",
  "mercery - The trade of mercers; the goods in which a mercer deals.",
  "flaneur - One who strolls about aimlessly; a lounger; a loafer.",
  "tetrabranchiate - Of or pertaining to the Tetrabranchiata. -- n.  One of the Tetrabranchiata.",
  "subdeaconry - The order or office of subdeacon.",
  "preponderatingly - In a preponderating manner; preponderantly.",
  "questrist - A seeker; a pursuer. [Obs.] \"Hot questrists after him.\" Shak.",
  "formication - A sensation resembling that made by the creeping of ants on the skin. Dunglison.",
  "monostich - A composition consisting of one verse only.",
  "hary - To draw; to drag; to carry off by vio [Obs.] Chaucer.",
  "aeriform - Having the form or nature of air, or of an elastic fluid; gaseous. Hence fig.: Unreal.",
  "dramaturgy - The art of dramatic composition and representation.",
  "desirer - One who desires, asks, or wishes.",
  "maleficence - Evil doing, esp. to others.",
  "tipcart - A cart so constructed that the body can be easily tipped, in order to dump the load.",
  "imperfectibility - The state or quality of being imperfectible. [R.]",
  "transvasation - The act or process of pouring out of one vessel into another. [Obs.] Holland.",
  "unnaturalize - To make unnatural. [R.] Hales.",
  "asceticism - The condition, practice, or mode of life, of ascetics.",
  "showman - One who exhibits a show; a proprietor of a show.",
  "electrolyze - To decompose by the direct action of electricity. Faraday.",
  "abhorring - 1. Detestation. Milton. 2. Object of abhorrence. Isa. lxvi. 24.",
  "accipitral - Pertaining to, or of the nature of, a falcon or hawk; hawklike. Lowell.",
  "dispeopler - One who, or that which, dispeoples; a depopulator. Gay.",
  "postscribe - To make a postscript. [R.] T. Adams.",
  "idly - In a idle manner; ineffectually; vainly; lazily; carelessly; (Obs.) foolishly.",
  "thanksgiver - One who gives thanks, or acknowledges a kindness. Barrow.",
  "fabulist - One who invents or writes fables.",
  "circumduce - To declare elapsed, as the time allowed for introducing evidence. Sir W. Scott.",
  "ragabash - An idle, ragged person. Nares. Grose.",
  "releasee - One to whom a release is given.",
  "excuseless - Having no excuse; not admitting of excuse or apology. Whillock.",
  "sortance - Suitableness; agreement. [Obs.] hak.",
  "imprimery - (a) A print; impression. (b) A printing establishment. (c) The art of printing.",
  "haematodynamometer - Same as Hemadynamometer.",
  "stepstone - A stone laid before a door as a stair to rise on in entering the house.",
  "cornuto - A man that wears the horns; a cuckold. [R.] Shak.",
  "sandpit - A pit or excavation from which sand is or has been taken.",
  "change key - A key adapted to open only one of a set of locks; -- distinguished from a master key.",
  "collectedness - A collected state of the mind; self-possession.",
  "hypodermatic - Hypodermic. -- Hyp`o*der*mat\"ic*al*ly, adv.",
  "crotcheted - Marked or measured by crotchets; having musical notation. Harmar (1587).",
  "struthious - Of or pertaining to the Struthiones, or Ostrich tribe.",
  "evangelic - Belonging to, or contained in, the gospel; evangelical. \"Evangelic truth.\" J. Foster.",
  "architraved - Furnished with an architrave. Cowper.",
  "relentment - The act or process of retenting; the state of having relented. Sir T. Browne.",
  "alethiology - The science which treats of the nature of truth and evidence. Sir W. Hamilton.",
  "crabstick - A stick, cane, or cudgel, made of the wood of the carb tree.",
  "amicability - The quality of being amicable; friendliness; amicableness. Ash.",
  "shipyard - A yard, place, or inclosure where ships are built or repaired.",
  "sympetalous - Having the petals united; gamopetalous.",
  "racker - 1. One who racks. 2. A horse that has a racking gait.",
  "ametabolic - Not undergoing any metamorphosis; as, ametabolic insects.",
  "preordain - To ordain or appoint beforehand: to predetermine: to foreordain. Milton.",
  "stealthiness - The state, quality, or character of being stealthy; stealth.",
  "overlayer - One who overlays; that with which anything is overlaid.",
  "encoach - To carry in a coach. [R.] Davies (Wit's Pilgr.)",
  "fordrunken - Utterly drunk; very drunk. [Obs.] Chaucer.",
  "unborrowed - Not borrowed; being one's own; native; original.",
  "pandermite - A hydrous borate of lime, near priceite.",
  "metatungstate - A salt of metatungstic acid.",
  "bastardism - The state of being a bastard; bastardy.",
  "triticum - A genus of grasses including the various species of wheat.",
  "impressionistic - Pertaining to, or characterized by, impressionism.",
  "inaugur - To inaugurate. [Obs.] Latimer.",
  "attracting - That attracts. -- At*tract\"ing*ly, adv.",
  "craker - One who boasts; a braggart. [Obs.] Old Play.",
  "outburn - 1. To exceed in burning. 2. To burn entirely; to be consumed. Shak.",
  "worldlywise - Wise in regard to things of this world. Bunyan.",
  "undeserver - One of no merit; one who is nor deserving or worthy. [Obs.] Shak.",
  "gopher state - Minnesota; -- a nickname alluding to the abundance of gophers.",
  "stiriated - Adorned with pendants like icicles.",
  "charwoman - A woman hired for odd work or for single days.",
  "disclame - To disclaim; to expel. [Obs.] \"Money did love disclame.\" Spenser.",
  "manywise - In many different ways; variously.",
  "roundure - Roundness; a round or circle. [Obs.] Shak.",
  "whereout - Out of which. [R.] The cleft whereout the lightning breaketh. Holland.",
  "callisection - Painless vivisection; -- opposed to sentisection. B. G. Wilder.",
  "refrigerate - To cause to become cool; to make or keep cold or cool.",
  "fibrospongiae - An order of sponges having a fibrous skeleton, including the commercial sponges.",
  "haliotoid - Like or pertaining to the genus Haliotis; ear-shaped.",
  "alme - An Egyptian dancing girl; an Alma. The Almehs lift their arms in dance. Bayard Taylor.",
  "deambulate - To walk abroad. [Obs.] Cockeram.",
  "nidulite - A Silurian fossil, formerly supposed to consist of eggs.",
  "deterrence - That which deters; a deterrent; a hindrance. [R.]",
  "grandeeship - The rank or estate of a grandee; lordship. H. Swinburne.",
  "manling - A little man. [Obs.] B. Jonson.",
  "sectionize - To form into sections. [R.]",
  "vitious - See Vicious, Viciously, Viciousness.",
  "krang - The carcass of a whale after the blubber has been removed. [Written also crang and kreng.]",
  "unmantle - To divest of a mantle; to uncover. Nay, she said, but I will unmantle you. Sir W. Scott.",
  "reinvestment - The act of investing anew; a second or repeated investment.",
  "ancientness - The quality of being ancient; antiquity; existence from old times.",
  "mazological - Of or pertaining to mazology.",
  "leetman - One subject to the jurisdiction of a court-leet.",
  "accelerative - Relating to acceleration; adding to velocity; quickening. Reid.",
  "thermostatic - Of or pertaining to the thermostat; made or effected by means of the thermostat.",
  "playbill - A printed programme of a play, with the parts assigned to the actors.",
  "guardianess - A female guardian. I have placed a trusty, watchful guardianess. Beau. & Fl.",
  "rhino- - A combining form from Greek the nose, as in rhinolith, rhinology.",
  "resolutionist - One who makes a resolution.",
  "anthropologist - One who is versed in anthropology.",
  "sagy - Full of sage; seasoned with sage.",
  "reluctation - Repugnance; resistance; reluctance. [Obs.] Bacon.",
  "sea lawyer - The gray snapper. See under Snapper.",
  "standage - A reservior in which water accumulates at the bottom of a mine.",
  "goliardery - The satirical or ribald poetry of the Goliards. Milman.",
  "subchanter - An underchanter; a precentor's deputy in a cathedral; a succentor.",
  "dinumeration - Enumeration. [Obs.] Bullokar.",
  "milk-livered - White-livered; cowardly; timorous.",
  "morphologist - One who is versed in the science of morphology.",
  "nasopharyngeal - Of or pertaining to both throat and nose; as, a nasopharyngeal polypus.",
  "emparlance - Parley; imparlance. [Obs.] Spenser.",
  "thick-skinned - Having a thick skin; hence, not sensitive; dull; obtuse. Holland.",
  "limacon - A curve of the fourth degree, invented by Pascal. Its polar equation is r = a cos + b.",
  "wou-wou - The agile, or silvery, gibbon; -- called also camper. See Gibbon. [Written also wow-wow.]",
  "whitewing - (a) The chaffinch; -- so called from the white bands on the wing. (b) The velvet duck.",
  "scorpioid - 1. Having the inflorescence curved or circinate at the end, like a scorpion's tail.",
  "stonish - Stony. [R.] \"Possessed with stonish insensibility.\" Robynson (More's Utopia).",
  "intermine - To intersect or penetrate with mines. [Obs.] Drayton.",
  "crossly - Athwart; adversely; unfortunately; peevishly; fretfully; with ill humor.",
  "mastoiditis - Inflammation in the mastoid process of the temporal bone.",
  "winze - A small shaft sunk from one level to another, as for the purpose of ventilation.",
  "resperse - To sprinkle; to scatter. [Obs.] Jer. Taylor.",
  "vesses - A kind of worsted; also, a worsted cloth. [Prov. Eng.]",
  "thallate - A salt of a hypothetical thallic acid.",
  "quarried - Provided with prey. Now I am bravely quarried. Beau. & Fl.",
  "preconformity - Anticipative or antecedent conformity. Coleridge.",
  "codification - The act or process of codifying or reducing laws to a code.",
  "jugulate - To cut the throat of. [R.] Jacob Bigelow.",
  "splendidous - Splendid. [Obs.] B. Jonson.",
  "magnification - The act of magnifying; enlargement; exaggeration. [R.]",
  "telesmatic - Of or pertaining to telesms; magical. J. Gregory.",
  "cormophylogeny - The phylogeny of groups or families of individuals. Haeckel.",
  "pedagogics - The science or art of teaching; the principles and rules of teaching; pedagogy.",
  "befoul - 1. To make foul; to soil. 2. To entangle or run against so as to impede motion.",
  "rima - A narrow and elongated aperture; a cleft; a fissure.",
  "defectuosity - Great imperfection. [Obs.] W. Montagu.",
  "underleaf - A prolific sort of apple, good for cider. [Obs.] Mortimer.",
  "madnep - The masterwort (Peucedanum Ostruthium).",
  "bain - A bath; a bagnio. [Obs.] Holland.",
  "chandlerly - Like a chandler; in a petty way. [Obs.] Milton.",
  "impoverisher - One who, or that which, impoverishes.",
  "twangle - To twang. While the twangling violin Struck up with Soldier-laddie. Tennyson.",
  "entryng - Am entrance. [Obs.] So great an entryng and so large. Chaucer.",
  "planetical - Of or pertaining to planets. Sir T. Browne.",
  "denominationally - In a denominational manner; by denomination or sect.",
  "avicular - Of or pertaining to a bird or to birds.",
  "avowable - Capable of being avowed, or openly acknowledged, with confidence. Donne.",
  "anyway - Anywise; at all. Tennyson. Southey.",
  "godild - A corruption of God yield, i. e., God reward or bless. Shak.",
  "angularness - The quality of being angular.",
  "prosobranch - One of the Prosobranchiata.",
  "forstraught - Distracted. [Obs.] Chaucer.",
  "supranaturalistic - Of or pertaining to supernaturalism; supernaturalistic.",
  "determinability - The quality of being determinable; determinableness. Coleridge.",
  "pugil - As much as is taken up between the thumb and two first fingers. [Obs.] Bacon.",
  "pelicosauria - A suborder of Theromorpha, including terrestrial reptiles from the Permian formation.",
  "oxygonial - Having acute angles. Barlow.",
  "cryptogamist - One skilled in cryptogamic botany.",
  "gunsmithery - The art or business of a gunsmith.",
  "relove - To love in return. [Obs.] Boyle.",
  "cheverliize - To make as pliable as kid leather. [Obs.] Br. Montagu.",
  "cerebration - Action of the brain, whether conscious or unconscious.",
  "electroscopic - Relating to, or made by means of, the electroscope.",
  "becker - A European fish (Pagellus centrodontus); the sea bream or braise.",
  "illapsable - Incapable of slipping, or of error. [R.] Morally immutable and illapsable. Glanvill.",
  "unstep - To remove, as a mast, from its step.",
  "vinolent - Given to wine; drunken; intemperate. [Obs.] Chaucer.",
  "cacostomia - Diseased or gangrenous condition of the mouth.",
  "lapilli - Volcanic ashes, consisting of small, angular, stony fragments or particles.",
  "stallion - A male horse not castrated; a male horse kept for breeding.",
  "epipodium - One of the lateral lobes of the foot in certain gastropods.",
  "circuline - Proceeding in a circle; circular. [Obs.] \"With motion circuline\". Dr. H. More.",
  "bandle - An Irish measure of two feet in length.",
  "chimney-piece - A decorative construction around the opning of a fireplace.",
  "enseel - To close eyes of; to seel; -- said in reference to a hawk. [Obs.]",
  "hyopastron - The second lateral plate in the plastron of turtles; -- called also hyosternum.",
  "apiculate - Terminated abruptly by a small, distinct point, as a leaf.",
  "atabal - A kettledrum; a kind of tabor, used by the Moors. Croly.",
  "fucate - Painted; disguised with paint, or with false show.",
  "hagiocracy - Government by a priesthood; hierarchy.",
  "instructional - Pertaining to, or promoting, instruction; educational.",
  "minious - Of the color of red or vermilion. [Obs.] Sir T. Browne.",
  "paleosaurus - A genus of fossil saurians found in the Permian formation.",
  "calcographical - Relating to, or in the style of, calcography.",
  "monotrematous - Of or pertaining to the Monotremata.",
  "toupettit - The crested titmouse. [Prov. Eng.]",
  "decretist - One who studies, or professes the knowledge of, the decretals.",
  "parter - One who, or which, parts or separates. Sir P. Sidney.",
  "inspiring - Animating; cheering; moving; exhilarating; as, an inspiring or scene.",
  "chaldrich - A kind of bird; the oyster catcher.",
  "ratability - The quality or state of being ratable.",
  "uprighteously - In an upright or just manner. [Obs.] Shak.",
  "nucleobranch - Belonging to the Nucleobranchiata. -- n.  One of the Nucleobranchiata.",
  "ostraciont - A fish of the genus Ostracion and allied genera.",
  "vicenary - Of or pertaining to twenty; consisting of twenty.",
  "geognosis - Knowledge of the earth. [R.] G. Eliot.",
  "malignly - In a malign manner; with malignity.",
  "sporophoric - Having the nature of a sporophore.",
  "zymologic - Of or pertaining to zymology.",
  "venose - Having numerous or conspicuous veins; veiny; as, a venose frond.",
  "bedew - To moisten with dew, or as with dew. \"Falling tears his face bedew.\" Dryden.",
  "orgy - A frantic revel; drunken revelry. See Orgies",
  "molossus - A foot of three long syllables. [Written also molosse.]",
  "sonority - The quality or state of being sonorous; sonorousness.",
  "medicative - Medicinal; acting like a medicine.",
  "pipevine - The Dutchman's pipe. See under Dutchman.",
  "insubstantiality - Unsubstantiality; unreality. [R.]",
  "discriminous - Hazardous; dangerous. [Obs.] Harvey.",
  "goniometry - The art of measuring angles; trigonometry.",
  "onliness - The state of being alone. [Obs.]",
  "dramatist - The author of a dramatic composition; a writer of plays.",
  "cosmologist - One who describes the universe; one skilled in cosmology.",
  "sickerness - The quality or state of being sicker, or certain. [Obs.] Chaucer. Spenser.",
  "occasionable - Capable of being occasioned or caused. Barrow.",
  "alopecist - A practitioner who tries to prevent or cure baldness.",
  "genesiolgy - The doctrine or science of generation.",
  "chrysogen - A yellow crystalline substance extracted from crude anthracene.",
  "tastable - Capable of worthy of being tasted; savory; relishing.",
  "tropism - Modification of the direction of growth.",
  "procuratorship - The office or term of a procurator. Bp. Pearson.",
  "franchisement - Release; deliverance; freedom. Spenser.",
  "transportance - Transportation. [Obs.] \"Give me swift transportance.\" Shak.",
  "gloat - To look steadfastly; to gaz In vengeance gloating on another's pain. Byron.",
  "ruderary - Of or pertaining to rubbish.. [Obs.] Bailey.",
  "fermacy - Medicine; pharmacy. [Obs.] Chaucer.",
  "manyways - In many different ways; variously.",
  "melanochroi - A group of the human race, including the dark whites.",
  "frangibility - The state or quality of being frangible. Fox.",
  "ordinability - Capability of being ordained or appointed. [Obs.] Bp. Bull.",
  "cabiric - Of or pertaining to the Cabiri, or to their mystical worship. [Written also Cabiritic.]",
  "misallied - Wrongly allied or associated.",
  "theriodont - One of the Theriodontia. Used also adjectively.",
  "fucivorous - Eating fucus or other seaweeds.",
  "monachal - Of or pertaining to monks or a monastic life; monastic.",
  "dimly - In a dim or obscure manner; not brightly or clearly; with imperfect sight.",
  "balsamous - Having the quality of balsam; containing balsam. \"A balsamous substance.\" Sterne.",
  "sinicism - Anything peculiar to the Chinese; esp., a Chinese peculiarity in manners or customs.",
  "germ cell - A cell, of either sex, directly concerned in the production of a new organism.",
  "incremate - To consume or reduce to ashes by burning, as a dead body; to cremate.",
  "unmasterable - Incapable of being mastered or subdued. [Obs.] Sir T. Browne.",
  "drillmaster - One who teaches drill, especially in the way of gymnastics. Macaulay.",
  "oenology - Knowledge of wine, scientific or practical.",
  "chati - A small South American species of tiger cat (Felis mitis).",
  "praecornu - The anterior horn of each lateral ventricle of the brain. B. G. Wilder.",
  "subalternating - Subalternate; successive.",
  "gaudish - Gaudy. \"Gaudish ceremonies.\" Bale.",
  "belute - To bespatter, as with mud. [R.] Sterne.",
  "swasher - One who makes a blustering show of valor or force of arms. Shak.",
  "oberon - The king of the fairies, and husband of Titania or Queen Mab. Shak.",
  "hydatoid - Resembling water; watery; aqueous; hyaloid.",
  "daltonian - One afflicted with color blindness.",
  "recognizor - One who enters into a recognizance. [Written also recognisor.] Blackstone.",
  "cavort - To prance ostentatiously; -- said of a horse or his rider. [Local slang U. S.]",
  "pleonastically - In a pleonastic manner.",
  "cardiography - 1. Description of the heart. 2.  (Physiol.) Examination by the cardiograph.",
  "whipcord - A kind of hard-twisted or braided cord, sometimes used for making whiplashes.",
  "demonetization - The act of demonetizing, or the condition of being demonetized.",
  "nousle - To insnare; to entrap. [Obs.] Johnson.",
  "disportment - Act of disporting; diversion; play. [Obs.] Dr. H. More.",
  "underpull - To exert one's influence secretly. [Obs.] Ld. North.",
  "discusser - One who discusses; one who sifts or examines. Wood.",
  "burgrass - Grass of the genus Cenchrus, growing in sand, and having burs for fruit.",
  "slip-on - A kind of overcoat worn upon the shoulders in the manner of a cloak. [Scot.]",
  "cannonier - A man who manages, or fires, cannon.",
  "gangliated - Furnished with ganglia; as, the gangliated cords of the sympathetic nervous system.",
  "irreconciliation - Want of reconciliation; disagreement.",
  "juiciness - The state or quality of being juicy; succulence plants.",
  "subocular - Situated under, or on the ventral side of, the eye.",
  "glomerous - Gathered or formed into a ball or round mass. [Obs.] Blount.",
  "ichthyolatry - Worship of fishes, or of fish-shaped idols. Layard.",
  "ergotic - Pertaining to, or derived from, ergot; as, ergotic acid.",
  "unabridged - Not abridged, or shortened; full; complete; entire; whole.",
  "rummer - A large and tall glass, or drinking cup. [Obs.] J. Philips.",
  "irreptitious - Surreptitious; spurious. [Obs.] Dr. Castell (1673).",
  "pulpited - Placed in a pulpit. [R.] Sit . . . at the feet of a pulpited divine. Milton.",
  "autohypnotism - Hypnotism of one's self by concentration of the attention on some object or idea.",
  "harten - To hearten; to encourage; to incite. [Obs.] Spenser.",
  "altiloquent - High-sounding; pompous in speech. [R.] Bailey.",
  "nonchalance - Indifference; carelessness; coolness.",
  "novatianism - The doctrines or principles of the Novatians. Milner.",
  "timorsome - Easily frightened; timorous. [Written also timersome.] [Scot.] Sir W. Scott.",
  "impeople - To people; to give a population to. [Obs.] Thou hast helped to impeople hell. Beaumont.",
  "improviso - Not prepared or mediated beforehand; extemporaneous. [Obs.] Jonhson.",
  "camel-backed - Having a back like a camel; humpbacked. Fuller.",
  "annomination - 1. Paronomasia; punning. 2. Alliteration. [Obs.] Tyrwhitt.",
  "razor-backed - Having a sharp, lean, or thin back; as, a razor-backed hog, perch, etc.",
  "stelography - The art of writing or inscribing characters on pillars. [R.] Stackhouse.",
  "accumbency - The state of being accumbent or reclining. [R.]",
  "blasphemously - In a blasphemous manner.",
  "spignet - An aromatic plant of America. See Spikenard.",
  "dropt - imp. & p. p. of Drop, v. G. Eliot.",
  "boroughmonger - One who buys or sells the parliamentary seats of boroughs.",
  "ironmongery - Hardware; a general name for all articles made of iron. Gwilt.",
  "hammochrysos - A stone with spangles of gold color in it.",
  "plani- - Combining forms signifying flat, level, plane; as planifolious, planimetry, plano-concave.",
  "chylopoetic - Concerned in the formation of chyle; as, the chylopoetic organs.",
  "abluent - Washing away; carrying off impurities; detergent. -- n. (Med.)  A detergent.",
  "neighboring - Living or being near; adjacent; as, the neighboring nations or countries.",
  "yeldrin - The yellow-hammer; -- called also yeldrock, and yoldrin. [Prov. Eng.]",
  "annunciative - Pertaining to annunciation; announcing. [R.] Dr. H. More.",
  "outway - A way out; exit. [R.] In divers streets and outways multiplied. P. Fletcher.",
  "searchless - Impossible to be searched; inscrutable; impenetrable.",
  "aglimmer - In a glimmering state. Hawthorne.",
  "mucid - Musty; moldy; slimy; mucous. -- Mu\"cid*ness, n.",
  "charras - The gum resin of the hemp plant (Cannabis sativa). Same as Churrus. Balfour.",
  "ichnite - A fossil footprint; as, the ichnites in the Triassic sandstone. Page.",
  "cobwall - A wall made of clay mixed with straw.",
  "subtartarean - Being or living under Tartarus; infernal. \"Subtartarean powers.\" Pope.",
  "delaceration - A tearing in pieces. [Obs.] Bailey.",
  "subpulmonary - Situated under, or on the ventral side of, the lungs.",
  "concavo-concave - Concave or hollow on both sides; double concave.",
  "floppy - Having a tendency to flop or flap; as, a floppy hat brim. G. Eliot.",
  "nighness - The quality or state of being nigh. [R.] \"Nighness of blood.\" Holished.",
  "churning - 1. The act of one who churns. 2. The quantity of butter made at one operation.",
  "xanthose - An orange-yellow substance found in pigment spots of certain crabs.",
  "inadmissibility - The state or quality of being inadmissible, or not to be received.",
  "gambroon - A kind of twilled linen cloth for lining. Simmonds.",
  "subarytenoid - Situated under the arytenoid cartilage of the larynx.",
  "zinziberaceous - Same as Zingiberaceous.",
  "premillennial - , Previous to the millennium.",
  "refashion - To fashion anew; to form or mold into shape a second time. MacKnight.",
  "duly - In a due, fit, or becoming manner; as it (anything) ought to be; properly; regularly.",
  "vaccary - A cow house, dairy house, or cow pasture. [Obs. or Prov. Eng.] Wright.",
  "hepatogenous - Arising from the liver; due to a condition of the liver; as, hepatogenic jaundice.",
  "rosland - heathy land; land full of heather; moorish or watery land. [prov. Eng.]",
  "downweigh - To weigh or press down. A different sin downweighs them to the bottom. Longfellow.",
  "egregiously - Greatly; enormously; shamefully; as, egregiously cheated.",
  "puzzlement - The state of being puzzled; perplexity. Miss Mitford.",
  "kanacka - A native of the Sandwich Islands.",
  "chondritis - An inflammation of cartilage.",
  "tahaleb - A fox (Vulpes Niloticus) of Northern Africa.",
  "hepta - A combining form from Gr. \"epta`, seven.",
  "swag-bellied - Having a prominent, overhanging belly. Shak.",
  "racketer - One who makes, or engages in, a racket.",
  "misworshiper - One who worships wrongly.",
  "liquidity - The state or quality of being liquid.",
  "pronate - Somewhat prone; inclined; as, pronate trees. Kane.",
  "monospherical - Consisting of one sphere only.",
  "oxybromic - Pertaining to, or designating, certain compounds of oxygen and bromine.",
  "culrage - Smartweed (Polygonum Hydropiper).",
  "shet - To shut. [Obs. or Prov. Eng.] Chaucer.",
  "phenanthridine - A nitrogenous hydrocarbon base, C13H9N, analogous to phenanthrene and quinoline.",
  "causerie - Informal talk or discussion, as about literary matters; light conversation; chat.",
  "tonnihood - The female of the bullfinch; -- called also tonyhoop. [Prov. Eng.]",
  "vividity - The quality or state of being vivid; vividness. [R.]",
  "embryologist - One skilled in embryology.",
  "oratorial - Oratorical. [R.] Swift. --Or`a*to\"ri*al*ly, adv.",
  "bawcock - A fine fellow; -- a term of endearment. [Obs.] \"How now, my bawcock \" Shak.",
  "auditorship - The office or function of auditor.",
  "block book - A book printed from engraved wooden blocks instead of movable types.",
  "nigrosine - A dark blue dyestuff, of the induline group; -- called also azodiphenyl blue.",
  "overwasted - Wasted or worn out; [Obs.] Drayton.",
  "doubtfully - In a doubtful manner. Nor did the goddess doubtfully declare. Dryden.",
  "exigible - That may be exacted; repairable. [R.] A. Smith.",
  "assenting - Giving or implying assent. -- As*sent\"ing*ly, adv.",
  "antefact - Something done before another act. [Obs.]",
  "encrinic - Relating to encrinites; containing encrinites, as certain kinds of limestone.",
  "heathenesse - Heathendom. [Obs.] Chaucer. Sir W. Scott.",
  "berime - To berhyme. Note: [The earlier and etymologically preferable spelling.]"
]