export default [
  "contrabandism - Traffic in contraband gods; smuggling.",
  "martialism - The quality of being warlike; exercises suitable for war. [Obs.]",
  "posteriors - The hinder parts, as of an animal's body. Swift.",
  "lester - A dry sirocco in the Madeira Islands.",
  "indistancy - Want of distance o [Obs.] Bp. Pearson.",
  "bakehouse - A house for baking; a bakery.",
  "tideway - Channel in which the tide sets.",
  "indefiniteness - The quality of being indefinite.",
  "thana - A police station. [India] Kipling.",
  "in commendam - See Commendam, and Partnership in Commendam, under Partnership.",
  "mollifiable - Capable of being mollified.",
  "trustiness - The quality or state of being trusty.",
  "reconjoin - To join or conjoin anew. Boyle.",
  "eccritic - A remedy which promotes discharges, as an emetic, or a cathartic.",
  "catery - The place where provisions are deposited. [Obs.]",
  "orthostichy - A longitudinal rank, or row, of leaves along a stem.",
  "dendriform - Resembling in structure a tree or shrub.",
  "undefatigable - Indefatigable. [Obs.] \"Undefatigable pains.\" Camden.",
  "incuriosity - Want of curiosity or interest; inattentiveness; indifference. Sir H. Wotton.",
  "atmological - Of or pertaining to atmology. \"Atmological laws of heat.\" Whewell.",
  "electro-kinetics - That branch of electrical science which treats of electricity in motion.",
  "platetrope - One of a pair of a paired organs.",
  "porphyrization - The act of porphyrizing, or the state of being porphyrized.",
  "carpological - Of or pertaining to carpology.",
  "trucking - The business of conveying goods on trucks.",
  "upridged - Raised up in a ridge or ridges; as, a billow upridged. Cowper.",
  "shearbill - The black skimmer. See Skimmer.",
  "anthropophaginian - One who east human flesh. [Ludicrous] Shak.",
  "wrong-timed - Done at an improper time; ill-timed.",
  "manless - 1. Destitute of men. Bakon. 2. Unmanly; inhuman. [Obs.] Chapman.",
  "unbowel - To deprive of the entrails; to disembowel. Dr. H. More.",
  "inmesh - To bring within meshes, as of a net; to enmesh.",
  "dysphony - A difficulty in producing vocal sounds; enfeebled or depraved voice.",
  "intropression - Pressure acting within. [R.]",
  "housewifery - The business of the mistress of a family; female management of domestic concerns.",
  "do-naught - A lazy, good-for-nothing fellow.",
  "prognathism - Projection of the jaws. -- Prog\"na*thy, n.",
  "haffle - To stammer; to speak unintelligibly; to prevaricate. [Prov.Eng.] Halliwell.",
  "anthropic - Like or related to man; human. [R.] Owen.",
  "receivability - The quality of being receivable; receivableness.",
  "ennuyee - A woman affected with ennui. Mrs. Jameson.",
  "bannition - The act of expulsion.[Obs.] Abp. Laud.",
  "unpredict - To retract or falsify a previous prediction. Milton.",
  "persevering - Characterized by perseverance; persistent. -- Per`se*ver\"ing*ly, adv.",
  "pentastich - A composition consisting of five verses.",
  "pargetory - Something made of, or covered with, parget, or plaster. [Obs.] Milton.",
  "cherubic - Of or pertaining to cherubs; angelic. \"The cherubic host.\" Milton.",
  "doughnut - A small cake (usually sweetened) fried in a kettle of boiling lard.",
  "panelation - The act of impaneling a jury. [Obs.] [Written also panellation.] Wood.",
  "neonomianism - The doctrines or belief of the neonomians.",
  "legibleness - The state or quality of being legible.",
  "anacanths - A group of teleostean fishes destitute of spiny fin-rays, as the cod.",
  "gangrel - Wandering; vagrant. [Scot.] Sir W. Scott.",
  "ranterism - The practice or tenets of the Ranters.",
  "chaliced - Having a calyx or cup; cupshaped. \"Chaliced flowers.\" Shak.",
  "deer-neck - A deerlike, or thin, ill-formed neck, as of a horse.",
  "indigency - Indigence. New indigencies founded upon new desires. South.",
  "sky pilot - A person licensed as a pilot. [Slang]",
  "elleck - The red gurnard or cuckoo fish. [Prov. Eng.]",
  "scoat - To prop; to scotch. [Prov. Eng.]",
  "handiness - The quality or state of being handy.",
  "zincide - A binary compound of zinc. [R.]",
  "whiggish - Of or pertaining to Whigs; partaking of, or characterized by, the principles of Whigs.",
  "electrizer - One who, or that which, electrizes.",
  "paludicolae - A division of birds, including the cranes, rails, etc.",
  "semipenniform - Half or partially penniform; as, a semipenniform muscle.",
  "microtomical - Of or pert. to the microtome or microtomy; cutting thin slices.",
  "ditheistical - Pertaining to ditheism; dualistic.",
  "batture - An elevated river bed or sea bed.",
  "assumed - 1. Supposed. 2. Pretended; hypocritical; make-believe; as, an assumed character.",
  "outpass - To pass beyond; to exceed in progress.",
  "undercraft - A sly trick or device; as, an undercraft of authors. [R.] Sterne.",
  "imbuement - The act of imbuing; the state of being imbued; hence, a deep tincture.",
  "here-at - At, or by reason of, this; as, he was offended hereat. Hooker.",
  "diversivolent - Desiring different things. [Obs.] Webster (White Devil).",
  "sea term - A term used specifically by seamen; a nautical word or phrase.",
  "umbonated - Having a conical or rounded projection or protuberance, like a boss.",
  "synonymist - One who collects or explains synonyms.",
  "hymenopteral - Like, or characteristic of, the Hymenoptera; pertaining to the Hymenoptera.",
  "antiparallel - Running in a contrary direction. Hammond.",
  "sisyphean - Relating to Sisyphus; incessantly recurring; as, Sisyphean labors.",
  "trugging-house - A brothel. [Obs.] Robert Greene.",
  "rentier - One who has a fixed income, as from lands, stocks, or the like.",
  "binturong - A small Asiatic civet of the genus Arctilis.",
  "velutina - Any one of several species of marine gastropods belonging to Velutina and allied genera.",
  "survivance - Survivorship. [R.] His son had the survivance of the stadtholdership. Bp. Burnet.",
  "dismortgage - To redeem from mortgage. [Obs.] Howell.",
  "yedding - The song of a minstrel; hence, any song. [Obs.] Chaucer.",
  "rescribe - 1. To write back; to write in reply. Ayliffe. 2. To write over again. Howell.",
  "vacher - A keeper of stock or cattle; a herdsman. [Southwestern U. S.] Bartlett.",
  "fixative - That which serves to set or fix colors or drawings, as a mordant.",
  "yester-morning - The morning of yesterday. Coleridge.",
  "moonrise - The rising of the moon above the horizon; also, the time of its rising.",
  "alkaloidal - Pertaining to, resembling, or containing, alkali.",
  "rivery - Having rivers; as, a rivery country. Drayton.",
  "wilful - See Willful, Willfully, and Willfulness.",
  "bibliotaph - One who hides away books, as in a tomb. [R.] Crabb.",
  "ichnolithology - Same as Ichnology. Hitchcock.",
  "shelduck - The sheldrake. [Written also shellduck.]",
  "resorption - The act of resorbing; also, the act of absorbing again; reabsorption.",
  "routinary - Involving, or pertaining to, routine; ordinary; customary. [R.] Emerson.",
  "academist - 1. An Academic philosopher. 2. An academician. [Obs.] Ray.",
  "slippage - The act of slipping; also, the amount of slipping.",
  "flatulency - The state or quality of being flatulent.",
  "staffier - An attendant bearing a staff. [Obs.] \"Staffiers on foot.\" Hudibras.",
  "lumbric - An earthworm, or a worm resembling an earthworm.",
  "speechful - Full of speech or words; voluble; loquacious. [R.]",
  "vocalness - The quality of being vocal; vocality.",
  "delimitation - The act or process of fixing limits or boundaries; limitation. Gladstone.",
  "merulidan - A bird of the Thrush family.",
  "sewe - To perform the duties of a sewer. See 3d Sewer. [Obs.]",
  "slipperiness - The quality of being slippery.",
  "coscinomancy - Divination by means of a suspended sieve.",
  "imaginability - Capacity for imagination. [R.] Coleridge.",
  "lacrymose - See Lachrymary, Lachrymatory, Lachrymose.",
  "sagoin - A marmoset; -- called also sagouin.",
  "diacoustic - Pertaining to the science or doctrine of refracted sounds.",
  "tousle - To put into disorder; to tumble; to touse. [Colloq.]",
  "appetence - A longing; a desire; especially an ardent desire; appetite; appetency.",
  "pyrethrine - An alkaloid extracted from the root of the pellitory of Spain (Anacyclus pyrethrum).",
  "ejulation - A wailing; lamentation. [Obs.] \"Ejulation in the pangs of death.\" Philips.",
  "etymologist - One who investigates the derivation of words.",
  "verifier - One who, or that which, verifies.",
  "petulcous - Wanton; frisky; lustful. [Obs.] J. V. Cane.",
  "upswarm - To rise, or cause to rise, in a swarm or swarms. [R.] Shak. Cowper.",
  "four-wheeler - A vehicle having four wheels. [Colloq.]",
  "hyperthyrion - That part of the architrave which is over a door or window.",
  "congratulator - One who offers congratulation. Milton.",
  "imaginant - Imagining; conceiving. [Obs.] Bacon. -- n.  An imaginer. [Obs.] Glanvill.",
  "cancriform - 1. Having the form of, or resembling, a crab; crab-shaped. 2. Like a cancer; cancerous.",
  "refortification - A fortifying anew, or a second time. Mitford.",
  "coxcombry - The manners of a coxcomb; foppishness.",
  "enjail - To put into jail; to imprison. [R.] Donne.",
  "surement - A making sure; surety. [Obs.] Every surement and every bond. Chaucer.",
  "entomologic - Of or relating to entomology. -- En`to*mo*log\"ic*al*ly, adv.",
  "marmoraceous - Pertaining to, or like, marble.",
  "prelatical - Of or pertaining to prelates or prelacy; as, prelatical authority. Macaulay.",
  "reimbursement - The act reimbursing. A. Hamilton.",
  "hyphenated - United by hyphens; hyphened; as, a hyphenated or hyphened word.",
  "quadragesimal - Belonging to Lent; used in Lent; Lenten.",
  "toxotes - A genus of fishes comprising the archer fishes. See Archer fish.",
  "inion - The external occipital protuberance of the skull.",
  "paduasoy - A rich and heavy silk stuff. [Written also padesoy.]",
  "sceneshifter - One who moves the scenes in a theater; a sceneman.",
  "fireside - A place near the fire or hearth; home; domestic life or retirement.",
  "carcinosys - The affection of the system with cancer.",
  "amblyopic - Of or pertaining to amblyopy. Quain.",
  "rickety - 1. Affected with rickets. 2. Feeble in the joints; imperfect; weak; shaky.",
  "scammoniate - Made from scammony; as, a scammoniate aperient.",
  "proboscidate - Having a proboscis; proboscidial.",
  "apronful - The quality an apron can hold.",
  "wifehood - 1. Womanhood. [Obs.] Chaucer. 2. The state of being a wife; the character of a wife.",
  "allopathic - Of or pertaining to allopathy.",
  "acanthopodious - Having spinous petioles.",
  "interpretatively - By interpretation. Ray.",
  "vinette - A sprig or branch. [Archaic] Halliwell.",
  "biliprasin - A dark green pigment found in small quantity in human gallstones.",
  "moggan - A closely fitting knit sleeve; also, a legging of knitted material. [Scot.]",
  "epiboly - Epibolic invagination. See under Invagination.",
  "mouth-footed - Having the basal joints of the legs converted into jaws.",
  "multilineal - Having many lines. Steevens.",
  "cutwal - The chief police officer of a large city. [East Indies]",
  "musquaw - The American black bear. See Bear.",
  "bejape - To jape; to laugh at; to deceive. [Obs.] Chaucer.",
  "bottler - One who bottles wine, beer, soda water, etc.",
  "insecable - Incapable of being divided by cutting; indivisible.",
  "misbeliever - One who believes wrongly; one who holds a false religion. Shak.",
  "intirely - See Entire, a., Entirely, adv.",
  "extendlessness - Unlimited extension. [Obs.] An . . . extendlessness of excursions. Sir. M. Hale.",
  "conciseness - The quality of being concise.",
  "hithe - A port or small haven; -- used in composition; as, Lambhithe, now Lambeth. Pennant.",
  "lacquering - The act or business of putting on lacquer; also, the coat of lacquer put on.",
  "lender - One who lends. The borrower is servant to the lender. Prov. xxii. 7.",
  "weanedness - Quality or state of being weaned.",
  "prorate - To divide or distribute proportionally; to assess pro rata. [U.S.]",
  "monodelphous - Of or pertaining to the Monodelphia.",
  "wynkernel - The European moor hen. [Prov. Eng.]",
  "ergotized - Affected with the ergot fungus; as, ergotized rye.",
  "jackeen - A drunken, dissolute fellow. [Ireland] S. C. Hall.",
  "stylopodium - An expansion at the base of the style, as in umbelliferous plants.",
  "dummerer - One who feigns dumbness. [Obs.] Burton.",
  "maltreat - To treat ill; to abuse; to treat roughly.",
  "actuality - The state of being actual; reality; as, the actuality of God's nature. South.",
  "bed-moulding - The molding of a cornice immediately below the corona. Oxf. Gloss.",
  "fibrinogenous - Possessed of properties similar to fibrinogen; capable of forming fibrin.",
  "sinologue - A student of Chinese; one versed in the Chinese language, literature, and history.",
  "capulin - The Mexican chery (Prunus Capollin).",
  "tetrasyllabical - Consisting of, or having, four syllables; quadrisyllabic.",
  "infoldment - The act of infolding; the state of being infolded.",
  "anthropidae - The group that includes man only.",
  "racking - Spun yarn used in racking ropes.",
  "hawkeye state - Iowa; -- a nickname of obscure origin.",
  "spetches - Parings and refuse of hides, skins, etc., from which glue is made.",
  "grosgrain - Of a coarse texture; -- applied to silk with a heavy thread running crosswise.",
  "hen-hearted - Cowardly; timid; chicken-hearted. Udall.",
  "pyro - Abbreviation of pyrogallic acid. [Colloq.]",
  "sculptural - Of or pertaining to sculpture. G. Eliot.",
  "bookbinding - The art, process, or business of binding books.",
  "indivisibleness - The state of being indivisible; indivisibility. W. Montagu.",
  "quiddler - One who wastes his energy about trifles. Emerson.",
  "hybernation - See Hibernacle, Hibernate, Hibernation.",
  "tithable - Subject to the payment of tithes; as, tithable lands.",
  "limpsy - Limp; flexible; flimsy. [Local, U. S.]",
  "erminois - See Note under Ermine, n., 4.",
  "missish - Like a miss; prim; affected; sentimental. -- Miss\"ish*ness, n.",
  "deline - 1. To delineate. [Obs.] 2. To mark out. [Obs.] R. North.",
  "gastroraphy - The operation of sewing up wounds of the abdomen. Quincy.",
  "serry - To crowd; to press together. Note: [Now perhaps only in the form serried, p. p. or a.]",
  "corregidor - The chief magistrate of a Spanish town.",
  "subahship - The office or jurisdiction of a subahdar.",
  "long-stop - One who is set to stop balls which pass the wicket keeper.",
  "enthelmintha - Intestinal worms. See Helminthes.",
  "encouraging - Furnishing ground to hope; inspiriting; favoring. -- En*cour\"a*ging*ly, adv.",
  "stercoration - Manuring with dung. [Obs.] Bacon.",
  "sexdigitism - The state of having six fingers on a hand, or six toes on a foot.",
  "metazoic - Of or pertaining to the Metazoa.",
  "howp - To cry out; to whoop. [Obs.] Chaucer.",
  "chlorometer - An instrument to test the decoloring or bleaching power of chloride of lime.",
  "hernani - A thin silk or woolen goods, for women's dresses, woven in various styles and colors.",
  "marginella - A genus of small, polished, marine univalve shells, native of all warm seas.",
  "phase angle - The angle expressing phase relation.",
  "embrawn - To harden. [Obs.] It will embrawn and iron-crust his flesh. Nash.",
  "glabrous - Smooth; having a surface without hairs or any unevenness.",
  "suprapubic - Situated above, or anterior to, the pubic bone.",
  "chromoblast - An embryonic cell which develops into a pigment cell.",
  "imprejudicate - Not prejuged; unprejudiced; impartial. [Obs.] Sir T. Browne.",
  "glombe - To gloom; to look gloomy, morose, or sullen. [Obs.] Surrey.",
  "tubfish - The sapphirine gurnard (Trigla hirundo). See Illust. under Gurnard. [Prov. Eng.]",
  "coadjutive - Rendering mutual aid; coadjutant. Feltham.",
  "velveting - The fine shag or nap of velvet; a piece of velvet; velvet goods.",
  "brettice - The wooden boarding used in supporting the roofs and walls of coal mines. See Brattice.",
  "beautiless - Destitute of beauty. Hammond.",
  "pawnbroking - The business of a pawnbroker.",
  "charmful - Abounding with charms. \"His charmful lyre.\" Cowley.",
  "nonstriated - Without striations; unstriped; as, nonstriated muscle fibers.",
  "poh - An exclamation expressing contempt or disgust; bah !",
  "undraw - To draw aside or open; to draw back. Angels undrew the curtain of the throne. Young.",
  "metagnathous - Cross-billed; -- said of certain birds, as the crossbill.",
  "moderatress - A female moderator. Fuller.",
  "sphygmometer - An instrument for measuring the strength of the pulse beat; a sphygmograph.",
  "tournery - Work turned on a lathe; turnery.[Obs.] See Turnery. Evelyn.",
  "pincpinc - An African wren warbler. (Drymoica textrix).",
  "suaviloquent - Sweetly speaking; using agreeable speech. [R.]",
  "tentmaker - One whose occupation it is to make tents. Acts xviii. 3.",
  "slowback - A lubber; an idle fellow; a loiterer. [Old Slang] Dr. Favour.",
  "foulness - The quality or condition of being foul.",
  "hedonic - 1. Pertaining to pleasure. 2. Of or relating to Hedonism or the Hedonic sect.",
  "syndicalist - One who advocates or practices syndicalism. --Syn`dic*al*is\"tic (#), a.",
  "russophobe - One who dreads Russia or Russian influence. [Words sometimes found in the newspapers.]",
  "glyptic - 1. Of or pertaining to gem engraving. 2. (Min.)  Figured; marked as with figures.",
  "gastrurous - Pertaining to the Gastrura.",
  "moll - Minor; in the minor mode; as, A moll, that is, A minor.",
  "shepherdism - Pastoral life or occupation.",
  "archducal - Of or pertaining to an archduke or archduchy.",
  "attributively - In an attributive manner.",
  "sluttery - The qualities and practices of a slut; sluttishness; slatternlines. Drayton.",
  "pantometer - An instrument for measuring angles for determining elevations, distances, etc.",
  "exactress - A woman who is an exactor. [R.] B. Jonson.",
  "morbosity - A diseased state; unhealthiness. [R.] Sir T. Browne.",
  "nephelodometer - An instrument for reckoning the distances or velocities of clouds.",
  "gonoph - A pickpocket or thief. [Eng. Slang] Dickens.",
  "diswont - To deprive of wonted usage; to disaccustom. [R.] Bp. Hall.",
  "viticulturist - One engaged in viticulture.",
  "noninhabitant - One who is not an inhabitant; a stranger; a foreigner; a nonresident.",
  "pirry - A rough gale of wind. [Obs.] Sir T. Elyot.",
  "ambi- - A prefix meaning about, around; -- used in words derived from the Latin.",
  "antisepalous - Standing before a sepal, or calyx leaf.",
  "ichthyopsida - A grand division of the Vertebrata, including the Amphibia and Fishes.",
  "self-condemnation - Condemnation of one's self by one's own judgment.",
  "squacco - A heron (Ardea comata) found in Asia, Northern Africa, and Southern Europe.",
  "oxyphony - Acuteness or shrillness of voice.",
  "trigastric - Having three bellies; -- said of a muscle. Dunglison.",
  "zantiot - A native or inhabitant of Zante, one of the Ionian Islands.",
  "vility - Vileness; baseness. [Obs.] Kennet.",
  "dissembling - That dissembles; hypocritical; false. -- Dis*sem\"bling*ly, adv.",
  "intersert - To put in between other things; to insert. [Obs.] Brerewood.",
  "bifoliate - Having two leaves; two-leaved.",
  "bellibone - A woman excelling both in beauty and goodness; a fair maid. [Obs.] Spenser.",
  "sudorific - Causing sweat; as, sudorific herbs. -- n.  A sudorific medicine. Cf. Diaphoretic.",
  "applicability - The quality of being applicable or fit to be applied.",
  "nebulated - Clouded with indistinct color markings, as an animal.",
  "kriegsspiel - A game of war, played for practice, on maps. Farrow.",
  "quadricornous - Having four horns, or hornlike organs; as, a quadricornous beetle.",
  "propugner - A defender; a vindicator. \"Zealous propugners.\" Gov. of Tongue.",
  "laidly - Ugly; loathsome. [Prov. Eng. & Scot.] This laidly and loathsome worm. W. Howitt.",
  "portesse - See Porteass. [Obs.] Tyndale.",
  "knighthead - A bollard timber. See under Bollard.",
  "knee-high - Rising or reaching upward to the knees; as, the water is knee- high.",
  "biography - 1. The written history of a person's life. 2. Biographical writings in general.",
  "insteep - To steep or soak; to drench. [R.] \"In gore he lay insteeped.\" Shak.",
  "light-heeled - Lively in walking or running; brisk; light-footed.",
  "corage - See Courage [Obs.] To Canterbury with full devout corage. Chaucer.",
  "ruffianly - Like a ruffian; bold in crimes; characteristic of a ruffian; violent; brutal.",
  "ophiological - Of or pertaining to ophiology.",
  "soutage - That in which anything is packed; bagging, as for hops. [Obs.] Halliwell.",
  "zaimet - A district from which a Zaim draws his revenue. Smart.",
  "tobie - A kind of inferior cigar of a long slender shape, tapered at one end. [Local, U. S.]",
  "limaceous - Pertaining to, or like, Limax, or the slugs.",
  "fulcible - Capable of being propped up. [Obs.] Cockeram.",
  "socager - A tennant by socage; a socman.",
  "diathermic - Affording a free passage to heat; as, diathermic substances. Melloni.",
  "scelestic - Evil; wicked; atrocious. [Obs.] \"Scelestic villainies.\" Feltham.",
  "explicator - One who unfolds or explains; an expounder; an explainer.",
  "intoxicatedness - The state of being intoxicated; intoxication; drunkenness. [R.]",
  "allomorphic - Of or pertaining to allomorphism.",
  "carborundum paper - Cloth or paper covered with powdered carborundum.",
  "explanatoriness - The quality of being explanatory.",
  "pentine - An unsaturated hydrocarbon, C5H8, of the acetylene series. Same as Valerylene.",
  "sermoning - The act of discoursing; discourse; instruction; preaching. [Obs.] Chaucer.",
  "buckshot - A coarse leaden shot, larger than swan shot, used in hunting deer and large game.",
  "cautioner - 1. One who cautions or advises. 2. (Scots Law)  A surety or sponsor.",
  "overhauling - A strict examination with a view to correction or repairs.",
  "peaky - 1. Having a peak or peaks. Tennyson. 2. Sickly; peaked. [Colloq.]",
  "hogger-pipe - The upper terminal pipe of a mining pump. Raymond.",
  "hygrology - The science which treats of the fluids of the body.",
  "ungainliness - The state or quality of being ungainly; awkwardness.",
  "publishable - Capable of being published; suitable for publication.",
  "quinazol - A complex nitrogenous base related to cinnoline. [Written also chinazol.]",
  "quadrilateralness - The property of being quadrilateral.",
  "parseeism - The religion and customs of the Parsees.",
  "irrefragability - The quality or state of being irrefragable; incapability of being refuted.",
  "snuffbox - A small box for carrying snuff about the person.",
  "wouldingness - Willingness; desire. [Obs.]",
  "nightgown - A loose gown used for undress; also, a gown used for a sleeping garnment.",
  "aldehydic - Of or pertaining to aldehyde; as, aldehydic acid. Miller.",
  "stercorary - A place, properly secured from the weather, for containing dung.",
  "augustness - The quality of being august; dignity of mien; grandeur; magnificence.",
  "lig - To recline; to lie still. [Obs. or Scot.] Chaucer. Spenser.",
  "demolitionist - A demolisher. [R.] Carlyle.",
  "assigner - One who assigns, appoints, allots, or apportions.",
  "primipilar - Of or pertaining to the captain of the vanguard of a Roman army. Barrow.",
  "immailed - Wearing mail or armor; clad of armor. W. Browne.",
  "baggager - One who takes care of baggage; a camp follower. [Obs.] Sir W. Raleigh.",
  "troglodytic - Of or pertaining to a troglodyte, or dweller in caves.",
  "pentaglot - A work in five different tongues.",
  "nummulite - A fossil of the genus Nummulites and allied genera.",
  "overruling - Exerting controlling power; as, an overruling Providence. -- O`ver*rul\"ing*ly, adv.",
  "postulated - Assumed without proof; as, a postulated inference. Sir T. Browne.",
  "precautionary - Of or pertaining to precaution, or precautions; as, precautionary signals.",
  "sextic - Of the sixth degree or order. -- n. (Alg.)  A quantic of the sixth degree.",
  "auctary - That which is superadded; augmentation. [Obs.] Baxter.",
  "alexipharmical - Expelling or counteracting poison; antidotal.",
  "preterient - Passed through; antecedent; previous; as, preterient states. [R.]",
  "frugalness - , n. Quality of being frugal; frugality.",
  "chess-apple - The wild service of Europe (Purus torminalis).",
  "lactarene - A preparation of casein from milk, used in printing calico.",
  "burinist - One who works with the burin. For. Quart. Rev.",
  "banging - Huge; great in size. [Colloq.] Forby.",
  "urinate - To discharge urine; to make water.",
  "blowess - A prostitute; a courtesan; a strumpet. [Low] Smart.",
  "disvantageous - Disadvantageous. [Obs.] \"Disadvantageous ground.\" Drayton.",
  "cancrine - Having the qualities of a crab; crablike.",
  "detumescence - Diminution of swelling; subsidence of anything swollen. [R.] Cudworth.",
  "displenish - To deprive or strip, as a house of furniture, or a barn of stock. [Scot.]",
  "stelleridean - A starfish, or brittle star.",
  "presurmise - A surmise previously formed. Shak.",
  "metanephritic - Of or pertaining to the metanephros.",
  "nodulose - Having small nodes or knots; diminutively nodose.",
  "kingston - The black angel fish. See Angel fish, under Angel.",
  "conglobation - 1. The act or process of forming into a ball. Sir T. Browne. 2. A round body.",
  "ashery - 1. A depository for ashes. 2. A place where potash is made.",
  "-ess - A suffix used to form feminine nouns; as, actress, deaconess, songstress.",
  "mellowness - Quality or state of being mellow.",
  "corniculum - A small hornlike part or process.",
  "edulious - Edible. [Obs.] \"Edulious pulses.\" Sir T. Browne.",
  "hatable - Capable of being, or deserving to be, hated; odious; detestable.",
  "oftentimes - Frequently; often; many times. Wordsworth.",
  "pauperization - The act or process of reducing to pauperism. C. Kingsley.",
  "proslavery - Favoring slavery. -- n.  Advocacy of slavery.",
  "discapacitate - To deprive of capacity; to incapacitate. [R.]",
  "anights - In the night time; at night. [Archaic] Does he hawk anights still Marston.",
  "anantherous - Destitute of anthers. Gray.",
  "foody - Eatable; fruitful. [R.] Chapman.",
  "eudaemonistic - Of or pertaining to eudemonism.",
  "tittuppy - Given to tittuping; gay; lively; prancing; also, shaky; unsteady.",
  "envier - One who envies; one who desires inordinately what another possesses.",
  "soaker - 1. One who, or that which, soaks. 2. A hard drinker. [Slang] South.",
  "ingeny - Natural gift or talent; ability; wit; ingenuity. [Obs.] [Written also ingenie.] Becon.",
  "delineatory - That delineates; descriptive; drawing the outline; delineating.",
  "childlessness - The state of being childless.",
  "distinguishably - So as to be distinguished.",
  "outsit - To remain sitting, or in session, longer than, or beyond the time of; to outstay.",
  "ineffaceable - Incapable of being effaced; indelible; ineradicable.",
  "pansclavic - See Panslavic, Panslavism, etc.",
  "brad awl - A straight awl with chisel edge, used to make holes for brads, etc. Weale.",
  "acrase - 1. To craze. [Obs.] Grafton. 2. To impair; to destroy. [Obs.] Hacket.",
  "lunt - 1. The match cord formerly used in firing cannon. 2. A puff of smoke. [Scotch.] Burns.",
  "petronel - A sort of hand cannon, or portable firearm, used in France in the 15th century.",
  "proximad - Toward a proximal part; on the proximal side of; proximally.",
  "hypnum - The largest genus of true mosses; feather moss.",
  "watchmaker - One whose occupation is to make and repair watches.",
  "unitable - Capable of union by growth or otherwise. Owen.",
  "penner - 1. One who pens; a writer. Sir T. North. 2. A case for holding pens. [Obs.]",
  "dispraiser - One who blames or dispraises.",
  "marai - A sacred inclosure or temple; -- so called by the islanders of the Pacific Ocean.",
  "animator - One who, or that which, animates; an animater. Sir T. Browne.",
  "renewable - Capable of being renewed; as, a lease renewable at pleasure. Swift.",
  "peristerion - The herb vervain (Verbena officinalis).",
  "unreprievable - Not capable of being reprieved. Shak.",
  "marble-edged - Having the edge veined or spotted with different colors like marble, as a book.",
  "egg squash - A variety of squash with small egg-shaped fruit.",
  "polypterus - An African genus of ganoid fishes including the bichir.",
  "inexpressibles - Breeches; trousers. [Colloq. or Slang] Ld. Lytton.",
  "tiger-footed - Hastening to devour; furious.",
  "deonerate - To unload; to disburden. [Obs.] Cockeram.",
  "gypsography - The act or art of engraving on gypsum.",
  "tablebook - A tablet; a notebook. Put into your tablebook whatever you judge worthly. Dryden.",
  "malefic - Doing mischief; causing harm or evil; nefarious; hurtful. [R.] Chaucer.",
  "matrimonious - Matrimonial. [R.] Milton.",
  "prelook - To look forward. [Obs.] Surrey.",
  "synanthesis - The simultaneous maturity of the anthers and stigmas of a blossom. Gray.",
  "siphonophoran - Belonging to the Siphonophora. -- n.  One of the Siphonophora.",
  "topstone - A stone that is placed on the top, or which forms the top.",
  "gooroo - A spiritual teacher, guide, or confessor amoung the Hindoos. Malcom.",
  "screwer - One who, or that which, screws.",
  "oscitation - The act of yawning or gaping. Addison.",
  "firmitude - Strength; stability. [Obs.] Bp. Hall.",
  "invariability - The quality of being invariable; invariableness; constancy; uniformity.",
  "jeel - A morass; a shallow lake. [Written also jhil.] [India] Whitworth.",
  "peribolos - In ancient architecture, an inclosed court, esp., one surrounding a temple.",
  "buzzingly - In a buzzing manner; with a buzzing sound.",
  "above-named - Mentioned or named before; aforesaid.",
  "zamite - A fossil cycad of the genus Zamia.",
  "discinct - Ungirded; loosely dressed. [R.] Sir W. Scott.",
  "decametre - A measure of length in the metric system; ten meters, equal to about 393.7 inches.",
  "singeress - A songstress. [Obs.] Wyclif.",
  "metaphysis - Change of form; transformation.",
  "gaussage - The intensity of a magnetic field expressed in C.G.S. units, or gausses.",
  "epidemiological - Connected with, or pertaining to, epidemiology.",
  "dogmatics - The science which treats of Christian doctrinal theology.",
  "pressive - Pressing; urgent; also, oppressive; as, pressive taxation. [R.] Bp. Hall.",
  "risker - One who risks or hazards. Hudibras.",
  "bonibell - See Bonnibel. [Obs.] Spenser.",
  "-escent - A suffix signifying beginning, beginning to be; as, adolescent, effervescent, etc.",
  "objectless - Having no object; purposeless.",
  "annularity - Annular condition or form; as, the annularity of a nebula. J. Rogers.",
  "expiator - One who makes expiation or atonement.",
  "clifted - Broken; fissured. Climb the Andeclifted side. Grainger.",
  "phiz - The face or visage. [Colloq.] Cowper.",
  "sugarplum - A kind of candy or sweetneat made up in small balls or disks.",
  "overofficious - Too busy; too ready to intermeddle; too officious. Collier.",
  "subterranity - A place under ground; a subterrany. [Obs.] Sir T. Browne.",
  "overbold - Excessively or presumptuously bold; impudent. Shak. -- O\"ver*bold\"ly, adv.",
  "enravish - To transport with delight; to enrapture; to fascinate. Spenser.",
  "verminly - Resembling vermin; in the manner of vermin. [Obs.] Gauden.",
  "casse paper - Broken paper; the outside quires of a ream.",
  "hyperorthodoxy - Orthodoxy pushed to excess.",
  "fulminatory - Thundering; striking terror. Cotgrave.",
  "plainant - One who makes complaint; the plaintiff. [Obs.]",
  "tentage - A collection of tents; an encampment. [Obs.] Drayton.",
  "shoading - The tracing of veins of metal by shoads. [Written also shoding.] Pryce.",
  "orbic - Spherical; orbicular; orblike; circular. [R.] Bacon.",
  "suster - Sister. [Obs.] Chaucer. There are seven sustren, that serve truth ever. Piers Plowman.",
  "twattler - One who twattles; a twaddler.",
  "deminatured - Having half the nature of another. [R.] Shak.",
  "heptoic - Pertaining to, or derived from, heptane; as, heptoic acid.",
  "astronomize - To study or to talk astronomy. [R.] They astronomized in caves. Sir T. Browne.",
  "disembossom - To separate from the bosom. [R.] Young.",
  "patchy - Full of, or covered with, patches; abounding in patches.",
  "bihydroguret - A compound of two atoms of hydrogen with some other substance. [Obs.]",
  "twelvepence - A shilling sterling, being about twenty-four cents.",
  "astheny - Want or loss of strength; debility; diminution of the vital forces.",
  "deplorate - Deplorable. [Obs.] A more deplorate estate. Baker.",
  "spiraea - A genus of shrubs or perennial herbs including the meadowsweet and the hardhack.",
  "vindicable - Capable of being vindicated. -- Vin`di*ca*bil\"i*ty, n.",
  "cutlery - 1. The business of a cutler. 2. Edged or cutting instruments, collectively.",
  "woofy - Having a close texture; dense; as, a woofy cloud. J. Baillie.",
  "quintuple-ribbed - The same as Quinquenerved.",
  "commatic - Having short clauses or sentences; brief; concise.",
  "antipole - The opposite pole; anything diametrically opposed. Geo. Eliot.",
  "hafter - A caviler; a wrangler. [Obs.] Baret.",
  "middlemost - Being in the middle, or nearest the middle; midmost.",
  "tutorship - The office, duty, or care of a tutor; guardianship; tutelage. Hooker.",
  "carotte - A cylindrical roll of tobacco; as, a carotte of perique.",
  "transpiratory - Of or relating to transpiration.",
  "solenette - A small European sole (Solea minuta).",
  "gallinaceous - Resembling the domestic fowls and pheasants; of or pertaining to the Gallinae.",
  "swearing - from Swear, v. Idle swearing is a cursedness. Chaucer.",
  "reimport - To import again; to import what has been exported; to bring back. Young.",
  "materialization - The act of materializing, or the state of being materialized.",
  "covenantor - The party who makes a covenant. Burrill.",
  "accusatival - Pertaining to the accusative case.",
  "foxearth - A hole in the earth to which a fox resorts to hide himself.",
  "sea pear - A pedunculated ascidian of the genus Boltonia.",
  "conversableness - The quality of being conversable; disposition to converse; sociability.",
  "intensively - In an intensive manner; by increase of degree. Abp. Bramhall.",
  "driftless - Having no drift or direction; without aim; purposeless.",
  "subdeaconship - The order or office of subdeacon.",
  "substantiveness - The quality or state of being substantive.",
  "umbriferous - Casting or making a shade; umbrageous. -- Um*brif\"er*ous*ly, adv.",
  "slugabed - One who indulges in lying abed; a sluggard. [R.] \"Fie, you slugabed!\" Shak.",
  "cochleare - 1. A spoon. Andrews. 2. (Med)  A spoonful. Dungleson.",
  "pestillation - The act of pounding and bruising with a pestle in a mortar. Sir T. Browne.",
  "mischiefful - Mischievous. [Obs.] Foote.",
  "colophonite - A coarsely granular variety of garnet.",
  "saccule - A little sac; specifically, the sacculus of the ear.",
  "sannup - A male Indian; a brave; -- correlative of squaw.",
  "subriguous - Watered or wet beneath; well-watered. [Obs.] Blount.",
  "puzzledom - The domain of puzzles; puzzles, collectively. C. Kingsley.",
  "affirmant - 1. One who affirms or asserts. 2. (Law)  One who affirms of taking an oath.",
  "rubian - One of several color-producing glycosides found in madder root.",
  "suppressive - Tending to suppress; subduing; concealing.",
  "chrysosperm - The seed of gold; a means of creating gold. [Obs.] B. Jonson.",
  "philomathy - The love of learning or letters.",
  "aroideous - Belonging to, or resembling, the Arum family of plants.",
  "torpedo boom - A spar formerly carried by men-of-war, having a torpedo on its end.",
  "decagynian - Belonging to the Decagynia; having ten styles.",
  "school-teacher - One who teaches or instructs a school. -- School\"-teach`ing, n.",
  "besetter - One who, or that which, besets.",
  "sharpsaw - The great titmouse; -- so called from its harsh call notes. [Prov. Eng.]",
  "unprayed - Not prayed for. [Obs.] Sir T. More.",
  "drie - To endure. [Obs.] So causeless such drede for to drie. Chaucer.",
  "araneiform - Having the form of a spider. Kirby.",
  "literalist - One who adheres to the letter or exact word; an interpreter according to the letter.",
  "bibbs - Pieces of timber bolted to certain parts of a mast tp support the trestletrees.",
  "drooper - One who, or that which, droops.",
  "smeir - A salt glaze on pottery, made by adding common salt to an earthenware glaze.",
  "vaccinator - One who, or that which, vaccinates.",
  "slavey - A maidservant. [Colloq. & Jocose Eng.]",
  "self-fertilized - Fertilized by pollen from the same flower.",
  "nearhand - Near; near at hand; closely. [Obs. or Scot.] Bacon.",
  "heatingly - In a heating manner; so as to make or become hot or heated.",
  "transnatation - The act of swimming across, as a river.",
  "phylarchy - The office of a phylarch; government of a class or tribe.",
  "phonotypic - Of or pertaining to phonotypy; as, a phonotypic alphabet.",
  "tungstenic - Of or pertaining to tungsten; containing tungsten; as, tungstenic ores. [R.]",
  "frangible - Capable of being broken; brittle; fragile; easily broken.",
  "crystallographical - Pertaining to crystallography.",
  "chrysocolla - A hydrous silicate of copper, occurring massive, of a blue or greenish blue color.",
  "petitioning - The act of presenting apetition; a supplication.",
  "cunningness - Quality of being cunning; craft.",
  "strepsipteran - One of the Strepsiptera.",
  "cumulus - One of the four principal forms of clouds. SeeCloud.",
  "theomancy - A kind of divination drawn from the responses of oracles among heathen nations.",
  "incorruptibility - The quality of being incorruptible; incapability of corruption. Holland.",
  "mercenariness - The quality or state of being mercenary; venality. Boyle.",
  "autopneumatic - Acting or moving automatically by means of compressed air.",
  "defeasanced - Liable to defeasance; capable of being made void or forfeited.",
  "viscounty - The quality, rank, or office of a viscount.",
  "friendless - Destitute of friends; forsaken. -- Friend\"less*ness, n.",
  "inconcerning - Unimportant; trifling. [Obs.] \"Trifling and inconcerning matters.\" Fuller.",
  "tritheite - A tritheist. [Obs.] E. Phillips.",
  "ephippial - Saddle-shaped; occupying an ephippium. Dana.",
  "plurifoliolate - Having several or many leaflets.",
  "musculophrenic - Pertaining to the muscles and the diaphragm; as, the musculophrenic artery.",
  "outhaul - A rope used for hauling out a sail upon a spar; -- opposite of inhaul.",
  "deontology - The science relat J. Bentham.",
  "wishly - According to desire; longingly; with wishes. [Obs. or Prov. Eng.] Chapman.",
  "lollardy - The doctrines or principles of the Lollards.",
  "catchable - Capable of being caught. [R.]",
  "omelet - Eggs beaten up with a little flour, etc., and cooked in a frying pan; as, a plain omelet.",
  "addible - Capable of being added. \"Addible numbers.\" Locke.",
  "architectonics - The science of architecture.",
  "postillation - The act of postillating; exposition of Scripture in preaching.",
  "glastonbury thorn - A variety of the common hawthorn. Loudon.",
  "hexavalent - Having a valence of six; -- said of hexads.",
  "indeprehensible - Incapable of being found out. Bp. Morton.",
  "atrabilarious - Affected with melancholy; atrabilious. Arbuthnot.",
  "damourite - A kind of Muscovite, or potash mica, containing water.",
  "flaminical - Pertaining to a flamen. Milton.",
  "predigest - To subject (food) to predigestion or artificial digestion.",
  "clem - To starve; to famish. [Obs.] B. Jonson.",
  "syruped - Moistened, covered, or sweetened with sirup, or sweet juice.",
  "flushness - The state of being flush; abundance.",
  "depiction - A painting or depicting; a representation.",
  "dextrally - (adv. Towards the right; as, the hands of a watch rotate dextrally.",
  "barbastel - A European bat (Barbastellus communis), with hairy lips.",
  "darby - A plasterer's float, having two handles; -- used in smoothing ceilings, etc.",
  "pronunciamento - A proclamation or manifesto; a formal announcement or declaration.",
  "culinarily - In the manner of a kitchen; in connection with a kitchen or cooking.",
  "bagreef - The lower reef of fore and aft sails; also, the upper reef of topsails. Ham. Nav. Encyc.",
  "nepeta - A genus of labiate plants, including the catnip and ground ivy.",
  "mittened - Covered with a mitten or mittens. \"Mittened hands.\" Whittier.",
  "terricolae - A division of annelids including the common earthworms and allied species.",
  "fingrigo - A prickly, climbing shrub of the genus Pisonia. The fruit is a kind of berry.",
  "microlestes - An extinct genus of small Triassic mammals, the oldest yet found in European strata.",
  "hymnody - Hymns, considered collectively; hymnology.",
  "maxilliform - Having the form, or structure, of a maxilla.",
  "hylic - Of or pertaining to matter; material; corporeal; as, hylic influences.",
  "jehu - A coachman; a driver; especially, one who drives furiously. [Colloq.]",
  "presentific - Making present. [Obs.] -- Pres`en*tif\"ic*ly, adv. [Obs.] Dr. H. More.",
  "hungerer - One who hungers; one who longs. Lamb.",
  "terebratulid - Any species of Terebratula or allied genera. Used also adjectively.",
  "velocipedist - One who rides on a velocipede.",
  "self-esteem - The holding a good opinion of one's self; self-complacency.",
  "bloodlet - bleed; to let blood. Arbuthnot.",
  "cock-a-hoop - Boastful; defiant; exulting. Also used adverbially.",
  "craspedote - Of or pertaining to the Craspedota.",
  "tighter - A ribbon or string used to draw clothes closer. [Obs.]",
  "unbeknown - Not known; unknown. [Colloq.]",
  "prevalently - In a prevalent manner. Prior.",
  "uncared - Not cared for; not heeded; -- with for.",
  "photozincograph - A print made by photozincography. -- Pho`to*zin`co*graph\"ic, a.",
  "nash - Firm; stiff; hard; also, chilly. [Prov. Eng.] Halliwell.",
  "amphitheatrical - Of, pertaining to, exhibited in, or resembling, an amphitheater.",
  "overperch - To perch upon; to fly over. [Obs.] Shak.",
  "senhora - A Spanish title of courtesy given to a lady; Mrs.; Madam; also, a lady.",
  "entophytic - Of or pertaining to entophytes; as, an entophytic disease.",
  "gantline - A line rigged to a mast; -- used in hoisting rigging; a girtline.",
  "equicrescent - Increasing by equal increments; as, an equicrescent variable.",
  "cheiropterous - Belonging to the Cheiroptera, or Bat family.",
  "alcohometric - Same as Alcoholometer, Alcoholometric.",
  "pharmacopolist - One who sells medicines; an apothecary.",
  "millionairess - A woman who is a millionaire, or the wife of a millionaire. [Humorous] Holmes.",
  "podder - One who collects pods or pulse.",
  "strophic - Pertaining to, containing, or consisting of, strophes.",
  "stem-winding - Wound by mechanism connected with the stem; as, a stem-winding watch.",
  "advertent - Attentive; heedful; regardful. Sir M. Hale. -- Ad*vert\"ent*ly, adv.",
  "sticktail - The ruddy duck. [Local, U.S.]",
  "minionly - Like a minion; daintily. Camden.",
  "amygdalin - A glucoside extracted from bitter almonds as a white, crystalline substance.",
  "cowleech - One who heals disease of cows; a cow doctor.",
  "empoisonment - The act of poisoning. Bacon.",
  "ducal - Of or pertaining to a duke. His ducal cap was to be exchanged for a kingly crown. Motley.",
  "deceptious - Tending deceive; delusive. [R.] As if those organs had deceptious functions. Shak.",
  "supervention - The act of supervening. Bp. Hall.",
  "institutively - In conformity with an institution. Harrington.",
  "long-tongued - 1. Having a long tongue. 2. Talkative; babbling; loquacious. Shak.",
  "oneiromancy - Divination by means of dreams. De Quincey.",
  "irregulate - To make irregular; to disorder. [Obs.] Sir T. Browne.",
  "flusteration - The act of flustering, or the state of being flustered; fluster. [Colloq.]",
  "conjunctivitis - Inflammation of the conjunctiva.",
  "pericranium - The periosteum which covers the cranium externally; the region around the cranium.",
  "whiterump - The American black-tailed godwit.",
  "biplicity - The state of being twice folded; reduplication. [R.] Bailey.",
  "chachalaca - The texan guan (Ortalis vetula). [written also chiacalaca.]",
  "zooesperm - One of the spermatic particles; spermatozoid.",
  "awayward - Turned away; away. [Obs.] Chaucer.",
  "intermeddlesome - Inclined or disposed to intermeddle. -- In`ter*med\"dle*some*ness, n.",
  "carousing - That carouses; relating to a carouse.",
  "aland - On land; to the land; ashore. \"Cast aland.\" Sir P. Sidney.",
  "aphanitic - Resembling aphanite; having a very fine-grained structure.",
  "rockwood - Ligniform asbestus; also, fossil wood.",
  "demilancer - A soldier of light cavalry of the 16th century, who carried a demilance.",
  "almeh - An Egyptian dancing girl; an Alma. The Almehs lift their arms in dance. Bayard Taylor.",
  "maggotish - Full of whims or fancies; maggoty.",
  "rhomboid-ovate - Between rhomboid and ovate, or oval, in shape.",
  "inofficially - Without the usual forms, or not in the official character.",
  "thrackscat - Metal still in the mine. [Obs.]",
  "disgruntle - To dissatisfy; to disaffect; to anger. [Colloq.]",
  "sheepbite - To bite or nibble like a sheep; hence, to practice petty thefts. [Obs.] Shak.",
  "contortionist - One who makes or practices contortions.",
  "clapcake - Oatmeal cake or bread clapped or beaten till it is thin. [Obs.] Halliwell.",
  "antiscorbutic - Counteracting scurvy. -- n.  A remedy for scurvy.",
  "defiliation - Abstraction of a child from its parents. Lamb.",
  "gratifier - One who gratifies or pleases.",
  "selenide - A binary compound of selenium, or a compound regarded as binary; as, ethyl selenide.",
  "donnat - See Do-naught. [Prov. Eng.] Halliwell.",
  "implorator - One who implores. [Obs.] Mere implorators of unholy suits. Shak.",
  "broken-bellied - Having a ruptured belly. [R.]",
  "fleshmonger - One who deals in flesh; hence, a pimp; a procurer; a pander. [R.] Shak.",
  "atlantides - The Pleiades or seven stars, fabled to have been the daughters of Atlas.",
  "pleuroptera - A group of Isectivora, including the colugo.",
  "shragger - One who lops; one who trims trees. [Obs.] Huloet.",
  "bloodstroke - Loss of sensation and motion from hemorrhage or congestion in the brain. Dunglison.",
  "mutch - The close linen or muslin cap of an old woman. [Prov. Eng. & Scot.]",
  "dissentation - Dissension. [Obs.] W. Browne.",
  "orchesography - A treatise upon dancing. [R.]",
  "matagasse - A shrike or butcher bird; -- called also mattages. [Prov. Eng.]",
  "perineal - Of or pertaining to the perineum.",
  "hippogriff - A fabulous winged animal, half horse and half griffin. Milton.",
  "internodal - Of or pertaining to internodes; intervening between nodes or joints.",
  "clayey - Consisting of clay; abounding with clay; partaking of clay; like clay.",
  "quirkish - , Consisting of quirks; resembling a quirk. Barrow.",
  "ethnarch - The governor of a province or people. Lew Wallace.",
  "iridian - Of or pertaining to the iris or rainbow.",
  "genterie - Nobility of birth or of character; gentility. [Obs.] Chaucer.",
  "disapprobatory - Containing disapprobation; serving to disapprove.",
  "asomatous - Without a material body; incorporeal. Todd.",
  "fecial - Pertaining to heralds, declarations of war, and treaties of peace; as, fecial law. Kent.",
  "odometrical - Of or pertaining to the odometer, or to measurements made with it.",
  "pultaceous - Macerated; softened; nearly fluid.",
  "practicality - The quality or state of being practical; practicalness.",
  "medal play - Play in which the score is reckoned by counting the number of strokes.",
  "decertation - Contest for mastery; contention; strife. [R.] Arnway.",
  "cornercap - The chief ornament. [Obs.] Thou makest the triumviry the cornercap of society. Shak.",
  "emacerate - To make lean or to become lean; to emaciate. [Obs.] Bullokar.",
  "exostome - The small aperture or foremen in the outer coat of the ovule of a plant.",
  "golgotha - Calvary. See the Note under Calvary.",
  "preceptial - Preceptive. [Obs.] [Passion] would give preceptial medicine to rage. Shak.",
  "episcopalianism - The doctrine and usages of Episcopalians; episcopacy.",
  "ploughwright - One who makes or repairs plows.",
  "solidification - Act of solidifying, or state of being solidified.",
  "detonator - One who, or that which, detonates.",
  "sulcated - Scored with deep and regular furrows; furrowed or grooved; as, a sulcated stem.",
  "withered - Faded; dried up; shriveled; wilted; wasted; wasted away. -- With\"ered*ness, n. Bp. Hall.",
  "morosely - Sourly; with sullen austerity.",
  "giantess - A woman of extraordinary size.",
  "vanning - A process by which ores are washed on a shovel, or in a vanner.",
  "disembrangle - To free from wrangling or litigation. [Obs.] Berkeley.",
  "metronomy - Measurement of time by an instrument.",
  "slubbing - from Slub. Slubbing billy, or Slubbing machine, the machine by which slubs are formed.",
  "patchingly - Knavishy; deceitfully. [Obs.]",
  "dysphoria - Impatience under affliction; morbid restlessness; dissatisfaction; the fidgets.",
  "socialistic - Pertaining to, or of the nature of, socialism.",
  "moonery - Conduct of one who moons. [R.]",
  "orcadian - Of or pertaining to the Orkney Islands.",
  "handbarrow - A frame or barrow, without a wheel, carried by hand.",
  "solacement - The act of solacing, or the state of being solaced; also, that which solaces. [R.]",
  "sea level - The level of the surface of the sea; any surface on the same level with the sea.",
  "relativeness - The state of being relative, or having relation; relativity.",
  "self-control - Control of one's self; restraint exercised over one's self; self-command.",
  "vitrescent - Capable of being formed into glass; tending to become glass.",
  "versionist - One who makes or favors a version; a translator. [R.]",
  "contradictorily - In a contradictory manner. Sharp.",
  "plasticity - 1. The quality or state of being plastic. 2. (Physiol.)  Plastic force. Dunglison.",
  "odometrous - Serving to measure distance on a road. [R.] Sydney Smith.",
  "inductively - By induction or inference.",
  "vulgarize - To make vulgar, or common. Exhortation vulgarized by low wit. V. Knox.",
  "rheumatismoid - Of or resembling rheum or rheumatism.",
  "posthumed - Posthumos. [Obs.] I. Watts. Fuller.",
  "jaw-fall - Depression of the jaw; hence, depression of spirits. M. Griffith (1660).",
  "administrate - To administer. [R.] Milman.",
  "tonsorial - Of or pertaining to a barber, or shaving.",
  "monophanous - Having one the same appearance; having a mutual resemblance.",
  "legioned - Formed into a legion or legions; legionary. Shelley.",
  "home-felt - Felt in one's own breast; inward; private. \"Home-felt quiet. Pope.",
  "speechmaker - One who makes speeches; one accustomed to speak in a public assembly.",
  "ruttle - A rattling sound in the throat arising from difficulty of breathing; a rattle. [Obs.]",
  "coworker - One who works with another; a co",
  "curbstone - A stone Curbstone broker.See under Broker.",
  "univariant - Having one degree of freedom or variability.",
  "boskage - Same as Boscage. Thridding the somber boskage of the wood. Tennyson.",
  "spongious - Somewhat spongy; spongelike; full of small cavities like sponge; as, spongious bones.",
  "hierogrammatist - A writer of hierograms; also, one skilled in hieroglyphics. Greenhill.",
  "knowleche - See Knowl, edge. We consider and knowleche that we have offended. Chaucer.",
  "typist - A person who operates a typewriting machine; a typewriter.",
  "alcoranist - One who adheres to the letter of the Koran, rejecting all traditions.",
  "pyromania - An insane disposition to incendiarism.",
  "sneb - To reprimand; to sneap. [Obs.] \"Scold and sneb the good oak.\" Spenser.",
  "efflagitate - To ask urgently. [Obs.] Cockeram.",
  "subderisorious - Ridiculing with moderation. [R.] Dr. H. More.",
  "tattlery - Idle talk or chat; tittle-tattle.",
  "shoddy fever - A febrile disease characterized by dyspnoa and bronchitis caused by inhaling dust.",
  "novilunar - Of or pertaining to the new moon. [R.]",
  "untwain - To rend in twain; to tear in two. [Obs.] Skelton.",
  "harvestless - Without harvest; lacking in crops; barren. \"Harvestless autumns.\" Tennyson.",
  "helminthological - Of or pertaining to helminthology.",
  "defendee - One who is defended. [R. & Ludicrous]",
  "lapidification - The act or process of lapidifying; fossilization; petrifaction.",
  "medle - To mix; to mingle; to meddle. [Written also medly.] [Obs.] Chaucer.",
  "cowled - Wearing a cowl; hooded; as, a cowled monk. \"That cowled churchman.\" Emerson.",
  "nasutness - Quickness of scent; hence, nice discernment; acuteness. [Obs.] Dr. H. More.",
  "tapster - One whose business is to tap or draw ale or other liquor.",
  "epitomator - An epitomist. Sir W. Hamilton.",
  "manteltree - The lintel of a fireplace when of wood, as frequently in early houses.",
  "accentually - In an accentual manner; in accordance with accent.",
  "fracho - A shallow iron pan to hold glass ware while being annealed.",
  "balefully - In a baleful manner; perniciously.",
  "translatorship - The office or dignity of a translator.",
  "inculcation - A teaching and impressing by frequent repetitions. Bp. Hall.",
  "sectoral - Of or pertaining to a sector; as, a sectoral circle.",
  "abstractitious - Obtained from plants by distillation. [Obs.] Crabb.",
  "interregency - An interregnum. [Obs.] Blount.",
  "monophyodont - Having but one set of teeth; -- opposed to diphyodont.",
  "tottery - Trembling or vaccilating, as if about to fall; unsteady; shaking. Johnson.",
  "swanmark - A mark of ownership cut on the bill or swan. [Eng.] Encyc. Brit.",
  "renate - Born again; regenerate; renewed. [Obs.] Beau & Fl.",
  "preferably - In preference; by choice. To choose Plautus preferably to Terence. Dennis.",
  "woolpack - A pack or bag of wool weighing two hundred and forty pounds.",
  "two-capsuled - Having two distinct capsules; bicapsular.",
  "transferrer - One who makes a transfer or conveyance.",
  "bruisewort - A plant supposed to heal bruises, as the true daisy, the soapwort, and the comfrey.",
  "balladry - Ballad poems; the subject or style of ballads. \"Base balladry is so beloved.\" Drayton.",
  "sinecurism - The state of having a sinecure.",
  "chirurgic - Surgical [Obs.] \"Chirurgical lore\" Longfellow.",
  "destroyable - Destructible. [R.] Plants . . . scarcely destroyable by the weather. Derham.",
  "amylaceous - Pertaining to starch; of the nature of starch; starchy.",
  "setout - A display, as of plate, equipage, etc.; that which is displayed. [Coloq.] Dickens.",
  "magniloquence - The quality of being magniloquent; pompous discourse; grandiloquence.",
  "effluviable - Capable of being given off as an effluvium. \"Effluviable matter.\" Boyle.",
  "agrostographic - Pertaining to agrostography.",
  "epipleural - Arising from the pleurapophysis of a vertebra. Owen.",
  "protuberate - To swell, or be prominent, beyond the adjacent surface; to bulge out. S. Sharp.",
  "connaturally - By the act of nature; originally; from birth. Sir M. Hale.",
  "hospitalize - To render (a building) unfit for habitation, by long continued use as a hospital.",
  "universologist - One who is versed in universology.",
  "coatless - Not wearing a coat; also, not possessing a coat.",
  "assimulation - Assimilation. [Obs.] Bacon.",
  "oilcloth - Cloth treated with oil or paint, and used for marking garments, covering flooors, etc.",
  "inauspicate - Inauspicious [Obs.] Sir G. Buck.",
  "disclaunder - To injure one's good name; to slander. [Obs.]",
  "complexionary - Pertaining to the complexion, or to the care of it. Jer. Taylor.",
  "inexhaustibility - The state or quality of being inexhaustible; abundance.",
  "stitcher - One who stitches; a seamstress.",
  "triseralous - Having three sepals, or calyx leaves.",
  "deconsecrate - To deprive of sacredness; to secularize. -- De*con`se*cra\"tion, n.",
  "conservant - Having the power or quality of conservation.",
  "stoichiometric - Of or pertaining to stoichiometry; employed in, or obtained by, stoichiometry.",
  "herbivorous - Eating plants; of or pertaining to the Herbivora.",
  "synantherous - Having the stamens united by their anthers; as, synantherous flowers.",
  "billman - One who uses, or is armed with, a bill or hooked ax. \"A billman of the guard.\" Savile.",
  "embryogeny - The production and development of an embryo.",
  "ooetooid - A half oviparous, or an oviparous, mammal; a marsupial or monotreme.",
  "gnathonical - Flattering; deceitful. [Obs.]",
  "confineless - Without limitation or end; boundless. Shak.",
  "intempestivity - Unseasonableness; untimeliness. [Obs.] Hales.",
  "excoct - To boil out; to produce by boiling. [Obs.] Bacon.",
  "feracity - The state of being feracious or fruitful. [Obs.] Beattie.",
  "hornblower - One who, or that which, blows a horn.",
  "coralliferous - Containing or producing coral.",
  "overvaluation - Excessive valuation; overestimate.",
  "dismarry - To free from the bonds of marriage; to divorce. [Obs.] Ld. Berners.",
  "intermundane - Being, between worlds or orbs. [R.] \"Intermundane spaces.\" Locke.",
  "obtusity - Obtuseness. Lond. Quart. Rev.",
  "ascription - The act of ascribing, imputing, or affirming to belong; also, that which is ascribed.",
  "saponacity - The quality or state of being saponaceous.",
  "bolection - A projecting molding round a panel. Same as Bilection. Gwilt.",
  "symbolization - The act of symbolizing; symbolical representation. Sir T. Browne.",
  "microseismology - Science or study of microseisms.",
  "abevacuation - A partial evacuation. Mayne.",
  "alveolate - Deeply pitted, like a honeycomb.",
  "overdrown - To wet or drench to excess. [Obs.] W. Browne.",
  "anergy - Lack of energy; inactivity. -- An*er\"gic (#), a.",
  "floricomous - Having the head adorned with flowers. [R.]",
  "disparkle - To scatter abroad. [Obs.] Holland.",
  "arpentator - The Anglicized form of the French arpenteur, a land surveyor. [R.]",
  "premonishment - Previous warning or admonition; forewarning. Sir H. Wotton.",
  "clandestinity - Privacy or secrecy. [R.]",
  "lapillation - The state of being, or the act of making, stony.",
  "laxativeness - The quality of being laxative.",
  "aponeurotomy - Dissection of aponeuroses.",
  "mity - Having, or abounding with, mites.",
  "oxbiter - The cow blackbird. [Local, U. S.]",
  "wrannock - The common wren. [Prov. Eng.]",
  "intercarpal - Between the carpal bone; as, intercarpal articulations, ligaments.",
  "necromancer - One who practices necromancy; a sorcerer; a wizard.",
  "dishful - As much as a dish holds when full.",
  "sovran - A variant of Sovereign. [Poetic] On thy bald, awful head, O sovran Blanc. Coleridge.",
  "catilinarian - Pertaining to Catiline, the Roman conspirator; resembling Catiline's conspiracy.",
  "filasse - Vegetable fiber, as jute or ramie, prepared for manufacture.",
  "eh - An expression of inquiry or slight surprise.",
  "beglerbeg - The governor of a province of the Ottoman empire, next in dignity to the grand vizier.",
  "beautifier - One who, or that which, beautifies or makes beautiful.",
  "inferiae - Sacrifices offered to the souls of deceased heroes or friends.",
  "sorehead - One who is disgruntled by a failure in politics, or the like. [Slang, U.S.]",
  "transumption - Act of taking from one place to another. [R.] South.",
  "immortification - Failure to mortify the passions. [R.] Jer. Taylor.",
  "eath - Easy or easily. [Obs.] \"Eath to move with plaints.\" Fairfax.",
  "viatic - Of or pertaining to a journey or traveling.",
  "increated - Uncreated; self-existent. [R.] Bright effincreate. Milton.",
  "overheat - To heat to excess; to superheat. Cowper.",
  "heteroclitic - Deviating from ordinary forms or rules; irregular; anomalous; abnormal.",
  "semuncia - A Roman coin equivalent to one twenty-fourth part of a Roman pound.",
  "osteopterygious - Having bones in the fins, as certain fishes.",
  "intendiment - Attention; consideration; knowledge; understanding. [Obs.] Spenser.",
  "decortication - The act of stripping off the bark, rind, hull, or outer coat.",
  "foolify - To make a fool of; to befool. [R.] Holland.",
  "venesection - The act or operation of opening a vein for letting blood; bloodletting; phlebotomy.",
  "scottering - The burning of a wad of pease straw at the end of harvest. [Prov. Eng.]",
  "intemperature - Intemperateness. [Obs.] Boyle.",
  "poorbox - A receptacle in which money given for the poor is placed.",
  "pratingly - With idle talk; with loquacity.",
  "compotier - A dish for holding compotes, fruit, etc.",
  "razorable - Ready for the razor; fit to be shaved. [R.] Shak.",
  "lapwork - Work in which one part laps over another. Grew.",
  "brigandage - Life and practice of brigands; highway robbery; plunder.",
  "spearwort - A name given to several species of crowfoot (Ranunculus) which have spear-shaped leaves.",
  "overwell - To overflow. R. D. Blackmore.",
  "idiophanous - Exhibiting interference figures without the aid of a polariscope, as certain crystals.",
  "deciduate - Possessed of, or characterized by, a decidua.",
  "alimonious - Affording food; nourishing. [R.] \"Alimonious humors.\" Harvey.",
  "lycopodite - An old name for a fossil club moss.",
  "mulierly - In the manner or condition of a mulier; in wedlock; legitimately. [Obs.]",
  "great-grandchild - The child of one's grandson or granddaughter.",
  "interspinal - Between spines; esp., between the spinous processes of the vertebral column.",
  "blastodermatic - Of or pertaining to the blastoderm.",
  "tusker - An elephant having large tusks.",
  "dewfall - The falling of dew; the time when dew begins to fall.",
  "balsamation - 1. The act of imparting balsamic properties. 2. The art or process of embalming.",
  "revendicate - To reclaim; to demand the restoration of. [R.] Vattel (Trans. ).",
  "conductress - A woman who leads or directs; a directress.",
  "crustalogical - Pertaining to crustalogy.",
  "fantigue - State of worry or excitment; fidget; ill humor. [Prov. Eng.] Dickens.",
  "fetidness - The quality or state of being fetid.",
  "divineress - A woman who divines. Dryden.",
  "sanders - An old name of sandalwood, now applied only to the red sandalwood. See under Sandalwood.",
  "seemingness - Semblance; fair appearance; plausibility. Sir K. Digby.",
  "pedalian - Relating to the foot, or to a metrical foot; pedal. [R.] Maunder.",
  "trialogue - A discourse or colloquy by three persons.",
  "undershoot - To shoot short of (a mark).",
  "instore - To store up; to inclose; to contain. [Obs.] Wyclif.",
  "analogize - To employ, or reason by, analogy.",
  "actinozoal - Of or pertaining to the Actinozoa.",
  "tartufish - Like a tartuffe; precise; hypocritical. Sterne.",
  "xylophilous - Of or pertaining to the xylophilans.",
  "imbruement - The act of imbruing or state of being imbrued.",
  "shaftment - A measure of about six inches. [Obs.]",
  "maleficent - Doing evil to others; harmful; mischievous.",
  "tranquilizer - One who, or that which, tranquilizes.",
  "poleless - Without a pole; as, a poleless chariot.",
  "encage - To confine in a cage; to coop up. Shak.",
  "lustrical - Pertaining to, or used for, purification.",
  "waped - Cast down; crushed by misery; dejected. [Obs.]",
  "pretensed - Pretended; feigned. [Obs.] -- Pre*tens\"ed*ly, adv. [Obs.]",
  "undisposedness - Indisposition; disinclination.",
  "xiphoid - (a) Like a sword; ensiform. (b) Of or pertaining to the xiphoid process; xiphoidian.",
  "encarnalize - To carnalize; to make gross. [R.] \"Encarnalize their spirits.\" Tennyson.",
  "oxymel - A mixture of honey, water, vinegar, and spice, boiled to a sirup. Sir T. Elyot.",
  "myelencephalous - Of or pertaining to the Myelencephala.",
  "jacobitism - The principles of the Jacobites. Mason.",
  "iconoclasm - The doctrine or practice of the iconoclasts; image breaking.",
  "housecarl - A household servant; also, one of the bodyguard of King Canute.",
  "scrupulize - To perplex with scruples; to regard with scruples. [Obs.] Bp. Montagu.",
  "smooth-chinned - Having a smooth chin; beardless. Drayton.",
  "hieromancy - Divination by observing the objects offered in sacrifice.",
  "morphinism - A morbid condition produced by the excessive or prolonged use of morphine.",
  "bebloody - To make bloody; to stain with blood. [Obs.] Sheldon.",
  "frightless - Free from fright; fearless. [Obs.]",
  "malignify - To make malign or malignant. [R.] \"A strong faith malignified.\" Southey.",
  "eventuate - To come out finally or in conclusion; to result; to come to pass.",
  "bettong - A small, leaping Australian marsupial of the genus Bettongia; the jerboa kangaroo.",
  "messinese - Of or pertaining to Messina, or its inhabitans.",
  "ramulus - A small branch, or branchlet, of corals, hydroids, and similar organisms.",
  "water bird - Any aquatic bird; a water fowl.",
  "tilt-mill - A mill where a tilt hammer is used, or where the process of tilting is carried on.",
  "unmaterial - Not material; immaterial. [Obs.] Daniel.",
  "mistradition - A wrong tradition. \"Monsters of mistradition.\" Tennyson.",
  "pourparler - A consultation preliminary to a treaty.",
  "stoniness - The quality or state of being stony.",
  "capnomor - A limpid, colorless oil with a peculiar odor, obtained from beech tar. Watts.",
  "wing-handed - Having the anterior limbs or hands adapted for flight, as the bats and pterodactyls.",
  "concubinate - Concubinage. [Obs.] Johnson.",
  "eaglewood - A kind of fragrant wood. See Agallochum.",
  "interjaculate - To ejaculate parenthetically. [R.] Thackeray.",
  "philostorgy - Natural affection, as of parents for their children. [R.]",
  "stupefiedness - Quality of being stupid.",
  "camelbacked - Having a back like a camel; humpbacked. Fuller.",
  "irremovable - Not removable; immovable; inflexible. Shak. -- Ir`re*mov\"a*bly, adv.",
  "roadmaster - One who has charge of the track; --called also roadmaster.",
  "labyrinthibranch - Of or pertaining to the Labyrinthici. -- n.  One of the Labyrinthici.",
  "macrurous - Of or pertaining to the Macrura; having a long tail.",
  "dichotomist - One who dichotomizes. Bacon.",
  "pou sto - A place to stand upon; a locus standi; hence, a foundation or basis for operations.",
  "mac - A prefix, in names of Scotch origin, signifying son.",
  "exactitude - The quality of being exact; exactness.",
  "airward - Toward the air; upward. [R.] Keats.",
  "wrathily - In a wrathy manner; very angrily; wrathfully. [Colloq.]",
  "ammonal - An explosive consisting of a mixture of powdered aluminium and nitrate of ammonium.",
  "blackguardly - In the manner of or resembling a blackguard; abusive; scurrilous; ruffianly.",
  "magically - In a magical manner; by magic, or as if by magic.",
  "phonological - Of or pertaining to phonology.",
  "chasable - Capable of being chased; fit for hunting. Gower.",
  "cassimere - A thin, twilled, woolen cloth, used for men's garments. [Written also kerseymere.]",
  "angling - The act of one who angles; the art of fishing with rod and line. Walton.",
  "blae - Dark blue or bluish gray; lead-colored. [Scot.]",
  "triableness - Quality or state of being triable.",
  "fistinut - A pistachio nut. [Obs.] Johnson.",
  "lugmark - A mark cut into the ear of an animal to identify it; an earmark.",
  "appallment - Depression occasioned by terror; dismay. [Obs.] Bacon.",
  "naturism - The belief or doctrine that attributes everything to nature as a sanative agent.",
  "distad - Toward a distal part; on the distal side of; distally.",
  "icefall - A frozen waterfall, or mass of ice resembling a frozen waterfall. Coleridge.",
  "griever - One who, or that which, grieves.",
  "pharmaceutist - One skilled in pharmacy; a druggist. See the Note under Apothecary.",
  "flabbiness - Quality or state of being flabby.",
  "demain - 1. Rule; management. [Obs.] Chaucer. 2. (Law)  See Demesne.",
  "paronymy - The quality of being paronymous; also, the use of paronymous words.",
  "fermentable - Capable of fermentation; as, cider and other vegetable liquors are fermentable.",
  "outdream - To pass, or escape, while dreaming. \"To oultdream dangers.\" Beau. & Fl.",
  "multinuclear - Containing many nuclei; as, multinuclear cells.",
  "epicentral - Arising from the centrum of a vertebra. Owen.",
  "ambassy - See Embassy, the usual spelling. Helps.",
  "unsocket - To loose or take from a socket.",
  "fickly - In a fickle manner. [Obs.] Pepys.",
  "ascessancy - See Acescency, Acescent. [Obs.]",
  "dumfound - To strike dumb; to confuse with astonishment. [Written also dumbfound.] Spectator.",
  "chandlery - Commodities sold by a chandler.",
  "inextricableness - The state of being inextricable.",
  "omnigenous - Consisting of all kinds. [R.]",
  "radiothorium - A radioactive substance apparently formed as a product from thorium.",
  "demissive - Downcast; submissive; humble. [R.] They pray with demissive eyelids. Lord (1630).",
  "impolarly - Not according to or in, the direction of the poles. [Obs.] Sir T. Browne.",
  "chablis - A white wine made near Chablis, a town in France.",
  "cylindrically - In the manner or shape of a cylinder; so as to be cylindrical.",
  "earshrift - A nickname for auricular confession; shrift. [Obs.] Cartwright.",
  "scrotocele - A rupture or hernia in the scrotum; scrotal hernia.",
  "crinet - A very fine, hairlike feather. Booth.",
  "excambion - Exchange; barter; -- used commonly of lands.",
  "interspinous - Between spines; esp., between the spinous processes of the vertebral column.",
  "subduer - One who, or that which, subdues; a conqueror. Spenser.",
  "variate - To alter; to make different; to vary.",
  "protectorship - , The office of a protector or regent; protectorate.",
  "appulsive - Striking against; impinging; as, the appulsive influence of the planets. P. Cyc.",
  "catechetically - In a catechetical manner; by question and answer.",
  "gopher wood - A species of wood used in the construction of Noah's ark. Gen. vi. 14.",
  "pneumoskeleton - A chitinous structure which supports the gill in some invertebrates.",
  "stepdaughter - A daughter of one's wife or husband by a former marriage.",
  "rabidly - In a rabid manner; with extreme violence.",
  "repellency - The principle of repulsion; the quality or capacity of repelling; repulsion.",
  "winebibber - One who drinks much wine. Prov. xxiii. 20. -- Wine\"bib`bing, n.",
  "susurrous - Whispering; rustling; full of whispering sounds. [R.]",
  "lentitude - Slowness; sluggishness. [Obs.]",
  "blastophoric - Relating to the blastophore.",
  "obeah - Same as Obi. -- a.  Of or pertaining to obi; as, the obeah man. B. Edwards.",
  "monasticism - The monastic life, system, or condition. Milman.",
  "depressant - An agent or remedy which lowers the vital powers.",
  "forslugge - To lsoe by idleness or slotch. [Obs.] Chaucer.",
  "chaps - The jaws, or the fleshy parts about them. See Chap. \"Open your chaps again.\" Shak.",
  "confiteor - A form of prayer in which public confession of sins is made."
]