export default [
  "tubeform - In the form of a tube; tubular; tubiform.",
  "anathematizer - One who pronounces an anathema. Hammond.",
  "seamstress - A woman whose occupation is sewing; a needlewoman.",
  "darrein - Last; as, darrein continuance, the last continuance.",
  "set-fair - In plastering, a particularly good troweled surface. Knight.",
  "brenningly - Burningly; ardently. [Obs.]",
  "melodist - A composer or singer of melodies.",
  "fatigable - Easily tired. [Obs.] Bailey.",
  "matureness - The state or quality of being mature; maturity.",
  "squarrulose - Somewhat squarrose; slightly squarrose. Gray.",
  "coptic - Of or pertaining to the Copts. -- n.  The language of the Copts.",
  "felsitic - relating to, composed of, or containing, felsite.",
  "elliptically - 1. In the form of an ellipse. 2. With a part omitted; as, elliptically expressed.",
  "wharfinger - A man who owns, or has the care of, a wharf.",
  "dolichocephalism - The quality or condition of being dolichocephalic.",
  "waxiness - Quality or state of being waxy.",
  "dilater - One who, or that which, dilates, expands, o r enlarges.",
  "malacissation - The act of making soft or supple. [Obs.] Bacon.",
  "saheb - A respectful title or appelation given to Europeans of rank. [India]",
  "ireful - Full of ire; angry; wroth. \"The ireful bastard Orleans.\" Shak. -- Ire\"ful*ly, adv.",
  "taverning - A feasting at taverns. [Obs.] \"The misrule of our tavernings.\" Bp. Hall.",
  "feese - the short run before a leap. [Obs.] Nares.",
  "neography - A new method or system of writing.",
  "onethe - Scarcely. See Unnethe. [Obs.] Chaucer.",
  "natrium - The technical name for sodium.",
  "dissimulour - A dissembler. [Obs.] Chaucer.",
  "remiges - The quill feathers of the wings of a bird.",
  "stromatic - Miscellaneous; composed of different kinds.",
  "nippitato - Strong liquor. [Old Cant] Beau. & Fl.",
  "angelicalness - The quality of being angelic; excellence more than human.",
  "demigrate - To emigrate. [Obs.] Cockeram.",
  "trevat - A weaver's cutting instrument; for severing the loops of the pile threads of velvet.",
  "galvanometry - The art or process of measuring the force of electric currents.",
  "trecentist - A member of the trecento, or an imitator of its characteristics.",
  "misrelation - Erroneous relation or narration. Abp. Bramhall.",
  "segnitude - Sluggishness; dullness; inactivity. [Obs.]",
  "minutia - A minute particular; a small or minor detail; -- used chiefly in the plural.",
  "fullonical - Pertaining to a fuller of cloth. [Obs.] Blount.",
  "proterandrous - Having the stamens come to maturity before the pistil; -- opposed to proterogynous.",
  "reattachment - The act of reattaching; a second attachment.",
  "maty - A native house servant in India. Balfour (Cyc. of India).",
  "multisect - Divided into many similar segments; -- said of an insect or myriapod.",
  "coessentiality - Participation of the same essence. Johnson.",
  "salesman - One who sells anything; one whose occupation is to sell goods or merchandise.",
  "volge - The common sort of people; the crowd; the mob. [Obs.] Fuller.",
  "gult - Guilt. See Guilt. [Obs.] Chaucer.",
  "libertinage - Libertinism; license. [R.]",
  "brownstone - A dark variety of sandstone, much used for building purposes.",
  "extemporal - Extemporaneous; unpremeditated. [Obs.] B. Jonson. -- Ex*tem\"po*ral*ly, adv. [Obs.]",
  "miscellane - A mixture of two or more sorts of grain; -- now called maslin and meslin. Bacon.",
  "self-centring - Centering in one's self.",
  "sheldaple - A chaffinch. [Written also sheldapple, and shellapple.]",
  "urodelian - Of or pertaining to the Urodela. -- n.  One of the Urodela.",
  "sinical - Of or pertaining to a sine; employing, or founded upon, sines; as, a sinical quadrant.",
  "tartarine - Potassium carbonate, obtained by the incineration of tartar. [Obs.]",
  "egestion - Act or process of egesting; a voiding. Sir M. Hale.",
  "feaberry - A gooseberry. [Prov. Eng.] Prior.",
  "psalmodize - To practice psalmody. \" The psalmodizing art.\" J. G. Cooper.",
  "twifallow - To plow, or fallow, a second time (land that has been once fallowed).",
  "tusky - Having tusks. \"The scar indented by the tusky oar.\" Dryden.",
  "tripersonal - Consisting of three persons. Milton.",
  "jimmy - A short crowbar used by burglars in breaking open doors. [Written also jemmy.]",
  "moselle - A light wine, usually white, produced in the vicinity of the river Moselle.",
  "contemplator - One who contemplates. Sir T. Browne.",
  "embranchment - The branching forth, as of trees.",
  "ploughhead - The clevis or draught iron of a plow.",
  "adiaphoristic - Pertaining to matters indifferent in faith and practice. Shipley.",
  "-est - A suffix used to form the superlative of adjectives and adverbs; as, smoothest; earl(y)iest.",
  "biradiated - Having two rays; as, a biradiate fin.",
  "mawk - 1. A maggot. [Scot.] 2. A slattern; a mawks. [Prov. Eng.]",
  "dispossessor - One who dispossesses. Cowley.",
  "abuseful - Full of abuse; abusive. [R.] \"Abuseful names.\" Bp. Barlow.",
  "demi-tasse - A small cup for, or of, black coffee.",
  "bridgetree - The beam which supports the spindle socket of the runner in a grinding mill. Knight.",
  "columbian - Of or pertaining to the United States, or to America.",
  "proxime - Next; immediately preceding or following. [Obs.]",
  "predictive - Foretelling; prophetic; foreboding. -- Pre*dict\"ive*ly, adv.",
  "latchkey - A key used to raise, or throw back, the latch of a door, esp. a night latch.",
  "cartographic - Of or pertaining to cartography.",
  "pudendum - The external organs of generation, especially of the female; the vulva.",
  "shrape - A place baited with chaff to entice birds. [Written also scrap.] [Obs.] Bp. Bedell.",
  "polygenous - Consisting of, or containing, many kinds; as, a polygenous mountain. Kirwan.",
  "waxworker - 1. One who works in wax; one who makes waxwork. 2. A bee that makes or produces wax.",
  "cyclobranchiate - Having the gills around the margin of the body, as certain limpets.",
  "aimer - One who aims, directs, or points.",
  "boycotter - A participant in boycotting.",
  "commonplaceness - The quality of being commonplace; commonness.",
  "hibernation - The act or state of hibernating. Evelyn.",
  "audibility - The quality of being audible; power of being heard; audible capacity.",
  "subcylindrical - Imperfectly cylindrical; approximately cylindrical.",
  "systematist - 1. One who forms a system, or reduces to system. 2. One who adheres to a system.",
  "prestidigitator - One skilled in legerdemain or sleight of hand; a juggler.",
  "longimanous - Having long hands. Sir T. Browne.",
  "carcanet - A jeweled chain, necklace, or collar. [Also written carkenet and carcant.] Shak.",
  "anamese - Of or pertaining to Anam, to southeastern Asia. -- n.  A native of Anam.",
  "gymnocyte - (Biol.) A cytode without a proper cell wall, but with a nucleus. Haeckel.",
  "areometrical - Pertaining to, or measured by, an areometer.",
  "admarginate - To write in the margin. [R.] Coleridge.",
  "disterminate - Separated by bounds. [Obs.] Bp. Hall.",
  "seismograph - An apparatus for registering the shocks and undulatory motions of earthquakes.",
  "pedality - The act of measuring by paces. [R.] Ash.",
  "varietas - A variety; -- used in giving scientific names, and often abbreviated to var.",
  "rebaptization - A second baptism. [Obs.] Hooker.",
  "exacuate - To whet or sharpen. [Obs.] B. Jonson. -- Ex*ac`u*a\"tion, n. [Obs.]",
  "usherdom - The office or position of an usher; ushership; also, ushers, collectively. [R.]",
  "romany - 1. A gypsy. 2. The language spoken among themselves by the gypsies. [Written also Rommany.]",
  "reducent - Tending to reduce. -- n.  A reducent agent.",
  "hine - A servant; a farm laborer; a peasant; a hind. [Obs.] Bailiff, herd, nor other hine. Chaucer.",
  "halfen - Wanting half its due qualities. [Obs.] Spencer.",
  "tubicolous - Inhabiting a tube; as, tubicolous worms.",
  "tattling - Given to idle talk; apt to tell tales. -- Tat\"tling*ly, adv.",
  "cockswain - The steersman of a boat; a petty officer who has charge of a boat and its crew.",
  "exhaustless - Not be exhausted; inexhaustible; as, an exhaustless fund or store.",
  "feudalize - To reduce toa feudal tenure; to conform to feudalism.",
  "polluting - Adapted or tending to pollute; causing defilement or pollution. -- Pol*lut\"ing*ly, adv.",
  "reclusory - The habitation of a recluse; a hermitage.",
  "lustrous - Bright; shining; luminous. \" Good sparks and lustrous.\" Shak. -- Lus\"trous*ly, adv.",
  "echinate - Set with prickles; prickly, like a hedgehog; bristled; as, an echinated pericarp.",
  "cubism - A movement or phase in post-impressionism (which see, below). - - Cu\"bist (#), n.",
  "circumvolation - The act of flying round. [R.]",
  "apple-faced - Having a round, broad face, like an apple. \"Apple-faced children.\" Dickens.",
  "awork - At work; in action. \"Set awork.\" Shak.",
  "marquess - A marquis. Lady marquess, a marchioness. [Obs.] Shak.",
  "ferriprussiate - A ferricyanate; a ferricyanide. [R.]",
  "unicellular - Having, or consisting of, but a single cell; as, a unicellular organism.",
  "hogging - Drooping at the ends; arching;-in distinction from sagging. Hogging frame. See Hogframe.",
  "pentremite - Any species of Pentremites.",
  "nidgery - A trifle; a piece of foolery. [Obs.] Skinner.",
  "saengerfest - A festival of singers; a German singing festival.",
  "restitutor - One who makes restitution. [R].",
  "launderer - One who follows the business of laundering.",
  "spectation - Regard; aspect; appearance. Harvey.",
  "specificness - The quality or state of being specific.",
  "cyclometry - The art of measuring circles.",
  "perienteron - The primitive perivisceral cavity.",
  "somniculous - Inclined to sleep; drowsy; sleepy. [Obs.]",
  "nuddle - To walk quickly with the head bent forward; -- often with along. [Prov. Eng.]",
  "streamlet - A small stream; a rivulet; a rill.",
  "cerused - Washed with a preparation of white lead; as, cerused face. Beau. & Fl.",
  "tinnock - The blue titmouse. [Prov. Eng.]",
  "earthwards - Toward the earth; -- opposed to heavenward or skyward.",
  "kirsome - Christian; christened. [Obs.] I am a true kirsome woman. Beau. & Fl.",
  "chlorate - A salt of chloric acid; as, chlorate of potassium.",
  "underlaid - Laid or placed underneath; also, having something laid or lying underneath.",
  "milkful - Full of milk; abounding with food. [R.] \"Milkful vales.\" Sylvester.",
  "renownful - Having great renown; famous. \"Renownful Scipio.\" Marston.",
  "oldness - The state or quality of being old; old age.",
  "foresignify - To signify beforehand; to foreshow; to typify. Milton.",
  "metabasis - 1. (Rhet.)  A transition from one subject to another. 2. (Med.)  Same as Metabola.",
  "wankle - Not to be depended on; weak; unstable. [Prov. Eng.] Grose.",
  "hippophile - One who loves horses. Holmes.",
  "dopper - An Anabaptist or Baptist. [Contemptuous] B. Jonson.",
  "connumeration - A reckoning together. [R.] Porson.",
  "adeptness - The quality of being adept; skill.",
  "appetize - To make hungry; to whet the appetite of. Sir W. Scott.",
  "redolency - The quality of being redolent; sweetness of scent; pleasant odor; fragrance.",
  "coenosarc - The common soft tissue which unites the polyps of a compound hydroid. See Hydroidea.",
  "hirtellous - Pubescent with minute and somewhat rigid hairs.",
  "susurration - A whispering; a soft murmur. \"Soft susurrations of the trees.\" Howell.",
  "cranked - Formed with, or having, a bend or crank; as, a cranked axle.",
  "foliosity - The ponderousness or bulk of a folio; voluminousness. [R.] De Quincey.",
  "photism - A luminous image or appearance of a hallucinatory character.",
  "heliotypic - Relating to, or obtained by, heliotypy.",
  "prandial - Of or pertaining to a repast, especially to dinner.",
  "monton - A heap of ore; a mass undergoing the process of amalgamation.",
  "houselessness - The state of being houseless.",
  "cummin - Same as Cumin. Ye pay tithe of mint, and cummin. Matt. xxiii. 23.",
  "inextinguishably - So as not to be extinguished; in an inextinguishable manner.",
  "selective - Selecting; tending to select. This selective providence of the Almighty. Bp. Hall.",
  "directness - The quality of being direct; straightness; straightforwardness; immediateness.",
  "togs - Clothes; garments; toggery. [Colloq. or Slang]",
  "requisitionist - One who makes or signs a requisition.",
  "unsitting - Not sitting well; unbecoming. [Obs.] \"Unsitting words.\" Sir T. More.",
  "camous - Flat; depressed; crooked; -- said only of the nose. [Obs.]",
  "phthisipneumonia - Pulmonary consumption.",
  "lenger - Longer; longest; -- obsolete compar. and superl. of long. Chaucer.",
  "detersiveness - The quality of cleansing.",
  "uncipher - To decipher; as, to uncipher a letter. [Obs.] Sir W. Temple.",
  "delapsion - A falling down, or out of place; prolapsion.",
  "nidification - The act or process of building a nest.",
  "avulse - To pluck or pull off. Shenstone.",
  "earthward - Toward the earth; -- opposed to heavenward or skyward.",
  "supersensitive - Excessively sensitive; morbidly sensitive. -- Su`per*sen\"si*tive*ness, n.",
  "pedesis - Same as Brownian movement, under Brownian.",
  "methodological - Of or pertaining to methodology.",
  "renneted - Provided or treated with rennet. [R.] \"Pressed milk renneted.\" Chapman.",
  "sulphureity - The quality or state of being sulphureous. [Obs.] B. Jonson.",
  "thymate - A compound of thymol analogous to a salt; as, sodium thymate.",
  "nystagmus - A rapid involuntary oscillation of the eyeballs.",
  "personalize - To make personal. \"They personalize death.\" H. Spencer.",
  "carnate - Invested with, or embodied in, flesh.",
  "shako - A kind of military cap or headress.",
  "chiliarchy - A body consisting of a thousand men. Mitford.",
  "discorrespondent - Incongruous. W. Montagu.",
  "thoroughsped - Fully accomplished; thoroughplaced. [R.] Swift.",
  "bear state - Arkansas; -- a nickname, from the many bears once inhabiting its forests.",
  "battering train - A train of artillery for siege operations.",
  "self-reliance - Reliance on one's own powers or judgment; self-trust.",
  "multicipital - Having many heads or many stems from one crown or root. Gray.",
  "disenthrone - To dethrone; to depose from sovereign authority. Milton.",
  "sandwort - Any plant of the genus Arenaria, low, tufted herbs (order Caryophyllace\\'91.)",
  "decerniture - A decree or sentence of a court. Stormonth.",
  "adagial - Pertaining to an adage; proverbial. \"Adagial verse.\" Barrow.",
  "contramure - An outer wall. [Obs.] Chambers.",
  "misbecoming - Unbecoming. Milton. -- Mis`be*com\"ing*ly, adv. -- Mis`be*com\"ing*ness, n. Boyle.",
  "sparlyre - The calf of the leg. [Obs.] Wyclif (Deut. xxviii. 35).",
  "reparel - A change of apparel; a second or different suit. [Obs.] Beau & Fl.",
  "shebang - A jocosely depreciative name for a dwelling or shop. [Slang,U.S.]",
  "conure - An American parrakeet of the genus Conurus. Many species are known. See Parrakeet.",
  "stormwind - A heavy wind; a wind that brings a storm; the blast of a storm. Longfellow.",
  "siliginose - Made of fine wheat. [Obs.] Bailey.",
  "furzy - bounding in, or overgrown with, furze; characterized by furze. Gay.",
  "dracontine - Belonging to a dragon. Southey.",
  "mynchery - A nunnery; -- a term still applied to the ruins of certain nunneries in England.",
  "copper-faced - Faced or covered with copper; as, copper-faced type.",
  "producibility - The quality or state of being producible. Barrow.",
  "forrill - Lambskin parchment; vellum; forel. McElrath.",
  "inhiation - A gaping after; eager desire; craving. [R.] Bp. Hall.",
  "pleurodynia - A painful affection of the side, simulating pleurisy, usually due to rheumatism.",
  "flavine - A yellow, crystalline, organic base, C13H12N2O, obtained artificially.",
  "wyla - A helmeted Australian cockatoo (Calyptorhynchus funereus); -- called also funeral cockatoo.",
  "discalceate - To pull off shoes or sandals from. [Obs.] Cockeram.",
  "oxamethylane - Methyl oxamate, obtained as a pearly white crystalline substance.",
  "poristical - Of or pertaining to a porism; of the nature of a porism.",
  "capacify - To quality. [R.] The benefice he is capacified and designed for. Barrow.",
  "slaughterman - One employed in slaughtering. Shak.",
  "airling - A thoughtless, gay person. [Obs.] \"Slight airlings.\" B. Jonson.",
  "nimbleness - The quality of being nimble; lightness and quickness in motion; agility; swiftness.",
  "phlogosis - Inflammation of external parts of the body; erysipelatous inflammation.",
  "molle - Lower by a semitone; flat; as, E molle, that is, E flat.",
  "workbox - A box for holding instruments or materials for work.",
  "allhallow eve - The evening before Allhallows. See Halloween.",
  "antimonsoon - The upper, contrary-moving current of the atmosphere over a monsoon.",
  "ministerially - In a ministerial manner; in the character or capacity of a minister.",
  "tinny - Pertaining to, abounding with, or resembling, tin. \"The tinny strand.\" Drayton.",
  "desinent - Ending; forming an end; lowermost. [Obs.] \"Their desinent parts, fish.\" B. Jonson.",
  "potulent - 1. Fit to drink; potable. [Obs.] Johnson. 2. Nearly drunk; tipsy. [Obs.]",
  "redness - The quality or state of being red; red color.",
  "toxic - Of or pertaining to poison; poisonous; as, toxic medicines.",
  "eyeleteer - A small, sharp-pointed instrument used in piercing eyelet holes; a stiletto.",
  "inspan - To yoke or harness, as oxen to a vehicle. [South Africa]",
  "stage fright - Nervousness felt before an audience.",
  "restoratively - In a restorative manner.",
  "haustellata - An artificial division of insects, including all those with a sucking proboscis.",
  "regratiatory - A returning or giving of thanks. [Obs.] Skelton.",
  "strengthless - Destitute of strength. Boyle.",
  "intersecant - Dividing into parts; crossing; intersecting.",
  "spleenish - Spleeny; affected with spleen; fretful. -- Spleen\"ish*ly, adv. -- Spleen\"ish*ness, n.",
  "peaking - 1. Mean; sneaking. [Vulgar] 2. Pining; sickly; peakish. [Colloq.]",
  "thumper - One who, or that which, thumps.",
  "sopor - Profound sleep from which a person can be roused only with difficulty.",
  "mydriatic - Causing dilatation of the pupil. -- n.  A mydriatic medicine or agent, as belladonna.",
  "disfashion - To disfigure. [Obs.] Sir T. More.",
  "disjuncture - The act of disjoining, or state of being disjoined; separation. Fuller.",
  "overshine - 1. To shine over or upon; to illumine. Shak. 2. To excel in shining; to outshine. Shak.",
  "unhingement - The act unhinging, or the state of being unhinged.",
  "externally - In an external manner; outwardly; on the outside; in appearance; visibly.",
  "enouncement - Act of enouncing; that which is enounced.",
  "discursus - Argumentation; ratiocination; discursive reasoning.",
  "electro-capillary - Pert. to, or caused by, electro-capillarity.",
  "epistolean - One who writes epistles; a correspondent. Mary Cowden Clarke.",
  "forefinger - The finger next to the thumb; the index.",
  "predesign - To design or purpose beforehand; to predetermine. Mitford.",
  "wildly - In a wild manner; without cultivation; with disorder; rudely; distractedly; extravagantly.",
  "fantod - State of worry or excitement; fidget; fuss; also, indisposition; pet; sulks. [Slang]",
  "abruption - A sudden breaking off; a violent separation of bodies. Woodward.",
  "reputeless - Not having good repute; disreputable; disgraceful; inglorius. [R.] Shak.",
  "antichristianism - Opposition or contrariety to the Christian religion.",
  "acanthocephala - A group of intestinal worms, having the proboscis armed with recurved spines.",
  "excamb - To exchange; -- used with reference to transfers of land.",
  "fuliginous - 1. Pertaining to soot; sooty; dark; dusky. 2. Pertaining to smoke; resembling smoke.",
  "orbitary - Situated around the orbit; as, the orbitary feathers of a bird.",
  "tetraxile - Having four branches diverging at right angles; -- said of certain spicules of sponges.",
  "solitarily - In a solitary manner; in solitude; alone. Mic. vii. 14.",
  "cerebroid - Resembling, or analogous to, the cerebrum or brain.",
  "indo-briton - A person born in India, of mixed Indian and British blood; a half-caste. Malcom.",
  "cosmological - Of or pertaining to cosmology.",
  "scaur - A precipitous bank or rock; a scar.",
  "atwite - To speak reproachfully of; to twit; to upbraid. [Obs.]",
  "discounter - One who discounts; a discount broker. Burke.",
  "interepimeral - Between the epimeral plates of insects and crustaceans.",
  "residuous - Remaining; residual. Landor.",
  "emburse - To furnish with money; to imburse. [Obs.]",
  "nondeciduate - Characterized by the absence of a decidua; indeciduate.",
  "seleniferous - Containing, or impregnated with, selenium; as, seleniferous pyrites.",
  "flutemouth - A fish of the genus Aulostoma, having a much elongated tubular snout.",
  "cephalotome - An instrument for cutting into the fetal head, to facilitate delivery.",
  "secularly - In a secular or worldly manner.",
  "reciprocalness - The quality or condition of being reciprocal; mutual return; alternateness.",
  "estatlich - Stately; dignified. [Obs.] Chaucer.",
  "forshape - To render misshapen. [Obs.] Gower.",
  "anniversarily - Annually. [R.] Bp. Hall.",
  "elaborator - One who, or that which, elaborates.",
  "pretenceless - See Pretense, Pretenseful, Pretenseless.",
  "overswell - To swell or rise above; to overflow. [R.] Shak.",
  "sophical - Teaching wisdom. [Obs.] S. Harris.",
  "pleonastical - Of or pertaining to pleonasm; of the nature of pleonasm; redundant.",
  "half-brother - A brother by one parent, but not by both.",
  "sleetch - Mud or slime, such as that at the bottom of rivers. [Scot.]",
  "dejeuner - A breakfast; sometimes, also, a lunch or collation.",
  "smegmatic - Being of the nature of soap; soapy; cleansing; detersive.",
  "holometabola - Those insects which have a complete metamorphosis; metabola.",
  "remast - To furnish with a new mast or set of masts.",
  "plastery - Of the nature of plaster. The stone . . . is a poor plastery material. Clough.",
  "woolliness - The quality or state of being woolly.",
  "bookplate - A label, placed upon or in a book, showing its ownership or its position in a library.",
  "bow-legged - Having crooked legs, esp. with the knees bent outward. Johnson.",
  "irradiant - Irradiating or illuminating; as, the irradiant moon. Boyse.",
  "femalize - To make, or to describe as, female or feminine. Shaftesbury.",
  "horologer - A maker or vender of clocks and watches; one skilled in horology.",
  "typhoon - A violent whirlwind; specifically, a violent whirlwind occurring in the Chinese seas.",
  "rhizopodous - Of or pertaining to the rhizopods.",
  "muskiness - The quality or state of being musky; the scent of musk.",
  "latirostrous - Having a broad beak. Sir T. Browne.",
  "four-poster - A large bedstead with tall posts at the corners to support curtains. [Colloq.]",
  "assai - A direction equivalent to very; as, adagio assai, very slow.",
  "voracity - The quality of being voracious; voraciousness.",
  "subcolumnar - Having an imperfect or interrupted columnar structure.",
  "spleuchan - A pouch, as for tobacco. [Scot.] Sir W. Scott.",
  "linchpin - A pin used to prevent the wheel of a vehicle from sliding off the axletree.",
  "labeler - One who labels. [Written also labeller.]",
  "water bear - Any species of Tardigrada, 2. See Illust. of Tardigrada.",
  "semibarbaric - Half barbarous or uncivilized; as, semibarbaric display.",
  "psora - A cutaneous disease; especially, the itch.",
  "protectionism - The doctrine or policy of protectionists. See Protection, 4.",
  "declarator - A form of action by which some right or interest is sought to be judicially declared.",
  "gemmate - Having buds; reproducing by buds.",
  "loke - A private path or road; also, the wicket or hatch of a door. [Prov. Eng.]",
  "semaphorist - One who manages or operates a semaphore.",
  "vegetous - Vigorous; lively; active; vegete. [Obs.] B. Jonson.",
  "archduchy - The territory of an archduke or archduchess. Ash.",
  "transformable - Capable of being transformed or changed.",
  "gove - A mow; a rick for hay. [Obs.] Tusser.",
  "reliquian - Of or pertaining to a relic or relics; of the nature of a relic. [R.]",
  "turbination - The act of spinning or whirling, as a top.",
  "loudness - The quality or state of being loud.",
  "secess - Retirement; retreat; secession. [Obs.] R. H. More.",
  "attractivity - The quality or degree of attractive power.",
  "incarnification - The act of assuming, or state of being clothed with, flesh; incarnation.",
  "insessor - One of the Insessores. The group includes most of the common singing birds.",
  "etypical - Diverging from, or lacking conformity to, a type.",
  "superregal - More than regal; worthy of one greater than a king. Waterland.",
  "aegrotat - A medical certificate that a student is ill.",
  "distressedness - A state of being distressed or greatly pained.",
  "feather-head - A frivolous or featherbrained person. [Colloq.] H. James.",
  "endophloeum - The inner layer of the bark of trees.",
  "ophiura - A genus of ophiurioid starfishes.",
  "impostress - A woman who imposes upon or deceives others. [R.] Fuller.",
  "incommutability - The quality or state of being incommutable.",
  "dipsosis - Excessive thirst produced by disease.",
  "stenting - An opening in a wall in a coal mine. [Written also stenton.] [Prov. Eng.] Halliwell.",
  "guly - Of or pertaining to gules; red. \"Those fatal guly dragons.\" Milton.",
  "chinaman - A native of China; a Chinese.",
  "astipulation - Stipulation; agreement. [Obs.] Bp. Hall.",
  "commissaryship - The office or employment of a commissary. Ayliffe.",
  "high-stomached - Having a lofty spirit; haughty. [Obs.] Shak.",
  "long-armed - Having long arms; as, the long-armed ape or gibbon.",
  "riggish - Like a rig or wanton. [Obs.] \"Riggish and unmaidenly.\" Bp. Hall.",
  "disshadow - To free from shadow or shade. [Obs.] G. Fletcher.",
  "indice - Index; indication. [Obs.] B. Jonson.",
  "anneloid - An animal resembling an annelid.",
  "finable - Liable or subject to a fine; as, a finable person or offense. Bacon.",
  "sterve - To die, or cause to die; to perish. See Starve. [Obs.] Chaucer. Spenser.",
  "prelature - The state or dignity of a prelate; prelacy. Milman.",
  "neurotomist - One who skilled in or practices neurotomy.",
  "caracul - Var. of Karakul, a kind of fur.",
  "megapolis - A metropolis. [Obs.] Sir T. Herbert.",
  "misgoverned - Ill governed, as a people; ill directed. \"Rude, misgoverned hands.\" Shak.",
  "autocratship - The office or dignity of an autocrat.",
  "pediculate - Of or pertaining to the Pediculati.",
  "quinquesyllable - A word of five syllables.",
  "suffossion - A digging under; an undermining. [R.] Bp. Hall.",
  "appanagist - A prince to whom an appanage has been granted.",
  "causator - One who causes. [R.] Sir T. Browne.",
  "appreciativeness - The quality of being appreciative; quick recognition of excellence.",
  "motherhood - The state of being a mother; the character or office of a mother.",
  "disordinate - Inordinate; disorderly. [Obs.] \"With disordinate gestures.\" Prynne.",
  "virescent - Beginning to be green; slightly green; greenish.",
  "steerable - Capable of being steered; dirigible.",
  "booser - A toper; a guzzler. See Boozer.",
  "pyrogenous - Produced by fire; igneous. Mantell. .",
  "dionaea - An insectivorous plant. See Venus's flytrap.",
  "ovipositing - The depositing of eggs, esp. by insects.",
  "expone - To expound; to explain; also, to expose; to imperil. [Old Eng. & Scotch] Drummond.",
  "traunter - Same as Tranter. [Obs. or Prov. Eng.]",
  "circumstant - Standing or placed around; surrounding. [R.] \"Circumstant bodies.\" Sir K. Digby.",
  "bloedite - A hydrous sulphate of magnesium and sodium.",
  "misdight - Arrayed, prepared, or furnished, unsuitably. [Archaic] Bp. Hall.",
  "glumly - In a glum manner; sullenly; moodily.",
  "expediate - To hasten; to expedite. [Obs.] \"To expediate their business.\" Sir E. Sandys.",
  "flosculous - Consisting of many gamopetalous florets.",
  "lavatic - Like lava, or composed of lava; lavic.",
  "churchy - Relating to a church; unduly fond of church forms. [Colloq.]",
  "emulsic - Pertaining to, or produced from, emulsin; as, emulsic acid. Hoblyn.",
  "pantophagist - A person or an animal that has the habit of eating all kinds of food.",
  "begirt - To encompass; to begird. Milton.",
  "misobserver - One who misobserves; one who fails to observe properly.",
  "sepsis - The poisoning of the system by the introduction of putrescent material into the blood.",
  "goring - A piece of canvas cut obliquely to widen a sail at the foot.",
  "undertakable - Capable of being undertaken; practicable.",
  "dermopterygii - A group of fishlike animals including the Marsipobranchiata and Leptocardia.",
  "enterer - One who makes an entrance or beginning. A. Seward.",
  "chivarros - Leggings. [Mex. & Southwestern U. S.]",
  "trirhomboidal - Having three rhombic faces or sides.",
  "quinque foliolate - Having five leaflets. Gray.",
  "aflow - Flowing. Their founts aflow with tears. R. Browning.",
  "baronetcy - The rank or patent of a baronet.",
  "runer - A bard, or learned man, among the ancient Goths. Sir W. Temple.",
  "malpais - The rough surface of a congealed lava stream. [Southwestern U. S.]",
  "hexastich - A poem consisting of six verses or lines.",
  "enthrallment - The act of enthralling, or state of being enthralled. See Inthrallment.",
  "papillomatous - Of, pertaining to, or consisting of, papillomata.",
  "rancidness - The quality of being rancid.",
  "shagged - Shaggy; rough. Milton. -- Shag\"ged*ness, n. Dr. H. More.",
  "urinative - Provoking the flow of urine; uretic; diuretic. [R.] Bacon.",
  "bay state - Massachusetts, which had been called the Colony of Massachusetts Bay; -- a nickname.",
  "luculently - In a luculent manner; clearly.",
  "alcoholature - An alcoholic tincture prepared with fresh plants. New Eng. Dict.",
  "daphnomancy - Divination by means of the laurel.",
  "karatas - A West Indian plant of the Pineapple family (Nidularium Karatas).",
  "spiroylous - Pertaining to, or designating, a substance now called salicylal. [Obs.]",
  "flocculence - The state of being flocculent.",
  "fraughtage - Freight; loading; cargo. [Obs.] Shak.",
  "pomiculture - The culture of fruit; pomology as an art.",
  "protectorless - Having no protector; unprotected.",
  "viduity - Widowhood. [R.] \"Chaste viduity.\" Ld. Ellenborough.",
  "obtruncate - To deprive of a limb; to lop. [R.]",
  "spicer - 1. One who seasons with spice. 2. One who deals in spice. [Obs.] Piers Plowman.",
  "consolable - Capable of receiving consolation.",
  "nontenure - A plea of a defendant that he did not hold the land, as affirmed.",
  "spearer - One who uses a spear; as, a spearer of fish.",
  "self-born - Born or produced by one's self.",
  "placement - 1. The act of placing, or the state of being placed. 2. Position; place.",
  "infestive - Having no mirth; not festive or merry; dull; cheerless; gloomy; forlorn. [R.]",
  "smoothness - Quality or state of being smooth.",
  "bonne - (F., prop. good woman.) A female servant charged with the care of a young child.",
  "corno inglese - A reed instrument, related to the oboe, but deeper in pitch; the English horn.",
  "exoptile - A name given by Lestiboudois to dicotyledons; -- so called because the plumule is naked.",
  "domesticant - Forming part of the same family. [Obs.] Sir E. Dering.",
  "metric ton - A weight of 1,000 kilograms, or 2,204.6 pounds avoirdupois.",
  "receptiveness - The quality of being receptive.",
  "acidulate - To make sour or acid in a moderate degree; to sour somewhat. Arbuthnot.",
  "impoisonment - The act of poisoning or impoisoning. [Obs.] Pope.",
  "repasture - Food; entertainment. [Obs.] Food for his rage, repasture for his den. Shak.",
  "styan - See Sty, a boil. [R.] De quincey.",
  "contriturate - To triturate; to pulverize. [R.]",
  "runology - The science of runes. -- Ru*nol\"o*gist, n.",
  "stalled - Put or kept in a stall; hence, fatted. \"A stalled ox.\" Prov. xv. 17.",
  "bluestockingism - The character or manner of a bluestocking; female pedantry. [Colloq.]",
  "decrepitation - The act of decrepitating; a crackling noise, such as salt makes when roasting.",
  "agonizingly - With extreme anguish or desperate struggles.",
  "fubs - A plump young person or child. [Obs.] Smart.",
  "sight-seer - One given to seeing sights or noted things, or eager for novelties or curiosities.",
  "intaminated - Uncontaminated. [Obs.] Wood.",
  "pinchcock - A clamp on a flexible pipe to regulate the flow of a fluid through the pipe.",
  "graced - Endowed with grace; beautiful; full of graces; honorable. Shak.",
  "adry - In a dry or thirsty condition. \"A man that is adry.\" Burton.",
  "cotqueanity - The condition, character, or conduct of a cotquean. [Obs.] B. Jonson.",
  "sea moss - Any branched marine bryozoan resembling moss.",
  "winy - Having the taste or qualities of wine; vinous; as, grapes of a winy taste. Dampier.",
  "sea fern - Any gorgonian which branches like a fern.",
  "gramineous - Like, Or pertaining to, grass. See Grass, n., 2.",
  "pyritiferous - Containing or producing pyrites.",
  "admissive - Implying an admission; tending to admit. [R.] Lamb.",
  "emblossom - To cover or adorn with blossoms. On the white emblossomed spray. J. Cunningham.",
  "rerebrace - Armor for the upper part of the arm. Fairholt.",
  "day-net - A net for catching small birds.",
  "disquietment - State of being disquieted; uneasiness; harassment. [R.] Hopkins.",
  "youngness - The quality or state of being young.",
  "postanal - Situated behind, or posterior to, the anus.",
  "pinder - One who impounds; a poundkeeper. [Obs.]",
  "toluate - A salt of any one of the toluic acids.",
  "inceration - The act of smearing or covering with wax. B. Jonson.",
  "acuity - Sharpness or acuteness, as of a needle, wit, etc.",
  "pistareen - An old Spanish silver coin of the value of about twenty cents.",
  "retransform - To transform anew or back. -- Re`trans*for*ma\"tion, n.",
  "irresponsibly - So as not to be responsible.",
  "intreatful - Full of entreaty. [Obs.] Spenser.",
  "adsuki bean - A cultivated variety of the Asiatic gram, now introduced into the United States.",
  "commorient - Dying together or at the same time. [R.] Sir G. Buck.",
  "bootmaker - One who makes boots. -- Boot\"mak`ing, n.",
  "doghole - A place fit only for dogs; a vile, mean habitation or apartment. Dryden.",
  "hadj - The pilgrimage to Mecca, performed by Mohammedans.",
  "checklaton - 1. Ciclatoun. [Obs.] 2. Gilded leather. [Obs.] Spenser.",
  "munerary - Having the nature of a gift. [Obs.]",
  "subalternation - The state of being subalternate; succession of turns; subordination.",
  "cadetship - The position, rank, or commission of a cadet; as, to get a cadetship.",
  "asternal - Not sternal; -- said of ribs which do not join the sternum.",
  "giber - One who utters gibes. B. Jonson.",
  "plateful - Enough to fill a plate; as much as a plate will hold.",
  "avisement - Advisement; observation; deliberation. [Obs.]",
  "craftless - Without craft or cunning. Helpless, craftless, and innocent people. Jer. Taylor.",
  "metopomancy - Fortune telling by physiognomy. [R.] Urquhart.",
  "earthen-hearted - Hard-hearted; sordid; gross. [Poetic] Lowell.",
  "gallimatia - Senseless talk. [Obs. or R.] See Galimatias.",
  "septemvir - One of a board of seven men associated in some office.",
  "barraclade - A home-made woolen blanket without nap. [Local, New York] Bartlett.",
  "affabrous - Executed in a workmanlike manner; ingeniously made. [R.] Bailey.",
  "forwardly - Eagerly; hastily; obtrusively.",
  "deporture - Deportment. [Obs.] Stately port and majestical deporture. Speed.",
  "schiedam - Holland gin made at Schiedam in the Netherlands.",
  "stahlism - The Stahlian theoru, that every vital action is function or operation of the soul.",
  "gaverick - The European red gurnard (Trigla cuculus). [Prov. Eng.]",
  "ensate - Having sword-shaped leaves, or appendages; ensiform.",
  "extemporiness - The quality of being done or devised extempore [Obs.] Johnson.",
  "lapidarian - Of or pertaining to stone; inscribed on stone; as, a lapidarian record.",
  "co-respondent - One who is called upon to answer a summons or other proceeding jointly with another.",
  "quinquedentate - Five-toothed; as, a quinquedentate leaf.",
  "prothonotaryship - Office of a prothonotary.",
  "fistularioid - Like or pertaining to the genus Fistularia.",
  "viander - A feeder; an eater; also, one who provides viands, or food; a host. [Obs.] Holinshed.",
  "loggerheaded - Dull; stupid. Shak. A rabble of loggerheaded physicians. Urquhart.",
  "xylocarpous - Bearing fruit which becomes hard or woody.",
  "skee - A long strip of wood, curved upwards in front, used on the foot for sliding.",
  "hydriform - Having the form or structure of a hydra.",
  "muzzle-loading - Receiving its charge through the muzzle; as, a muzzle-loading rifle.",
  "sinic - Of or pertaining to the Chinese and allied races; Chinese.",
  "grallatory - Of or pertaining to the Grallatores, or waders.",
  "churchdom - The institution, government, or authority of a church. [R.] Bp. Pearson.",
  "pronuncial - Of or pertaining to pronunciation; pronunciative.",
  "broad-horned - Having horns spreading widely.",
  "feriation - The act of keeping holiday; cessation from work. [Obs.] Sir T. Browne.",
  "lampad - A lamp or candlestick. [R.] By him who 'mid the golden lampads went. Trench.",
  "cautiousness - The quality of being cautious.",
  "cobra de capello - The hooded snake (Naia tripudians), a highly venomous serpent inhabiting India.",
  "summum bonum - The supreme or highest good, -- referring to the object of human life.",
  "genealogist - One who traces genealogies or the descent of persons or families.",
  "incogitant - Toughtless; inconsiderate. [R.] Milton. Men are careless and incogitant. J. Goodman.",
  "boweled - Having bowels; hollow. \"The boweled cavern.\" Thomson.",
  "exculpable - . Capable of being exculpated; deserving exculpation. Sir G. Buck.",
  "diducement - Diduction; separation into distinct parts. Bacon.",
  "obsignate - To seal; to ratify. [Obs.] Barrow.",
  "preformative - A formative letter at the beginning of a word. M. Stuart.",
  "autodynamic - Supplying its own power; -- applied to an instrument of the nature of a water-ram.",
  "ago - Past; gone by; since; as, ten years ago; gone long ago.",
  "animistic - Of or pertaining to animism. Huxley. Tylor.",
  "funambulus - A ropewalker or ropedancer. [Obs.] Bacon.",
  "imperialist - One who serves an emperor; one who favors imperialism.",
  "ichthyophagy - The practice of eating, or living upon, fish.",
  "dolorific - Causing pain or grief. Arbuthnot.",
  "tallowy - Of the nature of tallow; resembling tallow; greasy.",
  "setous - Thickly set with bristles or bristly hairs.",
  "malgracious - Not graceful; displeasing. [Obs.] Gower.",
  "dichroic - Having the property of dichroism; as, a dichroic crystal.",
  "altaic - Of or pertaining to the Altai, a mountain chain in Central Asia.",
  "epexegesis - A full or additional explanation; exegesis.",
  "ebonize - To make black, or stain black, in imitation of ebony; as, to ebonize wood.",
  "anastomotic - Of or pertaining to anastomosis.",
  "ambrosially - After the manner of ambrosia; delightfully. \"Smelt ambrosially.\" Tennyson.",
  "skyish - Like the sky, or approaching the sky; lofty; ethereal. [R.] Shak.",
  "almsman - 1. A recipient of alms. Shak. 2. A giver of alms. [R.] Halliwell.",
  "angiotomy - Dissection of the blood vessels and lymphatics of the body. Dunglison.",
  "xiphophyllous - Having sword-shaped leaves.",
  "soncy - Lucky; fortunate; thriving; plump. [Prov. Eng. & Scot.]",
  "chessom - Mellow earth; mold. [Obs.] Bacon.",
  "paliform - Resembling a palus; as, the paliform lobes of the septa in corals.",
  "fetis - Neat; pretty; well made; graceful. [Obs.] Full fetis was her cloak, as I was ware. Chaucer.",
  "petiolulate - Supported by its own petiolule. Gray.",
  "acopic - Relieving weariness; restorative.",
  "flash burner - A gas burner with a device for lighting by an electric spark.",
  "comprehensibleness - The quality of being comprehensible; comprehensibility.",
  "quadrin - A small piece of money, in value about a farthing, or a half cent. [Obs.]",
  "elcesaite - One of a sect of Asiatic Gnostics of the time of the Emperor Trajan.",
  "impetrable - Capable of being obtained or moved by petition. [Obs.] Bailey.",
  "arhizous - See Arrhizal, Arrhizous, Arrhythmic, Arrhythmous.",
  "persifleur - One who indulges in persiflage; a banterer; a quiz. Carlyle.",
  "archaize - To make appear archaic or antique. Mahaffy.",
  "pinked - Pierced with small holes; worked in eyelets; scalloped on the edge. Shak.",
  "deceased - Passed away; dead; gone. The deceased, the dead person.",
  "fuscine - A dark-colored substance obtained from empyreumatic animal oil. [R.]",
  "vicissitudinous - Full of, or subject to, changes.",
  "concremation - The act of burning different things together. [Obs.]",
  "cawk - An opaque, compact variety of barite, or heavy spar. [Also written cauk.]",
  "infanticidal - Of or pertaining to infanticide; engaged in, or guilty of, child murder.",
  "nitromagnesite - Nitrate of magnesium, a saline efflorescence closely resembling nitrate of calcium.",
  "paracmastic - Gradually decreasing; past the acme, or crisis, as a distemper. Dunglison.",
  "consequentialness - The quality of being consequential.",
  "reseminate - To produce again by means of seed. [Obs.] Sir. T. Browne.",
  "yuletide - Christmas time; Christmastide; the season of Christmas.",
  "portman - An inhabitant or burgess of a port, esp. of one of the Cinque Ports.",
  "dermatic - Of or pertaining to the skin.",
  "jamaican - Of or pertaining to Jamaica. -- n.  A native or inhabitant of Jamaica.",
  "knavishness - The quality or state of being knavish; knavery; dishonesty.",
  "ribaudrous - Filthy; obscene; ribald. [Obs.]",
  "ethenic - Pertaining to, derived from. or resembling, ethene or ethylene; as, ethenic ether.",
  "unfeather - To deprive of feathers; to strip. [R.]",
  "tsarina - The title of the empress of Russia. See Czarina.",
  "anabaptize - To rebaptize; to rechristen; also, to rename. [R.] Whitlock.",
  "unhandy - Clumsy; awkward; as, an Unhandy man.",
  "listerian - Of or pertaining to listerism.",
  "fungous - 1. Of the nature of fungi; spongy. 2. Growing suddenly, but not substantial or durable.",
  "odible - Fitted to excite hatred; hateful. [Obs.] Bale.",
  "proscolex - An early larval form of a trematode worm; a redia. See Redia.",
  "flexanimous - Having power to change the mind. [Obs.] Howell.",
  "imponderableness - The quality or state of being imponderable.",
  "xiphura - Same as Limuloidea. Called also Xiphosura. X ray. See under Ray.",
  "intoleration - Intolerance; want of toleration; refusal to tolerate a difference of opinion.",
  "carousingly - In the manner of a carouser.",
  "biltong - Lean meat cut into strips and sun-dried. H. R. Haggard.",
  "indusiated - Furnished with an indusium.",
  "dryad - A wood nymph; a nymph whose life was bound up with that of her tree.",
  "extrinsicalness - The state or quality of being extrinsic.",
  "hornyhead - Any North American river chub of the genus Hybopsis, esp. H. biguttatus.",
  "salacity - Strong propensity to venery; lust; lecherousness.",
  "xylophaga - A genus of marine bivalves which bore holes in wood. They are allied to Pholas.",
  "ootooid - A half oviparous, or an oviparous, mammal; a marsupial or monotreme.",
  "tuba - (a) An ancient trumpet. (b) A sax-tuba. See Sax-tuba.",
  "orchestral - Of or pertaining to an orchestra; suitable for, or performed in or by, an orchestra.",
  "periproctitis - Inflammation of the tissues about the rectum.",
  "reverdure - To cover again with verdure. Ld. Berners.",
  "inapprehensible - Not apprehensible; unintelligible; inconceivable. Milton.",
  "lobiped - Having lobate toes, as a coot.",
  "monandric - Of or pertaining to monandry; practicing monandry as a system of marriage.",
  "dissilience - The act of leaping or starting asunder. Johnson.",
  "reassociate - To associate again; to bring again into close relatoins.",
  "scrophularia - A genus of coarse herbs having small flowers in panicled cymes; figwort.",
  "physico-theology - Theology or divinity illustrated or enforced by physics or natural philosophy.",
  "slate-gray - Of a dark gray, like slate.",
  "unshakable - Not capable of being shaken; firm; fixed. Shak. J. S. Mill.",
  "brideknot - A knot of ribbons worn by a guest at a wedding; a wedding favor. [Obs.]",
  "argentalium - A (patented) alloy of aluminium and silver, with a density of about 2.9.",
  "bouri - A mullet (Mugil capito) found in the rivers of Southern Europe and in Africa.",
  "bivector - A term made up of the two parts",
  "adulterize - To commit adultery. Milton.",
  "wincer - One who, or that which, winces, shrinks, or kicks.",
  "lenience - The quality or state of being lenient; lenity; clemency.",
  "unsensed - Wanting a distinct meaning; having no certain signification. [R.] Puller.",
  "discursist - A discourser. [Obs.] L. Addison.",
  "granduncle - father's or mother's uncle.",
  "recipience - The quality or state of being recipient; a receiving; reception; receptiveness.",
  "modernism - Modern practice; a thing of recent date; esp., a modern usage or mode of expression.",
  "toreumatology - The art or the description of scupture such as bas-relief in metal; toreumatography.",
  "consentant - Consenting. [Obs.] Chaucer.",
  "jatrophic - Of or pertaining to physic nuts, the seeds of plants of the genus Jatropha.",
  "derivational - Relating to derivation. Earle.",
  "breviature - An abbreviature; an abbreviation. [Obs.] Johnson.",
  "rosied - Decorated with roses, or with the color of roses.",
  "sioux state - North Dakota; -- a nickname.",
  "battology - A needless repetition of words in speaking or writing. Milton.",
  "interdentil - The space between two dentils. Gwilt.",
  "fustilugs - A gross, fat, unwieldy person. [Obs.] F. Junius.",
  "populares - The people or the people's party, in ancient Rome, as opposed to the optimates.",
  "pansclavist - See Panslavic, Panslavism, etc.",
  "moration - A delaying tarrying; delay. [R.] Sir T. Browne.",
  "tumble-down - Ready to fall; dilapidated; ruinous; as, a tumble-down house. [Colloq.]",
  "bedfellow - One who lies with another in the same bed; a person who shares one's couch.",
  "inchworm - The larva of any geometrid moth. See Geometrid.",
  "dissertationist - A writer of dissertations.",
  "deoppilative - Deobstruent; aperient. [Obs.] Harvey.",
  "danceress - A female dancer. [Obs.] Wyclif.",
  "antichristian - Opposed to the Christian religion.",
  "qualitied - Furnished with qualities; endowed. [Obs.] \"He was well qualitied.\" Chapman.",
  "frankness - The quality of being frank; candor; openess; ingenuousness; fairness; liberality.",
  "arithmetician - One skilled in arithmetic.",
  "well-natured - Good-natured; kind. Well-natured, temperate, and wise. Denham.",
  "pestful - Pestiferous. \"After long and pestful calms.\" Coleridge.",
  "promotive - Tending to advance, promote, or encourage. Hume.",
  "trunkful - As much as a trunk will hold; enough to fill a trunk.",
  "shotted - 1. Loaded with shot. 2. (Med.)  Having a shot attached; as, a shotten suture.",
  "fromwards - A way from; -- the contrary of toward. [Obs.] Towards or fromwards the zenith. Cheyne.",
  "causticness - The quality of being caustic; causticity.",
  "disorderliness - The state of being disorderly.",
  "buzzsaw - A circular saw; -- so called from the buzzing it makes when running at full speed.",
  "stiff-hearted - Obstinate; stubborn; contumacious. Ezek. ii. 4.",
  "sdeign - To disdain. [Obs.] But either sdeigns with other to partake. Spenser.",
  "storm-beat - Beaten, injured, or impaired by storms. Spenser.",
  "nonpresentation - Neglect or failure to present; state of not being presented.",
  "niggardy - Niggardliness. [Obs.] Chaucer.",
  "stuprate - To ravish; to debauch. [R.] Heywood.",
  "ill-bred - Badly educated or brought up; impolite; incivil; rude. See Note under Ill, adv.",
  "cystocarp - A minute vesicle in a red seaweed, which contains the reproductive spores.",
  "top-shaped - Having the shape of a top; (Bot.) cone-shaped, with the apex downward; turbinate.",
  "saporific - Having the power to produce the sensation of taste; producing taste, flavor, or relish.",
  "scrippage - The contents of a scrip, or wallet. [Obs.] Shak.",
  "bow-pencil - Bow-compasses, one leg of which carries a pencil.",
  "hippocrepiform - Shaped like a horseshoe.",
  "rory - Dewy. [R.] And shook his wings with rory May-dew wet. Fairfax.",
  "metapodiale - One of the bones of either the metacarpus or metatarsus.",
  "rhythmics - The department of musical science which treats of the length of sounds.",
  "polygyn - A plant of the order Polygynia.",
  "inorganization - The state of being without organization.",
  "plashet - A small pond or pool; a puddle.",
  "slaggy - Of or pertaining to slag; resembling slag; as, slaggy cobalt.",
  "diverticular - Pertaining to a diverticulum.",
  "faroese - An inhabitant, or, collectively, inhabitants, of the Faroe islands.",
  "grimy - Full of grime; begrimed; dirty; foul.",
  "gesturement - Act of making gestures; gesturing. [Obs.] Bp. Hall.",
  "flabelliform - Having the form of a fan; fan-shaped; flabellate.",
  "boardable - That can be boarded, as a ship.",
  "marauder - A rover in quest of booty or plunder; a plunderer; one who pillages. De Quincey.",
  "asperate - To make rough or uneven. The asperated part of its surface. Boyle.",
  "desireful - Filled with desire; eager. [R.] The desireful troops. Godfrey (1594).",
  "chondrotomy - The dissection of cartilages.",
  "antivaccinist - One opposed to vaccination.",
  "alcedo - A genus of perching birds, including the European kingfisher (Alcedo ispida). See Halcyon.",
  "stenographical - Of or pertaining to stenography.",
  "mainmast - The principal mast in a ship or other vessel.",
  "ruption - A breaking or bursting open; breach; rupture. \"By ruption or apertion.\" Wiseman.",
  "scur - To move hastily; to scour. [Obs. or Prov. Eng.] Halliwell.",
  "desynonymization - The act of desynonymizing.",
  "ptilopteri - An order of birds including only the penguins.",
  "vulnific - Causing wounds; inflicting wounds; wounding.",
  "coadjutorship - The state or office of a coadjutor; joint assistance. Pope.",
  "maegbote - Compensation for the injury done by slaying a kinsman. Spelman.",
  "repace - To pace again; to walk over again in a contrary direction.",
  "subclavian - Situated under the clavicle, or collar bone; as, the subclavian arteries.",
  "quartzose - Containing, or resembling, quartz; partaking of the nature or qualities of quartz.",
  "loma - A lobe; a membranous fringe or flap.",
  "revelator - One who makes a revelation; a revealer. [R.]",
  "lifemate - Companion for life. Hawthorne.",
  "attractability - The quality or fact of being attractable. Sir W. Jones.",
  "stringendo - Urging or hastening the time, as to a climax.",
  "boracous - Relating to, or obtained from, borax; containing borax.",
  "butyraceous - Having the qualities of butter; resembling butter.",
  "internecive - Internecine. [R.] Sydney Smith.",
  "phonographically - In a phonographic manner; by means of phonograph.",
  "apodeictically - So as to be evident beyond contradiction.",
  "spiritualness - The quality or state of being spiritual or spiritual-minded; spirituality.",
  "otoscopy - The examination of the ear; the art of using the otoscope.",
  "goroon shell - A large, handsome, marine, univalve shell (Triton femorale).",
  "versificator - A versifier. [R.] \"The best versificator next Virgil.\" Dryden.",
  "spermatism - The emission of sperm, or semen.",
  "slayer - One who slays; a killer; a murderer; a destrroyer of life.",
  "conchyliologist - See Conchologist, and Conchology.",
  "forepart - The part most advanced, or first in time or in place; the beginning.",
  "barad - The pressure of one dyne per square centimeter; -- used as a unit of pressure.",
  "water rice - Indian rice. See under Rice.",
  "belam - To beat or bang. [Prov. & Low, Eng.] Todd.",
  "hairiness - The state of abounding, or being covered, with hair. Johnson.",
  "prefectship - The office or jurisdiction of a prefect.",
  "scincoidea - A tribe of lizards including the skinks. See Skink.",
  "woodly - In a wood, mad, or raving manner; madly; furiously. [Obs.] Chaucer.",
  "recognisor - One who enters into a recognizance. [Written also recognisor.] Blackstone.",
  "hoo - 1. See Ho. [Obs.] Chaucer. 2. Hurrah! -- an exclamation of triumphant joy. Shak.",
  "inconcurring - Not concurring; disagreeing. [R.] Sir T. Browne.",
  "pseudograph - A false writing; a spurious document; a forgery.",
  "unnooked - Without nooks and corners; guileless. [Obs.] \"Unnooked simplicity.\" Marston.",
  "pluckiness - The quality or state of being plucky.",
  "-lith - Combining forms fr. Gr. li`qos a stone; -- used chiefly in naming minerals and rocks.",
  "questionableness - The quality or state of being questionable, doubtful, or suspicious.",
  "dogmatizer - One who dogmatizes; a bold asserter; a magisterial teacher. Hammond.",
  "skar - Wild; timid; shy. [Prov. Eng. & Scot.]",
  "bemeet - To meet. [Obs.] Our very loving sister, well bemet. Shak.",
  "helmless - 1. Destitute of a helmet. 2. Without a helm or rudder. Carlyle.",
  "finfish - (a) A finback whale. (b) (pl.) True fish, as distinguished from shellfish.",
  "valved - Having a valve or valve; valvate.",
  "oxytocic - Promoting uterine contractions, or parturition. -- n.  An oxytocic medicine or agent.",
  "kerseys - Varieties of kersey; also, trousers made of kersey.",
  "tradescantia - A genus including spiderwort and Wandering Jew.",
  "cuirassier - A soldier armed with a cuirass. Milton.",
  "potance - The stud in which the bearing for the lower pivot of the verge is made.",
  "dogtrick - A gentle trot, like that of a dog.",
  "purset - A purse or purse net. B. Jonson.",
  "glass-snail - A small, transparent, land snail, of the genus Vitrina.",
  "piot - The magpie. [Obs. or Prov. Eng. & Scot.] Holland.",
  "anchoretism - The practice or mode of life of an anchoret.",
  "lotong - An East Indian monkey (Semnopithecus femoralis).",
  "tetragynous - Belonging to the order Tetragynia; having four styles.",
  "taeniacide - A remedy to destroy tapeworms.",
  "arrhizal - Destitute of a true root, as a parasitical plant.",
  "serrulated - Finely serrate; having very minute teeth.",
  "deadliness - The quality of being deadly.",
  "erythematous - Relating to, or causing, erythema.",
  "pickering - The sauger of the St.Lawrence River.",
  "supersulphureted - Supersulphurized. [Obs.] [Written also -sulphuretted.]",
  "astonishedly - In an astonished manner. [R.] Bp. Hall.",
  "reclaimless - That can not be reclaimed.",
  "misurato - Measured; -- a direction to perform a passage in strict or measured time.",
  "overmost - Over the rest in authority; above all others; highest. [Obs.] Fabyan.",
  "seamster - One who sews well, or whose occupation is to sew. [Obs.]",
  "gothicize - To make Gothic; to bring back to barbarism.",
  "tetartohedrism - The property of being tetartohedral.",
  "fish-bellied - Bellying or swelling out on the under side; as, a fish-bellied rail. Knight.",
  "vicissitudinary - Subject to vicissitudes. Donne.",
  "philanthrope - A philanthropist. [Obs.] R. North.",
  "haberdash - To deal in small wares. [R.] To haberdash in earth's base ware. Quarles.",
  "analects - A collection of literary fragments.",
  "reexamination - A repeated examination. See under Examination.",
  "dilettanteish - Somewhat like a dilettante.",
  "arcane - Hidden; secret. [Obs.] \"The arcane part of divine wisdom.\" Berkeley.",
  "histographer - One who describes organic tissues; an histologist.",
  "internecion - Mutual slaughter or destruction; massacre. [Obs.] Sir M. Hale.",
  "sutler - A person who follows an army, and sells to the troops provisions, liquors, and the like.",
  "sympathist - One who sympathizes; a sympathizer. [R.] Coleridge.",
  "disquietful - Producing inquietude or uneasiness. [R.] Barrow.",
  "conjugational - relating to conjugation. Ellis.",
  "interventricular - Between the ventricles; as, the interventricular partition of the heart.",
  "estatly - Stately; dignified. [Obs.] Chaucer.",
  "duplicature - A doubling; a fold, as of a membrane.",
  "acervative - Heaped up; tending to heap up.",
  "gap-toothed - Having interstices between the teeth. Dryden.",
  "ananas - The pineapple (Ananassa sativa).",
  "uncity - To deprive of the rank or rights of a city. [Obs.]",
  "filicide - The act of murdering a son or a daughter; also, parent who commits such a murder.",
  "rhabdomere - One of the several parts composing a rhabdom.",
  "cubited - Having the measure of a cubit.",
  "astaticism - The state of being astatic.",
  "guiltiness - The quality or state of being guilty.",
  "ozonous - Pertaining to or containing, ozone.",
  "vetust - Venerable from antiquity; ancient; old. [Obs.]",
  "disgarnish - To divest of garniture; to disfurnish; to dismantle. Bp. Hall.",
  "philosophism - Spurious philosophy; the love or practice of sophistry. Carlyle.",
  "interfoliate - To interleave. [Obs.] Evelyn.",
  "melodramatist - One who acts in, or writes, melodramas.",
  "enantiopathic - Serving to palliate; palliative. Dunglison.",
  "injudicial - Not according to the forms of law; not judicial. [R.]",
  "pervestigation - Thorough investigation. [Obs.] Chillingworth.",
  "pyrolator - A fire worshiper. [R.] Southey.",
  "oratrix - A woman plaintiff, or complainant, in equity pleading. Burrill.",
  "brimful - Full to the brim; completely full; ready to overflow. \"Her brimful eyes.\" Dryden.",
  "eglatere - Eglantine. [Obs. or R.] [Written also eglantere.] Tennyson.",
  "absorptive - Having power, capacity, or tendency to absorb or imbibe. E. Darwin.",
  "carking - Distressing; worrying; perplexing; corroding; as, carking cares.",
  "spirulate - Having the color spots, or structural parts, arranged spirally.",
  "phytochemical - Relating to phytochemistry. R. Hunt.",
  "wallowish - Flat; insipid. [Obs.] Overbury.",
  "vengeable - Revengeful; deserving revenge. [Obs.] Spenser. -- Venge\"a*bly, adv. [Obs.]",
  "deifical - Making divine; producing a likeness to God; god-making. \"A deifical communion.\" Homilies.",
  "hymnography - The art or act of composing hymns.",
  "wowf - Disordered or unsettled in intellect; deranged. [Scot.] Sir W. Scott.",
  "nephritis - An inflammation of the kidneys.",
  "starost - A nobleman who possessed a starosty. [Poland]",
  "apocopation - Shortening by apocope; the state of being apocopated.",
  "chylaceous - Possessed of the properties of chyle; consisting of chyle.",
  "polypody - Any plant of the genus Polypodium.",
  "schematist - One given to forming schemes; a projector; a schemer. Swift.",
  "omphaloptic - An optical glass that is convex on both sides. [Obs.] Hutton.",
  "subsolary - Being under the sun; hence, terrestrial; earthly; mundane. [R.]",
  "mammet - An idol; a puppet; a doll. [Obs.] Selden. Shak.",
  "plumiped - Having feet covered with feathers. -- n.  A plumiped bird.",
  "senocular - Having six eyes. [R.] Derham.",
  "exfoliative - Having the power of causing exfoliation. -- n.  An exfoliative agent. Wiseman.",
  "inspective - Engaged in inspection; inspecting; involving inspection.",
  "meniscoid - Concavo-convex, like a meniscus.",
  "determent - The act of deterring; also, that which deters. Boyle.",
  "desertful - Meritorious. [R.] Beau. & Fl.",
  "lubrifaction - The act of lubricating, or making smooth. Ray. Bacon.",
  "pug-faced - Having a face like a monkey or a pug; monkey-faced.",
  "incompliable - Not compliable; not conformable.",
  "horticulture - The cultivation of a garden or orchard; the art of cultivating gardens or orchards.",
  "zoomelanin - A pigment giving the black color to the feathers of many birds.",
  "libertarianism - Libertarian principles or doctrines.",
  "nebulize - To reduce (as a liquid) to a fine spray or vapor; to atomize.",
  "agger - An earthwork; a mound; a raised work. [Obs.] Hearne.",
  "multicuspid - Multicuspidate; -- said of teeth.",
  "noemics - The science of the understanding; intellectual science.",
  "rataplan - The iterative sound of beating a drum, or of a galloping horse.",
  "abysmally - To a fathomless depth; profoundly. \"Abysmally ignorant.\" G. Eliot.",
  "craniometer - An instrument for measuring the size of skulls.",
  "ebulliency - A boiling up or over; effervescence. Cudworth.",
  "nosethril - Nostril. [Obs.] [Written also nosethurl, nosthrill.] Chaucer.",
  "sinistrally - Toward the left; in a sinistral manner. J. Le Conte.",
  "zoophagan - A animal that feeds on animal food.",
  "threnodist - One who composes, delivers, or utters, a threnode, or threnody.",
  "blenniid - Of, pertaining to, or resembling, the blennies.",
  "gunsmithing - The art or business of a gunsmith.",
  "ramus - A branch; a projecting part or prominent process; a ramification.",
  "polycracy - Government by many rulers; polyarchy.",
  "sesquitone - A minor third, or interval of three semitones.",
  "inactively - In an inactive manner. Locke.",
  "faineant - Doing nothing; shiftless. -- n.  A do-nothing; an idle fellow; a sluggard. Sir W. Scott.",
  "exprobrative - Expressing reproach; upbraiding; reproachful. [R.] Sir A. Shirley.",
  "ligge - To lie or recline. [Obs.] Chaucer.",
  "defoliate - Deprived of leaves, as by their natural fall.",
  "pilch - A gown or case of skin, or one trimmed or lined with fur. [Obs.]",
  "quester - One who seeks; a seeker. [Obs.]",
  "galactodensimeter - Same as Galactometer.",
  "infallibleness - The state or quality of being infallible; infallibility. Bp. Hall.",
  "phonetist - 1. One versed in phonetics; a phonologist. 2. One who advocates a phonetic spelling.",
  "home-speaking - Direct, forcible, and effective speaking. Milton.",
  "limpidity - The quality or state of being limpid.",
  "sea canary - The beluga, or white whale.",
  "urethrotomy - An incision of the urethra, esp. incision for relief of urethral stricture.",
  "phylum - One of the larger divisions of the animal kingdom; a branch; a grand division.",
  "agamogenesis - Reproduction without the union of parents of distinct sexes: asexual reproduction.",
  "floriculture - The cultivation of flowering plants.",
  "infrigidate - To chill; to make cold; to cool. [Obs.] Boyle.",
  "pteranodontia - A group of pterodactyls destitute of teeth, as in the genus Pteranodon.",
  "lucule - A spot or fleck on the sun brighter than the surrounding surface.",
  "container - One who, or that which, contains.",
  "peritomous - Cleaving in more directions than one, parallel to the axis.",
  "druxy - Having decayed spots or streaks of a whitish color; -- said of timber. Weale.",
  "inmeats - The edible viscera of animals, as the heart, liver, etc.",
  "unisonance - Accordance of sounds; unison.",
  "murenger - One who had charge of the wall of a town, or its repairs.",
  "distractible - Capable of being drawn aside or distracted.",
  "insurmountably - In a manner or to a degree not to be overcome.",
  "standel - A young tree, especially one reserved when others are cut. [Obs.] Fuller.",
  "hellanodic - A judge or umpire in games or combats.",
  "validness - The quality or state of being valid.",
  "blady - Consisting of blades. [R.] \"Blady grass.\" Drayton.",
  "waiver - The act of waiving, or not insisting on, some right, claim, or privilege.",
  "strobiline - Of or pertaining to a strobile; strobilaceous; strobiliform; as, strobiline fruits.",
  "cotyledonal - Of, pertaining to, or resembling, a cotyledon.",
  "truth-lover - One who loves the truth. Truth-lover was our English Duke. Tennyson.",
  "lym - A dog held in a leam; a bloodhound; a limehound. [Obs.] Shak.",
  "roriferous - generating or producing dew. [R.]",
  "nervimotor - Any agent capable of causing nervimotion. Dunglison.",
  "underfaculty - An inferior or subordinate faculty.",
  "aliethmoid - Pertaining to expansions of the ethmoid bone or",
  "diota - A vase or drinking cup having two handles or ears.",
  "adverbialize - To give the force or form of an adverb to.",
  "know-nothingism - The doctrines, principles, or practices, of the Know-nothings.",
  "banqueter - One who banquets; one who feasts or makes feasts.",
  "incubative - Of or pertaining to incubation, or to the period of incubation.",
  "myristin - The myristate of glycerin, -- found as a vegetable fat in nutmeg butter, etc.",
  "true-penny - An honest fellow. Shak. Bacon.",
  "demivill - A half-vill, consisting of five freemen or frankpledges. Blackstone.",
  "nut-brown - Brown as a nut long kept and dried. \"The spicy nutbrown ale.\" Milton.",
  "creativeness - The qualiyu of being creative.",
  "ingracious - Ungracious; unkind. [Obs.] Holland.",
  "noteworthy - Worthy of observation or notice; remarkable.",
  "chylification - The formation of chyle. See Chylifaction.",
  "residenter - A resident. [Obs. or Colloq.]",
  "enunciable - Capable of being enunciated or expressed.",
  "issuably - In an issuable manner; by way of issue; as, to plead issuably.",
  "acrita - The lowest groups of animals, in which no nervous system has been observed.",
  "electrician - An investigator of electricity; one versed in the science of electricity.",
  "ureal - Of or pertaining to urea; containing, or consisting of, urea; as, ureal deposits.",
  "vilification - The act of vilifying or defaming; abuse. South.",
  "veriloquent - Speaking truth; truthful. [Obs.]",
  "leftward - Toward or on the left side. Rightward and leftward rise the rocks. Southey.",
  "almightiful - All-powerful; almighty. [Obs.] Udall.",
  "drool - To drivel, or drop saliva; as, the child drools. His mouth drooling with texts. T. Parker.",
  "misapprehensively - By, or with, misapprehension.",
  "chirogymnast - A mechanocal contrivance for exercesing the fingers of a pianist.",
  "resultless - Being without result; as, resultless investigations.",
  "pretex - To frame; to devise; to disguise or excuse; hence, to pretend; to declare falsely. [Obs.]",
  "dendrachate - Arborescent or dendritic agate.",
  "adjectively - In the manner of an adjective; as, a word used adjectively.",
  "identicalness - The quality or state of being identical; sameness.",
  "spelk - A small stick or rod used as a spike in thatching; a splinter. [Prov. Eng.] Grose.",
  "derisory - Derisive; mocking. Shaftesbury.",
  "drazel - A slut; a vagabond wench. Same as Drossel. [Obs.] Hudibras.",
  "sclerodermite - (a) The hard integument of Crustacea. (b) Sclerenchyma.",
  "hydrotelluric - Formed by hydrogen and tellurium; as, hydrotelluric acid, or hydrogen telluride.",
  "dactylioglyphy - The art or process of gem engraving.",
  "multifold - Many times doubled; manifold; numerous.",
  "perioplic - Of or pertaining to the periople; connected with the periople.",
  "taurocholate - A salt of taurocholic acid; as, sodium taurocholate, which occurs in human bile.",
  "sundries - Many different or small things; sundry things.",
  "housebuilder - One whose business is to build houses; a housewright.",
  "sanctitude - Holiness; sacredness; sanctity. [R.] milton.",
  "enuresis - An involuntary discharge of urine; incontinence of urine.",
  "argufy - 1. To argue pertinaciously. [Colloq.] Halliwell. 2. To signify. [Colloq.]",
  "lophobranch - Of or pertaining to the Lophobranchii. -- n.  One of the Lophobranchii.",
  "innominable - Not to be named. [R.] Testament of Love.",
  "slapjack - A flat batter cake cooked on a griddle; a flapjack; a griddlecake. [Local, U.S.]",
  "arachnidium - The glandular organ in which the material for the web of spiders is secreted.",
  "countourhouse - A merchant's office; a countinghouse. [Obs.] Chaucer.",
  "portrayal - The act or process of portraying; description; delineation.",
  "cunningly - In a cunning manner; with cunning.",
  "couranto - A sprightly dance; a coranto; a courant.",
  "perispheric - Exactly spherical; globular.",
  "amendatory - Supplying amendment; corrective; emendatory. Bancroft.",
  "headgear - 1. Headdress. 2. Apparatus above ground at the mouth of a mine or deep well.",
  "hypnotization - The act or process of producing hypnotism.",
  "behemoth - An animal, probably the hippopotamus, described in Job xl. 15- 24.",
  "bivalved - Having two valves, as the oyster and some seed pods; bivalve.",
  "ovate-acuminate - Having an ovate form, but narrowed at the end into a slender point.",
  "distensive - Distending, or capable of being distended.",
  "inductility - The quality or state of being inductile.",
  "humectation - A moistening. [Obs.] Bacon.",
  "disinteresting - Uninteresting. [Obs.] \"Disinteresting passages.\" Bp. Warburton.",
  "ineffectible - Ineffectual; impracticable. [R.] Bp. Hall.",
  "deniable - Capable of being, or liable to be, denied.",
  "pulmonic - Relating to, or affecting the lungs; pulmonary. -- n.  A pulmonic medicine.",
  "water flag - A European species of Iris (Iris Pseudacorus) having bright yellow flowers.",
  "insitiency - Freedom from thirst. [Obs.] The insitiency of a camel for traveling in deserts. Grew.",
  "forcipated - Like a pair of forceps; as, a forcipated mouth.",
  "sight-shot - Distance to which the sight can reach or be thrown. [R.] Cowley.",
  "sprod - A salmon in its second year. [Prov. Eng.]",
  "comptroler - A controller; a public officer whose duty it is to examine certify accounts.",
  "disanoint - To invalidate the consecration of; as, to disanoint a king. [Obs.] Milton.",
  "sabbatarianism - The tenets of Sabbatarians. Bp. Ward. (1673).",
  "sans-souci - Without care; free and easy.",
  "raku ware - A kind of earthenware made in Japan, resembling Satsuma ware, but having a paler color.",
  "janker - A long pole on two wheels, used in hauling logs. [Scot.] Jamieson.",
  "froise - A kind of pancake. See 1st Fraise. [Written also fraise.]",
  "gastralgia - Pain in the stomach or epigastrium, as in gastric disorders.",
  "sea-bordering - Bordering on the sea; situated beside the sea. Drayton.",
  "triserial - Arranged in three vertical or spiral rows.",
  "crescentic - Crescent-shaped. \"Crescentic lobes.\" R. Owen.",
  "balas ruby - A variety of spinel ruby, of a pale rose red, or inclining to orange. See Spinel.",
  "herpetotomy - The anatomy or dissection of reptiles.",
  "mesencephalic - Of or pertaining to the mesencephalon or midbrain.",
  "contristate - To make sorrowful. [Obs.] Bacon.",
  "digestibleness - The quality of being digestible; digestibility.",
  "lymphoid - Resembling lymph; also, resembling a lymphatic gland; adenoid; as, lymphoid tissue.",
  "dueler - One who engages in a duel. [R.] [Written also dueller.] South.",
  "uncinate - Hooked; bent at the tip in the form of a hook; as, an uncinate process.",
  "psychography - 1. A description of the phenomena of mind. 2. (Spiritualism)  Spirit writing.",
  "sarcle - To weed, or clear of weeds, with a hoe. [Obs.] Ainsworth.",
  "monthling - That which is a month old, or which lives for a month. [R.] Wordsworth.",
  "jarrah - The mahoganylike wood of the Australian Eucalyptus marginata. See Eucalyptus.",
  "acritan - Of or pertaining to the Acrita. -- n. An individual of the Acrita.",
  "illuminable - Capable of being illuminated.",
  "periscian - Having the shadow moving all around.",
  "redargutory - Pertaining to, or containing, redargution; refutatory. [R.]",
  "glycogenic - Pertaining to, or caused by, glycogen; as, the glycogenic function of the liver."
]