export default [
  "coprolitic - Containing, pertaining to, or of the nature of, coprolites.",
  "goggle-eyed - Having prominent and distorted or rolling eyes. Ascham.",
  "hanselines - A sort of breeches. [Obs..] Chaucer.",
  "incommensurability - The quality or state of being incommensurable. Reid.",
  "accessoriness - The state of being accessory, or connected subordinately.",
  "sensated - Felt or apprehended through a sense, or the senses. [R.] Baxter.",
  "alferes - An ensign; a standard bearer. [Obs.] J. Fletcher.",
  "annodated - Curved somewhat in the form of the letter S. Cussans.",
  "whitewort - (a) Wild camomile. (b) A kind of Solomon's seal (Polygonum officinale).",
  "selenate - A salt of selenic acid; -- formerly called also seleniate.",
  "zeta - A Greek letter [z] corresponding to our z.",
  "anomaloflorous - Having anomalous flowers.",
  "sea mile - A geographical mile. See Mile.",
  "organling - A large kind of sea fish; the orgeis.",
  "subtribe - A division of a tribe; a group of genera of a little lower rank than a tribe.",
  "antiquitarian - An admirer of antiquity. Note: [Used by Milton in a disparaging sense.] [Obs.]",
  "right-lined - Formed by right lines; rectilineal; as, a right-lined angle.",
  "vitreo-electic - Containing or exhibiting positive, or vitreous, electricity.",
  "slab-sided - Having flat sides; hence, tall, or long and lank. [Colloq. U. S.]",
  "treasure-house - A house or building where treasures and stores are kept.",
  "braving - A bravado; a boast. With so proud a strain Of threats and bravings. Chapman.",
  "caseworm - A worm or grub that makes for itself a case. See Caddice.",
  "unbed - To raise or rouse from bed. Eels unbed themselves and stir at the noise of thunder. Wa",
  "pasquilant - A lampooner; a pasquiler. [R.] Coleridge.",
  "derogatorily - In a derogatory manner; disparagingly. Aubrey.",
  "sepidaceous - Like or pertaining to the cuttlefishes of the genus Sepia.",
  "snast - The snuff, or burnt wick, of a candle. [Obs.] Bacon.",
  "championship - State of being champion; leadership; supremancy.",
  "involucrate - Having an involucre; involucred.",
  "reperusal - A second or repeated perusal.",
  "wirble - To whirl; to eddy. [R.] The waters went wirbling above and around. Owen. Meredith.",
  "half-sighted - Seeing imperfectly; having weak discernment. Bacon.",
  "flatworm - Any worm belonging to the Plathelminthes; also, sometimes applied to the planarians.",
  "ichthyophagous - Eating, or subsisting on, fish.",
  "ametabola - A group of insects which do not undergo any metamorphosis. [Written also Ametabolia.]",
  "promisee - The person to whom a promise is made.",
  "fungate - A salt of fungic acid. [Formerly written also fungiate.]",
  "waahoo - The burning bush; -- said to be called after a quack medicine made from it.",
  "calyculate - Having a set of bracts resembling a calyx.",
  "shinty - A Scotch game resembling hockey; also, the club used in the game. Jamieson.",
  "dialogical - Relating to a dialogue; dialogistical. Burton.",
  "sporangium - A spore case in the cryptogamous plants, as in ferns, etc.",
  "trajetour - See Treget, Tregetour, and Tregetry. [Obs.]",
  "shopwalker - One who walks about in a shop as an overseer and director. Cf. Floorwalker.",
  "lochan - A small lake; a pond. [Scot.] A pond or lochan rather than a lake. H. Miller.",
  "parallelable - Capable of being paralleled, or equaled. [R.] Bp. Hall.",
  "azotometer - An apparatus for measuring or determining the proportion of nitrogen; a nitrometer.",
  "spumescent - Resembling froth or foam; foaming.",
  "inequivalvular - Having unequal valves, as the shell of an oyster.",
  "inappeasable - Incapable of being appeased or satisfied; unappeasable.",
  "irreducibility - The state or quality of being irreducible.",
  "arbitrable - Capable of being decided by arbitration; determinable. [Archaic] Bp. Hall.",
  "phyllomorphosis - The succession and variation of leaves during different seasons. R. Brown.",
  "ischiorectal - Of or pertaining to the region between the rectum and ishial tuberosity.",
  "tinsmith - One who works in tin; a tinner.",
  "apiol - An oily liquid derived from parsley.",
  "unlook - To recall or retract, as a look. [R.] Richardson.",
  "appay - To pay; to satisfy or appease. [Obs.] Sir P. Sidney.",
  "camisated - Dressed with a shirt over the other garments.",
  "parnellism - The policy or principles of the Parnellites.",
  "herbiferous - Bearing herbs or vegetation.",
  "geason - Rare; wonderful. [Obs.] Spenser.",
  "prickpunch - A pointed steel punch, to prick a mark on metal.",
  "orthotomous - Having two cleavages at right angles with one another.",
  "fool-happy - Lucky, without judgment or contrivance. [Obs.] Spenser.",
  "guardable - Capable of being guarded or protected.",
  "abatvoix - The sounding-board over a pulpit or rostrum.",
  "inquirent - Making inquiry; inquiring; questioning. [Obs.] Shenstone.",
  "double-hung - Having both sashes hung with weights and cords; -- said of a window.",
  "dilogy - An ambiguous speech; a figure in which a word is used an equivocal sense. [R.]",
  "shaftman - A measure of about six inches. [Obs.]",
  "flintwood - An Australian name for the very hard wood of the Eucalyptus piluralis.",
  "hollow-horned - Having permanent horns with a bony core, as cattle.",
  "exsiccative - Tending to make dry; having the power of drying.",
  "dirtily - In a dirty manner; foully; nastily; filthily; meanly; sordidly.",
  "excitative - Having power to excite; tending or serving to excite; excitatory. Barrow.",
  "redelivery - 1. Act of delivering back. 2. A second or new delivery or liberation.",
  "electrolytic - Pertaining to electrolysis; as, electrolytic action. -- E*lec`tro*lyt\"ic*al*ly, adv.",
  "hopeite - A hydrous phosphate of zinc in transparent prismatic crystals.",
  "wendish - Of or pertaining the Wends, or their language.",
  "mesodermal - Pertaining to, or derived from, the mesoderm; as, mesodermal tissues.",
  "semicalcined - Half calcined; as, semicalcined iron.",
  "bass horn - A modification of the bassoon, much deeper in tone.",
  "rosebud - The flower of a rose before it opens, or when but partially open.",
  "bulger - A driver or a brassy with a convex face.",
  "aleatory - Depending on some uncertain contingency; as, an aleatory contract. Bouvier.",
  "flatlong - ; 115), adv. With the flat side downward; not edgewise. Shak.",
  "prioress - A lady superior of a priory of nuns, and next in dignity to an abbess.",
  "suggillation - A livid, or black and blue, mark; a blow; a bruise.",
  "multiscious - Having much or varied knowledge. [Obs.]",
  "warmonger - One who makes ar a trade or business; a mercenary. [R.] Spenser.",
  "atimy - Public disgrace or stigma; infamy; loss of civil rights. Mitford.",
  "appearingly - Apparently. [Obs.] Bp. Hall.",
  "main yard - The yard on which the mainsail is extended, supported by the mainmast.",
  "flat-headed - Having a head with a flattened top; as, a flat-headed nail.",
  "peaty - Composed of peat; abounding in peat; resembling peat.",
  "haustellum - The sucking proboscis of various insects. See Lepidoptera, and Diptera.",
  "rampacious - High-spirited; rampageous. [Slang] Dickens.",
  "couchancy - State of lying down for repose. [R.]",
  "cruciform - Cross-shaped; (Bot.) having four parts arranged in the form of a cross.",
  "unisonous - Being in unison; unisonant. Busby.",
  "praecordia - The front part of the thoracic region; the epigastrium.",
  "toothshell - Any species of Dentalium and allied genera having a tooth- shaped shell. See Dentalium.",
  "franklinite - A kind of mineral of the spinel group.",
  "composture - Manure; compost. [Obs.] Shak.",
  "insinuator - One who, or that which, insinuates. De Foe.",
  "dubitation - Act of doubting; doubt. [R.] Sir T. Scott.",
  "unglaze - To strip of glass; to remove the glazing, or glass, from, as a window.",
  "nunatak - In Greenland, an insular hill or mountain surrounded by an ice sheet.",
  "demagogism - The practices of a demagogue.",
  "renewal - The act of renewing, or the state of being renewed; as, the renewal of a treaty.",
  "despume - To free from spume or scum. [Obs.] If honey be despumed. Holland.",
  "manus - The distal segment of the fore limb, including the carpus and fore foot or hand.",
  "rhine - A water course; a ditch. [Written also rean.] [Prov. Eng.] Macaulay.",
  "reimportation - The act of reimporting; also, that which is reimported.",
  "umbraculiferous - Bearing something like an open umbrella.",
  "woodhole - A place where wood is stored.",
  "shorer - One who, or that which, shores or props; a prop; a shore.",
  "unsettlement - The act of unsettling, or state of being unsettled; disturbance. J. H. Newman.",
  "rheinberry - One of the berries or drupes of the European buckthorn; also, the buckthorn itself.",
  "exhibitive - Serving for exhibition; representative; exhibitory. Norris. -- Ex*hib\"it*ive*ly, adv.",
  "kurdish - Of or pertaining to the Kurds. [Written also Koordish.]",
  "goeland - A white tropical tern (Cygis candida).",
  "metabole - A change or mutation; a change of disease, symptoms, or treatment.",
  "subpeduncular - Situated beneath the peduncle; as, the subpeduncular lobe of the cerebellum.",
  "triplasian - Three-fold; triple; treble. [Obs.] Cudworth.",
  "ellachick - A fresh-water tortoise (Chelopus marmoratus) of California; -- used as food.",
  "sublition - The act or process of laying the ground in a painting. [R.]",
  "polyphagous - Eating, or subsisting on, many kinds of food; as, polyphagous animals.",
  "epipubis - A cartilage or bone in front of the pubis in some amphibians and other animals.",
  "galvanoscopy - The use of galvanism in physiological experiments.",
  "hemipteral - Of or pertaining to the Hemiptera.",
  "acidulent - Having an acid quality; sour; acidulous. \"With anxious, acidulent face.\" Carlyle.",
  "collaboration - The act ofworking together; united labor.",
  "incongenial - Not congenial; uncongenial. [R.] -- In`con*ge`ni*al\"i*ty. [R.]",
  "rubefacient - Making red. -- n. (Med.)  An external application which produces redness of the skin.",
  "imitability - The quality of being imitable. Norris.",
  "disenchained - Freed from restraint; unrestrained. [Archaic] E. A. Poe.",
  "tippled - Intoxicated; inebriated; tipsy; drunk. [R.] Dryden.",
  "prettyism - Affectation of a pretty style, manner, etc. [R.] Ed. Rev.",
  "steatitic - Pertaining to, or of the nature of, steatite; containing or resembling steatite.",
  "orthodoxly - In an orthodox manner; with soundness of faith. Sir W. Hamilton.",
  "trifid - Cleft to the middle, or slightly beyond the middle, into three parts; three-cleft.",
  "maidpale - Pale, like a sick girl. Shak.",
  "potence - Potency; capacity. [R.] Sir W. Hamilton.",
  "kippernut - A name given to earthnuts of several kinds.",
  "presidio - A place of defense; a fortress; a garrison; a fortress; a garrison or guardhouse.",
  "phonocamptic - Reflecting sound. [R.] \"Phonocamptic objects.\" Derham.",
  "celibatist - One who lives unmarried. [R.]",
  "cicurate - To tame. [Obs.] Sir T. Browne.",
  "tachygraphical - Of or pertaining to tachygraphy; written in shorthand.",
  "constuprate - To ravish; to debauch. Burton.",
  "sarcologic - Of or pertaining to sarcology.",
  "payen - Pagan. Etym: [F.] [Obs.] Chaucer.",
  "overdate - To date later than the true or proper period. Milton.",
  "cacaine - The essential principle of cacao; -- now called theobromine.",
  "encalendar - To register in a calendar; to calendar. Drayton.",
  "dormancy - The state of being dormant; quiescence; abeyance.",
  "sternness - The quality or state of being stern.",
  "outground - Ground situated at a distance from the house; outlying land.",
  "decury - A set or squad of ten men under a decurion. Sir W. Raleigh.",
  "velvetbreast - The goosander. [Local, U. S.]",
  "suspensible - Capable of being suspended; capable of being held from sinking.",
  "precant - One who prays. [R.] Coleridge.",
  "neoplasm - A new formation or tissue, the product of morbid action.",
  "unlay - To untwist; as, to unlay a rope.",
  "campanology - The art of ringing bells, or a treatise on the art.",
  "disconsolated - Disconsolate. [Obs.] A poor, disconsolated, drooping creature. Sterne.",
  "floriated - Having floral ornaments; as, floriated capitals of Gothic pillars.",
  "missa - The service or sacrifice of the Mass.",
  "macrodiagonal - The longer of two diagonals, as of a rhombic prism. See Crystallization.",
  "outparish - A parish lying without the walls of, or in a remote part of, a town. Graunt.",
  "pentecostal - Of or pertaining to Pentecost or to Whitsuntide.",
  "cantoon - A cotton stuff showing a fine cord on one side and a satiny surface on the other.",
  "lithotypic - Of, pertaining to, or produced by, lithotypy.",
  "toe drop - A morbid condition of the foot in which the toe is depressed and the heel elevated.",
  "omniferous - All-bearing; producing all kinds.",
  "voraginous - Pertaining to a gulf; full of gulfs; hence, devouring. [R.] Mallet.",
  "multiplicator - The number by which another number is multiplied; a multiplier.",
  "perflate - To blow through. [Obs.] Harvey.",
  "configure - To arrange or dispose in a certain form, figure, or shape. Bentley.",
  "offskip - That part of a landscape which recedes from the spectator into distance. [R.] Fairholt.",
  "spendthrifty - Spendthrift; prodigal. [R.]",
  "consarcination - A patching together; patchwork. [Obs.] Bailey.",
  "scissible - Capable of being cut or divided by a sharp instrument. [R.] con.",
  "stintless - Without stint or restraint. The stintlesstears of old Heraclitus. Marston.",
  "capsulated - Inclosed in a capsule, or as in a chest or box.",
  "forslack - To neglect by idleness; to delay or to waste by sloth. [Obs.] Spenser.",
  "guidguid - A South American ant bird of the genus Hylactes; -- called also barking bird.",
  "cheddar - Of or pertaining to, or made at, Cheddar, in England; as, Cheddar cheese.",
  "diarthrodial - Relating to diarthrosis, or movable articulations.",
  "opisometer - An instrument with a revolving wheel for measuring a curved line, as on a map.",
  "double-lock - To lock with two bolts; to fasten with double security. Tatler.",
  "quartine - A supposed fourth integument of an ovule, counting from the outside.",
  "fraight - Same as Fraught. [Obs.] Spenser.",
  "impersonator - One who impersonates; an actor; a mimic.",
  "rome penny - See Peter pence, under Peter.",
  "hereditability - State of being hereditable. Brydges.",
  "flatulence - The state or quality of being flatulent.",
  "herea-bout - 1. About this place; in this vicinity. 2. Concerning this. [Obs.]",
  "gargoulette - A water cooler or jug with a handle and spout; a gurglet. Mollett.",
  "nemalite - A fibrous variety of brucite.",
  "goodlyhead - Goodness; grace; goodliness. [Obs.] Spenser.",
  "overdraft - The act of overdrawing; also, the amount or sum overdrawn.",
  "foreseer - One who foresees or foreknows.",
  "coheirship - The state of being a coheir.",
  "occasioner - One who, or that which, occasions, causes, or produces. Bp. Sanderson.",
  "impugnment - The act of impugning, or the state of being impugned. Ed. Rev.",
  "mameluco - A child born of a white father and Indian mother. [S. Amer.]",
  "orlo - A wind instrument of music in use among the Spaniards.",
  "remercie - To thank. [Obs.] She him remercied as the patron of her life. Spenser.",
  "plenilune - The full moon. [Obs.] B. Jonson.",
  "cremasteric - Of or pertaining to the cremaster; as, the cremasteric artery.",
  "doziness - The state of being dozy; drowsiness; inclination to sleep.",
  "lambale - A feast at the time of shearing lambs.",
  "euhemeristic - Of or pertaining to euhemerism.",
  "saturator - One who, or that which, saturates.",
  "ploughpoint - A detachable share at the extreme front end of the plow body.",
  "improvability - The state or quality of being improvable; improvableness.",
  "whenceforth - From, or forth from, what or which place; whence. [Obs.] Spenser.",
  "pass-key - A key for opening more locks than one; a master key.",
  "capsulate - Inclosed in a capsule, or as in a chest or box.",
  "alternating current - A current which periodically changes or reverses its direction of flow.",
  "eleutheromania - A mania or frantic zeal for freedom. [R.] Carlyle.",
  "electro-puncturation - See Electropuncture.",
  "dead beat - See Beat, n., 7. [Low, U.S.]",
  "hendecagon - A plane figure of eleven sides and eleven angles. [Written also endecagon.]",
  "startish - Apt to start; skittish; shy; -- said especially of a horse. [Colloq.]",
  "arrogantly - In an arrogant manner; with undue pride or self-importance.",
  "bon silene - A very fragrant tea rose with petals of various shades of pink.",
  "operancy - The act of operating or working; operation. [R.]",
  "trout-colored - White, with spots of black, bay, or sorrel; as, a trout-colored horse.",
  "vascularity - The quality or state of being vascular.",
  "self-satisfying - Giving satisfaction to one's self.",
  "umbellifer - A plant producing an umbel or umbels.",
  "ad libitum - . At one's pleasure; as one wishes.",
  "taslet - A piece of armor formerly worn to guard the things; a tasse.",
  "obtuse-angular - Having an obtuse angle; as, an obtuse-angled triangle.",
  "overthwartly - In an overthwart manner;across; also, perversely. [Obs.] Peacham.",
  "unpastor - To cause to be no longer pastor; to deprive of pastorship. [R.] Fuller.",
  "illuminism - The principles of the Illuminati.",
  "aviator - (a) An experimenter in aviation. (b) A flying machine.",
  "rustical - Rustic. \"Rustical society.\" Thackeray. -- Rus\"tic*al*ly, adv. -- Rus\"tic*al*ness, n.",
  "self-destructive - Destroying, or tending to destroy, one's self or itself; rucidal.",
  "seducing - Seductive. \"Thy sweet seducing charms.\" Cowper. -- Se*du\"cing*ly, adv.",
  "cubature - The process of determining the solid or cubic contents of a body.",
  "arachnitis - Inflammation of the arachnoid membrane.",
  "unpraise - To withhold praise from; to deprive of praise. [R.]",
  "wolframate - A salt of wolframic acid; a tungstate.",
  "growthful - Having capacity of growth. [R.] J. Hamilton.",
  "unpervert - To free from perversion; to deliver from being perverted; to reconvert. [Obs.]",
  "orderer - 1. One who puts in order, arranges, methodizes, or regulates. 2. One who gives orders.",
  "seriate - Arranged in a series or succession; pertaining to a series. -- Se\"ri*ate*ly, adv.",
  "statemonger - One versed in politics, or one who dabbles in state affairs.",
  "revengeless - Unrevenged. [Obs.] Marston.",
  "direct primary - A primary by which direct nominations of candidates for office are made.",
  "superinjection - An injection succeeding another.",
  "upbuoyance - The act of buoying up; uplifting. [R.] Coleridge.",
  "myrmidonian - Consisting of, or like, myrmidons. Pope.",
  "hendecasyllable - A metrical line of eleven syllables. J. Warton.",
  "calceated - Fitted with, or wearing, shoes. Johnson.",
  "aggroupment - Arrangement in a group or in groups; grouping.",
  "indistinguished - Indistinct. [R.] \"That indistinguished mass.\" Sir T. Browne.",
  "troublable - Causing trouble; troublesome. [Obs.] troublable ire.\" Chaucer.",
  "bibacity - The practice or habit of drinking too much; tippling. Blount.",
  "climacterical - See Climacteric. Evelyn.",
  "migniardise - Delicate fondling. [Obs.] B. Jonson.",
  "delphinoid - Pertaining to, or resembling, the dolphin.",
  "proofless - Wanting sufficient evidence to induce belief; not proved. Boyle. -- Proof\"less*ly, adv.",
  "micronometer - An instrument for noting minute portions of time.",
  "verbenate - To strew with verbena, or vervain, as in ancient sacrifices and rites.",
  "limberness - The quality or state of being limber; flexibleness. Boyle.",
  "mammalogical - Of or pertaining to mammalogy.",
  "guaranine - An alkaloid extracted from guarana. Same as Caffeine.",
  "heteronomous - Subject to the law of another. Krauth-Fleming.",
  "dwaule - To be delirious. [Obs.] Junius.",
  "sauterne - A white wine made in the district of sauterne, France.",
  "qualifier - , One who, or that which, qualifies; that which modifies, reduces, tempers or restrains.",
  "preordination - The act of foreordaining: previous determination. \"The preordination of God.\" Bale.",
  "croftland - Land of superior quality, on which successive crops are raised. [Scot.] Jamieson.",
  "deiparous - Bearing or bringing forth a god; -- said of the Virgin Mary. [Obs.] Bailey.",
  "hobit - A small mortar on a gun carriage, in use before the howitzer.",
  "festlich - Festive; fond of festive occasions. [Obs.] \"A festlich man.\" Chaucer.",
  "thalamic - Of or pertaining to a thalamus or to thalami.",
  "laudanine - A white organic base, resembling morphine, and obtained from certain varieties of opium.",
  "conspurcation - This act of defiling; defilement; pollution. Bp. Hall.",
  "dryandra - A genus of shrubs growing in Australia, having beautiful, hard, dry, evergreen leaves.",
  "monkeytail - A short, round iron bar or lever used in naval gunnery. Totten.",
  "enlard - To cover or dress with lard or grease; to fatten. Shak.",
  "arenarious - Sandy; as, arenarious soil.",
  "gnathopod - A gnathopodite or maxilliped. See Maxilliped.",
  "quindecemvirate - The body or office of the quindecemviri.",
  "condolatory - Expressing condolence. Smart.",
  "switzer - A native or inhabitant of Switzerland; a Swiss.",
  "andranatomy - The dissection of a human body, especially of a male; androtomy. Coxe.",
  "overhent - To overtake. [Obs.] So forth he went and soon them overhent. Spenser.",
  "maistrie - Mastery; superiority; art. See Mastery. [Obs.] Chaucer.",
  "desponsate - To betroth. [Obs.] Johnson.",
  "inextinguible - Inextinguishable. [Obs.] Sir T. More.",
  "gambit - A mode of opening the game, in which a pawn is sacrificed to gain an attacking position.",
  "stackstand - A staging for supporting a stack of hay or grain; a rickstand.",
  "frisky - Inclined to frisk; frolicsome; gay. He is too frisky for an old man. Jeffrey.",
  "analyzation - The act of analyzing, or separating into constituent parts; analysis.",
  "saturnist - A person of a dull, grave, gloomy temperament. W. browne.",
  "henotic - Harmonizing; irenic. Gladstone.",
  "trekometer - A field range finger used in the British service.",
  "aworking - At work; in action. [Archaic or Colloq.] Spenser.",
  "deciduousness - The quality or state of being deciduous.",
  "intersidereal - Between or among constellations or stars; interstellar.",
  "phasing - Pertaining to phase or differences of phase.",
  "disuniter - One who, or that which, disjoins or causes disunion.",
  "sonties - Probably from \"saintes\" saints, or from sanctities; -- used as an oath. [Obs.] Shak.",
  "sumatran - Of or pertaining to Sumatra or its inhabitants. -- n.  A native of Sumatra.",
  "spurling-line - The line which forms the communication between the steering wheel and the telltale.",
  "inde - Azure-colored; of a bright blue color. [Obs.] Rom. of R.",
  "prancer - A horse which prances. Then came the captain . . . upon a brave prancer. Evelyn.",
  "testaceology - The science of testaceous mollusks; conchology. [R.]",
  "denture - An artificial tooth, block, or set of teeth.",
  "nutty - 1. Abounding in nuts. 2. Having a flavor like that of nuts; as, nutty wine.",
  "resurrectionize - To raise from the dead. [R.] Southey.",
  "widdy - A rope or halter made of flexible twigs, or withes, as of birch. [Scot.]",
  "goodwife - The mistress of a house. [Archaic] Robynson (More's Utopia).",
  "retroactively - In a retroactive manner.",
  "peridrome - The space between the columns and the wall of the cella, in a Greek or a Roman temple.",
  "fistular - Hollow and cylindrical, like a pipe or reed. Johnson.",
  "enlarged - Made large or larger; extended; swollen. -- En*lar\"ged*ly, adv. -- En*lar\"ged*ness, n.",
  "intriguery - Arts or practice of intrigue.",
  "intestacy - The state of being intestate, or of dying without having made a valid will. Blackstone.",
  "extratropical - Beyond or outside of the tropics. Whewell.",
  "ganger - One who oversees a gang of workmen. [R.] Mayhew.",
  "suspiciency - Suspiciousness; suspicion. [Obs.] Hopkins.",
  "deliberatively - In a deliberative manner; circumspectly; considerately.",
  "scythestone - A stone for sharpening scythes; a whetstone.",
  "exocetus - A genus of fishes, including the common flying fishes. See Flying fish.",
  "guze - A roundlet of tincture sanguine, which is blazoned without mention of the tincture.",
  "votist - One who makes a vow. [Obs.] Chapman.",
  "alomancy - Divination by means of salt. [Spelt also halomancy.] Morin.",
  "tsar - The title of the emperor of Russia. See Czar.",
  "ardently - In an ardent manner; eagerly; with warmth; affectionately; passionately.",
  "to-brest - To burst or break in pieces. [Obs.] Chaucer.",
  "erubescency - The act of becoming red; redness of the skin or surface of anything; a blushing.",
  "cypripedium - A genus of orchidaceous plants including the lady's slipper.",
  "altissimo - The part or notes situated above F in alt.",
  "flaxy - Like flax; flaxen. Sir M. Sandys.",
  "zincking - The act or process of applying zinc; galvanization.",
  "indenting - Indentation; an impression like that made by a tooth.",
  "fanega - A dry measure in Spain and Spanish America, varying from 1 De Colange.",
  "imposturage - Imposture; cheating. [R.] Jer. Taylor.",
  "nosological - Of or pertaining to nosology.",
  "philosophistical - Of or pertaining to the love or practice of sophistry. [R.]",
  "dovish - Like a dove; harmless; innocent. \"Joined with dovish simplicity.\" Latimer.",
  "heaving - A lifting or rising; a swell; a panting or deep sighing. Addison. Shak.",
  "serrous - Like the teeth off a saw; jagged. [Obs.] Sir T. Browne.",
  "universalistic - Of or pertaining to the whole; universal.",
  "bandon - Disposal; control; license. [Obs.] Rom. of R.",
  "inoperation - Agency; influence; production of effects. [Obs.] Bp. Hall.",
  "outclimb - To climb bevond; to surpass in climbing. Davenant.",
  "divorcive - Having power to divorce; tending to divorce. \"This divorcive law.\" Milton.",
  "sleeved - Having sleeves; furnished with sleeves; -- often in composition; as, long-sleeved.",
  "brahmoism - The religious system of Brahmo-somaj. Balfour.",
  "cephalalgic - Relating to, or affected with, headache. -- n.  A remedy for the headache.",
  "sitz bath - A tub in which one bathes in a sitting posture; also, a bath so taken; a hip bath.",
  "thrumwort - A kind of amaranth (Amarantus caudatus). Dr. Prior.",
  "valve-shell - Any fresh-water gastropod of the genus Valvata.",
  "strictured - Affected with a stricture; as, a strictured duct.",
  "stillatitious - Falling in drops; drawn by a still.",
  "cementer - A person or thing that cements.",
  "annulation - A circular or ringlike formation; a ring or belt. Nicholson.",
  "puckerer - One who, or that which, puckers.",
  "scrutator - One who scrutinizes; a close examiner or inquirer. Ayliffe.",
  "metaphysically - In the manner of metaphysical science, or of a metaphysician. South.",
  "metasilicate - A salt of metasilicic acid.",
  "vulgarization - The act or process of making vulgar, or common.",
  "intentively - Attentively; closely. [Obs.] \"Intentively to observe.\" Holland.",
  "ovidian - Of or pertaining to the Latin poet Ovid; resembling the style of Ovid.",
  "torpedo body - An automobile body which is built so that the side surfaces are flush. [Cant]",
  "waterer - One who, or that which, waters.",
  "spannishing - The full blooming of a flower. [Obs.] Rom. of R.",
  "fore tooth - One of the teeth in the forepart of the mouth; an incisor.",
  "uncastle - To take a castle from; to turn out of a castle.",
  "armet - A kind of helmet worn in the 14th, 15th, and 16th centuries.",
  "cushiony - Like a cushion; soft; pliable. A flat and cushiony noce. Dickens.",
  "gabelle - A tax, especially on salt. [France] Brande & C.",
  "uncorrigible - Incorrigible; not capable of correction. [Obs.]",
  "inexorability - The quality of being inexorable, or unyielding to entreaty. Paley.",
  "leptomeningitis - Inflammation of the pia mater or of the arachnoid membrane.",
  "munjeet - See Indian madder, under Madder.",
  "proxyship - The office or agency of a proxy.",
  "endlessness - The quality of being endless; perpetuity.",
  "sutile - Done by stitching. [R.] Boswell.",
  "copist - A copier. [Obs.] \"A copist after nature.\" Shaftesbury.",
  "addle-head - A foolish or dull-witted fellow. [Colloq.]",
  "circumlocutional - Relating to, or consisting of, circumlocutions; periphrastic; circuitous.",
  "lirella - A linear apothecium furrowed along the middle; the fruit of certain lichens.",
  "convexed - Made convex; protuberant in a spherical form. Sir T. Browne.",
  "oculiform - In the form of an eye; resembling an eye; as, an oculiform pebble.",
  "depredicate - To proclaim; to celebrate. [R.]",
  "turbary - A right of digging turf on another man's land; also, the ground where turf is dug.",
  "antrustion - A vassal or voluntary follower of Frankish princes in their enterprises.",
  "osteogeny - The formation or growth of bone.",
  "scoptic - Jesting; jeering; scoffing. [Obs.] South. -- Scop\"tic*al*ly, adv. [Obs.]",
  "enclitics - The art of declining and conjugating words.",
  "rationalization - The act or process of rationalizing.",
  "blue-eye - The blue-cheeked honeysucker of Australia.",
  "ranker - One who ranks, or disposes in ranks; one who arranges.",
  "phthisiology - A treatise on phthisis. Dunglison.",
  "aknow - Earlier form of Acknow. [Obs.] To be aknow, to acknowledge; to confess. [Obs.]",
  "epiplexis - A figure by which a person seeks to convince and move by an elegant kind of upbraiding.",
  "overmuch - Too much. -- adv.  In too great a degree; too much. -- n.  An excess; a surplus.",
  "gatewise - In the manner of a gate. Three circles of stones set up gatewise. Fuller.",
  "phosphorized - Containing, or impregnated with, phosphorus.",
  "interpedencular - Between peduncles; esp., between the peduncles, or crura, of the cerebrum.",
  "afrit - A powerful evil jinnee, demon, or monstrous giant.",
  "applicancy - The quality or state of being applicable. [R.]",
  "bladdery - Having bladders; also, resembling a bladder.",
  "rogueship - The quality or state of being a rogue. [Jocose] \"Your rogueship.\" Dryden.",
  "hoit - To leap; to caper; to romp noisily. [Obs.] Beau. & Fl.",
  "unmeant - Not meant or intended; unintentional. Dryden.",
  "regenerateness - The quality or state of being rgenerate.",
  "didal - A kind of triangular spade. [Obs.]",
  "enlightenment - Act of enlightening, or the state of being enlightened or instructed.",
  "prospectively - In a prospective manner.",
  "playground - A piece of ground used for recreation; as, the playground of a school.",
  "azoleic - Pertaining to an acid produced by treating oleic with nitric acid. [R.]",
  "gryphite - A shell of the genus Gryphea.",
  "helio- - A combining form from Gr. \"h`lios the sun.",
  "unface - To remove the face or cover from; to unmask; to expose.",
  "strifeful - Contentious; discordant. The ape was strifeful and ambitious. Spenser.",
  "chargeably - At great cost; expensively. [Obs.]",
  "animalcular - Of, pertaining to, or resembling, animalcules. \"Animalcular life.\" Tyndall.",
  "despumate - To throw off impurities in spume; to work off in foam or scum; to foam.",
  "pled - imp. & p. p. of Plead [Colloq.] Spenser.",
  "unexceptive - Not exceptive; not including, admitting, or being, an exception.",
  "inveil - To cover, as with a vail. W. Browne.",
  "premonstrator - One who, or that which, premonstrates. [R.]",
  "advolution - A rolling toward something. [R.]",
  "leafcup - A coarse American composite weed (Polymnia Uvedalia).",
  "aperea - The wild Guinea pig of Brazil (Cavia aperea).",
  "stereotypographer - A stereotype printer.",
  "quelquechose - A trifle; a kickshaw. Donne.",
  "innermostly - In the innermost place. [R.] His ebon cross worn innermostly. Mrs. Browning.",
  "excentricity - . (Math.) Same as Eccentricity.",
  "calyon - Flint or pebble stone, used in building walls, etc. Haliwell.",
  "interosseous - Situated between bones; as, an interosseous ligament.",
  "informous - Of irregular form; shapeless. [Obs.] Sir T. Browne.",
  "multinodate - Having many knots or nodes.",
  "octamerous - Having the parts in eights; as, an octamerous flower; octamerous mesenteries in polyps.",
  "megasthenic - Having a typically large size; belonging to the megasthenes.",
  "skyed - Surrounded by sky. [Poetic & R.] \"The skyed mountain.\" Thomson.",
  "binuclear - Having two nuclei; as, binucleate cells.",
  "prenomination - The act of prenominating; privilege of being named first. Sir T. Browne.",
  "hispanicize - To give a Spanish form or character to; as, to Hispanicize Latin words.",
  "cupulate - Having or bearing cupeles; cupuliferous.",
  "aliferous - Having wings, winged; aligerous. [R.]",
  "electron - Amber; also, the alloy of gold and silver, called electrum.",
  "lentoid - Having the form of a lens; lens-shaped.",
  "compliancy - Compliance; disposition to yield to others. Goldsmith.",
  "discursion - The act of discoursing or reasoning; range, as from thought to thought. Coleridge.",
  "in transitu - In transit; during passage; as, goods in transitu.",
  "disfavorable - Unfavorable. [Obs.] Stow.",
  "omnifarious - Of all varieties, forms, or kinds. \"Omnifarious learning.\" Coleridge.",
  "secularness - The quality or state of being secular; worldliness; worldly- minded-ness.",
  "twelfthtide - The twelfth day after Christmas; Epiphany; -- called also Twelfth-day.",
  "parochialize - To render parochial; to form into parishes.",
  "calyptriform - Having the form a calyptra, or extinguisher.",
  "irreconcilability - The quality or state of being irreconcilable; irreconcilableness.",
  "dressmaking - The art, process, or occupation, of making dresses.",
  "commutability - The quality of being commutable.",
  "anchoress - A female anchoret. And there, a saintly anchoress, she dwelt. Wordsworth.",
  "nudum pactum - A bare, naked contract, without any consideration. Tomlins.",
  "grass-grown - Overgrown with grass; as, a grass-grown road.",
  "seminifical - Forming or producing seed, or the male generative product of animals or of plants.",
  "craterous - Pertaining to, or resembling, a crater. [R.] R. Browning.",
  "helminthology - The natural history, or study, of worms, esp. parasitic worms.",
  "itchy - Infected with the itch, or with an itching sensation. Cowper.",
  "subbrachial - Of or pertaining to the subbrachians.",
  "fonly - Foolishly; fondly. [Obs.] Spenser.",
  "echinoid - Of or pertaining to the Echinoidea. -- n.  One of the Echinoidea.",
  "slobberer - 1. One who slobbers. 2. A slovenly farmer; a jobbing tailor. [Prov. Eng.]",
  "cultivable - Capable of being cultivated or tilled. Todd.",
  "heraldship - The office of a herald. Selden.",
  "illegalize - To make or declare illegal or unlawful.",
  "negotious - Very busy; attentive to business; active. [R.] D. Rogers.",
  "rhinoscope - A small mirror for use in rhinoscopy.",
  "greengrocer - A retailer of vegetables or fruits in their fresh or green state.",
  "sagene - A Russian measure of length equal to about seven English feet.",
  "archpriest - A chief priest; also, a kind of vicar, or a rural dean.",
  "interception - The act of intercepting; as, interception of a letter; interception of the enemy.",
  "bewrought - Embroidered. [Obs.] B. Jonson.",
  "compromissorial - Relating to compromise. [R.] Chalmers.",
  "torsibillty - The tendency, as of a rope, to untwist after being twisted.",
  "subjectivist - One who holds to subjectivism; an egoist.",
  "voortreker - One who treks before or first; a pioneer. [South Africa]",
  "bishopdom - Jurisdiction of a bishop; episcopate. \"Divine right of bishopdom.\" Milton.",
  "guidable - Capable of being guided; willing to be guided or counseled. Sprat.",
  "zoophilist - A lover of animals. Southey.",
  "itineracy - The act or practice of itinerating; itinerancy.",
  "plotinian - Of pertaining to the Plotinists or their doctrines.",
  "certitude - Freedom from doubt; assurance; certainty. J. H. Newman.",
  "comptograph - A machine for adding numbers and making a printed record of the sum.",
  "cooter - (a) A fresh-water tortoise (Pseudemus concinna) of Florida. (b) The box tortoise.",
  "emaculate - To clear from spots or stains, or from any imperfection. [Obs.] Hales.",
  "paleozoic era - The Paleozoic time or strata.",
  "warnstore - To furnish. [Obs.] \"To warnstore your house.\" Chaucer.",
  "cross-tining - A mode of harrowing crosswise, or transversely to the ridges. Crabb.",
  "deleble - Capable of being blotted out or erased. \"An impression easily deleble.\" Fuller.",
  "devanagari - The character in which Sanskrit is written.",
  "disinfectant - That which disinfects; an agent for removing the causes of infection, as chlorine.",
  "impinguate - To fatten; to make fat. [Obs.] Bacon.",
  "arbalester - A crossbowman. [Obs.] Speed.",
  "allegretto - Quicker than andante, but not so quick as allegro. -- n.  A movement in this time.",
  "readeption - A regaining; recovery of something lost. [Obs.] Bacon.",
  "bagwig - A wig, in use in the 18th century, with the hair at the back of the head in a bag.",
  "constupration - The act of ravishing; violation; defilement. Bp. Hall.",
  "considerative - Considerate; careful; thoughtful. [Archaic] I love to be considerative. B. Jonson.",
  "sentimentally - In a sentimental manner.",
  "billyboy - A flat-bottomed river barge or coasting vessel. [Eng.]",
  "roral - Of or pertaining to dew; consisting of dew; dewy. [R.] M. Green.",
  "nationalness - The quality or state of being national; nationality. Johnson.",
  "sural - Of or pertaining to the calf of the leg; as, the sural arteries.",
  "nardine - Of or pertaining to nard; having the qualities of nard.",
  "semioxygenated - Combined with oxygen only in part. Kirwan.",
  "arctogeal - Of or pertaining to arctic lands; as, the arctogeal fauna.",
  "hodiern - Of this day; belonging to the present day. [R.] Boyle. Quart. Rev.",
  "enteron - The whole alimentary, or enteric, canal.",
  "floscularian - One of a group of stalked rotifers, having ciliated tentacles around the lobed disk.",
  "outmost - Farthest from the middle or interior; farthest outward; outermost.",
  "outwalk - To excel in walking; to leave behind in walking. B. Jonson.",
  "hythe - A small haven. See Hithe. [Obs.]",
  "hendecasyllabic - Pertaining to a line of eleven syllables.",
  "glandage - A feeding on nuts or mast. [Obs.] Crabb.",
  "slaughterhouse - A house where beasts are butchered for the market.",
  "queenhood - The state, personality, or character of a queen; queenliness. Tennyson.",
  "hygienic - Of or pertaining to health or hygiene; sanitary.",
  "retroaction - 1. Action returned, or action backward. 2. Operation on something past or preceding.",
  "pentyl - The hypothetical radical, C5H11, of pentane and certain of its derivatives. Same as Amyl.",
  "venew - A bout, or turn, as at fencing; a thrust; a hit; a veney. [Obs.] Fuller.",
  "remorate - To hinder; to delay. [Obs.] Johnson.",
  "intagliated - Engraved in intaglio; as, an intagliated stone. T. Warton.",
  "leucophyllous - Having white or silvery foliage.",
  "overdight - Covered over. [Obs.] Spenser.",
  "fattener - One who, or that which, fattens; that which gives fatness or fertility.",
  "smee - (a) The pintail duck. (b) The widgeon. (c) The poachard. (d) The smew. [Prov. Eng.]",
  "logroll - To engage in logrolling; to accomplish by logrolling. [Political cant, U. S.]",
  "extraprovincial - Not within of pertaining to the same province or jurisdiction. Ayliffe.",
  "ciceronian - Resembling Cicero in style or action; eloquent.",
  "eremite - A hermit. Thou art my heaven, and I thy eremite. Keats.",
  "orbical - Spherical; orbicular; orblike; circular. [R.] Bacon.",
  "costated - Having ribs, or the appearance of ribs; (Bot.) having one or more longitudinal ribs.",
  "ladkin - A little lad. [R.] Dr. H. More.",
  "proof-arm - To arm with proof armor; to arm securely; as, to proof-arm herself. [R.] Beau. & Fl.",
  "thermogram - The trace or record made by means of a thermograph.",
  "brainsick - Disordered in the understanding; giddy; thoughtless. -- Brain\"sick*ness, n.",
  "artlessly - In an artless manner; without art, skill, or guile; unaffectedly. Pope.",
  "slowness - The quality or state of being slow.",
  "cataian - A native of Cathay or China; a foreigner; -- formerly a term of reproach. Shak.",
  "misobserve - To observe inaccurately; to mistake in observing. Locke.",
  "rheomotor - Any apparatus by which an electrical current is originated. [R.]",
  "cloom - To close with glutinous matter. [Obs.] Mortimer.",
  "mesopodial - Of or pertaining to the mesopodialia or to the parts of the limbs to which they belong.",
  "paltock - A kind of doublet; a jacket. [Obs.] Piers Plowman.",
  "metamorphoser - One who metamorphoses. [R.] Gascoigne.",
  "chorograph - An instrument for constructing triangles in marine surveying, etc.",
  "dethronization - Dethronement. [Obs.] Speed.",
  "strawy - Of or pertaining to straw; made of, or resembling, straw. Shak.",
  "lunated - Crescent-shaped; as, a lunate leaf; a lunate beak; a lunated cross. Gray.",
  "olivaster - Of the color of the olive; tawny. Sir T. Herbert.",
  "pavisor - A soldier who carried a pavise.",
  "cadillac - A large pear, shaped like a flattened top, used chiefly for cooking. Johnson.",
  "perforative - Having power to perforate or pierce.",
  "towage - 1. The act of towing. 2. The price paid for towing.",
  "gelidness - The state of being gelid; gelidity.",
  "pyromancy - Divination by means of fire.",
  "pausingly - With pauses; haltingly. Shak.",
  "odorament - A perfume; a strong scent. [Obs.] Burton.",
  "dodecasyllabic - Having twelve syllables.",
  "phytopathology - The science of diseases to which plants are liable.",
  "semiannular - Having the figure of a half circle; forming a semicircle. Grew.",
  "diactinic - Capable of transmitting the chemical or actinic rays of light; as, diactinic media.",
  "friended - 1. Having friends; [Obs.] 2. Iuclined to love; well-disposed. [Obs.] Shak.",
  "cauter - A hot iron for searing or cauterizing. Minsheu.",
  "crimpy - Having a crimped appearance; frizzly; as, the crimpy wool of the Saxony sheep.",
  "erethism - A morbid degree of excitement or irritation in an organ. Hoblyn.",
  "improver - One who, or that which, improves.",
  "dimication - A fight; contest. [Obs.] Bp. Hall.",
  "glancingly - In a glancing manner; transiently; incidentally; indirectly. Hakewill.",
  "han - To have; have. [Obs.] Piers Plowman. Him thanken all, and thus they han an end. Chaucer.",
  "magneto- - A prefix meaning pertaining to, produced by, or in some way connected with, magnetism.",
  "falk - The razorbill. [Written also falc, and faik.] [Prov. Eng.]",
  "torilto - A species of Turnix (Turnix sylvatica) native of Spain and Northen Africa.",
  "integropallial - Having the pallial line entire, or without a sinus, as certain bivalve shells.",
  "lutanist - A person that plays on the lute. Johnson.",
  "anaphora - A repetition of a word or of words at the beginning of two or more successive clauses.",
  "oatmeal - 1. Meal made of oats. Gay. 2. (Bot.)  A plant of the genus Panicum; panic grass.",
  "overbrim - To flow over the brim; to be so full as to overflow. [R.]",
  "calculatory - Belonging to calculation. Sherwood.",
  "gradational - By regular steps or gradations; of or pertaining to gradation.",
  "liparite - A quartzose trachyte; rhyolite.",
  "fraying - The skin which a deer frays from his horns. B. Jonson.",
  "au fait - Expert; skillful; well instructed.",
  "kenspeckle - Having so marked an appearance as easily to be recognized. [Scot.]",
  "tobogganer - One who practices tobogganing.",
  "gallein - A red crystalline dyestuff, obtained by heating together pyrogallic and phthalic acids.",
  "craniotomy - The operation of opening the fetal head, in order to effect delivery.",
  "subpodophyllous - Situated under the podophyllous tissue of the horse's foot.",
  "compunct - Affected with compunction; conscience-stricken. [Obs.]",
  "nefasch - Any fish of the genus Distichodus. Several large species inhabit the Nile.",
  "introcession - A depression, or inward sinking of parts.",
  "unendly - Unending; endless. [Obs.] Sir P. Sidney.",
  "vivifical - Giving life; reviving; enlivening. [R.]",
  "indefinable - Incapable of being defined or described; inexplicable. Bp. Reynolds.",
  "rectangularity - The quality or condition of being rectangular, or right-angled.",
  "dendrometer - An instrument to measure the height and diameter of trees.",
  "lamellibranch - One of the Lamellibranchia. Also used adjectively.",
  "pichey - A Brazilian armadillo (Dasypus minutus); the little armadillo. [Written also pichiy.]",
  "yellowish - Somewhat yellow; as, amber is of a yellowish color. -- Yel\"low*ish*ness, n.",
  "encloud - To envelop in clouds; to cloud. [R.] Spenser.",
  "agrypnotic - Anything which prevents sleep, or produces wakefulness, as strong tea or coffee.",
  "unfledged - Not fledged; not feathered; hence, not fully developed; immature. Dryden.",
  "uncrudded - Not cruddled, or curdled. [Obs.] Her breast like to a bowl of cream uncrudded. Spenser.",
  "pulvinar - A prominence on the posterior part of the thalamus of the human brain.",
  "precation - The act of praying; supplication; entreaty. Cotton.",
  "fiddlestick - The bow, strung with horsehair, used in playing the fiddle; a fiddle bow.",
  "winnowing - The act of one who, or that which, winnows.",
  "noematic - Of or pertaining to the understanding. [Obs.] Cudworth.",
  "outre - Being out of the common course or limits; extravagant; bizarre.",
  "astringer - A falconer who keeps a goschawk. [Obs.] Shak. Cowell. [Written also austringer.]",
  "rowed - Formed into a row, or rows; having a row, or rows; as, a twelve-rowed ear of corn.",
  "self-opinioned - Having a high opinion of one's self; opinionated; conceited. South.",
  "lap-jointed - Having a lap joint, or lap joints, as many kinds of woodwork and metal work.",
  "uglesome - Ugly. [Obs.] \"Such an uglesome countenance.\" Latimer.",
  "osteologer - One versed in osteology; an osteologist.",
  "shardy - Having, or consisting of, shards.",
  "bridalty - Celebration of the nuptial feast. [Obs.] \"In honor of this bridalty.\" B. Jonson.",
  "seismographic - Of or pertaining to a seismograph; indicated by a seismograph.",
  "unfriend - One not a friend; an enemy. [R.] Carlyle.",
  "gynandromorph - An animal affected with gynandromorphism,",
  "transmove - To move or change from one state into another; to transform. [Obs.] Spenser.",
  "arminianism - The religious doctrines or tenets of the Arminians.",
  "earles penny - Earnest money. Same as Arles penny. [Obs.]",
  "rehibition - The returning of a thing purchased to the seller, on the ground of defect or frand.",
  "dreamless - Free from, or without, dreams. Camden. -- Dream\"less*ly, adv.",
  "inburning - Burning within. Her inburning wrath she gan abate. Spenser.",
  "monotheism - The doctrine or belief that there is but one God.",
  "conscribe - To enroll; to enlist. [Obs.] E. Hall.",
  "fovilla - One of the fine granules contained in the protoplasm of a pollen grain.",
  "repealability - The quality or state of being repealable.",
  "radiotelegram - A message transmitted by radiotelegraph.",
  "briolette - An oval or pearshaped diamond having its entire surface cut in triangular facets.",
  "hellhound - A dog of hell; an agent of hell. A hellhound, that doth hunt us all to death. Shak.",
  "regle - To rule; to govern. [Obs.] \"To regle their lives.\" Fuller.",
  "cowblakes - Dried cow dung used as fuel.[Prov. Eng.] Simmonds.",
  "thickness - The quality or state of being thick (in any of the senses of the adjective).",
  "misdepart - To distribute wrongly. [Obs.] He misdeparteth riches temporal. Chaucer.",
  "copartnery - the state of being copartners in any undertaking. [R.]",
  "exhumation - The act of exhuming that which has been buried; as, the exhumation of a body.",
  "hydroxanthane - A persulphocyanate. [Obs.]",
  "suburbed - Having a suburb or suburbs on its outer part.",
  "complaintful - Full of complaint. [Obs.]",
  "precedented - Having a precedent; authorized or sanctioned by an example of a like kind. Walpole.",
  "moistness - The quality or state of being moist.",
  "helmwind - A wind attending or presaged by the cloud called helm. [Prov. Eng.]",
  "maziness - The state or quality of being mazy.",
  "torpescent - Becoming torpid or numb. Shenstone.",
  "employable - Capable of being employed; capable of being used; fit or proper for use. Boyle.",
  "eventerate - To rip open; todisembowel. [Obs.] Sir. T. Brown.",
  "continently - In a continent manner; chastely; moderately; temperately.",
  "clicky - Resembling a click; abounding in clicks. \"Their strange clicky language.\" The Century.",
  "uvulatome - An instrument for removing the uvula.",
  "illecebration - Allurement. [R.] T. Brown.",
  "eyestalk - One of the movable peduncles which, in the decapod Crustacea, bear the eyes at the tip.",
  "kaleidoscopical - Of, pertaining to, or formed by, a kaleidoscope; variegated.",
  "exprobratory - Expressing reproach; upbraiding; reproachful. [R.] Sir A. Shirley.",
  "rocking-horse - The figure of a horse, mounted upon rockers, for children to ride.",
  "spunky - Full of spunk; quick; spirited. [Colloq.]",
  "clucking - The noise or call of a brooding hen.",
  "distracter - One who, or that which, distracts away.",
  "pithiness - The quality or state of being pithy.",
  "sexradiate - Having six rays; -- said of certain sponge spicules. See Illust. of Spicule.",
  "evolatical - Apt to fly away. [Obs. or R.] Blount.",
  "deuteronomy - The fifth book of the Pentateuch, containing the second giving of the law by Moses.",
  "frore - Frostily. [Obs.] The parching air Burns frore, and cold performs the effect of fire. Milton.",
  "by-wash - The outlet from a dam or reservoir; also, a cut to divert the flow of water.",
  "iconograph - An engraving or other picture or illustration for a book.",
  "ideological - Of or pertaining to ideology.",
  "vixenly - Like a vixen; vixenish. Barrow.",
  "hotel-de-ville - A city hall or townhouse.",
  "outdweller - One who holds land in a parish, but lives elsewhere. [Eng.]",
  "discontentation - Discontent. [Obs.] Ascham.",
  "isomorphous - Having the quality of isomorphism.",
  "invaletudinary - Wanting health; valetudinary. [R.]",
  "outrunner - An offshoot; a branch. [R.] \"Some outrunner of the river.\" Lauson.",
  "teint - Tint; color; tinge, See Tint. [Obs.] Time shall . . . embrown the teint. Dryden.",
  "refix - To fix again or anew; to establish anew. Fuller.",
  "nazaritism - The vow and practice of a Nazarite.",
  "troppo - Too much; as, allegro ma non troppo, brisk but not too much so.",
  "tetrathionate - A salt of tetrathionic acid.",
  "polycarpellary - Composed of several or numerous carpels; -- said of such fruits as the orange.",
  "scalary - Resembling a ladder; formed with steps. [Obs.] Sir T. Browne.",
  "endostyle - A fold of the endoderm, which projects into the blood cavity of ascidians. See Tunicata.",
  "blindstory - The triforium as opposed to the clearstory.",
  "recondensation - The act or process of recondensing.",
  "coupure - A passage cut through the glacis to facilitate sallies by the besieged. Wilhelm.",
  "unpardonable - Not admitting of pardon or forgiveness; inexcusable.",
  "presidentship - The office and dignity of president; presidency. Hooker.",
  "shiver-spar - A variety of calcite, so called from its slaty structure; -- called also slate spar.",
  "haystack - A stack or conical pile of hay in the open air.",
  "scriber - A sharp-pointed tool, used by joiners for drawing lines on stuff; a marking awl.",
  "emboyssement - An ambush. [Obs.] Chaucer.",
  "rumbler - One who, or that which, rumbles.",
  "polypragmaty - The state of being overbusy. [R.]",
  "symbolistic - Characterized by the use of symbols; as, symbolistic poetry.",
  "earthiness - The quality or state of being earthy, or of containing earth; hence, grossness.",
  "superessential - Essential above others, or above the constitution of a thing. J. Ellis.",
  "psellism - Indistinct pronunciation; stammering.",
  "seid - A descendant of Mohammed through his daughter Fatima and nephew Ali.",
  "ignorantism - The spirit of those who extol the advantage to ignorance; obscuriantism.",
  "semicalcareous - Half or partially calcareous; as, a semicalcareous plant.",
  "inventorial - Of or pertaining to an inventory. -- In`ven*to\"ri*al*ly, adv. Shak.",
  "morioplasty - The restoration of lost parts of the body.",
  "unexpert - Not expert; inexpert. Milton.",
  "heliciform - Having the form of a helix; spiral.",
  "altiloquence - Lofty speech; pompous language. [R.] Bailey.",
  "stradometrical - Of, or relating to, the measuring of streets or roads. [R.]",
  "chirologist - One who communicates thoughts by signs made with the hands and fingers.",
  "collarette - A small collar; specif., a woman's collar of lace, fur, or other fancy material.",
  "flannen - Made or consisting of flannel. [Obs.] \"Flannen robes.\" Dryden.",
  "obdured - Obdurate; hard. [Obs.] This saw his hapless foes, but stood obdured. Milton.",
  "pronounceable - Capable of being pronounced.",
  "traitoress - A traitress. [Obs.] Rom. of R.",
  "bivaulted - Having two vaults or arches.",
  "fraischeur - Freshness; coolness. [R.] Dryden.",
  "singult - A sigh or sobbing; also, a hiccough. [Obs.] Spenser. W. Browne.",
  "siluridan - Any fish of the family Silurid or of the order Siluroidei.",
  "exercisable - That may be exercised, used, or exerted.",
  "overwrought - Wrought upon excessively; overworked; overexcited.",
  "historiography - The art of employment of an historiographer.",
  "countervote - To vote in opposition ti; to balance or overcome by viting; to outvote. Dr. J. Scott.",
  "vaticinator - One who vaticinates; a prophet.",
  "pedaneous - Going on foot; pedestrian. [R.]",
  "spaghetti - A variety or macaroni made in tubes of small diameter.",
  "outreason - To excel or surpass in reasoning; to reason better than. South.",
  "endopleura - The inner coating of a seed. See Tegmen.",
  "decylic - Allied to, or containing, the radical decyl.",
  "oxyacetic - Hydroxyacetic; designating an acid called also glycolic acid.",
  "misnurture - To nurture or train wrongly; as, to misnurture children. Bp. Hall.",
  "earlock - A lock or curl of hair near the ear; a lovelock. See Lovelock.",
  "spermic - Of or pertaining to sperm, or semen.",
  "chromogenic - Containing, or capable of forming, chromogen; as, chromogenic bacteria.",
  "potale - The refuse from a grain distillery, used to fatten swine.",
  "continuo - Basso continuo, or continued bass.",
  "foreordination - Previous ordination or appointment; predetermination; predestination.",
  "clergyable - Entitled to, or admitting, the benefit of clergy; as, a clergyable felony. Blackstone.",
  "hypnotize - To induce hypnotism in; to place in a state of hypnotism.",
  "pesky - Pestering; vexatious; troublesome. Used also as an intensive. [Colloq. & Low, U.S.] Judd.",
  "disinterment - The act of disinterring, or taking out of the earth; exhumation.",
  "agrostological - Pertaining to agrostology.",
  "approof - 1. Trial; proof. [Archaic] Shak. 2. Approval; commendation. Shak.",
  "depopulacy - Depopulation; destruction of population. [R.] Chapman.",
  "perineorrhaphy - The operation of sewing up a ruptured perineum.",
  "dedecoration - Disgrace; dishonor. [Obs.] Bailey.",
  "pilot balloon - A small, unmanned balloon sent up to indicate the direction of air currents.",
  "dedecorate - To bring to shame; to disgrace. [Obs.] Bailey.",
  "unculpable - Inculpable; not blameworthy. [R.] Hooker.",
  "interspersion - The act of interspersing, or the state of being interspersed.",
  "septuary - Something composed of seven; a week. [R.] Ash.",
  "drawspring - The spring to which a drawbar is attached.",
  "anthropophuism - Human nature. [R.] Gladstone.",
  "jobation - A scolding; a hand, tedious reproof. [Law] Grose.",
  "panderism - The employment, arts, or practices of a pander. Bp. Hall.",
  "bilinguous - Having two tongues, or speaking two languages. [Obs.]",
  "pursuable - Capable of being, or fit to be, pursued, followed, or prosecuted. Sherwood.",
  "genian - Of or pertaining to the chin; mental; as, the genian prominence.",
  "plebeiance - 1. Plebeianism. [Obs.] 2. Plebeians, collectively. [Obs.]",
  "water chickweed - A small annual plant (Montia fontana) growing in wet places in southern regions.",
  "bumptious - Self-conceited; forward; pushing. [Colloq.] Halliwell.",
  "ruby-tailed - Having the tail, or lower part of the body, bright red.",
  "dilluing - A process of sorting ore by washing in a hand sieve. [Written also deluing.]",
  "subaid - To aid secretly; to assist in a private manner, or indirectly. [R.] Daniel.",
  "compte rendu - A report of an officer or agent.",
  "saltire - A St. Andrew's cross, or cross in the form of an X, -- one of the honorable ordinaries.",
  "rebaptize - To baptize again or a second time.",
  "one-hand - Employing one hand; as, the one-hand alphabet. See Dactylology.",
  "complainable - That may be complained of. [R.] Feltham.",
  "fomalhaut - A star of the first magnitude, in the constellation Piscis Australis, or Southern Fish.",
  "calker - 1. One who calks. 2. A calk on a shoe. See Calk, n., 1.",
  "hires - Hers; theirs. See Here, pron. [Obs.] Chaucer.",
  "praesternum - Same as Preoral, Prepubis, Prescapula, etc.",
  "unobedient - Disobedient. [Obs.] Milton.",
  "ypsiloid - In the form of the letter Y; Y-shaped.",
  "foolhardihood - The state of being foolhardy; foolhardiness.",
  "anthobian - A beetle which feeds on flowers.",
  "rayonnant - Darting forth rays, as the sun when it shines out.",
  "atmospherology - The science or a treatise on the atmosphere.",
  "sensorial - Of or pertaining to the sensorium; as, sensorial faculties, motions, powers. A. Tucker.",
  "demonomania - A form of madness in which the patient conceives himself possessed of devils.",
  "multigranulate - Having, or consisting of, many grains.",
  "quiddany - A confection of quinces, in consistency between a sirup and marmalade.",
  "thrillant - Piercing; sharp; thrilling. [Obs.] \"His thrillant spear.\" Spenser.",
  "anaseismic - Moving up and down; -- said of earthquake shocks.",
  "underpart - A subordinate part. It should be lightened with underparts of mirth. Dryden.",
  "nutant - Nodding; having the top bent downward.",
  "mackintosh - A waterproof outer garment; -- so called from the name of the inventor.",
  "water blackbird - The European water ousel, or dipper.",
  "sorghe - The three-beared rocking, or whistlefish. [Prov. Eng.]",
  "protectingly - By way of protection; in a protective manner.",
  "carbonarism - The principles, practices, or organization of the Carbonari.",
  "hysteranthous - Having the leaves expand after the flowers have opened. Henslow.",
  "depriment - Serving to depress. [R.] \"Depriment muscles.\" Derham.",
  "uncut velvet - A fabric woven like velvet, but with the loops of the warp threads uncut.",
  "ejaculator - A muscle which helps ejaculation.",
  "aruspicy - Prognostication by inspection of the entrails of victims slain sacrifice.",
  "fortissimo - Very loud; with the utmost strength or loudness.",
  "rossel - Light land; rosland. [Obs. or Prov. Eng.] Mortimer.",
  "sternothyroid - Of or pertaining to the sternum and the thyroid cartilage.",
  "diverticle - 1. A turning; a byway; a bypath. [Obs.] Hales. 2. (Anat.)  A diverticulum.",
  "carthamin - A red coloring matter obtained from the safflower, or Carthamus tinctorius.",
  "declass - To remove from a class; to separate or degrade from one's class.  North Am. Rev.",
  "demephitize - To purify from mephitic. -- De*meph`i*ti*za\"tion, n.",
  "clamminess - State of being clammy or viscous.",
  "erastianism - The principles of the Erastains.",
  "tormentry - Anything producing torment, annoyance, or pain. [Obs.] Chaucer.",
  "mutuation - The act of borrowing or exchanging. [Obs.] Bp. Hall.",
  "sycock - The missel thrush. [Prov. Eng.]",
  "chiminage - A toll for passage through a forest. [Obs.] Cowell.",
  "interreceive - To receive between or within.",
  "sentencer - One who pronounced a sentence or condemnation.",
  "thermotical - Of or pertaining to heat; produced by heat; as, thermotical phenomena. Whewell.",
  "legislatorial - Of or pertaining to a legislator or legislature.",
  "enfever - To excite fever in. [R.] A. Seward.",
  "supperless - Having no supper; deprived of supper; as, to go supperless to bed. Beau. & Fl.",
  "gentlemanhood - The qualities or condition of a gentleman. [R.] Thackeray.",
  "fissilingual - Having the tongue forked.",
  "excremental - Of or pertaining to excrement.",
  "exarillate - Having no aril; -- said of certain seeds, or of the plants producing them.",
  "ocarina - A kind of small simple wind instrument.",
  "wagonry - Conveyance by means of a wagon or wagons. [Obs.] Milton.",
  "whistlingly - In a whistling manner; shrilly.",
  "muggy - 1. Moist; damp; moldy; as, muggy straw. 2. Warm, damp, and close; as, muggy air, weather.",
  "centricity - The state or quality of being centric; centricalness.",
  "clootie - 1.  A little hoof. 2.  The Devil. \"Satan, Nick, or Clootie.\"  Burns.",
  "prorector - An officer who presides over the academic senate of a German university. Heyse.",
  "inshaded - Marked with different shades. W. Browne.",
  "strictness - Quality or state of being strict.",
  "legislatrix - A woman who makes laws. Shaftesbury.",
  "agrostologic - Pertaining to agrostology.",
  "praefoliation - Same as Prefoliation. Gray.",
  "mateology - A vain, unprofitable discourse or inquiry. [R.]",
  "alfilaria - The pin grass (Erodium cicutarium), a weed in California.",
  "undumpish - To relieve from the dumps. [Obs.] Fuller.",
  "shader - One who, or that which, shades.",
  "reviler - One who reviles. 1. Cor. vi. 10.",
  "myristone - The ketone of myristic acid, obtained as a white crystalline substance.",
  "pentagram - A pentacle or a pentalpha. \"Like a wizard pentagram.\" Tennyson.",
  "sombrero - A kind of broad-brimmed hat, worn in Spain and in Spanish America. Marryat.",
  "self-contradictory - Contradicting one's self or itself.",
  "homoeomorphous - Manifesting homoeomorphism.",
  "giblet - Made of giblets; as, a giblet pie.",
  "longinquity - Greatness of distance; remoteness. [R.] Barrow.",
  "supplicator - One who supplicates; a supplicant.",
  "tetractinellid - Any species of sponge of the division Tetractinellida. Also used adjectively.",
  "ereption - A snatching away. [Obs.] Cockeram.",
  "planimetric - Of or pertaining to planimetry.",
  "calcarine - Pertaining to, or situated near, the calcar of the brain.",
  "strawboard - Pasteboard made of pulp of straw.",
  "purprise - A close or inclosure; the compass of a manor. Bacon.",
  "courtling - A sycophantic courtier. B. Jonson.",
  "emperorship - The rank or office of an emperor.",
  "deplanate - Flattened; made level or even.",
  "hobbist - One who accepts the doctrines of Thomas Hobbes.",
  "pernicity - Swiftness; celerity. [R.] Ray.",
  "preciousness - The quality or state of being precious; costliness; dearness.",
  "sheep-headed - Silly; simple-minded; stupid. Taylor (1630)",
  "agoing - In motion; in the act of going; as, to set a mill agoing.",
  "premunitory - Of or pertaining to a premunire; as, a premunitory process.",
  "whipstock - The rod or handle to which the lash of a whip is fastened.",
  "turney - Tourney. [Obs.] Chaucer. \"In open turney.\" Spenser. Milton.",
  "gyrostatic - Of or pertaining to the gyrostat or to gyrostatics.",
  "tappester - A female tapster. [Obs.] Chaucer.",
  "glossarially - In the manner of a glossary.",
  "dampish - Moderately damp or moist. -- Damp\"ish*ly, adv. -- Damp\"ish*ness, n.",
  "amazonite - A variety of feldspar, having a verdigris-green color.",
  "ionize - To separate (a compound) into ions, esp. by dissolving in water. --I`on*i*za\"tion (#), n.",
  "repullulation - The act of budding again; the state of having budded again.",
  "galley-bird - The European green woodpecker; also, the spotted woodpecker. [Prov. Eng.]",
  "unbear - To remove or loose the bearing rein of (a horse).",
  "unlaugh - To recall, as former laughter. [Obs. & R.] Sir T. More.",
  "actionary - A shareholder in joint-stock company. [Obs.]",
  "tyrannicide - 1. The act of killing a tyrant. Hume. 2. One who kills a tyrant.",
  "acrocephalic - Characterized by a high skull.",
  "corporealness - Corporeality; corporeity.",
  "perfectibilist - A perfectionist. See also Illuminati, 2. [R.]",
  "salicyl - The hypothetical radical of salicylic acid and of certain related compounds.",
  "didelphia - The subclass of Mammalia which includes the marsupials. See Marsupialia.",
  "thuriferous - Producing or bearing frankincense.",
  "parisienne - A female native or resident of Paris.",
  "apathetic - Void of feeling; not susceptible of deep emotion; passionless; indifferent.",
  "cholericly - In a choleric manner; angrily.",
  "yerd - See 1st & 2d Yard. [Obs.] Chaucer.",
  "saucily - In a saucy manner; impudently; with impertinent boldness. Addison.",
  "candlestick - An instrument or utensil for supporting a candle.",
  "invection - An inveighing against; invective. [Obs.] Fulke.",
  "poultive - A poultice. [Obs.] W. Temple.",
  "importunely - In an importune manner. [Obs.]",
  "exonerator - One who exonerates or frees from obligation.",
  "pointsman - A man who has charge of railroad points or switches. [Eng.]",
  "megerg - One of the larger measures of work, amounting to one million ergs; -- called also megalerg.",
  "lanky - Somewhat lank. Thackeray. The lanky Dinka, nearly seven feet in height. The Century.",
  "candidacy - The position of a candidate; state of being a candidate; candidateship.",
  "priorship - The state or office of prior; priorate.",
  "piedmont - Noting the region of foothills near the base of a mountain chain.",
  "scleroderma - A disease of adults, characterized by a diffuse rigidity and hardness of the skin.",
  "tajassu - The common, or collared, peccary.",
  "moha - A kind of millet (Setaria Italica); German millet.",
  "preterimperfect - Old name of the tense also called imperfect.",
  "steep-up - Lofty and precipitous. [R.] Her stand she takes upon a steep-up hill. Shak.",
  "cancan - A rollicking French dance, accompanied by indecorous or extravagant postures and gestures.",
  "pyrena - A nutlet resembling a seed, or the kernel of a drupe. Gray.",
  "remissful - Inclined to remit punishment; lenient; clement. Drayton.",
  "connectively - In connjunction; jointly.",
  "perturbability - The quality or state of being perturbable.",
  "pappiform - Resembling the pappus of composite plants.",
  "requicken - To quicken anew; to reanimate; to give new life to. Shak.",
  "sustainment - The act of sustaining; maintenance; support. Milton. Lowell.",
  "pianist - A performer, esp. a skilled performer, on the piano.",
  "pilgarlic - One who has lost his hair by disease; a sneaking fellow, or one who is hardly used.",
  "incumbently - In an incumbent manner; so as to be incumbent.",
  "raip - A rope; also, a measure equal to a rod. [Scot.]",
  "dexterousness - The quality of being dexterous; dexterity.",
  "palsied - Affected with palsy; paralyzed.",
  "imbrocado - Cloth of silver or of gold. [R.]",
  "latitudinal - Of or pertaining to latitude; in the direction of latitude.",
  "pas - 1. A pace; a step, as in a dance. Chaucer. 2. Right of going foremost; precedence. Arbuthnot.",
  "disregardfully - Negligently; heedlessly.",
  "remanet - A case for trial which can not be tried during the term; a postponed case. [Eng.]",
  "excursionist - One who goes on an excursion, or pleasure trip.",
  "enforcive - Serving to enforce or constrain; compulsive. Marsion. -- En*for\"cive*ly, adv.",
  "anorexy - Want of appetite, without a loathing of food. Coxe.",
  "coccosphere - A small, rounded, marine organism, capable of braking up into coccoliths.",
  "estuarine - Pertaining to an estuary; estuary.",
  "miscibility - Capability of being mixed.",
  "urethroscopy - Examination of the urethra by means of the urethroscope.",
  "hebdomad - A week; a period of seven days. [R.] Sir T. Browne.",
  "thedom - Success; fortune; luck; chance. [Obs.] Evil thedom on his monk's snout. Chaucer.",
  "bufferhead - The head of a buffer, which recieves the concussion, in railroad carriages.",
  "interveniency - Intervention; interposition. [R.]",
  "eluctation - A struggling out of any difficulty. [Obs.] Bp. Hall.",
  "presupposal - Presupposition. [R.] \"Presupposal of knowledge.\" Hooker.",
  "sphygmic - Of or pertaining to the pulse.",
  "erica - A genus of shrubby plants, including the heaths, many of them producing beautiful flowers.",
  "descensional - Pertaining to descension. Johnson.",
  "stomachless - 1. Being without a stomach. 2. Having no appetite. [R.] Bp. Hall.",
  "atmiatry - Treatment of disease by vapors or gases, as by inhalation.",
  "osmometry - The study of osmose by means of the osmometer.",
  "antistrophon - An argument retorted on an opponent. Milton.",
  "two-edged - Having two edges, or edges on both sides; as, a two-edged sword.",
  "osteotome - Strong nippers or a chisel for dividing bone.",
  "praetores - A division of butterflies including the satyrs.",
  "aliseptal - Relating to expansions of the nasal septum.",
  "hirundo - A genus of birds including the swallows and martins.",
  "pretermission - 1. The act of passing by or omitting; omission. Milton. 2. (Rhet.)  See Preterition.",
  "hebetation - 1. The act of making blunt, dull, or stupid. 2. The state of being blunted or dulled.",
  "lettish - Of or pertaining to the Letts. -- n.  The language spoken by the Letts. See Lettic.",
  "endomysium - The delicate bands of connective tissue interspersed among muscular fibers.",
  "levelness - The state or quality of being level.",
  "plunderer - One who plunders or pillages.",
  "suadible - Suasible. [Obs.] Wyclif (James iii. 17).",
  "appeasable - Capable of being appeased or pacified; placable. -- Ap*peas\"a*ble*ness, n.",
  "pierced - Penetrated; entered; perforated.",
  "oxlip - The great cowslip (Primula veris, var. elatior).",
  "wirework - Work, especially openwork, formed of wires.",
  "nitriferous - Bearing niter; yielding, or containing, niter.",
  "soger - Var. of Soldier. [Dial. or Slang]  R. H. Dana, Jr.",
  "unstrain - To relieve from a strain; to relax. B. Jonson.",
  "slyly - In a sly manner; shrewdly; craftily. Honestly and slyly he it spent. Chaucer.",
  "ballad monger - A seller or maker of ballads; a poetaster. Shak.",
  "surquedrous - Having or exhibiting surquedry; arrogant; insolent. [Obs.] Gower. James II. of Scot.",
  "casually - Without design; accidentally; fortuitously; by chance; occasionally.",
  "predisponency - The state of being predisposed; predisposition. [R.]",
  "diorthotic - Relating to the correcting or straightening out of something; corrective.",
  "cumacea - An order of marine Crustacea, mostly of small size.",
  "paltriness - The state or quality of being paltry.",
  "reiter - A German cavalry soldier of the fourteenth and fifteenth centuries.",
  "suent - Uniformly or evenly distributed or spread; even; smooth. See Suant. Thoreau.",
  "expeditionist - One who goes upon an expedition. [R].",
  "suprasternal - Situated above, or anterior to, the sternum.",
  "geodiferous - Producing geodes; containing geodes.",
  "hereunto - Unto this; up to this time; hereto.",
  "corrasive - Corrosive. [Obs.] Corrasive sores which eat into the flesh. Holland.",
  "trackage - The act of tracking, or towing, as a boat; towage.",
  "twinkler - One who, or that which, twinkles, or winks; a winker; an eye.",
  "misname - To call by the wrong name; to give a wrong or inappropriate name to.",
  "chitinous - Having the nature of chitin; consisting of, or containing, chitin.",
  "pettiness - The quality or state of being petty or paltry; littleness; meanness.",
  "sheepfold - A fold or pen for sheep; a place where sheep are collected or confined.",
  "overking - A king who has sovereignty over inferior kings or ruling princes. J. R. Green.",
  "knacky - Having a knack; cunning; crafty; trickish. [Prov. Eng. & Scot.] Halliwell.",
  "pulsion - The act of driving forward; propulsion; -- opposed to Ant: suction or Ant: traction. [R.]",
  "reliefless - Destitute of relief; also, remediless.",
  "inaffected - Unaffected. [Obs.] -- In`af*fect\"ed*ly, adv. [Obs.]"
]