export default [
  "derider - One who derides, or laughs at, another in contempt; a mocker; a scoffer.",
  "jocundity - The state or quality of being jocund; gayety; sportiveness.",
  "conquerable - Capable of being conquered or subdued. South. -- Con\"quer*a*ble*ness, n.",
  "calkin - A calk on a shoe. See Calk, n., 1.",
  "affinitive - Closely connected, as by affinity.",
  "bedstead - A framework for supporting a bed.",
  "homoeopathist - Same as Homeopathic, Homeopathist, Homeopathy.",
  "playgoer - One who frequents playhouses, or attends dramatic performances.",
  "pathological - Of or pertaining to pathology. -- Path`o*log\"ic*al*ly, adv.",
  "wofulness - The quality or state of being woeful; misery; wretchedness.",
  "middler - One of a middle or intermediate class in some schools and seminaries.",
  "diplococcus - A form of micrococcus in which cocci are united in a binary manner. See Micrococcus.",
  "gynecocracy - Government by a woman, female power; gyneocracy. Bailey.",
  "hard-headed - Having sound judgment; sagacious; shrewd. -- Hard\"-head`ed*ness, n.",
  "ternion - The number three; three things together; a ternary. Bp. Hall.",
  "reclusion - A state of retirement from the world; seclusion.",
  "mammilliform - Having the form of a mammilla.",
  "loup-loup - The Pomeranian or Spitz dog.",
  "confervaceous - Belonging to the confervae.",
  "huguenot - A French Protestant of the period of the religious wars in France in the 16th century.",
  "monomyaria - An order of lamellibranchs having but one muscle for closing the shell, as the oyster.",
  "trihedron - A figure having three sides.",
  "fulgency - Brightness; splendor; glitter; effulgence. Bailey.",
  "munify - To prepare for defense; to fortify. [Obs.]",
  "dissilition - The act of bursting or springing apart. [R.] Boyle.",
  "twigger - A fornicator. [Eng.] Halliwell.",
  "indogenide - Any one of the derivatives of indogen, which contain that group as a nucleus.",
  "crystallomancy - Divination by means of a crystal or other transparent body, especially a beryl.",
  "outreckon - To exceed in reckoning or computation. Bp. Pearson.",
  "rushiness - The quality or state of abounding with rushes.",
  "primordian - A name given to several kinds of plums; as, red primordian, amber primordian, etc.",
  "interspiration - Spiritual inspiration at separate times, or at intervals. [Obs.] Bp. Hall.",
  "presumptuousness - The quality or state of being presumptuous.",
  "checkwork - Anything made so as to form alternate squares lke those of a checkerboard.",
  "seismogram - The trace or record of an earth tremor, made by means of a seismograph.",
  "meagreness - The state or quality of being meager; leanness; scantiness; barrenness.",
  "pine-tree state - Maine; -- a nickname alluding to the pine tree in its coat of arms.",
  "monstruosity - Monstrosity. [Obs.] Shak.",
  "overbow - To bend or bow over; to bend in a contrary direction. [Obs.] Fuller.",
  "eventilate - 1. To winnow out; to fan. [Obs.] Cockeram. 2. To discuss; to ventilate. [Obs.] Johnson.",
  "superstructor - One who builds a superstructure. [R.] R. North.",
  "bombazet - A sort of thin woolen cloth. It is of various colors, and may be plain or twilled.",
  "territoried - Possessed of territory. [R.]",
  "unicarinated - Having one ridge or keel. Craig.",
  "illusiveness - The quality of being illusive; deceptiveness; false show.",
  "dependable - Worthy of being depended on; trustworthy. \"Dependable friendships.\" Pope.",
  "grumousness - The state of being grumous.",
  "aperient - Gently opening the bowels; laxative. -- n.  An aperient medicine or food. Arbuthnot.",
  "anabaptistical - Relating or attributed to the Anabaptists, or their doctrines. Milton. Bp. Bull.",
  "drearihood - Affliction; dreariness. [Obs.] Spenser.",
  "superstratum - A stratum, or layer, above another.",
  "clicket - 1. The knocker of a door. [Prov. Eng.] 2. A latch key. [Eng.] Chaucer.",
  "westernmost - Situated the farthest towards the west; most western.",
  "dweller - An inhabitant; a resident; as, a cave dweller. \"Dwellers at Jerusalem.\" Acts i. 19.",
  "accidentalness - The quality of being accidental; casualness.",
  "overhasty - Too hasty; precipitate; rash. -- O\"ver*has\"ti*ly, adv. -- O`ver*has\"ti*ness, n.",
  "lock-weir - A waste weir for a canal, discharging into a lock chamber.",
  "inseparableness - The quality or state of being inseparable; inseparability. Bp. Burnet.",
  "tetrapteran - An insect having four wings.",
  "presbyopic - Affected by presbyopia; also, remedying presbyopia; farsighted.",
  "voluted - Having a volute, or spiral scroll.",
  "betongue - To attack with the tongue; to abuse; to insult.",
  "springtime - The season of spring; springtide.",
  "dictatory - Dogmatical; overbearing; dictatorial. Milton.",
  "percussive - Striking against; percutient; as, percussive force.",
  "glycogeny - The production or formation of sugar from gycogen, as in the liver.",
  "disprover - One who disproves or confutes.",
  "night-blooming - Blooming in the night. Night-blooming cereus. (Bot.) See Note under Cereus.",
  "lademan - One who leads a pack horse; a miller's servant. [Obs. or Local]",
  "reliquidate - To liquidate anew; to adjust a second time.",
  "fancymonger - A lovemonger; a whimsical lover. [Obs.] Shak.",
  "aconitine - An intensely poisonous alkaloid, extracted from aconite.",
  "seposition - The act of setting aside, or of giving up. [Obs.] Jer. Taylor.",
  "efforce - To force; to constrain; to compel to yield. [Obs.] Spenser.",
  "shirting - Cloth, specifically cotton cloth, suitable for making shirts.",
  "withoutforth - Without; outside' outwardly. Cf. Withinforth. [Obs.] Chaucer.",
  "ricinine - A bitter white crystalline alkaloid extracted from the seeds of the castor-oil plant.",
  "whole-souled - Thoroughly imbued with a right spirit; noble-minded; devoted.",
  "foveate - Having pits or depressions; pitted.",
  "quirister - A chorister. See Chorister. [R.] Thomson.",
  "spearman - One who is armed with a spear. Acts xxiii. 23.",
  "outdwell - To dwell or stay beyond. [Poetic] \"He outdwells his hour.\" Shak.",
  "homunculus - A little man; a dwarf; a manikin. Sterne.",
  "witherband - A piece of iron in a saddle near a horse's withers, to strengthen the bow.",
  "impalsy - To palsy; to paralyze; to deaden. [R.]",
  "demonstrativeness - The state or quality of being demonstrative.",
  "poking - Drudging; servile. [Colloq.] Bred to some poking profession. Gray.",
  "rabdomancy - Divination by means of rods or wands. [Written also rhabdomancy.]  Sir T. Browne.",
  "triose - (a) A sugar derived from a trihydric alcohol. (b) A trisaccharide.",
  "affrap - To strike, or strike down. [Obs.] Spenser.",
  "peroneal - Of or pertaining to the fibula; in the region of the fibula.",
  "revulse - To pull back with force. [R.] Cowper.",
  "laxity - The state or quality of being lax; want of tenseness, strictness, or exactness.",
  "musky - Having an odor of musk, or somewhat the like. Milton.",
  "oilery - The business, the place of business, or the goods, of a maker of, or dealer in, oils.",
  "sure-footed - Not liable to stumble or fall; as, a sure-footed horse.",
  "supervisory - Of or pertaining to supervision; as, supervisory powers.",
  "angularly - In an angular manner; with of at angles or corners. B. Jonson.",
  "latchet - The string that fastens a shoe; a shoestring.",
  "creatorship - State or condition of a creator.",
  "usurarious - Usurious. [Obs.] \"Usurarious contracts.\" Jer. Taylor. Bp. Hall.",
  "outsole - The outside sole of a boot or shoe.",
  "nonchalantly - In a nonchalant, indifferent, or careless manner; coolly.",
  "nominalize - To convert into a noun. [Obs.]",
  "elaphine - Pertaining to, resembling, or characteristic of, the stag, or Cervus elaphus.",
  "disparadised - Removed from paradise. [R.] Cockeram.",
  "abbreviated - Shortened; relatively short; abbreviate.",
  "vulviform - Like a cleft with projecting edges.",
  "underdig - To dig under or beneath; to undermine. [Obs.] Wyclif.",
  "inexperienced - Not having experience unskilled. \"Inexperienced youth.\" Cowper.",
  "unapproved - 1. Not approved. 2. Not proved. [Obs.]",
  "parelectronomic - Of or relating to parelectronomy; as, the parelectronomic part of a muscle.",
  "cottonous - Resembling cotton. [R.] Evelyn.",
  "seascape - A picture representing a scene at sea. [Jocose] Thackeray.",
  "dural - Pertaining to the dura, or dura mater.",
  "polysyllabism - The quality or state of being polysyllabic.",
  "treatably - In a treatable manner. [Obs.]",
  "stagely - Pertaining to a stage; becoming the theater; theatrical. [Obs.] Jer. Taylor.",
  "petrary - An ancient war engine for hurling stones.",
  "bristletail - An insect of the genera Lepisma, Campodea, etc., belonging to the Thysanura.",
  "intertangle - To entangle; to intertwine. \"Moss and intertangled vines.\" Longfellow.",
  "gorgoneion - A mask carved in imitation of a Gorgon's head. Elmes.",
  "flanneled - Covered or wrapped in flannel.",
  "slaveholding - Holding persons in slavery.",
  "placitory - Of or pertaining to pleas or pleading, in courts of law. [Obs.] Clayton.",
  "crepon - A thin stuff made of the finest wool or silk, or of wool and silk.",
  "tractability - The quality or state of being tractable or docile; docility; tractableness.",
  "distrainable - Capable of being, or liable to be, distrained. Blackstone.",
  "crystallology - The science of the crystalline structure of inorganic bodies.",
  "air brush - A kind of atomizer for applying liquid coloring matter in a spray by compressed air.",
  "inconfutable - Not confutable. -- In`con*fut\"a*bly, adv. [Obs.] Jer. Taylor.",
  "printery - A place where cloth is printed; print works; also, a printing office. [R.]",
  "prophetically - In a prophetical manner; by way of prediction.",
  "bushment - 1. A thicket; a cluster of bushes. [Obs.] Raleigh. 2. An ambuscade. [Obs.] Sir T. More.",
  "sea risk - Risk of injury, destruction, or loss by the sea, or while at sea.",
  "academicism - 1. A tenet of the Academic philosophy. 2. A mannerism or mode peculiar to an academy.",
  "monopody - A measure of but a single foot.",
  "amphigenous - Increasing in size by growth on all sides, as the lichens.",
  "cute - Clever; sharp; shrewd; ingenious; cunning. [Colloq.]",
  "eyestring - The tendon by which the eye is moved. Shak.",
  "apostatical - Apostate. An heretical and apostatical church. Bp. Hall.",
  "rapeful - 1. Violent. [Obs.] 2. Given to the commission of rape. Byron.",
  "dowset - 1. A custard. [Obs.] 2. A dowcet, or deep's testicle.",
  "nearness - The state or quality of being near; -- used in the various senses of the adjective.",
  "embryonated - In the state of, or having, an embryonal.",
  "orientalize - to render Oriental; to cause to conform to Oriental manners or conditions.",
  "cetin - A white, waxy substance, forming the essential part of spermaceti.",
  "reascension - The act of reascending; a remounting.",
  "turtle-footed - Slow-footed. [R.] \"Turtle-footed Peace.\" Ford.",
  "rescous - 1. Rescue; deliverance. [Obs.] Chaucer. 2. (Law)  See Rescue,2. [Obs.]",
  "dilatedly - In a dilated manner. Feltham.",
  "muride - Bromine; -- formerly so called from its being obtained from sea water.",
  "fore-night - The evening between twilight and bedtime. [Scot.]",
  "potassa - (a) Potassium oxide. [Obs.] (b) Potassium hydroxide, commonly called caustic potash.",
  "overstatement - An exaggerated statement or account.",
  "sprent - p. p. of Sprenge. Sprinkled. All the ground with purple blood was sprent. Spenser.",
  "spindle-legged - Having long, slender legs.",
  "tricipital - Having three heads, or three origins; as, a tricipital muscle.",
  "erotical - Of or pertaining to the passion of love; treating of love; amatory.",
  "letheonize - To subject to the influence of letheon. [R. or Obs.]",
  "cufic - Of or pertaining to the older characters of the Arabic language. [Written also Kufic.]",
  "umquhile - Some time ago; formerly. [Scot.] Sir W. Scott. -- a.  Former. [Scot.]",
  "butterman - A man who makes or sells butter.",
  "vettura - An Italian four-wheeled carriage, esp. one let for hire; a hackney coach.",
  "terraculture - Cultivation on the earth; agriculture. [R.] -- Ter`ra*cul\"tur*al, a. [R.]",
  "unavoided - 1. Not avoided or shunned. Shak. 2. Unavoidable; inevitable. [Obs.] B. Jonson.",
  "crux ansata - A cross in the shape of the ankh.",
  "conspirant - Engaging in a plot to commit a crime; conspiring. [Obs.] Shak.",
  "scasely - Scarcely; hardly. [Obs. or Colloq.] Robynson (More's Utopia)",
  "disenchantment - The act of disenchanting, or state of being disenchanted. Shelton.",
  "brelan carre - In French games, a double pair royal.",
  "enunciator - One who enunciates or proclaims.",
  "chrismatory - A cruet or vessel in which chrism is kept.",
  "hexaphyllous - Having six leaves or leaflets.",
  "agible - Possible to be done; practicable. [Obs.] \"Fit for agible things.\" Sir A. Sherley.",
  "eccle - The European green woodpecker; -- also called ecall, eaquall, yaffle. [Prov. Eng.]",
  "pelage - The covering, or coat, of a mammal, whether of wool, fur, or hair.",
  "ovology - That branch of natural history which treats of the origin and functions of eggs.",
  "telesm - A kind of amulet or magical charm. [Obs.] J. Gregory.",
  "aluminic - Of or containing aluminium; as, aluminic phosphate.",
  "lobbish - Like a lob; consisting of lobs. Sir. P. Sidney.",
  "blunderhead - A stupid, blundering fellow.",
  "hyporadius - One of the barbs of the hypoptilum, or aftershaft of a feather. See Feather.",
  "nectarize - To mingle or infuse with nectar; to sweeten. [Obs.] Cockeram.",
  "dissolvative - Having the power to dissolve anything; solvent. [Obs.] Frampton.",
  "linguistically - In a linguistic manner; from the point of view of a linguist. Tylor.",
  "androtomous - Having the filaments of the stamens divided into two parts.",
  "coticular - Pertaining to whetstones; like or suitable for whetstones.",
  "piceous - Of or pertaining to pitch; resembling pitch in color or quality; pitchy.",
  "inseverable - Incapable of being severed; indivisible; inseparable. De Quincey.",
  "playmate - A companion in diversions; a playfellow.",
  "exuperant - Surpassing; exceeding; surmounting. [Obs.]",
  "undecency - Indecency. [Obs.] \"Decency and undecency.\" Jer. Taylor.",
  "uncentury - To remove from its actual century. [R.] It has first to uncentury itself. H. Drummond.",
  "semiangle - The half of a given, or measuring, angle.",
  "overpart - To give too important or difficult a part to. [Obs.] B. Jonson.",
  "diluvialist - One who explains geological phenomena by the Noachian deluge. Lyell.",
  "grandchild - A son's or daughter's child; a child in the second degree of descent.",
  "nondiscovery - Want or failure of discovery.",
  "obloquious - Containing obloquy; reproachful [R.] Naunton.",
  "improportionate - Not proportionate. [Obs.]",
  "tongo - The mangrove; -- so called in the Pacific Islands.",
  "tautomeric - Relating to, or characterized by, tautomerism.",
  "diamagnetically - In the manner of, or according to, diamagnetism.",
  "emporetic - Pertaining to an emporium; relating to merchandise. [Obs.] Johnson.",
  "agminated - Grouped together; as, the agminated glands of Peyer in the small intestine.",
  "calcinatory - A vessel used in calcination.",
  "excrementize - To void excrement. [R.] Life of A. Wood",
  "ornithologic - Of or pertaining to ornithology.",
  "snuggery - A snug, cozy place. [Colloq.] Dickens.",
  "penelope - A genus of curassows, including the guans.",
  "doorcase - The surrounding frame into which a door shuts.",
  "enragement - Act of enraging or state of being enraged; excitement. [Obs.]",
  "teeming - Prolific; productive. Teeming buds and cheerful appear. Dryden.",
  "bhunder - An Indian monkey (Macacus Rhesus), protected by the Hindoos as sacred. See Rhesus.",
  "oystering - Gathering, or dredging for, oysters.",
  "overview - An inspection or overlooking. [Obs.] Shak.",
  "siliquiform - Having the form of a silique.",
  "subsidiarily - In a subsidiary manner; so as to assist.",
  "paleotheroid - Resembling Paleotherium. -- n.  An animal resembling, or allied to, the paleothere.",
  "neuroskeletal - Of or pertaining to the neuroskeleton. [R.] Owen.",
  "thermobarometer - An instrument for determining altitudes by the boiling point of water.",
  "labidometer - A forceps with a measuring attachment for ascertaining the size of the fetal head.",
  "pecuniarily - In a pecuniary manner; as regards money.",
  "trimester - A term or period of three months.",
  "dry-rub - To rub and cleanse without wetting. Dodsley.",
  "horseweed - A composite plant (Erigeron Canadensis), which is a common weed.",
  "chantey - A sailor's song. May we lift a deep-sea chantey such as seamen use at sea Kipling.",
  "tartly - In a tart manner; with acidity.",
  "spitball - Paper chewed, and rolled into a ball, to be thrown as a missile.",
  "schismatical - Same as Schismatic. -- Schismat\"ic*al*ly, adv. -- Schis*mat\"ic*al*ness, n.",
  "betso - A small brass Venetian coin. [Obs.]",
  "nymphean - Of, pertaining to, or appropriate to, nymphs; inhabited by nymphs; as, a nymphean cave.",
  "diaheliotropic - Relating or, or manifesting, diaheliotropism.",
  "silverware - Dishes, vases, ornaments, and utensils of various sorts, made of silver.",
  "hairspring - The slender recoil spring which regulates the motion of the balance in a timepiece.",
  "good now - An exclamation of wonder, surprise, or entreaty. [Obs.] Shak.",
  "winnower - One who, or that which, winnows; specifically, a winnowing machine.",
  "antivariolous - Preventing the contagion of smallpox.",
  "foremostly - In the foremost place or order; among the foremost. J. Webster.",
  "barbotine - A paste of clay used in decorating coarse pottery in relief.",
  "inchpin - The sweetbread of a deer. Cotgrave.",
  "apprize - To appraise; to value; to appreciate.",
  "disrate - To reduce to a lower rating or rank; to degrade. Marryat.",
  "fumblingly - In the manner of one who fumbles.",
  "trooper - A soldier in a body of cavalry; a cavalryman; also, the horse of a cavalryman.",
  "high-finished - Finished with great care; polished.",
  "anathematic - Pertaining to, or having the nature of, an anathema. -- A*nath`e*mat\"ic*al*ly, adv.",
  "preact - To act beforehand; to perform previously.",
  "ventosity - Quality or state of being ventose; windiness; hence, vainglory; pride. Bacon.",
  "fogbow - A nebulous arch, or bow, of white or yellowish light sometimes seen in fog, etc.",
  "cremator - One who, or that which, cremmates or consumes to ashes.",
  "admiralship - The office or position oaf an admiral; also, the naval skill of an admiral.",
  "concolorous - Of the same color throughout.",
  "preform - To form beforehand, or for special ends. \"Their natures and preformed faculties. \" Shak.",
  "opiniate - To hold or maintain persistently. [Obs.] Barrow.",
  "pneumology - The science which treats of the lungs.",
  "reconsolidate - To consolidate anew or again.",
  "extemporization - The act of extemporizing; the act of doing anything extempore.",
  "trehalose - Mycose; -- so called because sometimes obtained from trehala.",
  "persulphate - A sulphate of the peroxide of any base. [R.]",
  "interconvertible - Convertible the one into the other; as, coin and bank notes are interconvertible.",
  "berain - To rain upon; to wet with rain. [Obs.] Chaucer.",
  "lapdog - A small dog fondled in the lap.",
  "hydrotic - Causing a discharge of water or phlegm. -- n. (Med.)  A hydrotic medicine.",
  "thickly - In a thick manner; deeply; closely.",
  "overmagnify - To magnify too much. Bp. Hall.",
  "colline - A small hill or mount. [Obs.] And watered park, full of fine collines and ponds. Evelyn.",
  "appetible - Desirable; capable or worthy of being the object of desire. Bramhall.",
  "whimsicality - The quality or state of being whimsical; whimsicalness.",
  "amaurotic - Affected with amaurosis; having the characteristics of amaurosis.",
  "mutic - Without a point or pointed process; blunt.",
  "xylanthrax - Wood coal, or charcoal; -- so called in distinction from mineral coal.",
  "familism - The tenets of the Familists. Milton.",
  "lipoma - A tumor consisting of fat or adipose tissue. -- Li*pom\"a*tous, a.",
  "displantation - The act of displanting; removal; displacement. Sir W. Raleigh.",
  "glebosity - The quality of being glebous. [R.]",
  "unguligrade - Having, or walking on, hoofs.",
  "impartialist - One who is impartial. [R.] Boyle.",
  "raree-show - A show carried about in a box; a peep show. Pope.",
  "murdress - A battlement in ancient fortifications with interstices for firing through.",
  "coheir - A joint heir; one of two or more heirs; one of several entitled to an inheritance.",
  "entender - 1. To make tender. [R.] Jer. Taylor. 2. To treat with tenderness. [R.] Young.",
  "unigeniture - The state of being the only begotten. [R.] Bp. Pearson.",
  "irretractile - 1. Not retractile. 2. Not tractile or ductile. [R.] Sir W. Hamilton.",
  "adenitis - Glandular inflammation. Dunglison.",
  "profusive - Profuse; lavish; prodigal.[Obs.]",
  "latered - Inclined to delay; dilatory. [Obs.] \"When a man is too latered.\" Chaucer.",
  "brainy - Having an active or vigorous mind. [Colloq.]",
  "exaggeratory - Containing, or tending to, exaggeration; exaggerative. Johnson.",
  "blender - One who, or that which, blends; an instrument, as a brush, used in blending.",
  "monosyllabled - Formed into, or consisting of, monosyllables. Cleveland.",
  "knoller - One who tolls a bell. [Obs.] Sherwood.",
  "attainability - The quality of being attainable; attainbleness.",
  "undight - To put off; to lay aside, as a garment. [Obs.] Spenser.",
  "pone - A kind of johnnycake. [Written also paune.] [Southern U. S.]",
  "misbehaved - Guilty of ill behavior; illbred; rude. \"A misbehaved and sullen wench.\" Shak.",
  "misintelligence - 1. Wrong information; misinformation. 2. Disagreement; misunderstanding. [Obs.]",
  "reducer - One who, or that which, reduces.",
  "approachable - Capable of being approached; accessible; as, approachable virtue.",
  "bedstock - The front or the back part of the frame of a bedstead. [Obs. or Dial. Eng.]",
  "cryptobranchiate - Having concealed or rudimentary gills.",
  "knackish - Trickish; artful. [Obs.] -- Knack\"ish*ness, n. [Obs.] Dr. H. More.",
  "tormentise - Torture; torment. [Obs.] Chaucer.",
  "knobbling fire - . A bloomery fire. See Bloomery.",
  "succorless - Destitute of succor. Thomson.",
  "demurrable - That may be demurred to. Stormonth.",
  "tiaraed - Adorned with, or wearing, a tiara.",
  "adpress - See Appressed. -- Ad*pressed\",, a.",
  "remissive - Remitting; forgiving; abating. Bp. Hacket.",
  "eviscerate - To take out the entrails of; to disembowel; to gut.",
  "slovenliness - The quality or state of being slovenly.",
  "happed - Wrapped; covered; cloaked. [Scot.] All happed with flowers in the green wood were. Hogg.",
  "sovenaunce - Remembrance. [Obs.] Of his way he had no sovenance. Spenser.",
  "pedagogy - Pedagogics; pedagogism. South.",
  "intro- - A prefix signifying within, into, in, inward; as, introduce, introreception, introthoracic.",
  "pagandom - The pagan lands; pagans, collectively; paganism. [R.]",
  "metacism - A defect in pronouncing the letter m, or a too frequent use of it.",
  "xylotomous - Capable of boring or cutting wood; -- said of many insects.",
  "moric - Pertaining to, or derived from, fustic (see Morin); as, moric acid.",
  "tallow-faced - Having a sickly complexion; pale. Burton.",
  "carbazol - A white crystallized substance, C12H8NH, derived from aniline and other amines.",
  "descensive - Tending to descend; tending downwards; descending. Smart.",
  "vessets - A kind of worsted; also, a worsted cloth. [Prov. Eng.]",
  "neocracy - Government by new or inexperienced hands; upstart rule; raw or untried officials.",
  "villenous - Of or pertaining to a villein.",
  "barbigerous - Having a beard; bearded; hairy.",
  "jutting - Projecting, as corbels, cornices, etc. -- Jut\"ting*ly, adv.",
  "shunless - Not to be shunned; inevitable; unavoidable. [R.] \"Shunless destiny.\" Shak.",
  "revivalism - The spirit of religious revivals; the methods of revivalists.",
  "incarnative - Causing new flesh to grow; healing; regenerative. -- n.  An incarnative medicine.",
  "undersay - To say by way of derogation or contradiction. [Obs.] Spenser.",
  "allecret - A kind of light armor used in the sixteenth century, esp. by the Swiss. Fairholt.",
  "grimalkin - An old cat, esp. a she-cat. J. Philips.",
  "pileorhiza - A cap of cells which covers the growing extremity of a root; a rootcap.",
  "lamplight - Light from a lamp. This world's artificial lamplights. Owen Meredith.",
  "irous - Irascible; passionate. [Obs.] Chaucer.",
  "megadyne - One of the larger measures of force, amounting to one million dynes.",
  "expurgator - One who expurgates or purifies.",
  "square-toed - Having the toe square. Obsolete as fardingales, ruffs, and square-toed shoes. V. Knox.",
  "demonologer - One versed in demonology. R. North.",
  "klipfish - Dried cod, exported from Norway. [Written also clipfish.]",
  "smatterer - One who has only a slight, superficial knowledge; a sciolist.",
  "moonling - A simpleton; a lunatic. [Obs.]",
  "diaphanic - Having power to transmit light; transparent; diaphanous.",
  "cheven - A river fish; the chub. Sir T. Browne.",
  "skeldrake - (a) The common European sheldrake. (b) The oyster catcher.",
  "copland - A piece of ground terminating in a point or acute angle. [Obs.]",
  "coagulable - Capable of being coagulated. Boyle.",
  "palustral - Of or pertaining to a bog or marsh; boggy. [R.]",
  "tristitiate - To make sad. [Obs.] Feltham.",
  "seepage - Water that seeped or oozed through a porous soil. [Scot. & U. S.]",
  "deliriant - A poison which occasions a persistent delirium, or mental aberration (as belladonna).",
  "productile - Capable of being extended or prolonged; extensible; ductile.",
  "consonantly - In a consonant, consistent, or congruous manner; agreeably.",
  "discontentful - Full of discontent. [R.]",
  "desmoid - Resembling, or having the characteristics of, a ligament; ligamentous.",
  "fatiferous - Fate-bringing; deadly; mortal; destructive. [R.] Johnson.",
  "cardinalate - The office, rank, or dignity of a cardinal.",
  "overmodest - Modest to excess; bashful. -- O\"ver*mod\"est*ly, adv.",
  "carbonization - The act or process of carbonizing.",
  "larget - A sport piece of bar iron for rolling into a sheet; a small billet.",
  "rockered - Shaped like a rocker; curved; as, a rockered keel.",
  "allotropicity - Allotropic property or nature.",
  "muculent - Slimy; moist, and moderately viscous.",
  "alveoliform - Having the form of alveoli, or little sockets, cells, or cavities.",
  "rabbate - To abate or diminish. [Obs.] --n.  Abatement. [Obs.]",
  "welcomeness - The quality or state of being welcome; gratefulness; agreeableness; kind reception.",
  "otis - A genus of birds including the bustards.",
  "epidictic - Serving to explain; demonstrative.",
  "lengthwise - In the direction of the length; in a longitudinal direction.",
  "polyspermous - Containing many seeds; as, a polyspermous capsule or berry. Martyn.",
  "countermandable - Capable of being countermanded; revocable. Bacon.",
  "wardenry - The office or jurisdiction of a warden.",
  "remonstrative - Having the character of a remonstrance; expressing remonstrance.",
  "haplomi - An order of freshwater fishes, including the true pikes, cyprinodonts, and blindfishes.",
  "cypraea - A genus of mollusks, including the cowries. See Cowrie.",
  "archdiocese - The diocese of an archbishop.",
  "thundershower - A shower accompanied with lightning and thunder.",
  "wordless - Not using words; not speaking; silent; speechless. Shak.",
  "pyroantimonate - A salt of pyroantimonic acid.",
  "dispositional - Pertaining to disposition.",
  "enticingly - In an enticing manner; charmingly. \"She . . . sings most enticingly.\" Addison.",
  "pan-american - Of or pertaining to both North and South America.",
  "comprador - A kind of steward or agent. [China] S. W. Williams",
  "tipulary - Of or pertaining to the tipulas.",
  "dreggy - Containing dregs or lees; muddy; foul; feculent. Boyle.",
  "potentize - To render the latent power of (anything) available. Dunglison.",
  "priggish - Like a prig; conceited; pragmatical. -- Prig\"gish*ly, adv. -- Prig\"gish-ness, n.",
  "surgent - Rising; swelling, as a flood. [R.] Robert Greene.",
  "brickmaker - One whose occupation is to make bricks. -- Brick\"mak*ing, n.",
  "euphorbine - A principle, or mixture of principles, derived from various species of Euphorbia.",
  "profligation - Defeat; rout; overthrow. [Obs.] Bacon.",
  "caxton - Any book printed by William Caxton, the first English printer. Hansard.",
  "hexa - A prefix or combining form, used to denote six, sixth, etc.; as, hexatomic, hexabasic.",
  "castlery - The government of a castle. Blount.",
  "angulosity - A state of being angulous or angular. [Obs.]",
  "cherishment - Encouragement; comfort. [Obs.] Rich bounty and dear cherishment. Spenser.",
  "shelling - Groats; hulled oats. Simmonds.",
  "catechistic - Of or pertaining to a catechist or to a catechism. Dr. H. More.",
  "foreskin - The fold of skin which covers the glans of the penis; the prepuce.",
  "scherzando - In a playful or sportive manner.",
  "fissipara - Animals which reproduce by fission.",
  "nubiferous - Bringing, or producing, clouds.",
  "plumbery - 1. The business of a plumber. [Obs.] 2. A place where plumbing is carried on; lead works.",
  "abetment - The act of abetting; as, an abetment of treason, crime, etc.",
  "eschevin - The alderman or chief officer of an ancient guild. [Obs.]",
  "quadrifoil - Four-leaved; having the leaves in whorls of four.",
  "arcuated - Bent or curved in the form of a bow. \"Arcuate stalks.\" Gray.",
  "boes - Behoves or behooves. [Obs.] Chaucer.",
  "levigation - The act or operation of levigating.",
  "ento- - A combining form signifying within; as, entoblast.",
  "mandarinic - Appropriate or peculiar to a mandarin.",
  "homotypy - A term suggested by Haeckel to be instead of serial homology. See Homotype.",
  "convocational - Of or pertaining to a convocation.",
  "fribbling - Frivolous; trining; toolishly captious.",
  "chaplaincy - The office, position, or station of a chaplain. Swift.",
  "bdelloidea - The order of Annulata which includes the leeches. See Hirudinea.",
  "moses - A large flatboat, used in the West Indies for taking freight from shore to ship.",
  "isatic - Pertaining to, or derived from, isatin; as, isatic acid, which is also called trioxindol.",
  "analogist - One who reasons from analogy, or represent, by analogy. Cheyne.",
  "impackment - The state of being closely surrounded, crowded, or pressed, as by ice. [R.] Kane.",
  "bugginess - The state of being infested with bugs.",
  "masse shot - A stroke made with the cue held vertically.",
  "trething - A tax; an impost. [Obs.] Johnson.",
  "dauphiness - The title of the wife of the dauphin.",
  "mounty - The rise of a hawk after prey. Sir P. Sidney.",
  "ciliform - Having the form of cilia; very fine or slender.",
  "reclined - Falling or turned downward; reclinate.",
  "threatful - Full of threats; having a menacing appearance. Spenser. -- Threat\"ful*ly, adv.",
  "recognizer - One who recognizes; a recognizor. [Written also recogniser.]",
  "mundil - A turban ornamented with an imitation of gold or silver embroidery.",
  "miasmology - That department of medical science which treats of miasma.",
  "embryologic - Of or pertaining to embryology.",
  "facundity - Eloquence; readiness of speech. [Archaic]",
  "phallic - Of or pertaining to the phallus, or to phallism.",
  "frank-chase - The liberty or franchise of having a chase; free chase. Burrill.",
  "republicate - To make public again; to republish. [Obs.]",
  "demigod - A half god, or an inferior deity; a fabulous hero, the offspring of a deity and a mortal.",
  "didacticity - Aptitude for teaching. Hare.",
  "oafish - Like an oaf; simple. -- Oaf\"ish*ness, n.",
  "solitariety - The state of being solitary; solitariness. [Obs.] Cudworth.",
  "wigged - , a. Having the head covered with a wig; wearing a wig.",
  "squireen - One who is half squire and half farmer; -- used humorously. [Eng.] C. Kingsley.",
  "menopause - The period of natural cessation of menstruation. See Change of life, under Change.",
  "hoidenish - Like, or appropriate to, a hoiden.",
  "unslacked - Not slacked; unslaked; as, unslacked lime.",
  "digitipartite - Parted like the fingers.",
  "furcated - Forked; branching like a fork; as, furcate twigs.",
  "impen - To shut up or inclose, as in a pen. Feltham.",
  "malamethane - A white crystalline substance forming the ethyl salt of malamic acid.",
  "oricalche - See Orichalch. Costly oricalche from strange Phoenice. Spenser.",
  "blusterer - One who, or that which, blusters; a noisy swaggerer.",
  "laminarite - A broad-leafed fossil alga.",
  "phalangite - A soldier belonging to a phalanx. [Obs.]",
  "telotype - An electric telegraph which prints the messages in letters and not in signs.",
  "startingly - By sudden fits or starts; spasmodically. Shak.",
  "onement - The state of being at one or reconciled. [Obs.] Bp. Hall.",
  "suppage - What may be supped; pottage. [Obs.] Hooker.",
  "agrostography - A description of the grasses.",
  "misfortunate - Producing misfortune. [Obs.]",
  "slumberer - One who slumbers; a sleeper.",
  "shuttlewise - Back and forth, like the movement of a shuttle.",
  "paralogize - To reason falsely; to draw conclusions not warranted by the premises. [R.]",
  "apparentness - Plainness to the eye or the mind; visibleness; obviousness. [R.] Sherwood.",
  "mothered - Thick, like mother; viscid. They oint their naked limbs with mothered oil. Dryden.",
  "crestless - Without a crest or escutcheon; of low birth. \"Crestless yeomen.\" Shak.",
  "bombax - A genus of trees, called also the silkcotton tree; also, a tree of the genus Bombax.",
  "betoss - To put in violent motion; to agitate; to disturb; to toss. \"My betossed soul.\" Shak.",
  "bobac - The Poland marmot (Arctomys bobac).",
  "subinvolution - Partial or incomplete involution; as, subinvolution of the uterus.",
  "segge - The hedge sparrow. [Prov. Eng.] Halliwell.",
  "justificator - One who justifies or vindicates; a justifier. Johnson.",
  "overtax - To tax or to task too heavily.",
  "asturian - Of or pertaining to Asturias in Spain. -- n.  A native of Asturias.",
  "orbicle - A small orb, or sphere. [Obs.] G. Fletcher.",
  "immeasurably - In an immeasurable manner or degree. \"Immeasurably distant.\" Wordsworth.",
  "emigrationist - An advocate or promoter of emigration.",
  "readjust - To adjust or settle again; to put in a different order or relation; to rearrange.",
  "surrein - To override; to exhaust by riding. [Obs.] Shak.",
  "dertrotheca - The horny covering of the end of the bill of birds.",
  "ichthyomancy - Divination by the heads or the entrails of fishes.",
  "depulse - To drive away. [Obs.] Cockeram.",
  "disordination - The state of being in disorder; derangement; confusion. [Obs.] Bacon.",
  "impalla - The pallah deer of South Africa.",
  "moabite - One of the posterity of Moab, the son of Lot. (Gen. xix. 37.) Also used adjectively.",
  "executorial - Of or pertaining to an executive.",
  "otolithic - Of or pertaining to otoliths.",
  "abnodation - The act of cutting away the knots of trees. [R.] Crabb.",
  "caseic - OF or pertaining to cheese; as, caseic acid.",
  "neuropod - A neuropodous animal. G. Rolleston.",
  "tetracolon - A stanza or division in lyric poetry, consisting of four verses or lines. Crabb.",
  "ringhead - An instrument used for stretching woolen cloth.",
  "sweetening - 1. The act of making sweet. 2. That which sweetens.",
  "adenophyllous - Having glands on the leaves.",
  "ayen - Again; back against. [Obs.] Chaucer.",
  "olibanum - The fragrant gum resin of various species of Boswellia; Oriental frankincense.",
  "fumacious - Smoky; hence, fond of smoking; addicted to smoking tobacco.",
  "dolorifical - Causing pain or grief. Arbuthnot.",
  "symmetrian - One eminently studious of symmetry of parts. [R.] Sir P. Sidney.",
  "hard-favored - Hard-featured; ill-looking; as, Vulcan was hard-favored. Dryden.",
  "luciform - Having, in some respects, the nature of light; resembling light. Berkeley.",
  "sharebeam - The part of the plow to which the share is attached.",
  "elbowchair - A chair with arms to support the elbows; an armchair. Addison.",
  "quaffer - One who quaffs, or drinks largely.",
  "cotland - Land appendant to a cot or cottage, or held by a cottager or cotter.",
  "choke damp - See Carbonic acid, under Carbonic.",
  "frostless - Free from frost; as, a frostless winter.",
  "rettery - A place or establishment where flax is retted. See Ret. Ure.",
  "diskindness - Unkindness; disservice. [R.] A. Tucker.",
  "intervolve - To involve one within another; to twist or coil together. Milton.",
  "smyrniot - Of or pertaining to Smyrna. -- n.  A native or inhabitant of Smyrna.",
  "chamal - The Angora goat. See Angora goat, under Angora.",
  "nosebleed - 1. A bleeding at the nose. 2. (Bot.)  The yarrow. See Yarrow.",
  "cognomination - A cognomen or surname. [R.] Jer. Taylor.",
  "sailcloth - Duck or canvas used in making sails.",
  "penchant - Inclination; decided taste; bias; as, a penchant for art.",
  "paraphernal - Of or pertaining to paraphernalia; as, paraphernal property. Kent.",
  "porret - A scallion; a leek or small onion. [R.] Sir T. Browne.",
  "keener - A professional mourner who wails at a funeral. [Ireland]",
  "underheave - To heave or lift from below. [Obs.] Wyclif.",
  "odorating - Diffusing odor or scent; fragrant.",
  "pleurosteon - The antero-lateral piece which articulates the sternum of birds.",
  "duumvir - One of two Roman officers or magistrates united in the same public functions.",
  "monasterial - Of or pertaining to monastery, or to monastic life. -- Mon`as*te\"ri*al*ly, adv.",
  "philosophistic - Of or pertaining to the love or practice of sophistry. [R.]",
  "hidage - A tax formerly paid to the kings of England for every hide of land. [Written also hydage.]",
  "agamous - Having no visible sexual organs; asexual. In Bot., cryptogamous.",
  "cordially - In a cordial manner. Dr. H. More.",
  "nethermore - Lower, nether. [Obs.] Holland.",
  "unaccomplishment - The state of being unaccomplished. [Obs.] Milton.",
  "geomantical - Pertaining or belonging to geomancy.",
  "diathermanism - The doctrine or the phenomena of the transmission of radiant heat. Nichol.",
  "arbor dianae - A precipitation of silver, in a beautiful arborescent form.",
  "phormium - A genus of liliaceous plants, consisting of one species (Phormium tenax). See Flax-plant.",
  "undermatch - One who is not a match for another. Fuller.",
  "dioptase - A hydrous silicate of copper, occurring in emerald-green crystals.",
  "arteritis - Inflammation of an artery or arteries. Dunglison.",
  "vibrative - ; vibratory. \"A vibrative motion.\" Sir I. Newton.",
  "yonker - A young fellow; a younker. [Obs. or Colloq.] Sir W. Scott.",
  "fulvous - Tawny; dull yellow, with a mixture of gray and brown. Lindley.",
  "elocutionist - One who is versed in elocution; a teacher of elocution.",
  "rentable - Capable of being rented, or suitable for renting.",
  "commingle - To mingle together; to mix in one mass, or intimately; to blend. Bacon.",
  "cinque-spotted - Five-spotted. [R.] Shak.",
  "exuscitate - See Exsuscitate [Obs.] T. Adams.",
  "remittee - One to whom a remittance is sent.",
  "sea flower - A sea anemone, or any related anthozoan.",
  "perfuse - To suffuse; to fill full or to excess. Harvey.",
  "conoidal - Nearly, but not exactly, conical. Lindley.",
  "biflorate - Bearing two flowers; two-flowered.",
  "confirmee - One to whom anuthing is confirmed.",
  "nooelogy - The science of intellectual phenomena.",
  "thimbleeye - The chub mackerel. See under Chub.",
  "roselite - A hydrous arsenite of cobalt, occuring in small red crystals, allied to erythrite.",
  "sik - Such. See Such. [Obs.] \"Sike fancies weren foolerie.\" Spenser.",
  "canebrake - A thicket of canes. Ellicott.",
  "entheastic - Of godlike energy; inspired. -- En`the*as\"tic*al*ly, adv.",
  "otological - Of or pertaining tootology.",
  "alack - An exclamation expressive of sorrow. [Archaic. or Poet.] Shak.",
  "longirostral - Having a long bill; of or pertaining to the Longirostres.",
  "pegomancy - Divination by fountains. [R.]",
  "unamiability - The quality or state of being unamiable; moroseness.",
  "uncurbable - Not capable of being curbed. Shak.",
  "cutling - The art of making edged tools or cutlery. [Obs.] Milton.",
  "spader - One who, or that which, spades; specifically, a digging machine.",
  "disciplinal - Relating to discipline. Latham.",
  "campaigner - One who has served in an army in several campaigns; an old soldier; a veteran.",
  "repugn - To fight against; to oppose; to resist. [R.] Stubbornly he did repugn the truth. Shak.",
  "gargil - A distemper in geese, affecting the head.",
  "tartrated - Containing, or derived from, tartar; combined with tartaric acid.",
  "playfellow - A companion in amusements or sports; a playmate. Shak.",
  "animater - One who animates. De Quincey.",
  "broadish - Rather broad; moderately broad.",
  "lingo - Language; speech; dialect. [Slang]",
  "admirableness - The quality of being admirable; wonderful excellence.",
  "inlander - One who lives in the interior of a country, or at a distance from the sea. Sir T. Browne.",
  "invendibility - The quality of being invendible; invendibleness; unsalableness.",
  "rough-footed - Feather-footed; as, a rough-footed dove. [R.] Sherwood.",
  "phonotype - A type or character used in phonotypy.",
  "cacography - Incorrect or bad writing or spelling. Walpole.",
  "roundish - Somewhat round; as, a roundish seed; a roundish figure. -- Round\"ish*ness, n.",
  "astrophyton - A genus of ophiurans having the arms much branched.",
  "underbuilder - A subordinate or assistant builder. An underbuilder in the house of God. Jer. Taylor.",
  "longeval - Long-loved; longevous.[R.] Pope.",
  "creolean - Pertaining to, or characteristic of, the Creoles. -- n.  A Creole.",
  "atlantal - (a) Relating to the atlas. (b) Anterior; cephalic. Barclay.",
  "imploratory - Supplicatory; entreating. [R.] Carlyle.",
  "accelerograph - An apparatus for studying the combustion of powder in guns, etc.",
  "unswayable - Not capable of being swayed. Shak.",
  "superplusage - Surplusage. [Obs.] \"There yet remained a superplusage.\" Bp. Fell.",
  "vermiparous - Producing or breeding worms. \"Vermiparous animals.\" Sir T. Browne.",
  "neven - To name; to mention; to utter. [Obs.] As oft I heard my lord them neven. Chaucer.",
  "museful - Meditative; thoughtfully silent. \"Museful mopings.\" Dryden. -- Muse\"ful*ly, adv.",
  "aga - In Turkey, a commander or chief officer. It is used also as a title of respect.",
  "crowth - An ancient musical instrument. See 4th Crowd.",
  "seriation - Arrangement or position in a series.",
  "signality - The quality or state of being signal or remarkable. [Obs.] Sir T. Browne.",
  "wreathen - Twisted; made into a wreath. \"Wreathen work of pure gold.\" Ex. xxviii. 22.",
  "sea milkwort - A low, fleshy perennial herb (Glaux maritima) found along northern seashores.",
  "kranging hook - A hook for holding the blubber while cutting it away. [Written also cranging hook.]",
  "gripingly - In a griping or oppressive manner. Bacon.",
  "transshape - To change into another shape or form; to transform. [Written also transhape.] Shak.",
  "ineligible - Not eligible; not qualified to be chos Burke.",
  "restrainer - One who, or that which, restrains.",
  "infuneral - To inter with funeral rites; to bury. [Obs.] G. Fletcher.",
  "araneidan - Of or pertaining to the Araneina or spiders. -- n.  One of the Araneina; a spider.",
  "caged - Confined in, or as in, a cage; like a cage or prison. \"The caged cloister.\" Shak.",
  "haircloth - Stuff or cloth made wholly or in part of hair.",
  "struse - A Russian river craft used for transporting freight.",
  "inextensible - Not capable of being extended; not elastic; as, inextensible fibers.",
  "decad - A decade. Averill was a decad and a half his elder. Tennyson.",
  "approvedly - So as to secure approbation; in an approved manner.",
  "valuator - One who assesses, or sets a value on, anything; an appraiser. Swift.",
  "powdermill - A mill in which gunpowder is made.",
  "teated - Having protuberances resembling the teat of an animal.",
  "griper - One who gripes; an oppressor; an extortioner. Burton.",
  "loppard - A tree, the top of which has been lopped off. [Eng.]",
  "vagancy - A wandering; vagrancy. [Obs.] A thousand vagancies of glory and desight. Milton.",
  "avertible - Capable of being averted; preventable.",
  "misraise - To raise or exite unreasonable. \"Misraised fury.\" Bp. Hall.",
  "coyish - Somewhat coy or reserved. Warner.",
  "massiness - The state or quality of being massy; ponderousness.",
  "sharp-witted - Having an acute or nicely discerning mind.",
  "yokel - A country bumpkin. [Eng.] Dickens.",
  "allheal - A name popularly given to the officinal valerian, and to some other plants.",
  "clergial - Learned; erudite; clercial. [Obs.] Chaucer.",
  "introspectionist - One given to the introspective method of examining the phenomena of the soul.",
  "pyriform - Having the form of a pear; pear-shaped.",
  "holing - Undercutting in a bed of coal, in order to bring down the upper mass. Raymond.",
  "horatian - Of or pertaining to Horace, the Latin poet, or resembling his style.",
  "peraeopod - One of the thoracic legs of a crustacean. See Illust. of Crustacea.",
  "pimento - Allspice; -- applied both to the tree and its fruit. See Allspice.",
  "sithence - Since. See Sith, and Sithen. [Obs.] Piers Plowman.",
  "plicate - Plaited; folded like a fan; as, a plicate leaf. -- Pli\"cate*ly, adv.",
  "osteomanty - Divination by means of bones. [R.]",
  "lycanthropic - Pertaining to lycanthropy.",
  "fresnel lamp - A lantern having a lamp surrounded by a hollow cylindrical Fresnel lens.",
  "kerse - A cress. [Obs.] Chaucer. Not worth a kers. See under Cress.",
  "leggin - A cover for the leg, like a long gaiter.",
  "wranglership - The honor or position of being a wrangler at the University of Cambridge, England.",
  "ventrad - Toward the ventral side; on the ventral side; ventrally; -- opposed to dorsad.",
  "subpetiolar - Concealed within the base of the petiole, as the leaf buds of the plane tree.",
  "despend - To spend; to squander. See Dispend. [Obs.] Some noble men in Spain can despend Howell.",
  "hatti-sherif - A irrevocable Turkish decree countersigned by the sultan.",
  "instigator - One who instigates or incites. Burke.",
  "ethnographer - One who investigates ethnography.",
  "duoliteral - Consisting of two letters only; biliteral. Stuart.",
  "concussive - Having the power or quality of shaking or agitating. Johnson.",
  "shapable - 1. That may be shaped. 2. Shapely. [R.] \"Round and shapable.\" De Foe.",
  "gerocomy - That part of medicine which treats of regimen for old people.",
  "ventriloquize - To practice ventriloquism; to speak like a ventriloquist.",
  "disinherison - Same as Disherison. Bacon.",
  "destinal - Determined by destiny; fated. [Obs.] \"The order destinal.\" Chaucer.",
  "plenal - Full; complete; as, a plenal view or act. [Obs.]",
  "unblemished - Not blemished; pure; spotless; as, an unblemished reputation or life. Addison.",
  "yle - Isle. [Obs.] \"The barren yle.\" Chaucer.",
  "superinduction - The act of superinducing, or the state of being superinduced. South.",
  "compiler - One who compiles; esp., one who makes books by compilation.",
  "louk - An accomplice; a \"pal.\" [Obs.] There is no thief without a louk. Chaucer.",
  "docity - Teachableness. [Prov. Eng. & Local, U. S.]",
  "draper - One who sells cloths; a dealer in cloths; as, a draper and tailor.",
  "cursorary - Cursory; hasty. [Obs.] With a cursorary eye o'erglanced the articles. Shak.",
  "erythrophleine - A white crystalline alkaloid, extracted from sassy bark (Erythrophleum Guineense).",
  "recordership - The office of a recorder.",
  "authotype - A type or block containing a facsimile of an autograph. Knight.",
  "cephalomere - One of the somites (arthromeres) which make up the head of arthropods. Packard.",
  "solutive - Tending to dissolve; loosening; laxative. Bacon.",
  "tripe-de-roche - Same as Rock tripe, under Rock.",
  "gainable - Capable of being obtained or reached. Sherwood.",
  "appendence - State of being appendant; appendance. [Obs.]",
  "guillevat - A vat for fermenting liquors.",
  "semitonic - Of or pertaining to a semitone; consisting of a semitone, or of semitones.",
  "pignerate - 1. To pledge or pawn. [Obs.] 2. to receive in pawn, as a pawnbroker does. [Obs.]",
  "warted - Having little knobs on the surface; verrucose; as, a warted capsule.",
  "civism - State of citizenship. [R.] Dyer.",
  "oneberry - The herb Paris. See Herb Paris, under Herb.",
  "forejudger - A judgment by which one is deprived or put of a right or thing in question.",
  "intricateness - The state or quality of being intricate; intricacy.",
  "huguenotism - The religion of the Huguenots in France.",
  "indutive - Covered; -- applied to seeds which have the usual integumentary covering.",
  "lackluster - A want of luster. -- a.  Wanting luster or brightness. \"Lackluster eye.\" Shak.",
  "electrotypic - Pertaining to, or effected by means of, electrotypy.",
  "axilla - The armpit, or the cavity beneath the junction of the arm and shoulder. 2. (Bot.)  An axil.",
  "devastator - One who, or that which, devastates. Emerson.",
  "amazon stone - A variety of feldspar, having a verdigris-green color.",
  "eradiate - To shoot forth, as rays of light; to beam; to radiate. Dr. H. More.",
  "monopteron - A circular temple consisting of a roof supported on columns, without a cella.",
  "burgall - A small marine fish; -- also called cunner.",
  "stamin - A kind of woolen cloth. [Written also stamine.] [Obs.]",
  "endometrium - The membrane lining the inner surface of the uterus, or womb.",
  "filiate - To adopt as son or daughter; to establish filiation between. [R.] Southey.",
  "lucidity - The quality or state of being lucid.",
  "devoutless - Destitute of devotion. -- De*vout\"less*ly, adv. -- De*vout\"less*ness, n.",
  "succorer - One who affords succor; a helper.",
  "indeprivable - Incapable of being deprived, or of being taken away.",
  "lactifical - Producing or yielding milk.",
  "claviform - Club-shaped; clavate. Craig.",
  "weaser - The American merganser; -- called also weaser sheldrake. [Local, U. S.]",
  "telautogram - A message transmitted and recorded by a teleautograph.",
  "veniality - The quality or state of being venial; venialness. Jer. Taylor.",
  "deracination - The act of pulling up by the roots; eradication. [R.]",
  "exceeder - One who exceeds. Bp. Montagu.",
  "blennioid - Of, pertaining to, or resembling, the blennies.",
  "senatorship - The office or dignity of a senator. Carew.",
  "tetryl - Butyl; -- so called from the four carbon atoms in the molecule.",
  "errableness - Liability to error. Dr. H. More.",
  "notandum - A thing to be noted or observed; a notable fact; -- chiefly used in the plural.",
  "landwaiter - See Landing waiter, under Landing, a.",
  "ceremoniousness - The quality, or practice, of being ceremonious.",
  "indigometry - The art or method of determining the coloring power of indigo.",
  "molebut - The sunfish (Orthagoriscus, or Mola). [Written also molebat.]",
  "exheredate - To disinherit. [R.] Huloet.",
  "shasta fir - A Californian fir (Abies shastensis).",
  "hemothorax - An effusion of blood into the cavity of the pleura.",
  "vugg - A cavity in a lode; -- called also vogle.",
  "molecularity - The state of consisting of molecules; the state or quality of being molecular.",
  "comedown - A downfall; an humillation. [Colloq.]",
  "spirable - Capable of being breathed; respirable. [Obs.] Nash.",
  "hydrofluate - A supposed compound of hydrofluoris acid and a base; a fluoride. [Archaic]",
  "intuitionalist - One who holds the doctrine of intuitionalism.",
  "lutestring - A plain, stout, lustrous silk, used for ladies' dresses and for ribbon. Goldsmith.",
  "slavic - Slavonic. -- n.  The group of allied languages spoken by the Slavs.",
  "preannounce - To announce beforehand. Coleridge.",
  "pinnage - Poundage of cattle. See Pound. [Obs.]",
  "recriminatory - Having the quality of recrimination; retorting accusation; recriminating.",
  "paraboloidal - Of, pertaining to, or resembling, a paraboloid.",
  "heterocarpous - Characterized by heterocarpism.",
  "thick-headed - Having a thick skull; stupid.",
  "anthropomorphology - The application to God of terms descriptive of human beings.",
  "tinnen - Made or consisting of tin. [Obs.]",
  "plagiostomi - An order of fishes including the sharks and rays; -- called also Plagiostomata.",
  "geometral - Pertaining to geometry. [Obs.]",
  "hylarchical - Presiding over matter. [Obs.] Hallywell.",
  "aspergilliform - Resembling the aspergillum in form; as, an aspergilliform stigma. Gray.",
  "winner - One who wins, or gains by success in competition, contest, or gaming.",
  "comradeship - The state of being a comrade; intimate fellowship.",
  "pleurothotonus - A species of tetanus, in which the body is curved laterally. Quain. Dunglison.",
  "sandglass - An instrument for measuring time by the running of sand. See Hourglass.",
  "tribunate - The state or office of a tribune; tribuneship.",
  "committible - Capable of being committed; liable to be committed. [R.] Sir T. Browne.",
  "sacrificator - A sacrificer; one who offers a sacrifice. [R.] Sir T. Browne.",
  "barefacedly - Openly; shamelessly. Locke.",
  "feckless - Spiritless; weak; worthless. [Scot]",
  "hunt-counter - A worthless dog that runs back on the scent; a blunderer. [Obs.] Shak.",
  "unworldly - Not worldly; spiritual; holy. Hawthorne. -- Un*world\"li*ness, n.",
  "centrostaltic - A term applied to the action of nerve force in the spinal center. Marshall Hall.",
  "gibbier - Wild fowl; game. [Obs.] Addison.",
  "participially - In the sense or manner of a participle.",
  "rheoscope - An instrument for detecting the presence or movement of currents, as of electricity.",
  "textorial - Of or pertaining to weaving. T. Warton.",
  "poseuse - A person who poses or attitudizes, esp. mentally.",
  "myxocystodea - A division of Infusoria including the Noctiluca. See Noctiluca.",
  "remarriage - A second or repeated marriage.",
  "turnverein - A company or association of gymnasts and athletes.",
  "jouissance - Jollity; merriment. [Obs.] Spenser.",
  "piatti - Cymbals. [Written also pyatti.]",
  "ragabrash - An idle, ragged person. Nares. Grose.",
  "prosiness - The quality or state of being prosy; tediousness; tiresomeness.",
  "bestraught - Out of one's senses; distracted; mad. [Obs.] Shak.",
  "assimilable - That may be assimilated; that may be likened, or appropriated and incorporated.",
  "manufactural - Of or pertaining to manufactures. [R.]",
  "billet-doux - A love letter or note. A lover chanting out a billet-doux. Spectator.",
  "pleasurist - A person devoted to worldly pleasure. [R.] Sir T. Browne.",
  "abandoner - One who abandons. Beau. & Fl.",
  "ging - Same as Gang, n., 2. [Obs.] There is a knot, a ging, a pack, a conspiracy against me. Shak.",
  "teemless - Not fruitful or prolific; barren; as, a teemless earth. [Poetic] Dryden.",
  "nonelectrical - Not electric; conducting electricity.",
  "inconsideracy - Inconsiderateness; thoughtlessness. [Obs.] Chesterfield.",
  "myelocoele - The central canal of the spinal cord.",
  "vineyardist - One who cultivates a vineyard.",
  "benefactress - A woman who confers a benefit. His benefactress blushes at the deed. Cowper.",
  "lungie - A guillemot. [Written also longie.] [Prov. Eng. & Scot.] Sir W. Scott.",
  "plagioclase - A general term used of any triclinic feldspar. See the Note under Feldspar.",
  "contagionist - One who believes in the contagious character of certain diseases, as of yellow fever.",
  "pneumatocele - A distention of the scrotum by air; also, hernia of the lungs.",
  "baillie - 1. Bailiff. [Obs.] 2. Same as Bailie. [Scot.]",
  "unsorrowed - Not sorrowed for; unlamented. Beau. & Fl.",
  "oppositionist - One who belongs to the opposition party. Praed.",
  "vitalization - The act or process of vitalizing, or infusing the vital principle.",
  "succubine - Of or pertaining to succuba.",
  "cantharidal - Of or pertaining to cantharides or made of cantharides; as, cantharidal plaster.",
  "ant cow - Any aphid from which ants obtain honeydew.",
  "accessional - Pertaining to accession; additional. [R.] Sir T. Browne.",
  "reeden - Consisting of a reed or reeds. Through reeden pipes convey the golden flood. Dryden.",
  "paleola - A diminutive or secondary palea; a lodicule.",
  "ferier - , compar. of Fere, fierce. [Obs.] Rhenus ferier than the cataract. Marston.",
  "fungic - Pertaining to, or obtained from, mushrooms; as, fungic acid.",
  "passageway - A way for passage; a hall. See Passage, 5.",
  "chuprassy - A messenger or servant wearing an official badge. [Anglo- Indian]",
  "philately - The collection of postage stamps of various issues.",
  "actuator - One who actuates, or puts into action. [R.] Melville.",
  "hyalophane - A species of the feldspar group containing barium. See Feldspar.",
  "encauma - An ulcer in the eye, upon the cornea, which causes the loss of the humors. Dunglison.",
  "ingloriousness - The state of being inglorious.",
  "herbous - Abounding with herbs. \"Fields poetically called herbose.\" Byrom.",
  "trichiuroid - Of, like, or pertaining to, Trichiurus.",
  "sea gherkin - Any small holothurian resembling in form a gherkin.",
  "tachygraphic - Of or pertaining to tachygraphy; written in shorthand.",
  "morsing horn - A horn or flask for holding powder, as for priming. [Scot.] Sir W. Scott.",
  "jesuited - Conforming to the principles of the Jesuits. Milton.",
  "cytoid - Cell-like; -- applied to the corpuscles of lymph, blood, chyle, etc.",
  "pusil - Very small; little; petty. [Obs.] Bacon.",
  "tranquillity - The quality or state of being tranquil; calmness; composure.",
  "guttifer - A plant that exudes gum or resin.",
  "universalian - Of or pertaining to Universalism; Universalist. [R.]",
  "monecian - See Monoecian, and Monoecious.",
  "pesanted - Made heavy or dull; debased. [Obs.] \"Pesanted to each lewd thought's control.\" Marston.",
  "osteo- - A combining form of Gr. a bone.",
  "raging - a. & n. from Rage, v. i. -- Ra\"*ging*ly, adv.",
  "angelhood - The state of being an angel; angelic nature. Mrs. Browning.",
  "exanimous - Lifeless; dead. [Obs.] Johnson.",
  "ablen - A small fresh-water fish (Leuciscus alburnus); the bleak.",
  "seek-sorrow - One who contrives to give himself vexation. [Archaic.] Sir P. Sidney.",
  "saprophytism - State or fact of being saprophytic.",
  "wateriness - The quality or state of being watery; moisture; humidity.",
  "bashless - Shameless; unblushing. [Obs.] Spenser.",
  "diatribist - One who makes a diatribe or diatribes.",
  "governableness - The quality of being governable; manageableness.",
  "cephalology - The science which treats of the head.",
  "cyclonoscope - An apparatus to assist in locating the center of a cyclone.",
  "ironware - Articles made of iron, as household utensils, tools, and the like.",
  "cosier - A tailor who botches his work. [Obs.] Shak.",
  "evolutionary - Relating to evolution; as, evolutionary discussions.",
  "illustrable - Capable of illustration. Sir T. Browne.",
  "midgarth - The middle space or region between heaven and hell, the abode of human beings; the earth.",
  "outbreast - To surpass in singing. See Breast, n., 6. [Obs.]",
  "pharyngotome - An instrument for incising or scarifying the tonsils, etc.",
  "palliament - A dress; a robe. [Obs.] Shak.",
  "saintdom - The state or character of a saint. [R.] Tennyson.",
  "craniognomy - The science of the form and characteristics of the skull. [R.]",
  "proletariat - The indigent class in the State; the body of proletarians.",
  "crosswise - In the form of a cross; across; transversely. Longfellow.",
  "serum-therapy - The treatment of disease by the injection of blood serum from immune animals.",
  "cibarious - Pertaining to food; edible. Johnson.",
  "suffragate - To vote or vote with. [Obs.] \"Suffragating tribes.\" Dryden.",
  "exuberate - To abound; to be in great abundance. [Obs.] Boyle.",
  "imperdibility - The state or quality of being imperdible. [Obs.] Derham.",
  "ameliorable - Capable of being ameliorated.",
  "plantocracy - Government by planters; planters, collectively. [R.]",
  "jibb - To shift, or swing round, as a sail, boom, yard, etc., as in tacking.",
  "inswathe - To wrap up; to infold; to swathe. Inswathed sometimes in wandering mist. Tennyson.",
  "austin - Augustinian; as, Austin friars.",
  "trachelipodous - Having the foot united with the neck; of or pertainingto the Trachelipoda.",
  "amnigenous - Born or bred in, of, or near a river. [Obs.] Bailey.",
  "antarchism - Opposition to government in general. [R.]",
  "pyromalic - Pertaining to, or designating, an acid now called maleic acid.",
  "displeasance - Displeasure; discontent; annoyance. [Obs.] Chaucer.",
  "forlet - To give up; to leave; to abandon. [Obs.] \"To forlet sin.\" Chaucer.",
  "lumberman - One who is engaged in lumbering as a business or employment. [U.S.]",
  "amanitine - The poisonous principle of some fungi.",
  "desertrice - A feminine deserter. Milton.",
  "belime - To besmear or insnare with birdlime.",
  "eulogic - Bestowing praise of eulogy; commendatory; eulogistic. [R.] -- Eu*log\"ic*al*ly, adv. [R.]",
  "tungstate - A salt of tungstic acid; a wolframate.",
  "herschelian - Of or relating to Sir William Herschel; as, the Herschelian telescope.",
  "zuisin - The American widgeon. [Local, U. S.]",
  "hemihedron - A solid hemihedrally derived. The tetrahedron is a hemihedron.",
  "prochein - Next; nearest. Prochein ami or amy ( (Law), the next friend. See under Next.",
  "colportage - The distribution of religious books, tracts, etc., by colporteurs.",
  "mains - The farm attached to a mansion house. [Scot.]",
  "headspring - Fountain; source. The headspring of our belief. Stapleton.",
  "supraclavicular - (a) Situated above the clavicle. (b) Of or pertaining to the supraclavicle.",
  "wizardly - Resembling or becoming a wizard; wizardlike; weird.",
  "imband - To form into a band or bands. \"Imbanded nations.\" J. Barlow.",
  "hesperidene - An isomeric variety of terpene from orange oil.",
  "allocate - 1. To distribute or assign; to allot. Burke. 2. To localize. [R.]",
  "overtitle - To give too high a title to.",
  "catabasion - A vault under altar of a Greek church.",
  "ceruleous - Cerulean. [Obs.] Dr. H. More.",
  "fishskin - 1. The skin of a fish (dog fish, shark, etc.) 2. (Med.)  See Ichthyosis.",
  "subsemitone - The sensible or leading note, or sharp seventh, of any key; subtonic.",
  "dowerless - Destitute of dower; having no marriage portion. Shak.",
  "concentual - Possesing harmony; accordant. [R.] Warton.",
  "predicamental - Of or pertaining to a predicament. John Hall (1646).",
  "schorlaceous - Partaking of the nature and character of schorl; resembling schorl.",
  "inabstinence - Want of abstinence; indulgence. [Obs.] \"The inabstinence of Eve.\" Milton.",
  "glandulous - Containing glands; consisting of glands; pertaining to glands; resembling glands.",
  "chrysoprasus - See Chrysoprase. Rev. xxi. 20.",
  "self-complacent - Satisfied with one's own character, capacity, and doings; self- satisfied.",
  "pachy- - A combining form meaning thick; as, pachyderm, pachydactyl.",
  "tomaley - The liver of the lobster, which becomes green when boiled; -- called also tomalline.",
  "megohm - One of the larger measures of electrical resistance, amounting to one million ohms.",
  "oversnow - To cover with snow, or as with snow. [Poetic] Shak. Dryden.",
  "hypertrophical - Of or pertaining to hypertrophy; affected with, or tending to, hypertrophy.",
  "numps - A dolt; a blockhead. [Obs.] Bp. Parker.",
  "moorpan - A clayey layer or pan underlying some moors, etc.",
  "polymathist - One versed in many sciences; a person of various learning.",
  "annotator - A writer of annotations; a commentator.",
  "distancy - Distance. [Obs.] Dr. H. More.",
  "fract - To break; to violate. [Obs.] Shak.",
  "plurisy - Superabundance; excess; plethora. [Obs.] Shak.",
  "decacuminated - Having the point or top cut off. [Obs.] Bailey.",
  "loriot - The golden oriole of Europe. See Oriole.",
  "drossel - A slut; a hussy; a drazel. [Obs.] Warner.",
  "canonicate - The office of a canon; a canonry.",
  "equicrural - Having equal legs or sides; isosceles. [R.] \"Equicrural triangles.\" Sir T. Browne.",
  "hinderling - A worthless, base, degenerate person or animal. [Obs.] Callander.",
  "engrasp - To grasp; to grip. [R.] Spenser.",
  "margraviate - The territory or jurisdiction of a margrave.",
  "sashoon - A kind of pad worn on the leg under the boot. [Obs.] Nares.",
  "archical - Chief; primary; primordial. [Obs.] Cudworth.",
  "bertha - A kind of collar or cape worn by ladies.",
  "banstickle - A small fish, the three-spined stickleback.",
  "hammercloth - The cloth which covers a coach box.",
  "unbespeak - To unsay; hence, to annul or cancel. [Obs.] Pepys.",
  "trampoose - To walk with labor, or heavily; to tramp. [Law, U. S.] Bartlett.",
  "opisthotic - The inferior and posterior of the three elements forming the periotic bone.",
  "auto-infection - Poisoning caused by a virus that originates and develops in the organism itself.",
  "isotrimorphous - Having the quality of isotrimorphism; isotrimorphic.",
  "short-dated - Having little time to run from the date. \"Thy short-dated life.\" Sandys.",
  "triunity - The quality or state of being triune; trinity. Dr. H. More.",
  "buzzardet - A hawk resembling the buzzard, but with legs relatively longer.",
  "dedans - A division, at one end of a tennis court, for spectators.",
  "abrogative - Tending or designed to abrogate; as, an abrogative law.",
  "brickbat - A piece or fragment of a brick. See Bat, 4. Bacon.",
  "bromoiodized - Treated with bromides and iodides.",
  "junta - A council; a convention; a tribunal; an assembly; esp., the grand council of state in Spain.",
  "contourniated - Having furrowed edges, as if turned in a lathe.",
  "viraginian - Of or pertaining to a virago; having the qualities of a virago. Milton.",
  "supernaturalist - One who holds to the principles of supernaturalism.",
  "bloodily - In a bloody manner; cruelly; with a disposition to shed blood.",
  "creme - Cream; -- a term used esp. in cookery, names of liqueurs, etc.",
  "frounceless - Without frounces. Rom. of R.",
  "inlandish - Inland. [Obs.] T. Reeve(1657)",
  "deadlight - A strong shutter, made to fit open ports and keep out water in a storm.",
  "lento - Slow; in slow time; slowly; -- rarely written lente.",
  "lactuca - A genus of composite herbs, several of which are cultivated foe salad; lettuce.",
  "vastness - The quality or state of being vast.",
  "metabolia - A comprehensive group of insects, including those that undegro a metamorphosis.",
  "hypopharynx - An appendage or fold on the lower side of the pharynx, in certain insects.",
  "worrisome - Inclined to worry or fret; also, causing worry or annoyance.",
  "electronic - Of or pertaining to an electron or electrons.",
  "difficultate - To render difficult; to difficilitate. [Obs.] Cotgrave.",
  "antipyrine - An artificial alkaloid, believed to be efficient in abating fever.",
  "perfusive - Of a nature to flow over, or to spread through.",
  "transmogrify - To change into a different shape; to transform. [Colloq.] Fielding.",
  "overmount - To mount over; to go higher than; to rise above.",
  "jargonist - One addicted to jargon; one who uses cant or slang. Macaulay.",
  "balefulness - The quality or state of being baleful.",
  "tacaud - The bib, or whiting pout. [Prov. Eng.]",
  "jellify - To make, or to become, gelatinous; to jelly. -- Jel`li*fi*ca\"tion (#), n.",
  "emboguing - The mouth of a river, or place where its waters are discharged. [R.]",
  "saur - Soil; dirt; dirty water; urine from a cowhouse. [Prov. Eng.]",
  "exaggerator - One who exaggerates; one addicted to exaggeration. L. Horner.",
  "ullet - A European owl (Syrnium aluco) of a tawny color; -- called also uluia.",
  "evanish - To vanish. Or like the rainbow's lovely form, Evanishing amid the storm. Burns.",
  "blendwater - A distemper incident to cattle, in which their livers are affected. Crabb.",
  "auto- - A combining form, with the meaning of self, one's self, one's own, itself, its own.",
  "normalcy - The quality, state, or fact of being normal; as, the point of normalcy. [R.]",
  "fin-toed - Having toes connected by a membrane; palmiped; palmated; also, lobate.",
  "rurigenous - Born in the country. [Obs.]",
  "spermatorrhoea - Abnormally frequent involuntary emission of the semen without copulation.",
  "assumer - One who assumes, arrogates, pretends, or supposes. W. D. Whitney.",
  "apostil - A marginal note on a letter or other paper; an annotation. Motley.",
  "animus - Animating spirit; intention; temper. nimus furandi Etym: [L.] (Law), intention of stealing.",
  "pervigilation - Careful watching. [Obs.]",
  "ademption - The revocation or taking away of a grant donation, legacy, or the like. Bouvier.",
  "outlast - To exceed in duration; to survive; to endure longer than. Milton.",
  "photo-etching - A photo-engraving produced by any process involving the etching of the plate.",
  "neighborliness - The quality or state of being neighborly.",
  "frizzy - Curled or crisped; as, frizzly, hair.",
  "involucral - Pertaining to, possessing, or like, an involucrum.",
  "volta-electric - Of or pertaining to voltaic electricity, or voltaism.",
  "otology - The branch of science which treats of the ear and its diseases.",
  "denominable - Capable of being denominated or named. Sir T. Browne.",
  "craniometry - The art or act of measuring skulls.",
  "giftedness - The state of being gifted. Echard.",
  "castigator - One who castigates or corrects.",
  "graciousness - Quality of being gracious.",
  "repudiable - Admitting of repudiation; fit or proper to be put away.",
  "theologian - A person well versed in theology; a professor of theology or divinity; a divine.",
  "varus - A deformity in which the foot is turned inward. See Talipes.",
  "sited - Having a site; situated. [Obs.] [The garden] sited was in fruitful soil. Chaucer.",
  "deprecable - That may or should be deprecated. Paley.",
  "epigenesist - One who believes in, or advocates the theory of, epigenesis.",
  "peasantlike - Rude; clownish; illiterate.",
  "archbutler - A chief butler; -- an officer of the German empire.",
  "indefatigableness - Indefatigable quality; unweariedness; persistency. Parnell.",
  "supra-acromial - Situated above the acromial process of the scapula.",
  "cowlick - A tuft of hair turned up or awry (usually over the forehead), as if licked by a cow.",
  "omental - Of or pertaining to an omentum or the omenta.",
  "whitflaw - Whitlow. [Obs.] \"The nails fallen off by whitflaws.\" Herrick.",
  "intricable - Entangling. [Obs.] Shelton.",
  "ticklenburg - A coarse, mixed linen fabric made to be sold in the West Indies.",
  "somatopleuric - of or pertaining to the somatopleure.",
  "fluff - Nap or down; flue; soft, downy feathers.",
  "heretofore - Up to this time; hitherto; before; in time past. Shak.",
  "patriciate - The patrician class; the aristocracy; also, the office of patriarch. Milman.",
  "incurved - Bending gradually toward the axis or center, as branches or petals.",
  "sonifer - A kind of ear trumpet for the deaf, or the partially deaf.",
  "rance - 1. A prop or shore. [Scot.] 2. A round between the legs of a chair.",
  "disconsecrate - To deprive of consecration or sacredness. [R.]",
  "lacrimoso - Plaintive; -- a term applied to a mournful or pathetic movement or style. Moore.",
  "beardie - The bearded loach (Nemachilus barbatus) of Europe. [Scot.]",
  "teakettle - A kettle in which water is boiled for making tea, coffee, etc.",
  "imporous - Destitute of pores; very close or compact in texture; solid. Sir T. Browne.",
  "jangleress - A female prater or babbler.",
  "lighting - A name sometimes applied to the process of annealing metals.",
  "liar - A person who knowingly utters falsehood; one who lies."
]