export default [
  "sepalody - The metamorphosis of other floral organs into sepals or sepaloid bodies.",
  "unweary - To cause to cease being weary; to refresh. [Obs.] Dryden.",
  "luctual - Producing grief; saddening. [Obs.] Sir G. Buck.",
  "vitascope - A form of machine for exhibiting animated pictures.",
  "ellinge - See Elenge, Elengeness. [Obs.]",
  "endognathal - Pertaining to the endognath.",
  "unsanctification - Absence or lack of sanctification. Shak.",
  "exoskeletal - Pertaining to the exoskeleton; as exoskeletal muscles.",
  "minyan - A quorum, or number necessary, for conducting public worship.",
  "asphyxial - Of or relating to asphyxia; as, asphyxial phenomena.",
  "supralapsarianism - The doctrine, belief, or principles of the Supralapsarians.",
  "imponderability - The quality or state of being imponderable; imponderableness.",
  "inevident - Not evident; not clear or obvious; obscure.",
  "benet - To catch in a net; to insnare. Shak.",
  "psilanthropy - The doctrine of the merely human existence of Christ.",
  "cyanean - Having an azure color. Pennant.",
  "siderographist - One skilled in siderography.",
  "polyzoon - One of the individual zooids forming the compound organism of a polyzoan.",
  "countless - Incapable of being counted; not ascertainable; innumerable.",
  "lime-twigged - Beset with snares; insnared, as with birdlime. L. Addison.",
  "splayfooted - Having a splayfoot or splayfeet.",
  "juggleress - 1. A female juggler. T. Warton.",
  "flowerful - Abounding with flowers. Craig.",
  "amiableness - The quality of being amiable; amiability.",
  "polycystine - Pertaining to the Polycystina. -- n.  One of the Polycystina.",
  "water drain - A drain or channel for draining off water.",
  "microsporic - Of or pertaining to microspores.",
  "arundineous - Abounding with reeds; reedy.",
  "degum - To deprive of, or free from, gum; as, to degum ramie.",
  "amethodist - One without method; a quack. [Obs.]",
  "methodology - The science of method or arrangement; a treatise on method. Coleridge.",
  "urogastric - Behind the stomach; -- said of two lobes of the carapace of certain crustaceans.",
  "stack-guard - A covering or protection, as a canvas, for a stack.",
  "stone-blind - As blind as a stone; completely blind.",
  "inwith - Within. [Obs.] This purse hath she inwith her bosom hid. Chaucer.",
  "peopled - Stocked with, or as with, people; inhabited. \"The peopled air.\" Gray.",
  "celature - 1. The act or art of engraving or embossing. 2. That which is engraved. [Obs.] Hakewill.",
  "encephalic - Pertaining to the encephalon or brain.",
  "humanitian - A humanist. [Obs.] B. Jonson.",
  "starlit - Lighted by the stars; starlight.",
  "dirl - To thrill; to vibrate; to penetrate. [Prov. Eng.] Halliwell.",
  "bathygraphic - Descriptive of the ocean depth; as, a bathygraphic chart.",
  "pachacamac - A divinity worshiped by the ancient Peruvians as the creator of the universe.",
  "unresistance - Nonresistance; passive submission; irresistance. Bp. Hall.",
  "pamperize - To pamper. [R.] Sydney Smith.",
  "unwisely - In an unwise manner; foolishly.",
  "inframundane - Lying or situated beneath the world.",
  "dernier - Last; final. Dernier ressort ( Etym: [F.], last resort or expedient.",
  "fringent - Encircling like a fringe; bordering. [R.] \"The fringent air.\" Emerson.",
  "neologization - The act or process of neologizing.",
  "teamed - Yoked in, or as in, a team. [Obs.] Let their teamed fishes softly swim. Spenser.",
  "unheedy - Incautious; precipitate; heedless. [Obs.] Milton.",
  "conchological - Pertaining to, or connected with, conchology.",
  "dasypaedes - Those birds whose young are covered with down when hatched.",
  "disgarland - To strip of a garland. [Poetic] \"Thy locks disgarland.\" Drummond.",
  "transference - The act of transferring; conveyance; passage; transfer.",
  "meatus - A natural passage or canal; as, the external auditory meatus. See Illust. of Ear.",
  "modiolar - Shaped like a bushel measure.",
  "diarrhoeal - Of or pertaining to diarrhea; like diarrhea.",
  "curative - Relating to, or employed in, the cure of diseases; tending to cure. Arbuthnot.",
  "miniardize - To render delicate or dainty. [Obs.] Howell.",
  "reptantia - A divisiom of gastropods; the Pectinibranchiata.",
  "undepartable - Incapable of being parted; inseparable. [Obs.] Chaucer. Wyclif.",
  "monostrophic - Having one strophe only; not varied in measure; written in unvaried measure. Milton.",
  "water glass - See Soluble glass, under Glass.",
  "circumambage - A roundabout or indirect course; indirectness. [Obs.] S. Richardson.",
  "pape - A spiritual father; specifically, the pope. [Obs.]",
  "pituitrin - A substance or extract from the pituitary body.",
  "sesquitertian - Having the ratio of one and one third to one (as 4 : 3).",
  "ben nut - The seed of one or more species of moringa; as, oil of ben. See Moringa.",
  "blub - To swell; to puff out, as with weeping. [Obs.]",
  "chafery - An open furnace or forge, in which blooms are heated before being wrought into bars.",
  "arthropleura - The side or limb-bearing portion of an arthromere.",
  "granitiform - Resembling granite in structure or shape.",
  "mammonite - One devoted to the acquisition of wealth or the service of Mammon. C. Kingsley.",
  "stiltify - To raise upon stilts, or as upon stilts; to stilt.",
  "capitularly - In the manner or form of an ecclesiastical chapter. Sterne.",
  "forejudgment - Prejudgment. [Obs.] Spenser.",
  "sabelloid - Like, or related to, the genus Sabella. -- Sa*bel\"loid, n.",
  "chubbedness - The state of being chubby.",
  "lately - Not long ago; recently; as, he has lately arrived from Italy.",
  "pyrrhicist - One two danced the pyrrhic.",
  "coadjutrix - A female coadjutor or assistant. Holland. Smollett.",
  "pledgee - The one to whom a pledge is given, or to whom property pledged is delivered.",
  "forcipation - Torture by pinching with forceps or pinchers. Bacon.",
  "scrutinous - Closely examining, or inquiring; careful; sctrict. -- Scru\"ti*nous*ly, adv.",
  "ouzel - Same as Ousel. The mellow ouzel fluted in the elm. Tennyson.",
  "elucidatory - Tending to elucidate; elucidative. [R.]",
  "oscillative - Tending to oscillate; vibratory. [R.] I. Taylor.",
  "quarterfoil - An ornamental foliation having four lobes, or foils.",
  "interwreathe - To weave into a wreath; to intertwine. [R.] Lovelace.",
  "thriftiness - The quality or state of being thrifty; thrift.",
  "farlie - An unusual or unexpected thing; a wonder. See Fearly. [Obs. or Prov. Eng.] Drayton.",
  "pragmatically - In a pragmatical manner.",
  "proterosaurus - An extinct genus of reptiles of the Permian period. Called also Protosaurus.",
  "perflation - The act of perflating. [Obs.] Woodward.",
  "anatine - Of or pertaining to the ducks; ducklike.",
  "sandaliform - Shaped like a sandal or slipper.",
  "deistically - After the manner of deists.",
  "vendee - The person to whom a thing is vended, or sold; -- the correlative of vendor.",
  "skiagraphy - See Sciagraph, Sciagraphy, etc.",
  "ouarine - A Brazilian monkey of the genus Mycetes.",
  "replevisable - Repleviable. Sir M. Hale.",
  "stuckle - A number of sheaves set together in the field; a stook.",
  "pasigraphic - Of or pertaining to pasigraphy.",
  "manliness - The quality or state of being manly.",
  "dromaeognathous - Having the structure of the palate like that of the ostrich and emu.",
  "thimbleberry - A kind of black raspberry (Rubus occidentalis), common in America.",
  "acouchy - A small species of agouti (Dasyprocta acouchy).",
  "unportuous - Having no ports. [Obs.] \"An unportuous coast.\" Burke.",
  "tumblerful - As much as a tumbler will hold; enough to fill a tumbler.",
  "conglobulate - To gather into a small round mass.",
  "huddler - One who huddles things together.",
  "rightwiseness - Righteousness. [Obs.] In doom and eke in rightwisnesse. Chaucer.",
  "cardinalize - To exalt to the office of a cardinal. Sheldon.",
  "octylic - Pertaining to, derived from, or containing, octyl; as, octylic ether.",
  "sloam - A layer of earth between coal seams.",
  "afflictedness - The state of being afflicted; affliction. [Obs.] Bp. Hall.",
  "decimeter - A measure of length in the metric system; one tenth of a meter, equal to 3.937 inches.",
  "amatorious - Amatory. [Obs.] \"Amatorious poem.\" Milton.",
  "dispost - To eject from a post; to displace. [R.] Davies (Holy Roode).",
  "capella - A brilliant star in the constellation Auriga.",
  "mesoxalic - Pertaining to, or designating, an acid, CH2O2(CO2H)2, obtained from amido malonic acid.",
  "epithelioid - Like epithelium; as, epithelioid cells.",
  "pulex - A genus of parasitic insects including the fleas. See Flea.",
  "scrotal - Of or pertaining to the scrotum; as, scrotal hernia.",
  "cremona - A superior kind of violin, formerly made at Cremona, in Italy.",
  "overcloud - To cover or overspread with clouds; to becloud; to overcast.",
  "taker - One who takes or receives; one who catches or apprehended.",
  "ammiral - An obsolete form of admiral. \"The mast of some great ammiral.\" Milton.",
  "gymnast - One who teaches or practices gymnastic exercises; the manager of a gymnasium; an athlete.",
  "nugacity - Futility; trifling talk or behavior; drollery. [R.] Dr. H. More.",
  "addictedness - The quality or state of being addicted; attachment.",
  "dicebox - A box from which dice are thrown in gaming. Thackeray.",
  "lanuginose - Covered with down, or fine soft hair; downy.",
  "spoonworm - A gephyrean worm of the genus Thalassema, having a spoonlike probiscis.",
  "centrally - In a central manner or situation.",
  "ritualistic - Pertaining to, or in accordance with, a ritual; adhering to ritualism.",
  "inconveniently - In an inconvenient manner; incommodiously; unsuitably; unseasonably.",
  "tantalization - The act of tantalizing, or state of being tantalized. Gayton.",
  "loftily - In a lofty manner or position; haughtily.",
  "irreflective - Not reflective. De Quincey.",
  "constableship - The office or functions of a constable.",
  "suppositional - Resting on supposition; hypothetical; conjectural; supposed. South.",
  "clavicular - Of or pertaining to the clavicle.",
  "conceptualist - One who maintains the theory of conceptualism. Stewart.",
  "articulative - Of or pertaining to articulation. Bush.",
  "superlation - Exaltation of anything beyond truth or propriety. [Obs.] B. Jonson.",
  "borrower - One who borrows. Neither a borrower nor a lender be. Shak.",
  "pesterous - Inclined to pester. Also, vexatious; encumbering; burdensome. [Obs.] Bacon.",
  "sur- - A prefix signifying over, above, beyond, upon.",
  "veterinarian - One skilled in the diseases of cattle or domestic animals; a veterinary surgeon.",
  "octogenary - Of eighty years of age. \"Being then octogenary.\" Aubrey.",
  "exestuation - A boiling up; effervescence. [Obs.] Boyle.",
  "polytheist - One who believes in, or maintains the doctrine of, a plurality of gods.",
  "stintedness - The state of being stinted.",
  "steeply - In a steep manner; with steepness; with precipitous declivity.",
  "ingannation - Cheat; deception. [Obs.] Sir T. Brown.",
  "antiloimic - A remedy against the plague. Brande & C.",
  "vitriform - Having the form or appearance of glass; resembling glass; glasslike.",
  "madly - In a mad manner; without reason or understanding; wildly.",
  "nocument - Harm; injury; detriment. [Obs.]",
  "sternohyoid - Of or pertaining to the sternum and the hyoid bone or cartilage.",
  "stannum - The technical name of tin. See Tin.",
  "endoscope - An instrument for examining the interior of the rectum, the urethra, and the bladder.",
  "fluo- - A combining form indicating fluorine as an ingredient; as in fluosilicate, fluobenzene.",
  "formule - A set or prescribed model; a formula. [Obs.] Johnson.",
  "saxicavid - Of or pertaining to the saxicavas. -- n.  A saxicava.",
  "echinated - Set with prickles; prickly, like a hedgehog; bristled; as, an echinated pericarp.",
  "acalycine - Without a calyx, or outer floral envelope.",
  "tetrasyllabic - Consisting of, or having, four syllables; quadrisyllabic.",
  "podophthalmite - The eyestalk of a crustacean.",
  "nitrolic - of, derived from, or designating, a nitrol; as, a nitrolic acid.",
  "sharewort - A composite plant (Aster Tripolium) growing along the seacoast of Europe.",
  "perfervid - Very fervid; too fervid; glowing; ardent.",
  "premosaic - Relating to the time before Moses; as, premosaic history.",
  "definitiveness - The quality of being definitive.",
  "outstorm - To exceed in storming. Insults the tempest and outstorms the skies. J. Barlow.",
  "half-sister - A sister by one parent only.",
  "hederose - Pertaining to, or of, ivy; full of ivy.",
  "precipitator - One who precipitates, or urges on with vehemence or rashness. Hammond.",
  "ordinative - Tending to ordain; directing; giving order. [R.] Gauden.",
  "adjection - The act or mode of adding; also, the thing added. [R.] B. Jonson.",
  "magged - Worn; fretted; as, a magged brace. Ham. Nav. Encyc.",
  "popularness - The quality or state of being popular; popularity. Coleridge.",
  "lachrymary - Containing, or intended to contain, tears; lachrymal. Addison.",
  "pollinose - Having the surface covered with a fine yellow dust, like pollen.",
  "decandrous - Belonging to the Decandria; having ten stamens.",
  "truantship - The conduct of a truant; neglect of employment; idleness; truancy. Ascham.",
  "normalization - Reduction to a standard or normal state.",
  "circumbendibus - A roundabout or indirect way. [Jocular] Goldsmith.",
  "outscorn - To confront, or subdue, with greater scorn. Shak.",
  "wantrust - Failing or diminishing trust; want of trust or confidence; distrust. [Obs.] Chaucer.",
  "circuity - A going round in a circle; a course not direct; a roundabout way of proceeding.",
  "hypognatous - Having the maxilla, or lower jaw, longer than the upper, as in the skimmer.",
  "water-furrow - To make water furrows in.",
  "pataca - The Spanish dollar; -- called also patacoon. [Obs.]",
  "sea pincushion - (a) A sea purse. (b) A pentagonal starfish.",
  "patible - Sufferable; tolerable; endurable. [Obs.] Bailey.",
  "conservational - Tending to conserve; preservative.",
  "torace - To scratch to pieces. [Obs.] Chaucer.",
  "judaic - Of or pertaining to the Jews. \"The natural or Judaical [religion].\" South.",
  "proximo - In the next month after the present; -- often contracted to prox.; as, on the 3d proximo.",
  "gazeebo - A summerhouse so situated as to command an extensive prospect. [Colloq.]",
  "definitional - Relating to definition; of the nature of a definition; employed in defining.",
  "traulism - A stammering or stuttering. [Obs.] Dalgarno.",
  "quicksilvered - Overlaid with quicksilver, or with an amalgam of quicksilver and tinfoil.",
  "edictal - Relating to, or consisting of, edicts; as, the Roman edictal law.",
  "marver - A stone, or cast-iron plate, or former, on which hot glass is rolled to give it shape.",
  "storier - A relater of stories; an historian. [Obs.] Bp. Peacock.",
  "dout - To put out. [Obs.] \"It douts the light.\" Sylvester.",
  "benefactor - One who confers a benefit or benefits. Bacon.",
  "simpleton - A person of weak intellect; a silly person.",
  "fantastic-alness - The quality of being fantastic.",
  "nonsolvency - Inability to pay debts; insolvency.",
  "overbuilt - Having too many buildings; as, an overbuilt part of a town.",
  "levet - A trumpet call for rousing soldiers; a reveille. [Obs.] Hudibras.",
  "inimicitious - Inimical; unfriendly. [R.] Sterne.",
  "pardo - A money of account in Goa, India, equivalent to about 2s. 6d. sterling. or 60 cts.",
  "rhombohedron - A solid contained by six rhomboids; a parallelopiped.",
  "ovular - Relating or belonging to an ovule; as, an ovular growth.",
  "selachian - One of the Selachii. See Illustration in Appendix.",
  "repartotion - Another, or an additional, separation into parts.",
  "carpentering - The occupation or work of a carpenter; the act of workingin timber; carpentry.",
  "covenably - Fitly; suitably. [Obs.] \"Well and covenably.\" Chaucer.",
  "parabronchium - One of the branches of an ectobronchium or entobronchium.",
  "glass maker - One who makes, or manufactures, glass. -- Glass\" mak`ing, or Glass\"mak`ing, n.",
  "textury - The art or process of weaving; texture. [Obs.] Sir T. Browne.",
  "entonic - Having great tension, or exaggerated action. Dunglison.",
  "apohyal - Of or pertaining to a portion of the horn of the hyoid bone.",
  "stalagmitic - Having the form or structure of stalagmites. -- Stal`ag*mit\"ic*al*ly, adv.",
  "embedment - The act of embedding, or the state of being embedded.",
  "intermination - A menace or threat. [Obs.] Jer. Taylor.",
  "spellbound - Bound by, or as by, a spell.",
  "misinterpret - To interpret erroneously; to understand or to explain in a wrong sense.",
  "purbeck stone - A limestone from the Isle of Purbeck in England.",
  "demagogic - Relating to, or like, a demagogue; factious.",
  "truceless - Without a truce; unforbearing. Two minds in one, and each a truceless guest. H. Brooke.",
  "confident - See Confidant. South. Dryden.",
  "spiritually - In a spiritual manner; with purity of spirit; like a spirit.",
  "vire - An arrow, having a rotary motion, formerly used with the crossbow. Cf. Vireton. Gower.",
  "glost oven - An oven in which glazed pottery is fired; -- also called glaze kiln, or glaze.",
  "avesta - The Zoroastrian scriptures. See Zend-Avesta.",
  "sanableness - The quality of being sanable.",
  "lathing - The act or process of covering with laths; laths, collectively; a covering of laths.",
  "revince - To overcome; to refute, as error. [Obs.] Foxe.",
  "scoot - To walk fast; to go quickly; to run hastily away. [Colloq. & Humorous, U.S.]",
  "catch-meadow - meadow irrigated by water from a spring or rivulet on the side of hill.",
  "disagreeableness - The state or quality of being; disagreeable; unpleasantness.",
  "unrivaled - Having no rival; without a competitor; peerless. [Spelt also unrivalled.] Pope.",
  "coombe - A hollow in a hillside. [Prov. Eng.] See Comb, Combe.",
  "oratorize - To play the orator. [Jocose or derisive] Dickens.",
  "anacrotism - A secondary notch in the pulse curve, obtained in a sphygmographic tracing.",
  "instillment - The act of instilling; also, that which is instilled. [Written also instilment.]",
  "expansure - Expanse. [Obs.] \"Night's rich expansure.\"",
  "obtension - The act of obtending. [Obs.] Johnson.",
  "higgledy-piggledy - In confusion; topsy-turvy. [Colloq.] Johnson.",
  "therewhile - At that time; at the same time. [Obs.] Laud.",
  "overrighteous - Excessively righteous; -- usually implying hypocrisy.",
  "scripturalist - One who adheres literally to the Scriptures.",
  "cheaply - At a small price; at a low value; in a common or inferior manner.",
  "elogium - The praise bestowed on a person or thing; panegyric; eulogy.",
  "chaetetes - A genus of fossil corals, common in the lower Silurian limestones.",
  "wonder-worker - One who performs wonders, or miracles.",
  "tantalizingly - In a tantalizing or teasing manner.",
  "disinflame - To divest of flame or ardor. Chapman.",
  "craniota - A comprehensive division of the Vertebrata, including all those that have a skull.",
  "satellitious - Pertaining to, or consisting of, satellites. [R.] Cheyne.",
  "exploitation - The act of exploiting or utilizing. J. D. Whitney.",
  "atonable - Admitting an atonement; capable of being atoned for; expiable.",
  "retent - That which is retained. Hickok.",
  "mono - The black howler of Central America (Mycetes villosus).",
  "brachyurous - Of or pertaining to the Brachyura.",
  "mismanage - To manage ill or improperly; as, to mismanage public affairs.",
  "chalcanthite - Native blue vitriol. See Blue vitriol, under Blue.",
  "jargle - To emit a harsh or discordant sound. [Obs.] Bp. Hall.",
  "labyrinthic - Like or pertaining to a labyrinth.",
  "mosaical - Mosaic (in either sense). \"A mosaical floor.\" Sir P. Sidney.",
  "telegraphist - One skilled in telegraphy; a telegrapher.",
  "infra - Below; beneath; under; after; -- often used as a prefix.",
  "biflagellate - Having two long, narrow, whiplike appendages.",
  "begrave - To bury; also, to engrave. [Obs.] Gower.",
  "indissolubility - The quality or state of being indissoluble.",
  "pinguefaction - A making of, or turning into, fat.",
  "suborbital - Situated under or below the orbit.",
  "skippingly - In a skipping manner; by skips, or light leaps.",
  "crescentwise - In the form of a crescent; like a crescent. Tennyson.",
  "forsythia - A shrub of the Olive family, with yellow blossoms.",
  "alchymy - See Alchemic, Alchemist, Alchemistic, Alchemy.",
  "lychnobite - One who labors at night and sleeps in the day.",
  "impanelment - The act or process of impaneling, or the state of being impaneled.",
  "adjectivally - As, or in the manner of, an adjective; adjectively.",
  "discernibly - In a manner to be discerned; perceptibly; visibly. Hammond.",
  "illegitimacy - The state of being illegitimate. Blackstone.",
  "exonerative - Freeing from a burden or obligation; tending to exonerate.",
  "omnipresential - Implying universal presence. [R.] South.",
  "stander-by - One who stands near; one who is present; a bystander.",
  "mitigatory - Tending to mitigate or alleviate; mitigative.",
  "entoglossal - Within the tongue; -- applied to the glossohyal bone.",
  "opiparous - Sumptuous. [Obs.] -- O*pip\"a*rous*ly, adv. [Obs.] E. Waterhouse.",
  "controversially - In a controversial manner.",
  "acclivous - Sloping upward; rising as a hillside; -- opposed to declivous.",
  "disembodiment - The act of disembodying, or the state of being disembodied.",
  "antitypous - Resisting blows; hard. [Obs.] Cudworth.",
  "hulky - Bulky; unwiedly. [R.] \"A huge hulking fellow.\" H. Brooke.",
  "delenifical - Assuaging pain. [Obs.] Bailey.",
  "separability - Quality of being separable or divisible; divisibility; separableness.",
  "anaglyptographic - Of or pertaining to anaglyptography; as, analyptographic engraving.",
  "granivorous - Eating grain; feeding or subsisting on seeds; as, granivorous birds. Gay.",
  "soam - A chain by which a leading horse draws a plow. Knight.",
  "detonization - The act of detonizing; detonation.",
  "apetalous - Having no petals, or flower leaves. [See Illust. under Anther].",
  "immarginate - Not having a distinctive margin or border. Grey.",
  "rationalness - The quality or state of being rational; rationality.",
  "diluteness - The quality or state of being dilute. Bp. Wilkins.",
  "torpidness - The qualityy or state of being torpid.",
  "parishen - A parishioner. [Obs.] Chaucer.",
  "homestall - Place of a home; homestead. Cowper.",
  "dittander - A kind of peppergrass (Lepidium latifolium).",
  "ursus - A genus of Carnivora including the common bears.",
  "addulce - To sweeten; to soothe. [Obs.] Bacon.",
  "bogsucker - The American woodcock; -- so called from its feeding among the bogs.",
  "idiorepulsive - Repulsive by itself; as, the idiorepulsive power of heat.",
  "skiffling - Rough dressing by knocking off knobs or projections; knobbing.",
  "undersoil - The soil beneath the surface; understratum; subsoil.",
  "barky - Covered with, or containing, bark. \"The barky fingers of the elm.\" Shak.",
  "dal - Split pulse, esp. of Cajanus Indicus. [East Indies]",
  "kantist - A disciple or follower of Kant.",
  "alebench - A bench in or before an alehouse. Bunyan.",
  "independentism - Independency; the church system of Independents. Bp. Gauden.",
  "postic - Backward. [Obs.] Sir T. Browne.",
  "consumedly - Excessively. [Low] He's so consumedly pround of it. Thackeray.",
  "plumelet - A small plume. When rosy plumelets tuft the larch. Tennyson.",
  "graveolence - A strong and offensive smell; rancidity. [R.] Bailey.",
  "hollands - 1. Gin made in Holland. 2. pl.  See Holland.",
  "noon-flower - The goat's beard, whose flowers close at midday.",
  "therebefore - Before that time; beforehand. [Obs.] Many a winter therebiforn. Chaucer.",
  "arching - 1. The arched part of a structure. 2. (Naut.)  Hogging; -- opposed to sagging.",
  "divalent - Having two units of combining power; bivalent. Cf. Valence.",
  "spiketail - The pintail duck. [Local, U.S.]",
  "blast lamp - A lamp provided with some arrangement for intensifying combustion by means of a blast.",
  "attemperly - Temperately. [Obs.] Chaucer.",
  "giantly - Appropriate to a giant. [Obs.] Usher.",
  "spiritualty - An ecclesiastical body; a spirituality. Shak.",
  "moon-eyed - Having eyes affected by the moon; moonblind; dim-eyed; purblind.",
  "inaquation - The state of being inaquate. [Obs.] Bp. Gardiner.",
  "alterableness - The quality of being alterable; variableness; alterability.",
  "mask shell - Any spiral marine shell of the genus Persona, having a curiously twisted aperture.",
  "nephilim - Giants. Gen. vi. 4. Num. xiii. 33.",
  "outvote - To exceed in the number of votes given; to defeat by votes. South.",
  "sclerometer - An instrument for determining with accuracy the degree of hardness of a mineral.",
  "collectively - In a mass, or body; in a collected state; in the aggregate; unitedly.",
  "roble - The California white oak (Quercus lobata).",
  "nerita - A genus of marine gastropods, mostly natives of warm climates.",
  "involucrated - Having an involucre; involucred.",
  "gynobase - A dilated base or receptacle, supporting a multilocular ovary.",
  "penguinery - A breeding place, or rookery, of penguins.",
  "emerods - Hemorrhoids; piles; tumors; boils. [R.] Deut. xxviii. 27.",
  "hyne - A servant. See Hine. [Obs.] Chaucer.",
  "wishable - Capable or worthy of being wished for; desirable. Udall.",
  "spangly - Resembling, or consisting of, spangles; glittering; as, spangly light.",
  "arnicine - An alkaloid obtained from the arnica plant.",
  "bereavement - The state of being bereaved; deprivation; esp., the loss of a relative by death.",
  "marsipobranch - One of the Marsipobranchia.",
  "rhadamanthys - One of the three judges of the internal regions; figuratively, a strictly just judge.",
  "alutaceous - 1. Leathery. 2. Of a pale brown color; leather-yellow. Brande.",
  "quirky - Full of quirks; tricky; as, a quirky lawyer.",
  "rouet - A small wheel formerly fixed to the pan of firelocks for discharging them. Crabb.",
  "chevrette - A machine for raising guns or mortar into their carriages.",
  "hilt - 1. A handle; especially, the handle of a sword, dagger, or the like.",
  "outquench - To quench entirely; to extinguish. \"The candlelight outquenched.\" Spenser.",
  "eyebolt - A bolt which a looped head, or an opening in the head.",
  "lemuroid - Like or pertaining to the lemurs or the Lemuroidea. -- n.  One of the Lemuroidea.",
  "rejourn - To adjourn; to put off. [Obs.] Shak.",
  "slatt - A slab of stone used as a veneer for coarse masonry. Knight.",
  "polygynous - Having many styles; belonging to the order Polygynia.",
  "shackly - Shaky; rickety. [Colloq. U. S.]",
  "ceroplasty - The art of modeling in wax.",
  "instrumentist - A performer on a musical instrument; an instrumentalist.",
  "branchiostege - The branchiostegal membrane. See Illustration in Appendix.",
  "salamandroidea - A division of Amphibia including the Salamanders and allied groups; the Urodela.",
  "fad - A hobby ; freak; whim. -- Fad\"dist, n. It is your favorite fad to draw plans. G. Eliot.",
  "toxicological - Of or pertaining to toxicology. -- Tox`i*co*log\"ic*al*ly, adv.",
  "desume - To select; to borrow. [Obs.] Sir. M. Hale.",
  "inscience - Want of knowledge; ignorance. [Obs.]",
  "assibilation - Change of a non-sibilant letter to a sibilant, as of -tion to - shun, duke to ditch.",
  "handicapper - One who determines the conditions of a handicap.",
  "fraudulency - The quality of being fraudulent; deliberate deceit; trickishness. Hooker.",
  "sanguiferous - Conveying blood; as, sanguiferous vessels, i. e., the arteries, veins, capillaries.",
  "platycnemism - Lateral flattening of the tibia.",
  "bigha - A measure of land in India, varying from a third of an acre to an acre.",
  "vincibleness - The quality or state of being vincible.",
  "gerlind - A salmon returning from the sea the second time. [Prov. Eng.]",
  "shemitish - Of or pertaining to Shem, the son of Noah, or his descendants. See Semitic.",
  "clavichord - A keyed stringed instrument, now superseded by the pianoforte. See Clarichord.",
  "precisianism - The quality or state of being a precisian; the practice of a precisian. Milton.",
  "rugosity - The quality or state of being rugose.",
  "breviped - Having short legs. -- n.  A breviped bird.",
  "water tabby - A kind of waved or watered tabby. See Tabby, n., 1.",
  "flap-eared - Having broad, loose, dependent ears. Shak.",
  "workshop - A shop where any manufacture or handiwork is carried on.",
  "grease cup - A cock or cup containing grease, to serve as a lubricator.",
  "parabolically - 1. By way of parable; in a parabolic manner. 2. In the form of a parabola.",
  "imbonity - Want of goodness. [Obs.] Burton.",
  "non-episcopal - Not Episcopal; not pertaining to the Episcopal church or system.",
  "butty - One who mines by contract, at so much per ton of coal or ore.",
  "knockings - Large lumps picked out of the sieve, in dressing ore.",
  "compulsorily - ; by force or constraint.",
  "orthopterous - Of or pertaining to the Orthoptera.",
  "foregame - A first game; first plan. [Obs.] Whitlock.",
  "balbuties - The defect of stammering; also, a kind of incomplete pronunciation.",
  "unease - Want of ease; uneasiness. [Obs.]",
  "servage - Serfage; slavery; servitude. [Obs.] Chaucer.",
  "discal - Pertaining to, or resembling, a disk; as, discal cells.",
  "applausable - Worthy pf applause; praiseworthy. [Obs.]",
  "hydrographic - Of or relating to hydrography.",
  "antigalastic - Causing a diminution or a suppression of the secretion of milk.",
  "overknowing - Too knowing or too cunning.",
  "cuneated - Wedge-shaped; (Bot.), wedge-shaped, with the point at the base; as, a cuneate leaf.",
  "vulturism - The quality or state of being like a vulture; rapaciousness.",
  "tollhouse - A house occupied by a receiver of tolls.",
  "sulphinate - A salt of a sulphinic acid.",
  "peristole - Peristaltic action, especially of the intestines.",
  "consoling - Adapted to console or comfort; cheering; as, this is consoling news.",
  "clarisonus - Having a clear sound. [Obs.] Ash.",
  "avis - Advice; opinion; deliberation. [Obs.] Chaucer.",
  "platypod - An animal having broad feet, or a broad foot.",
  "noology - The science of intellectual phenomena.",
  "fluviograph - An instrument for measuring and recording automatically the rise and fall of a river.",
  "staphyloma - A protrusion of any part of the globe of the eye; as, a staphyloma of the cornea.",
  "inusitation - Want of use; disuse. [R.] Paley.",
  "hydrozoal - Of or pertaining to the Hydrozoa.",
  "catch title - A short expressive title used for abbreviated book lists, etc.",
  "coalescent - Growing together; cohering, as in the organic cohesion of similar parts; uniting.",
  "unmanacle - To free from manacles. Tennyson.",
  "logodaedaly - Verbal legerdemain; a playing with words. [R.] Coleridge.",
  "musculation - The muscular system of an animal, or of any of its parts.",
  "mortifier - One who, or that which, mortifies.",
  "bipunctate - Having two punctures, or spots.",
  "horsewoman - A woman who rides on horseback.",
  "rondache - A circular shield carried by foot soldiers.",
  "everywhereness - Ubiquity; omnipresence. [R.] Grew.",
  "selenographical - Of or pertaining to selenography.",
  "magneticalness - Quality of being magnetic.",
  "lifely - In a lifelike manner. [Obs.] Chaucer.",
  "neuralgic - of or pertaining to, or having the character of, neuralgia; as, a neuralgic headache.",
  "sphagnous - Pertaining to moss of the genus Sphagnum, or bog moss; abounding in peat or bog moss.",
  "ludwigite - A borate of iron and magnesia, occurring in fibrous masses of a blackish green color.",
  "melicerous - Consisting of or containing matter like honey; -- said of certain encysted tumors.",
  "switchel - A beverage of molasses and water, seasoned with vinegar and ginger. [U. S.]",
  "consequencing - Drawing inference. [R.] Milton.",
  "ayeins - Again; back against. [Obs.] Chaucer.",
  "impairer - One who, or that which, impairs.",
  "macadamization - The process or act of macadamizing.",
  "pick-me-up - A stimulant, restorative, or tonic; a bracer. [Colloq.]",
  "earth shine - See Earth light, under Earth.",
  "pimping - 1. Little; petty; pitiful. [Obs.] Crabbe. 2. Puny; sickly. [Local, U.S.]",
  "scutal - Of or pertaining to a shield. A good example of these scutal monstrosities. Cussans.",
  "underlock - A lock of wool hanging under the belly of a sheep.",
  "integrally - In an integral manner; wholly; completely; also, by integration.",
  "water drainage - The draining off of water.",
  "treachour - A traitor. [Obs.] \"Treachour full of false despite.\" Spenser.",
  "neckerchief - A kerchief for the neck; -- called also neck handkerchief.",
  "cystose - Containing, or resembling, a cyst or cysts; cystic; bladdery.",
  "pyroantimonic - Pertaining to, or designating, an acid of antimony analogous to pyrophosphoric acid.",
  "precedaneous - Preceding; antecedent; previous. [Obs.] Hammond.",
  "pantographical - Of or pertaining to a pantograph; relating to pantography.",
  "unmovable - Immovable. \"Steadfast, unmovable.\" 1 Cor. xv. 58. Locke.",
  "so-called - So named; called by such a name (but perhaps called thus with doubtful propriety).",
  "indiscrimination - Want of discrimination or distinction; impartiality. Jefferson.",
  "evincive - Tending to prove; having the power to demonstrate; demonstrative; indicative.",
  "succiferous - Producing or conveying sap.",
  "adjutor - A helper or assistant. [Archaic] Drayton.",
  "examinator - An examiner. [R.] Sir T. Browne.",
  "milliard - A thousand millions; -- called also billion. See Billion.",
  "penteconter - A Grecian vessel with fifty oars. [Written also pentaconter.]",
  "impressionableness - The quality of being impressionable.",
  "orographic - Of or pertaining to orography.",
  "affiliable - Capable of being affiliated to or on, or connected with in origin.",
  "self-delusion - The act of deluding one's self, or the state of being thus deluded.",
  "carminated - Of, relating to, or mixed with, carmine; as, carminated lake. Tomlinson.",
  "intercidence - The act or state of coming or falling between; occurrence; incident. [Obs.] Holland.",
  "padow - A paddock, or toad. Padow pipe. (Bot.) See Paddock pipe, under Paddock.",
  "acraspeda - A group of acalephs, including most of the larger jellyfishes; the Discophora.",
  "nonemphatical - Having no emphasis; unemphatic.",
  "facto - In fact; by the act or fact. De facto. (Law) See De facto.",
  "phacolite - A colorless variety of chabazite; the original was from Leipa, in Bohemia.",
  "walk-mill - A fulling mill. [Prov. Eng.] Halliwell.",
  "coelacanth - Having hollow spines, as some ganoid fishes.",
  "asthenia - Want or loss of strength; debility; diminution of the vital forces.",
  "ultimation - State of being ultimate; that which is ultimate, or final; ultimatum. [R.] Swift.",
  "infralabial - Below the lower lip; -- said of certain scales of reptiles and fishes.",
  "prefidence - The quality or state of being prefident. [Obs.] Baxter.",
  "animadversal - The faculty of perceiving; a percipient. [Obs.] Dr. H. More.",
  "plain-dealing - Practicing plain dealing; artless. See Plain dealing, under Dealing. Shak.",
  "gastrolith - See Crab's eyes, under Crab.",
  "emydea - A group of chelonians which comprises many species of fresh- water tortoises and terrapins.",
  "ephraim - A hunter's name for the grizzly bear.",
  "exhortatory - Of or pertaining to exhortation; hortatory. Holinshed.",
  "cretose - Chalky; cretaceous. [Obs.] Ash.",
  "thenal - Of or pertaining to the thenar; corresponding to thenar; palmar.",
  "phonomotor - An instrument in which motion is produced by the vibrations of a sounding body.",
  "giddy-paced - Moving irregularly; flighty; fickle. [R.] Shak.",
  "paratonnerre - A conductor of lightning; a lightning rod.",
  "attractable - Capable of being attracted; subject to attraction. -- At*tract\"a*ble*ness, n.",
  "schillerization - The act or process of producing schiller in a mineral mass.",
  "penological - Of or pertaining to penology.",
  "organographic - Of or pertaining to organography.",
  "nasally - In a nasal manner; by the nose.",
  "garvie - The spart; -- called also garvie herring, and garvock. [Prov. Eng. & Scot.]",
  "underbranch - 1. A lower branch. 2. A twig or branchlet. [Obs.] Spenser.",
  "enchiridion - Handbook; a manual of devotions. Evelyn.",
  "derf - Strong; powerful; fierce. [Obs.] -- Derf\"ly, adv. [Obs.]",
  "jangler - 1. An idle talker; a babbler; a prater. Chaucer. 2. A wrangling, noisy fellow.",
  "satyrion - Any one of several kinds of orchids. [Obs.]",
  "auxometer - An instrument for measuring the magnifying power of a lens or system of lenses.",
  "atole - A porridge or gruel of maize meal and water, milk, or the like. [Sp. Amer.]",
  "spherosome - The body wall of any radiate animal.",
  "polynia - The open sea supposed to surround the north pole. Kane.",
  "hamadryas - The sacred baboon of Egypt (Cynocephalus Hamadryas).",
  "fault-finding - The act of finding fault or blaming; -- used derogatively. Also Adj.",
  "concordist - The compiler of a concordance.",
  "metatitanic - Of, pertaining to, or designating, an acid of titanium analogous to metasilicic acid.",
  "justificatory - Vindicatory; defensory; justificative.",
  "excusator - One who makes, or is authorized to make, an excuse; an apologist. [Obs.] Hume.",
  "fissipalmate - Semipalmate and loboped, as a grebe's foot. See Illust. under Aves.",
  "leiotrichan - Of or pertaining to the Leiotrichi. -- n.  One of the Leiotrichi.",
  "isagogic - Introductory; especially, introductory to the study of theology.",
  "perpetualty - The state or condition of being perpetual. [Obs.] Testament of Love.",
  "commensurably - In a commensurable manner; so as to be commensurable.",
  "mastodynia - Pain occuring in the mamma or female breast, -- a form of neuralgia.",
  "phanerogamic - Having visible flowers containing distinct stamens and pistils; -- said of plants.",
  "rackabones - A very lean animal, esp. a horse. [Colloq. U. S.]",
  "minable - Such as can be mined; as, minable earth. Sir T. North.",
  "fadaise - A vapid or meaningless remark; a commonplace; nonsense.",
  "setireme - A swimming leg (of an insect) having a fringe of hairs on the margin.",
  "palative - Pleasing to the taste; palatable. [Obs.] \"Palative delights.\" Sir T. Browne.",
  "comes - The answer to the theme (dux) in a fugue.",
  "acinetae - A group of suctorial Infusoria, which in the adult stage are stationary. See Suctoria.",
  "accustomable - Habitual; customary; wonted. \"Accustomable goodness.\" Latimer.",
  "subdulcid - Somewhat sweet; sweetish. [R.]",
  "sliddery - Slippery. [Obs.] To a drunk man the way is slidder. Chaucer.",
  "conveniently - In a convenient manner, form, or situation; without difficulty.",
  "flatling - With the flat side, as of a sword; flatlong; in a prostrate position. [Obs.] Spenser.",
  "begrimer - One who, or that which, begrimes.",
  "jaspideous - Consisting of jasper, or containing jasper; jaspery; jasperlike.",
  "transelementation - Transubstantiation. [Obs.]",
  "free-lover - One who believes in or practices free-love.",
  "childbearing - The act of producing or bringing forth children; parturition. Milton. Addison.",
  "alco - A small South American dog, domesticated by the aborigines.",
  "cornered - 1 Having corners or angles. 2. In a possition of great difficulty; brought to bay.",
  "inutterable - Unutterable; inexpressible. Milton.",
  "moquette - A kind of carpet having a short velvety pile.",
  "blusterous - Inclined to bluster; given to blustering; blustering. Motley.",
  "arhythmic - See Arrhizal, Arrhizous, Arrhythmic, Arrhythmous.",
  "explat - To explain; to unfold. [Obs.] Like Solon's self explatest the knotty laws. B. Jonson.",
  "hypothetist - One who proposes or supports an hypothesis. [R.]",
  "mandola - An instrument closely resembling the mandolin, but of larger size and tuned lower.",
  "theretofore - Up to that time; before then; -- correlative with heretofore.",
  "doorway - The passage of a door; entrance way into a house or a room.",
  "upsetting - Conceited; assuming; as, an upsetting fellow. [Scot.] Jamieson.",
  "jucundity - Pleasantness; agreeableness. See Jocundity. [R.] Sir T. Browne.",
  "weet-weet - (a) The common European sandpiper. (b) The chaffinch. [Prov. Eng.]",
  "inevidence - Want of evidence; obscurity. [Obs.] Barrow.",
  "hurries - A staith or framework from which coal is discharged from cars into vessels.",
  "concho-spiral - A kind of spiral curve found in certain univalve shells. Agassiz.",
  "photoluminescent - Luminescent by exposure to light waves. -- Pho`to*lu`mi*nes\"cence (#), n.",
  "chronography - A description or record of past time; history. [Obs.] Bp. Hall.",
  "thickskull - A dullard, or dull person; a blockhead; a numskull. Entick.",
  "extricable - Capable of being extricated. Sir W. Jones.",
  "intermean - Something done in the meantime; interlude. [Obs.] B. Jonson.",
  "fly-case - The covering of an insect, esp. the elytra of beetles.",
  "embasement - Act of bringing down; depravation; deterioration. South.",
  "carman - A man whose employment is to drive, or to convey goods in, a car or car.",
  "tisar - The fireplace at the side of an annealing oven. Knight.",
  "shipbuilding - Naval architecturel the art of constructing ships and other vessels.",
  "self-gratulation - Gratulation of one's self.",
  "dare-deviltry - Reckless mischief; the action of a dare-devil.",
  "malleate - To hammer; to beat into a plate or leaf.",
  "denticle - A small tooth or projecting point.",
  "snide - Tricky; deceptive; contemptible; as, a snide lawyer; snide goods. [Slang]",
  "retroflexion - The act of reflexing; the state of being retroflexed. Cf. Retroversion.",
  "hydrogenous - Of or pertaining to hydrogen; containing hydrogen.",
  "rose water - Water tinctured with roses by distillation.",
  "sponsible - responsible; worthy of credit. [Prov. Eng. & Scot.]",
  "inequidistant - Not equally distant; not equidistant.",
  "hariali grass - The East Indian name of the Cynodon Dactylon; dog's-grass.",
  "snatcher - One who snatches, or takes abruptly.",
  "inferobranchian - One of the Inferobranchiata.",
  "hemicerebrum - A lateral half of the cerebrum. Wilder.",
  "raphaelism - The principles of painting introduced by Raphael, the Italian painter.",
  "unaccountability - The quality or state of being unaccountable.",
  "minutary - Pertaining to, or consisting of, minutes. [Obs.] Fuller.",
  "resistant - Making resistance; resisting. -- n.  One who, or that which, resists. Bp. Pearson.",
  "henceforward - From this time forward; henceforth.",
  "laryngoscopist - One skilled in laryngoscopy.",
  "papillulate - Having a minute papilla in the center of a larger elevation or depression.",
  "debaser - One who, or that which, debases.",
  "digraphic - Of or pertaining to a digraph. H. Sweet.",
  "pattened - Wearing pattens. \"Some pattened girl.\" Jane Austen.",
  "hybernacle - See Hibernacle, Hibernate, Hibernation.",
  "baroscopical - Pertaining to, or determined by, the baroscope.",
  "inter- - A prefix signifying among, between, amid; as, interact, interarticular, intermit.",
  "indrench - To overwhelm with water; to drench; to drown. [Obs.] Shak.",
  "matrimonially - In a matrimonial manner.",
  "single-hearted - Having an honest heart; free from duplicity. -- Sin\"gle-heart\"ed*ly, adv.",
  "semiphlogisticated - Partially impregnated with phlogiston.",
  "cornsheller - A machine that separates the kernels of corn from the cob.",
  "tylarus - One of the pads on the under surface of the toes of birds.",
  "stalwartness - The quality of being stalwart.",
  "myotomy - The dissection, or that part of anatomy which treats of the dissection, of muscles.",
  "tentaculata - A division of Ctenophora including those which have two long tentacles.",
  "incenter - The center of the circle inscribed in a triangle.",
  "contradictive - Contradictory; inconsistent. -- Con`tra*dict\"ive*ly, adv..",
  "pactitious - Setted by a pact, or agreement. [R.] Johnson.",
  "lithotomical - Pertaining to, or performed by, lithotomy.",
  "invious - Untrodden. [R.] Hudibras. -- In\"vi*ous*ness, n. [R.]",
  "neuropodium - The ventral lobe or branch of a parapodium.",
  "egression - The act of going; egress. [R.] B. Jonson.",
  "blandisher - One who uses blandishments.",
  "volitation - The act of flying; flight. [R.] Sir T. Browne.",
  "piped - Formed with a pipe; having pipe or pipes; tubular.",
  "architective - Used in building; proper for building. Derham.",
  "matfelon - The knapweed (Centaurea nigra).",
  "fustianist - A writer of fustian. [R.] Milton.",
  "orchanet - Same as Alkanet, 2. Ainsworth.",
  "bezoartic - Having the qualities of an antidote, or of bezoar; healing. [Obs.]",
  "conduplication - A doubling together or folding; a duplication. [R.]",
  "daun - A variant of Dan, a title of honor. [Obs.] Chaucer.",
  "marined - Having the lower part of the body like a fish. Crabb.",
  "nosegay - A bunch of odorous and showy flowers; a bouquet; a posy. Pope.",
  "riotise - Excess; tumult; revelry. [Obs.] His life he led in lawless riotise. Spenser.",
  "unexpectation - Absence of expectation; want of foresight. [Obs.] Bp. Hall.",
  "elucubrate - See Lucubrate. [Obs.] Blount.",
  "technics - The doctrine of arts in general; such branches of learning as respect the arts.",
  "outsail - To excel, or to leave behind, in sailing; to sail faster than. Beau. & Fl.",
  "arew - In a row. [Obs.] \"All her teeth arew.\" Spenser.",
  "officiary - Of or pertaining to an office or an officer; official. [R.] Heylin.",
  "ansa - A name given to either of the projecting ends of Saturn's ring.",
  "actinolite - A bright green variety of amphibole occurring usually in fibrous or columnar masses.",
  "heirdom - The state of an heir; succession by inheritance. Burke.",
  "nys - Is not. See Nis. Chaucer. Spenser.",
  "decimetre - A measure of length in the metric system; one tenth of a meter, equal to 3.937 inches.",
  "quatre - A card, die. or domino, having four spots, or pips",
  "idiocratical - Peculiar in constitution or temperament; idiosyncratic.",
  "overlashing - Excess; exaggeration. [Obs.]",
  "eightling - A compound or twin crystal made up of eight individuals.",
  "half-strained - Half-bred; imperfect. [R.] \"A half-strained villain.\" Dryden.",
  "butting - An abuttal; a boundary. Without buttings or boundings on any side. Bp. Beveridge.",
  "inalimental - Affording no aliment or nourishment. [Obs.] Bacon.",
  "pelvimeter - An instrument for measuring the dimensions of the pelvis. Coxe.",
  "apprehensiveness - The quality or state of being apprehensive.",
  "instinctivity - The quality of being instinctive, or prompted by instinct. [R.] Coleridge.",
  "delactation - The act of weaning. [Obs.] Bailey.",
  "camoys - Flat; depressed; crooked; -- said only of the nose. [Obs.]",
  "sodger - Var. of Soldier. [Dial. or Slang]",
  "divinistre - A diviner. [Obs.] \" I am no divinistre.\" Chaucer.",
  "scratch player - One that starts from the scratch; hence, one of first-rate ability.",
  "sunsted - Solstice. [Obs.] \"The summer sunsted.\" Holland.",
  "demonological - Of or Pertaining to demonology.",
  "primigenial - First born, or first of all; original; primary. See Primogenial.",
  "deturbation - The act of deturbating. [Obs.]",
  "parodic - Having the character of parody. Very paraphrastic, and sometimes parodical. T. Warton.",
  "accentual - Of or pertaining to accent; characterized or formed by accent.",
  "incensory - The vessel in which incense is burned and offered; a censer; a thurible. [R.] Evelyn.",
  "toothpick - A pointed instument for clearing the teeth of substances lodged between them.",
  "nymphlike - Resembling, or characteristic of, a nymph.",
  "stepmother - The wife of one's father by a subsequent marriage.",
  "carping - Fault-finding; censorious caviling. See Captious. -- Carp\"ing*ly, adv.",
  "curiality - The privileges, prerogatives, or retinue of a court. [Obs.] Bacon.",
  "fungicide - Anything that kills fungi. -- Fun`gi*ci\"dal, n.",
  "pigeonry - A place for pigeons; a dovecote.",
  "bimestrial - Continuing two months. [R.]",
  "recentness - Quality or state of being recent.",
  "montoir - A stone used in mounting a horse; a horse block.",
  "humanness - The quality or state of being human.",
  "allyl - An organic radical, C3H5, existing especially in oils of garlic and mustard.",
  "uphand - Lifted by the hand, or by both hands; as, the uphand sledge. [R.] Moxon.",
  "enubilous - Free from fog, mist, or clouds; clear. [R.]",
  "parapectin - A gelatinous modification of pectin.",
  "pericarp - The ripened ovary; the walls of the fruit. See Illusts. of Capsule, Drupe, and Legume.",
  "luce - A pike when full grown. Halliwell.",
  "pleochroic - Having the property of pleochroism.",
  "pepsinhydrochloric - Same as Peptohydrochloric.",
  "profulgent - Shining forth; brilliant; effulgent. [Obs.] \"Profulgent in preciousness.\" Chaucer.",
  "parching - Scorching; burning; drying. \"Summer's parching heat.\" Shak. -- Parch\"ing*ly, adv.",
  "curledness - State of being curled; curliness.",
  "minette - The smallest of regular sizes of portrait photographs.",
  "orthopraxy - The treatment of deformities in the human body by mechanical appliances.",
  "torpedo catcher - A small fast vessel for pursuing and destroying torpedo boats.",
  "highering - Rising higher; ascending. In ever highering eagle circles. Tennyson.",
  "shonde - Harm; disgrace; shame. [Obs.] Chaucer.",
  "ostracodermi - A suborder of fishes of which Ostracion is the type.",
  "keld - Having a kell or covering; webbed. [Obs.] Drayton.",
  "schmelze - A kind of glass of a red or ruby color, made in Bohemia.",
  "rubification - The act of making red. Howell.",
  "finlet - A little fin; one of the parts of a divided fin.",
  "mandolin - A small and beautifully shaped instrument resembling the lute.",
  "numskull - A dunce; a dolt; a stupid fellow. [Colloq.] They have talked like numskulls. Arbuthnot.",
  "ruralism - 1. The quality or state of being rural; ruralness. 2. A rural idiom or expression.",
  "anticor - A dangerous inflammatory swelling of a horse's breast, just opposite the heart.",
  "egyptologer - One skilled in the antiquities of Egypt; a student of Egyptology.",
  "bewonder - 1. To fill with wonder. [Obs.] 2. To wonder at; to admire. [Obs.]",
  "annuitant - One who receives, or its entitled to receive, an annuity. Lamb.",
  "insectary - A place for keeping living insects. -- In`sec*ta\"ri*um, n. Etym: [L.]",
  "copepod - Of or pertaining to the Copepoda. -- n.  One of the Copepoda.",
  "waverer - One who wavers; one who is unsettled in doctrine, faith, opinion, or the like. Shak.",
  "fiddle-shaped - Inversely ovate, with a deep hollow on each side. Gray.",
  "sleepwaker - On in a state of magnetic or mesmeric sleep.",
  "primogenitor - The first ancestor; a forefather.",
  "weazen - Thin; sharp; withered; wizened; as, a weazen face. They were weazen and shriveled. Dickens.",
  "sathanas - Satan. [Obs.] Chaucer. Wyclif.",
  "astrophotometer - A photometer for measuring the brightness of stars.",
  "stillion - A stand, as for casks or vats in a brewery, or for pottery while drying.",
  "commenter - One who makes or writes comments; a commentator; an annotator.",
  "handyfight - A fight with the hands; boxing. \"Pollux loves handyfights.\" B. Jonson.",
  "alar - 1. Pertaining to, or having, wings. 2. (Bot.)  Axillary; in the fork or axil. Gray.",
  "abawed - Astonished; abashed. [Obs.] Chaucer.",
  "institutist - A writer or compiler of, or a commentator on, institutes. [R.] Harvey.",
  "underfellow - An underling [R.] Sir P. Sidney.",
  "contrafagetto - The double bassoon, an octave deeper than the bassoon.",
  "herologist - One who treats of heroes. [R.] T. Warton.",
  "truncal - Of or pertaining to the trunk, or body.",
  "strabismometer - An instrument for measuring the amount of strabismus.",
  "chievance - An unlawful bargain; traffic in which money is exported as discount. [Obs.] Bacon.",
  "obscurement - The act of obscuring, or the state of being obscured; obscuration. Pomfret.",
  "impressionist - One who adheres to the theory or method of impressionism, so called.",
  "promorphological - Relating to promorphology; as, a promorphological conception.",
  "peacebreaker - One who disturbs the public peace. -- Peace\"break`ing, n.",
  "soyned - Filled with care; anxious. [Obs.] Mir. for Mag.",
  "acutely - In an acute manner; sharply; keenly; with nice discrimination.",
  "gryllus - A genus of insects including the common crickets.",
  "propylic - Pertaining to, derived from, or containing, propyl; as, propylic alcohol.",
  "cumidine - A strong, liquid, organic base, C3H7.C6H4.NH2, homologous with aniline.",
  "intastable - Incapable of being tasted; tasteless; unsavory. [R.] Grew.",
  "men-pleaser - One whose motive is to please men or the world, rather than God. Eph. vi. 6.",
  "self-accused - Accused by one's self or by one's conscience. \"Die self- accused.\" Cowper.",
  "sabellianism - The doctrines or tenets of Sabellius. See Sabellian, n.",
  "gumminess - The state or quality of being gummy; viscousness.",
  "sepiostare - The bone or shell of cuttlefish. See Illust. under Cuttlefish.",
  "hyponitrite - A salt of hyponitrous acid.",
  "negrohead - An inferior commercial variety of India rubber made up into round masses.",
  "monisher - One who monishes; an admonisher. [Archaic]",
  "like-minded - Having a like disposition or purpose; of the same mind. Tillotson.",
  "flammeous - Pertaining to, consisting of, or resembling, flame. [Obs.] Sir T. Browne.",
  "soldanel - A plant of the genus Soldanella, low Alpine herbs of the Primrose family.",
  "indorser - The person who indorses. [Written also endorser.]",
  "stoechiometry - See Stoichiology, Stoichiometry, etc.",
  "crustalogist - One versed in crustalogy.",
  "accrument - The process of accruing, or that which has accrued; increase. Jer. Taylor.",
  "pectostraca - A degenerate order of Crustacea, including the Rhizocephala and Cirripedia.",
  "teary - 1. Wet with tears; tearful. 2. Consisting of tears, or drops like tears.",
  "somnipathist - A person in a state of somniapathy.",
  "inertly - Without activity; sluggishly. Pope.",
  "hump-shouldered - Having high, hunched shoulders. Hawthorne.",
  "oleaginous - Having the nature or qualities of oil; oily; unctuous.",
  "malashaganay - The fresh-water drumfish (Haploidonotus grunniens).",
  "beetrave - The common beet (Beta vulgaris).",
  "scalenohedral - Of or pertaining to a scalenohedron.",
  "pluripresence - Presence in more places than one. [R.] Johnson.",
  "irrepleviable - Not capable of being replevied.",
  "fleecer - One who fleeces or strips unjustly, especially by trickery or fraund. Prynne.",
  "impairment - The state of being impaired; injury. \"The impairment of my health.\" Dryden.",
  "mariolater - One who worships the Virgin Mary.",
  "reticle - 1. A small net. 2. A reticule. See Reticule,2. [R.]",
  "antipapal - Opposed to the pope or to popery. Milton.",
  "sulphostannate - A salt of sulphostannic acid.",
  "phosphoresce - To shine as phosphorus; to be phosphorescent; to emit a phosphoric light.",
  "carpogenic - Productive of fruit, or causing fruit to be developed.",
  "triture - A rubbing or grinding; trituration. [Obs.] Cheyne.",
  "yesternoon - The noon of yesterday; the noon last past.",
  "doomful - Full of condemnation or destructive power. [R.] \"That doomful deluge.\" Drayton.",
  "foregleam - An antecedent or premonitory gleam; a dawning light. The foregleams of wisdom. Whittier.",
  "truancy - The act of playing truant, or the state of being truant; as, addicted to truancy.",
  "arcubalister - A crossbowman; one who used the arcubalist. Camden.",
  "allophylian - Pertaining to a race or a language neither Aryan nor Semitic. J. Prichard.",
  "placodermal - Of or pertaining to the placoderms; like the placoderms.",
  "sphacelated - Affected with gangrene; mortified.",
  "grindingly - In a grinding manner. [Colloq.]",
  "tollable - Subject to the payment of toll; as, tollable goods. Wright.",
  "nonconduction - The quality of not being able to conduct or transmit; failure to conduct.",
  "philip - (a) The European hedge sparrow. (b) The house sparrow. Called also phip. [Prov. Eng.]",
  "thinkable - Capable of being thought or conceived; cogitable. Sir W. Hamilton.",
  "tystie - The black guillemot. [Prov. Eng.]",
  "flagellation - A beating or flogging; a whipping; a scourging. Garth.",
  "accustomedness - Habituation. Accustomedness to sin hardens the heart. Bp. Pearce.",
  "intelligency - Intelligence. [Obs.] Evelyn.",
  "crossbowman - One who shoots with a crossbow. See Arbalest.",
  "geisha - A Japanese singing and dancing girl.",
  "formful - Creative; imaginative. [R.] \"The formful brain.\" Thomson.",
  "garefowl - The great auk; also, the razorbill. See Auk. [Written also gairfowl, and gurfel.]",
  "vidonia - A dry white wine, of a tart flavor, produced in Teneriffe; -- called also Teneriffe.",
  "mycology - That branch of botanical science which relates to the musgrooms and other fungi.",
  "phosphorite - (min.) A massive variety of apatite.",
  "farsightedness - 1. Quality of bbeing farsighted. 2. (Med.)  Hypermetropia.",
  "revelate - To reveal. [Obs.] Frith. Barnes.",
  "disembay - To clear from a bay. Sherburne.",
  "decistere - The tenth part of the stere or cubic meter, equal to 3.531 cubic feet. See Stere.",
  "transvolation - The act of flying beyond or across. Jer. Taylor.",
  "maggoty - 1. Infested with maggots. 2. Full of whims; capricious. Norris.",
  "myolin - The essential material of muscle fibers.",
  "chorda - A cord. Chorda dorsalis (. Etym: [NL., lit., cord of the back.] (Anat.) See Notochord.",
  "mendicity - The practice of begging; the life of a beggar; mendicancy. Rom. of R.",
  "tardigradous - Moving slowly; slow-paced. [Obs.] Sir T. Browne.",
  "biblicality - The quality of being biblical; a biblical subject. [R.]",
  "feather-brained - Giddy; frivolous; feather-headed. [Colloq.]",
  "beshroud - To cover with, or as with, a shroud; to screen.",
  "fenceful - Affording defense; defensive. [Obs.] Congreve.",
  "distasture - Something which excites distaste or disgust. [Obs.] Speed.",
  "allantoidal - Of or pertaining to the allantois.",
  "fibrinous - Having, or partaking of the properties of, fibrin; as, fibrious exudation.",
  "balaniferous - Bearing or producing acorns.",
  "swanky - An active and clever young fellow. [Scot.] Sir W. Scott.",
  "flittern - A term applied to the bark obtained from young oak trees. McElrath.",
  "halberdier - One who is armed with a halberd. Strype.",
  "cottonseed meal - A meal made from hulled cotton seeds after the oil has been expressed.",
  "phytotomy - The dissection of plants; vegetable anatomy.",
  "polyacoustic - Multiplying or magnifying sound. -- n.  A polyacoustic instrument.",
  "notelet - A little or short note; a billet.",
  "lethality - The quality of being lethal; mortality.",
  "dust-point - An old rural game. With any boy at dust-point they shall play. Peacham (1620).",
  "absorptiveness - The quality of being absorptive; absorptive power.",
  "detteles - Free from debt. [Obs.] Chaucer.",
  "literality - The state or quality of being literal. Sir T. Browne.",
  "withamite - A variety of epidote, of a reddish color, found in Scotland.",
  "moril - An edible fungus. Same as 1st Morel.",
  "sourness - The quality or state of being sour.",
  "ramiparous - Producing branches; ramigerous.",
  "tristfully - In a tristful manner; sadly.",
  "meatless - Having no meat; without food. \"Leave these beggars meatless.\" Sir T. More.",
  "nagor - A West African gazelle (Gazella redunca).",
  "uncustomable - Not customable, or subject to custom duties.",
  "swaddlebill - The shoveler. [Local, U.S.]",
  "buceros - A genus of large perching birds; the hornbills.",
  "sward-cutter - (a) A plow for turning up grass land. (b) A lawn mower.",
  "gastromyces - The fungoid growths sometimes found in the stomach; such as Torula, etc.",
  "hydrobilirubin - A body formed from bilirubin, identical with urobilin.",
  "cognateness - The state of being cognate.",
  "leat - An artificial water trench, esp. one to or from a mill. C. Kingsley.",
  "sation - A sowing or planting. [Obs.] Sir T. Browne.",
  "almsdeed - An act of charity. Acts ix. 36.",
  "ament - A species of inflorescence; a catkin. The globular ament of a buttonwood. Coues.",
  "terreous - Consisting of earth; earthy; as, terreous substances; terreous particles. [Obs.]",
  "intralobular - Within lobules; as, the intralobular branches of the hepatic veins.",
  "fellmonger - A dealer in fells or sheepskins, who separates the wool from the pelts.",
  "intermittently - With intermissions; in an intermittent manner; intermittingly.",
  "botryogen - A hydrous sulphate of iron of a deep red color. It often occurs in botryoidal form.",
  "debted - Indebted; obliged to. [R.] I stand debted to this gentleman. Shak.",
  "multiseptate - Divided into many chambers by partitions, as the pith of the pokeweed.",
  "pockmark - A mark or pit made by smallpox.",
  "oecology - The various relations of animals and plants to one another and to the outer world.",
  "pennached - Variegated; striped. [Obs.] Evelyn.",
  "ebracteolate - Without bracteoles, or little bracts; -- said of a pedicel or flower stalk.",
  "amioid - Like or pertaining to the Amioidei. -- n.  One of the Amioidei.",
  "panhellenist - An advocate of Panhellenism.",
  "gashful - Full of gashes; hideous; frightful. [Obs.] \"A gashful, horrid, ugly shape.\" Gayton.",
  "crinoidal - Of pertaining to crinoids; consisting of, or containing, crinoids.",
  "sea lavender - See Marsh rosemary, under Marsh.",
  "entoderm - See Endoderm, and Illust. of Blastoderm.",
  "dialist - A maker of dials; one skilled in dialing.",
  "dehorter - A dissuader; an adviser to the contrary. [Obs.]",
  "re-reiterate - To reiterate many times. [R.] \"My re-reiterated wish.\" Tennyson.",
  "embarkment - Embarkation. [R.] Middleton.",
  "atmospherically - In relation to the atmosphere.",
  "alpia - The seed of canary grass (Phalaris Canariensis), used for feeding cage birds.",
  "adenotomy - Dissection of, or incision into, a gland or glands.",
  "scrit - Writing; document; scroll. [Obs.] \"Of every scrit and bond.\" Chaucer.",
  "juiceless - Lacking juice; dry. Dr. H. More.",
  "noble-minded - Having a noble mind; honorable; magnanimous. -- No\"ble-mind`ed*ness, n.",
  "farthermost - Most distant or remote; as, the farthest degree. See Furthest.",
  "gruntle - To grunt; to grunt repeatedly. [Obs.]",
  "invocatory - Making or containing invocation; invoking.",
  "interscapulars - The interscapular feathers of a bird.",
  "linament - Lint; esp., lint made into a tent for insertion into wounds or ulcers.",
  "masticable - Capable of being masticated.",
  "ethnologist - One versed in ethnology; a student of ethnology.",
  "allusiveness - The quality of being allusive.",
  "xanthochroid - Having a yellowish or fair complexion. -- n.  A person having xanthochroid traits.",
  "disarmature - The act of divesting of armature. [R.]",
  "iconodule - One who serves images; -- opposed to an iconoclast. Schaff- Herzog Encyc.",
  "encase - To inclose as in a case. See Incase. Beau. & Fl.",
  "wrawl - To cry, as a cat; to waul. [Obs.] Spenser.",
  "chloropeptic - Of or pertaining to an acid more generally called pepsin- hydrochloric acid.",
  "dethronement - Deposal from a throne; deposition from regal power.",
  "physiographical - Of or pertaining to physiography.",
  "impassionable - Excitable; susceptible of strong emotion.",
  "monocephalous - Having a solitary head; -- said of unbranched composite plants.",
  "precipitability - The quality or state of being precipitable.",
  "roundridge - To form into round ridges by plowing. B. Edwards.",
  "opiniaster - Opinionated. [Obs.] Sir W. Raleigh.",
  "archontate - An archon's term of office. Gibbon.",
  "sweltry - Suffocating with heat; oppressively hot; sultry. [R.] Evelyn.",
  "marmorean - Pertaining to, or resembling, marble; made of marble.",
  "surah - A soft twilled silk fabric much used for women's dresses; -- called also surah silk.",
  "unsatisfaction - Dissatisfaction. [Obs.] Bp. Hall.",
  "candify - To make or become white, or candied. [R.]",
  "hummeler - One who, or a machine which, hummels.",
  "galvanopuncture - Same as Electro-puncture.",
  "interposal - The act of interposing; interposition; intervention.",
  "suji - Indian wheat, granulated but not pulverized; a kind of semolina. [Written also soojee.]",
  "breastpin - A pin worn on the breast for a fastening, or for ornament; a brooch.",
  "moderateness - The quality or state of being moderate; temperateness; moderation.",
  "acephalist - One who acknowledges no head or superior. Dr. Gauden.",
  "billsticker - One whose occupation is to post handbills or posters in public places.",
  "papiliones - The division of Lepidoptera which includes the butterflies.",
  "overfeed - To feed to excess; to surfeit.",
  "sober-minded - Having a disposition or temper habitually sober. -- So\"ber-mind`ed*ness, n.",
  "vaporiferous - Conveying or producing vapor.",
  "potpie - A meat pie which is boiled instead of being baked.",
  "seamanship - The skill of a good seaman; the art, or skill in the art, of working a ship.",
  "regularia - A division of Echini which includes the circular, or regular, sea urchins.",
  "talmudist - One versed in the Talmud; one who adheres to the teachings of the Talmud.",
  "lacquerer - One who lacquers, especially one who makes a business of lacquering.",
  "batterer - One who, or that which, batters.",
  "catechetics - The science or practice of instructing by questions and answers.",
  "excarnificate - To clear of flesh; to excarnate. Dr. H. More.",
  "sheller - One who, or that which, shells; as, an oyster sheller; a corn sheller.",
  "deprisure - Low estimation; disesteem; contempt. [Obs.]",
  "regenesis - New birth; renewal. A continued regenesis of dissenting sects. H. Spenser.",
  "amrita - Immorality; also, the nectar conferring immortality. -- a. Ambrosial; immortal.",
  "blaeberry - The bilberry. [North of Eng. & Scot.]",
  "archiepiscopal - Of or pertaining to an archbishop; as, Canterbury is an archiepiscopal see.",
  "inorthography - Deviation from correct orthography; bad spelling. [Obs.] Feltham.",
  "flagginess - The condition of being flaggy; laxity; limberness. Johnson.",
  "vitiosity - Viciousness; depravity. The perverseness and vitiosity of man's will. South.",
  "gaited - Having (such) a gait; -- used in composition; as, slow-gaited; heavy-gaited.",
  "inkstone - A kind of stone containing native vitriol or subphate of iron, used in making ink.",
  "woolward - In wool; with woolen raiment next the skin. [Obs.]",
  "throw-crook - An instrument used for twisting ropes out of straw.",
  "neurography - A description of the nerves. Dunglison.",
  "chondroma - A cartilaginous tumor or growth.",
  "elmy - Abounding with elms. The simple spire and elmy grange. T. Warton.",
  "redition - Act of returning; return. [Obs.] Chapman.",
  "homoeopathy - Same as Homeopathic, Homeopathist, Homeopathy.",
  "underfaction - A subordinate party or faction.",
  "tergeminal - Thrice twin; having three pairs of leaflets.",
  "demonry - Demoniacal influence or possession. J. Baillie.",
  "angola - A fabric made from the wool of the Angora goat.",
  "pseudonymity - The using of fictitious names, as by authors.",
  "footpath - A narrow path or way for pedestrains only; a footway.",
  "marceline - A thin silk fabric used for linings, etc., in ladies' dresses.",
  "christlike - Resembling Christ in character, actions, etc. -- Christ\"like`ness, n.",
  "sarcological - Of or pertaining to sarcology.",
  "trihybrid - A hybrid whose parents differ by three pairs of contrasting Mendelian characters.",
  "semiplume - A feather which has a plumelike web, with the shaft of an ordinary feather.",
  "paludine - Of or pertaining to a marsh. Buckland.",
  "hot-head - A violent, passionate person; a hasty or impetuous person; as, the rant of a hot-head.",
  "galeopithecus - A genus of flying Insectivora, formerly called flying lemurs. See Colugo.",
  "decumbence - The act or posture of lying down. The ancient manner of decumbency. Sir T. Browne.",
  "senza - Without; as, senza stromenti, without instruments.",
  "grangerize - To collect (illustrations from books) for decoration of other books. G. A. Sala.",
  "dukeling - A little or insignificant duke. Ford.",
  "self-moved - Moved by inherent power., without the aid of external impulse.",
  "volcanism - Volcanic power or action; volcanicity.",
  "stichic - Of or pertaining to stichs, or lines; consisting of stichs, or lines. [R.]",
  "pertused - Punched; pierced with, or having, holes.",
  "dipsomaniac - One who has an irrepressible desire for alcoholic drinks.",
  "good-tempered - Having a good temper; not easily vexed. See Good-natured.",
  "noblewoman - A female of noble rank; a peeress.",
  "dreamful - Full of dreams. \" Dreamful ease.\" Tennyson. -- Dream\"ful*ly, adv.",
  "stone-deaf - As deaf as a stone; completely deaf.",
  "crevet - A crucible or melting pot; a cruset. Crabb.",
  "cheeselep - A bag in which rennet is kept.",
  "calligraphic - Of or pertaining to calligraphy. Excellence in the calligraphic act. T. Warton.",
  "fumingly - In a fuming manner; angrily. \"They answer fumingly.\" Hooker.",
  "monopodial - Having a monopodium or a single and continuous axis, as a birchen twig or a cornstalk.",
  "talookdar - A proprietor of a talook. [India]",
  "confusedness - A state of confusion.  Norris.",
  "norian - Pertaining to the upper portion of the Laurentian rocks. T. S. Hunt.",
  "penetrativeness - The quality of being penetrative.",
  "moorland - Land consisting of a moor or moors.",
  "purposeful - Important; material. \"Purposeful accounts.\" Tylor. -- Pur\"pose*ful*ly, adv.",
  "palestric - Of or pertaining to the palestra, or to wrestling.",
  "intermure - To wall in; to inclose. [Obs.] Ford.",
  "arthen - Same as Earthen. [Obs.] \"An arthen pot.\" Holland.",
  "kill-joy - One who causes gloom or grief; a dispiriting person. W. Black.",
  "surfacer - A form of machine for dressing the surface of wood, metal, stone, etc.",
  "yunx - A genus of birds comprising the wrynecks.",
  "plano-subulate - Smooth and awl-shaped. See Subulate.",
  "crazedness - A broken state; decrepitude; an impaired state of the intellect.",
  "sassenach - A Saxon; an Englishman; a Lowlander. [Celtic] Sir W. Scott.",
  "ethologist - One who studies or writes upon ethology.",
  "doctrinarianism - The principles or practices of the Doctrinaires.",
  "foliferous - Producing leaves. [Written also foliiferous.]",
  "accountancy - The art or employment of an accountant.",
  "inimitability - The quality or state of being inimitable; inimitableness. Norris.",
  "jury-rigged - Rigged for temporary service. See Jury, a.",
  "incliner - One who, or that which, inclines; specifically, an inclined dial.",
  "hardbeam - A tree of the genus Carpinus, of compact, horny texture; hornbeam.",
  "diiambus - A double iambus; a foot consisting of two iambuses (",
  "diseasedness - The state of being diseased; a morbid state; sickness. [R.] T. Burnet.",
  "calvaria - The bones of the cranium; more especially, the bones of the domelike upper portion.",
  "ghebre - A worshiper of fire; a Zoroastrian; a Parsee.",
  "perfectionism - The doctrine of the Perfectionists.",
  "pluriliteral - Consisting of more letters than three. -- n.  A pluriliteral word.",
  "presensation - Previous sensation, notion, or idea. [Obs.] Dr. H. More.",
  "villatic - Of or pertaining to a farm or a village; rural. \"Tame villatic fowl.\" Milton.",
  "sagum - The military cloak of the Roman soldiers.",
  "thermoanaesthesia - Loss of power to distinguish heat or cold by touch.",
  "intercedence - The act of interceding; intercession; intervention. [R.] Bp. Reynolds."
]