export default [
  "supplicatory - Containing supplication; humble; earnest.",
  "cornu - A horn, or anything shaped like or resembling a horn.",
  "juglandine - An alkaloid found in the leaves of the walnut (Juglans regia).",
  "primateship - The office, dignity, or position of a primate; primacy.",
  "impunctuality - Neglect of, or failure in, punctuality. [R.] A. Hamilton.",
  "stirt - Started; leaped. They privily be stirt into a well. Chaucer.",
  "articulateness - Quality of being articulate.",
  "scorie - The young of any gull. [Written also scaurie.] [prov. Eng.]",
  "laccin - A yellow amorphous substance obtained from lac.",
  "angiography - A description of blood vessels and lymphatics.",
  "nonet - A composition for nine instruments, rarely for nine voices.",
  "glassmaker - One who makes, or manufactures, glass. -- Glass\" mak`ing, or Glass\"mak`ing, n.",
  "hederiferous - Producing ivy; ivy-bearing.",
  "loir - A large European dormouse (Myoxus glis).",
  "paronym - A paronymous word. [Written also paronyme.]",
  "co-sufferer - One who suffers with another. Wycherley.",
  "worldly-wise - Wise in regard to things of this world. Bunyan.",
  "festally - Joyously; festively; mirthfully.",
  "thermolyze - To subject to thermolysis; to dissociate by heat.",
  "quinquangular - Having five angles or corners.",
  "tepor - Gentle heat; moderate warmth; tepidness. Arbuthnot.",
  "simplist - One skilled in simples, or medicinal plants; a simpler. Sir T. Browne.",
  "pococurantism - Carelessness; apathy; indifference. [R.] Carlyle.",
  "unspirit - To dispirit. [Obs.] Sir W. Temple.",
  "brachiopod - One of the Brachiopoda, or its shell.",
  "employer - One who employs another; as, an employer of workmen.",
  "twistical - Crooked; tortuous; hence, perverse; unfair; dishonest. [Slang, U. S.] Bartlett.",
  "sithen - Since; afterwards. See 1st Sith. [Obs.] Fortune was first friend and sithen foe. Chaucer.",
  "proser - 1. A writer of prose. [Obs.] 2. One who talks or writes tediously. Sir W. Scott.",
  "glomuliferous - Having small clusters of minutely branched coral-like excrescences. M. C. Cooke.",
  "erin - An early, and now a poetic, name of Ireland.",
  "hairpin - A pin, usually forked, or of bent wire, for fastening the hair in place, -- used by women.",
  "illimitation - State of being illimitable; want of, or freedom from, limitation. Bp. Hall.",
  "nectariferous - Secreting nectar; -- said of blossoms or their parts.",
  "matie - A fat herring with undeveloped roe. [Written also matty.] [Eng. & Scot.]",
  "aeruginous - Of the nature or color of verdigris, or the rust of copper.",
  "polyphore - A receptacle which bears many ovaries.",
  "white-foot - A white mark on the foot of a horse, between the fetlock and the coffin.",
  "quoll - A marsupial of Australia (Dasyurus macrurus), about the size of a cat.",
  "serjeant - See Sergeant, Sergeantcy, etc. Serjeant-at-arms. See Sergeant- at-arms, under Sergeant.",
  "pin-tailed - Having a tapered tail, with the middle feathers longest; -- said of birds.",
  "oreographic - Of or pertaining to oreography.",
  "reviver - One who, or that which, revives.",
  "discovenant - To dissolve covenant with.",
  "munific - Munificent; liberal. [Obs. or R.]",
  "anticlinal - The crest or line in which strata slope or dip in opposite directions.",
  "indorsable - Capable of being indorsed; transferable; convertible.",
  "serio-comical - Having a mixture of seriousness and sport; serious and comical.",
  "apiked - Trimmed. [Obs.] Full fresh and new here gear apiked was. Chaucer.",
  "genialness - The quality of being genial.",
  "santoninate - A salt of santoninic acid.",
  "bilinguist - One versed in two languages.",
  "scutage - Shield money; commutation of service for a sum of money. See Escuage.",
  "knifeboard - A board on which knives are cleaned or polished.",
  "macho - The striped mullet of California (Mugil cephalus, or Mexicanus).",
  "confus - Confused, disturbed. [Obs.]  Chaucer.",
  "fielden - Consisting of fields. [Obs.] The fielden country also and plains. Holland.",
  "insidiate - To lie in ambush for. [Obs.] Heywood.",
  "affecter - One who affects, assumes, pretends, or strives after. \"Affecters of wit.\" Abp. Secker.",
  "ceremonially - According to rites and ceremonies; as, a person ceremonially unclean.",
  "melaconite - An earthy black oxide of copper, arising from the decomposition of other ores.",
  "crincum - A twist or bend; a turn; a whimsey. [Colloq.] Hudibras.",
  "gorcrow - The carrion crow; -- called also gercrow. [Prov. Eng.]",
  "cassioberry - The fruit of the Viburnum obovatum, a shrub which grows from Virginia to Florida.",
  "psarolite - A silicified stem of tree fern, found in abundance in the Triassic sandstone.",
  "destituent - Deficient; wanting; as, a destituent condition. [Obs.] Jer. Taylor.",
  "fatner - One who fattens. [R.] See Fattener. Arbuthnit.",
  "piliferous - 1. Bearing a single slender bristle, or hair. 2. Beset with hairs.",
  "nonylic - Of, pertaining to, or designating, nonyl or its compounds; as, nonylic acid.",
  "serotinous - Appearing or blossoming later in the season than is customary with allied species.",
  "israelite - A descendant of Israel, or Jacob; a Hebrew; a Jew.",
  "alizari - The madder of the Levant. Brande & C.",
  "nide - A nestful; a brood; as, a nide of pheasants. [Obs.]",
  "velvety - Made of velvet, or like velvet; soft; smooth; delicate.",
  "morainic - Of or pertaining to a moranie.",
  "palmin - (a) A white waxy or fatty substance obtained from castor oil. (b) Ricinolein. [Obs.]",
  "unhouse - To drive from a house or habitation; to dislodge; hence, to deprive of shelter.",
  "carbolize - To apply carbonic acid to; to wash or treat with carbolic acid.",
  "notionality - A notional or groundless opinion. [R.] Glanvill.",
  "wype - The wipe, or lapwing. [Prov. Eng.]",
  "idolatress - A female worshiper of idols.",
  "hexastichon - A poem consisting of six verses or lines.",
  "communicability - The quality of being communicable; capability of being imparted.",
  "protozooenite - One of the primary, or first-formed, segments of an embryonic arthropod.",
  "tabler - 1. One who boards. [Obs.] 2. One who boards others for hire. [Obs.] B. Jonson.",
  "mediacy - The state or quality of being mediate. Sir W. Hamilton.",
  "melanterite - A hydrous sulphate of iron of a green color and vitreous luster; iron vitriol.",
  "sequential - Succeeding or following in order. -- Se*quen\"tial*ly, adv.",
  "preoblongata - The anterior part of the medulla oblongata. B. G. Wilder.",
  "incondensibility - The quality or state of being incondensable.",
  "collitigant - Disputing or wrangling. [Obs.] -- n.  One who litigates or wrangles. [Obs.]",
  "sinusoidal - Of or pertaining to a sinusoid; like a sinusoid.",
  "ironmaster - A manufacturer of iron, or large dealer therein. Bp. Hurd.",
  "sontag - A knitted worsted jacket, worn over the waist of a woman's dress.",
  "metely - According to measure or proportion; proportionable; proportionate. [Obs.]",
  "actinomere - One of the radial segments composing the body of one of the Coelenterata.",
  "borate - A salt formed by the combination of boric acid with a base or positive radical.",
  "casuistic - Of or pertaining to casuists or casuistry.",
  "coinstantaneous - Happening at the same instant. C. Darwin.",
  "anisostemonous - Having unequal stamens; having stamens different in number from the petals.",
  "injuriousness - The quality of being injurious or hurtful; harmfulness; injury.",
  "cynoidea - A division of Carnivora, including the dogs, wolves, and foxes.",
  "planary - Of or pertaining to a plane. [R.]",
  "heathery - Heathy; abounding in heather; of the nature of heath.",
  "advenient - Coming from outward causes; superadded. [Obs.]",
  "demicannon - A kind of ordnance, carrying a ball weighing from thirty to thirty-six pounds. Shak.",
  "mower - One who, or that which, mows; a mowing machine; as, a lawn mower.",
  "sheriffwick - The office or jurisdiction of sheriff. See Shrievalty.",
  "paramalic - Pertaining to, or designating, an organic acid metameric with malic acid.",
  "tobacconing - Smoking tobacco. [Obs.] \"Tobacconing is but a smoky play.\" [Obs.] Sylvester.",
  "putid - Rotten; fetid; stinking; base; worthless. Jer. Taylor. \"Thy putid muse.\" Dr. H. More.",
  "suffragette - A woman who advocates the right to vote for women; a woman suffragist.",
  "avoyer - A chief magistrate of a free imperial city or canton of Switzerland. [Obs.]",
  "coppled - Rising to a point; conical; copped. [Obs.] Woodward.",
  "legatee - One to whom a legacy is bequeathed.",
  "carpologist - One who describes fruits; one versed in carpology.",
  "reengage - To engage a second time or again.",
  "superpolitic - More than politic; above or exceeding policy. Milton.",
  "tipsify - To make tipsy. [Colloq.] Thackeray.",
  "aptly - In an apt or suitable manner; fitly; properly; pertinently; appropriately; readily.",
  "cabalize - To use cabalistic language. [R] Dr. H. More.",
  "vanadate - A salt of vanadic acid. [Formerly also vanadiate.]",
  "pinniform - Shaped like a fin or feather. Sir J. Hill.",
  "lentigo - A freckly eruption on the skin; freckles.",
  "sorriness - The quality or state of being sorry.",
  "myriarch - A captain or commander of ten thousand men.",
  "twank - To cause to make a sharp twanging sound; to twang, or twangle. Addison.",
  "dolioform - Barrel-shaped, or like a cask in form.",
  "deodorize - To deprive of odor, especially of such as results from impurities.",
  "scandia - A chemical earth, the oxide of scandium.",
  "flimflam - A freak; a trick; a lie. Beau. & Fl.",
  "malacostomous - Having soft jaws without teeth, as certain fishes.",
  "parchmentize - To convert to a parchmentlike substance, esp. by sulphuric acid.",
  "confessedly - By confession; without denial. [Written also confessly.]",
  "hives - (a) The croup. (b) An eruptive disease (Varicella globularis), allied to the chicken pox.",
  "wormed - Penetrated by worms; injured by worms; worm-eaten; as, wormed timber.",
  "ectocuniform - One of the bones of the tarsus. See Cuneiform.",
  "digynian - Of or pertaining to the Digynia; having two styles.",
  "disgage - To free from a gage or pledge; to disengage. [Obs.] Holland.",
  "urith - The bindings of a hedge. [Obs. or Prov. Eng.] Halliwell.",
  "astone - To stun; to astonish; to stupefy. [Obs.] Chaucer.",
  "inconfusion - Freedom from confusion; distinctness. [Obs.] Bacon.",
  "perivitelline - Situated around the vitellus, or between the vitellus and zona pellucida of an ovum.",
  "scission - The act of dividing with an instrument having a sharp edge. Wiseman.",
  "tracheotomy - The operation of making an opening into the windpipe.",
  "broadpiece - An old English gold coin, broader than a guinea, as a Carolus or Jacobus.",
  "deviceful - Full of devices; inventive. [R.] A carpet, rich, and of deviceful thread. Chapman.",
  "importuous - Without a port or harbor. [R.]",
  "indigogen - 1. (Chem.)  See Indigo white, under Indigo. 2. (Physiol. Chem.)  Same as Indican, 2.",
  "pendence - Slope; inclination. [Obs.] Sir H. Wotton.",
  "dry-stone - Constructed of uncemented stone. \"Dry-stone walls.\" Sir W. Scott.",
  "suppositor - An apparatus for the introduction of suppositories into the rectum.",
  "colorature - Vocal music colored, as it were, by florid ornaments, runs, or rapid passages.",
  "panton - A horseshoe to correct a narrow, hoofbound heel.",
  "pythonic - Prophetic; oracular; pretending to foretell events.",
  "amplificatory - Serving to amplify or enlarge; amplificative. Morell.",
  "supinator - A muscle which produces the motion of supination.",
  "swoln - Contraction of Swollen, p. p. Milton.",
  "translative - tropical; figurative; as, a translative sense. [R.] Puttenham.",
  "backbiting - Secret slander; detraction. Backbiting, and bearing of false witness. Piers Plowman.",
  "designative - Serving to designate or indicate; pointing out.",
  "zonaria - A division of Mammalia in which the placenta is zonelike.",
  "schistous - Of or pertaining to schist; having the structure of a schist.",
  "divineness - The quality of being divine; superhuman or supreme excellence. Shak.",
  "ctenocyst - An organ of the Ctenophora, supposed to be sensory.",
  "overwrestle - To subdue by wrestling. [Obs.] Spenser.",
  "disordinately - Inordinately. [Obs.] E. Hall.",
  "endamagement - Damage; injury; harm. [Obs.] Shak.",
  "ghostless - Without life or spirit. [R.]",
  "biliousness - The state of being bilious.",
  "scratchbrush - A stiff wire brush for cleaning iron castings and other metal.",
  "irrecognizable - Not recognizable. Carlyle.",
  "suffumigation - The operation of suffumigating.",
  "ayegreen - The houseleek (Sempervivum tectorum). Halliwell.",
  "supersalt - An acid salt. See Acid salt (a), under Salt, n.",
  "unoperative - Producing no effect; inoperative. [Obs.] South.",
  "unequalness - The quality or state of being unequal; inequality; unevenness. Jer. Taylor.",
  "kerchered - Covered, or bound round, with a kercher. [Obs.] G. Fletcher.",
  "gumboil - A small suppurting inflamed spot on the gum.",
  "roostcock - The male of the domestic fowl; a cock. [Prov. Eng.] Halliwell.",
  "exopodite - The external branch of the appendages of Crustacea.",
  "marlaceous - Resembling marl; partaking of the qualities of marl.",
  "culler - One who piks or chooses; esp., an inspector who select wares suitable for market.",
  "disseminated - Occurring in small portions scattered through some other substance.",
  "disblame - To clear from blame. [Obs.] Chaucer.",
  "unpleat - To remove the plaits of; to smooth. W. Browne.",
  "irresuscitable - Incapable of being resuscitated or revived. -- Ir`re*sus\"ci*ta*bly, adv.",
  "relievement - The act of relieving, or the state of being relieved; relief; release. [Archaic.]",
  "remoulade - An ointment used in farriery.",
  "obese - Excessively corpulent; fat; fleshy.",
  "prenatal - Being or happening before birth.",
  "foolfish - (a) The orange filefish. See Filefish. (b) The winter flounder. See Flounder.",
  "gingerly - Cautiously; timidly; fastidiously; daintily. What is't that you took up so gingerly Shak.",
  "refutatory - Tending tu refute; refuting.",
  "self-denial - The denial of one's self; forbearing to gratify one's own desires; self-sacrifice.",
  "nondevelopment - Failure or lack of development.",
  "chitinization - The process of becoming chitinous.",
  "windowed - Having windows or openings. [R.] \"Looped and windowed raggedness.\" Shak.",
  "appointer - One who appoints, or executes a power of appointment. Kent.",
  "unmanhood - Absence or lack of manhood. [Obs.] Chaucer.",
  "whimsicalness - The quality or state of being whimsical; freakishness; whimsical disposition.",
  "baggala - A two-masted Arab or Indian trading vessel, used in Indian Ocean.",
  "claudent - Shutting; confining; drawing together; as, a claudent muscle. [R.] Jonson",
  "rivered - Supplied with rivers; as, a well rivered country.",
  "quadrinominal - Quadrinomial. Sir W. R. Hamilton.",
  "intertubular - Between tubes or tubules; as, intertubular cells; intertubular substance.",
  "wondered - Having performed wonders; able to perform wonderful things. [Obs.] Shak.",
  "mesymnicum - A repetition at the end of a stanza.",
  "confrication - A rubbing together; friction. [Obs.] Bacon.",
  "hydrargochloride - A compound of the bichloride of mercury with another chloride. [Obs.]",
  "walleteer - One who carries a wallet; a foot traveler; a tramping beggar. [Colloq.] Wright.",
  "cabesse - The finest kind of silk received from India.",
  "indignance - Indignation. [Obs.] Spenser.",
  "ingluvies - The crop, or craw, of birds.",
  "foiningly - With a push or thrust. [Obs.]",
  "solecist - One who commits a solecism. Blackwall.",
  "illegitimatize - To render illegitimate; to bastardize.",
  "ardurous - Burning; ardent. [R.] Lo! further on, Where flames the arduous Spirit of Isidore. Cary.",
  "stanchness - The quality or state of being stanch.",
  "liman - The deposit of slime at the mouth of a river; slime.",
  "goggled - Prominent; staring, as the eye.",
  "drail - To trail; to draggle. [Obs.] South.",
  "neuropathic - Of or pertaining to neuropathy; of the nature of, or suffering from, nervous disease.",
  "twinlike - Closely resembling; being a counterpart. -- Twin\"like`ness, n.",
  "melee - A fight in which the combatants are mingled",
  "stackyard - A yard or inclosure for stacks of hay or grain. A. Smith.",
  "acromion - The outer extremity of the shoulder blade.",
  "polythalamia - A division of Foraminifera including those having a manychambered shell.",
  "mansionry - The state of dwelling or residing; occupancy as a dwelling place. [Obs.] Shak.",
  "revalescent - Growing well; recovering strength.",
  "microscopist - One skilled in, or given to, microscopy.",
  "pegador - A species of remora (Echeneis naucrates). See Remora.",
  "aquiparous - Secreting water; -- applied to certain glands. Dunglison.",
  "polychoerany - A government by many chiefs, princes, or rules. [Obs.] Cudworth.",
  "rubiginous - Having the appearance or color of iron rust; rusty-looking.",
  "lithogenous - Stone-producing; -- said of polyps which form coral.",
  "ballistics - The science or art of hurling missile weapons by the use of an engine. Whewell.",
  "indispensableness - The state or quality of being indispensable, or absolutely necessary. S. Clarke.",
  "adreamed - Visited by a dream; -- used in the phrase, To be adreamed, to dream. [Obs.]",
  "threpsology - The doctrine of nutrition; a treatise on nutrition.",
  "rulingly - In a ruling manner; so as to rule.",
  "ferula - 1. A ferule. [Obs.] Beau. & Fl. 2. The imperial scepter in the Byzantine or Eastern Empire.",
  "onto - On the top of; upon; on. See On to, under On, prep.",
  "superintendency - The act of superintending; superintendence. Boyle.",
  "archaistic - Like, or imitative of, anything archaic; pertaining to an archaism.",
  "supernacular - Like supernaculum; first-rate; as, a supernacular wine. [R.] Thackeray.",
  "revellent - Causing revulsion; revulsive. -- n. (Med.)  A revulsive medicine.",
  "filiety - The relation of a son to a father; sonship; -- the correlative of paternity. J. S. Mill.",
  "ponibility - The capability of being placed or located. [Obs.] Barrow.",
  "annexationist - One who favors annexation.",
  "bryological - Relating to bryology; as, bryological studies.",
  "renerve - To nerve again; to give new vigor to; to reinvigorate.",
  "tiddle - To use with tenderness; to fondle. [Obs. or Prov. Eng.]",
  "indescribable - Incapable of being described. -- In`de*scrib\"a*bly, adv.",
  "farmery - The buildings and yards necessary for the business of a farm; a homestead. [Eng.]",
  "hander - One who hands over or transmits; a conveyer in succession. Dryden.",
  "neife - A woman born in the state of villeinage; a female serf. Blackstone.",
  "connotatively - In a connotative manner; expressing connotation.",
  "obtruncation - The act of lopping or cutting off. [R.] Cockeram.",
  "dapatical - Sumptuous in cheer. [Obs.] Bailey.",
  "defendress - A female defender. [R.] Defendress of the faith. Stow.",
  "distemperate - 1. Immoderate. [Obs.] Sir W. Raleigh. 2. Diseased; disordered. [Obs.] Wodroephe.",
  "deambulation - A walking abroad; a promenading. [Obs.] Sir T. Elyot.",
  "richness - The quality or state of being rich (in any sense of the adjective).",
  "jugata - The figures of two heads on a medal or coin, either side by side or joined.",
  "doctorly - Like a doctor or learned man. [Obs.] \"Doctorly prelates.\" Foxe.",
  "innodate - To bind up,as in a knot; to include. [Obs.] Fuller.",
  "unblushing - Not blushing; shameless. -- Un*blush\"ing*ly, adv.",
  "copeck - A Russian copper coin. See Kopeck.",
  "circumscriptive - Circumscribing or tending to circumscribe; marcing the limits or form of.",
  "courteousness - The quality of being courteous; politeness; courtesy.",
  "porcate - Having grooves or furrows broader than the intervening ridges; furrowed.",
  "abrenounce - To renounce. [Obs.] \"They abrenounce and cast them off.\" Latimer.",
  "overpamper - To pamper excessively; to feed or dress too much. Dryton.",
  "dispassioned - Free from passion; dispassionate. [R.] \"Dispassioned men.\" Donne.",
  "strategist - One skilled in strategy, or the science of directing great military movements.",
  "curtsy - Same as Courtesy, an act of respect.",
  "implicity - Implicitness. [Obs.] Cotgrave.",
  "limosis - A ravenous appetite caused by disease; excessive and morbid hunger.",
  "methodios - The art and principles of method.",
  "stocah - A menial attendant. [Obs.] Spenser.",
  "slatternly - Resembling a slattern; sluttish; negligent; dirty. -- adv.  In a slatternly manner.",
  "nonplane - Not lying in one plane; -- said of certain curves.",
  "kiddyish - Frolicsome; sportive. [Slang]",
  "anthropomancy - Divination by the entrails of human being.",
  "orchestrion - A large music box imitating a variety of orchestral instruments.",
  "scritch - A screech. [R.] Perhaps it is the owlet's scritch. Coleridge.",
  "interceder - One who intercedes; an intercessor; a mediator. Johnson.",
  "erythrochroic - Having, or subject to, erythrochroism.",
  "baffler - One who, or that which, baffles.",
  "viscoidal - Somewhat viscous. Cf. Mobile, a., 2.",
  "gern - To grin or yawn. [Obs.] \"[/He] gaped like a gulf when he did gern.\" Spenser.",
  "fetal - Pertaining to, or connected with, a fetus; as, fetal circulation; fetal membranes.",
  "holder-forth - One who speaks in public; an haranguer; a preacher. Addison.",
  "mastology - The natural history of Mammalia.",
  "rankness - The condition or quality of being rank.",
  "tetterous - Having the character of, or pertaining to, tetter.",
  "bouk - 1. The body. [Obs.] Chaucer. 2. Bulk; volume. [Scot.]",
  "pink-sterned - Having a very narrow stern; -- said of a vessel.",
  "chaffern - A vessel for heating water. [Obs.] Johnson.",
  "accessariness - The state of being accessary.",
  "pory - Porous; as, pory stone. [R.] Dryden.",
  "supersaliency - The act of leaping on anything. [Obs.] Sir T. Browne.",
  "vernant - Flourishing, as in spring; vernal. [Obs.] \"Vernant flowers.\" Milton.",
  "customariness - Quality of being customary.",
  "haemomanometer - Same as Hemadynamometer.",
  "second-sighted - Having the power of second-sight. Addison.",
  "armpit - The hollow beneath the junction of the arm and shoulder; the axilla.",
  "whoremonger - A whoremaster; a lecher; a man who frequents the society of whores.",
  "euisopoda - A group which includes the typical Isopoda.",
  "assuredness - The state of being assured; certainty; full confidence.",
  "friskal - A leap or caper. [Obs.] B. Jonson.",
  "wottest - 2d pers. sing. pres. of Wit, to know. [Obs.]",
  "trutination - The act of weighing. [Obs.] Sir T. Browne.",
  "mismanagement - Wrong or bad management; as, he failed through mismagement.",
  "inebrious - Intoxicated, or partially so; intoxicating. [R.] T. Brown.",
  "dry-boned - Having dry bones, or bones without flesh.",
  "tyrannous - Tyrannical; arbitrary; unjustly severe; despotic. Sir P. Sidney. -- Tyr\"an*nous*ly, adv.",
  "tocher - Dowry brought by a bride to her husband. [Scot.] Burns.",
  "bobbish - Hearty; in good spirits. [Low, Eng.] Dickens.",
  "ascitical - Of, pertaining to, or affected by, ascites; dropsical.",
  "sleepily - In a sleepy manner; drowsily.",
  "grotesqueness - Quality of being grotesque.",
  "thomaism - The doctrine of Thomas Aquinas, esp. with respect to predestination and grace.",
  "intentionally - In an intentional manner; with intention; by design; of purpose.",
  "nival - Abounding with snow; snowy. [Obs.] Johnson.",
  "valinch - A tube for drawing liquors from a cask by the bunghole. [Written also velinche.]",
  "pured - Purified; refined. [Obs.] \"Bread of pured wheat.\" \"Pured gold.\" Chaucer.",
  "oxygenation - The act or process of combining or of treating with oxygen; oxidation.",
  "ornithon - An aviary; a poultry house. Weale.",
  "throw-off - A start in a hunt or a race. [Eng.]",
  "forlornly - In a forlorn manner. Pollok.",
  "barmote - A court held in Derbyshire, in England, for deciding controversies between miners. Blount.",
  "gentle-hearted - Having a kind or gentle disposition. Shak. -- Gen\"tle-heart`ed*ness, n.",
  "whoremasterly - Having the character of a whoremaster; lecherous; libidinous.",
  "caligation - Dimness; cloudiness. [R.] Sir T. Browne.",
  "blea - The part of a tree which lies immediately under the bark; the alburnum or sapwood.",
  "stercorianism - The doctrine or belief of the Stercoranists.",
  "outwing - To surpass, exceed, or outstrip in flying. Garth.",
  "privateersman - An officer or seaman of a privateer.",
  "choreic - Of the nature of, or pertaining to, chorea; convulsive.",
  "embryonate - In the state of, or having, an embryonal.",
  "rosselly - Loose; light. [Obs.] Mortimer.",
  "concessionnaire - The beneficiary of a concession or grant.",
  "acidic - Containing a high percentage of silica; -- opposed to basic. an acidic solution.",
  "eviternal - Eternal; everlasting. [Obs.] -- Ev`i*ter\"nal*ly, adv. Bp. Hall.",
  "leavings - 1. Things left; remnants; relics. 2. Refuse; offal.",
  "besieging - That besieges; laying siege to. -- Be*sie\"ging*ly, adv.",
  "riffraff - Sweepings; refuse; the lowest order of society. Beau & Fl.",
  "submetallic - Imperfectly metallic; as, a submetallic luster.",
  "nascal - A kind of pessary of medicated wool or cotton, formerly used.",
  "nitter - The horselouse; an insect that deposits nits on horses.",
  "philosophaster - A pretender to philosophy. [Obs.] Dr. H. More.",
  "overnumerous - Excessively numerous; too many.",
  "metallographic - Pertaining to, or by means of, metallography.",
  "knitter - One who, or that which, knits, joins, or unites; a knitting machine. Shak.",
  "protege - One under the care and protection of another.",
  "staving - A cassing or lining of staves; especially, one encircling a water wheel.",
  "approvable - Worthy of being approved; meritorious. -- Ap*prov\"a*ble*ness, n.",
  "water rate - A rate or tax for a supply of water.",
  "detersion - The act of deterging or cleansing, as a sore.",
  "exhaustible - Capable of being exhausted, drained off, or expended. Johnson.",
  "recurviroster - A bird whose beak bends upward, as the avocet.",
  "regentship - The office of a regent; regency.",
  "covert baron - Under the protection of a husband; married. Burrill.",
  "precessional - Of or pertaining to pression; as, the precessional movement of the equinoxes.",
  "tituled - Having a title. [Obs.] Fuller.",
  "supersaturation - The operation of supersaturating, or the state of being supersaturated.",
  "assurgency - Act of rising. The . . . assurgency of the spirit through the body. Coleridge.",
  "inequitate - To ride over or through. [Obs.] Dr. H. More.",
  "etymological - Pertaining to etymology, or the derivation of words. -- Et`y*mo*log\"ic*al*ly, adv.",
  "gnatworm - The aquatic larva of a gnat; -- called also, colloquially, wiggler.",
  "toothlet - A little tooth, or like projection.",
  "engulfment - A swallowing up as if in a gulf. [R.]",
  "perpetrable - Capable of being perpetrated. R. North.",
  "circumventor - One who circumvents; one who gains his purpose by cunning.",
  "indocibility - The state of being indocible; indocibleness; indocility.",
  "ambitiousness - The quality of being ambitious; ambition; pretentiousness.",
  "pruriginous - Tending to, or caused by, prurigo; affected by, or of the nature of, prurigo.",
  "forty-spot - The Tasmanian forty-spotted diamond bird (Pardalotus quadragintus).",
  "bicallous - Having two callosities or hard spots. Gray.",
  "nupson - A simpleton; a fool. [Obs.] B. Jonson.",
  "filamentous - Like a thread; consisting of threads or filaments. Gray.",
  "advancer - 1. One who advances; a promoter. 2. A second branch of a buck's antler. Howell.",
  "water pheasant - (a) The pintail. See Pintail, n., 1. (b) The goosander. (c) The hooded merganser.",
  "proratable - Capable of being prorated, or divided proportionately. [U.S.]",
  "extraarticular - Situated outside of a joint.",
  "mammiferous - Having breasts; of, pertaining to, or derived from, the Mammalia.",
  "surcle - A little shoot; a twig; a sucker. [Obs.] Sir T. Browne.",
  "cumulostratus - A form of cloud. See Cloud.",
  "iguanian - Resembling, or pertaining to, the iguana.",
  "ypres lace - Fine bobbin lace made at Ypres in Belgium, usually exactly like Valenciennes lace.",
  "existimation - Esteem; opinion; reputation. [Obs.] Steele.",
  "quidam - Somebody; one unknown. Spenser.",
  "groveling - Lying prone; low; debased. [Written also grovelling.] \"A groveling creature.\" Cowper.",
  "makeless - 1. Matchless. [Obs.] Chaucer. 2. Without a mate. Shak.",
  "bronchitic - Of or pertaining to bronchitis; as, bronchitic inflammation.",
  "civicism - The principle of civil government.",
  "deanship - The office of a dean. I dont't value your deanship a straw. Swift.",
  "gently - In a gentle manner. My mistress gently chides the fault I made. Dryden.",
  "echoer - One who, or that which, echoes.",
  "swimmingness - Act or state of swimming; suffusion. \"A swimmingness in the eye.\" Congreve.",
  "unconsonant - Incongruous; inconsistent. \"A thing unconsonant.' Hooker.",
  "excrementitial - Pertaining to, or consisting of, excrement; of the nature of excrement.",
  "arenicolite - An ancient wormhole in sand, preserved in the rocks. Dana.",
  "epithelial - Of or pertaining to epithelium; as, epithelial cells; epithelial cancer.",
  "nephalist - One who advocates or practices nephalism.",
  "concupiscibleness - The state of being concupiscible. [Obs.]",
  "tubulibranchiata - A group of gastropod mollusks having a tubular shell. Vermetus is an example.",
  "cleavable - Capable of cleaving or being divided.",
  "disappendent - Freed from a former connection or dependence; disconnected. [R.]",
  "masser - A priest who celebrates Mass. [R.] Bale.",
  "brunette - A girl or woman with a somewhat brown or dark complexion. -- a.  Having a dark tint.",
  "medioxumous - Intermediate. [Obs.] Dr. H. More.",
  "self-communicative - Imparting or communicating by its own powers.",
  "water plate - A plate heated by hot water contained in a double bottom or jacket. Knight.",
  "cripply - Lame; disabled; in a crippled condition. [R.] Mrs. Trollope.",
  "clancularly - privately; secretly. [Obs.]",
  "conjunctional - Relating to a conjunction.",
  "furnishment - The act of furnishing, or of supplying furniture; also, furniture. [Obs.] Daniel.",
  "nipping - Biting; pinching; painful; destructive; as, a nipping frost; a nipping wind.",
  "luny - Crazy; mentally unsound. [Written also loony.] [Law, U.S.]",
  "jenneting - A variety of early apple. See Juneating. [Written also geniting.]",
  "inseparate - Not separate; together; united. Shak.",
  "footstool - A low stool to support the feet of one when sitting.",
  "defuse - To disorder; to make shapeless. [Obs.] Shak.",
  "furnisher - One who supplies or fits out.",
  "penalize - 1. To make penal. 2. (Sport.)  To put a penalty on. See Penalty, 3. [Eng.]",
  "minuteness - The quality of being minute.",
  "transcalent - Pervious to, or permitting the passage of, heat.",
  "prolatum - A prolate spheroid. See Ellipsoid of revolution, under Ellipsoid.",
  "incaverned - Inclosed or shut up as in a cavern. Drayton.",
  "morsitation - The act of biting or gnawing. [Obs.]",
  "cautel - 1. Caution; prudence; wariness. [Obs.] Fulke. 2. Craft; deceit; falseness. [Obs.] Shak.",
  "outpace - To outgo; to move faster than; to leave behind. [R.] Lamb.",
  "photochromic - Of or pertaining to photochromy; produced by photochromy.",
  "toxaemia - Blood poisoning. See under Blood.",
  "bristle-pointed - Terminating in a very fine, sharp point, as some leaves.",
  "stoutly - In a stout manner; lustily; boldly; obstinately; as, he stoutly defended himself.",
  "debellation - The act of conquering or subduing. [Obs.]",
  "dittology - A double reading, or twofold interpretation, as of a Scripture text. [R.]",
  "firmamental - Pertaining to the firmament; celestial; being of the upper regions. Dryden.",
  "metabolite - A product of metabolism; a substance produced by metabolic action, as urea.",
  "nonsexual - Having no distinction of sex; sexless; neuter.",
  "misdistinguish - To make wrong distinctions in or concerning. Hooker.",
  "prevenient - Going before; preceding; hence, preventive. \"Prevenient grace descending.\" Milton.",
  "reillumination - The act or process of enlightening again.",
  "roominess - The quality or state of being roomy; spaciousness; as, the roominess of a hall.",
  "inbreathe - To infuse by breathing; to inspire. Coleridge.",
  "unkent - Unknown; strange. [Obs. or Scot.] W. Browne.",
  "almsfolk - Persons supported by alms; almsmen. [Archaic] Holinshed.",
  "westerner - A native or inhabitant of the west.",
  "noctivagation - A roving or going about in the night. Gayton.",
  "insignment - A token, mark, or explanation. [Obs.] Sir T. Elyot.",
  "vang - A rope to steady the peak of a gaff.",
  "escritorial - Of or pertaining to an escritoire.",
  "hals - The neck or throat. [Obs.] Do me hangen by the hals. Chaucer.",
  "consulter - One who consults, or asks counsel or information.",
  "jards - A callous tumor on the leg of a horse, below the hock.",
  "cirrigrade - Moving or moved by cirri, or hairlike appendages.",
  "stufa - A jet of steam issuing from a fissure in the earth.",
  "unravelment - The act of unraveling, or the state of being unraveled.",
  "herpetological - Pertaining to herpetology.",
  "schismatize - To make part in schism; to make a breach of communion in the church.",
  "bicorned - Having two horns; two-horned; crescentlike.",
  "palmaceous - Of or pertaining to palms; of the nature of, or resembling, palms.",
  "peritoneal - Of or pertaining to the peritoneum.",
  "miscredulity - Wrong credulity or belief; misbelief. Bp. Hall.",
  "corsage - The waist or bodice of a lady's dress; as. a low corsage.",
  "halloysite - A claylike mineral, occurring in soft, smooth, amorphous masses, of a whitish color.",
  "platonist - One who adheres to the philosophy of Plato; a follower of Plato. Hammond.",
  "unrevenued - Not furnished with a revenue. [R.] Milton.",
  "forestal - Of or pertaining to forests; as, forestal rights.",
  "costate - Having ribs, or the appearance of ribs; (Bot.) having one or more longitudinal ribs.",
  "aesthesis - Sensuous perception. [R.] Ruskin.",
  "supplely - In a supple manner; softly; pliantly; mildly. Cotgrave.",
  "unpinion - To loose from pinions or manacles; to free from restraint. Goldsmith.",
  "arhizal - See Arrhizal, Arrhizous, Arrhythmic, Arrhythmous.",
  "snively - Running at the nose; sniveling pitiful; whining.",
  "pedantocracy - The sway of pedants. [R.] J. S. Mill.",
  "mahumetan - See Mohammedan, Mohammedanism.",
  "authorial - Of or pertaining to an author. \"The authorial Hare.",
  "tranquilization - The act of tranquilizing, or the state of being tranquilized.",
  "claymore - A large two-handed sword used formerly by the Scottish Highlanders.",
  "incomplex - Not complex; uncompounded; simple. Barrow.",
  "broad-brimmed - Having a broad brim. A broad-brimmed flat silver plate. Tatler.",
  "tron - See 3d Trone, 2. [Obs. or Scott.]",
  "copped - Rising to a point or head; conical; pointed; crested. Wiseman.",
  "brontometer - An instrument for noting or recording phenomena attendant on thunderstorms.",
  "glassware - Ware, or articles collectively, made of glass.",
  "antlered - Furnished with antlers. The antlered stag. Cowper.",
  "formidability - Formidableness. Walpole.",
  "episodial - Pertaining to an episode; by way of episode; episodic.",
  "steller - The rytina; -- called also stellerine.",
  "enhydrous - Having water within; containing fluid drops; -- said of certain crystals.",
  "guardianless - Without a guardian. Marston.",
  "insouciant - Careless; heedless; indifferent; unconcerned. J. S. Mill.",
  "pistoleer - One who uses a pistol. [R.] Carlyle.",
  "unplight - To unfold; to lay open; to explain. [Obs.] Chaucer.",
  "bedwarf - To make a dwarf of; to stunt or hinder the growth of; to dwarf. Donne.",
  "yesterweek - The week last past; last week.",
  "furtherer - One who furthers. or helps to advance; a promoter. Shak.",
  "afflux - A flowing towards; that which flows to; as, an afflux of blood to the head.",
  "postcornu - The posterior horn of each lateral ventricle of the brain. B. G. Wilder.",
  "monarcho - The nickname of a crackbrained Italian who fancied himself an emperor. [Obs.] Shak.",
  "branchiferous - Having gills; branchiate; as, branchiferous gastropods.",
  "struthio - A genus of birds including the African ostriches.",
  "derm - 1. The integument of animal; the skin. 2. (Anat.)  See Dermis.",
  "electro-gilding - The art or process of gilding copper, iron, etc., by means of voltaic electricity.",
  "unscrupulous - Not scrupulous; unprincipled. -- Un*scru\"pu*lous*ly, adv. -- Un*scru\"pu*lous*ness, n.",
  "categorematic - Capable of being employed by itself as a term; -- said of a word.",
  "autotheist - One given to self-worship. [R.]",
  "clearage - The act of reforming anything; clearance. [R.]",
  "chalchihuitl - The Mexican name for turquoise. See Turquoise.",
  "nauscopy - The power or act of discovering ships or land at considerable distances.",
  "hallucinate - To wander; to go astray; to err; to blunder; -- used of mental processes. [R.] Byron.",
  "barruly - Traversed by barrulets or small bars; -- said of the field.",
  "pantologist - One versed in pantology; a writer of pantology.",
  "anglicity - The state or quality of being English.",
  "enthuse - To make or become enthusiastic. [Slang]",
  "deesis - An invocation of, or address to, the Supreme Being.",
  "reciprok - Reciprocal. [Obs.] B. Jonson.",
  "patroness - A female patron or helper. Spenser. Night, best patroness of grief. Milton.",
  "recto-uterine - Of or pertaining to both the rectum and the uterus.",
  "statued - Adorned with statues. \"The statued hall.\" Longfellow. \"Statued niches.\" G. Eliot.",
  "gnomically - In a gnomic, didactic, or sententious manner.",
  "slaughterous - Destructive; murderous. Shak. M. Arnold. -- Slaugh\"ter*ous*ly, adv.",
  "disinteressment - Disinterestedness; impartiality; fairness. [Obs.] Prior.",
  "votarist - A votary. Like a sad votarist in palmer's weed. Milton.",
  "viduation - The state of being widowed or bereaved; loss; bereavement. [R.]",
  "miny - Abounding with mines; like a mine. \"Miny caverns.\" Thomson.",
  "pentylic - Pertaining to, derived from, or containing, pentyl; as, pentylic alcohol",
  "boggy - Consisting of, or containing, a bog or bogs; of the nature of a bog; swampy; as, boggy land.",
  "protectionist - One who favors protection. See Protection, 4.",
  "overmultiply - To multiply or increase too much; to repeat too often.",
  "fistulose - Formed like a fistula; hollow; reedlike. Craig.",
  "prepossessor - One who possesses, or occupies, previously. R. Brady.",
  "outbabble - To utter foolishly or excessively; to surpass in babbling. [R.] Milton.",
  "anallantoic - Without, or not developing, an allantois.",
  "innovationist - One who favors innovation.",
  "ambiguously - In an ambiguous manner; with doubtful meaning.",
  "ventiduct - A passage for wind or air; a passage or pipe for ventilating apartments. Gwilt.",
  "epidermoid - Like epidermis; pertaining to the epidermis.",
  "milord - Lit., my lord; hence (as used on the Continent), an English nobleman or gentleman.",
  "ellingeness - See Elenge, Elengeness. [Obs.]",
  "cookmaid - A female servant or maid who dresses provisions and assists the cook.",
  "galloping - Going at a gallop; progressing rapidly; as, a galloping horse.",
  "inexactly - In a manner not exact or precise; inaccurately. R. A. Proctor.",
  "duodecuple - Consisting of twelves. Arbuthnot.",
  "bilingualism - Quality of being bilingual. The bilingualism of King's English. Earle.",
  "unwrite - To cancel, as what is written; to erase. Milton.",
  "moldwarp - See Mole the animal. Spenser.",
  "dendrology - A discourse or treatise on trees; the natural history of trees.",
  "cirrate - Having cirri along the margin of a part or organ.",
  "pricky - Stiff and sharp; prickly. Holland.",
  "princeling - A petty prince; a young prince.",
  "outluster - To excel in brightness or luster. Shak.",
  "washable - Capable of being washed without damage to fabric or color.",
  "tun-bellied - Having a large, protuberant belly, or one shaped like a tun; pot-bellied.",
  "ignominiously - In an ignominious manner; disgracefully; shamefully; ingloriously.",
  "cream-fruit - A plant of Sierra Leone which yields a wholesome, creamy juice.",
  "metallicly - In a metallic manner; by metallic means.",
  "compassing - Curved; bent; as, compassing timbers.",
  "stylohyal - A segment in the hyoidean arch between the epihyal and tympanohyal.",
  "interjectionally - In an interjectional manner. G. Eliot.",
  "immediacy - The relation of freedom from the interventionof a medium; immediateness. Shak.",
  "cryptogamous - Of or pertaining to the series Cryptogamia, or to plants of that series.",
  "subsensible - Deeper than the reach of the senses. \"That subsensible world.\" Tyndall.",
  "hypural - Under the tail; -- applied to the bones which support the caudal fin rays in most fishes.",
  "alectorides - A group of birds including the common fowl and the pheasants.",
  "chaus - a lynxlike animal of Asia and Africa (Lynx Lybicus).",
  "ctenoidean - Relating to the Ctenoidei. -- n.  One of the Ctenoidei.",
  "suffixion - The act of suffixing, or the state of being suffixed.",
  "coffeeroom - A public room where coffee and other refreshments may be obtained.",
  "parrock - A croft, or small field; a paddock. [Prov. Eng.]",
  "devilism - The state of the devil or of devils; doctrine of the devil or of devils. Bp. Hall.",
  "workable - Capable of being worked, or worth working; as, a workable mine; workable clay.",
  "blirt - A gust of wind and rain. Ham. Nav. Encyc.",
  "candent - Heated to whiteness; glowing with heat. \"A candent vessel.\" Boyle.",
  "crossjack - The lowest square sail, or the lower yard of the mizzenmast.",
  "conditory - A repository for holding things; a hinding place.",
  "dankish - Somewhat dank. -- Dank\"ish*ness, n. In a dark and dankish vault at home. Shak.",
  "slinky - Thin; lank. [Prov. Eng. & U. S.]",
  "desirousness - The state of being desirous.",
  "statarian - Fixed; settled; steady; statary. [Obs.]",
  "convexo-convex - Convex on botConvex, a.",
  "frisette - a fringe of hair or curls worn about the forehead by women.",
  "lithophosphor - A stone that becomes phosphoric by heat.",
  "subtrude - To place under; to insert. [R.]",
  "exarticulation - Luxation; the dislocation of a joint. Bailey.",
  "decrown - To deprive of a crown; to discrown. [R.] Hakewill.",
  "unforgettable - Not forgettable; enduring in memory. Pungent and unforgettable truths. Emerson.",
  "pongee - A fabric of undyed silk from India and China.",
  "comatose - Relating to, or resembling, coma; drowsy; lethargic; as, comatose sleep; comatose fever.",
  "ventriculous - Somewhat distended in the middle; ventricular.",
  "inurement - Use; practice; discipline; habit; custom.",
  "podostomata - An order of Bryozoa of which Rhabdopleura is the type. See Rhabdopleura.",
  "scotticize - To cause to become like the Scotch; to make Scottish. [R.]",
  "conjunctively - In conjunction or union; together. Sir T. Browne.",
  "infeasible - Not capable of being done or accomplished; impracticable. Glanvill.",
  "caroche - A kind of pleasure carriage; a coach. [Obs.] To mount two-wheeled caroches. Butler.",
  "crabby - Crabbed; difficult, or perplexing. \"Persius is crabby, because ancient.\" Marston.",
  "oneiroscopy - The interpretation of dreams.",
  "panicled - Furnished with panicles; arranged in, or like, panicles; paniculate.",
  "self-knowledge - Knowledge of one's self, or of one's own character, powers, limitations, etc.",
  "spectrally - In the form or manner of a specter.",
  "eugetic - Pertaining to, or derived from, eugenol; as, eugetic acid.",
  "dinosaur - One of the Dinosauria. [Written also deinosaur, and deinosaurian.]",
  "paedogenesis - Reproduction by young or larval animals.",
  "spermatoon - A spermoblast. -- Sper`ma*to\"al, a. Owen.",
  "acidimeter - An instrument for ascertaining the strength of acids. Ure.",
  "dicastery - A court of justice; judgment hall. [R.] J. S. Mill.",
  "fairhood - Fairness; beauty. [Obs.] Foxe.",
  "wadset - A kind of pledge or mortgage. [Written also wadsett.]",
  "interopercular - Of or pertaining to the interoperculum. -- n.  The interopercular bone.",
  "nosocomial - Of or pertaining to a hospital; as, nosocomial atmosphere. Dunglison.",
  "dichlamydeous - Having two coverings, a calyx and in corolla.",
  "misrepeat - To repeat wrongly; to give a wrong version of. Gov. Winthrop.",
  "respirational - Of or pertaining to respiration; as, respirational difficulties.",
  "sequestral - Of or pertaining to a sequestrum. Quian.",
  "allectation - Enticement; allurement. [Obs.] Bailey.",
  "mosque - A Mohammedan church or place of religious worship. [Written also mosk.]",
  "ounded - Wavy; waving [Obs.] \"Owndie hair.\" Chaucer.",
  "emulousness - The quality of being emulous.",
  "representatively - In a representative manner; vicariously.",
  "guerdonable - Worthy of reward. Sir G. Buck.",
  "corked - having acquired an unpleasant taste from the cork; as, a bottle of wine is corked.",
  "fielded - Engaged in the field; encamped. [Obs.] To help fielded friends. Shak.",
  "hungrily - In a hungry manner; voraciously. Dryden.",
  "colitis - An inflammation of the large intestine, esp. of its mucous membrane; colonitis.",
  "trematoid - f or pertaining to the Trematodea. See Illustration in Appendix.",
  "psychomachy - A conflict of the soul with the body.",
  "loculose - Divided by internal partitions into cells, as the pith of the pokeweed.",
  "cramoisy - Crimson. [Obs.] A splendid seignior, magnificent in cramoisy velevet. Motley.",
  "corrugant - Having the power of contracting into wrinkles. Johnson.",
  "weatherly - Working, or able to sail, close to the wind; as, a weatherly ship. Cooper.",
  "tatt - To make (anything) by tatting; to work at tatting; as, tatted edging.",
  "norroy - The most northern of the English Kings-at-arms. See King-at- arms, under King.",
  "starchedness - The quality or state of being starched; stiffness in manners; formality.",
  "oozy - Miry; containing soft mud; resembling ooze; as, the oozy bed of a river. Pope.",
  "correctify - To correct. [Obs.] When your worship's plassed to correctify a lady. Beau & Fl.",
  "bockelet - A kind of long-winged hawk; -- called also bockerel, and bockeret. [Obs.]",
  "alchemize - To change by alchemy; to transmute. Lovelace.",
  "altarist - (a) A chaplain. (b) A vicar of a church.",
  "abortionist - One who procures abortion or miscarriage.",
  "statured - Arrived at full stature. [R.]",
  "polygony - Any plant of the genus Polygonum.",
  "peabird - The wryneck; -- so called from its note. [Prov. Eng.]",
  "entomoid - Resembling an insect. -- n.  An object resembling an insect.",
  "dermatography - An anatomical description of, or treatise on, the skin.",
  "hexdecyl - The essential radical, C16H33, of hecdecane.",
  "reannex - To annex again or anew; to reunite. \"To reannex that duchy.\" Bacon.",
  "hogo - High flavor; strong scent. [Obs.] Halliwell.",
  "basidiospore - A spore borne by a basidium. -- Ba*sid`i*o*spor\"ous (, a.",
  "neckcloth - A piece of any fabric worn around the neck.",
  "hawked - Curved like a hawk's bill; crooked.",
  "aldermanlike - Like or suited to an alderman.",
  "diffame - Evil name; bad reputation; defamation. [Obs.] Chaucer.",
  "hypospadias - A deformity of the penis, in which the urethra opens upon its under surface.",
  "carnalize - To make carnal; to debase to carnality. A sensual and carnalized spirit. John Scott.",
  "concubinacy - The practice of concubinage. [Obs.] Strype.",
  "impatronize - To make lord or master; as, to impatronize one's self of a seigniory. [R.] Bacon.",
  "veritas - The Bureau Veritas. See under Bureau.",
  "distermination - Separation by bounds. [Obs.] Hammond.",
  "charqui - Jerked beef; beef cut into long strips and dried in the wind and sun. Darwin.",
  "cereous - Waxen; like wax. [Obs.] Gayton.",
  "hamesecken - The felonious seeking and invasion of a person in his dwelling house. Bouvier.",
  "beeswax - The wax secreted by bees, and of which their cells are constructed.",
  "festivous - Pertaining to a feast; festive. [R.] Sir W. Scott.",
  "hypochondriacal - Same as Hypochondriac, 2. -- Hy`po*chon\"dri*a*cal*ly, adv.",
  "lambaste - To beat severely. [Low] Nares.",
  "administrant - Executive; acting; managing affairs. -- n.  One who administers.",
  "shattery - Easily breaking into pieces; not compact; loose of texture; brittle; as, shattery spar.",
  "wise-hearted - Wise; knowing; skillful; sapient; erudite; prudent. Ex. xxviii. 3.",
  "kerf - A notch, channel, or slit made in any material by cutting or sawing.",
  "tympanitis - Inflammation of the lining membrane of the middle ear.",
  "tead - A torch. [Obs.] \"A burning teade.\" Spenser.",
  "phlebolite - A small calcareous concretion formed in a vein; a vein stone.",
  "gasiform - Having a form of gas; gaseous.",
  "fughetta - a short, condensed fugue. Grove.",
  "persiennes - Window blinds having movable slats, similar to Venetian blinds.",
  "lace-winged - Having thin, transparent, reticulated wings; as, the lace- winged flies.",
  "cornigerous - Horned; having horns; as, cornigerous animals. [Obs.] Sir T. Browne.",
  "underprize - To undervalue; to underestimate. Shak.",
  "acetaldehyde - Acetic aldehyde. See Aldehyde.",
  "shamanic - Of or pertaining to Shamanism.",
  "decatoic - Pertaining to, or derived from, decane.",
  "maleyl - A hypothetical radical derived from maleic acid.",
  "metavanadic - Of, pertaining to, or designating, a vanadic acid analogous to metaphosphoric acid.",
  "inoxidizable - Incapable of being oxidized; as, gold and platinum are inoxidizable in the air.",
  "deputable - Fit to be deputed; suitable to act as a deputy. Carlyle.",
  "croquante - A brittle cake or other crisp pastry.",
  "similitudinary - Involving or expressing similitude. [Obs.] Coke.",
  "solidly - In a solid manner; densely; compactly; firmly; truly.",
  "exceptor - One who takes exceptions. T. Burnet.",
  "inimicality - The state or quality of being inimical or hostile; hostility; unfriendliness. [R.]",
  "waldgrave - In the old German empire, the head forest keeper.",
  "prescriptible - Depending on, or derived from, prescription; proper to be prescribed. Grafton.",
  "salvific - Tending to save or secure safety. [Obs.]",
  "wayfarer - One who travels; a traveler; a passenger.",
  "implicitness - State or quality of being implicit.",
  "rufous - Reddish; of a yellowish red or brownish red color; tawny.",
  "politically - 1. In a political manner. 2. Politicly; artfully. [Obs.] Knolles.",
  "concealable - Capable of being concealed.",
  "moanful - Full of moaning; expressing sorrow. -- Moan\"ful*ly, adv.",
  "resolvedness - Fixedness of purpose; firmness; resolution. Dr. H. More.",
  "entocuniform - One of the bones of the tarsus. See Cuneiform.",
  "ywar - Aware; wary. [Obs.] \"Be ywar, and his way shun.\" Piers Plowman.",
  "subinduce - To insinuate; to offer indirectly. [Obs.] Sir E. Dering.",
  "phytolithologist - One versed in phytolithology; a paleobotanist.",
  "maistry - Mastery; superiority; art. See Mastery. [Obs.] Chaucer.",
  "coachdog - One of a breed of dogs trained to accompany carriages; the Dalmatian dog.",
  "bewailing - Wailing over; lamenting. -- Be*wail\"ing*ly, adv.",
  "parergy - Something unimportant, incidental, or superfluous. [Obs.] Sir T. Browne.",
  "hot-brained - Ardent in temper; violent; rash; impetuous; as, hot-brained youth. Dryden.",
  "underpeep - To peep under. \"The flame . . . would underpeep her lids.\" [R.] Shak.",
  "propagative - Producing by propagation, or by a process of growth.",
  "interlining - Correction or alteration by writing between the lines; interlineation. Bp. Burnet.",
  "rangle - To range about in an irregular manner. [Obs. or Prov. Eng.] Halliwell.",
  "legibility - The quality of being legible; legibleness. Sir. D. Brewster.",
  "gambist - A performer upon the viola di gamba. See under Viola.",
  "uchees - A tribe of North American Indians belonging to the Creek confederation.",
  "match-coat - A coat made of match-cloth.",
  "anarchist - An anarch; one who advocates anarchy of aims at the overthrow of civil government.",
  "devotionalist - One given to devotion, esp. to excessive formal devotion.",
  "syllabicate - To form or divide into syllables; to syllabify.",
  "mormondom - The country inhabited by the Mormons; the Mormon people.",
  "elasmobranchiate - Of or pertaining to Elasmobranchii. -- n.  One of the Elasmobranchii.",
  "latently - In a secret or concealed manner; invisibly.",
  "subagitation - Unlawful sexual intercourse. [Obs.]",
  "interplay - Mutual action or influence; interaction; as, the interplay of affection.",
  "basipodite - The basal joint of the legs of Crustacea.",
  "magnifiable - Such as can be magnified, or extolled.",
  "amphilogism - Ambiguity of speech; equivocation. [R.]",
  "dolomize - To convert into dolomite. -- Dol`o*mi*za\"tion, n.",
  "tumored - Distended; swelled. [R.] \"His tumored breast.\" R. Junius.",
  "acrisia - 1. Inability to judge. 2. (Med.)  Undecided character of a disease. [Obs.]",
  "biodynamical - Of or pertaining to biodynamics, or the doctrine of vital forces or energy.",
  "water plant - A plant that grows in water; an aquatic plant.",
  "sanguigenous - Producing blood; as, sanguigenous food.",
  "cursorily - In a running or hasty manner; carelessly.",
  "arbalister - A crossbowman. [Obs.] Speed.",
  "creant - Creative; formative. [R.] Mrs. Browning.",
  "usself - Ourselves. [Obs.] Wyclif. Piers Plowman. Chaucer.",
  "cassinette - A cloth with a cotton wart, and a woof of very fine wool, or wool and silk.",
  "orbulina - A genus of minute living Foraminifera having a globular shell.",
  "zarthe - A European bream (Abramis vimba). [Written also zaerthe.]",
  "leafage - Leaves, collectively; foliage.",
  "abbreviatory - Serving or tending to abbreviate; shortening; abridging.",
  "rethor - A rhetorician; a careful writer. [Obs.] If a rethor couthe fair endite. Chaucer.",
  "redisburse - To disburse anew; to give, or pay, back. Spenser.",
  "umbratious - Suspicious; captious; disposed to take umbrage. [Obs. & R.] Sir H. Wotton.",
  "incense-breathing - Breathing or exhaling incense. \"Incense-breathing morn.\" Gray.",
  "localize - To make local; to fix in, or assign to, a definite place. H. Spencer. Wordsworth.",
  "myrtiform - Resembling myrtle or myrtle berries; having the form of a myrtle leaf.",
  "acidific - Producing acidity; converting into an acid. Dana.",
  "monocle - An eyeglass for one eye. Simmonds.",
  "friendlily - In a friendly manner. Pope.",
  "parcase - Perchance; by chance. [Obs.] Chaucer.",
  "accelerando - Gradually accelerating the movement.",
  "petitor - One who seeks or asks; a seeker; an applicant. [R.] Fuller.",
  "cheiropterygium - The typical pentadactyloid limb of the higher vertebrates.",
  "ichthyotomy - The anatomy or dissection of fishes. [R.]",
  "coenoecium - The common tissue which unites the various zooids of a bryozoan.",
  "cofferer - One who keeps treasures in a coffer. [R.]",
  "havened - Sheltered in a haven. Blissful havened both from joy and pain. Keats.",
  "poecilopod - One of the Poecilopoda. Also used adjectively.",
  "macroural - Same as Macrura, Macrural, etc.",
  "inaniloquent - Given to talking inanely; loquacious; garrulous. [R.]",
  "steedless - Having no steed; without a horse.",
  "tightener - That which tightens; specifically (Mach.), a tightening pulley.",
  "perfecter - One who, or that which, makes perfect. \"The . . . perfecter of our faith.\" Barrow.",
  "caducean - Of or belonging to Mercury's caduceus, or wand.",
  "disincarcerate - To liberate from prison. [R.] Harvey.",
  "pedantize - To play the pedant; to use pedantic expressions. [R.]",
  "astragalomancy - Divination by means of small bones or dice.",
  "clayes - Wattles, or hurdles, made with stakes interwoven with osiers, to cover lodgments. [Obs.]",
  "geophagist - One who eats earth, as dirt, clay, chalk, etc.",
  "resistive - Serving to resist. B. Jonsosn.",
  "worshipability - The quality of being worthy to be worshiped. [R.] Coleridge.",
  "punicial - Of a bright red or purple color. [R.]",
  "sustentacular - Supporting; sustaining; as, a sustentacular tissue.",
  "percurrent - Running through the entire length.",
  "pauciloquent - Uttering few words; brief in speech. [R.]",
  "hydride - A compound of the binary type, in which hydrogen is united with some other element.",
  "depredable - Liable to depredation. [Obs.] \"Made less depredable.\" Bacon.",
  "faultful - Full of faults or sins. Shak.",
  "devilwood - A kind of tree (Osmanthus Americanus), allied to the European olive.",
  "verein - A union, association, or society; -- used in names of German organizations.",
  "shepherdly - Resembling, or becoming to, a shepherd; pastoral; rustic. [R.] Jer. Taylor.",
  "exolution - See Exsolution. [Obs.] Sir T. Browne.",
  "thundrous - Thunderous; sonorous. \"Scraps of thunderous epic.\" Tennyson.",
  "coursed - 1. Hunted; as, a coursed hare. 2. Arranged in courses; as, coursed masonry.",
  "displicency - Dislike; dissatisfaction; discontent. [Obs.] W. Montagu.",
  "articulus - A joint of the cirri of the Crinoidea; a joint or segment of an arthropod appendage.",
  "winninish - The land-locked variety of the common salmon. [Canada]",
  "crenulation - 1. A minute crenation. 2. The state of being minutely scalloped.",
  "underhangman - An assistant or deputy hangman. Shak.",
  "insatiateness - The state of being insatiate.",
  "rurality - 1. The quality or state of being rural. 2. A rural place. \"Leafy ruralities.\" Carlyle.",
  "telephotographic - Designating, or pertaining to, the process of telephotography.",
  "haunter - One who, or that which, haunts.",
  "poltroonish - Resembling a poltroon; cowardly.",
  "balkingly - In manner to balk or frustrate.",
  "iatromathematical - Of or pertaining to iatromathematicians or their doctrine.",
  "aline - To range or place in a line; to bring into line; to align. Evelyn.",
  "fairyland - The imaginary land or abode of fairies.",
  "hyporhachis - The stem of an aftershaft or hypoptilum. [Written also hyporachis.]",
  "hurry-skurry - Confusedly; in a bustle. [Obs.] Gray.",
  "erythronium - A name originally given (from its red acid) to the metal vanadium. [R.]",
  "lazyback - A support for the back, attached to the seat of a carriage. [Colloq.]",
  "restaurateur - The keeper of an eathing house or a restaurant.",
  "burg - 1. A fortified town. [Obs.] 2. A borough. [Eng.] See 1st Borough.",
  "tetraptote - A noun that has four cases only. Andrews.",
  "vestibular - Of or pertaining to a vestibule; like a vestibule.",
  "botuliform - Having the shape of a sausage. Henslow.",
  "spooler - One who, or that which, spools.",
  "toff - A fop; a beau; a swell. [Slang, Eng.]  Kipling.",
  "amazedness - The state of being amazed, or confounded with fear, surprise, or wonder. Bp. Hall.",
  "crotalum - A kind of castanet used by the Corybantes.",
  "incivilization - The state of being uncivilized; want of civilization; barbarism.",
  "powderflask - A flask in which gunpowder is carried, having a charging tube at the end.",
  "synpelmous - Having the two main flexor tendons of the toes blended together.",
  "wonderstruck - Struck with wonder, admiration, or surprise. Dryden.",
  "public-minded - Public-spirited. -- Pub\"lic-mind`ed*ness, n.",
  "subhyoidean - Situated or performed beneath the hyoid bone; as, subhyoidean laryngotomy.",
  "midweek - The middle of the week. Also used adjectively.",
  "cymar - A sight covering; a scarf. See Simar. Her body shaded with a light cymar. Dryden.",
  "liquescency - The quality or state of being liquescent. Johnson.",
  "logos - 1. A word; reason; speech. H. Bushell. 2. The divine Word; Christ.",
  "aphrodisian - Pertaining to Aphrodite or Venus. \"Aphrodisian dames\" [that is, courtesans]. C. Reade.",
  "subdolous - Sly; crafty; cunning; artful. [R.]",
  "tolerant - Inclined to tolerate; favoring toleration; forbearing; ingulgent.",
  "maintop - The platform about the head of the mainmast in square-rigged vessels.",
  "incapsulate - To inclose completely, as in a membrane.",
  "witing - Knowledge. [Obs.] \"Withouten witing of any other wight.\" Chaucer.",
  "cephalosome - The anterior region or head of insects and other arthropods. Packard.",
  "anthypochondriac - See Antihypochondriac.",
  "xylotomist - One versed or engaged in xylotomy.",
  "metallograph - A print made by metallography.",
  "paraguay tea - See Mate, the leaf of the Brazilian holly.",
  "smuggler - 1. One who smuggles. 2. A vessel employed in smuggling.",
  "terete - Cylindrical and slightly tapering; columnar, as some stems of plants.",
  "osmidrosis - The secretion of fetid sweat.",
  "quizzism - The act or habit of quizzing.",
  "outfitter - One who furnishes outfits for a voyage, a journey, or a business.",
  "mischief-maker - One who makes mischief; one who excites or instigates quarrels or enmity.",
  "tryster - One who makes an appointment, or tryst; one who meets with another.",
  "supercilium - The eyebrow, or the region of the eyebrows.",
  "triangled - Having three angles; triangular.",
  "blore - The act of blowing; a roaring wind; a blast. [Obs.] A most tempestuous blore. Chapman.",
  "bilboquet - The toy called cup and ball.",
  "unknight - To deprive of knighthood. Fuller.",
  "goodlyhood - Goodness; grace; goodliness. [Obs.] Spenser.",
  "spit-venom - Poison spittle; poison ejected from the mouth. [R.] Hooker.",
  "paleographic - Of or pertaining to paleography.",
  "dijudicate - To make a judicial decision; to decide; to determine. [R.] Hales.",
  "revealability - The quality or state of being revealable; revealableness.",
  "crustation - An adherent crust; an incrustation. Pepys.",
  "ruination - The act of ruining, or the state of being ruined.",
  "risen - 1. p. p. & a. from Rise. \"Her risen Son and Lord.\" Keble. 2. Obs. imp. pl. of Rise. Chaucer.",
  "merlon - One of the solid parts of a battlemented parapet; a battlement. See Illust. of Battlement.",
  "bank-sided - Having sides inclining inwards, as a ship; -- opposed to wall- sided.",
  "puncticular - Comprised in, or like, a point; exact. [Obs. & R.] Sir T. Browne.",
  "despeed - To send hastily. [Obs.] Despeeded certain of their crew. Speed.",
  "weeder - One who, or that which, weeds, or frees from anything noxious.",
  "moonglade - The bright reflection of the moon's light on an expanse of water. [Poetic]",
  "grasper - One who grasps or seizes; one who catches or holds.",
  "presentiality - State of being actually present. [Obs.] South.",
  "valetudinous - Valetudinarian. [Obs.] \"The valetudinous condition of King Edward.\" Fuller.",
  "primigenous - First formed or generated; original; primigenial. Bp. Hall.",
  "manteau - 1. A woman's cloak or mantle. 2. A gown worn by women. [Obs.]",
  "ettle - To earn. [Obs.] See Addle, to earn. Boucher.",
  "innixion - Act of leaning upon something; incumbency. [Obs.] Derham.",
  "superjacent - Situated immediately above; as, superjacent rocks.",
  "achlamydate - Not possessing a mantle; -- said of certain gastropods.",
  "serrifera - A division of Hymenoptera comprising the sawflies.",
  "verine - An alkaloid obtained as a yellow amorphous substance by the decomposition of veratrine.",
  "cops - The connecting crook of a harrow. [Prov. Eng.]",
  "abolitionism - The principles or measures of abolitionists. Wilberforce.",
  "intime - Inward; internal; intimate. [Obs.] Sir K. Digby.",
  "plagiocephaly - Oblique lateral deformity of the skull.",
  "astylar - Without columns or pilasters. Weale.",
  "cyamelide - A white amorphous substance, regarded as a polymeric modification of isocyanic acid.",
  "herr - A title of respect given to gentlemen in Germany, equivalent to the English Mister.",
  "gigue - A piece of lively dance music, in two strains which are repeated; also, the dance.",
  "infraposition - A situation or position beneath. Kane.",
  "splenoid - Resembling the spleen; spleenlike.",
  "siesta - A short sleep taken about the middle of the day, or after dinner; a midday nap.",
  "desistive - Final; conclusive; ending. [R.]",
  "conjurement - Serious injunction; solemn demand or entreaty. [Obs.] Milton.",
  "vaulty - Arched; concave. [Obs.] \"The vaulty heaven.\" Shak.",
  "subsphenoidal - Situated under, or on the ventral side of, the body of the sphenoid bone.",
  "malapropism - A grotesque misuse of a word; a word so used.",
  "stillhouse - A house in which distillation is carried on; a distillery.",
  "yellow book - In France, an official government publication bound in yellow covers.",
  "theosophize - To practice theosophy. [R.]",
  "conclavist - One of the two ecclesiastics allowed to attend a cardinal in the conclave.",
  "fluviometer - An instrument for measuring the height of water in a river; a river gauge.",
  "examinership - The office or rank of an examiner.",
  "cast-iron - Made of cast iron. Hence, Fig.: like cast iron; hardy; unyielding.",
  "huer - One who cries out or gives an alarm; specifically, a balker; a conder. See Balker.",
  "disinvestiture - The act of depriving of investiture. [Obs.] Ogilvie.",
  "mediaevals - The people who lived in the Middle Ages. Ruskin.",
  "disprivilege - To deprive of a privilege or privileges. [R.]",
  "unfertile - Not fertile; infertile; barren. -- Un*fer\"tile*ness, n.",
  "northeaster - A storm, strong wind, or gale, coming from the northeast.",
  "swampy - Consisting of swamp; like a swamp; low, wet, and spongy; as, swampy land.",
  "seniority - The quality or state of being senior.",
  "topet - The European crested titmouse. [Prov. Eng.]",
  "invigoration - The act of invigorating, or the state of being invigorated.",
  "usitative - Denoting usual or customary action. \"The usitative aorist.\" Alford.",
  "teaze-hole - The opening in the furnaces through which fuel is introduced.",
  "shittim wood - The wood of the shittah tree.",
  "phyllodineous - Having phyllodia; relating to phyllodia.",
  "clansman - One belonging to the same clan with another.",
  "abovesaid - Mentioned or recited before.",
  "mechanicalize - To cause to become mechanical.",
  "terpsichore - The Muse who presided over the choral song and the dance, especially the latter.",
  "machining - Of or pertaining to the machinery of a poem; acting or used as a machine.[Obs.] Dryden.",
  "genuflect - To bend the knee, as in worship.",
  "inspirationist - One who holds to inspiration.",
  "gleg - Quick of perception; alert; sharp. [Scot.] Jamieson.",
  "imperfectness - The state of being imperfect.",
  "symmetrize - To make proportional in its parts; to reduce to symmetry. Burke.",
  "widower - A man who has lost his wife by death, and has not married again. Shak.",
  "elinguate - To deprive of the tongue. [Obs.] Davies (Holy Roode).",
  "turtling - The act, practice, or art of catching turtles. Marryat.",
  "gyp - A college servant; -- so called in Cambridge, England; at Oxford called a scout. [Cant]",
  "fotive - Nourishing. [Obs.] T. Carew (1633).",
  "theriacal - Of or pertaining to theriac; medicinal. \"Theriacal herbs.\" Bacon.",
  "roller bearing - A bearing containing friction rollers.",
  "advantageously - Profitably; with advantage.",
  "photo-electrical - Pert. to, or capable of developing, photo-electricity.",
  "foreship - The fore part of a ship. [Obs.]",
  "slipstring - One who has shaken off restraint; a prodigal. [Obs.] Cotgrave.",
  "helena - See St. Elmo's fire, under Saint.",
  "overmast - To furnish (a vessel) with too long or too heavy a mast or masts.",
  "miserableness - The state or quality of being miserable.",
  "mountlet - A small or low mountain. [R.]",
  "thaumaturgist - One who deals in wonders, or believes in them; a wonder worker. Carlyle.",
  "lantern-jawed - Having lantern jaws or long, thin jaws; as, a lantern-jawed person.",
  "stagehouse - A house where a stage regularly stops for passengers or a relay of horses.",
  "contradictoriness - The quality of being contradictory; opposition; inconsistency. J. Whitaker.",
  "racemed - Arranged in a raceme, or in racemes.",
  "matriarchate - The office or jurisdiction of a matriarch; a matriarchal form of government.",
  "farstretched - Stretched beyond ordinary limits.",
  "oundy - Wavy; waving [Obs.] \"Owndie hair.\" Chaucer.",
  "contradicter - one who contradicts. Swift.",
  "arbitrariness - The quality of being arbitrary; despoticalness; tyranny. Bp. Hall.",
  "iconize - To form an image or likeness of. [R.] Cudworth.",
  "bel-accoyle - A kind or favorable reception or salutation. [Obs.]",
  "presbyterate - A presbytery; also, presbytership. Heber.",
  "discloak - To take off a cloak from; to uncloak. [Obs.] B. Jonson.",
  "quinquevalvular - Having five valves, as a pericarp.",
  "masorite - One of the writers of the Masora.",
  "-ably - A suffix composed of -able and the adverbial suffix -ly; as, favorably.",
  "pard - A leopard; a panther. And more pinch-spotted make them Than pard or cat o'mountain. Shak.",
  "reverentially - In a reverential manner.",
  "marcian - Under the influence of Mars; courageous; bold. [Obs.] Chaucer.",
  "soler - A loft or garret. See Solar, n. Sir W. Scott.",
  "fantast - One whose manners or ideas are fantastic. [R.] Coleridge.",
  "psilanthropist - One who believes that Christ was a mere man. Smart.",
  "velivolant - Flying with sails; passing under full sail. [R.]",
  "parietine - A piece of a fallen wall; a ruin. [Obs.] Burton.",
  "pronely - In a prone manner or position.",
  "antinomist - An Antinomian. [R.] Bp. Sanderson.",
  "inequity - Want of equity; injustice; wrong. \"Some form of inequity.\" H. Spencer.",
  "demency - Dementia; loss of mental powers. See Insanity.",
  "transporting - That transports; fig., ravishing. Your transporting chords ring out. Keble.",
  "winkle-hawk - A rectangular rent made in cloth; -- called also winkle-hole. [Local, U. S.] Bartlett.",
  "arest - A support for the spear when couched for the attack. [Obs.] Chaucer.",
  "progressist - One who makes, or holds to, progress; a progressionist.",
  "presignify - To intimate or signify beforehand; to presage.",
  "haematothermal - Warm-blooded; homoiothermal.",
  "inflex - To bend; to cause to become curved; to make crooked; to deflect. J. Philips.",
  "vidual - Of or pertaining to the state of a widow; widowed. [R.] Jer. Taylor.",
  "nominalism - The principles or philosophy of the Nominalists.",
  "evolation - A flying out or up. [Obs.] Bp. Hall.",
  "sea gull - Any gull living on the seacoast.",
  "ambassadorial - Of or pertaining to an ambassador. H. Walpole.",
  "amatorial - Of or pertaining to a lover or to love making; amatory; as, amatorial verses.",
  "hardwareman - One who makes, or deals in, hardware.",
  "diarchy - A form of government in which the supreme power is vested in two persons.",
  "sadiron - An iron for smoothing clothes; a flatiron.",
  "prosaicism - The quality or state of being prosaic; a prosaic manner or style. [R.] Poe.",
  "low-churchmanship - The state of being a low-churchman.",
  "aphyllous - Destitute of leaves, as the broom rape, certain euphorbiaceous plants, etc.",
  "tithly - Tightly; nimbly. [Obs.] \"I have seen him trip it tithly.\" Beau. & Fl.",
  "southmost - Farthest toward the south; southernmost. [R.] Milton.",
  "hollowness - 1. State of being hollow. Bacon. 2. Insincerity; unsoundness; treachery. South.",
  "opinable - Capable of being opined or thought. Holland.",
  "animative - Having the power of giving life or spirit. Johnson.",
  "auriphrygiate - Embroidered or decorated with gold. [R.] Southey.",
  "photolithographic - Of or pertaining to photolithography; produced by photolithography.",
  "pecora - An extensive division of ruminants, including the antelopes, deer, and cattle.",
  "manuducent - One who leads by the hand; a manuductor. [Obs.]",
  "trachelorrhaphy - The operation of sewing up a laceration of the neck of the uterus.",
  "analogicalness - Quality of being analogical.",
  "latirostres - The broad-billed singing birds, such as the swallows, and their allies."
]