export default [
  "palmatilobed - Palmate, with the divisions separated less than halfway to the common center.",
  "roomthy - Roomy; spacious. [Obs.] Fuller.",
  "hawkbit - The fall dandelion (Leontodon autumnale).",
  "gumma - A kind of soft tumor, usually of syphilitic origin.",
  "deceptiveness - The power or habit of deceiving; tendency or aptness to deceive.",
  "mishmash - A hotchpotch. Sir T. Herbert.",
  "prejudicative - Forming a judgment without due examination; prejudging. Dr. H. More.",
  "pantographic - Of or pertaining to a pantograph; relating to pantography.",
  "pyloric - Of, pertaining to, or in the region of, the pylorus; as, the pyloric end of the stomach.",
  "condescendingly - In a condescending manner. Atterbury.",
  "ambuscadoed - Posted in ambush; ambuscaded. [Obs.]",
  "avel - To pull away. [Obs.] Yet are not these parts avelled. Sir T. Browne.",
  "psychiatric - Of or pertaining to psychiatria.",
  "phantasmatical - Phantasmal. Dr. H. More.",
  "extersion - The act of wiping or rubbing out. [Obs.]",
  "tetrastich - A stanza, epigram, or poem, consisting of four verses or lines. Pope.",
  "rejectment - Act of rejecting; matter rejected, or thrown away. Eaton.",
  "smokable - Capable of being smoked; suitable or ready to be smoked; as, smokable tobacco.",
  "diffuser - One who, or that which, diffuses.",
  "pediatric - Pertaining to the care and medical treatment of children. [Webster 1913 Suppl.]",
  "sarcoptes - A genus of parasitic mites including the itch mites.",
  "acoumetry - The measuring of the power or extent of hearing.",
  "algoid - Of the nature of, or resembling, an alga.",
  "attenuated - 1. Made thin or slender. 2. Made thin or less viscid; rarefied. Bacon.",
  "postponence - The act of postponing, in sense 2. [Obs.] Johnson.",
  "adelantado - A governor of a province; a commander. Prescott.",
  "unbowed - Not bent or arched; not bowed down. Byron.",
  "bin- - A euphonic form of the prefix Bi-.",
  "photoscope - Anything employed for the observation of light or luminous effects.",
  "unmoneyed - Destitute of money; not rich. [Written also unmonied.] Shenstone.",
  "soleship - The state of being sole, or alone; soleness. [R.] Sir E. Dering.",
  "baalite - A worshiper of Baal; a devotee of any false religion; an idolater.",
  "affluxion - The act of flowing towards; afflux. Sir T. Browne.",
  "inbreak - A breaking in; inroad; invasion.",
  "atwain - In twain; asunder. [Obs. or Poetic] \"Cuts atwain the knots.\" Tennyson.",
  "maghet - A name for daisies and camomiles of several kinds.",
  "palenque - A collective name for the Indians of Nicaragua and Honduras.",
  "plano-horizontal - Having a level horizontal surface or position. Lee.",
  "catchweight - Without any additional weight; without being handicapped; as, to ride catchweight.",
  "puniness - The quality or state of being puny; littleness; pettiness; feebleness.",
  "sarcophile - A flesh-eating animal, especially any one of the carnivorous marsupials.",
  "piscina - A niche near the altar in a church, containing a small basin for rinsing altar vessels.",
  "pelvimetry - The measurement of the pelvis.",
  "theologaster - A pretender or quack in theology. [R.] Burton.",
  "ulotrichan - Of or pertaining to the Ulotrichi. -- n.  One of the Ulotrichi.",
  "milkman - A man who sells milk or delivers is to customers.",
  "cajolement - The act of cajoling; the state of being cajoled; cajolery. Coleridge.",
  "domage - 1. Damage; hurt. [Obs.] Chapman. 2. Subjugation. [Obs.] Hobbes.",
  "boyishness - The manners or behavior of a boy.",
  "excortication - The act of stripping off bark, or the state of being thus stripped; decortication.",
  "bacchical - Of or relating to Bacchus; hence, jovial, or riotous,with intoxication.",
  "rascallion - A low, mean wretch [Written also rascalion.]",
  "tortuose - Wreathed; twisted; winding. Loudon",
  "jin - See Jinnee. \"Solomon is said to have had power over the jin.\" Balfour (Cyc. of India).",
  "occasive - Of or pertaining to the setting sun; falling; descending; western.",
  "vituline - Of or pertaining to a calf or veal.",
  "inductional - Pertaining to, or proceeding by, induction; inductive.",
  "cerebriform - Like the brain in form or substance.",
  "hanap - A rich goblet, esp. one used on state occasions. [Obs.]",
  "by-turning - An obscure road; a way turning from the main road. Sir P. Sidney.",
  "vertu - 1. Virtue; power. See Virtue. [Obs.] Chaucer. 2. See Virtu.",
  "adumbrant - Giving a faint shadow, or slight resemblance; shadowing forth.",
  "blunger - A wooden blade with a cross handle, used for mi Tomlinson.",
  "salimetry - The art or process of measuring the amount of salt in a substance.",
  "intraventricular - Within or between ventricles.",
  "by-pass - A by-passage, for a pipe, or other channel, to divert circulation from the usual course.",
  "anatomist - One who is skilled in the art of anatomy, or dissection.",
  "distrustless - Free from distrust. Shenstone.",
  "sentine - A place for dregs and dirt; a sink; a sewer. [Obs.] Latimer.",
  "revocate - To recall; to call back. [Obs.]",
  "nineholes - A game in which nine holes are made in the ground, into which a ball is bowled.",
  "peterman - A fisherman; -- so called after the apostle Peter. [An obs. local term in Eng.] Chapman.",
  "oto- - A combining form denoting relation to, or situation near or in, the ear.",
  "unweld - Unwieldy; unmanageable; clumsy. [Obs.] Our old limbs move [may] well be unweld. Chaucer.",
  "unwashen - Not washed. [Archaic] \"To eat with unwashen hands.\" Matt. xv. 20.",
  "laryngotome - An instrument for performing laryngotomy.",
  "attinge - To touch lightly. [Obs.] Coles.",
  "mesa - A high tableland; a plateau on a hill. [Southwestern U.S.] Bartlett.",
  "stomatode - Having a mouth; -- applied to certain Protozoa. -- n.  One of the Stomatoda.",
  "self-glorious - Springing from vainglory or vanity; vain; boastful. Dryden.",
  "parturitive - Pertaining to parturition; obstetric. [R.]",
  "subministrant - Subordinate; subservient. [Obs.] Bacon.",
  "preteritness - The quality or state of being past. Bentley. Lowell.",
  "haruspicy - The art or practices of haruspices. See Aruspicy.",
  "producent - One who produces, or offers to notice. [Obs.] Ayliffe.",
  "reiglement - Rule; regulation. [Obs.] Bacon. Jer. Taylor.",
  "equivocatory - Indicating, or characterized by, equivocation.",
  "dephase - To put out of phase, as two parts of a single alternating current.",
  "credibly - In a manner inducing belief; as, I have been credibly informed of the event.",
  "donna - A lady; madam; mistress; -- the title given a lady in Italy.",
  "distractful - Distracting. [R.] Heywood.",
  "revaccinate - To vaccinate a second time or again. -- Re*vac`ci*na\"tion(#), n.",
  "destructibleness - The quality of being destructible.",
  "wheyey - Of the nature of, or containing, whey; resembling whey; wheyish. Bacon.",
  "binal - Twofold; double. [R.] \"Binal revenge, all this.\" Ford.",
  "weazeny - Somewhat weazen; shriveled. [Colloq.] \"Weazeny, baked pears.\" Lowell.",
  "meliorism - The doctrine that there is a tendency throughout nature toward improvement. J. Sully.",
  "nucleiform - Formed like a nucleus or kernel.",
  "pursership - The office of purser. Totten.",
  "amphopeptone - A product of gastric digestion, a mixture of hemipeptone and antipeptone.",
  "parforn - To perform. [Obs.] Chaucer. Piers Plowman.",
  "employe - One employed by another; a clerk or workman in the service of an employer.",
  "dentigerous - Bearing teeth or toothlike structures.",
  "intermontane - Between mountains; as, intermontane soil.",
  "noncomplying - Neglecting or refusing to comply.",
  "otoconite - (a) A mass of otoliths. (b) An otolith.",
  "phosphoryl - The radical PO, regarded as the typical nucleus of certain compounds.",
  "fermentability - Capability of fermentation.",
  "multanimous - Many-minded; many-sided. The multanimous nature of the poet. J. R. Lowell.",
  "inacquiescent - Not acquiescent or acquiescing.",
  "perichordal - Around the notochord; as, a perichordal column. See Epichordal.",
  "excambie - To exchange; -- used with reference to transfers of land.",
  "immixed - Unmixed. [Obs.] How pure and immixed the design is. Boyle.",
  "cross-stone - See Harmotome, and Staurotide.",
  "insense - To make to understand; to instruct. [Prov. Eng.] Halliwell.",
  "abler - comp. of Able. -- A\"blest, a.,  superl. of Able.",
  "sicer - A strong drink; cider. [Obs.] Chaucer.",
  "mettled - Having mettle; high-spirited; ardent; full of fire. Addison.",
  "diadrom - A complete course or vibration; time of vibration, as of a pendulum. [Obs.] Locke.",
  "schoolmistress - A woman who governs and teaches a school; a female school- teacher.",
  "unking - To cause to cease to be a king. [R.] Shall his condescension, therefore, unking him South.",
  "red-tape - Pertaining to, or characterized by, official formality. See Red tape, under Red, a.",
  "parker - , The keeper of a park. Sir M. Hale.",
  "imposableness - Quality of being imposable.",
  "derdoing - Doing daring or chivalrous deeds. [Obs.] \"In derdoing arms.\" Spenser.",
  "arduousness - The quality of being arduous; difficulty of execution.",
  "headache - Pain in the head; ceph \"Headaches and shivering fits.\" Macaulay.",
  "slug-horn - An erroneous form of the Scotch word slughorne, or sloggorne, meaning slogan.",
  "prosencephalic - Of or pertaining to the prosencephalon.",
  "redingote - A long plain double-breasted outside coat for women.",
  "untighten - To make less tight or tense; to loosen.",
  "completely - In a complete manner; fully.",
  "petrine - Of or pertaining to St.Peter; as, the Petrine Epistles.",
  "siemens-martin steel - See Open-hearth steel, under Open.",
  "psalterial - Of or pertaining to the psalterium.",
  "ptolemaist - One who accepts the astronomical system of Ptolemy.",
  "blendous - Pertaining to, consisting of, or containing, blende.",
  "fustilug - A gross, fat, unwieldy person. [Obs.] F. Junius.",
  "radiolarian - Of or pertaining to the Radiolaria. -- n.  One of the Radiolaria.",
  "penality - The quality or state of being penal; lability to punishment. Sir T. Browne.",
  "ignify - To form into fire. [R.] Stukeley.",
  "drabble-tail - A draggle-tail; a slattern. Halliwell.",
  "ricebird - (a) The Java sparrow. (b) The bobolink.",
  "grecism - An idiom of the Greek language; a Hellenism. Addison.",
  "invigilancy - Want of vigilance; neglect of watching; carelessness.",
  "helotism - The condition of the Helots or slaves in Sparta; slavery.",
  "illatively - By inference; as an illative; in an illative manner.",
  "nigged - Hammer-dressed; -- said of building stone.",
  "mucigen - A substance which is formed in mucous epithelial cells, and gives rise to mucin.",
  "ovarious - Consisting of eggs; as, ovarious food. [R.] Thomson.",
  "eupatrid - One well born, or of noble birth.",
  "diaphaneity - The quality of being diaphanous; transparency; pellucidness.",
  "rest-harrow - A European leguminous plant (Ononis arvensis) with long, tough roots.",
  "ovoidal - Resembling an egg in shape; egg-shaped; ovate; as, an ovoidal apple.",
  "apetalousness - The state of being apetalous.",
  "kemp - Coarse, rough hair wool or fur, injuring its quality.",
  "ingustable - Tasteless; insipid. Sir T. Browne.",
  "besogne - A worthless fellow; a bezonian. [Obs.]",
  "encash - To turn into cash; to cash. Sat. Rev.",
  "heteroclitical - Deviating from ordinary forms or rules; irregular; anomalous; abnormal.",
  "acrotomous - Having a cleavage parallel with the base.",
  "semitransparency - Imperfect or partial transparency.",
  "bafflement - The process or act of baffling, or of being baffled; frustration; check.",
  "bow-saw - A saw with a thin or narrow blade set in a strong frame.",
  "run-around - A whitlow running around the finger nail, but not affecting the bone. [Colloq.]",
  "forwander - To wander away; to go astray; to wander far and to weariness. [Obs.]",
  "acetabular - Cup-shaped; saucer-shaped; acetabuliform.",
  "intervenient - Being or coming between; intercedent; interposed. [Obs.] Bacon.",
  "abbacy - The dignity, estate, or jurisdiction of an abbot.",
  "posthume - Posthumos. [Obs.] I. Watts. Fuller.",
  "souvenance - Remembrance. [Obs.] Of his way he had no sovenance. Spenser.",
  "intramarginal - Situated within the margin. Loudon.",
  "quakingly - In a quaking manner; fearfully. Sir P. Sidney.",
  "pentremites - A genus of crinoids belonging to the Blastoidea. They have five petal-like ambulacra.",
  "paver - One who paves; one who lays a pavement. [Written also pavier and pavior.]",
  "renardine - Of or pertaining to Renard, the fox, or the tales in which Renard is mentioned.",
  "collenchyma - A tissue of vegetable cells which are thickend at the angles and (usually) elongated.",
  "erodent - A medicine which eats away extraneous growths; a caustic.",
  "immoderateness - The quality of being immoderate; excess; extravagance. Puller.",
  "impoisoner - A poisoner. [Obs.] Beau. & Fi.",
  "pundle - A short and fat woman; a squab. [Obs.]",
  "isodimorphous - Having the quality of isodimorphism.",
  "hogger-pump - The for pump in the pit. Raymond.",
  "obstupefaction - See Stupefaction. [Obs.] Howell.",
  "impropriator - One who impropriates; specifically, a layman in possession of church property.",
  "matajuelo blanco - A West Indian food fish (Malacanthus plumieri) related to the tilefish.",
  "self-luminous - Possessing in itself the property of emitting light. Sir D. Brewster.",
  "preadmonition - Previous warning or admonition; forewarning.",
  "buttermilk - The milk that remains after the butter is separated from the cream.",
  "pontificial - Papal; pontifical. [Obs.] \"Pontificial writers.\" Burton.",
  "troyounce - See Troy ounce, under Troy weight, above, and under Ounce.",
  "padnag - An ambling nag. \"An easy padnag.\" Macaulay.",
  "polypiferous - Bearing polyps, or polypites.",
  "contractive - Tending to contract; having the property or power or power of contracting.",
  "inopercular - Having no operculum; -- said of certain gastropod shells.",
  "rotor - The rotating part of a generator or motor.",
  "idealistic - Of or pertaining to idealists or their theories.",
  "bristliness - The quality or state of having bristles.",
  "greenhouse - A house in which tender plants are cultivated and sheltered from the weather.",
  "labyrinthine - Pertaining to, or like, a labyrinth; labyrinthal.",
  "direptitiously - With plundering violence; by violent injustice. [R.] Strype.",
  "ministress - A woman who ministers. Akenside.",
  "dilacerate - To rend asunder; to tear to pieces. Sir T. Browne.",
  "courtiery - The manners of a courtier; courtliness. [Obs.] B. Jonson.",
  "pinnigrade - An animal of the seal tribe, moving by short feet that serve as paddles.",
  "panderly - Having the quality of a pander. \"O, you panderly rascals.\" Shak.",
  "chlorodyne - A patent anodyne medicine, containing opium, chloroform, Indian hemp, etc.",
  "releasor - One by whom a release is given.",
  "floxed silk - See Floss silk, under Floss.",
  "teil - The lime tree, or linden; -- called also teil tree.",
  "apodictically - So as to be evident beyond contradiction.",
  "dedicatee - One to whom a thing is dedicated; -- correlative to dedicator.",
  "genteelness - The quality of being genteel.",
  "zulu-kaffir - A member of the Bantu race comprising the Zulus and the Kaffirs.",
  "rehabilitation - The act of rehabilitating, or the state of being rehabilitated. Bouvier. Walsh.",
  "considerer - One who considers; a man of reflection; a thinker. Milton.",
  "textman - One ready in quoting texts. [R.] Bp. Sanderston.",
  "barbituric acid - A white, crystalline substance,",
  "exulcerative - Tending to cause ulcers; exulceratory. Holland.",
  "consentient - Agreeing in mind; accordant. The consentient judgment of the church. Bp. Pearson.",
  "polyeidism - The quality or state of being polyeidic.",
  "semisoun - A half sound; a low tone. [Obs.] \"Soft he cougheth with a semisoun.\" Chaucer.",
  "testicond - Having the testicles naturally concealed, as in the case of the cetaceans.",
  "sublobular - Situated under, or at the bases of, the lobules of the liver.",
  "scissile - Capable of being cut smoothly; scissible. [R.] Arbuthnot.",
  "heterosporous - Producing two kinds of spores unlike each other.",
  "tubercled - Having tubercles; affected with, tubercles; tuberculate; as, a tubercled lung or stalk.",
  "parallel transformer - A transformer connected in parallel.",
  "traductive - Capable of being deduced; derivable. [R.] Bp. Warburton.",
  "imperceptive - Unable to perceive. The imperceptive part of the soul. Dr. H. More.",
  "icterical - 1. Pertaining to, or affected with, jaundice. 2. Good against the jaundice. Johnson.",
  "metensomatosis - The assimilation by one body or organism of the elements of another.",
  "austerely - Severely; rigidly; sternly. A doctrine austerely logical. Macaulay.",
  "cavetto - A concave molding; -- used chiefly in classical architecture. See Illust. of Calumn.",
  "poonac - A kind of oil cake prepared from the cocoanut. See Oil cake, under Cake.",
  "fleshling - A person devoted to fleshly things. [Obs.] Spenser.",
  "hibernicism - An idiom or mode of speech peculiar to the Irish. Todd.",
  "firstly - In the first place; before anything else; -- sometimes improperly used for first.",
  "unpeerable - Incapable of having a peer, or equal.",
  "frescade - A cool walk; shady place. [R.] Maunder.",
  "majestatic - Majestic. [Obs.] E. Pocock. Dr. J. Scott.",
  "counterirritation - See Counter irritant, etc., under Counter, a.",
  "pawky - Arch; cunning; sly. [Scot.] Jamieson.",
  "light-minded - Unsettled; unsteady; volatile; not considerate. -- Light\"-mind`ed*ness, n.",
  "angiology - That part of anatomy which treats of blood vessels and lymphatics.",
  "placoganoid - Pertaining to the Placoganoidei.",
  "ethmotrubinal - See Turbinal. -- n.  An ethmoturbinal bone.",
  "canonistic - Of or pertaining to a canonist. \"This canonistic exposition.\" Milton.",
  "amortizable - Capable of being cleared off, as a debt.",
  "bechamel - A rich, white sauce, prepared with butter and cream.",
  "latterday - Belonging to present times or those recent by comparison.",
  "cashmerette - A kind of dress goods, made with a soft and glossy surface like cashmere.",
  "sweepings - Things collected by sweeping; rubbish; as, the sweepings of a street.",
  "adulter - To commit adultery; to pollute. [Obs.] B. Jonson.",
  "tull - To allure; to tole. [Obs.] With empty hands men may no hawkes tull. Chaucer.",
  "voltairism - The theories or practice of Voltaire. J. Morley.",
  "unefectual - Ineffectual. \"His uneffectual fire.\" Shak.",
  "latterkin - A pointed wooden tool used in glazing leaden lattice.",
  "galliform - Like the Gallinae (or Galliformes) in structure.",
  "disharmonious - Unharmonious; discordant. [Obs.] Hallywell.",
  "fleamy - Bloody; clotted. [Obs. or Prov.] Foamy bubbling of a fleamy brain. Marston.",
  "dietist - One skilled in dietetics. [R.]",
  "reclinant - Bending or leaning backward.",
  "amphipodous - Of or pertaining to the Amphipoda.",
  "anhinga - An aquatic bird of the southern United States (Platus anhinga); the darter, or snakebird.",
  "cryptogram - A cipher writing. Same as Cryptograph.",
  "edgeless - Without an edge; not sharp; blunt; obtuse; as, an edgeless sword or weapon.",
  "superreflection - The reflection of a reflected image or sound. [R.] Bacon.",
  "suzerainty - The dominion or authority of a suzerain; paramount authority.",
  "heartdear - Sincerely beloved. [R.] Shak.",
  "moveless - Motionless; fixed. \"Moveless as a tower.\" Pope.",
  "aroid - Belonging to, or resembling, the Arum family of plants.",
  "phascolome - A marsupial of the genus Phascolomys; a wombat.",
  "xeme - An Arctic fork-tailed gull (Xema Sabinii).",
  "barograph - An instrument for recording automatically the variations of atmospheric pressure.",
  "stroud - A kind of coarse blanket or garment used by the North American Indians.",
  "manipulative - Of or pertaining to manipulation; performed by manipulation.",
  "malefice - An evil deed; artifice; enchantment. [Obs.]",
  "dissunder - To separate; to sunder; to destroy. [R.] Chapman.",
  "fungoid - Like a fungus; fungous; spongy.",
  "geoponic - Pertaining to tillage of the earth, or agriculture.",
  "greillade - Iron ore in coarse powder, prepared for reduction by the Catalan process.",
  "incontrollable - Not controllable; uncontrollable. -- In`con*trol\"la*bly, adv. South.",
  "elegantly - In a manner to please nice taste; with elegance; with due symmetry; richly.",
  "quickener - One who, or that which, quickens.",
  "uropodal - Of or pertaining to a uropod.",
  "estancia - A grazing; a country house. [Spanish America]",
  "tenebricose - Tenebrous; dark; gloomy. [Obs.]",
  "emeroids - Hemorrhoids; piles; tumors; boils. [R.] Deut. xxviii. 27.",
  "lineation - Delineation; a line or lines.",
  "corrupter - One who corrupts; one who vitiates or taints; as, a corrupter of morals.",
  "unshapen - Not shaped; shapeless; misshapen; deformed; ugly.",
  "dinetical - Revolving on an axis. [Obs.] Sir T. Browne.",
  "expolish - To polish thoroughly. [Obs.] Heywood.",
  "retrospection - The act, or the faculty, of looking back on things past.",
  "umbonate - Having a conical or rounded projection or protuberance, like a boss.",
  "demandant - One who demands; the plaintiff in a real action; any plaintiff.",
  "grandiloquent - Speaking in a lofty style; pompous; bombastic.",
  "cajun - In Louisiana, a person reputed to be Acadian French descent.",
  "criticiser - One who criticises; a critic.",
  "nucleole - The nucleus within a nucleus; nucleolus.",
  "ramiflorous - Flowering on the branches.",
  "pyrotritartaric - Designating an acid which is more commonly called uric acid.",
  "super - A contraction of Supernumerary, in sense 2. [Theatrical Cant]",
  "morass - A tract of soft, wet ground; a marsh; a fen. Morass ore. (Min.) See Bog ore, under Bog.",
  "perfumery - 1. Perfumes, in general. 2. Etym: [Cf. F. parfumerie.]  The art of preparing perfumes.",
  "celluliferous - Bearing or producing little cells.",
  "bucktooth - Any tooth that juts out. When he laughed, two white buckteeth protruded. Thackeray.",
  "lacertiloid - Like or belonging to the Lacertilia.",
  "jemminess - Spruceness. [Slang, Eng.] Pegge (1814).",
  "micropantograph - A kind of pantograph which produces copies microscopically minute.",
  "upmost - Highest; topmost; uppermost. Spenser. Dryden.",
  "quadrennium - A space or period of four years.",
  "ganil - A kind of brittle limestone. [Prov. Eng.] Kirwan.",
  "accidentality - The quality of being accidental; accidentalness. [R.] Coleridge.",
  "allurer - One who, or that which, allures.",
  "rectoress - 1. A governess; a rectrix. Drayton. 2. The wife of a rector. Thackeray.",
  "wilded - Become wild. [R.] An old garden plant escaped and wilded. J. Earle.",
  "two-tongued - Double-tongued; deceitful. Sandys.",
  "intertex - To intertwine; to weave or bind together. [Obs.] B. Jonson.",
  "mountebankism - The practices of a mountebank; mountebankery.",
  "disconformable - Not conformable. Disconformable in religion from us. Stow (1603).",
  "typology - 1. (Theol.)  A discourse or treatise on types. 2. (Theol.)  The doctrine of types.",
  "eburnine - Of or pertaining to ivory. \"[She] read from tablet eburnine.\" Sir W. Scott.",
  "astrophysical - Pertaining to the physics of astronomical science.",
  "cymule - A small cyme, or one of very few flowers.",
  "derbio - A large European food fish (Lichia glauca).",
  "cruiser - One who, or a vessel that, cruises; -- usually an armed vessel.",
  "prase - A variety of cryptocrystalline of a leek-green color.",
  "squabash - To crush; to quash; to squash. [Colloq. or Slang, Scot.] Sir W. Scott.",
  "epencephalic - (a) Pertaining to the epencephalon. (b) Situated on or over the brain.",
  "noachian - Of or pertaining to the patriarch Noah, or to his time.",
  "pepo - Any fleshy fruit with a firm rind, as a pumpkin, melon, or gourd. See Gourd.",
  "ableness - Ability of body or mind; force; vigor. [Obs. or R.]",
  "uncaused - Having no antecedent cause; uncreated; self-existent; eternal. A. Baxter.",
  "furfurous - Made of bran; furfuraceous. [R.] \"Furfurous bread.\" Sydney Smith.",
  "anomoura - A group of decapod Crustacea, of which the hermit crab in an example.",
  "bemuddle - To muddle; to stupefy or bewilder; to confuse.",
  "semideistical - Half deisticsl; bordering on deism. S. Miller.",
  "lightman - A man who carries or takes care of a light. T. Brown.",
  "tinner - 1. One who works in a tin mine. 2. One who makes, or works in, tinware; a tinman.",
  "rhenish - Of or pertaining to the river Rhine; as, Rhenish wine. -- n.  Rhine wine.",
  "incompassion - Want of compassion or pity. [Obs.] Bp. Sanderson.",
  "extremeless - Having no extremes; infinite.",
  "dysuria - Difficult or painful discharge of urine.",
  "bushelage - A duty payable on commodities by the bushel. [Eng.]",
  "supplyant - Supplying or aiding; auxiliary; suppletory. [Obs.] Shak.",
  "marmorate - Variegated like marble; covered or overlaid with marble. [R.]",
  "dentoid - Shaped like a tooth; tooth-shaped.",
  "vomica - (a) An abscess cavity in the lungs. (b) An abscess in any other parenchymatous organ.",
  "sorcerous - Of or pertaining to sorcery.",
  "ambushment - An ambush. [Obs.] 2 Chron. xiii. 13.",
  "tightness - The quality or condition of being tight.",
  "serfdom - The state or condition of a serf.",
  "autoptically - By means of ocular view, or one's own observation. Sir T. Browne.",
  "foredate - To date before the true time; to antendate.",
  "circumfulgent - Shining around or about.",
  "kymographic - Of or pertaining to a kymograph; as, a kymographic tracing.",
  "hobbyhorsical - Pertaining to, or having, a hobby or whim; eccentric; whimsical.[Colloq.] Sterne.",
  "goosish - Like a goose; foolish. [Obs.] Chaucer.",
  "kilerg - A unit of work equal to one thousand ergs.",
  "respersion - The act of sprinkling or scattering. [Obs.]",
  "friezer - One who, or that which, friezes or frizzes.",
  "aoristic - Indefinite; pertaining to the aorist tense.",
  "ensweep - To sweep over or across; to pass over rapidly. [R.] Thomson.",
  "pailful - The quantity that a pail will hold. \"By pailfuls.\" Shak.",
  "replantation - The act of planting again; a replanting. [R.] Hallywell.",
  "preconform - To conform by way anticipation. De Quincey.",
  "ecclesiological - Belonging to ecclesiology.",
  "prender - The power or right of taking a thing before it is offered. Burrill.",
  "crenated - Having the margin cut into rounded teeth notches, or scallops.",
  "pseudotinea - The bee moth, or wax moth (Galleria).",
  "cuisine - 1. The kitchen or cooking department. 2. Manner or style of cooking.",
  "tittle-tattling - The act or habit of parting idly or gossiping.",
  "sun-burner - A circle or cluster of gas-burners for lighting and ventilating public buildings.",
  "assuming - Pretentious; taking much upon one's self; presumptuous. Burke.",
  "abstractness - The quality of being abstract. \"The abstractness of the ideas.\" Locke.",
  "colling - An embrace; dalliance. [Obs.] Halliwell.",
  "stonework - Work or wall consisting of stone; mason's work of stone. Mortimer.",
  "fordry - Entirely dry; withered. [Obs.] \"A tree fordry.\" Chaucer.",
  "economization - The act or practice of using to the best effect. [R.] H. Spenser.",
  "malet - A little bag or budget. [Obs.] Shelton.",
  "intracranial - Within the cranium or skull. Sir W. Hamilton.",
  "brotelness - Brittleness. [Obs.] Chaucer.",
  "hobiler - A light horseman. See 2d Hobbler. [Obs.] Brande & C.",
  "testudinal - Of, pertaining to, or resembling, a tortoise.",
  "governance - Exercise of authority; control; government; arrangement. Chaucer. J. H. Newman.",
  "woulding - Emotion of desire; inclination; velleity. [Obs.] Hammond.",
  "incontracted - Uncontracted. [Obs.] Blackwall.",
  "maselyn - A drinking cup. See 1st Maslin, 2. [Obs.] Chaucer.",
  "self-conviction - The act of convicting one's self, or the state of being self- convicted.",
  "suboctave - Containing one part of eight; having the ratio of one to eight. Bp. Wilkins.",
  "jingoism - The policy of the Jingoes, so called. See Jingo, 2. [Cant, Eng.]",
  "expulse - To drive out; to expel. [Obs.] If charity be thus excluded and expulsed. Milton.",
  "solertiousness - The quality or state of being solert. [Obs.] Bp. Hacket.",
  "soothly - In truth; truly; really; verily. [Obs.] \"Soothly for to say.\" Chaucer.",
  "hypogastrium - The lower part of the abdomen.",
  "maritated - Having a husband; married. [Obs.]",
  "tibicinate - To play on a tibia, or pipe. [R.]",
  "atmology - That branch of science which treats of the laws and phenomena of aqueous vapor. Whewell.",
  "bilalo - A two-masted passenger boat or small vessel, used in the bay of Manila.",
  "piggin - A small wooden pail or tub with an upright stave for a handle, -- often used as a dipper.",
  "kidney-shaped - Having the form or shape of a kidney; reniform; as, a kidney- shaped leaf. Gray.",
  "pollenize - To supply with pollen; to impregnate with pollen.",
  "folkething - The lower house of the Danish Rigsdag, or Parliament. See Legislature, below.",
  "sancte bell - See Sanctus bell, under Sanctus.",
  "highly - In a high manner, or to a high degree; very much; as, highly esteemed.",
  "lick-spittle - An abject flatterer or parasite. Theodore Hook.",
  "untowardly - Perverse; froward; untoward. \"Untowardly tricks and vices.\" Locke.",
  "peerie - Inquisitive; suspicious; sharp. [Prov. Eng. & Scot.] \"Two peery gray eyes.\" Sir W. Scott.",
  "archencephala - The division that includes man alone. R. Owen.",
  "argean - Pertaining to the ship Argo. See Argo.",
  "ill-timed - Done, attempted, or said, at an unsuitable or unpropitious time.",
  "supplicatingly - In a supplicating manner.",
  "carnify - To form flesh; to become like flesh. Sir M. Hale.",
  "reserate - To unlock; to open. [Obs.] Boyle.",
  "excur - To run out or forth; to extend. [Obs.] Harvey.",
  "semipellucid - Half clear, or imperfectly transparent; as, a semipellucid gem.",
  "loud-mouthed - Having a loud voice; talking or sounding noisily; noisily impudent.",
  "black death - A pestilence which ravaged Europe and Asia in the fourteenth century.",
  "swaggerer - One who swaggers; a blusterer; a bully; a boastful, noisy fellow. Shak.",
  "truffled - Provided or cooked with truffles; stuffed with truffles; as, a truffled turkey.",
  "inquiline - A gallfly which deposits its eggs in galls formed by other insects.",
  "empire state of the west - Missouri; -- a nickname.",
  "nematoblast - A spermatocyte or spermoblast.",
  "politize - To play the politician; to dispute as politicians do. [Obs.] Milton.",
  "decolorant - A substance which removes color, or bleaches.",
  "gast - To make aghast; to frighten; to terrify. See Aghast. [Obs.] Chaucer. Shak.",
  "lamellicornia - A group of lamellicorn, plant-eating beetles; -- called also Lamellicornes.",
  "locally - With respect to place; in place; as, to be locally separated or distant.",
  "equirotal - Having wheels of the same size or diameter; having equal rotation. [R.]",
  "homeopath - A practitioner of homeopathy. [Written also homoeopath.]",
  "milliweber - The thousandth part of one weber.",
  "streek - To stretch; also, to lay out, as a dead body. See Streak. [Obs. or Prov. Eng. & Scot.]",
  "finicking - Finical; unduly particular. [Colloq.]",
  "saim - Lard; grease. [Scot. & Prov. Eng.]",
  "tautologist - One who uses tautological words or phrases.",
  "picine - Of or pertaining to the woodpeckers (Pici), or to the Piciformes.",
  "urry - A sort of blue or black clay lying near a vein of coal.",
  "interknowledge - Mutual knowledge or acquaintance. [Obs.] Bacon.",
  "goman - A husband; a master of a family. [Obs.]",
  "dandyize - To make, or to act, like a dandy; to dandify.",
  "squali - The suborder of elasmobranch fishes which comprises the sharks.",
  "duskish - Somewhat dusky. \" Duskish smoke.\" Spenser. -- Dusk\"ish*ly, adv. -- Dusk\"ish*ness, n.",
  "preventingly - So as to prevent or hinder.",
  "millifold - Thousandfold. [R.] Davies (Holy Roode).",
  "printa-ble - Worthy to be published. [R.]",
  "cor- - A prefix signifying with, together, etc. See Com-.",
  "dereyne - Same as Darraign. [Obs.] Chaucer.",
  "collingly - With embraces. [Obs.] Gascoigne.",
  "grassiness - The state of abounding with grass; a grassy state.",
  "ambulant - Walking; moving from place to place. Gayton.",
  "iterative - Repeating. Cotgrave. -- It\"er*a*tive*ly, adv.",
  "momently - 1. For a moment. 2. In a moment; every moment; momentarily.",
  "psychoanalytic - = Psychanalysis, Psychanalytic.",
  "debacchation - Wild raving or debauchery. [R.] Prynne.",
  "exoculate - To deprive of eyes. [R.] W. C. Hazlitt.",
  "incontaminate - Not contaminated; pure. Moore. -- In`con*tam\"i*nate*ness, n.",
  "tartuffish - Like a tartuffe; precise; hypocritical. Sterne.",
  "reviviscent - Able or disposed to revive; reviving. E. Darwin.",
  "grilly - To broil; to grill; hence, To harass. [Obs.] Hudibras.",
  "smiter - One who smites. I give my back to the smiters. Isa. l. 6.",
  "fair-haired - Having fair or light-colored hair.",
  "semiquaver - A note of half the duration of the quaver; -- now usually called a sixsteenth note.",
  "disobligatory - Releasing from obligation. \"Disobligatory power.\" Charles I.",
  "internality - The state of being internal or within; interiority.",
  "metalliferous - Producing metals; yielding metals.",
  "double dealing - False or deceitful dealing. See Double dealing, under Dealing. Shak.",
  "poikilothermal - Having a varying body temperature. See Homoiothermal.",
  "whitling - A young full trout during its second season. [Prov. Eng.]",
  "sphenoidal - 1. Sphenoid. 2. (Crystalloq.)  Pertaining to, or resembling, a sphenoid.",
  "irretention - Want of retaining power; forgetfulness. De Quincey.",
  "dreynte - p. p., of Drench to drown. [Obs.] Chaucer.",
  "microweber - The millionth part of one weber.",
  "treacher - A traitor; a cheat. [Obs.] Treacher and coward both. Beau. & Fl.",
  "fastuous - Proud; haughty; disdainful. [Obs.] Barrow. Fas\"tu*ous*ness, n. [Obs.] Jer. Taylor.",
  "stutterer - One who stutters; a stammerer.",
  "expiscatory - Tending to fish out; searching out [R.] Carlyle.",
  "hederaceous - Of, pertaining to, or resembling, ivy.",
  "snippack - The common snipe. [Prov. Eng.]",
  "undevotion - Absence or want of devotion.",
  "sundryman - One who deals in sundries, or a variety of articles.",
  "aurocephalous - Having a gold-colored head.",
  "trangram - Something intricately contrived; a contrived; a puzzle. [Cant & Obs.] Arbuthnot.",
  "tulipist - A person who is especially devoted to the cultivation of tulips. Sir T. Browne.",
  "poseur - A person who poses or attitudizes, esp. mentally.",
  "bequeathal - The act of bequeathing; bequeathment; bequest. Fuller.",
  "chondrify - To convert, or be converted, into cartilage.",
  "mortifiedness - The state of being mortified; humiliation; subjection of the passions. [R.]",
  "chantant - Composed in a melodious and singing style.",
  "interoperculum - The postero-inferior opercular bone, in fishes.",
  "church-bench - A seat in the porch of a church. Shak.",
  "halk - A nook; a corner. [Obs.] Chaucer.",
  "acreable - Of an acre; per acre; as, the acreable produce.",
  "muffetee - A small muff worn over the wrist. [Prov. Eng.] Halliwell.",
  "subministration - The act of subministering. [Obs.] Sir H. Wotton.",
  "epiclinal - Situated on the receptacle or disk of a flower.",
  "strumousness - The state of being strumous.",
  "primordially - At the beginning; under the first order of things; originally.",
  "longhorn - A long-horned animal, as a cow, goat, or beetle. See Long- horned.",
  "crossroad - A road that crosses another; an obscure road intersecting or avoiding the main road.",
  "enjoyable - Capable of being enjoyed or of giving joy; yielding enjoyment. Milton.",
  "hemselve - Themselves; -- used reflexively. [Obs.] Chaucer.",
  "limbmeal - Piecemeal. [Obs.] \"To tear her limbmeal.\" Shak.",
  "stipendiarian - Acting from mercenary considerations; stipendiary. A. Seward.",
  "petrific - Petrifying; petrifactive. Death with his mace petrific, cold and dry. Milton.",
  "shoppish - Having the appearance or qualities of a shopkeeper, or shopman.",
  "sibilous - Having a hissing sound; hissing; sibilant. [R.] Pennant.",
  "painture - The art of painting. [Obs.] Chaucer. Dryden.",
  "aptotic - Pertaining to, or characterized by, aptotes; uninflected; as, aptotic languages.",
  "malaxate - To soften by kneading or stirring with some thinner substance. [R.]",
  "croupy - Of or pertaining to croup; resembling or indicating croup; as, a croupy cough.",
  "flower-gentle - A species of amaranth (Amarantus melancholicus).",
  "exheredation - A disinheriting; disherisor. [R.]",
  "earcap - A cap or cover to protect the ear from cold.",
  "mesmerical - Of, pertaining to, or induced by, mesmerism; as, mesmeric sleep.",
  "permanable - Permanent; durable. [Obs.] Lydgate.",
  "indiscipline - Want of discipline or instruction. [R.]",
  "tempestivily - The quality, or state, of being tempestive; seasonableness. [Obs.] Sir T. Browne.",
  "levulosan - An unfermentable carbohydrate obtained by gently heating levulose.",
  "ostriferous - Producing oysters; containing oysters.",
  "irreverend - Irreverent. [Obs.] Immodest speech, or irreverend gesture. Strype.",
  "psychologist - One who is versed in, devoted to, psychology.",
  "ichthyotomist - One skilled in ichthyotomy.",
  "unsensualize - To elevate from the domain of the senses; to purify. Coleridge.",
  "syncarpous - Composed of several carpels consolidated into one ovary.",
  "annealer - One who, or that which, anneals.",
  "carriageable - Passable by carriages; that can be conveyed in carriages. [R.] Ruskin.",
  "opinionist - One fond of his own notions, or unduly attached to his own opinions. Glanvill.",
  "ahorseback - On horseback. Two suspicious fellows ahorseback. Smollet.",
  "repertitious - Found; gained by finding. [Obs.]",
  "nexible - That may be knit together. [R.]",
  "baccivorous - Eating, or subsisting on, berries; as, baccivorous birds.",
  "sensifacient - Converting into sensation. Huxley.",
  "highfaluting - High-flown, bombastic language. [Written also hifalutin.] [Jocular, U. S.] Lowell.",
  "lobulated - Made up of, or divided into, lobules; as, a lobulated gland.",
  "viraginity - The qualities or characteristics of a virago.",
  "bloncket - Gray; bluish gray. [Obs.] Our bloncket liveries been all too sad. Spenser.",
  "trimeran - One of the Trimera. Also used adjectively.",
  "confluxibility - The  tendency of fluids to run together. [R.] Boyle.",
  "angrily - In an angry manner; under the influence of anger.",
  "waniand - The wane of the moon. [Obs.] Halliwell.",
  "nitryl - A name sometimes given to the nitro group or radical.",
  "solempne - Solemn; grand; stately; splendid; magnificent. [Obs.] Chaucer.",
  "caber - A pole or beam used in Scottish games for tossing as a trial of strength.",
  "enode - To clear of knots; to make clear. [Obs.] Cockeram.",
  "herpetologist - One versed in herpetology, or the natural history of reptiles.",
  "colorman - A vender of paints, etc. Simmonds.",
  "scribatious - Skillful in, or fond of, writing. [Obs.] Barrow.",
  "azorian - Of or pertaining to the Azores. -- n.  A native of the Azores.",
  "unexpressible - Inexpressible. Tillotson. -- Un`ex*press\"i*bly, adv.",
  "siddow - Soft; pulpy. [Obs. or Prov. Eng.]",
  "exorate - To persuade, or to gain, by entreaty. [Obs.] Cockeram.",
  "painless - Free from pain; without pain. -- Pain\"less*ly, adv. -- Pain\"less*ness, n.",
  "strang - Strong. [Obs. or Prov. Eng. & Scot.] Halliwell.",
  "spicery - 1. Spices, in general. Chaucer. 2. A repository of spices. Addison.",
  "brininess - The state or quality of being briny; saltness; brinishness.",
  "undertenancy - Tenancy or tenure under a tenant or lessee; the tenure of an undertenant.",
  "arcadic - Of or pertaining to Arcadia; pastoral; ideally rural; as, Arcadian simplicity or scenery.",
  "monomya - An order of lamellibranchs having but one muscle for closing the shell, as the oyster.",
  "pyritology - The science of blowpipe analysis.",
  "erective - Making erect or upright; raising; tending to erect.",
  "superfecundity - Superabundant fecundity or multiplication of the species.",
  "contrabandist - One who traffic illegaly; a smuggler.",
  "tangelo - A hybrid between the tangerine orange and the grapefruit, or pomelo; also, the fruit.",
  "indevote - Not devoted. [Obs.] Bentley. Clarendon.",
  "pollinium - A coherent mass of pollen, as in the milkweed and most orchids.",
  "duressor - One who subjects another to duress Bacon.",
  "pruce - Prussian leather. [Obs.] Dryden.",
  "phelloderm - A layer of green parenchimatous cells formed on the inner side of the phellogen.",
  "toxicogenic - Producing toxic products; as, toxicogenic germs or bacteria.",
  "eventuation - The act of eventuating or happening as a result; the outcome. R. W. Hamilton.",
  "montrue - That on which anything is mounted; a setting; hence, a saddle horse. [Obs.] Spenser.",
  "habile - Fit; qualified; also, apt. [Obs.] Spenser.",
  "zoanthoid - Of or pertaining to the Zoanthacea.",
  "damascus steel - See Damask steel, under Damask.",
  "elephantoid - Resembling an elephant in form or appearance.",
  "ophthalmology - The science which treats of the structure, functions, and diseases of the eye.",
  "adviso - Advice; counsel; suggestion; also, a dispatch or advice boat. [Obs.] Sir T. Browne.",
  "tonsilitis - Inflammation of the tonsil; quinsy. [Written also, and more usually, tonsillitis.]",
  "disprepare - To render unprepared. [Obs.] Hobbes.",
  "logarithmically - By the use of logarithms.",
  "putour - A keeper of a brothel; a procurer. [Obs.] Chaucer.",
  "succumbent - Submissive; yielding. [R.] Howell.",
  "mouldwarp - See Mole the animal. Spenser.",
  "cancerate - To grow into a canser; to become cancerous. Boyle.",
  "shrill-tongued - Having a shrill voice. \"When shrill-tongued Fulvia scolds.\" Shak.",
  "spritely - See Sprightful, Sprightfully, Sprightliness, Sprightly, etc.",
  "unripeness - Quality or state of being unripe.",
  "blowen - A prostitute; a courtesan; a strumpet. [Low] Smart.",
  "impalm - To grasp with or hold in the hand. [R.] J. Barlow.",
  "consecutiveness - The state or quality of being consecutive.",
  "unheired - Destitute of an heir. To leave him utterly unheired. Chapman.",
  "precursive - Preceding; introductory; precursory. \"A deep precursive sound.\" Coleridge.",
  "ustorious - Having the quality of burning. [R.] I. Watts.",
  "talegalla - A genus of Australian birds which includes the brush turkey. See Brush turkey.",
  "trisaccharid - A complex sugar, as raffinose, yielding by hydrolysis three simple sugar molecules.",
  "processive - Proceeding; advancing. Because it is language, -- ergo, processive. Coleridge.",
  "siphuncled - Having a siphuncle; siphunculated.",
  "brumal - Of or pertaining to winter. \"The brumal solstice.\" Sir T. Browne.",
  "temporist - A temporizer. [Obs.] Why, turn a temporist, row with the tide. Marston.",
  "bayad - A large, edible, siluroid fish of the Nile, of two species (Bagrina bayad and B. docmac).",
  "infallibilist - One who accepts or maintains the dogma of papal infallibility.",
  "jaspidean - Consisting of jasper, or containing jasper; jaspery; jasperlike.",
  "prepositive - Put before; prefixed; as, a prepositive particle. -- n.  A prepositive word. Tooke.",
  "skilder - To beg; to pilfer; to skelder. [Prov. Eng.& Scot.] Sir W. Scott.",
  "megavolt - One of the larger measures of electro-motive force, amounting to one million volts.",
  "castrametation - The art or act of encamping; the making or laying out of a camp.",
  "lightstruck - Damaged by accidental exposure to light; light-fogged; -- said of plates or films.",
  "antarchistical - Opposed to all human government. [R.]",
  "subundation - A flood; a deluge. [Obs.] Huloet.",
  "dicast - A functionary in ancient Athens answering nearly to the modern juryman.",
  "pollage - A head or poll tax; hence, extortion. [Obs.] Foxe.",
  "flame-colored - Of the color of flame; of a bright orange yellow color. Shak.",
  "paronychia - A whitlow, or felon. Quincy.",
  "nonmalignant - Not malignant, as a disease.",
  "pulsator - 1. A beater; a striker. 2. (Mech.)  That which beats or throbs in working.",
  "telegrammic - Pertaining to, or resembling, a telegram; laconic; concise; brief. [R.]",
  "coiffure - A headdress, or manner of dressing the hair. Addison.",
  "divel - To rend apart. [Obs.] Sir T. Browne.",
  "fornicatress - A woman guilty of fornication. Shak.",
  "brazenness - The quality or state of being brazen. Johnson.",
  "emaculation - The act of clearing from spots. [Obs.] Johnson.",
  "wolverene state - Michigan; -- a nickname.",
  "rubrician - One skilled in, or tenaciously adhering to, the rubric or rubrics.",
  "headshake - A significant shake of the head, commonly as a signal of denial. Shak.",
  "nonfulfillment - Neglect or failure to fulfill.",
  "photochromotypy - The art of making photochromotypes.",
  "terebrate - To perforate; to bore; to pierce. [R.] Sir T. Browne.",
  "ectodermic - Of or relating to the ectoderm.",
  "isobaric - Denoting equal pressure; as, an isobaric line; specifically, of or pertaining to isobars.",
  "befitting - Suitable; proper; becoming; fitting.",
  "craniological - Of or pertaining to craniology.",
  "caird - A traveling tinker; also a tramp or sturdy beggar. [Prov. Eng.]",
  "gibel - A kind of carp (Cyprinus gibelio); -- called also Prussian carp.",
  "misconsequence - A wrong consequence; a false deduction.",
  "acuition - The act of sharpening. [Obs.]",
  "arciform - Having the form of an arch; curved.",
  "terrestre - Terrestrial; earthly. [Obs.] \"His paradise terrestre.\" Chaucer.",
  "irroration - The act of bedewing; the state of being moistened with de [Obs.] Chambers.",
  "plicature - A fold; a doubling; a plication. Dr. H. More.",
  "foreshortening - Representation in a foreshortened mode or way.",
  "bona fides - Good faith; honesty; freedom from fraud or deception.",
  "efferous - Like a wild beast; fierce. [Obs.]",
  "assessable - Liable to be assessed or taxed; as, assessable property.",
  "mussy - Disarranged; rumpled. [Colloq. U.S.]",
  "pitfall - A pit deceitfully covered to entrap wild beasts or men; a trap of any kind. Sir T. North.",
  "fossilist - One who is versed in the science of fossils; a paleontologist. Joseph Black.",
  "shrouding - The shrouds. See Shroud, n., 7.",
  "monographist - One who writes a monograph.",
  "omnipercipient - Perceiving everything. Dr. H. More.",
  "decagonal - Pertaining to a decagon; having ten sides.",
  "gregal - Pertaining to, or like, a flock. For this gregal conformity there is an excuse. W. S. Mayo.",
  "anisometropia - Unequal refractive power in the two eyes.",
  "unguiform - Having the form of a claw or claws.",
  "canoeing - The act or art of using a canoe.",
  "gorce - A pool of water to keep fish in; a wear. [Obs.]",
  "erythric - Pertaining to, derived from, or resembling, erythrin.",
  "vitriolation - The act, process, or result of vitriolating.",
  "trifurcate - Having three branches or forks; trichotomous.",
  "foistiness - Fustiness; mustiness. [Obs.]",
  "noncompletion - Lack of completion; failure to complete.",
  "roomage - Space; place; room. [Obs.] Sir H. Wotton.",
  "confessary - One who makes a confession. [Obs.] Bp. Hall.",
  "quartziferous - Consisting chiefly of quartz; containing quartz.",
  "classifiable - Capable of being classified.",
  "joculatory - Droll; sportive. [Obs.] Cockeram.",
  "scombriformes - A division of fishes including the mackerels, tunnies, and allied fishes.",
  "benedictory - Expressing wishes for good; as, a benedictory prayer. Thackeray.",
  "incage - To confine in, or as in, a cage; to coop up. [Written also encage.] \"Incaged birds.\" Shak.",
  "phocacean - Any species of Phoca; a seal.",
  "prohibiter - One who prohibits or forbids; a forbidder; an interdicter.",
  "arthrology - That part of anatomy which treats of joints.",
  "braggardism - Boastfulness; act of bragging. Shak.",
  "calligraphical - Of or pertaining to calligraphy. Excellence in the calligraphic act. T. Warton.",
  "anasarcous - Belonging, or affected by, anasarca, or dropsy; dropsical. Wiseman.",
  "overagitate - To agitate or discuss beyond what is expedient. Bp. Hall.",
  "sided - Having (such or so many) sides; -- used in composition; as, one-sided; many-sided.",
  "moslings - Thin shreds of leather shaved off in dressing skins. Simmonds.",
  "subventionize - To come to the aid of; to subsidize; to support.",
  "charismatic - Of or pertaining to a charism.",
  "epilogize - To speak an epilogue to; to utter as an epilogue.",
  "rattler - One who, or that which, rattles.",
  "decoy-man - A man employed in decoying wild fowl.",
  "threepenny - Costing or worth three pence; hence, worth but little; poor; mean.",
  "oilstone - A variety of hone slate, or whetstone, used for whetting tools when lubricated with oil.",
  "stirpiculture - The breeding of special stocks or races.",
  "priorate - The dignity, office, or government, of a prior. T. Warton.",
  "abrood - In the act of brooding. [Obs.] Abp. Sancroft.",
  "epicurism - 1. The doctrines of Epicurus. 2. Epicurean habits of living; luxury.",
  "antheriform - Shaped like an anther; anther-shaped.",
  "ear-splitting - Deafening; disagreeably loud or shrill; as, ear-splitting strains.",
  "angustifoliate - Having narrow leaves. Wright.",
  "largeness - The quality or state of being large.",
  "dandyling - A little or insignificant dandy; a contemptible fop.",
  "pharmacist - One skilled in pharmacy; a pharmaceutist; a druggist.",
  "reingratiate - To ingratiate again or anew. Sir. T. Herbert.",
  "transpirable - Capable of being transpired, or of transpiring.",
  "dehortatory - Fitted or designed to dehort or dissuade. Bp. Hall.",
  "excreation - Act of spitting out. [Obs.] Cockeram.",
  "fouter - A despicable fellow. [Prov. Eng.] Brockett.",
  "facound - Speech; eloquence. [Obs.] Her facound eke full womanly and plain. Chaucer.",
  "circassian - Of or pertaining to Circassia, in Asia. -- n.  A native or inhabitant of Circassia.",
  "quotiety - The relation of an object to number. Krauth-Fleming.",
  "disprejudice - To free from prejudice. [Obs.] W. Montagu.",
  "licensee - The person to whom a license is given.",
  "surrejoinder - The answer of a plaintiff to a defendant's rejoinder.",
  "scleroid - Having a hard texture, as nutshells.",
  "orographical - Of or pertaining to orography.",
  "undisclose - To keep close or secret. [Obs.] Daniel.",
  "joobbeh - A long outer garment worn by both sexes of Mohammedans of the better class.",
  "irrationally - In an irrational manner. Boyle.",
  "disadvance - To draw back, or cause to draw back. [Obs.] Spenser.",
  "tarsotomy - The operation of cutting or removing the tarsal cartilages.",
  "smock-faced - Having a feminine countenance or complexion; smooth-faced; girlish. Fenton.",
  "anapodeictic - Not apodeictic; undemonstrable. [R.]",
  "pertransient - Passing through or over. [R.]",
  "annunciable - That may be announced or declared; declarable. [R.]",
  "caporal - One who directs work; an overseer. [Sp. Amer.]",
  "betrim - To set in order; to adorn; to deck, to embellish; to trim. Shak.",
  "kaleidoscopic - Of, pertaining to, or formed by, a kaleidoscope; variegated.",
  "smallclothes - A man's garment for the hips and thighs; breeches. See Breeches.",
  "brimming - Full to the brim; overflowing.",
  "misusage - Bad treatment; abuse. Spenser.",
  "redleg - (a) The redshank. (b) The turnstone.",
  "slavophil - One, not being a Slav, who is interested in the development and prosperity of that race.",
  "dialogist - 1. A speaker in a dialogue. 2. A writer of dialogues. P. Skelton.",
  "lustihood - State of being lusty; vigor of body. \" Full of lustihood.\" Tennyson.",
  "stern-wheeler - A steamboat having a stern wheel instead of side wheels. [Colloq. U.S.]",
  "prelatic - Of or pertaining to prelates or prelacy; as, prelatical authority. Macaulay.",
  "prospectiveness - Quality of being prospective.",
  "inknot - To fasten or bind, as with a knot; to knot together. Fuller.",
  "columnated - Having columns; as, columnated temples.",
  "contradictable - Capable of being contradicting.",
  "monothelitism - The doctrine of the Monothelites.",
  "altitudinal - Of or pertaining to height; as, altitudinal measurements.",
  "plutology - The science which treats of wealth.",
  "regimentally - In or by a regiment or regiments; as, troops classified regimentally.",
  "shatter-pated - Disordered or wandering in intellect; hence, heedless; wild. J. Goodman.",
  "misinformer - One who gives or incorrect information.",
  "papism - Popery; -- an offensive term. Milton.",
  "mulse - Wine boiled and mingled with honey.",
  "astroscopy - Observation of the stars. [Obs.]",
  "equus - A genus of mammals, including the horse, ass, etc.",
  "abnormally - In an abnormal manner; irregularly. Darwin.",
  "spirituousness - The quality or state of being spirituous. [R.] Boyle.",
  "abstracter - One who abstracts, or makes an abstract.",
  "petrological - Of or pertaining to petrology.",
  "plumbum - The technical name of lead. See Lead.",
  "rectorate - The office, rank, or station of a rector; rectorship.",
  "jaunty - Airy; showy; finical; hence, characterized by an affected or fantastical manner.",
  "prong-hoe - A hoe with prongs to break the earth.",
  "pillow lace - Lace made by hand with bobbins on a pillow.",
  "semifable - That which is part fable and part truth; a mixture of truth and fable. De Quincey.",
  "unlived - Bereft or deprived of life. [Obs.] Shak.",
  "sinister-handed - Left-handed; hence, unlucky. [Obs.] Lovelace.",
  "electorality - The territory or dignity of an elector; electorate. [R.] Sir H. Wotton.",
  "impictured - Pictured; impressed. [Obs.] Spenser.",
  "flourishingly - , adv. In a flourishing manner; ostentatiously.",
  "mizzenmast - The hindmost mast of a three-masted vessel, or of a yawl-rigged vessel.",
  "patolli - An American Indian game analogous to dice, probably originally a method of divination.",
  "concinnate - To place fitly together; to adapt; to clear. [Obs.] Holland.",
  "pestalozzianism - The system of education introduced by Pestalozzi.",
  "kimbo - Crooked; arched; bent. [Written also kimbow.] Dryden.",
  "farandams - A fabrik made of silk and wool or hair. Simmonds.",
  "osteopath - A practitioner of osteopathy.",
  "saintologist - One who writes the lives of saints. [R.]",
  "inocular - Inserted in the corner of the eye; -- said of the antenn",
  "streperous - Loud; boisterous. [R.] Sir T. Browne.",
  "motte - A clump of trees in a prairie. [Local, U.S.]",
  "hyperoxide - A compound having a relatively large percentage of oxygen; a peroxide. [Obs.]",
  "philomathic - 1. Of or pertaining to philomathy. 2. Having love of learning or letters.",
  "plutonist - One who adopts the geological theory of igneous fusion; a Plutonian. See Plutonism.",
  "herbid - Covered with herbs. [Obs.] Bailey.",
  "propitiable - Capable of being propitiated.",
  "paleontologist - One versed in paleontology.",
  "sinisterly - In a sinister manner. Wood.",
  "oxidable - Capable of being converted into an oxide.",
  "schoolery - Something taught; precepts; schooling. [Obs.] penser.",
  "brahmanism - The religion or system of doctrines of the Brahmans; the religion of Brahma.",
  "heartdeep - Rooted in the heart. Herbert.",
  "anachoret - See Anchoret, Anchoretic. [Obs.]",
  "depardieux - In God's name; certainly. [Obs.] Chaucer.",
  "lentisk - A tree; the mastic. See Mastic.",
  "cottaged - Set or covered with cottages. Even humble Harting's cottaged vale. Collins.",
  "but-thorn - The common European starfish (Asterias rubens).",
  "tonite - An explosive compound; a preparation of gun cotton.",
  "ruction - An uproar; a quarrel; a noisy outbreak. [Prov. Eng. & Scot.]",
  "grouting - The process of filling in or finishing with grout; also, the grout thus filled in. Gwilt.",
  "ash-fire - A low fire used in chemical operations.",
  "flat-bottomed - Having an even lower surface or bottom; as, a flat-bottomed boat.",
  "volumist - One who writes a volume; an author. [Obs.] Milton.",
  "festination - Haste; hurry. [Obs.] Sir T. Browne.",
  "staffman - A workman employed in silk throwing.",
  "gaming - The act or practice of playing games for stakes or wagers; gambling.",
  "sheathy - Forming or resembling a sheath or case. Sir T. Browne.",
  "epodic - Pertaining to, or resembling, an epode.",
  "zincic - Pertaining to, containing, or resembling, zinc; zincous.",
  "fiants - The dung of the fox, wolf, boar, or badger.",
  "ronnen - obs. imp. pl., and Ron\"nen (,  obs. p. p. of Renne, to run. Chaucer.",
  "ridgepole - The timber forming the ridge of a roof, into which the rafters are secured.",
  "armozine - A thick plain silk, generally black, and used for clerical. Simmonds.",
  "besiegement - The act of besieging, or the state of being besieged. Golding.",
  "oilman - One who deals in oils; formerly, one who dealt in oils and pickles.",
  "desilverize - To deprive, or free from, silver; to remove silver from.",
  "fissipedal - Having the toes separated to the base. [See Aves.]",
  "undeserve - To fail to deserve. [Obs.] Milton.",
  "effierce - To make fierce. [Obs.] Spenser.",
  "tith - Tight; nimble. [Obs.] Of a good stirring strain too, she goes tith. Beau. & Fl.",
  "beseechment - The act of beseeching or entreating earnestly. [R.] Goodwin.",
  "tristichous - Arranged in three vertical rows.",
  "unconquerable - Not conquerable; indomitable. -- Un*con\"quer*a*bly, adv.",
  "prosecutable - Capable of being prosecuted; liable to prosecution.",
  "redcoat - One who wears a red coat; specifically, a red-coated British soldier.",
  "interworking - The act of working in together; interweaving. Milton.",
  "reimpression - A second or repeated impression; a reprint.",
  "predeclare - To declare or announce beforehand; to preannounce. Milman.",
  "campylospermous - Having seeds grooved lengthwise on the inner face, as in sweet cicely.",
  "dulcification - The act of dulcifying or sweetening. Boyle.",
  "enteradenology - The science which treats of the glands of the alimentary canal.",
  "unseasoned - 1. Not seasoned. 2. Untimely; ill-timed. [Obs.] Shak.",
  "pererration - A wandering, or rambling, through various places. [R.] Howell.",
  "collateralness - The state of being collateral.",
  "munity - Freedom; security; immunity. [Obs.] W. Montagu.",
  "water pimpernel - A small white-flowered shrub; brookweed.",
  "endearing - Making dear or beloved; causing love. -- En*dear\"ing*ly, adv.",
  "disrulily - In a disorderly manner. [Obs.] Rom. of R.",
  "hippocratism - The medical philosophy or system of Hippocrates.",
  "claps - Variant of Clasp [Obs.] Chaucer.",
  "monothelism - The doctrine of the Monothelites.",
  "battening - Furring done with small pieces nailed directly upon the wall.",
  "immaterialist - One who believes in or professes, immaterialism.",
  "kipe - An osier basket used for catching fish. [Prov. Eng.]",
  "tut-mouthed - Having a projecting under jaw; prognathous. [Obs.] Holland.",
  "mitigator - One who, or that which, mitigates.",
  "recoveror - The demandant in a common recovery after judgment. Wharton.",
  "consumptiveness - A state of being consumptive, or a tendency to a consumption.",
  "untreatable - Incapable of being treated; not practicable. [R.] Dr. H. More.",
  "agood - In earnest; heartily. [Obs.] \"I made her weep agood.\"  Shak.",
  "inertitude - Inertness; inertia. [R.] Good.",
  "fluoroscope - An instrument for observing or exhibiting fluorescence.",
  "refreshing - Reviving; reanimating. -- Re*fresh\"ing*ly, adv. -- Re*fresh\"ing*ness, n.",
  "lincoln green - . A color of cloth formerly made in Lincoln, England; the cloth itself.",
  "centigramme - The hundredth part of a gram; a weight equal to .15432 of a grain. See Gram.",
  "epidermal - Of or pertaining to the epidermis; epidermic; cuticular.",
  "high-seasoned - Enriched with spice and condiments; hence, exciting; piquant.",
  "scoundrelism - The practices or conduct of a scoundrel; baseness; rascality. Cotgrave.",
  "underfeed - To feed with too little food; to supply with an insufficient quantity of food.",
  "bongrace - A projecting bonnet or shade to protect the complexion; also, a wide-brimmed hat. [Obs.]",
  "undefine - To make indefinite; to obliterate or confuse the definition or limitations of.",
  "unpriest - To deprive of priesthood; to unfrock. [R.] Milton.",
  "principiation - Analysis into primary or elemental parts. [Archaic] Bacon.",
  "obsolescence - The state of becoming obsolete.",
  "archmarshal - The grand marshal of the old German empire, a dignity that to the Elector of Saxony.",
  "sardonian - Sardonic. [Obs.] \"With Sardonian smile.\" Spenser.",
  "chunam - Quicklime; also, plaster or mortar. [India] Whitworth.",
  "rarification - See Rarefaction. [R.] Am. Chem. Journal.",
  "dynamitard - A political dynamiter. Note: [A form found in some newspapers.]",
  "gargarize - To gargle; to rinse or wash, as the mouth and throat. [Obs.] Bacon.",
  "overmeddling - Excessive interference. \"Justly shent for their overmeddling.\" Fuller.",
  "plumulose - Having hairs branching out laterally, like the parts of a feather.",
  "papality - The papacy. [Obs.] Ld. Berners. Milton.",
  "summist - One who sums up; one who forms an abridgment or summary. Sir E. Dering.",
  "anabatic - Pertaining to anabasis; as, an anabatic fever. [Obs.]",
  "arietta - A short aria, or air. \"A military ariette.\" Sir W. Scott.",
  "dialogize - To discourse in dialogue. Fotherby.",
  "santon - A Turkish saint; a kind of dervish, regarded by the people as a saint: also, a hermit.",
  "defendable - Capable of being defended; defensible. [R.]",
  "hot-short - More or less brittle when heated; as, hot-short iron.",
  "alleviative - Tending to alleviate. -- n.  That which alleviates.",
  "conqueress - A woman who conquers. Fairfax.",
  "witchuck - The sand martin, or bank swallow. [Prov. Eng.]",
  "unthrone - To remove from, or as from, a throne; to dethrone. Milton.",
  "sulks - The condition of being sulky; a sulky mood or humor; as, to be in the sulks.",
  "tokened - Marked by tokens, or spots; as, the tokened pestilence. [Obs.] Shak.",
  "circumgyrate - To roll or turn round; to cause to perform a rotary or circular motion. Ray.",
  "tantrum - A whim, or burst of ill-humor; an affected air. [Colloq.] Thackeray.",
  "pentachloride - A chloride having five atoms of chlorine in each molecule.",
  "odontography - A description of the teeth.",
  "demonographer - A demonologist. [R.] Am. Cyc.",
  "self-help - The act of aiding one's self, without depending on the aid of others.",
  "importing - Full of meaning. [Obs.] Shak.",
  "lendable - Such as can be lent. Sherwood.",
  "ferriage - The price or fare to be paid for passage at a ferry.",
  "frote - To rub or wear by rubbing; to chafe. [Obs.] B. Jonson.",
  "canalization - Construction of, or furnishing with, a canal or canals. [R.]",
  "miscomputation - Erroneous computation; false reckoning.",
  "stridulator - That which stridulates. Darwin.",
  "oxiodic - Pertaining to, or designating, certain compounds of iodine and oxygen.",
  "disadvise - To advise against; to dissuade from. [R.] Boyle.",
  "badger-legged - Having legs of unequal length, as the badger was thought to have. Shak.",
  "soil pipe - A pipe or drain for carrying off night soil.",
  "mealies - Maize or Indian corn; -- the common name in South Africa.",
  "unruinated - Not ruined or destroyed. [Obs.] \"Unruinated towers.\" Bp. Hall.",
  "pucherite - Vanadate of bismuth, occurring in minute reddish brown crystals.",
  "clamatorial - Like or pertaining to the Clamatores.",
  "entomical - Relating to insects; entomological.",
  "grey - See Gray (the correct orthography).",
  "foiler - One who foils or frustrates. Johnson.",
  "tenability - The quality or state of being tenable; tenableness.",
  "appaume - A hand open and extended so as to show the palm.",
  "stowce - (a) A windlass. (b) A wooden landmark, to indicate possession of mining land.",
  "laureateship - State, or office, of a laureate.",
  "empark - To make a park of; to inclose, as with a fence; to impark. [Obs.]",
  "frigorific - Causing cold; producing or generating cold. Quincy.",
  "booetes - A northern constellation, containing the bright star Arcturus.",
  "quaich - A small shallow cup or drinking vessel. [Scot.] [Written also quegh.]",
  "gill-flirt - A thoughtless, giddy girl; a flirt-gill. Sir W. Scott.",
  "abrahamitic - Relating to the patriarch Abraham.",
  "subfuscous - Duskish; moderately dark; brownish; tawny.",
  "preterperfect - Old name of the tense also called preterit.",
  "organo- - A combining form denoting relation to, or connection with, an organ or organs.",
  "papoose - A babe or young child of Indian parentage in North America.",
  "silicle - A seed vessel resembling a silique, but about as broad as it is long. See Silique.",
  "nunnation - The pronunciation of n at the end of words.",
  "puggered - Puckered. [Obs.] Dr. H. More.",
  "encincture - A cincture. [Poetic] The vast encincture of that gloomy sea. Wordsworth.",
  "bioplasmic - Pertaining to, or consisting of, bioplasm.",
  "canopus - A star of the first magnitude in the southern constellation Argo.",
  "undull - To remove the dullness of; to clear. [Obs.] Whitlock.",
  "grammatist - A petty grammarian. [R] Tooke.",
  "silentiary - One appointed to keep silence and order in court; also, one sworn not to divulge secre",
  "pykar - An ancient English fishing boat.",
  "johnsonian - Pertaining to or resembling Dr. Johnson or his style; pompous; inflated.",
  "sparkish - 1. Like a spark; airy; gay. W. Walsh. 2. Showy; well-dresed; fine. L'Estrange.",
  "blackguardism - The conduct or language of a blackguard; rufflanism.",
  "peignoir - A woman's loose dressing sack; hence, a loose morning gown or wrapper.",
  "mentality - Quality or state of mind. \"The same hard mentality.\" Emerson.",
  "stylometer - An instrument for measuring columns.",
  "sportal - Of or pertaining to sports; used in sports. [R.] \"Sportal arms.\" Dryden.",
  "mendication - The act or practice of begging; beggary; mendicancy. Sir T. Browne.",
  "dasewe - To become dim-sighted; to become dazed or dazzled. [Obs.] Chauscer.",
  "galvanologist - One who describes the phenomena of galvanism; a writer on galvanism.",
  "diocesener - One who belongs to a diocese. [Obs.] Bacon.",
  "heatless - Destitute of heat; cold. Beau. & Fl.",
  "trucebreaker - One who violates a truce, covenant, or engagement.",
  "semispheroidal - Formed like a half spheroid.",
  "tut-workman - One who does tut-work. Tomlinson.",
  "admittatur - The certificate of admission given in some American colleges.",
  "numismatics - The science of coins and medals.",
  "water sprite - A sprite, or spirit, imagined as inhabiting the water. J. R. Drake.",
  "anisomerous - Having the number of floral organs unequal, as four petals and six stamens.",
  "imban - To put under a ban. [R.] Barlow.",
  "occamy - An alloy imitating gold or silver. [Written also ochimy, ochymy, etc.]",
  "aggravatingly - In an aggravating manner.",
  "agonism - Contention for a prize; a contest. [Obs.] Blount.",
  "disparagingly - In a manner to disparage or dishonor; slightingly.",
  "theosophic - Of or pertaining to theosophy. -- The`o*soph\"ic*al*ly, adv.",
  "drogue - See Drag, n., 6, and Drag sail, under Drag, n.",
  "deceptible - Capable of being deceived; deceivable. Sir T. Browne. -- De*cep`ti*bil\"i*ty (, n.",
  "scolopendrine - Like or pertaining to the Scolopendra.",
  "appropinquate - To approach. [Archaic] Ld. Lytton.",
  "eucrasy - Such a due mixture of qualities in bodies as constitutes health or soundness. Quincy.",
  "monothelitic - Of or pertaining to the Monothelites, or their doctrine.",
  "gerful - Changeable; capricious. [Obs.] Chaucer.",
  "stational - Of or pertaining to a station. [R.]",
  "succinic - Pertaining to, or derived from, amber; specif., designating a dibasic acid, C",
  "slish - A cut; as, slish and slash. [Colloq.] Shak.",
  "straight-spoken - Speaking with directness; plain-spoken. [Colloq. U.S.] Lowell.",
  "consolidative - Tending or having power to consolidate; healing.",
  "ordinately - In an ordinate manner; orderly. Chaucer. Skelton.",
  "poundrate - A rate or proportion estimated at a certain amount for each pound; poundage.",
  "light-winged - Having light and active wings; volatile; fleeting. Shak.",
  "yellow-eyed - Having yellow eyes. Yellow-eyed grass (Bot.), any plant of the genus Xyris.",
  "agronomical - Pertaining to agronomy, of the management of farms.",
  "glaucomatous - Having the nature of glaucoma.",
  "tetrical - Forward; perverse; harsh; sour; rugged. [Obs.] -- Tet\"ric*al*ness, n.",
  "anarthropodous - Having no jointed legs; pertaining to Anarthropoda.",
  "achrooedextrin - Dextrin not colorable by iodine. See Dextrin.",
  "grouty - Cross; sulky; sullen. [Colloq.]",
  "sax - A kind of chopping instrument for trimming the edges of roofing slates.",
  "explanate - Spreading or extending outwardly in a flat form.",
  "deosculate - To kiss warmly. [Obs.] -- De*os`cu*la\"tion, n. [Obs.]",
  "upbrought - Brought up; educated. [Obs.] Spenser.",
  "allegro - Brisk, lively. -- n.  An allegro movement; a quick, sprightly strain or piece.",
  "nucha - The back or upper part of the neck; the nape.",
  "chiragrical - Having the gout in the hand, or subject to that disease. Sir. T. Browne.",
  "protrusile - Capable of being protruded or thrust out; protractile; protrusive.",
  "stifler - 1. One who, or that which, stifles. 2. (Mil.)  See Camouflet.",
  "devocation - A calling off or away. [R.] Hallywell.",
  "mulierosity - A fondness for women. [R.] Dr. H. More.",
  "metallifacture - The production and working or manufacture of metals. [R.] R. Park.",
  "conquadrate - To bring into a square. [R.] Ash.",
  "delayer - One who delays; one who lingers.",
  "countre- - Same as prefix Counter-. [Obs.]",
  "heathenize - To render heathen or heathenish. Firmin.",
  "belgard - A sweet or loving look. [Obs.] Spenser.",
  "outmanoeuvre - To surpass, or get an advantage of, in maneuvering; to outgeneral.",
  "suppute - To reckon; to compute; to suppose; to impute. [Obs.] Drayton.",
  "beerhouse - A house where malt liquors are sold; an alehouse.",
  "houri - A nymph of paradise; -- so called by the Mohammedans.",
  "pinfeathered - Having part, or all, of the feathers imperfectly developed.",
  "extractible - Capable of being extracted.",
  "histogeny - Same as Histogenesis. Dunglison.",
  "martyrization - Act of martyrizing, or state of being martyrized; torture. B. Jonson.",
  "chymification - The conversion of food into chyme by the digestive action of gastric juice.",
  "reassertion - A second or renewed assertion of the same thing.",
  "subsumable - Capable of being subsumed. J. B. Stallo.",
  "brachelytra - A group of beetles having short elytra, as the rove beetles.",
  "squalidness - Quality or state of being squalid."
]