export default [
  "haemaphaein - A brownish substance sometimes found in the blood, in cases of jaundice.",
  "redditive - Answering to an interrogative or inquiry; conveying a reply; as, redditive words.",
  "neurotomical - Of or pertaining to neurotomy.",
  "sharking - Petty rapine; trick; also, seeking a livelihood by shifts and dishonest devices.",
  "honey-tongued - Sweet speaking; persuasive; seductive. Shak.",
  "ignipotent - Presiding over fire; also, fiery. Vulcan is called the powerful ignipotent. Pope.",
  "luxive - Given to luxury; voluptuous. [Obs.]",
  "trisulcate - Having three furrows, forks, or prongs; having three grooves or sulci; three-grooved.",
  "isopod - Having the legs similar in structure; belonging to the Isopoda. -- n.  One of the Isopoda.",
  "tried - imp. & p. p. of Try. Also adj.  Proved; tested; faithful; trustworthy; as, a tried friend.",
  "surfman - One who serves in a surfboat in the life-saving service.",
  "anno domini - In the year of the Christian era; as, a. d. 1887.",
  "advisability - The quality of being advisable; advisableness.",
  "leanness - The condition or quality of being lean.",
  "prepubic - Situated in front of, or anterior to, the pubis; pertaining to the prepubis.",
  "eligibleness - The quality worthy or qualified to be chosen; suitableness; desirableness.",
  "myriacanthous - Having numerous spines, as certain fishes.",
  "camphretic - Pertaining to, or derived from camphor. [R.]",
  "lithophotography - Same as Photolithography.",
  "confessionist - One professing a certain faith. Bp. Montagu.",
  "pierian - Of or pertaining to Pierides or Muses. Drink deep, or taste not the Pierian spring. Pope.",
  "petitionarily - By way of begging the question; by an assumption. [R.] Sir T. Browne.",
  "breathlessness - The state of being breathless or out of breath.",
  "forpass - To pass by or along; to pass over. [Obs.] Spenser.",
  "marriageability - The quality or state of being marriageable.",
  "exantlate - To exhaust or wear out. [Obs.] \"Seeds . . . wearied or exantlated.\" Boyle.",
  "fugh - An exclamation of disgust; foh; faugh. Dryden.",
  "immoderately - In an immoderate manner; excessively.",
  "appetent - Desiring; eagerly desirous. [R.] Appetent after glory and renown. Sir G. Buck.",
  "unlink - To separate or undo, as links; to uncoil; to unfasten. Shak.",
  "unwild - To tame; to subdue. [Obs. & R.] Sylvester.",
  "fawn-colored - Of the color of a fawn; light yellowish brown.",
  "stirte - imp. of Start, v. i. & t. Chaucer.",
  "doorplane - A plane on a door, giving the name, and sometimes the employment, of the occupant.",
  "beamingly - In a beaming manner; radiantly.",
  "unlawed - Not having the claws and balls of the forefeet cut off; -- said of dogs.",
  "conning tower - The shotproof pilot house of a war vessel.",
  "horoscopist - One versed in horoscopy; an astrologer.",
  "tartarean - Of or pertaining to Tartarus; hellish.",
  "clubbable - Suitable for membership in a club; sociable. [Humorous.] G. W. Curtis.",
  "odorant - Yielding odors; fragrant. Holland.",
  "tidbit - A delicate or tender piece of anything eatable; a delicious morsel. [Written also titbit.]",
  "indestructibility - The quality of being indestructible.",
  "fustilarian - A low fellow; a stinkard; a scoundrel. [Obs.] Shak.",
  "musard - A dreamer; an absent-minded person. [Obs.] Rom. of R.",
  "ecgonine - A colorless, crystalline, nitrogenous base, obtained by the decomposition of cocaine.",
  "myelon - The spinal cord. (Sometimes abbrev. to myel.)",
  "coalitionist - One who joins or promotes a coalition; one who advocates coalition.",
  "confoundedly - Extremely; odiously; detestably. [Colloq.] \"Confoundedly sick.\" Goldsmith.",
  "upcaught - Seized or caught up. \" She bears upcaught a mariner away.\" Cowper.",
  "pudency - Modesty; shamefacedness. \"A pudency so rosy.\" Shak.",
  "bolty - An edible fish of the Nile (genus Chromis). [Written also bulti.]",
  "apertness - Openness; frankness. [Archaic]",
  "disapprovingly - In a disapproving manner.",
  "tuz - A lock or tuft of hair. [Obs.] Dryden.",
  "southwesterly - To ward or from the southwest; as, a southwesterly course; a southwesterly wind.",
  "acrolith - A statue whose extremities are of stone, the trunk being generally of wood. Elmes.",
  "phthalyl - The hypothetical radical of phthalic acid.",
  "uniphonous - Having but one sound, as the drum. [R.]",
  "phosphorogenic - Generating phosphorescence; as, phosphorogenic rays.",
  "disembowelment - The act of disemboweling, or state of being disemboweled; evisceration.",
  "flowage - An overflowing with water; also, the water which thus overflows.",
  "testable - 1. Capable of being tested or proved. 2. Capable of being devised, or given by will.",
  "coffle - A gang of negro slaves being driven to market.",
  "bloody-minded - Having a cruel, ferocious disposition; bloodthirsty. Dryden.",
  "magnificently - In a Magnificent manner.",
  "trapball - An old game of ball played with a trap. See 4th Trap, 4.",
  "dalmania - A genus of trilobites, of many species, common in the Upper Silurian and Devonian rocks.",
  "unmiter - To deprive of a miter; to depose or degrade from the rank of a bishop. Milton.",
  "dermobranchiata - A group of nudibranch mollusks without special gills.",
  "mundatory - Cleansing; having power to cleanse. [Obs.]",
  "perdurance - Long continuance. [Archaic]",
  "overlordship - Lordship or supremacy of a person or a people over others. J. R. Green.",
  "minatory - Threatening; menacing. Bacon.",
  "japanning - The art or act of varnishing in the Japanese manner.",
  "saintly - Like a saint; becoming a holy person. So dear to Heaven is saintly chastity. Milton.",
  "palapteryx - A large extinct ostrichlike bird of New Zealand.",
  "lustreless - Destitute of luster; dim; dull.",
  "didrachm - A two-drachma piece; an ancient Greek silver coin, worth nearly forty cents.",
  "hete - Variant of Hote. [Obs.] But one avow to greate God I hete. Chaucer.",
  "pentacrinin - A red and purple pigment found in certain crinoids of the genus Pentacrinus.",
  "vallancy - A large wig that shades the face. [Obs.]",
  "dramatis personae - The actors in a drama or play.",
  "temporization - The act of temporizing. Johnson.",
  "summery - Of or pertaining to summer; like summer; as, a summery day.",
  "unequity - Want of equity or uprightness; injustice; wickedness; iniquity. [Obs.] Wyclif.",
  "metapectin - A substance obtained from, and resembling, pectin, and occurring in overripe fruits.",
  "unshipment - The act of unshipping, or the state of being unshipped; displacement.",
  "slocken - To quench; to allay; to slake. See Slake. [Obs. or Scot.]",
  "osteolite - A massive impure apatite, or calcium phosphate.",
  "perfectibilian - A perfectionist. [R.] Ed. Rev.",
  "bathymetry - The art or science of sounding, or measuring depths in the sea.",
  "faulting - The state or condition of being faulted; the process by which a fault is produced.",
  "vituperator - One who vituperates, or censures abusively.",
  "misknow - To have a mistaken notion of or about. [Obs.] Bp. Hall.",
  "longanimity - Disposition to bear injuries patiently; forbearance; patience. Jer. Taylor.",
  "dilution - The act of diluting, or the state of being diluted. Arbuthnot.",
  "quinquereme - A galley having five benches or banks of oars; as, an Athenian quinquereme.",
  "crimple - To cause to shrink or draw together; to contract; to curl. [R.] Wiseman.",
  "hulking - Bulky; unwiedly. [R.] \"A huge hulking fellow.\" H. Brooke.",
  "forcipate - Like a pair of forceps; as, a forcipated mouth.",
  "nemaline - Having the form of threads; fibrous.",
  "calabarine - An alkaloid resembing physostigmine and occurring with it in the calabar bean.",
  "equestrienne - A woman skilled in equestrianism; a horsewoman.",
  "decasyllabic - Having, or consisting of, ten syllables.",
  "dimyarian - Like or pertaining to the Dimya. -- n.  One of the Dimya.",
  "maslach - An excitant containing opium, much used by the Turks. Dunglison.",
  "attemperament - A tempering, or mixing in due proportion.",
  "botchy - Marked with botches; full of botches; poorly done. \"This botchy business.\" Bp. Watson.",
  "rex - A king. To play rex, to play the king; to domineer. [Obs.]",
  "misadjustment - Wrong adjustment; unsuitable arrangement.",
  "myxoma - A tumor made up of a gelatinous tissue resembling that found in the umbilical cord.",
  "photologist - One who studies or expounds the laws of light.",
  "cerebritis - Inflammation of the cerebrum.",
  "misease - Want of ease; discomfort; misery. [Obs.] Chaucer.",
  "hotpressed - Pressed while heat is applied. See Hotpress, v. t.",
  "universalize - To make universal; to generalize. Coleridge.",
  "irretrievableness - The state or quality of being irretrievable.",
  "tarre - To set on, as a dog; to incite. [Obs.] Shak.",
  "gelatification - The formation of gelatin.",
  "biconvex - Convex on both sides; as, a biconvex lens.",
  "maskery - The dress or disguise of a maske [Obs.] Marston.",
  "ananthous - Destitute of flowers; flowerless.",
  "uliginous - Muddy; oozy; slimy; also, growing in muddy places. [R.] Woodward.",
  "achaian - Of or pertaining to Achaia in Greece; also, Grecian. -- n.  A native of Achaia; a Greek.",
  "guelphic - Of or pertaining to the family or the facttion of the Guelphs.",
  "rhizanthous - Producing flowers from a rootstock, or apparently from a root.",
  "leadsman - The man who heaves the lead. Totten.",
  "calvinist - A follower of Calvin; a believer in Calvinism.",
  "inexcitability - The quality of being inexcitable; insusceptibility to excitement.",
  "damningness - Tendency to bring damnation. \"The damningness of them [sins].\" Hammond.",
  "athermancy - Inability to transmit radiant; impermeability to heat. Tyndall.",
  "ossean - A fish having a bony skeleton; a teleost.",
  "ginshop - A shop or barroom where gin is sold as a beverage. [Colloq.]",
  "windowless - Destitute of a window. Carlyle.",
  "psychagogic - Attractive; persuasive. J. Morley.",
  "animous - Full of spirit; hot; vehement; resolute. [Obs.] Ash.",
  "epispore - The thickish outer coat of certain spores.",
  "metastoma - A median elevation behind the mouth in the arthropods.",
  "oxyphenol - A phenol, oxyphenic acid, and now pyrocatechin.",
  "cosmopolitical - Having the character of a cosmopolite. [R.] Hackluyt.",
  "anilinism - A disease due to inhaling the poisonous fumes present in the manufacture of aniline.",
  "postpositional - Of or pertaining to postposition.",
  "sentiently - In a sentient or perceptive way.",
  "gemmiferous - Producing gems or buds; (Biol.)  multiplying by buds.",
  "invertebrata - A comprehensive division of the animal kingdom, including all except the Vertebrata.",
  "crowdy - A thick gruel of oatmeal and milk or water; food of the porridge kind. [Scot.]",
  "involvement - The act of involving, or the state of being involved. Lew Wallace.",
  "particularist - One who holds to particularism. -- Par*tic`u*lar*is\"tic, a.",
  "procatarxis - The kindling of a disease into action; also, the procatarctic cause. Quincy.",
  "interphalangeal - Between phalanges; as, interphalangeal articulations.",
  "repugnate - To oppose; to fight against. [Obs.]",
  "nugation - The act or practice of trifling. [R.] Bacon.",
  "cuckoldom - The state of a cuckold; cuckolds, collectively. Addison.",
  "series turns - The turns in a series circuit.",
  "noneffective - 1. Not effective. 2. (Mil.)  Not fit or available for duty.",
  "bibliomaniac - One who has a mania for books. -- a.  Relating to a bibliomaniac.",
  "tear-falling - Shedding tears; tender. [Poetic] \"Tear-falling pity.\" Shak.",
  "broiling - Excessively hot; as, a broiling sun. -- n.  The act of causing anything to broil.",
  "indeprecable - Incapable or undeserving of being deprecated. Cockeram.",
  "phantasmal - Pertaining to, of the nature of, or resembling, a phantasm; spectral; illusive.",
  "collyrium - An application to the eye, usually an eyewater.",
  "outreign - To go beyond in reigning; to reign through the whole of, or longer than. [R.] Spenser.",
  "spree - A merry frolic; especially, a drinking frolic; a carousal. [Colloq.]",
  "ungear - To strip of gear; to unharness; to throw out of gear.",
  "insected - Pertaining to, having the nature of, or resembling, an insect. Howell.",
  "scutiferous - Carrying a shield or buckler.",
  "infandous - Too odious to be expressed or mentioned. [Obs.] Howell.",
  "hornwort - An aquatic plant (Ceratophyllum), with finely divided leaves.",
  "decrial - A crying down; a clamorous censure; condemnation by censure.",
  "unteam - To unyoke a team from. [R.] Jer. Taylor.",
  "celadon - A pale sea-green color; also, porcelain or fine pottery of this tint.",
  "gonosome - The reproductive zooids of a hydroid colony, collectively.",
  "frequentness - The quality of being frequent.",
  "heterotactous - Relating to, or characterized by, heterotaxy.",
  "senility - The quality or state of being senile; old age.",
  "crack-brained - Having an impaired intellect; whimsical; crazy. Pope.",
  "elogy - The praise bestowed on a person or thing; panegyric; eulogy.",
  "wheyface - One who is pale, as from fear.",
  "ornithotomy - The anatomy or dissection of birds.",
  "cauma - Great heat, as of the body in fever.",
  "improvisatory - Of or pertaining to improvisation or extemporaneous composition.",
  "spermophile - Any ground squirrel of the genus Spermophilus; gopher. See Illust. under Gopher.",
  "dowral - Of or relating to a dower. [R.]",
  "gardenly - Like a garden. [R.] W. Marshall.",
  "leucoethiops - An albino. [Also written leucoethiops.]",
  "kirked - Turned upward; bent. [Obs.] Rom. of R.",
  "vesting - Cloth for vests; a vest pattern.",
  "tripeman - A man who prepares or sells tripe.",
  "escutcheoned - Having an escutcheon; furnished with a coat of arms or ensign. Young.",
  "infantly - Like an infant. [Obs.] Beau. & Fl.",
  "manuduction - Guidance by the hand. [Obs.] Glanvill. South.",
  "assyriological - Of or pertaining to Assyriology; as, Assyriological studies.",
  "graduality - The state of being gradual; gradualness. [R.] Sir T. Browne.",
  "achromatize - To deprive of color; to make achromatic.",
  "ophiuran - Of or pertaining to the Ophiurioidea. -- n.  One of the Ophiurioidea.",
  "pentagynian - Of or pertaining to plants of the order Pentagyna; having five styles.",
  "staphyline - Of or pertaining to the uvula or the palate.",
  "superterrene - Being above ground, or above the earth. [R.]",
  "eddish - Aftermath; also, stubble and stubble field. See Arrish. [Eng.]",
  "scythewhet - Wilson's thrush; -- so called from its note. [Local, U.S.]",
  "postnate - Subsequent. \"The graces and gifts of the spirit are postnate.\" [Archaic] Jer. Taylor.",
  "semiflosculous - Having all the florets ligulate, as in the dandelion.",
  "overcrow - To crow, exult, or boast, over; to overpower. Spenser. Shak.",
  "megametre - In the metric system, one million meters, or one thousand kilometers.",
  "pullus - A chick; a young bird in the downy stage.",
  "absolutory - Serving to absolve; absolving. \"An absolutory sentence.\" Ayliffe.",
  "pleopod - One of the abdominal legs of a crustacean. See Illust. under Crustacea.",
  "anisospore - A sexual spore in which the sexes differ in size; -- opposed to isospore.",
  "hemitropy - Twin composition in crystals.",
  "cali - The tenth avatar or incarnation of the god Vishnu. [Written also Kali.]",
  "both-hands - A factotum. [R.] He is his master's both-hands, I assure you. B. Jonson.",
  "gladiole - A lilylike plant, of the genus Gladiolus; -- called also corn flag.",
  "enravishingly - So as to throw into ecstasy.",
  "hayfield - A field where grass for hay has been cut; a meadow. Cowper.",
  "combustibility - The quality of being combustible.",
  "compassed - Rounded; arched. [Obs.] She came . . . into the compassed window. Shak.",
  "splanchnotomy - The dissection, or anatomy, of the viscera.",
  "furfurine - A white, crystalline base, obtained indirectly from furfurol.",
  "unamiable - Not amiable; morose; ill-natured; repulsive. -- Un*a\"mi*a*bly, adv.",
  "trippet - A cam, wiper, or projecting piece which strikes another piece repeatedly.",
  "bookman - A studious man; a scholar. Shak.",
  "macco - A gambling game in vogue in the eighteenth century. Thackeray.",
  "pathetism - See Mesmerism. L. Sunderland.",
  "insouciance - Carelessness; heedlessness; thoughtlessness; unconcern.",
  "desiderable - Desirable. [R.] \"Good and desiderable things.\" Holland.",
  "migniard - Soft; dainty. [Obs.] B. Jonson.",
  "versicular - Of or pertaining to verses; designating distinct divisions of a writing.",
  "spruntly - In a sprunt manner; smartly; vigorously; youthfully. [Obs.] B. Jonson.",
  "palla - An oblong rectangular piece of cloth, worn by Roman ladies, and fastened with brooches.",
  "batrachophagous - Feeding on frogs. Quart. Rev.",
  "bookbindery - A bookbinder's shop; a place or establishment for binding books.",
  "unhonest - Dishonest; dishonorable. Ascham. -- Un*hon\"est*ly, adv. Udall.",
  "pronity - Proneness; propensity. [R.] Dr. H. More.",
  "church-haw - Churchyard. [Obs.] Chaucer.",
  "combiner - One who, or that which, combines.",
  "decomposable - Capable of being resolved into constituent elements.",
  "parchedness - The state of being parched.",
  "spiller - 1. One who, or that which, spills. 2. A kind of fishing line with many hooks; a boulter.",
  "oculist - One skilled in treating diseases of the eye.",
  "hockamore - A Rhenish wine. [Obs.] See Hock. Hudibras.",
  "anachronous - Containing an anachronism; anachronistic. -- An*ach\"ro*nous*ly, adv.",
  "synarthrodia - Synarthrosis. -- Syn`ar*thro\"di*al, a. Dunglison.",
  "atter - Poison; venom; corrupt matter from a sore. [Obs.] Holland.",
  "foge - The Cornish name for a forge used for smelting tin. Raymond",
  "acquitter - One who acquits or releases.",
  "proscript - 1. A proscription; a prohibition; an interdict. [R.] 2. One who is proscribed. [R.]",
  "tenemental - Of or pertaining to a tenement; capable of being held by tenants. Blackstone.",
  "bodle - A small Scotch coin worth about one sixth of an English penny. Sir W. Scott.",
  "chilostomatous - Of or pertaining to the Chilostoma.",
  "extinguishable - Capable of being quenched, destroyed, or suppressed.",
  "justiceable - Liable to trial in a court of justice. [Obs.] Hayward.",
  "crinel - A very fine, hairlike feather. Booth.",
  "pancratiast - One who engaged in the contests of the pancratium.",
  "maniacal - Affected with, or characterized by, madness; maniac. -- Ma*ni\"a*cal*ly, adv.",
  "scotograph - An instrument for writing in the dark, or without seeing. Maunder.",
  "semite - One belonging to the Semitic race. Also used adjectively. [Written also Shemite.]",
  "assembler - One who assembles a number of individuals; also, one of a number assembled.",
  "cretan - Pertaining to Crete, or Candia. -- n.  A native or inhabitant of Crete or Candia.",
  "phenolate - A compound of phenol analogous to a salt.",
  "gilttail - A yellow-tailed worm or larva.",
  "manqueller - A killer of men; a manslayer. [Obs.] Carew.",
  "dingle - A narrow dale; a small dell; a small, secluded, and embowered valley.",
  "uncurse - To free from a curse or an execration. Shak.",
  "bordeaux - Pertaining to Bordeaux in the south of France. -- n.  A claret wine from Bordeaux.",
  "sparage - Obs. or corrupt forms of Asparagus.",
  "taction - The act of touching; touch; contact; tangency. \"External taction.\" Chesterfield.",
  "tinet - Brushwood and thorns for making and repairing hedges. [Obs. Eng.]",
  "venditation - The act of setting forth ostentatiously; a boastful display. [Obs.] B. Jonson.",
  "plumply - Fully; roundly; plainly; without reserve. [Colloq.]",
  "electrically - In the manner of electricity, or by means of it; thrillingly.",
  "polestar - 1. Polaris, or the north star. See North star, under North. 2. A guide or director.",
  "xylogen - (a) (Bot.) Nascent wood; wood cells in a forming state. (b) Lignin.",
  "reflexly - In a reflex manner; reflectively.",
  "houve - A head covering of various kinds; a hood; a coif; a cap. [Obs.] Chaucer.",
  "thermoneutrality - Neutrality as regards heat effects.",
  "figulated - Made of potter's clay; molded; shaped. [R.] Johnson.",
  "strengthy - Having strength; strong. [Obs.]",
  "vanilloes - An inferior kind of vanilla, the pods of Vanilla Pompona.",
  "phantasmagorial - Of, relating to, or resembling phantasmagoria; phantasmagoric.",
  "plethorical - Plethoric. [R.] -- Ple*thor\"ic*al*ly, adv. Burke.",
  "manoscopy - The science of the determination of the density of vapors and gases.",
  "averruncation - 1. The act of averting. [Obs.] 2. Eradication. [R.] De Quincey.",
  "gowd - Gold; wealth. [Scot.] The man's the gowd for a' that. Burns.",
  "depopulator - One who depopulates; a dispeopler.",
  "incombustibility - The quality of being incombustible.",
  "proportionately - In a proportionate manner; with due proportion; proportionally.",
  "renewability - The quality or state of being renewable. [R.]",
  "pesage - A fee, or toll, paid for the weighing of merchandise.",
  "opiniative - Opinionative. Glanvill. -- O*pin\"ia*tive*ly, adv. -- O*pin\"ia*tive*ness, n.",
  "pennach - A bunch of feathers; a plume. [Obs.] Holland.",
  "rokelay - A short cloak. [Written also rockelay, rocklay, etc.] [Scot.]",
  "conservatrix - A woman who preserves from loss, injury, etc.",
  "curvity - The state of being curved; a bending in a regular form; crookedness. Holder.",
  "misconstruable - Such as can be misconstrued, as language or conduct. R. North.",
  "ozonizer - An apparatus or agent for the production or application of ozone.",
  "obsolesce - To become obsolescent. [R.] Fitzed. Hall.",
  "brahmanist - An adherent of the religion of the Brahmans.",
  "footprint - The impression of the foot; a trace or footmark; as, \"Footprints of the Creator.\"",
  "necessitied - In a state of want; necessitous. [Obs.] Shak.",
  "iodo- - A prefix, or combining from, indicating iodine as an ingredient; as, iodoform.",
  "angelophany - The actual appearance of an angel to man.",
  "pectinibranchiate - Having pectinated gills.",
  "unshape - To deprive of shape, or of proper shape; to disorder; to confound; to derange. [R.] Shak.",
  "amphitheatral - Amphitheatrical; resembling an amphitheater.",
  "smilodon - An extinct genus of saber-toothed tigers. See Mach.",
  "atones - Etym: [See At one.] [Obs.] Down he fell atones as a stone. Chaucer.",
  "liberticide - 1. The destruction of civil liberty. 2. A destroyer of civil liberty. B. F. Wade.",
  "shikari - A sportsman; esp., a native hunter. [India]",
  "filicic - Pertaining to, or derived from, ferns; as, filicic acid.",
  "cryptograph - Cipher; something written in cipher. \"Decipherers of cryptograph.\" J. Earle.",
  "somonce - A summons; a citation. [Obs.] Chaucer.",
  "tonsilotome - An instrument for removing the tonsils.",
  "overwhelming - Overpowering; irresistible. -- O`ver*whelm\"ing*ly, adv.",
  "coachmanship - Skill in driving a coach.",
  "flexile - Flexible; pliant; pliable; easily bent; plastic; tractable. Wordsworth.",
  "bosjesman - ; pl. Bosjesmans. [D. boschjesman.]  See Bushman.",
  "chamfron - The frontlet, or head armor, of a horse. [Written also champfrain and chamfrain.]",
  "gallied - Worried; flurried; frightened. Ham. Nav. Encyc.",
  "passive flight - Flight, such as gliding and soaring, accomplished without the use of motive power.",
  "dorp - A hamlet. \"A mean fishing dorp.\" Howell.",
  "olympianism - Worship of the Olympian gods, esp. as a dominant cult or religion.",
  "toxalbumin - Any of a class of toxic substances of protein nature; a toxin.",
  "petzite - A telluride of silver and gold, related to hessite.",
  "sciscitation - The act of inquiring; inquiry; demand. [Obs.] Bp. Hall.",
  "inconverted - Not turned or changed about. [R.] Sir T. Browne.",
  "veridical - Truth-telling; truthful; veracious. [R.] Carlyle.",
  "thracian - Of or pertaining to Thrace, or its people. -- n.  A native or inhabitant of Thrace.",
  "receptaculum - A receptacle; as, the receptaculum of the chyle.",
  "overwind - To wind too tightly, as a spring, or too far, as a hoisting rope on a drum.",
  "prenuncious - Announcing beforehand; presaging. [Obs.] Blount.",
  "tringoid - Of or pertaining to Tringa, or the Sandpiper family.",
  "vincibility - The quality or state of being vincible, vincibleness.",
  "elbowboard - The base of a window casing, on which the elbows may rest.",
  "misground - To found erroneously. \"Misgrounded conceit.\" Bp. Hall.",
  "prefecundatory - Of or pertaining to prefecundation.",
  "agriology - Description or comparative study of the customs of savage or uncivilized tribes.",
  "undam - To free from a dam, mound, or other obstruction. Dryden.",
  "malting - The process of making, or of becoming malt.",
  "abusively - In an abusive manner; rudely; with abusive language.",
  "chattiness - The quality of being chatty, or of talking easily and pleasantly.",
  "sparada - A small California surf fish (Micrometrus aggregatus); -- called also shiner.",
  "latitation - A lying in concealment; hiding. [Obs.]",
  "deterioration - The process of growing worse, or the state of having grown worse.",
  "high-souled - Having a high or noble spirit; honorable. E. Everett.",
  "phonetization - The act, art, or process of representing sounds by phonetic signs.",
  "deliverness - Nimbleness; agility. [Obs.]",
  "sea-gait - A long, rolling swell of the sea. Ham. Nav. Encyc.",
  "pregustant - Tasting beforehand; having a foretaste. [R.] Ed. Rev.",
  "telescopically - In a telescopical manner; by or with the telescope.",
  "tripetalous - Having three petals, or flower leaves; three-petaled.",
  "subgelatinous - Imperfectly or partially gelatinous.",
  "glaucescent - Having a somewhat glaucous appearance or nature; becoming glaucous.",
  "recliner - One who, or that which, reclines.",
  "photophone - An apparatus for the production of sound by the action of rays of light. A. G. Bell.",
  "dequantitate - To diminish the quantity of; to disquantity. [Obs.] Sir T. Browne.",
  "driveler - A slaverer; a slabberer; an idiot; a fool. [Written also driveller.]",
  "pardonableness - The quality or state of being pardonable; as, the pardonableness of sin. Bp. Hall.",
  "belting - The material of which belts for machinery are made; also, belts, taken collectively.",
  "adverbiality - The quality of being adverbial. Earle.",
  "hymenophore - That part of a fungus which is covered with the hymenium.",
  "rakishness - The quality or state of being rakish.",
  "colleterial - Of or pertaining to the colleterium of insects. R. Owen.",
  "spelter - Zinc; -- especially so called in commerce and arts.",
  "fop-doodle - A stupid or insignaficant fellow; a fool; a simpleton. [R.] Hudibras.",
  "correspondently - In a a corresponding manner; conformably; suitably.",
  "saneness - The state of being sane; sanity.",
  "ciliiform - Having the form of cilia; very fine or slender.",
  "plucked - Having courage and spirit. [R.]",
  "townlet - A small town. North Brit. Rev.",
  "ustion - The act of burning, or the state of being burned. [R.] Johnson.",
  "tabanus - A genus of blood sucking flies, including the horseflies.",
  "yttria - The oxide, Y2O3, or earth, of yttrium.",
  "uberous - Fruitful; copious; abundant; plentiful. [Obs.] Sir T. Herbert.",
  "planetoidal - Pertaining to a planetoid.",
  "sandish - Approaching the nature of sand; loose; not compact. [Obs.] Evelyn.",
  "enatation - A swimming out. [Obs.] Bailey.",
  "jansenism - The doctrine of Jansen regarding free will and divine grace.",
  "shellproof - Capable of resisting bombs or other shells; bombproof.",
  "stomatiferous - Having or producing stomata.",
  "pathematic - Of, pertaining to, or designating, emotion or suffering. [R.] Chalmers.",
  "piedouche - A pedestal of small size, used to support small objects, as busts, vases, and the like.",
  "hardpan - The hard substratum. Same as Hard pan, under Hard, a.",
  "fleshings - Flesh-colored tights, worn by actors dancers. D. Jerrold.",
  "dispurvey - To disfurnish; to strip. [Obs.] Heywood.",
  "retexture - The act of weaving or forming again. Carlyle.",
  "decerptible - That may be plucked off, cropped, or torn away. [Obs.] Bailey.",
  "chanfrin - The fore part of a horse's head.",
  "gnathotheca - The horney covering of the lower mandible of a bird.",
  "aporosa - A group of corals in which the coral is not porous; -- opposed to Perforata.",
  "trunnioned - Provided with trunnions; as, the trunnioned cylinder of an oscillating steam engine.",
  "cabriole - A curvet; a leap. See Capriole. The cabrioles which his charger exhibited. Sir W. Scott.",
  "topsoil - The upper layer of soil; surface soil.",
  "fleetings - A mixture of buttermilk and boiling whey; curds. [prov. Eng.] Wright.",
  "allegement - Allegation. [Obs.] With many complaints and allegements. Bp. Sanderson.",
  "indubitableness - The state or quality of being indubitable.",
  "insolubleness - The quality or state of being insoluble; insolubility. Boyle.",
  "deferential - Expressing deference; accustomed to defer.",
  "financially - In a dfinancial manner. Burke.",
  "pervicacity - Obstinacy; pervicaciousness. [Obs.] Bentley.",
  "mattoid - A person of congenitally abnormal mind bordering on insanity or degeneracy.",
  "diversifiability - The quality or capacity of being diversifiable. Earle.",
  "apepsy - Defective digestion, indigestion. Coxe.",
  "genealogize - To investigate, or relate the history of, descents.",
  "mystagogy - The doctrines, principles, or practice of a mystagogue; interpretation of mysteries.",
  "creamcake - A kind of cake filled with custard made of cream, eggs, etc.",
  "consomme - A clear soup or bouillion boiled down so as to be very rich.",
  "pernicion - Destruction; perdition. [Obs.] hudibras.",
  "cheng - A chinese reed instrument, with tubes, blown by the mouth.",
  "dresden ware - A superior kind of decorated porcelain made near Dresden in Saxony.",
  "cesser - a neglect of a tenant to perform services, or make payment, for two years.",
  "sax-tuba - A powerful instrument of brass, curved somewhat like the Roman buccina, or tuba.",
  "antepenult - The last syllable of a word except two, as -syl in monosyllable.",
  "siphoid - A siphon bottle. See under Siphon, n.",
  "arara - The palm (or great black) cockatoo, of Australia (Microglossus aterrimus).",
  "fumigator - One who, or that which, fumigates; an apparattus for fumigating.",
  "mingleable - That can be mingled. Boyle.",
  "feldspathic - Pertaining to, or consisting of, feldspar.",
  "paragraphistical - Of or relating to a paragraphist. [R.] Beau. & Fl.",
  "shiplet - A little ship. [R.] Holinshed.",
  "biliation - The production and excretion of bile.",
  "vugh - A cavity in a lode; -- called also vogle.",
  "pass-parole - An order passed from front to rear by word of mouth.",
  "dysury - Difficult or painful discharge of urine.",
  "orbitosphenoidal - Of or pertaining to the orbitosphenoid bone; orbitosphenoid.",
  "oriency - Brightness or strength of color. [R.] E. Waterhouse.",
  "complicant - Overlapping, as the elytra of certain beetles.",
  "black-mouthed - Using foul or scurrilous language; slanderous.",
  "toadhead - The golden plover. [Local, U.S.]",
  "envolume - To form into, or incorporate with, a volume. [R.]",
  "procrastinator - One who procrastinates, or defers the performance of anything.",
  "dislimn - To efface, as a picture. [Obs.] Shak.",
  "emperil - To put in peril. See Imperil. Spenser.",
  "intactible - Not perceptible to the touch.",
  "hagship - The state or title of a hag. Middleton.",
  "centering - Same as Center, n., 6. [Written also centring.]",
  "icteritious - Yellow; of the color of the skin when it is affected by the jaundice.",
  "ducatoon - A silver coin of several countries of Europe, and of different values.",
  "constraintive - Constraining; compulsory. [R.] \"Any constraintive vow.\" R. Carew.",
  "jermoonal - The Himalayan now partridge.",
  "buster - Something huge; a roistering blade; also, a spree. [Slang, U.S.] Bartlett.",
  "polyarchist - One who advocates polyarchy; -- opposed to monarchist. Cudworth.",
  "per diem - By the day; substantively (chiefly U. S.), an allowance or amount of so much by the day.",
  "serratirostral - Having a toothed bill, like that of a toucan.",
  "geocentrically - In a geocentric manner.",
  "schoolmate - A pupil who attends the same school as another.",
  "ridgerope - See Life line (a), under Life.",
  "slotting - The act or process of making slots, or mortises.",
  "zopilote - The urubu, or American black vulture.",
  "tabefaction - A wasting away; a gradual losing of flesh by disease.",
  "husked - 1. Covered with a husk. 2. Stripped of husks; deprived of husks.",
  "figurist - One who uses or interprets figurative expressions. Waterland.",
  "syncrisis - A figure of speech in which opposite things or persons are compared. Crabb.",
  "alow - Below; in a lower part. \"Aloft, and then alow.\" Dryden.",
  "acrasia - Excess; intemperance. [Obs. except in Med.] Farindon.",
  "insnarl - To make into a snarl or knot; to entangle; to snarl. [Obs.] Cotgrave.",
  "restagnant - Stagnant; motionless. [Obs.] Boyle.",
  "endophragma - A chitinous structure above the nervous cord in the thorax of certain Crustacea.",
  "accentuality - The quality of being accentual.",
  "fraternate - To fraternize; to hold fellowship. Jefferson.",
  "catchwater - A ditch or drain for catching water. See Catchdrain.",
  "natron - Native sodium carbonate. [Written also anatron.]",
  "aforetime - In time past; formerly. \"He prayed . . . as he did aforetime.\" Dan. vi. 10.",
  "countercaster - A caster of accounts; a reckoner; a bookkeeper; -- used conteptuously.",
  "prestriction - Obstruction, dimness, or defect of sight. [Obs.] Milton.",
  "anglify - To convert into English; to anglicize. Franklin. Darwin.",
  "coarsen - To make coarse or vulgar; as, to coarsen one's character. [R.] Graham.",
  "pumiceous - Of or pertaining to pumice; resembling pumice.",
  "broad seal - The great seal of England; the public seal of a country or state.",
  "orgiastic - Pertaining to, or of the nature of, orgies. Elton.",
  "manubial - Belonging to spoils; taken in war. [Obs.] Bailey.",
  "indoxylic - Of or pertaining to, or producing, indoxyl; as, indoxylic acid.",
  "sweatiness - Quality or state of being sweaty.",
  "opiated - 1. Mixed with opiates. 2. Under the influence of opiates.",
  "crebricostate - Marked with closely set ribs or ridges.",
  "subcrustaceous - Occurring beneath a crust or scab; as, a subcrustaceous cicatrization.",
  "hemimetabola - Those insects which have an incomplete metamorphosis.",
  "cutler - One who makes or deals in cutlery, or knives and other cutting instruments.",
  "epicranial - Pertaining to the epicranium; as epicranial muscles.",
  "cradleland - Land or region where one was cradled; hence, land of origin.",
  "supernatation - The act of floating on the surface of a fluid. Sir T. Browne.",
  "glossa - The tongue, or lingua, of an insect. See Hymenoptera.",
  "dissentiate - To throw into a state of dissent. [R.] Feltham.",
  "spurn-water - A channel at the end of a deck to restrain the water.",
  "guilloched - Waved or engine-turned. Mollett.",
  "paleontographical - Of or pertaining to the description of fossil remains.",
  "acumination - A sharpening; termination in a sharp point; a tapering point. Bp. Pearson.",
  "decisory - Able to decide or determine; having a tendency to decide. [R.]",
  "metromania - A mania for writing verses.",
  "self-consistency - The quality or state of being self-consistent.",
  "agriculturalist - An agriculturist (which is the preferred form.)",
  "good-by - Farewell; a form of address used at parting. See the last Note under By, prep. Shak.",
  "polt - A blow or thump. Halliwell. -- a.  Distorted. Pot foot, a distorted foot. Sir T. Herbert.",
  "quadrijugous - Pinnate, with four pairs of leaflets; as, a quadrijugous leaf.",
  "satrapy - The government or jurisdiction of a satrap; a principality. Milton.",
  "enwrapment - Act of enwrapping; a wrapping or an envelope. Shuckford.",
  "improbate - To disapprove of; to disallow. [Obs.]",
  "teachless - Not teachable. [R.] Shelley.",
  "saliaunce - Salience; onslaught. [Obs.] \"So fierce saliaunce.\" Spenser.",
  "daguerrean - Pertaining to Daguerre, or to his invention of the daguerreotype.",
  "gaillard - Gay; brisk; merry; galliard. Chaucer.",
  "collocution - A speaking or conversing together; conference; mutual discourse. Bailey.",
  "coralloid - Having the form of coral; branching like coral.",
  "croisade - A holy war; a crusade. [Obs.] Bacon.",
  "misconstruct - To construct wrongly; to construe or interpret erroneously.",
  "deposal - The act of deposing from office; a removal from the throne. Fox.",
  "corrodible - Capable of being corroded; corrosible. Sir T. Browne.",
  "meadowy - Of or pertaining to meadows; resembling, or consisting of, meadow.",
  "sparable - A kind of small nail used by shoemakers.",
  "syphilologist - One skilled in syphilology.",
  "palanka - A camp permanently intrenched, attached to Turkish frontier fortresses.",
  "boniness - The condition or quality of being bony.",
  "gorgonzola - A kind of Italian pressed milk cheese; -- so called from a village near Milan.",
  "inconsiderately - In an inconsiderate manner.",
  "humectate - To moisten; to wet. [Obs.] Howell.",
  "plaiter - One who, or that which, plaits.",
  "mugil - A genus of fishes including the gray mullets. See Mullet.",
  "inerrably - With security from error; infallibly; unerringly.",
  "transpositive - Made by transposing; consisting in transposition; transposable.",
  "quixotry - Quixotism; visionary schemes.",
  "friabiiity - The quality of being friable; friableness. Locke.",
  "lardoon - A bit of fat pork or bacon used in larding.",
  "epispermic - Pertaining, or belonging, to the episperm, or covering of a seed.",
  "omniparous - Producing all things; omniparient.",
  "somnifugous - Driving away sleep. [Obs.]",
  "dodecagon - A figure or polygon bounded by twelve sides and containing twelve angles.",
  "crunkle - To cry like a crane. [Obs.] \"The crane crunketh.\" Withals (1608).",
  "hippodame - A fabulous sea monster. [Obs.] Spenser.",
  "deccagynous - Belonging to the Decagynia; having ten styles.",
  "impolitical - Impolitic. [Obs.] -- Im`po*lit\"i*cal*ly, adv. [Obs.] Bacon.",
  "uncovenable - Not covenable; inconvenient. [Obs.] Wyclif (1 Tim. iv. 7).",
  "fixedly - In a fixed, stable, or constant manner.",
  "particularization - The act of particularizing. Coleridge.",
  "anomophyllous - Having leaves irregularly placed.",
  "moulten - Having molted. [Obs.] \"A moulten raven.\" Shak.",
  "roytelet - A little king. [Archaic] Heylin. Bancroft.",
  "unsimplicity - Absence of simplicity; artfulness. C. Kingsley.",
  "bright-harnessed - Having glittering armor. [Poetic] Milton.",
  "stylommatophorous - Of or pertaining to Stylommatophora.",
  "equatorially - So as to have motion or direction parallel to the equator.",
  "revoice - To refurnish with a voice; to refit, as an organ pipe, so as to restore its tone.",
  "peragrate - To travel over or through. [Obs.]",
  "upseek - To seek or strain upward. \"Upseeking eyes suffused with . . . tears.\" Southey.",
  "contentation - Content; satisfaction. [Obs.] Bacon.",
  "singultous - Relating to, or affected with, hiccough. Dunglison.",
  "basset hound - A small kind of hound with a long body and short legs, used as an earth dog.",
  "meropodite - The fourth joint of a typical appendage of Crustacea.",
  "aflat - Level with the ground; flat. [Obs.] Bacon.",
  "chrysaurin - An orange-colored dyestuff, of artificial production.",
  "guardless - Without a guard or defense; unguarded. Chapman.",
  "monophyllous - One-leaved; composed of a single leaf; as, a monophyllous involucre or calyx.",
  "trinal - Threefold. \"Trinal unity.\" Milton. In their trinal triplicities on high. Spenser.",
  "outring - To excel in volume of ringing sound; to ring louder than.",
  "commodiously - In a commodious manner. To pass commodiously this life. Milton.",
  "place-proud - Proud of rank or office. Beau. & Fl.",
  "naturity - The quality or state of being produced by nature. [Obs.] Sir T. Browne.",
  "brike - A breach; ruin; downfall; peril. [Obs.] Chaucer.",
  "horometer - An instrument for measuring time.",
  "rodeo - A round-up. See Round-up. [Western U.S.]",
  "quincewort - The squinancy. Called also quinsywort.",
  "rockweed - Any coarse seaweed growing on sea-washed rocks, especially Fucus.",
  "antecedency - The state or condition of being antecedent; priority. Fothherby.",
  "incitative - A provocative; an incitant; a stimulant. [R.] Jervas.",
  "greek calends - A time that will never come, as the Greeks had no calends.",
  "divertisement - Diversion; amusement; recreation. [R.]",
  "rescindment - The act of rescinding; rescission.",
  "anchoretical - Pertaining to an anchoret or hermit; after the manner of an anchoret.",
  "foursquare - Having four sides and four equal angles. Sir W. Raleigh.",
  "comtist - A disciple of Comte; a positivist.",
  "obeyer - One who yields obedience. Holland.",
  "slasher - A machine for applying size to warp yarns.",
  "tungusic - Of or pertaining to the Tunguses; as, the Tungusic dialects.",
  "wye - 1. The letter Y. 2. A kind of crotch. See Y, n. (a).",
  "thread-shaped - Having the form of a thread; filiform.",
  "apostolicalness - Apostolicity. Dr. H. More.",
  "embank - To throw up a bank so as to confine or to defend; to protect by a bank of earth or stone.",
  "dissenterism - The spirit or principles of dissenters. Ed. Rev.",
  "touch-me-not - (a) See Impatiens. (b) Squirting cucumber. See under Cucumber.",
  "martinetism - The principles or practices of a martinet; rigid adherence to discipline, etc.",
  "visne - Neighborhood; vicinity; venue. See Venue.",
  "erigible - Capable of being erected. [Obs.]",
  "callid - Characterized by cunning or shrewdness; crafty. [R.]",
  "forstall - To forestall. [Obs.] Spenser.",
  "ommateal - Of or pertaining to an ommateum.",
  "great-grandson - A son of one's grandson or granddaughter.",
  "kiln-dry - To dry in a kiln; as, to kiln-dry meal or grain. Mortimer.",
  "brazenface - An impudent of shameless person. \"Well said, brazenface; hold it out.\" Shak.",
  "brahmin-ical - Of or pertaining to the Brahmans or to their doctrines and worship.",
  "americanization - The process of Americanizing.",
  "consignatary - A consignee. [Obs.] Jenkins.",
  "hard-favoredness - Coarseness of features.",
  "arithmancy - Divination by means of numbers.",
  "inexplicability - The quality or state of being inexplicable. H. Spencer.",
  "curacy - The office or employment of a curate.",
  "chincha - A south American rodent of the genus Lagotis.",
  "epiplastron - One of the first pair of lateral plates in the plastron of turtles.",
  "tapeti - A small South American hare (Lepus Braziliensis).",
  "acutilobate - Having acute lobes, as some leaves.",
  "wallah - A black variety of the jaguar; -- called also tapir tiger. [Written also walla.]",
  "bismuthinite - Native bismuth sulphide; -- sometimes called bismuthite.",
  "dernly - Secretly; grievously; mournfully. [Obs.] Spenser.",
  "eval - Relating to time or duration. [Obs.]",
  "quadragesimals - Offerings formerly made to the mother church of a diocese on Mid-Lent Sunday.",
  "irreclaimable - Incapable of being reclaimed. Addison. -- Ir`re*claim\"a*bly, ad",
  "furore - Excitement; commotion; enthusiasm.",
  "indivinity - Want or absence of divine power or of divinity. [Obs.] Sir T. Browne.",
  "securiform - Having the form of an ax hatchet.",
  "expeditionary - Of or pertaining to an expedition; as, an expeditionary force.",
  "exilement - Banishment. [R.] Sir. H. Wotton.",
  "backs - Among leather dealers, the thickest and stoutest tanned hides.",
  "evangelicalism - Adherence to evangelical doctrines; evangelism. G. Eliot.",
  "worral - An Egyptian fork-tongued lizard, about four feet long when full grown.",
  "plenish - 1. To replenish. [Obs.] T. Reeve. 2. To furnish; to stock, as a house or farm. [Scot.]",
  "siccation - The act or process of drying. [R.] Bailey.",
  "bavaroy - A kind of cloak or surtout. [Obs.] Johnson. Let the looped bavaroy the fop embrace. Gay.",
  "horopteric - Of or pertaining to the horopter.",
  "insabbatati - The Waldenses; -- so called from their peculiary cut or marked sabots, or shoes.",
  "overforward - Forward to excess; too forward. -- O\"ver*for\"ward*ness, n.",
  "cryptogamian - Of or pertaining to the series Cryptogamia, or to plants of that series.",
  "whiskyfied - Drunk with whisky; intoxicated. [Humorous] Thackeray.",
  "tricot - A fabric of woolen, silk, or cotton knitted, or women to resemble knitted work.",
  "obstancy - Opposition; impediment; obstruction. [Obs.] B. Jonson.",
  "trawlerman - A fisherman who used unlawful arts and engines to catch fish. [Obs.] Cowell.",
  "labioplasty - A plastic operation for making a new lip, or for replacing a lost tissue of a lip.",
  "dacian - Of or pertaining to Dacia or the Dacians. -- n.  A native of ancient Dacia.",
  "solvableness - Quality of being solvable.",
  "pulverulence - The state of being pulverulent; abundance of dust or powder; dustiness.",
  "charneco - A sort of sweet wine. [Obs.] Shak.",
  "egling - The European perch when two years old. [Prov. Eng.]",
  "lacklustre - A want of luster. -- a.  Wanting luster or brightness. \"Lackluster eye.\" Shak.",
  "temulency - Intoxication; inebriation; drunkenness. [R.] \"Their temulency.\" Jer. Taylor.",
  "visionless - Destitute of vision; sightless.",
  "overmanner - In an excessive manner; excessively. [Obs.] Wiclif.",
  "indicia - Discriminating marks; signs; tokens; indications; appearances. Burrill.",
  "scorpiones - A division of arachnids comprising the scorpions.",
  "meandrina - A genus of corals with meandering grooves and ridges, including the brain corals.",
  "oceanology - That branch of science which relates to the ocean.",
  "blaster - One who, or that which, blasts or destroys.",
  "otocranial - Of or pertaining to the otocrane.",
  "astragaloid - Resembling the astragalus in form.",
  "penicil - A tent or pledget for wounds or ulcers.",
  "rab - A rod or stick used by masons in mixing hair with mortar.",
  "unriddler - One who unriddles. Lovelace.",
  "loading - 1. The act of putting a load on or into. 2. A load; cargo; burden. Shak.",
  "elegiast - One who composes elegies. Goldsmith.",
  "floriage - Bloom; blossom. [Obs.] J. Scott.",
  "cheeky - a Brazen-faced; impudent; bold. [Slang.]",
  "gibingly - In a gibing manner; scornfully.",
  "robe-de-chambre - A dressing gown, or morning gown.",
  "monolith - A single stone, especially one of large size, shaped into a pillar, statue, or monument.",
  "moile - A kind of high shoe anciently worn. [Written also moyle.]",
  "ecbole - A digression in which a person is introduced speaking his own words.",
  "reiterant - Reiterating. [R.] Mrs. Browning.",
  "coercitive - Coercive. \"Coercitive power in laws.\" Jer. Taylor.",
  "inconcussible - Not concussible; that cannot be shaken.",
  "sindi - A native of Sind, India, esp. one of the native Hindoo stock.",
  "acceptably - In an acceptable manner; in a manner to please or give satisfaction.",
  "cysticule - An appendage of the vestibular ear sac of fishes. Owen.",
  "ahem - An exclamation to call one's attention; hem.",
  "levyne - A whitish, reddish, or yellowish, transparent or translucent mineral, allied to chabazite.",
  "polluted - Defiled; made unclean or impure; debauched. -- Pol*lut\"ed*ly, adv. -- Pol*lut\"ed*ness, n.",
  "judaically - After the Jewish manner. Milton.",
  "mugwumpery - The acts and views of the mugwumps. [Political Cant, U.S.]",
  "sherardize - To subject to the process of vapor galvanizing (which see, below).",
  "precipitantly - With rash or foolish haste; in headlong manner. Milton.",
  "disablement - Deprivation of ability; incapacity. Bacon.",
  "shelterless - Destitute of shelter or protection. Now sad and shelterless perhaps she lies. Rowe.",
  "reposed - Composed; calm; tranquil; at rest. Bacon. -- Re*pos\"ed*ly (r, adv. -- Re*pos\"ed*ness, n.",
  "uninfringible - That may not be infringed; as, an uninfringible monopoly.",
  "cerographic - Of or pertaining to cerography.",
  "antiputrescent - Counteracting, or preserving from, putrefaction; antiseptic.",
  "monstrance - A transparent pyx, in which the consecrated host is exposed to view.",
  "deludable - Capable of being deluded; liable to be imposed on gullible. Sir T. Browne.",
  "inanimated - Destitute of life; lacking animation; unanimated. Pope.",
  "dottard - An old, decayed tree. [R.] Bacon.",
  "comatulid - Any crinoid of the genus Antedon or allied genera.",
  "kemps - The long flower stems of the ribwort plantain (Plantago Lanceolata). Dr. Prior.",
  "abature - Grass and sprigs beaten or trampled down by a stag passing through them. Crabb.",
  "globy - Resembling, or pertaining to, a globe; round; orbicular. \"The globy sea.\" Milton.",
  "rhachidian - Of or pertaining to the rhachis; as, the rhachidian teeth of a mollusk.",
  "admaxillary - Near to the maxilla or jawbone.",
  "cobiron - An andiron with a knob at the top. Bacon.",
  "coterminous - Bordering; conterminous; -- followed by with.",
  "anemograph - An instrument for measuring and recording the direction and force of the wind. Knight.",
  "fairily - In the manner of a fairy. Numerous as shadows haunting fairily The brain. Keats.",
  "sanctionary - Of, pertaining to, or giving, sanction.",
  "sand-blind - Having defective sight; dim-sighted; purblind. Shak.",
  "thalassography - The study or science of the life of marine organisms. Agassiz.",
  "enschedule - To insert in a schedule. See Schedule. [R.] Shak.",
  "compages - A system or structure of many parts united. A regular compages of pipes and vessels. Ray.",
  "interfluous - Flowing between or among; intervening. Boyle.",
  "immanity - The state or quality of being immane; barbarity. [R.] Shak.",
  "gesticulatory - Representing by, or belonging to, gestures. T. Warton.",
  "amitotic - Of or pertaining to amitosis; karyostenotic; -- opposed to mitotic.",
  "adverbially - In the manner of an adverb.",
  "rigidness - The quality or state of being rigid.",
  "cubicle - A loding room; esp., a sleeping place partitioned off from a large dormitory.",
  "knurled - 1. Full of knots; gnarled. 2. Milled, as the head of a screw, or the edge of a coin.",
  "acaroid - Shaped like or resembling a mite.",
  "besee - To see; to look; to mind. [Obs.] Wyclif.",
  "ambrite - A fossil resin occurring in large masses in New Zealand.",
  "nymphiparous - Producing pupas or nymphs.",
  "intermittence - Act or state of intermitting; intermission. Tyndall.",
  "inmew - To inclose, as in a mew or cage. [R.] \"Inmew the town below.\" Beau. & Fl.",
  "semi pupa - The young of an insect in a stage between the larva and pupa.",
  "quadruplication - The act of making fourfold; a taking four times the simple sum or amount.",
  "dimit - To dismiss, let go, or release. [Obs.]",
  "disassimilate - To subject to disassimilation.",
  "offshore - From the shore; as, an offshore wind; an offshore signal.",
  "abjudicate - To reject by judicial sentence; also, to abjudge. [Obs.] Ash.",
  "bosa - A drink, used in the East. See Boza.",
  "chaperonage - Attendance of a chaperon on a lady in public; protection afforded by a chaperon.",
  "admonitorial - Admonitory. [R.] \"An admonitorial tone.\" Dickens.",
  "accorporate - To unite; to attach; to incorporate. [Obs.] Milton.",
  "aleuromancy - Divination by means of flour. Encyc. Brit.",
  "resisting - Making resistance; opposing; as, a resisting medium. -- Re*sist\"ing ly, adv.",
  "actinal - Pertaining to the part of a radiate animal which contains the mouth. L. Agassiz.",
  "uncoach - To detach or loose from a coach. [Obs.] Chapman.",
  "cunette - A drain trench, in a ditch or moat; -- called also cuvette.",
  "imprevalency - Want of prevalence. [Obs.]",
  "sea daffodil - A European amarylidaceous plant (Pancratium maritimum).",
  "autarchy - Self-sufficiency. [Obs.] Milton.",
  "sny - An upward bend in a piece of timber; the sheer of a vessel.",
  "toxemia - Blood poisoning. See under Blood.",
  "improsperity - Want of prosperity. [Obs.]",
  "noter - 1. One who takes notice. 2. An annotator. [Obs.]",
  "athetize - To set aside or reject as spurious, as by marking with an obelus.",
  "hammerkop - A bird of the Heron family; the umber.",
  "ecphonema - A breaking out with some interjectional particle.",
  "goliath beetle - Any species of Goliathus, a genus of very large and handsome African beetles.",
  "stakeholder - The holder of a stake; one with whom the bets are deposited when a wager is laid.",
  "unrightwise - Unrighteous. [Obs.] Wyclif. -- Un*right\"wise`ly, adv. [Obs.]",
  "suppuration - 1. The act or process of suppurating. 2. The matter produced by suppuration; pus.",
  "zooegamy - The sexual reproduction of animals.",
  "neurism - Nerve force. See Vital force, under Vital.",
  "corymbose - Consisting of corymbs, or resembling them in form. [Written also corymbous.]",
  "semiformed - Half formed; imperfectly formed; as, semiformed crystals.",
  "obvert - To turn toward. If its base be obverted towards us. I. Watts.",
  "imperilment - The act of imperiling, or the state of being imperiled.",
  "towered - Adorned or defended by towers. Towered cities please us then. Milton.",
  "worn-out - Consumed, or rendered useless, by wearing; as, worn-out garments.",
  "smothery - Tending to smother; stifling.",
  "catstick - A stick or club employed in the game of ball called cat or tipcat. Massinger.",
  "shipwright - One whose occupation is to construct ships; a builder of ships or other vessels.",
  "disadvantageable - Injurious; disadvantageous. [Obs.] Bacon.",
  "collybist - A money changer. [Obs.] In the face of these guilty collybists. Bp. Hall.",
  "infiniteness - The state or quality of being infinite; infinity; greatness; immensity. Jer. Taylor.",
  "dreibund - A triple alliance; specif., the alliance of Germany, Austria, and Italy, formed in 1882.",
  "foxship - Foxiness; craftiness. [R.] Shak.",
  "supralunary - Beyond the moon; hence, very lofty.",
  "subcordate - Somewhat cordate; somewhat like a heart in shape.",
  "resorb - To swallow up. Now lifted by the tide, and now resorbed. Young.",
  "hirs - Hers; theirs. See Here, pron. [Obs.] Chaucer.",
  "tyrannish - Like a tyrant; tyrannical. [Obs.] \"The proud tyrannish Roman.\" Gower.",
  "hektare - Same as Hectare, Hectogram, Hectoliter, and Hectometer.",
  "heretoch - The leader or commander of an army; also, a marshal. Blackstone.",
  "atmidometer - An instrument for measuring the evaporation from water, ice, or snow. Brande & C.",
  "tref - Ceremonially unclean, according to the Jewish law; -- opposed to kosher.",
  "inexhalable - Incapable of being exhaled. [Obs.] Sir T. Browne.",
  "chiromancer - One who practices chiromancy. Dryden.",
  "entheat - Divinely inspired. [Obs.] Drummond.",
  "bovid - Relating to that tribe of ruminant mammals of which the genus Bos is the type.",
  "cofferwork - Rubblework faced with stone. Knight.",
  "sigil - A seal; a signature. Dryden. Of talismans and sigils knew the power. Pope.",
  "dobbin - 1. An old jaded horse. Shak. 2. Sea gravel mixed with sand. [Prov. Eng.]",
  "bloomless - Without bloom or flowers. Shelley.",
  "pickpenny - A miser; also, a sharper. Dr. H. More.",
  "medicornu - The middle or inferior horn of each lateral ventricle of the brain. B. G. Wilder.",
  "ballastage - A toll paid for the privilege of taking up ballast in a port or harbor.",
  "recti- - A combining form signifying straight; as, rectilineal, having straight lines; rectinerved.",
  "hemipode - Any bird of the genus Turnix. Various species inhabit Asia, Africa, and Australia.",
  "dehonestation - A dishonoring; disgracing. [Obs.] Gauden.",
  "blandiloquence - Mild, flattering speech.",
  "pontage - A duty or tax paid for repairing bridges. Ayliffe.",
  "skieldrake - (a) The common European sheldrake. (b) The oyster catcher.",
  "papaverous - Of or pertaining to the poppy; of the nature of the poppy. Sir T. Browne.",
  "humectant - Diluent. -- n.  A diluent drink or medicine. [Obs.]",
  "perjurious - Guilty of perjury; containing perjury. [Obs.] Quarles. B. Johnson.",
  "bobbery - A squabble; a tumult; a noisy disturbance; as, to raise a bobbery. [Low] Halliwell.",
  "gastromyth - One whose voice appears to proceed from the stomach; a ventriloquist. [Obs.]",
  "frontingly - In a fronting or facing position; opposingly.",
  "inappealable - Not admitting of appeal; not appealable. Coleridge.",
  "radiophony - The art or practice of using the radiophone.",
  "chain tie - A tie consisting of a series of connected iron bars or rods.",
  "tetrapody - A set of four feet; a measure or distance of four feet.",
  "unconcluding - Inconclusive. [Obs.] Locke. -- Un`con*clud\"ing*ness, n. [Obs.] Jer. Taylor.",
  "heronshaw - A heron. [Written variously hernshaw, harnsey, etc.]",
  "bounder - One who, or that which, limits; a boundary. Sir T. Herbert.",
  "parochially - In a parochial manner; by the parish, or by parishes. Bp. Stillingfleet.",
  "atmologist - One who is versed in atmology.",
  "testudineous - Resembling the shell of a tortoise.",
  "woodhouse - A house or shed in which wood is stored, and sheltered from the weather.",
  "refractorily - In a refractory manner; perversely; obstinately.",
  "doubletree - The bar, or crosspiece, of a carriage, to which the singletrees are attached.",
  "frequenter - One who frequents; one who often visits, or resorts to customarily.",
  "docent - Serving to instruct; teaching. [Obs.]",
  "longipennes - A group of longwinged sea birds, including the gulls, petrels, etc.",
  "antilibration - A balancing; equipoise. [R.] De Quincey.",
  "grandevous - Of great age; aged; longlived. [R.] Bailey.",
  "kinsman - A man of the same race or family; one related by blood.",
  "newmarket - A long, closely fitting cloak.",
  "bisection - Division into two parts, esp. two equal parts.",
  "oneirocriticism - The art of interpreting dreams.",
  "altaian - Of or pertaining to the Altai, a mountain chain in Central Asia.",
  "dioeciousness - The state or quality of being dioecious.",
  "sulphaurate - A salt of sulphauric acid.",
  "quadricipital - Of or pertaining to the quadriceps.",
  "chromophotolithograph - A photolithograph printed in colors.",
  "respirable - Suitable for being breathed; adapted for respiration. -- Re*spir\"a*ble*ness, n.",
  "gemmiparity - Reproduction by budding; gemmation. See Budding.",
  "unflower - To strip of flowers. [R.] G. Fletcher.",
  "equitemporaneous - Contemporaneous. [Obs.] Boyle.",
  "air drill - A drill driven by the elastic pressure of condensed air; a pneumatic drill. Knight.",
  "saith - 3d pers. sing. pres. of Say. [Archaic]",
  "narrator - One who narrates; one who relates a series of events or transactions.",
  "correspondingly - In a corresponding manner; conformably.",
  "fletcher - One who fletches of feathers arrows; a manufacturer of bows and arrows. [Obs.] Mortimer.",
  "arbitrarily - In an arbitrary manner; by will only; despotically; absolutely.",
  "uxoricidal - Of or pertaining to uxoricide; tending to uxoricide.",
  "coralloidal - resembling coral; coralloid. Sir T. browne.",
  "asteriated - Radiated, with diverging rays; as, asteriated sapphire.",
  "ellwand - Formerly, a measuring rod an ell long.",
  "androphagi - Cannibals; man-eaters; anthropophagi. [R.]",
  "foresleeve - The sleeve below the elbow.",
  "forthcoming - Ready or about to appear; making appearance.",
  "interall - Entrail or inside. [Obs.] G. Fletcher.",
  "derail - To cause to run off from the rails of a railroad, as a locomotive. Lardner.",
  "brilliantness - Brilliancy; splendor; glitter.",
  "pearlaceous - Resembling pearl or mother-of-pearl; pearly in quality or appearance.",
  "proximally - On or toward a proximal part; proximad.",
  "chronographer - One who writes a chronography; a chronologer. Tooke.",
  "chronographic - Of or pertaining to a chronograph.",
  "turm - A troop; a company. [Obs. or Poetic] Legions and cohorts, turms of horse and wings. Milton.",
  "trajet - See Treget, Tregetour, and Tregetry. [Obs.]",
  "traditionist - One who adheres to tradition.",
  "extermine - To exterminate; to destroy. [Obs.] Shak.",
  "impedible - Capable of being impeded or hindered. [R.] Jer. Taylor.",
  "trochaical - Of or pertaining to trochees; consisting of trochees; as, trochaic measure or verse.",
  "cast-off - Cast or laid aside; as, cast-off clothes.",
  "brittlely - In a brittle manner. Sherwood.",
  "fibrilla - A minute thread of fiber, as one of the fibrous elements of a muscular fiber; a fibril.",
  "objectively - In the manner or state of an object; as, a determinate idea objectively in the mind.",
  "unsaintly - Unbecoming to a saint. Gauden.",
  "divisionor - One who divides or makes division. [Obs.] Sheldon.",
  "eudemonistic - Of or pertaining to eudemonism.",
  "crimpage - The act or practice of crimping; money paid to a crimp for shipping or enlisting men.",
  "specificalness - The quality of being specific.",
  "catechumenate - The state or condition of a catechumen or the time during which one is a catechumen.",
  "nonterm - A vacation between two terms of a court.",
  "diversifier - One who, or that which, diversifies.",
  "ichthyopterygium - The typical limb, or lateral fin, of fishes.",
  "briefman - 1. One who makes a brief. 2. A copier of a manuscript.",
  "antihydropic - Good against dropsy. -- n.  A remedy for dropsy.",
  "bull fly - Any large fly troublesome to cattle, as the gadflies and breeze flies.",
  "transcendentalist - One who believes in transcendentalism.",
  "dotery - The acts or speech of a dotard; drivel. [R.]",
  "appete - To seek for; to desire. [Obs.] Chaucer.",
  "retuse - Having the end rounded and slightly indented; as, a retuse leaf.",
  "unruinate - Not ruined or destroyed. [Obs.] \"Unruinated towers.\" Bp. Hall.",
  "inobtrusive - Not obtrusive; unobtrusive. -- In`ob*tru\"sive*ly, adv. -- In`ob*tru\"sive*ness, n.",
  "likerous - See Lickerish, Lickerishness. Chaucer.",
  "revamp - To vamp again; hence, topatch up; to reconstruct.",
  "sudoral - Of or pertaining to sweat; as, sudoral eruptions.",
  "atramentaceous - Black, like ink; inky; atramental. [Obs.] Derham.",
  "woefulness - The quality or state of being woeful; misery; wretchedness.",
  "pince-nez - Eyeglasses kept on the nose by a spring.",
  "heartshaped - Having the shape of a heart; cordate.",
  "bransle - A brawl or dance. [Obs.] Spenser.",
  "hemisect - To divide along the mesial plane.",
  "self-discipline - Correction or government of one's self for the sake of improvement.",
  "lacrytory - See Lachrymary, Lachrymatory, Lachrymose.",
  "arose - The past or preterit tense of Arise.",
  "inerratic - Not erratic or wandering; fixed; settled; established.",
  "intercur - To intervene; to come or occur in the meantime. [Obs.] Shelton.",
  "molto - Much; very; as, molto adagio, very slow.",
  "omphalopter - An optical glass that is convex on both sides. [Obs.] Hutton.",
  "biform - Having two forms, bodies, or shapes. Croxall.",
  "woofell - The European blackbird. \"The woofell near at hand that hath a golden bill.\" Drayton.",
  "heresiarch - A leader in heresy; the chief of a sect of heretics. Bp. Stillingfleet.",
  "prairie state - Illinois; -- a nickname.",
  "fremescent - Becoming murmurous, roaring. \"Fremescent clangor.\" Carlyle. -- Fre*mes\"cence (#), n.",
  "whole-hoofed - Having an undivided hoof, as the horse.",
  "wheelman - One who rides a bicycle or tricycle; a cycler, or cyclist.",
  "antepone - To put before; to prefer. [Obs.] Bailey.",
  "albescent - Becoming white or whitish; moderately white.",
  "daybreak - The time of the first appearance of light in the morning.",
  "indeciduate - 1. Indeciduous. 2. (Anat.)  Having no decidua; nondeciduate.",
  "self-indulgent - Indulging one's appetites, desires, etc., freely.",
  "muezzin - A Mohammedan crier of the hour of prayer. [Written also mouezzin, mueddin, and muwazzin.]",
  "caulocarpous - Having stems which bear flowers and fruit year after year, as most trees and shrubs.",
  "fauvette - A small singing bird, as the nightingale and warblers.",
  "graphitoidal - Resembling graphite or plumbago.",
  "intracolic - Within the colon; as, the intracolic valve.",
  "tapadero - One of the leather hoods which cover the stirrups of a Mexican saddle.",
  "isography - Imitation of another's handwriting,",
  "truncus - The thorax of an insect. See Trunk, n., 5.",
  "enpatron - To act the part of a patron towards; to patronize. [Obs.] Shak.",
  "poraille - Poor people; the poor. [Obs.] Chaucer.",
  "alliciency - Attractive power; attractiveness. [Obs.] Sir T. Browne.",
  "colstaff - A staff by means of which a burden is borne by two persons on their shoulders.",
  "compellable - Capable of being compelled or constrained. Blackstone.",
  "structurist - One who forms structures; a builder; a constructor. [R.]",
  "epistolic - Pertaining to letters or epistles; in the form or style of letters; epistolary.",
  "cocoonery - A building or apartment for silkworms, when feeding and forming cocoons.",
  "misallegation - A erroneous statement or allegation. Bp. Hall.",
  "chapellany - A chapel within the jurisdiction of a church; a subordinate ecclesiastical foundation.",
  "toponomy - The designation of position and direction. B. G. Wilder.",
  "neurotome - 1. An instrument for cutting or dissecting nerves. 2. (Anat.)  A neuromere.",
  "obscurantist - Same as Obscurant. Ed. Rev.",
  "examinate - A person subjected to examination. [Obs.] Bacon.",
  "relicted - Left uncovered, as land by recession of water. Bouvier.",
  "incorrespondence - Want of correspondence; disagreement; disproportion. [R.]",
  "faience - Glazed earthenware; esp., that which is decorated in color.",
  "palestrical - Of or pertaining to the palestra, or to wrestling.",
  "feaster - 1. One who fares deliciously. 2. One who entertains magnificently. Johnson.",
  "guelfic - Of or pertaining to the family or the facttion of the Guelphs.",
  "bawbling - Insignificant; contemptible. [Obs.]",
  "metonymic - Used by way of metonymy. -- Met`o*nym\"ic*al*ly, adv.",
  "shrillness - The quality or state of being shrill.",
  "similor - An alloy of copper and zinc, resembling brass, but of a golden color. Ure.",
  "coparceny - An equal share of an inheritance.",
  "cobwebby - Abounding in cobwebs, or any fine web; resembling a cobweb.",
  "tergeminous - Threefold; thrice-paired. Blount.",
  "sastrugi - Incorrect, but common, var. of Zastrugi.",
  "debouchure - The outward opening of a river, of a valley, or of a strait.",
  "discontenting - 1. Discontented. [Obs.] Shak. 2. Causing discontent; dissatisfying. Milton.",
  "enlivener - One who, or that which, enlivens, animates, or invigorates.",
  "sciatically - With, or by means of, sciatica.",
  "defrayal - The act of defraying; payment; as, the defrayal of necessary costs.",
  "light-handed - Not having a full complement of men; as, a vessel light-handed.",
  "fondue - A dish made of cheese, eggs, butter, etc., melted together.",
  "gymnophiona - An order of Amphibia, having a long, annulated, snakelike body. See Ophiomorpha.",
  "high-bred - Bred in high life; of pure blood. Byron.",
  "rammishness - The quality of being rammish.",
  "kruppize - To treat by, or subject to, the Krupp process.",
  "ithyphallic - Lustful; lewd; salacious; indecent; obscene.",
  "undiscerning - Want of discernment. [R.] Spectator.",
  "labialization - The modification of an articulation by contraction of the lip opening.",
  "pesthouse - A house or hospital for persons who are infected with any pestilential disease.",
  "dolesome - Doleful; dismal; gloomy; sorrowful. -- Dole\"some*ly, adv. -- Dole\"some*ness, n.",
  "ebulliate - To boil or bubble up. [Obs.] Prynne.",
  "gimmor - A piece of mechanism; mechanical device or contrivance; a gimcrack. [Obs.] Bp. Hall. Shak.",
  "westminster assembly - See under Assembly.",
  "imaginariness - The state or quality of being imaginary; unreality.",
  "subpubic - Situated under, or posterior to, the pubic bones.",
  "depucelate - To deflour; to deprive of virginity. [Obs.] Bailey.",
  "pneumatogarm - A tracing of the respiratory movements, obtained by a pneumatograph or stethograph.",
  "prismatoidal - Having a prismlike form. Ure.",
  "funambulate - To walk or to dance on a rope.",
  "leptorhine - Having the nose narrow; -- said esp. of the skull. Opposed to platyrhine.",
  "peculiarness - The quality or state of being peculiar; peculiarity. Mede.",
  "rachidian - Of or pertaining to the rachis; spinal; vertebral. Same as Rhachidian.",
  "cardigan jacket - A warm jacket of knit worsted with or without sleeves.",
  "sincaline - Choline. [Written also sinkaline.]",
  "hydromantic - Of or pertaining to divination by water.",
  "insecution - A following after; close pursuit. [Obs.] Chapman.",
  "exegetist - One versed in the science of exegesis or interpretation; -- also called exegete.",
  "sexlocular - Having six cells for seeds; six-celled; as, a sexlocular pericarp.",
  "conferrer - 1. One who confers; one who converses. Johnson. 2. One who bestows; a giver.",
  "acceptive - 1. Fit for acceptance. 2. Ready to accept. [Obs.] B. Jonson.",
  "photogravure - A photoengraving; also, the process by which such a picture is produced.",
  "septuagenarian - A person who is seventy years of age; a septuagenary.",
  "cerographist - One who practices cerography.",
  "bewake - To keep watch over; to keep awake. [Obs.] Gower.",
  "euphorbial - Of, relating to, or resembling, the Euphorbia family.",
  "frisure - The dressing of the hair by crisping or curling. Smollett.",
  "unwrap - To open or undo, as what is wrapped or folded. Chaucer.",
  "levana - A goddess who protected newborn infants.",
  "disentanglement - The act of disentangling or clearing from difficulties. Warton.",
  "proclive - Having a tendency by nature; prone; proclivous. [R.] Mrs. Browning.",
  "pantomimist - An actor in pantomime; also, a composer of pantomimes.",
  "good-fellowship - Agreeable companionship; companionableness.",
  "overdrive - To drive too hard, or far, or beyond strength.",
  "cornu ammonis - A fossil shell, curved like a ram's horn; an obsolete name for an ammonite.",
  "slimly - In a state of slimness; in a slim manner; slenderly.",
  "nobby - Stylish; modish; elegant; showy; aristocratic; fashionable. [Slang]",
  "servantess - A maidservant. [Obs.] Wyclif.",
  "anamnestic - Aiding the memory; as, anamnestic remedies.",
  "discamp - To drive from a camp. [Obs.] Holland.",
  "outsport - To exceed in sporting. [R.] \"Not to outsport discretion.\" Shak.",
  "saccharomycetes - A family of fungi consisting of the one genus Saccharomyces.",
  "receptible - Such as may be received; receivable.",
  "ethylin - Any one of the several complex ethers of ethyl and glycerin.",
  "suppletive - Supplying deficiencies; supplementary; as, a suppletory oath.",
  "sinuation - A winding or bending in and out.",
  "nitroxyl - The group NO2, usually called the nitro group.",
  "filigreed - Adorned with filigree. Tatler.",
  "pated - Having a pate; -- used only in composition; as, long-pated; shallow-pated.",
  "interluency - A flowing between; intervening water. [Obs.] Sir M. Hale.",
  "antemeridian - Being before noon; in or pertaining to the forenoon. (Abbrev. a. m.)",
  "denominationalist - One imbued with a denominational spirit. The Century.",
  "canticoy - A social gathering; usually, one for dancing.",
  "emball - To encircle or embrace. [Obs.] Sir P. Sidney.",
  "forgetive - Inventive; productive; capable. [Obs.] Shak.",
  "stylomastoid - Of or pertaining to the styloid and mastoid processes of the temporal bone.",
  "involucel - A partial, secondary, or small involucre. See Illust. of Involucre.",
  "moosewood - (a) The striped maple (Acer Pennsylvanicum). (b) Leatherwood.",
  "significate - One of several things signified by a common term. Whately.",
  "exinanite - To make empty; to render of no effect; to humble. [Obs.] Bp. Pearson.",
  "fibrine - Belonging to the fibers of plants."
]