export default [
  "claudication - A halting or limping. [R.] Tatler.",
  "gurglet - A porous earthen jar for cooling water by evaporation.",
  "subgovernor - A subordinate or assistant governor.",
  "immoment - Trifling. [R.] \"Immoment toys.\" Shak.",
  "perfuncturate - To perform in a perfunctory manner; to do negligently. [R.]",
  "lodged - Lying down; -- used of beasts of the chase, as couchant is of beasts of prey.",
  "utriculate - Resembling a bladder; swollen like a bladder; inflated; utricular. Dana.",
  "cobaltine - A mineral of a nearly silver-white color, composed of arsenic, sulphur, and cobalt.",
  "stealthlike - Stealthy; sly. Wordsworth.",
  "swordsmanship - The state of being a swordsman; skill in the use of the sword. Cowper.",
  "benumbment - Act of benumbing, or state of being benumbed; torpor. Kirby.",
  "vanguard - The troops who march in front of an army; the advance guard; the van.",
  "territorially - In regard to territory; by means of territory.",
  "notate - Marked with spots or lines, which are often colored. Henslow.",
  "octaemeron - A fast of eight days before a great festival. Shipley.",
  "gustoso - Tasteful; in a tasteful, agreeable manner.",
  "renowme - Renown. [Obs.] The glory and renowme of the ancectors. Robynson (More's Utopia).",
  "crofter - One who rents and tills a small farm or helding; as, the crofters of Scotland.",
  "earthboard - The part of a plow, or other implement, that turns over the earth; the moldboard.",
  "depressive - Able or tending to depress or cast down. -- De*press\"ive*ness, n.",
  "octosyllabical - Consisting of or containing eight syllables.",
  "anecdotist - One who relates or collects anecdotes.",
  "palpebral - Of or pertaining to the eyelids.",
  "halation - An appearance as of a halo of light, surround the edges of dark object",
  "by-past - Past; gone by. \"By-past perils.\" Shak.",
  "two-sided - 1. Having two sides only; hence, double-faced; hypocritical. 2. (Biol.)  Symmetrical.",
  "atypic - That has no type; devoid of typical character; irregular; unlike the type.",
  "mira - A remarkable variable star in the constellation Cetus (o Ceti).",
  "chromospheric - Of or pertaining to the chromosphere.",
  "cashbook - A book in which is kept a register of money received or paid out.",
  "swarthiness - The quality or state of being swarthy; a dusky or dark complexion; tawniness.",
  "limitless - Having no limits; unbounded; boundless. Davies (Wit's Pilgr.).",
  "cottagely - Cottagelike; suitable for a cottage; rustic. [Obs.] Jer. Taylor.",
  "moria - Idiocy; imbecility; fatuity; foolishness.",
  "bardish - Pertaining to, or written by, a bard or bards. \"Bardish impostures.\" Selden.",
  "scholiaze - To write scholia. [Obs.] Milton.",
  "apteryges - An order of birds, including the genus Apteryx.",
  "distracting - Tending or serving to distract.",
  "gastritis - Inflammation of the stomach, esp. of its mucuos membrane.",
  "succulency - The quality or condition of being succulent; juiciness; as, the succulence of a peach.",
  "laminar - In, or consisting of, thin plates or layers; having the form of a thin plate or lamina.",
  "alternativeness - The quality of being alternative, or of offering a choice between two.",
  "denization - The act of making one a denizen or adopted citizen; naturalization. Hallam.",
  "gaure - To gaze; to stare. [Obs.] Chaucer.",
  "geth - the original third pers. sing. pres. of Go. [Obs.] Chaucer.",
  "lithocarp - Fossil fruit; a fruit petrified; a carpolite.",
  "nilotic - Of or pertaining to the river Nile; as, the Nilotic crocodile.",
  "orchitis - Inflammation of the testicles.",
  "imbiber - One who, or that which, imbibes.",
  "stinkweed - Stramonium. See Jamestown weed, and Datura.",
  "digestedly - In a digested or well-arranged manner; methodically.",
  "rabdoidal - See Sagittal. [Written also rhabdoidal.]",
  "turioniferous - Producing shoots, as asparagus. Barton.",
  "tapered - Lighted with a taper or tapers; as, a tapered choir. [R.] T. Warton.",
  "assecution - An obtaining or acquiring. [Obs.] Ayliffe.",
  "mayhap - Perhaps; peradventure. [Prov. or Dialectic]",
  "-mere - A combining form meaning part, portion; as, blastomere, epimere.",
  "yachter - One engaged in sailing a jacht.",
  "tided - Affected by the tide; having a tide. \"The tided Thames.\" Bp. Hall.",
  "stepper - One who, or that which, steps; as, a quick stepper.",
  "inconcinne - Dissimilar; incongruous; unsuitable. [Obs.] Cudworth.",
  "clothespin - A forked piece of wood, or a small spring clamp, used for fastening clothes on a line.",
  "septifluous - Flowing in seven streams; septemfluous.",
  "enterorrhaphy - The operation of sewing up a rent in the intestinal canal.",
  "clean-timbered - Well-propotioned; symmetrical. [Poetic] Shak.",
  "autokinetic - Self-moving; moving automatically.",
  "philatelist - One versed in philately; one who collects postage stamps.",
  "engagedly - With attachment; with interest; earnestly.",
  "arduously - In an arduous manner; with difficulty or laboriousness.",
  "monstrousness - The state or quality of being monstrous, unusual, extraordinary. Shak.",
  "homonomous - Of or pertaining to homonomy.",
  "whiteblow - Same as Whitlow grass, under Whitlow.",
  "dukeship - The quality or condition of being a duke; also, the personality of a duke. Massinger.",
  "arundinaceous - Of or pertaining to a reed; resembling the reed or cane.",
  "offensible - That may give offense. [Obs.]",
  "sacristy - A apartment in a church where the sacred utensils, vestments, etc., are kept; a vestry.",
  "imperviable - Not pervious; impervious. [R.] -- Im*per\"vi*a*ble*ness, n. [R.]",
  "perishably - In a perishable degree or manner.",
  "indiligent - Not diligent; idle; slothful. [Obs.] Feltham. -- In*dil\"i*gent*ly, adv. [Obs.]",
  "potassic - Pertaining to, or containing, potassium.",
  "guaiac - Pertaining to, or resembling, guaiacum. -- n. Guaiacum.",
  "prerequire - To require beforehand. Some things are prerequired of us. Bp. Hall.",
  "bunchiness - The quality or condition of being bunchy; knobbiness.",
  "disproval - Act of disproving; disproof. [R.]",
  "surling - A sour, morose fellow. [Obs.] Camden.",
  "fracid - Rotten from being too ripe; overripe. [Obs.] Blount.",
  "hydrated - Formed into a hydrate; combined with water.",
  "somniloquist - One who talks in his sleep.",
  "hail-fellow - An intimate companion. Hail-fellow well met. Lyly.",
  "bacchus - The god of wine, son of Jupiter and Semele.",
  "old-maidish - Like an old maid; prim; precise; particular.",
  "neatly - In a neat manner; tidily; tastefully.",
  "patricidal - Of or pertaining to patricide; parricidal.",
  "catalogize - To insert in a catalogue; to register; to catalogue. [R.] Coles.",
  "zosterops - A genus of birds that comprises the white-eyes. See White-eye.",
  "amacratic - Amasthenic. Sir J. Herschel.",
  "protogine - A kind of granite or gneiss containing a silvery talcose mineral.",
  "dumose - 1. Abounding with bushes and briers. 2. (Bot.)  Having a compact, bushy form.",
  "saxonist - One versed in the Saxon language.",
  "secretaryship - The office, or the term of office, of a secretary.",
  "gazet - A Venetian coin, worth about three English farthings, or one and a half cents. [Obs.]",
  "zooephilist - A lover of animals. Southey.",
  "forleave - To leave off wholly. [Obs.] Chaucer.",
  "septi- - A combining form meaning seven; as, septifolious, seven-leaved; septi-lateral, seven-sided.",
  "pistillation - The act of pounding or breaking in a mortar; pestillation. [Obs.] Sir T. Browne.",
  "committal - The act of commiting, or the state of being committed; commitment.",
  "exanimation - Deprivation of life or of spirits. [R.] Bailey.",
  "epistemology - The theory or science of the method or grounds of knowledge.",
  "pacifiable - Capable of being pacified or appeased; placable.",
  "objuration - A binding by oath. [R.] Abp. Bramhall.",
  "pontificality - The state and government of the pope; the papacy. [R.] Bacon.",
  "instaurator - One who renews or restores to a former condition. [R.] Dr. H. More.",
  "smear dab - The sand fluke (b). [Prov. Eng.]",
  "anient - To frustrate; to bring to naught; to annihilate. [Obs.] Chaucer.",
  "inclamation - Exclamation. [Obs.] Bp. Hall.",
  "phasma - An apparition; a phantom; an appearance. [R.] Hammond. Sir T. Herbert.",
  "pennigerous - Bearing feathers or quills.",
  "mulberry-faced - Having a face of a mulberry color, or blotched as if with mulberry stains.",
  "antediluvial - Before the flood, or Deluge, in Noah's time.",
  "putrilage - That which is undergoing putrefaction; the products of putrefaction.",
  "calymene - A genus of trilobites characteristic of the Silurian age.",
  "top-armor - A top railing supported by stanchions and equipped with netting.",
  "tribunitious - Tribunician; tribunitial. [Obs.] Bacon.",
  "unlodge - To dislodge; to deprive of lodgment. Carew.",
  "licking - 1. A lapping with the tongue. 2. A flogging or castigation. [Colloq. or Low]",
  "ovate-rotundate - Having a form intermediate between that of an egg and a sphere; roundly ovate.",
  "gynandrous - Having stamens inserted in the pistil; belonging to the class Gynandria.",
  "boxberry - The wintergreern. (Gaultheria procumbens). [Local, U.S.]",
  "hip lock - A lock in which a close grip is obtained and a fall attempted by a heave over the hip.",
  "feuilltonist - A writer of feuilletons. F. Harrison.",
  "carbanil - A mobile liquid, CO.N.C6H5, of pungent odor. It is the phenyl salt of isocyanic acid.",
  "unisonal - Being in unison; unisonant. -- U*nis\"o*nal*ly, adv.",
  "ominate - To presage; to foreshow; to foretoken. [Obs.] Dr. H. More.",
  "bonhommie - good nature; pleasant and easy manner.",
  "twitcher - One who, or that which, twitches.",
  "diminishingly - In a manner to diminish.",
  "bearbind - The bindweed (Convolvulus arvensis).",
  "crocodility - A caption or sophistical mode of arguing. [R.]",
  "hot-blooded - Having hot blood; excitable; high-spirited; irritable; ardent; passionate.",
  "condemnable - Worthy of condemnation; blamable; culpable.",
  "enterotomy - Incision of the intestines, especially in reducing certain cases of hernia.",
  "plumularian - Any Plumularia. Also used adjectively.",
  "temptable - Capable of being tempted; liable to be tempted. Cudworth.",
  "nailery - A manufactory where nails are made.",
  "spareness - The quality or state of being lean or thin; leanness.",
  "constituter - One who constitutes or appoints.",
  "carline thistle - A prickly plant of the genus Carlina (C. vulgaris), found in Europe and Asia.",
  "cubo-octahedral - Presenting a combination of a cube and an octahedron.",
  "indecimable - Not decimable, or liable to be decimated; not liable to the payment of tithes. Cowell.",
  "magnetizee - A person subjected to the influence of animal magnetism. [R.]",
  "conformableness - The quality of being conformable; conformability.",
  "tellership - The office or employment of a teller.",
  "antepenultima - The last syllable of a word except two, as -syl in monosyllable.",
  "pseudostella - Any starlike meteor or phenomenon. [R.]",
  "grilse - A young salmon after its first return from the sea.",
  "determinateness - State of being determinate.",
  "manswear - To swear falsely. Same as Mainswear.",
  "remollient - Mollifying; softening. [R.]",
  "ovate-oblong - Oblong. with one end narrower than the other; ovato-oblong.",
  "recidivation - A falling back; a backsliding. Hammond.",
  "harrage - To harass; to plunder from. [Obs.] Fuller.",
  "philhellenic - Of or pertaining to philhellenism.",
  "emissive - Sending out; emitting; as, emissive powers.",
  "tyran - A tyrant. [Obs.] Lordly love is such a tyran fell. Spenser.",
  "hegelism - The system of logic and philosophy set forth by Hegel, a German writer (1770-1831).",
  "dialogite - Native carbonate of manganese; rhodochrosite.",
  "nonjurorism - The doctrines, or action, of the Nonjurors.",
  "cottontail - The American wood rabbit (Lepus sylvaticus); -- also called Molly cottontail.",
  "perimetric - Of or pertaining to the perimeter, or to perimetry; as, a perimetric chart of the eye.",
  "bicapsular - Having two capsules; as, a bicapsular pericarp.",
  "stibonium - The hypothetical radical SbH4, analogous to ammonium; -- called also antimonium.",
  "misgovernment - Bad government; want of government. Shak.",
  "prolificate - To make prolific; to fertilize; to impregnate. Sir T. Browne.",
  "evocate - To call out or forth; to summon; to evoke. [R.] Stackhouse.",
  "unitarianism - The doctrines of Unitarians.",
  "astrometer - An instrument for comparing the relative amount of the light of stars.",
  "fusted - Moldy; ill-smelling. [Obs.] Bp. Hall.",
  "pomelo - A variety of shaddock, called also grape fruit.",
  "bacillus - A variety of bacterium; a microscopic, rod-shaped vegetable organism.",
  "turdiformes - A division of singing birds including the thrushes and allied kinds.",
  "reasoner - One who reasons or argues; as, a fair reasoner; a close reasoner; a logical reasoner.",
  "upstay - To sustain; to support. [Obs.] \"His massy spear upstayed.\" Milton.",
  "inefficaciously - without efficacy or effect.",
  "selenitical - Of or pertaining to selenite; resembling or containing selenite.",
  "succeeder - A successor. Shak. Tennyson.",
  "hammerable - Capable of being formed or shaped by a hammer. Sherwood.",
  "intercitizenship - The mutual right to civic privileges, in the different States. Bancroft.",
  "plant-eating - Eating, or subsisting on, plants; as, a plant-eating beetle.",
  "inexpectation - Absence of expectation. Feltham.",
  "skeel - A shallow wooden vessel for holding milk or cream. [Prov. Eng. & Scot.] Grose.",
  "tirwit - The lapwing. [Prov. Eng.] 'T IS 'T is.  A common contraction of it is.",
  "biseye - of Besee. [Obs.] Chaucer. Evil biseye, ill looking. [Obs.]",
  "top-dress - To apply a surface dressing of manureto,as land.",
  "half-tongue - A jury, for the trial of a fore foreigner, composed equally of citizens and aliens.",
  "coppery - Mixed with copper; containing copper, or made of copper; like copper.",
  "raduliform - Rasplike; as, raduliform teeth.",
  "fibreless - Having no fibers; destitute of fibers or fiber.",
  "stercoranism - The doctrine or belief of the Stercoranists.",
  "sparpoil - To scatter; to spread; to disperse. [Obs.]",
  "superexaltation - Elevation above the common degree. Holyday.",
  "plathelminthes - Same as Platyelminthes.",
  "spirality - The quality or states of being spiral.",
  "patronate - The right or duty of a patron; patronage. [R.] Westm. Rev.",
  "bonair - Gentle; courteous; complaisant; yielding. [Obs.]",
  "circumfusile - Capable of being poured or spread round. \"Circumfusile gold.\" Pope.",
  "insuccess - Want of success. [R.] Feltham.",
  "notableness - The quality of being notable.",
  "pyritaceous - Of or pertaining to pyrites. See Pyritic.",
  "sophic - Teaching wisdom. [Obs.] S. Harris.",
  "glucinic - Pertaining to, derived from, or containing, glucinum; as, glucinic oxide.",
  "acreage - Acres collectively; as, the acreage of a farm or a country.",
  "pleonast - One who is addicted to pleonasm. [R.] C. Reade.",
  "inoppressive - Not oppressive or burdensome. O. Wolcott.",
  "nurseryman - One who cultivates or keeps a nursery, or place for rearing trees, etc.",
  "maharajah - A sovereign prince in India; -- a title given also to other persons of high rank.",
  "blet - A form of decay in fruit which is overripe.",
  "timelessly - In a timeless manner; unseasonably. [R.] Milton.",
  "turlupin - One of the precursors of the Reformation; -- a nickname corresponding to Lollard, etc.",
  "pseudocoelia - The fifth ventricle in the mammalian brain. See Ventricle. B. G. Wilder.",
  "cannot - Am, is, or are, not able; -- written either as one word or two.",
  "porphyrite - A rock with a porphyritic structure; as, augite porphyrite.",
  "encollar - To furnish or surround with a collar. [R.]",
  "stratography - A description of an army, or of what belongs to an army.",
  "derogatoriness - Quality of being derogatory.",
  "albertite - A bituminous mineral resembling asphaltum, found in the county of A.",
  "discongruity - Incongruity; disagreement; unsuitableness. Sir M. Hale.",
  "retinol - A hydrocarbon oil obtained by the distillation of resin, -- used in printer's ink.",
  "heliolatry - Sun worship. See Sabianism.",
  "angulation - A making angular; angular formation. Huxley.",
  "meteorous - Of the nature or appearance of a meteor.",
  "undetermination - Indetermination. Sir M. Hale.",
  "huffy - 1. Puffed up; as, huffy bread. 2. Characterized by arrogance or petulance; easily offended.",
  "winkingly - In a winking manner; with the eye almost closed. Peacham.",
  "axinomancy - A species of divination, by means of an ax or hatchet.",
  "besmut - To blacken with smut; to foul with soot.",
  "transmeable - Capable of being passed over or traversed; passable. [Obs.]",
  "badger state - Wisconsin; -- a nickname.",
  "blunging - The process of mixing clay in potteries with a blunger. Tomlinson.",
  "enwoman - To endow with the qualities of a woman. [R.] Daniel.",
  "simplistic - Of or pertaining to simples, or a simplist. [R.] Wilkinson.",
  "flaccidity - The state of being flaccid.",
  "emulatively - In an emulative manner; with emulation.",
  "uncleship - The office or position of an uncle. Lamb.",
  "good-bye - Farewell; a form of address used at parting. See the last Note under By, prep. Shak.",
  "bossism - The rule or practices of bosses, esp. political bosses. [Slang, U. S.]",
  "brewery - A brewhouse; the building and apparatus where brewing is carried on.",
  "reliquidation - A second or renewed liquidation; a renewed adjustment. A. Hamilton.",
  "foxery - Behavior like that of a fox; [Obs.] Chaucer.",
  "thunderstorm - A storm accompanied with lightning and thunder.",
  "mown - Cut down by mowing, as grass; deprived of grass by mowing; as, a mown field.",
  "apical - At or belonging to an apex, tip, or summit. Gray.",
  "water sparrow - (a) The reed warbler. [Prov. Eng.] (b) The reed bunting. [Prov. Eng.]",
  "unwist - 1. Not known; unknown. [Obs.] Chaucer. Spenser. 2. Not knowing; unwitting. [Obs.] Wyclif.",
  "anaglyph - Any sculptured, chased, or embossed ornament worked in low relief, as a cameo.",
  "rainy - Abounding with rain; wet; showery; as, rainy day or season.",
  "abhorrence - Extreme hatred or detestation; the feeling of utter dislike.",
  "sharock - An East Indian coin of the value of 12",
  "armisonant - Rustling in arms; resounding with arms. [Obs.]",
  "incomprehense - Incomprehensible. [Obs.] \"Incomprehense in virtue.\" Marston.",
  "legerdemainist - One who practices sleight of hand; a prestidigitator.",
  "supportless - Having no support. Milton.",
  "chalybeous - Steel blue; of the color of tempered steel.",
  "superlucration - Excessive or extraordinary gain. [Obs.] Davenant.",
  "acoustical - Of or pertaining to acoustics.",
  "phytographical - Of or pertaining to phytography.",
  "reseizure - A second seizure; the act of seizing again. Bacon.",
  "cobishop - A joint or coadjutant bishop. Ayliffe.",
  "chorometry - The art of surveying a region or district.",
  "scyphomedusae - Same as Acraspeda, or Discophora.",
  "dentate-sinuate - Having a form intermediate between dentate and sinuate.",
  "alchemist - One who practices alchemy. You are alchemist; make gold. Shak.",
  "swingletail - The thrasher, or fox shark. See Thrasher.",
  "dephlegmedness - A state of being freed from water. [Obs.] Boyle.",
  "turnhalle - A building used as a school of gymnastics.",
  "hard-mouthed - Not sensible to the bit; not easily governed; as, a hard- mouthed horse.",
  "bedagat - The sacred books of the Buddhists in Burmah. Malcom.",
  "elvanite - The rock of an elvan vein, or the elvan vein itself; an elvan course.",
  "fragmentarily - In a fragmentary manner; piecemeal.",
  "gormandize - To eat greedily; to swallow voraciously; to feed ravenously or like a glutton. Shak.",
  "edriophthalmous - Pertaining to the Edriophthalma.",
  "croker - A cultivator of saffron; a dealer in saffron. [Obs.] Holinshed.",
  "skinner - 1. One who skins. 2. One who deals in skins, pelts, or hides.",
  "featherly - Like feathers. [Obs.] Sir T. Browne.",
  "seiches - Local oscillations in level observed in the case of some lakes, as Lake Geneva.",
  "faithed - Having faith or a faith; honest; sincere. [Obs.] \"Make thy words faithed.\" Shak.",
  "meconium - (a) Opium. [Obs.] (b) The contents of the fetal intestine; hence, first excrement.",
  "sucre - A silver coin of Ecuador, worth 68 cents.",
  "mistaker - One who mistakes. Well meaning ignorance of some mistakers. Bp. Hall.",
  "centesimal - Hundredth. -- n.  A hundredth part. The neglect of a few centesimals. Arbuthnot.",
  "originalness - The quality of being original; originality. [R.] Johnson.",
  "fumage - Hearth money. Fumage, or fuage, vulgarly called smoke farthings. Blackstone.",
  "rammel - Refuse matter. [Obs.] Filled with any rubbish, rammel and broken stones. Holland.",
  "curvicaudate - Having a curved or crooked tail.",
  "diphyozooid - One of the free-swimming sexual zooids of Siphonophora.",
  "rotal - Relating to wheels or to rotary motion; rotary. [R.]",
  "underground insurance - Wildcat insurance.",
  "artfulness - The quality of being artful; art; cunning; craft.",
  "allumette - A match for lighting candles, lamps, etc.",
  "multifariously - With great multiplicity and diversity; with variety of modes and relations.",
  "raphaelesque - Like Raphael's works; in Raphael's manner of painting.",
  "mucksy - Somewhat mucky; soft, sticky, and dirty; muxy. [Prov. Eng.] R. D. Blackmore.",
  "inalienableness - The quality or state of being inalienable; inalienability.",
  "gastroscope - An instrument for viewing or examining the interior of the stomach.",
  "counterrolment - A counter account. See Control. [Obs.] Bacon.",
  "argil - Clay, or potter's earth; sometimes pure clay, or alumina. See Clay.",
  "collaud - To join in praising. [Obs.] Howell.",
  "oxyquinoline - Hydroxy quinoline; a phenol derivative of quinoline, -- called also carbostyril.",
  "deuthydroguret - Same as Deutohydroguret.",
  "petaline - Pertaining to a petal; attached to, or resembling, a petal.",
  "scaldic - Of or pertaining to the scalds of the Norsemen; as, scaldic poetry.",
  "torques - A cervical ring of hair or feathers, distinguished by its color or structure; a collar.",
  "shrubbery - 1. A collection of shrubs. 2. A place where shrubs are planted. Macaulay.",
  "carlin - An old woman. [Scot. & Prov. Eng.]",
  "kimnel - A tub. See Kemelin. [Obs.] She knew not what a kimnel was Beau. & Fl.",
  "selenonium - A hypothetical radical of selenium, analogous to sulphonium. [R.]",
  "transposal - The act of transposing, or the state of being transposed; transposition.",
  "memorist - One who, or that which, causes to be remembered. [Obs.]",
  "setula - A small, short hair or bristle; a small seta.",
  "incommodement - The act of incommoded. [Obs.] Cheyne.",
  "slanting - Oblique; sloping. -- Slant\"ing*ly, adv.",
  "exceptless - Not exceptional; usual. [Obs.] My general and exceptless rashness. Shak.",
  "manchet - Fine white bread; a loaf of fine bread. [Archaic] Bacon. Tennyson.",
  "bisector - One who, or that which, bisects; esp. (Geom.) a straight line which bisects an angle.",
  "embarge - To put in a barge. [Poetic] Drayton.",
  "incubiture - Incubation. [Obs.] J. Ellis.",
  "cardecu - A quarter of a crown. [Obs.] The bunch of them were not worth a cardecu. Sir W. Scott.",
  "match game - A game arranged as a test of superiority; also, one of a series of such games.",
  "crystallographic - Pertaining to crystallography.",
  "apriority - The quality of being innate in the mind, or prior to experience; a priori reasoning.",
  "pulverization - The action of reducing to dust or powder.",
  "arenilitic - Of or pertaining to sandstone; as, arenilitic mountains. Kirwan.",
  "ungka - The siamang; -- called also ungka ape.",
  "customarily - In a customary manner; habitually.",
  "stethoscopist - One skilled in the use of the stethoscope.",
  "gleety - Ichorous; thin; limpid. Wiseman.",
  "corporeality - The state of being corporeal; corporeal existence.",
  "haemadynamometer - Same as Hemadynamometer.",
  "refrigeration - The act or process of refrigerating or cooling, or the state of being cooled.",
  "antidotical - Serving as an antidote. -- An`ti*dot\"ic*al*ly, adv.",
  "appeasement - The act of appeasing, or the state of being appeased; pacification. Hayward.",
  "prebendate - To invest with the office of prebendary; to present to a prebend. [Obs.] Grafton.",
  "disjudication - Judgment; discrimination. See Dijudication. [Obs.] Boyle.",
  "zoutch - To stew, as flounders, eels, etc., with just enough or liquid to cover them. Smart.",
  "alloxantin - A substance produced by acting upon uric with warm and very dilute nitric acid.",
  "nebulation - The condition of being nebulated; also, a clouded, or ill- defined, color mark.",
  "cagmag - A tough old goose; hence, coarse, bad food of any kind. [Prov. Eng.] Halliwell.",
  "matriarch - The mother and ruler of a family or of her descendants; a ruler by maternal right.",
  "hardware - Ware made of metal, as cutlery, kitchen utensils, and the like; ironmongery.",
  "absinthate - A combination of absinthic acid with a base or positive radical.",
  "microtomy - The art of using the microtome; investigation carried on with the microtome.",
  "thrack - To load or burden; as, to thrack a man with property. [Obs.] South.",
  "profitless - Without profit; unprofitable. Shak.",
  "faciend - The multiplicand. See Facient, 2.",
  "coagulant - That which produces coagulation.",
  "spumescence - The state of being foamy; frothiness.",
  "sexennial - Lasting six years, or happening once in six years. -- n.  A sexennial event.",
  "swingeing - Huge; very large. [Colloq.] Arbuthnot. Byron. -- Swinge\"ing*ly, adv. Dryden.",
  "closehanded - Covetous; penurious; stingy; closefisted. -- Close\"hand`ed*ness, n.",
  "ulva - A genus of thin papery bright green seaweeds including the kinds called sea lettuce.",
  "ferrandine - A stuff made of silk and wool. I did buy a colored silk ferrandine. Pepys.",
  "prevene - To come before; to anticipate; hence, to hinder; to prevent. [Obs.] Philips.",
  "kindless - Destitute of kindness; unnatural.[Obs.] \"Kindless villain.\" Shak.",
  "excogitation - The act of excogitating; a devising in the thoughts; invention; contrivance.",
  "trustee stock - High-grade stock in which trust funds may be legally invested. [Colloq.]",
  "squillitic - Of or pertaining to squills. [R.] \"Squillitic vinegar.\" Holland.",
  "obediently - In an obedient manner; with obedience.",
  "trispaston - A machine with three pulleys which act together for raising great weights. Brande & C.",
  "palmitone - The ketone of palmitic acid.",
  "rostelliform - Having the form of a rostellum, or small beak.",
  "fameless - Without fame or renown. -- Fame\"less*ly, adv.",
  "whistly - In a whist manner; silently. [Obs.]",
  "ductible - Capable of being drawn out [R.] Feltham.",
  "childship - The state or relation of being a child.",
  "saintish - Somewhat saintlike; -- used ironically.",
  "thysanopteran - One of the Thysanoptera.",
  "monamide - An amido compound with only one amido group.",
  "self-aggrandizement - The aggrandizement of one's self.",
  "discoure - To discover. [Obs.] That none might her discoure. Spenser.",
  "feldspathose - Pertaining to, or consisting of, feldspar.",
  "stirious - Resembling icicles. [Obs.] Sir T. Browne.",
  "tank vessel - A vessel fitted with tanks for the carrying of oil or other liquid in bulk.",
  "reposure - Rest; quiet. In the reposure of most soft content. Marston.",
  "moldery - Covered or filled with mold; consisting of, or resembling, mold.",
  "complicacy - A state of being complicate or intricate. Mitford.",
  "ancome - A small ulcerous swelling, coming suddenly; also, a whitlow. [Obs.] Boucher.",
  "evanishment - A vanishing; disappearance. [R.] T. Jefferson.",
  "nakedly - In a naked manner; without covering or disguise; manifestly; simply; barely.",
  "chop-logic - One who bandies words or is very argunentative. [Jocular] Shak.",
  "binominal - Of or pertaining to two names; binomial.",
  "arioso - In the smooth and melodious style of an air; ariose.",
  "vernage - A kind of sweet wine from Italy. [Obs.] Chaucer.",
  "paracorolla - A secondary or inner corolla; a corona, as of the Narcissus.",
  "lutherism - The doctrines taught by Luther or held by the Lutheran Church.",
  "practisant - An agent or confederate in treachery. [Obs.] Shak.",
  "fluxure - 1. The quality of being fluid. [Obs.] Fielding. 2. Fluid matter. [Obs.] Drayton.",
  "meticulous - Timid; fearful. -- Me*tic\"u*lous*ly, adv.",
  "persic - Of or relating to Persia. -- n.  The Persian language.",
  "simultaneity - The quality or state of being simultaneous; simultaneousness.",
  "self-defensive - Defending, or tending to defend, one's own person, property, or reputation.",
  "pessimize - To hold or advocate the doctrine of pessimism. London Sat. Rev.",
  "nummulitic - Of, like, composed of, containing, nummulites; as, nummulitic beds.",
  "sororal - Relating to a sister; sisterly. [R.]",
  "unicolorous - Having the surface of a uniform color.",
  "appulsion - A driving or striking against; an appulse.",
  "trackwalker - A person employed to walk over and inspect a section of tracks.",
  "low-churchism - The principles of the low-church party.",
  "honorific - Conferring honor; tending to honor. London. Spectator.",
  "evulsion - The act of plucking out; a rooting out.",
  "gasification - The act or process of converting into gas.",
  "arachnoidal - Pertaining to the arachnoid membrane; arachnoid.",
  "abolishment - The act of abolishing; abolition; destruction. Hooker.",
  "gane - To yawn; to gape. [Obs.] Chaucer.",
  "directress - A woman who directs. Bp. Hurd.",
  "platitudinize - To utter platitudes or truisms.",
  "quinqueangled - Having five angles; quinquangular.",
  "giddiness - The quality or state of being giddy.",
  "omegoid - Having the form of the Greek capital letter Omega (",
  "tunk - A sharp blow; a thump. [Prov. Eng. or Colloq. U. S.]",
  "polycotyledonary - Having the villi of the placenta collected into definite patches, or cotyledons.",
  "uncoif - To deprive of the coif or cap. Young.",
  "fritinancy - A chirping or creaking, as of a cricket. [Obs.] Sir T. Browne.",
  "circularity - The quality or state of being circular; a circular form.",
  "rivality - 1. Rivalry; competition. [Obs.] 2. Equality, as of right or rank. [Obs.] hak.",
  "billy - 1. A club; esp., a policeman's club. 2. (Wool Manuf.)  A slubbing or roving machine.",
  "electro-ballistic - Pertaining to electro-ballistics.",
  "acritude - Acridity; pungency joined with heat. [Obs.]",
  "calcographer - One who practices calcography.",
  "preemptioner - One who holds a prior to purchase certain public land. Abbott.",
  "rouleau - A little roll; a roll of coins put up in paper, or something resembling such a roll.",
  "euphonium - A bass instrument of the saxhorn family.",
  "compensatory - Serving for compensation; making amends. Jer. Taylor.",
  "pumpet - A pompet. Pumpet ball (Print.), a ball for inking types; a pompet.",
  "rareness - The state or quality of being rare. And let the rareness the small gift commend. Dryden.",
  "uranographist - One practiced in uranography.",
  "tauricornous - Having horns like those of a bull. Sir T. Browne.",
  "aladinist - One of a sect of freethinkers among the Mohammedans.",
  "trottoir - Footpath; pavement; sidewalk. Headless bodies trailed along the trottoirs. Froude.",
  "weightiness - The quality or state of being weighty; weight; force; importance; impressiveness.",
  "mesmeric - Of, pertaining to, or induced by, mesmerism; as, mesmeric sleep.",
  "campaned - Furnished with, or bearing, campanes, or bells.",
  "curvilinearity - The state of being curvilinear or of being bounded by curved lines.",
  "posttertiary - Following, or more recent than, the Tertiary; Quaternary.",
  "forswearer - One who rejects of renounces upon oath; one who swears a false oath.",
  "waterishness - The quality of being waterish.",
  "clogging - Anything which clogs. Dr. H. More.",
  "phakoscope - An instrument for studying the mechanism of accommodation.",
  "pulselessness - The state of being pulseless.",
  "netify - To render neat; to clean; to put in order. [R.] Chapman.",
  "meloplasty - The process of restoring a cheek which has been destroyed wholly or in part.",
  "viscountcy - The dignity or jurisdiction of a viscount. Sir B. Burke.",
  "translatitious - Metaphorical; tralatitious; also, foreign; exotic. [Obs.] Evelyn.",
  "averruncate - 1. To avert; to ward off. [Obs.] Hudibras. 2. To root up. [Obs.] Johnson.",
  "deictic - Direct; proving directly; -- applied to reasoning, and opposed to elenchtic or refutative.",
  "fidicinal - Of or pertaining to a stringed instrument.",
  "water breather - Any arthropod that breathes by means of gills.",
  "ebriety - Drunkenness; intoxication by spirituous liquors; inebriety. \"Ruinous ebriety.\" Cowper.",
  "agrief - In grief; amiss. [Obs.] Chaucer.",
  "nunciature - The office of a nuncio. Clarendon.",
  "barse - The common perch. See 1st Bass. [Prov. Eng.] Halliwell.",
  "professionalist - professional person. [R.]",
  "invisibly - In an invisible manner, Denham.",
  "deturb - To throw down. [Obs.] Bp. Hall.",
  "alcohate - Shortened forms of Alcoholate.",
  "dislive - To deprive of life. [Obs.] Telemachus dislived Amphimedon. Chapman.",
  "tinkering - The act or work of a tinker.",
  "interanimate - To animate or inspire mutually. [Obs.] Donne.",
  "clayish - Partaking of the nature of clay, or containing particles of it.",
  "jargonic - Of or pertaining to the mineral jargon.",
  "glandular - Containing or supporting glands; consisting of glands; pertaining to glands.",
  "mesocoele - The cavity of the mesencephalon; the iter.",
  "skinless - Having no skin, or a very thin skin; as, skinless fruit.",
  "polytheize - To adhere to, advocate, or inculcate, the doctrine of polytheism. Milman.",
  "subarctic - Approximately arctic; belonging to a region just without the arctic circle.",
  "hypnologist - One who is versed in hypnology.",
  "illaqueable - Capable of being insnared or entrapped. [R.] Cudworth.",
  "hyblaean - Pertaining to Hybla, an ancient town of Sicily, famous for its bees.",
  "drone bee - The male of the honeybee; a drone.",
  "undermasted - Having masts smaller than the usual dimension; -- said of vessels. Totten.",
  "nanny - A diminutive of Ann or Anne, the proper name. Nanny goat, a female goat. [Colloq.]",
  "deliverable - Capable of being, or about to be, delivered; necessary to be delivered. Hale.",
  "neoplasia - Growth or development of new material; neoplasty.",
  "douter - An extinguisher for candles. [Obs.]",
  "obscurantism - The system or the principles of the obscurants. C. Kingsley.",
  "enarration - A detailed exposition; relation. [Obs.] Hakewill.",
  "syndesmology - That part of anatomy which treats of ligaments.",
  "vindicator - One who vindicates; one who justifies or maintains. Locke.",
  "superiorly - In a superior position or manner.",
  "dur - Major; in the major mode; as, C dur, that is, C major.",
  "sloughing - The act of casting off the skin or shell, as do insects and crustaceans; ecdysis.",
  "tetrarchical - Of or pertaining to a tetrarch or tetrarchy. Bolingbroke.",
  "scutibranchian - One of the Scutibranchiata.",
  "epigraphy - The science of inscriptions; the art of engraving inscriptions or of deciphering them.",
  "ambulation - The act of walking. Sir T. Browne.",
  "linum - A genus of herbaceous plants including the flax (Linum usitatissimum).",
  "numerative - Of or pertaining to numeration; as, a numerative system. Eng. Cyc.",
  "antitheist - A disbeliever in the existence of God.",
  "enoptomancy - Divination by the use of a mirror.",
  "titularity - The quality or state of being titular. [R.] Sir T. Browne.",
  "pluri- - A combining form from L. plus, pluris, more, many; as pluriliteral.",
  "intelligently - In an intelligent manner; with intelligence.",
  "enhancer - One who enhances; one who, or that which, raises the amount, price, etc.",
  "araguato - A South American monkey, the ursine howler (Mycetes ursinus). See Howler, n., 2.",
  "athleticism - The practice of engaging in athletic games; athletism.",
  "polythelism - The condition of having more than two teats, or nipples.",
  "cambistry - The science of exchange, weight, measures, etc.",
  "ethiop - A native or inhabitant of Ethiopia; also, in a general sense, a negro or black man.",
  "histographical - Of or pertaining to histography.",
  "traded - Professional; practiced. [Obs.] Shak.",
  "categorize - To insert in a category or list; to class; to catalogue.",
  "exhereditation - A disinheriting; disherison. [R.] E. Waterhouse.",
  "impoliticness - The quality of being impolitic.",
  "danseuse - a professional female dancer; a woman who dances at a public exhibition as in a ballet.",
  "tiring-house - A tiring-room. [Obs.] Shak.",
  "whally - Having the iris of light color; -- said of horses. \"Whally eyes.\" Spenser.",
  "albuminin - The substance of the cells which inclose the white of birds' eggs.",
  "gryphaea - A genus of cretaceous fossil shells allied to the oyster.",
  "myxa - The distal end of the mandibles of a bird.",
  "undercrest - To support as a crest; to bear. [Obs. & R.] Shak.",
  "revaluation - A second or new valuation.",
  "virtuosoship - The condition, pursuits, or occupation of a virtuoso. Bp. Hurd.",
  "religieuse - A person bound by monastic vows; a nun; a monk.",
  "inquirable - Capable of being inquired into; subject or liable to inquisition or inquest. Bacon.",
  "flative - Producing wind; flatulent. [Obs.] A. Brewer.",
  "margarodite - A hidrous potash mica related to muscovite.",
  "piewipe - The lapwing, or pewit. [Prov. Eng.]",
  "verbalism - Something expressed verbally; a verbal remark or expression.",
  "desultorily - In a desultory manner; without method; loosely; immethodically.",
  "pulvillus - One of the minute cushions on the feet of certain insects.",
  "exoptable - Very desirable. [Obs.] Bailey.",
  "inexpansible - Incapable of expansion, enlargement, or extension. Tyndall.",
  "zircon light - A light, similar to the calcium light, produced by incandescent zirconia.",
  "namation - A distraining or levying of a distress; an impounding. Burrill.",
  "tentaculated - Having tentacles, or organs like tentacles; tentacled.",
  "delightous - Delightful. [Obs.] Rom. of R.",
  "antipyretic - Efficacious in preventing or allaying fever. -- n.  A febrifuge.",
  "paneling - A forming in panels; panelwork. [Written also panelling.]",
  "barrulet - A diminutive of the bar, having one fourth its width.",
  "accountantship - The office or employment of an accountant.",
  "collagenous - Containing or resembling collagen.",
  "oreography - The science of mountains; orography.",
  "perichondritis - Inflammation of the perichondrium.",
  "grizzle - Gray; a gray color; a mixture of white and black. Shak.",
  "pterosaurian - Of or pertaining to the Pterosauria.",
  "malmag - The tarsius, or spectral lemur.",
  "preacquaintance - Previous acquaintance or knowledge. Harris.",
  "prore - The prow or fore part of a ship. [Poetic] \"Galleys with vermilion prores.\" Pope.",
  "ghyll - A ravine. See Gill a woody glen. [Prov. Eng. & Scot.] Wordsworth.",
  "twankay - See Note under Tea, n., 1. 'T WAS 'T was.  A contraction of it was.",
  "siderolite - A kind of meteorite. See under Meteorite.",
  "aidant - Helping; helpful; supplying aid. Shak.",
  "loving-kindness - Tender regard; mercy; favor. Ps. lxxxix. 33.",
  "yttro-tantalite - A tantalate of uranium, yttrium, and calcium, of a brown or black color.",
  "nucament - A catkin or ament; the flower cluster of the hazel, pine, willow, and the like.",
  "foreappointment - Previous appointment; preordinantion. Sherwood.",
  "slammerkin - A slut; a slatternly woman. [Obs. or Prov. Eng.]",
  "quinogen - A hypothetical radical of quinine and related alkaloids.",
  "odalwoman - A man or woman having odal, or able to share in it by inheritance.",
  "drumly - Turbid; muddy. [Scot. & Obs. or Prov. Eng.] Wodroephe (1623). Burns.",
  "indictive - Proclaimed; declared; public. Kennet.",
  "olived - Decorated or furnished with olive trees. [R.] T. Warton.",
  "consideringly - With consideration or deliberation.",
  "putrifacted - Putrefied. [Obs.] What vermin bred of putrifacted slime. Marston.",
  "coprolite - A piece of petrified dung; a fossil excrement.",
  "flatulently - In a flatulent manner; with flatulence.",
  "consignification - Joint signification. [R.]",
  "headrope - That part of a boltrope which is sewed to the upper edge or head of a sail.",
  "retinal - Of or pertaining to the retina. Retinal purple (Physiol. Chem.), the visual purple.",
  "podalgia - pain in the foot, due to gout, rheumatism, etc.",
  "inquinate - To defile; to pollute; to contaminate; to befoul. [Obs.] Sir T. Browne.",
  "catechumenical - Of or pertaining to catechumens; as, catechumenical instructions.",
  "strictly - In a strict manner; closely; precisely.",
  "misgiving - Evil premonition; doubt; distrust. \"Suspicious and misgivings.\" South.",
  "astrofell - A bitter herb, probably the same as aster, or starwort. Spenser.",
  "fozy - Spongy; soft; fat and puffy. [Scot.]",
  "chartless - 1. Without a chart; having no guide. 2. Not mapped; uncharted; vague. Barlow.",
  "relumine - 1. To light anew; to rekindle. Shak. 2. To illuminate again.",
  "unconcerning - Not interesting of affecting; insignificant; not belonging to one. [Obs.] Addison.",
  "mesonephric - Of or pertaining to the mesonephros; as, the mesonephric, or Wolffian, duct.",
  "screenings - The refuse left after screening sand, coal, ashes, etc.",
  "termine - To terminate. [Obs.] Bp. Hall.",
  "thymiatechny - The art of employing perfumes in medicine. [R.] Dunglison.",
  "autohypnotic - Pert. to autohypnotism; self-hypnotizing. -- n.  An autohypnotic person.",
  "sangaree - Wine and water sweetened and spiced, -- a favorite West Indian drink.",
  "spritefully - See Sprightful, Sprightfully, Sprightliness, Sprightly, etc.",
  "arguable - Capable of being argued; admitting of debate.",
  "spinstry - The business of one who spins; spinning. [Obs.] Milton.",
  "latibulum - A concealed hiding place; a burrow; a lair; a hole.",
  "coppering - 1. The act of covering with copper. 2. An envelope or covering of copper.",
  "sustainable - Capable of being sustained or maintained; as, the action is not sustainable.",
  "mainsheet - One of the ropes by which the mainsail is hauled aft and trimmed.",
  "sea onion - The officinal squill. See Squill.",
  "theomachist - One who fights against the gods; one who resists God of the divine will.",
  "perturbative - Tending to cause perturbation; disturbing. Sir J. Herschel.",
  "libral - Of a pound weight. [Obs.] Johnson.",
  "elinguation - Punishment by cutting out the tongue.",
  "castor and pollux - See Saint Elmo's fire, under Saint.",
  "inaniloquous - Given to talking inanely; loquacious; garrulous. [R.]",
  "imposer - One who imposes. The imposers of these oaths might repent. Walton.",
  "dodecastyle - Having twelve columns in front. -- n.  A dodecastyle portico, or building.",
  "ungrate - Displeasing; ungrateful; ingrate. [Obs.] Jer. Taylor.",
  "inobservation - Neglect or want of observation. [R.]",
  "eardrum - The tympanum. See Illust. of Ear.",
  "fumy - Producing fumes; fumous. \"Drowned in fumy wine.\" H. Brooke.",
  "gipoun - A short cassock. [Written also gepoun, gypoun, jupon, juppon.] [Obs.]",
  "bayou state - Mississippi; -- a nickname, from its numerous bayous.",
  "coldness - The state or quality of being cold.",
  "homilist - One who prepares homilies; one who preaches to a congregation.",
  "phratry - A subdivision of a phyle, or tribe, in Athens.",
  "nymphish - Relating to nymphs; ladylike. \"Nymphish war.\" Drayton.",
  "unsincerity - The quality or state of being unsincere or impure; insincerity. [Obs.] Boyle.",
  "crunodal - Possessing, or characterized by, a crunode; -- used of curves.",
  "healthiness - The state of being healthy or healthful; freedom from disease.",
  "sparble - To scatter; to disperse; to rout. [Obs.] The king's host was sparbled and chased. Fabyan.",
  "doorsill - The sill or threshold of a door.",
  "manation - The act of issuing or flowing out. [Obs.]",
  "stoping - The act of excavating in the form of stopes.",
  "blameworthy - Deserving blame; culpable; reprehensible. -- Blame\"wor`thi*ness, n.",
  "cohesibility - The state of being cohesible. Good.",
  "camelry - Troops that are mounted on camels.",
  "immutation - Change; alteration; mutation. [R.] Dr. H. More.",
  "glumella - One of the pelets or inner chaffy scales of the flowers or spikelets of grasses.",
  "strong-water - 1. An acid. [Obs.] 2. Distilled or ardent spirits; intoxicating liquor.",
  "solvend - A substance to be dissolved. [R.]",
  "strigose - Set with stiff, straight bristles; hispid; as, a strigose leaf.",
  "aparithmesis - Enumeration of parts or particulars.",
  "ormuzd - The good principle, or being, of the ancient Persian religion. See Ahriman.",
  "shallow-bodied - Having a moderate depth of hold; -- said of a vessel.",
  "redemptory - Paid for ransom; serving to redeem. \"Hector's redemptory price.\" Chapman.",
  "seminification - Propagation from seed. [R.] Sir M. Hale.",
  "garran - See Galloway. [Scot. garron or gerron. Jamieson.]",
  "ooetocoid - A half oviparous, or an oviparous, mammal; a marsupial or monotreme.",
  "ataman - A hetman, or chief of the Cossacks.",
  "horologiographer - A maker of clocks, watches, or dials.",
  "solemness - Solemnness. Some think he wanted solemnes. Sir H. Wotton.",
  "carlot - A churl; a boor; a peasant or countryman. [Obs.] Shak.",
  "meterage - The act of measuring, or the cost of measuring.",
  "sarcel - One of the outer pinions or feathers of the wing of a bird, esp. of a hawk.",
  "marteline - A small hammer used by marble workers and sculptors.",
  "ratihabition - Confirmation or approbation, as of an act or contract. [Obs.] Jer. Tailor.",
  "finicky - Finical; unduly particular. [Colloq.]",
  "murther - Murder, n. & v. [Obs. or Prov.] \"The treason of the murthering.\" Chaucer.",
  "longly - 1. With longing desire. [Obs.] Shak. 2. For a long time; hence, wearisomely.",
  "amphigonous - Relating to both parents. [R.]",
  "pyruvil - A complex nitrogenous compound obtained by heating together pyruvic acid and urea.",
  "weber - The standard unit of electrical quantity, and also of current. See Coulomb, and Amp. [Obs.]",
  "matronhood - The state of being a matron.",
  "extravagantly - In an extravagant manner; wildly; excessively; profusely.",
  "spinnaker - A large triangular sail set upon a boom, -- used when running before the wind.",
  "undreamed - Not dreamed, or dreamed of; not thof. Unpathed waters, undreamed shores. Shak.",
  "hopbind - The climbing stem of the hop. Blackstone.",
  "trichord - An instrument, as a lyre or harp, having three strings.",
  "incorporeally - In an incorporeal manner. Bacon.",
  "ethnographic - pertaining to ethnography.",
  "globulous - Globular; spherical; orbicular. -- Glob\"u*lous*ness, n.",
  "woodcutter - 1. A person who cuts wood. 2. An engraver on wood. [R.]",
  "phyllo- - A combining form from Gr. a leaf; as, phyllopod, phyllotaxy.",
  "puncher - One who, or that which, punches.",
  "adjectitious - Added; additional. Parkhurst.",
  "coda - A few measures added beyond the natural termination of a composition.",
  "snotty - Foul with snot; hence, mean; dirty. -- Snort\"ti*ly, adb. -- Snot\"ti*ness, n.",
  "ptyalism - Salivation, or an excessive flow of saliva. Quain.",
  "integrability - The quality of being integrable.",
  "alveated - Formed or vaulted like a beehive.",
  "apishly - In an apish manner; with servile imitation; foppishly.",
  "imminution - A lessening; diminution; decrease. [R.] Ray.",
  "amylogen - That part of the starch granule or granulose which is soluble in water.",
  "hagiographal - , Pertaining to the hagiographa, or to sacred writings.",
  "paseng - The wild or bezoar goat. See Goat.",
  "liquefiable - Capable of being changed from a solid to a liquid state.",
  "self-willed - Governed by one's own will; not yielding to the wishes of others; obstinate.",
  "agenesic - Characterized by sterility; infecund.",
  "crapulence - The sickness occasioned by intemperance; surfeit. Bailey.",
  "dethronize - To dethrone or unthrone. [Obs.] Cotgrave.",
  "caliphate - The office, dignity, or government of a caliph or of the caliphs.",
  "conductory - Having the property of conducting. [R.]",
  "miseducate - To educate in a wrong manner.",
  "decemviral - Pertaining to the decemvirs in Rome.",
  "trifoliolate - (Bot.) Having three leaflets.",
  "extensionist - One who favors or advocates extension.",
  "armure - 1. Armor. [Obs.] Chaucer. 2. A variety of twilled fabric ribbed on the surface.",
  "brachycatalectic - A verse wanting two syllables at its termination.",
  "preacquaint - To acquaint previously or beforehand. Fielding.",
  "ulteriorly - More distantly or remotely.",
  "stail - A handle, as of a mop; a stale. [Eng.]",
  "adjournal - Adjournment; postponement. [R.] \"An adjournal of the Diet.\" Sir W. Scott.",
  "halieutics - A treatise upon fish or the art of fishing; ichthyology.",
  "scrobicula - One of the smooth areas surrounding the tubercles of a sea urchin.",
  "parturious - Parturient. [Obs.] Drayton.",
  "gelable - Capable of being congealed; capable of being converted into jelly.",
  "encephalotomy - The act or art of dissecting the brain.",
  "tristigmatose - Having, or consisting of, three stigmas. Gray.",
  "fustiness - A fusty state or quality; moldiness; mustiness; an ill smell from moldiness.",
  "somatist - One who admits the existence of material beings only; a materialist. Glanvill.",
  "conformer - One who conforms; one who complies with established forms or doctrines.",
  "remonetization - The act of remonetizing.",
  "subintestinal - Situated under, or on the ventral side of, the intestine.",
  "greenhood - A state of greenness; verdancy. Chaucer.",
  "oleandrine - One of several alkaloids found in the leaves of the oleander.",
  "wool-hall - A trade market in the woolen districts. [Eng.]",
  "inapprehensive - Not apprehensive; regardless; unconcerned. Jer. Taylor.",
  "philosophe - A philosophaster; a philosopher. [R.] Carlyle.",
  "unifollilate - Having only one leaflet, as the leaves of the orange tree.",
  "incommunicating - Having no communion or intercourse with each other. [Obs.] Sir M. Hale.",
  "eggery - A place where eggs are deposited (as by sea birds) or kept; a nest of eggs. [R.]",
  "ascendible - Capable of being ascended; climbable.",
  "humblehead - Humble condition or estate; humility. [Obs.] Chaucer.",
  "astoop - In a stooping or inclined position. Gay.",
  "methodistical - Of or pertaining to methodists, or to the Methodists. -- Meth`o*dis\"tic*al*ly, adv.",
  "spermologist - One who treats of, or collects, seeds. Bailey.",
  "emulable - Capable of being emulated. [R.] Some imitable and emulable good. Abp. Leighton.",
  "ornithotomical - Of or pertaining to ornithotomy.",
  "incontestability - The quality or state of being incontestable.",
  "heteromorphy - The state or quality of being heteromorphic.",
  "intervary - To alter or vary between; to change. [Obs.] Rush.",
  "homopterous - Of or pertaining to the Homoptera.",
  "invision - Want of vision or of the power of seeing. [Obs.] Sir T. Browne.",
  "gamophyllous - Composed of leaves united by their edges (coalescent). Gray.",
  "epigrammatize - To represent by epigrams; to express by epigrams.",
  "accustomary - Usual; customary. [Archaic] Featley.",
  "epipolism - See Fluorescence. [R.] Sir J. Herschel.",
  "politicalism - Zeal or party spirit in politics.",
  "engiscope - A kind of reflecting microscope. [Obs.]",
  "air shaft - A passage, usually vertical, for admitting fresh air into a mine or a tunnel.",
  "shafting - Shafts, collectivelly; a system of connected shafts for communicating motion.",
  "mathesis - Learning; especially, mathematics. [R.] Pope.",
  "persulphocyanate - A salt of persulphocyanic acid. [R.]",
  "intersocial - Pertaining to the mutual intercourse or relations of persons in society; social.",
  "octandrian - Of or pertaining to the Octandria; having eight distinct stamens.",
  "immortalist - One who holds the doctrine of the immortality of the soul. [R.] Jer. Taylor.",
  "conjugally - In a conjugal manner; matrimonially; connubially.",
  "nuciferous - Bearing, or producing, nuts.",
  "antiptosis - The putting of one case for another.",
  "wagnerite - A fluophosphate of magnesia, occurring in yellowish crystals, and also in massive forms.",
  "diclinous - Having the stamens and pistils in separate flowers. Gray.",
  "adunation - A uniting; union. Jer. Taylor.",
  "emplunge - To plunge; to implunge. [Obs.] Spenser.",
  "camping - 1. Lodging in a camp. 2. Etym: [See Camp, n., 6]  A game of football. [Prov. Eng.]",
  "orthotomy - The property of cutting at right angles.",
  "inescate - To allure; to lay a bait for. [Obs.] To inescate and beguile young women! Burton.",
  "emmenagogue - A medicine that promotes the menstrual discharge.",
  "unessentially - In an unessential manner.",
  "weaponed - Furnished with weapons, or arms; armed; equipped.",
  "corah - Plain; undyed; -- applied to Indian silk. -- n.  Corah silk.",
  "afforestation - The act of converting into forest or woodland. Blackstone.",
  "benzoline - (a) Same as Benzole. (b) Same as Amarine. [R.] Watts.",
  "pasigraphical - Of or pertaining to pasigraphy.",
  "exercent - Practicing; professional. [Obs.] \"Every exercent advocate.\" Ayliffe.",
  "octogamy - A marrying eight times. [R.] Chaucer.",
  "enigmatize - To make, or talk in, enigmas; to deal in riddles.",
  "inimaginable - Unimaginable; inconceivable. [R.] Bp. Pearson.",
  "leptology - A minute and tedious discourse on trifling things.",
  "injuria - Injury; invasion of another's rights.",
  "cousinhood - The state or condition of a cousin; also, the collective body of cousins; kinsfolk.",
  "uptrain - To train up; to educate. [Obs.] \"Daughters which were well uptrained.\" Spenser.",
  "web-footed - Having webbed feet; palmiped; as, a goose or a duck is a web- footed fowl.",
  "incorrigibly - In an incorrigible manner.",
  "opitulation - The act of helping or aiding; help. [Obs.] Bailey.",
  "sexed - Belonging to sex; having sex; distinctively male of female; as, the sexed condition.",
  "sceneman - The man who manages the movable scenes in a theater.",
  "baptization - Baptism. [Obs.] Their baptizations were null. Jer. Taylor.",
  "uplean - To lean or incline upon anything. [Obs.] Spenser.",
  "jacksmith - A smith who makes jacks. See 2d Jack, 4, c. Dryden.",
  "growse - To shiver; to have chills. [Obs. or Prov. Eng.] Ray.",
  "spoliatory - Tending to spoil; destructive; spoliative.",
  "habituation - The act of habituating, or accustoming; the state of being habituated.",
  "bodock - The Osage orange. [Southwestern U.S.]",
  "catastrophist - One who holds the theory or catastrophism.",
  "ponderable - Capable of being weighed; having appreciable weight. -- Pon\"der*a*ble*ness, n.",
  "unadulterated - Not adulterated; pure. \"Unadulterate air.\" Cowper. -- Un`a*dul\"ter*ate*ly, adv.",
  "underwitted - Weak in intellect; half-witted; silly. [R.] Bp. Kennet.",
  "misconfident - Having a mistaken confidence; wrongly trusting. [R.] Bp. Hall.",
  "cerotic - Pertaining to, or derived from, beeswax or Chinese wax; as, cerotic acid or alcohol.",
  "filibusterism - The characteristics or practices of a filibuster. Bartlett.",
  "draffy - Dreggy; waste; worthless. The dregs and draffy part. Beau. & Fl.",
  "counterwheel - To cause to wheel or turn in an opposite direction.",
  "paludism - The morbid phenomena produced by dwelling among marshes; malarial disease or disposition.",
  "theurgic - Of or pertaining to theurgy; magical. Theurgic hymns, songs of incantation.",
  "unvoluntary - Involuntary. [Obs.] Fuller.",
  "encrinal - Relating to encrinites; containing encrinites, as certain kinds of limestone.",
  "unmarry - To annul the marriage of; to divorce. Milton.",
  "abscession - A separating; removal; also, an abscess. [Obs.] Gauden. Barrough.",
  "anaphrodisiac - Same as Antaphrodisiac. Dunglison.",
  "cirriferous - Bearing cirri, as many plants and animals.",
  "cometary - Pertaining to, or resembling, a comet. Cheyne.",
  "accension - The act of kindling or the state of being kindled; ignition. Locke.",
  "accompt - See Account. Note: Accompt, accomptant, etc., are archaic forms.",
  "thurst - The ruins of the fallen roof resulting from the removal of the pillars and stalls. Raymond.",
  "pseudo-symmetric - Exhibiting pseudo-symmetry.",
  "relaxant - A medicine that relaxes; a laxative.",
  "coverer - One who, or that which, covers.",
  "chariotee - A light, covered, four-wheeled pleasure carriage with two seats.",
  "pentoic - Pertaining to, or desingating, an acid (called also valeric acid) derived from pentane.",
  "loud-voiced - Having a loud voice; noisy; clamorous. Byron.",
  "pretenceful - See Pretense, Pretenseful, Pretenseless.",
  "hatting - The business of making hats; also, stuff for hats.",
  "saliency - Quality of being salient; hence, vigor. \"A fatal lack of poetic saliency.\" J. Morley.",
  "subnotochordal - Situated on the ventral side of the notochord; as, the subnotochordal rod.",
  "subterfluous - Running under or beneath. [R.]",
  "thick-winded - Affected with thick wind.",
  "viscerate - To deprive of the viscera, or entrails; to eviscerate; to disembowel.",
  "papabote - The upland plover. [Local, U. S.]",
  "versability - The quality or state of being versable. [R.] Sterne",
  "silver state - Nevada; -- a nickname alluding to its silver mines.",
  "ineffervescible - Not capable or susceptible of effervescence.",
  "anagraph - An inventory; a record. [Obs.] Knowles.",
  "unpreach - To undo or overthrow by preaching. [R.] De Foe.",
  "oblite - Indistinct; slurred over. [Obs.] \"Obscure and oblite mention.\" Fuller.",
  "affectionateness - The quality of being affectionate; fondness; affection.",
  "bedim - To make dim; to obscure or darken. Shak.",
  "sugariness - The quality or state of being sugary, or sweet.",
  "synagogical - Of or pertaining to a synagogue.",
  "staves - pl. of Staff. \"Banners, scarves and staves.\" R. Browning. Also (stavz),  pl. of Stave.",
  "incalculability - The quality or state of being incalculable.",
  "metrological - Of or pertaining to metrology.",
  "hexoic - Pertaining to, or derived from, hexane; as, hexoic acid.",
  "rit - 3d pers. ssing. pres. of Ride, contracted from rideth. Chaucer.",
  "overwax - To wax or grow too rapindly or too much. [Obs.] R. of Gloucester.",
  "squamulose - Having little scales; squamellate; squamulate.",
  "capivi - A balsam of the Spanish West Indies. See Copaiba.",
  "weasel-faced - Having a thin, sharp face, like a weasel.",
  "misrepute - To have in wrong estimation; to repute or estimate erroneously.",
  "subtleness - The quality or state of being subtle; subtlety.",
  "unfolder - One who, or that which, unfolds.",
  "acrospore - A spore borne at the extremity of the cells of fructification in fungi.",
  "undervaluation - The act of undervaluing; a rate or value not equal to the real worth.",
  "pantascopic - Viewing all; taking a view of the whole. See under Camera.",
  "oryctography - Description of fossils. [Obs.]",
  "double-shade - To double the natural darkness of (a place). Milton.",
  "alimentariness - The quality of being alimentary; nourishing quality. [R.]",
  "anticous - Facing toward the axis of the flower, as in the introrse anthers of the water lily.",
  "beaconage - Money paid for the maintenance of a beacon; also, beacons, collectively.",
  "variously - In various or different ways.",
  "phoronomics - The science of motion; kinematics. [R.] Weisbach.",
  "interfascicular - Between fascicles or bundles; as, the interfascicular spaces of connective tissue.",
  "scortatory - Pertaining to lewdness or fornication; lewd.",
  "feria - A week day, esp. a day which is neither a festival nor a fast. Shipley.",
  "bolus - A rounded mass of anything, esp. a large pill.",
  "faintish - Slightly faint; somewhat faint. -- Faint\"ish*ness, n.",
  "ugrian - A Mongolian race, ancestors of the Finns. [Written also Uigrian.]",
  "filing - A fragment or particle rubbed off by the act of filing; as, iron filings.",
  "antinational - Antagonistic to one's country or nation, or to a national government.",
  "sagittate - Shaped like an arrowhead; triangular, with the two basal angles prolonged downward.",
  "unalienable - Inalienable; as, unalienable rights. Swift. -- Un*al\"ien*a*bly, adv.",
  "bicostate - Having two principal ribs running longitudinally, as a leaf.",
  "photosphere - A sphere of light; esp., the luminous envelope of the sun.",
  "ransomless - Incapable of being ransomed; without ransom. Shak.",
  "swashbuckler - A bully or braggadocio; a swaggering, boastful fellow; a swaggerer. Milton.",
  "arbuscular - Of or pertaining to a dwarf tree; shrublike. Da Costa.",
  "furciferous - Rascally; scandalous. [R.] \"Furciferous knaves.\" De Quincey.",
  "hyalescence - The process of becoming, or the state of being, transparent like glass.",
  "changeless - That can not be changed; constant; as, a changeless purpose. -- Change\"less*ness, n.",
  "moira - The deity who assigns to every man his lot.",
  "instructible - Capable of being instructed; teachable; docible. Bacon.",
  "linguiform - Having the form of the tongue; tongue-shaped.",
  "soliloquize - To utter a soliloquy; to talk to one's self.",
  "bedrug - To drug abundantly or excessively.",
  "proboscidian - Pertaining to the Proboscidea. -- n.  One of the Proboscidea.",
  "kibed - Chapped; cracked with cold; affected with chilblains; as kibed heels. Beau. & Fl.",
  "gowdnook - The saury pike; -- called also gofnick.",
  "fantom - See Phantom. Fantom corn, phantom corn. Grose.",
  "imposingness - The quality of being imposing.",
  "yestern - Of or pertaining to yesterday; relating to the day last past.",
  "productus - An extinct genus of brachiopods, very characteristic of the Carboniferous rocks.",
  "orthodromic - Of or pertaining to orthodromy.",
  "unspilt - Not spilt or wasted; not shed.",
  "alguazil - An inferior officer of justice in Spain; a warrant officer; a constable. Prescott.",
  "lawbreaker - One who disobeys the law; a criminal. -- Law\"break`ing, n. & a.",
  "hiveless - Destitute of a hive. Gascoigne.",
  "two-cycle - A two-stroke cycle for an internal-combustion engine. --Two\"- cy`cle, a.",
  "centrebit - An instrument turning on a center, for boring holes. See Bit, n., 3.",
  "egotize - To talk or write as an egotist. Cowper.",
  "absterge - To make clean by wiping; to wipe away; to cleanse; hence, to purge. [R.] Quincy.",
  "adenographic - Pertaining to adenography.",
  "unfool - To restore from folly, or from being a fool. [Obs.] Shak.",
  "rhinoplastic - Of or pertaining to rhinoplasty; as, a rhinoplastic operation.",
  "unmentionables - The breeches; trousers. [Jocose]",
  "foreread - To tell beforehand; to signify by tokens; to predestine. [Obs.] Spenser.",
  "delusional - Of or pertaining to delusions; as, delusional monomania.",
  "chouka - The Indian four-horned antelope; the chikara.",
  "unio - Any one of numerous species of fresh-water mussels belonging to Unio and many allied genera.",
  "venulose - Full of venules, or small veins.",
  "noncontent - One who gives a negative vote; -- sometimes abridged into noncon. or non con.",
  "fernticle - A freckle on the skin, resembling the seed of fern. [Prov. Eng.]",
  "stalagmitical - Having the form or structure of stalagmites. -- Stal`ag*mit\"ic*al*ly, adv.",
  "speediness - The quality or state of being speedy.",
  "miscredent - A miscreant, or believer in a false religious doctrine. [Obs.] Holinshed.",
  "enecate - To kill off; to destroy. [Obs.] Harvey.",
  "tubful - As much as a tub will hold; enough to fill a tub.",
  "bighorn - The Rocky Mountain sheep (Ovis or Caprovis montana).",
  "rumkin - A popular or jocular name for a drinking vessel. [Obs.]",
  "syphilodermatous - Of or pertaining to the cutaneous manifestations of syphilis.",
  "land-poor - Pecuniarily embarrassed through owning much unprofitable land. [Colloq.]",
  "antivivisectionist - One opposed to vivisection",
  "bronchotome - An instrument for cutting into the bronchial tubes.",
  "demilance - A light lance; a short spear; a half pike; also, a demilancer.",
  "besmoke - 1. To foul with smoke. 2. To harden or dry in smoke. Johnson.",
  "contrapuntal - Pertaining to, or according to the rules of, counterpoint.",
  "paleographical - Of or pertaining to paleography.",
  "adaptly - In a suitable manner. [R.] Prior.",
  "lask - A diarrhea or flux. [Obs.] Holland.",
  "luminiferous - Producing light; yielding light; transmitting light; as, the luminiferous ether.",
  "garlandless - Destitute of a garland. Shelley.",
  "igasurine - An alkaloid found in nux vomica, and extracted as a white crystalline substance.",
  "anticonvulsive - Good against convulsions. J. Floyer.",
  "delibrate - To strip off the bark; to peel. [Obs.] Ash.",
  "armipotence - Power in arms. [R.] Johnson.",
  "bird-eyed - Quick-sighted; catching a glance as one goes.",
  "gleeman - A name anciently given to an itinerant minstrel or musician.",
  "adeniform - Shaped like a gland; adenoid. Dunglison.",
  "pleasantness - The state or quality of being pleasant.",
  "unparadise - To deprive of happiness like that of paradise; to render unhappy. [R.] Young.",
  "besieger - One who besieges; -- opposed to the besieged.",
  "spiracular - Of or pertaining to a spiracle.",
  "unruliment - Unruliness. [Obs.] \"Breaking forth with rude unruliment.\" Spenser.",
  "chitterlings - The smaller intestines of swine, etc., fried for food.",
  "electro-biologist - One versed in electro-biology.",
  "anamnesis - A recalling to mind; recollection.",
  "adrogation - A kind of adoption in ancient Rome. See Arrogation.",
  "sporiferous - Bearing or producing spores.",
  "ursal - The ursine seal. See the Note under 1st Seal.",
  "raiser - One who, or that which, raises (in various senses of the verb).",
  "lascivient - Lascivious. [Obs.] Dr. H. More.",
  "ignescent - Emitting sparks of fire when struck with steel; scintillating; as, ignescent stones.",
  "be-all - The whole; all that is to be. [Poetic] Shak.",
  "porosity - The quality or state of being porous; -- opposed to density.",
  "flammability - The quality of being flammable; inflammability. [Obs.] Sir T. Browne.",
  "illumine - To illuminate; to light up; to adorn.",
  "chromoplastid - A protoplasmic granule of some other color than green; -- also called chromoleucite.",
  "emendately - Without fault; correctly. [Obs.]",
  "synedral - Growing on the angles of a stem, as the leaves in some species of Selaginella.",
  "raton - A small rat. [Obs.] Piers Plowman.",
  "historiette - Historical narration on a small scale; a brief recital; a story. Emerson.",
  "manie - Mania; insanity. [Obs.] Chaucer.",
  "tarquinish - Like a Tarquin, a king of ancient Rome; proud; haughty; overbearing.",
  "tramrail - An overhead rail forming a track on which a trolley runs to convey a load, as in a shop.",
  "paresis - Incomplete paralysis, affecting motion but not sensation.",
  "acne - A pustular affection of the skin, due to changes in the sebaceous glands.",
  "shide - A thin board; a billet of wood; a splinter. [Prov. Eng.]",
  "medium-sized - Having a medium size; as, a medium-sized man.",
  "repand - Having a slightly undulating margin; -- said of leaves.",
  "complexus - A complex; an aggregate of parts; a complication.",
  "bacharach - A kind of wine made at Bacharach on the Rhine.",
  "sea-gate - A long, rolling swell of the sea. Ham. Nav. Encyc.",
  "concerned - Disturbed; troubled; solicitous; as, to be much concerned for the safety of a friend.",
  "scripturalness - Quality of being scriptural.",
  "feigning - That feigns; insincere; not genuine; false. -- Feign\"ing*ly, adv.",
  "cultrated - Sharp-edged and pointed; shaped like a pruning knife, as the beak of certain birds.",
  "artocarpeous - Of or pertaining to the breadfruit, or to the genus Artocarpus.",
  "conceptional - Pertaining to conception.",
  "infraorbital - Below the orbit; as, the infraorbital foramen; the infraorbital nerve.",
  "ravissant - In a half-raised position, as if about to spring on prey.",
  "vagarious - Given to, or characterized by, vagaries; capricious; whimsical; crochety.",
  "multinominous - Having many names or terms.",
  "unintermission - Want or failure of intermission. [R.] Bp. Parker.",
  "decime - A French coin, the tenth part of a franc, equal to about two cents.",
  "shilfa - The chaffinch; -- so named from its call note. [Prov. Eng.]",
  "gros - A heavy silk with a dull finish; as, gros de Naples; gros de Tours.",
  "hobbly - Rough; uneven; causing one to hobble; as a hobbly road.",
  "rug-gowned - Wearing a coarse gown or shaggy garment made of rug. Beau. & Fl.",
  "poachy - Wet and soft; easily penetrated by the feet of cattle; -- said of land",
  "bolar - Of or pertaining to bole or clay; partaking of the nature and qualities of bole; clayey.",
  "codicillary - Of the nature of a codicil.",
  "unijugate - Having but one pair of leaflets; -- said of a pinnate leaf.",
  "extender - One who, or that which, extends or stretches anything.",
  "leechcraft - The art of healing; skill of a physician. [Archaic] Chaucer.",
  "shoo - Begone; away; -- an expression used in frightening away animals, especially fowls.",
  "marmorosis - The metamorphism of limestone, that is, its conversion into marble. Geikie.",
  "chelifer - See Book scorpion, under Book.",
  "effront - To give assurance to. [Obs.] Sir T. Browne.",
  "logan - A rocking or balanced stone. Gwill.",
  "sphalerite - Zinc sulphide; -- called also blende, black-jack, false galena, etc. See Blende (a).",
  "gristle - Cartilage. See Cartilage. Bacon.",
  "seditionary - An inciter or promoter of sedition. Bp. Hall.",
  "thermotensile - Pertaining to the variation of tensile strength with the temperature.",
  "marconigram - A Marconi wireless message.",
  "impressibility - The quality of being impressible; susceptibility.",
  "interminableness - The state of being endless.",
  "southeastern - Of or pertaining to the southeast; southeasterly.",
  "testator - A man who makes and leaves a will, or testament, at death.",
  "whirlpit - A whirlpool. [Obs.] \"Raging whirlpits.\" Sandys.",
  "incorresponding - Not corresponding; disagreeing. [R.] Coleridge.",
  "tetraspaston - A machine in which four pulleys act together. Brande & C.",
  "noematical - Of or pertaining to the understanding. [Obs.] Cudworth.",
  "froufrou - A rustling, esp. the rustling of a woman's dress.",
  "rigolette - A woman's light scarflike head covering, usually knit or crocheted of wool.",
  "inamovable - Not amovable or removable. [R.] Palgrave.",
  "hoofbound - Having a dry and contracted hoof, which occasions pain and lameness.",
  "dodd - To cut off, as wool from sheep's tails; to lop or clip off. Halliwell.",
  "entomostracan - Relating to the Entomostraca. -- n.  One of the Entomostraca.",
  "aret - To reckon; to ascribe; to impute. [Obs.] Chaucer.",
  "dislikeful - Full of dislike; disaffected; malign; disagreeable. [Obs.] Spenser.",
  "nodation - Act of making a knot, or state of being knotted. [R.]",
  "illocality - Want of locality or place. [R.] Cudworth.",
  "unbreast - To disclose, or lay open; to unbosom. [Obs.] P. Fletcher,",
  "prentice - An apprentice. [Obs. or Colloq.] Piers Plowman. \"My accuser is my prentice.\" Shak.",
  "typesetting - The act or art of setting type.",
  "opuntia - A genus of cactaceous plants; the prickly pear, or Indian fig.",
  "disputacity - Proneness to dispute. [Obs.] Bp. Ward.",
  "prolocutorship - The office of a prolocutor.",
  "hieron - A consecrateo place; esp., a temple."
]