export default [
  "polariscopy - The art or rocess of making observations with the polariscope.",
  "probality - Probability. [Obs.] \"With as great probality.\" Holland.",
  "calcedon - A foul vein, like chalcedony, in some precious stones.",
  "anglomania - A mania for, or an inordinate attachment to, English customs, institutions, etc.",
  "domett - A kind of baize of which the ward is cotton and the weft woolen. Blakely.",
  "trumplike - Resembling a trumpet, esp. in sound; as, a trumplike voice. Chapman.",
  "blowy - Windy; as, blowy weather; a blowy upland.",
  "comprehensibility - The quality or state of being comprehensible; capability of being understood.",
  "collish - A tool to polish the edge of a sole. Knight.",
  "cribration - The act or process of separating the finer parts of drugs from the coarser by sifting.",
  "antiorgastic - Tending to allay venereal excitement or desire; sedative.",
  "dregginess - Fullness of dregs or lees; foulness; feculence.",
  "aeroscopy - The observation of the state and variations of the atmosphere.",
  "pneumonitis - Inflammation of the lungs; pneumonia.",
  "memorializer - One who petitions by a memorial. T. Hook.",
  "oscillometer - An instrument for measuring the angle through which a ship rolls or pitches at sea.",
  "amarine - A characteristic crystalline substance, obtained from oil of bitter almonds.",
  "booker - One who enters accounts or names, etc., in a book; a bookkeeper.",
  "magnetizer - One who, or that which, imparts magnetism.",
  "overfront - To confront; to oppose; to withstand. [Obs.] Milton.",
  "pityroid - Having the form of, or resembling, bran. Smart.",
  "unset - Not set; not fixed or appointed.",
  "ascospore - One of the spores contained in the asci of lichens and fungi. [See Illust. of Ascus.]",
  "scantiness - Quality condition of being scanty.",
  "turritelloid - Of, pertaining to, or resembling, the turritellas.",
  "plutarchy - Plutocracy; the rule of wealth. [R.]",
  "nodule - A rounded mass or irregular shape; a little knot or lump.",
  "neoplasty - Restoration of a part by granulation, adhesive inflammation, or autoplasty.",
  "endocarp - The inner layer of a ripened or fructified ovary.",
  "gismondite - A native hydrated silicate of alumina, lime, and potash, first noticed near Rome.",
  "dibranchiate - Having two gills. -- n.  One of the Dibranchiata.",
  "unaidable - Incapable of being aided. \"Her unaidable estate.\" Shak.",
  "saccharify - Toconvert into, or to impregnate with, sugar.",
  "surrebuter - The reply of a plaintiff to a defendant's rebutter.",
  "tussicular - Of or pertaining to a cough. Dunglison.",
  "autogenously - In an autogenous manner; spontaneously.",
  "balanoglossus - A peculiar marine worm. See Enteropneusta, and Tornaria.",
  "shasta - A mountain peak, etc., in California.",
  "fricatrice - A lewd woman; a harlot. [Obs.] B. Jonson.",
  "antivaccination - Opposition to vaccination. London Times.",
  "retaker - One who takes again what has been taken; a recaptor. Kent.",
  "supramundane - Being or situated above the world or above our system; celestial.",
  "disasterly - Disastrously. [Obs.] Drayton.",
  "ordering - Disposition; distribution; management. South.",
  "immechanical - Not mechanical. [Obs.] Cheyne. -- Im\"me*chan\"ic*al*ly, adv. [Obs.]",
  "memoria - Memory. Memoria technica, technical memory; a contrivance for aiding the memory.",
  "sextolet - A double triplet; a group of six equal notes played in the time of four.",
  "inisle - To form into an island; to surround. [Obs.] Drayton.",
  "enacture - Enactment; resolution. [Obs.] Shak.",
  "indefeasibility - The quality of being undefeasible.",
  "unpolish - To deprive of polish; to make impolite.",
  "xenogenetic - Of or pertaining to xenogenesis; as, the xenogenetic origin of microzymes. Huxley.",
  "maculation - The act of spotting; a spot; a blemish. Shak.",
  "historiographership - The office of an historiographer. Saintsbury.",
  "howell - The upper stage of a porcelian furnace.",
  "philopolemic - Fond of polemics or controversy. [R.]",
  "argilliferous - Producing clay; -- applied to such earths as abound with argil. Kirwan.",
  "conterminant - Having the same limits; ending at the same time; conterminous. Lamb.",
  "pornographic - Of or pertaining to pornography; lascivious; licentious; as, pornographic writing.",
  "aggeration - A heaping up; accumulation; as, aggerations of sand. [R.]",
  "appendency - State of being appendant; appendance. [Obs.]",
  "duckbill - See Duck mole, under Duck, n.",
  "photographer - One who practices, or is skilled in, photography.",
  "trainy - Belonging to train oil. [Obs.] Gay.",
  "growan - A decomposed granite, forming a mass of gravel, as in tin lodes in Cornwall.",
  "agog - In eager desire; eager; astir. All agog to dash through thick and thin. Cowper.",
  "retentivity - The power of retaining; retentive force; as, the retentivity of a magnet.",
  "draglink - (a) A link connecting the cranks of two shafts. (b) A drawbar.",
  "unlawlike - Not according to law; being or done in violation of law; unlawful. Milton.",
  "symposiast - One engaged with others at a banquet or merrymaking. Sydney Smith.",
  "underhonest - Not entirely honest. [R.] \"We think him overproud and underhonest.\" Shak.",
  "boarish - Swinish; brutal; cruel. In his anointed flesh stick boarish fangs. Shak.",
  "coleorhiza - A sheath in the embryo of grasses, inclosing the caulicle. Gray.",
  "neuropore - An opening at either end of the embryonic neural canal.",
  "chicaner - One who uses chicanery. Locke.",
  "fantasied - Filled with fancies or imaginations. [Obs.] Shak.",
  "dignified - Marked with dignity; stately; as, a dignified judge.",
  "proteiform - Changeable in form; resembling a Proteus, or an amoeba.",
  "plausive - 1. Applauding; manifesting praise. Young. 2. Plausible, specious. [Obs.] Shak.",
  "ellipsograph - An instrument for describing ellipses; -- called also trammel.",
  "steerer - One who steers; as, a boat steerer.",
  "dehisce - To gape; to open by dehiscence.",
  "pyrolithic - Same as Pyrouric, or Cyanuric.",
  "antiputrefactive - Counteracting, or preserving from, putrefaction; antiseptic.",
  "granulous - Full of grains; abounding with granular substances; granular.",
  "antarchist - One who opposes all government. [R.]",
  "jejunity - The quality of being jejune; jejuneness.",
  "benefic - Favorable; beneficent. Milton.",
  "umbrate - To shade; to shadow; to foreshadow. [Obs.]",
  "hamfatter - A low-grade actor or performer. [Theatrical Slang]",
  "pallidness - The quality or state of being pallid; paleness; pallor; wanness.",
  "penitentially - In a penitential manner.",
  "helminth - An intestinal worm, or wormlike intestinal parasite; one of the Helminthes.",
  "bourbonist - One who adheres to the house of Bourbon; a legitimist.",
  "doodlesack - The Scotch bagpipe. [Prov. Eng.]",
  "carcinomatous - Of or pertaining to carcinoma.",
  "populist - A member of the People's party. -- Pop`u*lis\"tic (#), a.",
  "nidulate - To make a nest, as a bird. [R.] Cockeram.",
  "enrapt - Thrown into ecstasy; transported; enraptured. Shak.",
  "twitlark - The meadow pipit. [Prov. Eng.]",
  "connoisseurship - State of being a connoisseur.",
  "henhussy - A cotquean; a man who intermeddles with women's concerns.",
  "decrepitness - Decrepitude. [R.] Barrow.",
  "physicianed - Licensed as a physician. [Obs.] \"A physicianed apothecary.\" Walpole.",
  "waddywood - An Australian tree (Pittosporum bicolor); also, its wood, used in making waddies.",
  "insaniate - To render unsound; to make mad. [Obs.] Feltham.",
  "unrumple - To free from rumples; to spread or lay even,",
  "categoricalness - The quality of being categorical, positive, or absolute. A. Marvell.",
  "craniologist - One proficient in craniology; a phrenologist.",
  "wriggler - One who, or that which, wriggles. Cowper.",
  "cruddle - To curdle. [Obs.] See how thy blood cruddles at this. Bea",
  "cartilagineous - See Cartilaginous. Ray.",
  "scrid - A screed; a shred; a fragment. [R.]",
  "unreverence - Absence or lack of reverence; irreverence. [Obs.] Wyclif.",
  "papery - Like paper; having the thinness or consistence of paper. Gray.",
  "surveyorship - The office of a surveyor.",
  "incavation - Act of making hollow; also, a hollow; an exvation; a depression.",
  "comfortably - In a comfortable or comforting manner. Speak ye comfortably to Jerusalem. Is. xl. 2.",
  "perishment - The act of perishing. [R.] Udall.",
  "transship - To transfer from one ship or conveyance to another. [Written also tranship.]",
  "caveating - Shifting the sword from one side of an adversary's sword to the other.",
  "misanthropos - A misanthrope. [Obs.] Shak.",
  "semicastrate - To deprive of one testicle. -- Sem`i*cas*tra\"tion,n.",
  "imperceptibility - The state or quality of being imperceptible.",
  "overseas - Over the sea; abroad. Milton. Tennyson.",
  "slyness - The quality or state of being sly.",
  "spatterdashed - Wearing spatterdashes. [Colloq.] Thackeray.",
  "gephyrean - Belonging to the Gephyrea. -- n. One of the Gerphyrea.",
  "sea partridge - The gilthead (Crenilabrus melops), a fish of the British coasts.",
  "frugiferous - Producing fruit; fruitful; fructiferous. Dr. H. More.",
  "nopalry - A plantation of the nopal for raising the cochineal insect.",
  "natals - One's birth, or the circumstances attending it. [Obs.] Fitz- Geffry.",
  "inapplication - Want of application, attention, or diligence; negligence; indolence.",
  "bacteriology - The science relating to bacteria.",
  "oblique-angled - Having oblique angles; as, an oblique-angled triangle.",
  "glycosometer - An apparatus for determining the amount of sugar in diabetic urine.",
  "recussion - The act of beating or striking back.",
  "chout - An assessment equal to a fourth part of the revenue. [India] J. Mill.",
  "poicile - The frescoed porch or gallery in Athens where Zeno taught. R. Browning.",
  "animalculine - Of, pertaining to, or resembling, animalcules. \"Animalcular life.\" Tyndall.",
  "premiant - Serving to reward; rewarding. [R.] Baxter.",
  "epochal - Belonging to an epoch; of the nature of an epoch. \"Epochal points.\" Shedd.",
  "gomphiasis - A disease of the teeth, which causes them to loosen and fall out of their sockets.",
  "retreatment - The act of retreating; specifically, the Hegira. [R.] D'Urfey.",
  "staggard - The male red deer when four years old.",
  "touchiness - The quality or state of being touchy peevishness; irritability; irascibility.",
  "bivalency - The quality of being bivalent.",
  "sycite - A nodule of flint, or a pebble, which resembles a fig. [Obs.]",
  "snew - To snow; to abound. [Obs.] It snewed in his house of meat and drink. Chaucer.",
  "individualizer - One who individualizes.",
  "scutibranch - Scutibranchiate. -- n.  One of the Scutibranchiata.",
  "mayduke - A large dark-red cherry of excellent quality.",
  "biblicism - Learning or literature relating to the Bible. [R.]",
  "patroonship - The office of a patroon. Irving.",
  "bloodletter - One who, or that which, lets blood; a phlebotomist.",
  "nonperformance - Neglect or failure to perform.",
  "dulcinea - A mistress; a sweetheart. I must ever have some Dulcinea in my head. Sterne.",
  "unforesee - To fail to foresee. Bp. Hacket.",
  "phoenicopterus - A genus of birds which includes the flamingoes.",
  "trivalvular - Having three valves; three-valved.",
  "unglorify - To deprive of glory. [R.] I. Watts.",
  "haymaking - The operation or work of cutting grass and curing it for hay.",
  "dizzard - A blockhead. [Obs.] [Written also dizard, and disard.] -- Diz\"zard*ly, adv. [Obs.]",
  "granger shares - Stocks or shares of the granger railroads.",
  "flanged - Having a flange or flanges; as, a flanged wheel.",
  "magazinist - One who edits or writes for a magazine. [R.]",
  "multicapsular - Having many, or several, capsules.",
  "masquerader - One who masquerades; a person wearing a mask; one disguised.",
  "unreal - Not real; unsubstantial; fanciful; ideal.",
  "clement - Mild in temper and disposition; merciful; compassionate. Shak. -- Clem\"ent*ly, adv.",
  "unbrewed - Not made by brewing; unmixed; pure; genuine. [R.] Young.",
  "madreporiform - Resembling a madreporian coral in form or structure.",
  "adversion - A turning towards; attention. [Obs.] Dr. H. More.",
  "bengalese - Of or pertaining to Bengal. -- n. sing. & pl. A native or natives of Bengal.",
  "crotalus - A genus of poisonous serpents, including the rattlesnakes.",
  "weatherwiser - Something that foreshows the weather. [Obs.] Derham.",
  "biconjugate - Twice paired, as when a petiole forks twice. Gray.",
  "gynoecium - The pistils of a flower, taken collectively. See Illust. of Carpophore.",
  "pulicene - Pertaining to, or abounding in, fleas; pulicose.",
  "exciteful - Full of exciting qualities; as, an exciteful story; exciteful players. Chapman.",
  "phalansterism - A system of phalansteries proposed by Fourier; Fourierism.",
  "predomination - The act or state of predominating; ascendency; predominance. W. Browne.",
  "conducibleness - Quality of being conducible.",
  "impawn - To put in pawn; to pledge. Shak.",
  "willier - One who works at a willying machine.",
  "affreighter - One who hires or charters a ship to convey goods.",
  "dispender - One who dispends or expends; a steward. [Obs.] Wyclif (1 Cor. iv. 1).",
  "incipience - Beginning; commencement; incipient state.",
  "heartstrike - To affect at heart; to shock. [R.] \"The seek to heartstrike us.\" B. Jonson.",
  "forcite - A gelatin dynamite in which the dope is composed largely of sodium nitrate.",
  "beneficed - Possessed of a benefice o \"Beneficed clergymen.\" Burke.",
  "artificiality - The quality or appearance of being artificial; that which is artificial.",
  "fibrination - The state of acquiring or having an excess of fibrin.",
  "placidness - The quality or state of being placid.",
  "weak-kneed - Having weak knees; hence, easily yielding; wanting resolution. H. James.",
  "metallochromy - The art or process of coloring metals.",
  "sullevate - To rouse; to excite. [Obs.] Daniel.",
  "obstetrician - One skilled in obstetrics; an accoucheur.",
  "let-up - Abatement; also, cessation; as, it blew a gale for three days without any let-up. [Colloq.]",
  "siliciferous - Producing silica; united with silica.",
  "metathoracic - Of or pertaining to the metathorax.",
  "fossulate - Having, or surrounded by, long, narrow depressions or furrows.",
  "pneumotherapy - The treatment of disease by inhalations of compressed or rarefied air.",
  "synsepalous - Having united sepals; gamosepalous.",
  "transaudient - Permitting the passage of sound. [R.] Lowell.",
  "archchemic - Of supreme chemical powers. [R.] \"The archchemic sun.\" Milton.",
  "venatorial - Or or pertaining to hunting; venatic. [R.]",
  "chivarras - Leggings. [Mex. & Southwestern U. S.]",
  "intercomparison - Mutual comparison of corresponding parts.",
  "windbore - The lower, or bottom, pipe in a lift of pumps in a mine. Ansted.",
  "not-pated - Same as Nott-headed. [Obs.] Shak.",
  "weigh-house - A building at or within which goods, and the like, are weighed.",
  "coly - Any bird of the genus Colius and allied genera. They inhabit Africa.",
  "breastfast - A large rope to fasten the midship part of a ship to a wharf, or to another vessel.",
  "terpilene - A polymeric form of terpene, resembling terbene.",
  "pictured - Furnished with pictures; represented by a picture or pictures; as, a pictured scene.",
  "recreancy - The quality or state of being recreant.",
  "sponginess - The quality or state of being spongy. Dr. H. More.",
  "craw - (a) The crop of a bird. (b) The stomach of an animal.",
  "handmaiden - A maid that waits at hand; a female servant or attendant.",
  "auncel - A rude balance for weighing, and a kind of weight, formerly used in England. Halliwell.",
  "rhinal - Og or pertaining to the nose or olfactory organs.",
  "epithalamic - Belonging to, or designed for, an epithalamium.",
  "starriness - The quality or state of being starry; as, the starriness of the heavens.",
  "purificator - One who, or that which, purifies; a purifier.",
  "gnosticism - The system of philosophy taught by the Gnostics.",
  "discloud - To clear from clouds. [Archaic] Fuller.",
  "glazier - One whose business is to set glass. Glazier's diamond. See under Diamond.",
  "praiseless - Without praise or approbation.",
  "autotoxemia - Self-intoxication. See Auto-intoxication.",
  "quercus - A genus of trees constituted by the oak. See Oak.",
  "vellicative - Having the power of vellicating, plucking, or twitching; causing vellication.",
  "bullist - A writer or drawer up of papal bulls. [R.] Harmar.",
  "conciliar - Of or pertaining to, or issued by, a council. Jer. Taylor.",
  "warefulness - Wariness; cautiousness. [Obs.] \"Full of warefulness.\" Sir P. Sidney.",
  "doughtiness - The quality of being doughty; valor; bravery.",
  "toysome - Disposed to toy; trifling; wanton. [R.] Ford.",
  "overturnable - Capable of being, or liable to be, overturned or subverted.",
  "jalons - Long poles, topped with wisps of straw, used as landmarks and signals. Farrow.",
  "fenestrated - 1. (Arch.)  Having windows; characterized by windows. 2. Same as Fenestrate.",
  "inquisitorially - In an inquisitorial manner.",
  "alto-stratus - A cloud formation similar to cirro-stratus, but heavier and at a lower level.",
  "alumna - A female pupil; especially, a graduate of a school or college.",
  "carborundum cloth - Cloth or paper covered with powdered carborundum.",
  "infeasibleness - The state of quality of being infeasible; infeasibility. W. Montagu.",
  "departmental - Pertaining to a department or division. Burke.",
  "diandrous - Of or pertaining to the class Diandria; having two stamens.",
  "maundril - A pick with two prongs, to pry with.",
  "blive - Quickly; forthwith. [Obs.] Chaucer.",
  "perfidiousness - The quality of being perfidious; perfidy. Clarendon.",
  "somonaunce - A summons; a citation. [Obs.] Chaucer.",
  "lobar - Of or pertaining to a lobe; characterized by, or like, a lobe or lobes.",
  "jubate - Fringed with long, pendent hair.",
  "procreativeness - The power of generating.",
  "vivandier - In Continental armies, esp. the French, a sutler.",
  "whealworm - The harvest mite; -- so called from the wheals, caused by its bite.",
  "illacerable - Not lacerable; incapable of being torn or rent. [Obs.]",
  "sternutative - Having the quality of provoking to sneeze.",
  "put-off - A shift for evasion or delay; an evasion; an excuse. L'Estrange.",
  "nonproficiency - Want of proficiency; failure to make progress.",
  "suburbian - Suburban. [Obs.] \"Suburbial fields.\" Warton. \"Suburbian muse.\" Dryden.",
  "maltman - A man whose occupation is to make malt.",
  "amphilogy - Ambiguity of speech; equivocation. [R.]",
  "deep-mouthed - Having a loud and sonorous voice. \"Deep-mouthed dogs.\" Dryden.",
  "demureness - The state of being demure; gravity; the show of gravity or modesty.",
  "spurtle - To spurt or shoot in a scattering manner. [Obs.] Drayton.",
  "intermediation - The act of coming between; intervention; interposition. Burke.",
  "triangularity - The quality or state of being triangular. Bolingbroke.",
  "canker bloom - The bloom or blossom of the wild rose or dog-rose.",
  "registership - The office of a register.",
  "duykerbok - A small South African antelope (Cephalous mergens); -- called also impoon, and deloo.",
  "natively - By natural or original condition; naturally; originally.",
  "unowned - 1. Not owned; having no owner. Milton. 2. Not acknowledged; not avowed. Gay.",
  "cessible - Giving way; yielding. [Obs.] -- Ces`si*bil\"i*ty, n. [Obs.] Sir K. Digby.",
  "myoid - Composed of, or resembling, muscular fiber.",
  "occasionality - Quality or state of being occasional; occasional occurrence. [R.]",
  "fodientia - A group of African edentates including the aard-vark.",
  "estrepe - To strip or lay bare, as land of wood, houses, etc.; to commit waste.",
  "unwedgeable - Not to be split with wedges. [Obs.] Shak.",
  "unbiased - Free from bias or prejudice; unprejudiced; impartial. -- Un*bi\"ased*ness, n.",
  "indoor - Done or being within doors; within a house or institution; domestic; as, indoor work.",
  "notelessness - A state of being noteless.",
  "rament - 1. A scraping; a shaving. [Obs.]",
  "avowed - Openly acknowledged or declared; admitted. -- A*vow\"ed*ly (, adv.",
  "tabaret - A stout silk having satin stripes, -- used for furniture.",
  "homeopathist - A believer in, or practitioner of, homeopathy. [Written also homoepathist.]",
  "concrew - To grow together. [Obs.] Spenser.",
  "exhume - To dig out of the ground; to take out of a place of burial; to disinter. Mantell.",
  "lymphangeitis - Inflammation of the lymphatic vessels. [Written also lymphangitis.]",
  "cork fossil - A variety of amianthus which is very light, like cork.",
  "boathouse - A house for sheltering boats. Half the latticed boathouse hides. Wordsworth.",
  "tidiness - The quality or state of being tidy.",
  "renewer - One who, or that which, renews.",
  "injudiciously - In an injudicious manner.",
  "nucula - A genus of small marine bivalve shells, having a pearly interior.",
  "pauxi - A curassow (Ourax pauxi), which, in South America, is often domesticated.",
  "achromatous - Lacking, or deficient in, color; as, achromatous blood.",
  "necessariness - The quality of being necessary.",
  "optable - That may be chosen; desirable. [Obs.] Cockeram.",
  "chloralism - A morbid condition of the system resulting from excessive use of chloral.",
  "neuro- - A combining denoting a nerve, of or pertaining to a nerve or the nervous system.",
  "lapidifical - Forming or converting into stone.",
  "electrition - The recognition by an animal body of the electrical condition of external objects.",
  "semiditone - A lesser third, having its terms as 6 to 5; a hemiditone. [R.]",
  "provincialist - One who lives in a province; a provincial.",
  "amygdalaceous - Akin to, or derived from, the almond.",
  "disemploy - To throw out of employment. [Obs.] Jer. Taylor.",
  "apnoea - Partial privation or suspension of breath; suffocation.",
  "journeywork - Originally, work done by the day; work done by a journeyman at his trade.",
  "colliquament - The first rudiments of an embryo in generation. Dr. H. More.",
  "amphitheatrically - In the form or manner of an amphitheater.",
  "memorative - Commemorative. [Obs.] Hammond.",
  "tiercet - A triplet; three lines, or three lines rhyming together.",
  "designable - Capable of being designated or distinctly marked out; distinguishable. Boyle.",
  "emollition - The act of softening or relaxing; relaxation. Bacon.",
  "chloriodine - A compound of chlorine and iodine. [R.]",
  "quaigh - A small shallow cup or drinking vessel. [Scot.] [Written also quegh.]",
  "steamship - A ship or seagoing vessel propelled by the power of steam; a steamer.",
  "canthus - The corner where the upper and under eyelids meet on each side of the eye.",
  "hennery - An inclosed place for keeping hens. [U. S.]",
  "pendicler - An inferior tenant; one who rents a pendicle or croft. [Scot.] Jamieson.",
  "feere - A consort, husband or wife; a companion; a fere. [Obs.]",
  "shroff - A banker, or changer of money. [East Indies]",
  "woodenly - Clumsily; stupidly; blockishly. R. North.",
  "sipunculoidea - (a) Same as Gephyrea. (b) In a restricted sense, same as Sipunculacea.",
  "providentness - The quality or state of being provident; carefulness; prudence; economy.",
  "individuity - Separate existence; individuality; oneness. Fuller.",
  "furacious - Given to theft; thievish. [Obs.]",
  "redolence - The quality of being redolent; sweetness of scent; pleasant odor; fragrance.",
  "unthriftfully - Not thriftily. [Obs.] \"Unthriftfully spent.\" Sir J. Cheke.",
  "biflabellate - Flabellate on both sides.",
  "gravelly - Abounding with gravel; consisting of gravel; as, a gravelly soil.",
  "twaddler - One who prates in a weak and silly manner, like one whose faculties are decayed.",
  "bethump - To beat or thump soundly. Shak.",
  "abirritant - A medicine that diminishes irritation.",
  "eyeflap - A blinder on a horse's bridle.",
  "misenter - To enter or insert wrongly, as a charge in an account.",
  "jovialist - One who lives a jovial life. Bp. Hall.",
  "incommodate - To incommode. [Obs.] Bp. Hall.",
  "orangite - An orange-yellow variety of the mineral thorite, found in Norway.",
  "spicular - Resembling a dart; having sharp points.",
  "undock - To take out of dock; as, to undock a ship.",
  "pudendal - Of or pertaining to the pudenda, or pudendum.",
  "cormoraut - Ravenous; voracious. Cormorant, devouring time. Shak.",
  "fundable - Capable of being funded, or converted into a fund; convertible into bonds.",
  "accordantly - In accordance or agreement; agreeably; conformably; -- followed by with or to.",
  "quadrinodal - Possessing four nodes; as, quadrinodal curves.",
  "exterminator - One who, or that which, exterminates. Buckle.",
  "executrix - A woman exercising the functions of an executor.",
  "tetradactylous - Having, or characterized by, four digits to the foot or hand.",
  "entasis - 1. (Arch.)  A slight convex swelling of the shaft of a column. 2. (Med.)  Same as Entasia.",
  "carene - A fast of forty days on bread and water. [Obs.]",
  "relatedness - The state or condition of being related; relationship; affinity. [R.] Emerson.",
  "conchometer - An instrument for measuring shells, or the angle of their spire.",
  "legislatively - In a legislative manner.",
  "dastardize - To make cowardly; to intimidate; to dispirit; as, to dastardize my courage. Dryden.",
  "paradactylum - The side of a toe or finger.",
  "misbegot - Unlawfully or irregularly begotten; of bad origin; pernicious. \"Valor misbegot.\" Shak.",
  "gnathonic - Flattering; deceitful. [Obs.]",
  "containable - Capable of being contained or comprised. Boyle.",
  "scopiferous - Bearing a tuft of brushlike hairs.",
  "ydrad - Dreaded. Yet nothing did he dread, but ever was ydrad. Spenser.",
  "petitioner - One who presents a petition.",
  "telic - Denoting the final end or purpose, as distinguished from ecbatic. See Ecbatic. Gibbs.",
  "forcut - To cut completely; to cut off. [Obs.] Chaucer.",
  "postexistent - Existing or living after. [R.] \"Postexistent atoms.\" Cudworth.",
  "tailoring - The business or the work of a tailor or a tailoress.",
  "credibleness - The quality or state of being credible; worthness of belief; credibility. [R.] Boyle.",
  "plagiotropic - Having the longer axis inclined away from the vertical line.",
  "octogenarian - A person eighty years, or more, of age.",
  "subvariety - A subordinate variety, or a division of a variety.",
  "sockless - Destitute of socks or shoes. B. & Fl.",
  "arroyo - 1. A water course; a rivulet. 2. The dry bed of a small stream. [Western U. S.]",
  "enthelminthes - Intestinal worms. See Helminthes.",
  "esparcet - The common sainfoin (Onobrychis sativa), an Old World leguminous forage plant.",
  "chymic - See Chemic, Chemist, Chemistry.",
  "chronopher - An instrument signaling the correct time to distant points by electricity.",
  "water-soak - To soak water; to fill the interstices of with water.",
  "elvishly - In an elvish manner. Sir W. Scott.",
  "inductric - Acting by, or in a state of, induction; relating to electrical induction.",
  "discomposition - Inconsistency; discordance. [Obs.] Donne.",
  "intuse - A bruise; a contusion. [Obs.] Spenser.",
  "ribbonman - A member of the Ribbon Society. See Ribbon Society, under Ribbon.",
  "briskness - Liveliness; vigor in action; quickness; gayety; vivacity; effervescence.",
  "charpie - Straight threads obtained by unraveling old linen cloth; -- used for surgical dressings.",
  "logicalness - The quality of being logical.",
  "raggie - Ragged; rough. [Obs.] \"A stony and raggie hill.\" Holland.",
  "ciselure - The process of chasing on metals; also, the work thus chased. Weale.",
  "suicidal - Partaking of, or of the nature of, the crime or suicide. -- Su\"i*ci`dal*ly, adv.",
  "paleocrystic - Of, pertaining to, or derived from, a former glacial formation.",
  "cachou - A silvered aromatic pill, used to correct the odor of the breath.",
  "poldway - A kind of coarse bagging, -- used for coal sacks. Weale.",
  "unorderly - Disorderly. [Obs.] Bp. Sanderson.",
  "monothecal - Having a single loculament.",
  "bespeckle - To mark with speckles or spots. Milton.",
  "motherless - Destitute of a mother; having lost a mother; as, motherless children.",
  "nephrotomy - Extraction of stone from the kidney by cutting.",
  "jacketed - Wearing, or furnished with, a jacket.",
  "airwoman - A woman who ascends or flies in an aircraft.",
  "sportsmanship - The practice of sportsmen; skill in field sports.",
  "tetard - A gobioid fish (Eleotris gyrinus) of the Southern United States; -- called also sleeper.",
  "quadrivalvular - Having four valves; quadrivalve.",
  "owelty - Equality; -- sometimes written ovelty and ovealty. Burrill.",
  "slighting - Characterized by neglect or disregard.",
  "cerumen - The yellow, waxlike secretion from the glands of the external ear; the earwax.",
  "beslaver - To defile with slaver; to beslobber.",
  "cummerbund - A sash for the waist; a girdle. [India]",
  "anthropometric - Pertaining to anthropometry.",
  "rotated - Turned round, as a wheel; also, wheel-shaped; rotate.",
  "evaporative - Pertaining to, or producing, evaporation; as, the evaporative process.",
  "sublate - To take or carry away; to remove. [R.] E. Hall.",
  "obsequent - Obedient; submissive; obsequious. [Obs.] Fotherby.",
  "philosophate - To play the philosopher; to moralize. [Obs.] Barrow.",
  "photomezzotype - A photomechanical process similar to collotype.",
  "tinamides - A division of struthious birds, including the tinamous.",
  "lilial - Having a general resemblance to lilies or to liliaceous plants.",
  "federalism - the principles of Federalists or of federal union.",
  "vafrous - Crafty; cunning; sly; as, vafrous tricks. [Obs.] Feltham.",
  "recidivous - Tending or liable to backslide or r",
  "ostleress - A female ostler. [R.] Tennyson.",
  "aviso - 1. Information; advice. 2. An advice boat, or dispatch boat.",
  "nagana - The disease caused by the tsetse fly. [South Africa]",
  "sper - To shut in; to support; to inclose; to fasten. [Obs.] \"To sperre the gate.\" Spenser.",
  "reprehensive - Containing reprehension; conveying reproof. South. -- Rep`re*hen\"sive*ly, adv.",
  "barbadian - Of or pertaining to Barbados. -- n.  A native of Barbados.",
  "forthputing - Bold; forward; aggressive.",
  "kapia - The fossil resin of the kauri tree of New Zealand.",
  "stably - In a stable manner; firmly; fixedly; steadily; as, a government stably settled.",
  "spottiness - The state or quality of being spotty.",
  "cross-examiner - One who cross-examines or conducts a crosse-examination.",
  "trente et quarante - Same as Rouge et noir, under Rouge.",
  "paleographist - One versed in paleography; a paleographer.",
  "glandiferous - Bearing acorns or other nuts; as, glandiferous trees.",
  "assapanic - The American flying squirrel (Pteromys volucella).",
  "gyrogonite - The petrified fruit of the Chara hispida, a species of stonewort. See Stonewort. Lyell.",
  "heterocephalous - Bearing two kinds of heads or capitula; -- said of certain composite plants.",
  "inamorata - A woman in love; a mistress. \"The fair inamorata.\" Sherburne.",
  "confidentness - The quality of being confident.",
  "sappiness - The quality of being sappy; juiciness.",
  "regalian - Pertaining to regalia; pertaining to the royal insignia or prerogatives. Hallam.",
  "childishly - In the manner of a child; in a trifling way; in a weak or foolish manner.",
  "cinchonize - To produce cinchonism in; to poison with quinine or with cinchona.",
  "hydrogenium - Hydrogen; -- called also in view of its supposed metallic nature. Graham.",
  "kidneywort - (a) A kind of saxifrage (Saxifrage stellaris). (b) The navelwort.",
  "exhibitory - Exhibiting; publicly showing. J. Warton.",
  "diageotropic - Relating to, or exhibiting, diageotropism.",
  "multangular - Having many angles. -- Mul*tan\"gu*lar*ly, adv. -- Mul*tan\"gu*lar*ness, n.",
  "spreadingly - , adv. Increasingly. The best times were spreadingly infected. Milton.",
  "pleased - Experiencing pleasure. -- Pleas\"ed*ly, adv. -- Pleas\"ed*ness, n.",
  "bibliopegic - Relating to the binding of books. [R.]",
  "palterly - Paltry; shabby; shabbily; paltrily. [Obs. or Prov. Eng.] \"In palterly clothes.\" Pepys.",
  "domeykite - A massive mineral of tin-white or steel-gray color, an arsenide of copper.",
  "wanger - A pillow for the cheek; a pillow. [Obs. & R.] His bright helm was his wanger. Chaucer.",
  "flockling - A lamb. [Obs.] Brome (1659).",
  "enfeeblish - To enfeeble. [Obs.] Holland.",
  "taplings - The strong double leathers by which the two parts of a flail are united. Halliwell.",
  "cubdrawn - Sucked by cubs. [R.] This night, wherein the cub-drawn bear would couch. Shak.",
  "swartish - Somewhat swart, dark, or tawny.",
  "saponifiable - Capable of conversion into soap; as, a saponifiable substance.",
  "reconcentrate - To concentrate again; to concentrate thoroughly.",
  "clake - The bernicle goose; -- called also clack goose.",
  "catchment - A surface of ground on which water may be caught and collected into a reservoir.",
  "otto engine - An engine using the Otto cycle.",
  "demarcate - To mark by bounds; to set the limits of; to separate; to discriminate. Wilkinson.",
  "buggery - Unnatural sexual intercourse; sodomy.",
  "aporetical - Doubting; skeptical. [Obs.] Cudworth.",
  "jargonelle - A variety of pear which ripens early.",
  "finn - A native of Finland; one of the FinnFinns.",
  "racial - Of or pertaining to a race or family of men; as, the racial complexion.",
  "colotomy - An operation for opening the colon",
  "shallowness - Quality or state of being shallow.",
  "asthenopia - Weakness of sight. Quain. -- As`the*nop\"ic, a.",
  "tuum - Lit., thine; that which is thine; -- used in meum and tuum. See 2d Meum.",
  "acephalocystic - Pertaining to, or resembling, the acephalocysts.",
  "fissiparity - Quality of being fissiparous; fissiparism.",
  "reedwork - A collective name for the reed stops of an organ.",
  "figurability - The quality of being figurable. Johnson.",
  "accroachment - An encroachment; usurpation. [Obs.] Bailey.",
  "zooedendrium - The branched, and often treelike, support of the colonies of certain Infusoria.",
  "pleasureless - Devoid of pleasure. G. Eliot.",
  "mitigant - Tending to mitigate; mitigating; lentitive. Johnson.",
  "warhable - Fit for war. [Obs.] \"Warhable youth.\" Spenser.",
  "allnight - Light, fuel, or food for the whole night. [Obs.] Bacon.",
  "manuring - The act of process of applying manure; also, the manure applied.",
  "sizarship - The position or standing of a sizar.",
  "subtracter - 1. One who subtracts. 2. The subtrahend. [Obs.]",
  "cabezon - A California fish (Hemilepidotus spinosus), allied to the sculpin.",
  "emplace - To put into place or position; to fix on an emplacement.",
  "genethliatic - One who calculates nativities. Sir W. Drummond.",
  "ensignship - The state or rank of an ensign.",
  "agon - A contest for a prize at the public games.",
  "annihilative - Serving to annihilate; destructive.",
  "pirameter - A dynamometer for ascertaining the power required to draw carriages over roads.",
  "bullheaded - Having a head like that of a bull. Fig.: Headstrong; obstinate; dogged.",
  "fecund - Fruitful in children; prolific. Graunt.",
  "breadthwise - In the direction of the breadth.",
  "praefloration - Same as Prefloration. Gray.",
  "highwayman - One who robs on the public road; a highway robber.",
  "mog - To move away; to go off. [Prov. Eng. or Local, U. S.]",
  "withdrawment - The act of withdrawing; withdrawal. W. Belsham.",
  "niveous - Snowy; resembling snow; partaking of the qualities of snow. Sir T. Browne.",
  "inharmonic - Not harmonic; inharmonious; discordant; dissonant.",
  "impertinently - In an impertinent manner. \"Not to betray myself impertinently.\" B. Jonson.",
  "cosine - The sine of the complement of an arc or angle. See Illust. of Functions.",
  "cox - A coxcomb; a simpleton; a gull. [Obs.] Go; you're a brainless cox, a toy, a fop. Beau. & Fl.",
  "titty - A little teat; a nipple. [Familiar]",
  "vraisemblance - The appearance of truth; verisimilitude.",
  "barbicanage - Money paid for the support of a barbican. [Obs.]",
  "gainless - Not producing gain; unprofitable. Hammond. -- Gain\"less/ness, n.",
  "plasmodial - Of or pertaining to, or like, a plasmodium; as, the plasmodial form of a life cycle.",
  "multiplicable - Capable of being multiplied; multipliable.",
  "culpability - The state of being culpable.",
  "ostracoid - Of or pertaining to the Ostracoidea. -- n.  One of the Ostracoidea.",
  "suppedaneous - Being under the feet. [Obs.] Sir T. Browne.",
  "icositetrahedron - A twenty-four-sided solid; a tetragonal trisoctahedron or trapezohedron.",
  "attitudinarianism - A practicing of attitudes; posture making.",
  "phthisical - Of or pertaining to phthisis; affected with phthisis; wasting; consumptive.",
  "boyer - A Flemish sloop with a castle at each end. Sir W. Raleigh.",
  "erstwhile - Till then or now; heretofore; formerly. [Archaic]",
  "helmed - Covered with a helmet. The helmed cherubim Are seen in glittering ranks. Milton.",
  "nightfall - The close of the day. Swift.",
  "slumpy - Easily broken through; boggy; marshy; swampy. [Prov. Eng. & Colloq. U.S.] Bartlett.",
  "ablet - A small fresh-water fish (Leuciscus alburnus); the bleak.",
  "unripe - 1. Not ripe; as, unripe fruit. 2. Developing too early; premature. Sir P. Sidney.",
  "tritheistic - Of or pertaining to tritheism. Bolingbroke.",
  "ariette - A short aria, or air. \"A military ariette.\" Sir W. Scott.",
  "hydrosulphate - Same as Hydrosulphurent.",
  "passementerie - Beaded embroidery for women's dresses.",
  "pronephron - The head kidney. See under Head.",
  "antivivisection - Opposition to vivisection.",
  "tribal - Of or pertaining to a tribe or tribes; as, a tribal scepter. Bp. Warburton.",
  "valvula - A little valve or fold; a valvelet; a valvule.",
  "eccentrically - In an eccentric manner. Drove eccentrically here and there. Lew Wallace.",
  "semihistorical - Half or party historical. Sir G. C. Lewis.",
  "oxycrate - A Mixture of water and vinegar. Wiseman.",
  "ungifted - Being without gifts, especially native gifts or endowments. Cowper.",
  "oligosiderite - A meteorite characterized by the presence of but a small amount of metallic iron.",
  "sway-bracing - The horizontal bracing of a bridge, which prevents its swaying.",
  "platy- - A combining form from Gr. platy`s broad, wide, flat; as, platypus, platycephalous.",
  "doxy - A loose wench; a disreputable sweetheart. Shak.",
  "tormentful - Full of torment; causing, or accompainied by, torment; excruciating. [R.] Tillotson.",
  "ivoride - A composition resembling ivory in appearance and used as a substitute for it.",
  "jalousied - Furnished with jalousies; as, jalousied porches.",
  "gurlet - A pickax with one sharp point and one cutting edge. Knight.",
  "apocalyptist - The writer of the Apocalypse.",
  "enrace - To enroot; to implant. [Obs.] Spenser.",
  "beguiler - One who, or that which, beguiles.",
  "filose - Terminating in a threadlike process.",
  "hot-headed - Fiery; violent; rash; hasty; impetuous; vehement. Macaulay.",
  "frowey - Working smoothly, or without splitting; -- said of timber.",
  "piscicultural - Relating to pisciculture.",
  "disloyalty - Want of loyalty; lack of fidelity; violation of allegiance.",
  "concupy - Concupiscence. Note: [Used only in \"Troilus and Cressida\"] Shak.",
  "lineally - In a lineal manner; as, the prince is lineally descended from the Conqueror.",
  "unseminared - Deprived of virility, or seminal energy; made a eunuch. [Obs.]",
  "sideroxylon - A genus of tropical sapotaceous trees noted for their very hard wood; ironwood.",
  "sweetish - Somewhat sweet. -- Sweet\"ish*ness, n.",
  "titaniferous - Containing or affording titanium; as, titaniferous magnetite.",
  "decolor - To deprive of color; to bleach.",
  "promiscuously - In a promiscuous manner.",
  "carabao - The water buffalo. [Phil. Islands]",
  "unpassable - Impassable. E. A. Freeman. -- Un*pass\"a*ble*ness, n. Evelyn.",
  "clubbed - Shaped like a club; grasped like, or used as, a club. Skelton.",
  "nodular - Of, pertaining to, or in the form of, a nodule or knot.",
  "heartlings - An exclamation used in addressing a familiar acquaintance. [Obs.] Shak.",
  "recommitment - A second or renewed commitment; a renewed reference to a committee.",
  "nonclaim - A failure to make claim within the time limited by law; omission of claim.",
  "residentship - The office or condition of a resident.",
  "vanadium bronze - A yellow pigment consisting of a compound of vanadium.",
  "czarinian - Of or pertaining to the czar or the czarina; czarish.",
  "suspensibility - The quality or state of being suspensible.",
  "fraulein - In Germany, a young lady; an unmarried woman; -- as a title, equivalent to Miss.",
  "vaporousness - The quality of being vaporous.",
  "nubigenous - Born of, or produced from, clouds. [R.]",
  "inclinableness - The state or quality of being inclinable; inclination.",
  "inexpiate - Not appeased or placated. [Obs.] To rest inexpiate were much too rude a part. Chapman.",
  "dispersal - The act or result of dispersing or scattering; dispersion. Darwin.",
  "watch meeting - A religious meeting held in the closing hours of the year.",
  "vlissmaki - The diadem indris. See Indris.",
  "jettiness - The state of being jetty; blackness. Pennant.",
  "quag - A quagmire. [R.] \"Crooked or straight, through quags or thorny dells.\" Cowper.",
  "laxiity - The state or quality of being lax; want of tenseness, strictness, or exactness.",
  "rack-renter - 1. One who is subjected to playing rack-rent. 2. One who exacts rack-rent.",
  "ideo- - . A combining form from the Gr. idea.",
  "outswell - 1. To exceed in swelling. 2. To swell beyond; to overflow. [Obs.] Hewyt.",
  "semeiography - A description of the signs of disease.",
  "ghostfish - A pale ubspotted variety of the wrymouth.",
  "maledicency - Evil speaking. [Obs.] Atterbury.",
  "brawned - Brawny; strong; muscular. [Obs.] Spenser.",
  "paronomasy - Paronomasia. [R.] B. Jonson.",
  "antipasch - The Sunday after Easter; Low Sunday.",
  "ceraceous - Having the texture and color of new wax; like wax; waxy.",
  "dragbar - Same as Drawbar (b). Called also draglink, and drawlink. [U. S.]",
  "bidder - One who bids or offers a price. Burke.",
  "idiographic - Of or pertaining to an idiograph.",
  "pegasoid - Like or pertaining to Pegasus.",
  "vastation - A laying waste; waste; depopulation; devastation. [Obs.] Bp. Hall.",
  "hemerobid - Of relating to the hemerobians.",
  "sea bird - Any swimming bird frequenting the sea; a sea fowl.",
  "broggle - To sniggle, or fish with a brog. [Prov. Eng.] Wright.",
  "pedunculata - A division of Cirripedia, including the stalked or goose barnacles.",
  "obliger - One who, or that which, obliges. Sir H. Wotton.",
  "corrosibleness - The quality or state of being corrosible. Bailey.",
  "shadeless - Being without shade; not shaded.",
  "entrick - To trick, to perplex. [Obs.] Rom. of R.",
  "trainable - Capable of being trained or educated; as, boys trainable to virtue. Richardson.",
  "statuminate - To prop or support. [Obs.] B. Jonson.",
  "spatter-dock - The common yellow water lily (Nuphar advena).",
  "nightjar - A goatsucker, esp. the European species. See Illust. of Goatsucker.",
  "etern - Eternal. [Poetic] Shak. Built up to eterne significance. Mrs. Browning.",
  "phaneroglossal - Having a conspicious tongue; -- said of certain reptiles and insects.",
  "caufle - A gung of slaves. Same as Coffle.",
  "primality - The quality or state of being primal. [Obs.]",
  "dodded - Without horns; as, dodded cattle; without beards; as, dodded corn. Halliwell.",
  "barbated - Having barbed points. A dart uncommonly barbated. T. Warton.",
  "androsphinx - A man sphinx; a sphinx having the head of a man and the body of a lion.",
  "mid sea - The middle part of the sea or ocean. Milton. The Mid-sea, the Mediterranean Sea. [Obs.]",
  "photo-electrograph - An electrometer registering by photography.",
  "homeopathically - According to the practice of homeopathy. [Also homoepathically.]",
  "phlegmon - Purulent inflammation of the cellular or areolar tissue.",
  "sans-culottism - Extreme republican principles; the principles or practice of the sans-culottes.",
  "monocotyledonous - Having only one cotyledon, seed lobe, or seminal leaf. Lindley.",
  "melibean - Alternately responsive, as verses.",
  "ytterbic - Pertaining to, or derived from, ytterbium; containing ytterbium.",
  "accelerometer - An apparatus for measuring the velocity imparted by gunpowder.",
  "shintyan - A kind of wide loose drawers or trousers worn by women in Mohammedan countries.",
  "whigling - A petty or inferior Whig; -- used in contempt. Spectator.",
  "coctible - Capable of being cooked. Blount.",
  "misfall - To befall, as ill luck; to happen to unluckily. [Obs.] Chaucer.",
  "gypsoplast - A cast taken in plaster of Paris, or in white lime.",
  "rabies - Same as Hydrophobia (b); canine madness.",
  "hydrothorax - An accumulation of serous fluid in the cavity of the chest.",
  "antephialtic - Good against nightmare. -- n.  A remedy nightmare. Dunglison.",
  "auszug - See Army organization, Switzerland.",
  "carpophagous - Living on fruits; fruit-consuming.",
  "fadeless - Not liable to fade; unfading.",
  "schizognathae - The schizognathous birds.",
  "cobbing - Haughty; purse-proud. See Cob, n., 2. [Obs.] Withals (1608).",
  "oestruation - The state of being under oestrual influence, or of having sexual desire.",
  "bacillary - Of or pertaining to little rods; rod-shaped.",
  "semiverticillate - Partially verticillate.",
  "water-bearer - The constellation Aquarius.",
  "fusteric - The coloring matter of fustet. Ure.",
  "inveteration - The act of making inveterate. [R.] Bailey.",
  "cothurnated - 1. Wearing a cothurn. 2. Relating to tragedy; solemn; grave.",
  "cannular - Having the form of a tube; tubular. [Written also canular.]",
  "antiquation - The act of making antiquated, or the state of being antiquated. Beaumont.",
  "infuscation - The act of darkening, or state of being dark; darkness; obscurity. Johnson.",
  "acetosity - The quality of being acetous; sourness.",
  "albigensian - Of or pertaining to the Albigenses.",
  "fox-hunting - Pertaining to or engaged in the hunting of foxes; fond of hunting foxes.",
  "discubitory - Leaning; fitted for a reclining posture. [Obs.] Sir T. Browne.",
  "unprelated - Deposed from the office of prelate.",
  "sotted - a. & p. p. of Sot. Befooled; deluded; besotted. [Obs.] \"This sotted priest.\" Chaucer.",
  "biggonnet - A cap or hood with pieces covering the ears.",
  "hypochondria - Hypochondriasis; melancholy; the blues.",
  "woefully - In a woeful manner; sorrowfully; mournfully; miserably; dolefully.",
  "oblectate - To delight; to please greatly. [Obs.]",
  "smooth-tongued - Having a smooth tongue; plausible; flattering.",
  "anamniotic - Without, or not developing, an amnion.",
  "potamospongiae - The fresh-water sponges. See Spongilla.",
  "weighbridge - A weighing machine on which loaded carts may be weighed; platform scales.",
  "wainable - Capable of being plowed or cultivated; arable; tillable. [Obs.] Cowell.",
  "urnful - As much as an urn will hold; enough to fill an urn.",
  "osteography - The description of bones; osteology.",
  "arenulous - Full of fine sand; like sand. [Obs.]",
  "favoress - A woman who favors or gives countenance. [Written also fovouress.]",
  "heterostyled - Having styles of two or more distinct forms or lengths. Darwin.",
  "gustation - The act of tasting. [R.] Sir T. Browne.",
  "hurricano - A waterspout; a hurricane. [Obs.] Drayton. \"You cataracts and hurricanoes, spout.\" Shak.",
  "jill-flirt - A light, giddy, or wanton girl or woman. See Gill-flirt.",
  "bookmate - A schoolfellow; an associate in study.",
  "xylograph - An engraving on wood, or the impression from such an engraving; a print by xylography.",
  "notal - Of or pertaining to the back; dorsal.",
  "deare - variant of Dere, v. t. & n. [Obs.]",
  "tempse - See Temse. [Obs. or Prov. Eng.]",
  "mitu - A South American curassow of the genus Mitua.",
  "cyclopedist - A maker of, or writer for, a cyclopedia.",
  "wyandots - Same as Hurons. [Written also Wyandottes, and Yendots.]",
  "pythiad - The period intervening between one celebration of the Pythian games and the next.",
  "detainment - Detention. [R.] Blackstone.",
  "albinoism - The state or condition of being an albino; albinism.",
  "cupper - One who performs the operation of cupping.",
  "poriform - Resembling a pore, or small puncture.",
  "kernelly - Full of kernels; resembling kernels; of the nature of kernels. Holland.",
  "bon ton - The height of the fashion; fashionable society.",
  "astarte - A genus of bivalve mollusks, common on the coasts of America and Europe.",
  "myographic - Of or pertaining to myography.",
  "tangfish - The common harbor seal. [Prov. Eng.]",
  "floren - A cerain gold coin; a Florence. [Obs.] Chaucer.",
  "posnet - A little basin; a porringer; a skillet.",
  "red-tapist - One who is tenacious of a strict adherence to official formalities. Ld. Lytton.",
  "dubitable - Liable to be doubted; uncertain. [R.] Dr. H. More. -- Du\"bi*ta*bly, adv. [R.]",
  "margravate - The territory or jurisdiction of a margrave.",
  "loweringly - In a lowering manner; with cloudiness or threatening gloom.",
  "osteoclasis - The operation of breaking a bone in order to correct deformity.",
  "lunicurrent - Having relation to changes in currents that depend on the moon's phases. Bache.",
  "inculpation - Blame; censure; crimination. Jefferson.",
  "crystallizable - Capable of being crystallized; that may be formed into crystals.",
  "microphotography - The art of making microphotographs.",
  "dowcet - One of the testicles of a hart or stag. [Spelt also doucet.] B. Jonson.",
  "princesse - A term applied to a lady's long, close-fitting dress made with waist and skirt in one.",
  "defensory - Tending to defend; defensive; as, defensory preparations.",
  "thermotonus - A condition of tonicity with respect to temperature.",
  "circumgyratory - Moving in a circle; turning round. Hawthorne.",
  "chaetotaxy - The arrangement of bristles on an insect.",
  "disseverment - Disseverance. Sir W. Scott.",
  "vaguely - In a vague manner. What he vaguely hinted at, but dared not speak. Hawthorne.",
  "sanguinariness - The quality or state of being sanguinary.",
  "febriculose - Somewhat feverish. [Obs.] Johnson.",
  "hygeia - The goddess of health, daughter of Esculapius.",
  "antirachitic - Good against the rickets.",
  "deservedly - According to desert (whether good or evil); justly.",
  "ignomy - Ignominy. [R. & Obs.] I blush to think upon this ignomy. Shak.",
  "showing - 1. Appearance; display; exhibition. 2. Presentation of facts; statement. J. S. Mill.",
  "incend - To inflame; to excite. [Obs.] Marston.",
  "ressaldar - In the Anglo-Indian army, a native commander of a ressala.",
  "hydrofluosilicate - A salt of hydrofluosilic acid; a silicofluoride. See Silicofluoride.",
  "ascham - A sort of cupboard, or case, to contain bows and other implements of archery.",
  "hauynite - A blue isometric mineral, characteristic of some volcani",
  "vaticine - A prediction; a vaticination. [Obs.] Holinshed.",
  "pollened - Covered with pollen. Tennyson.",
  "ichthyological - Of or pertaining to ichthyology.",
  "fuegian - Of or pertaining to Terra del Fuego. -- n.  A native of Terra del Fuego.",
  "verrayment - Verily; truly. [Obs.] Chaucer.",
  "absume - To consume gradually; to waste away. [Obs.] Boyle.",
  "mineralogically - According to the principles of, or with reference to, mineralogy.",
  "oviducal - Of or pertaining to oviducts; as, oviducal glands.",
  "uncharity - Uncharitableness. Tennyson. 'T were much uncharity in you. J. Webster.",
  "igasuric - Pertaining to, or obtained from, nux vomica or St. Ignatius's bean; as, igasuric acid.",
  "overfrieze - To cover with a frieze, or as with a frieze. E. Hall.",
  "abhal - The berries of a species of cypress in the East Indies.",
  "trygon - Any one of several species of large sting rays belonging to Trygon and allied genera.",
  "mincing - That minces; characterized by primness or affected nicety.",
  "slantly - In an inclined direction; obliquely; slopingly.",
  "misunderstander - One who misunderstands. Sir T. More.",
  "cracovienne - A lively Polish dance, in 2-4 time.",
  "inflicter - One who inflicts. Godis the sole and immadiate inflicter of such strokes. South.",
  "blenheim spaniel - A small variety of spaniel, kept as a pet.",
  "infaust - Not favorable; unlucky; unpropitious; sinister. [R.] Ld. Lytton.",
  "micrometric - Belonging to micrometry; made by the micrometer. -- Mi`cro*met\"ric*al*ly, adv.",
  "unlatch - To open or loose by lifting the latch; as, to unlatch a door.",
  "torsion electrometer - A torsion balance used for measuring electric attraction or repulsion.",
  "omniparient - Producing or bringing forth all things; all-producing. [R.]",
  "appendix vermiformis - The vermiform appendix.",
  "transmeatable - Capable of being passed over or traversed; passable. [Obs.]",
  "tenebrosity - The quality or state of being tenebrous; tenebrousness. Burton.",
  "water turkey - The American snakebird. See Snakebird.",
  "subglossal - Situated under the tongue; sublingual.",
  "incorporal - Immaterial; incorporeal; spiritual. [Obs.] Sir W. Raleigh.",
  "sorgo - Indian millet and its varieties. See Sorghum.",
  "bromatology - The science of aliments. Dunglison.",
  "keenness - The quality or state of being keen.",
  "nutriture - Nutrition; nourishment. [Obs.] Harvey.",
  "immeasurability - The quality of being immeasurable; immensurability.",
  "mishandle - To handle ill or wrongly; to maltreat.",
  "aisled - Furnished with an aisle or aisles.",
  "whiskeyfied - Drunk with whisky; intoxicated. [Humorous] Thackeray.",
  "sarabaite - One of certain vagrant or heretical Oriental monks in the early church.",
  "retable - A shelf behind the altar, for display of lights, vases of wlowers, etc.",
  "tenesmic - Of or pertaining to tenesmus; characterized by tenesmus.",
  "beden - The Abyssinian or Arabian ibex (Capra Nubiana). It is probably the wild goat of the Bible.",
  "moneyless - Destitute of money; penniless; impecunious. Swift.",
  "episcopy - 1. Survey; superintendence. [Obs.] Milton. 2. Episcopacy. [Obs.] Jer. Taylor.",
  "seminymph - The pupa of insects which undergo only a slight change in passing to the imago state.",
  "recommittal - A second or renewed commitment; a renewed reference to a committee.",
  "iritis - An inflammation of the iris of the eye.",
  "antichristianity - Opposition or contrariety to the Christian religion.",
  "shoaly - Full of shoals, or shallow places. The tossing vessel sailed on shoaly ground. Dryden.",
  "trichromatism - The quality, state, or phenomenon of being trichromatic.",
  "capillose - Having much hair; hairy. [R.]",
  "great-grandfather - The father of one's grandfather or grandmother.",
  "wizened - Dried; shriveled; withered; shrunken; weazen; as, a wizened old man.",
  "communalist - An advocate of communalism.",
  "emuscation - A freeing from moss. [Obs.]",
  "stalky - Hard as a stalk; resembling a stalk. At the top [it] bears a great stalky head. Mortimer.",
  "betaught - Delivered; committed in trust. [Obs.]",
  "riverhood - The quality or state of being a river. \"Useful riverhood.\" H. Miller.",
  "clanjamfrie - Same as Clamjamphrie. [Scot.] Sir W. Scott.",
  "yernut - An earthnut, or groundnut. See Groundnut (d). [Written also yarnut.]",
  "nursepond - A pond where fish are fed. Walton.",
  "stiddy - An anvil; also, a smith shop. See Stithy. [Prov. Eng.] Halliwell.",
  "monorhyme - A composition in verse, in which all the lines end with the same rhyme.",
  "tidley - (a) The wren. (b) The goldcrest. [Prov. Eng.]",
  "confabulatory - Of the nature of familiar talk; in the form of a dialogue. Weever.",
  "ferulaceous - Pertaining to reeds and canes; having a stalk like a reed; as, ferulaceous plants.",
  "swallowfish - The European sapphirine gurnard (Trigla hirundo). It has large pectoral fins.",
  "escopette - A kind of firearm; a carbine.",
  "waldensian - Of or pertaining to the Waldenses. -- n.  One Holding the Waldensian doctrines.",
  "sciomancy - Divination by means of shadows.",
  "invendible - Not vendible or salable. Jefferson. -- In*vend\"i*ble*ness, n.",
  "indivision - A state of being not divided; oneness. [Obs.] Bp. Hall.",
  "cemeterial - Of or pertaining to a cemetery. \"Cemeterial cells.\" [R.] Sir T. Browne.",
  "animality - Animal existence or nature. Locke.",
  "unglove - To take off the glove or gloves of; as, to unglove the hand. Beau. & Fl.",
  "vaporability - The quality or state of being vaporable.",
  "stingaree - Any sting ray. See under 6th Ray.",
  "interlamination - The state of being interlaminated.",
  "sarrasin - A portcullis, or herse. [Written also sarasin.]",
  "bitheism - Belief in the existence of two gods; dualism.",
  "monish - To admonish; to warn. See Admonish. [Archaic] Ascham.",
  "interspeech - A speech interposed between others. [R.] Blount.",
  "virose - Having a nauseous odor; fetid; poisonous. [R.]",
  "ballasting - That which is used for steadying anything; ballast.",
  "inconsequentiality - The state of being inconsequential.",
  "shopbook - A book in which a tradesman keeps his accounts. Locke.",
  "ylike - Like; alike. [Obs.] \"All . . . yliche good.\" Chaucer.",
  "absinthiated - Impregnated with wormwood; as, absinthiated wine.",
  "lunulite - Any bryozoan of the genus Lunulites, having a more or less circular form.",
  "transudatory - Of or pertaining to transudation; passing by transudation.",
  "phlegmonous - Having the nature or properties of phlegmon; as, phlegmonous pneumonia. Harvey.",
  "webbing - A woven band of cotton or flax, used for reins, girths, bed bottoms, etc.",
  "beprose - To reduce to prose. [R.] \"To beprose all rhyme.\" Mallet.",
  "osteolysis - Softening and absorption of bone. -- Os`te*o*lyt\"ic (#), a.",
  "boyishly - In a boyish manner; like a boy.",
  "semidiapente - An imperfect or diminished fifth. Busby.",
  "forcarve - To cut completely; to cut off. [Obs.] Chaucer.",
  "hygrostatics - The science or art of comparing or measuring degrees of moisture. Evelyn.",
  "pelfray - Pelf; also, figuratively, rubbish; trash. [Obs.] Cranmer.",
  "moringic - Designating an organic acid obtained from oil of ben. See Moringa.",
  "numbfish - The torpedo, which numbs by the electric shocks which it gives.",
  "self-view - A view if one's self; specifically, carefulness or regard for one's own interests",
  "meracious - Being without mixture or adulteration; hence, strong; racy. [Obs.]",
  "spute - To dispute; to discuss. [Obs.] Wyclif.",
  "inseparability - The quality or state of being inseparable; inseparableness. Locke.",
  "accouple - To join; to couple. [R.] The Englishmen accoupled themselves with the Frenchmen. Hall.",
  "browed - Having (such) a brow; -- used in composition; as, dark-browed, stern-browed.",
  "perichondrial - Of or pertaining to the perichondrium; situated around cartilage.",
  "intercartilaginous - Within cartilage; endochondral; as, intercartilaginous ossification.",
  "water ice - Water flavored, sweetened, and frozen, to be eaten as a confection.",
  "showiness - The quality or state of being showy; pompousness; great parade; ostentation.",
  "intenible - Incapable of holding or containing. [Obs.] This captious and intenible sieve. Shak.",
  "sipunculoid - Pertaining to the Sipunculoidea. -- n.  One of the Sipunculoidea.",
  "miraculize - To cause to seem to be a miracle. [R.] Shaftesbury.",
  "synepy - The interjunction, or joining, of words in uttering the clauses of sentences.",
  "reembark - To put, or go, on board a vessel again; to embark again.",
  "unplume - To strip of plumes or feathers; hence, to humiliate.",
  "longiloquence - Long-windedness. American longiloquence in oratory. Fitzed. Hall.",
  "septenate - Having parts in sevens; heptamerous.",
  "stitchel - A kind of hairy wool. [Prov.]",
  "denunciative - Same as Denunciatory. Farrar.",
  "enneagynous - Having or producing nine pistils or styles; -- said of a flower or plant.",
  "prosing - Writing prose; speaking or writing in a tedious or prosy manner. Sir W. Scott.",
  "hemorrhagic - Pertaining or tending to a flux o",
  "spirobacteria - See the Note under Microbacteria.",
  "horizontality - The state or quality of being horizontal. Kirwan.",
  "salmonet - A salmon of small size; a samlet.",
  "biaxal - Having two axes; as, biaxial polarization. Brewster. -- Bi*ax\"i*al*ly, adv.",
  "sickler - One who uses a sickle; a sickleman; a reaper.",
  "rebullition - The act of boiling up or effervescing. [R.] Sir H. Wotton.",
  "oology - The science of eggs in relation to their coloring, size, shape, and number.",
  "rutilate - To shine; to emit rays of light. [Obs.] Ure.",
  "scragginess - The quality or state of being scraggy; scraggedness.",
  "wainbote - See Cartbote. See also the Note under Bote.",
  "free-living - Unrestrained indulgence of the appetites.",
  "insisture - A dwelling or standing on something; fixedness; persistence. [Obs.] Shak.",
  "undertone - A low or subdued tone or utterance; a tone less loud than usual.",
  "holo- - A combining form fr. Gr. \"o`los whole.",
  "tweeze - A surgeon's case of instruments. Howell.",
  "ageless - Without old age limits of duration; as, fountains of ageless youth.",
  "arabesqued - Ornamented in the style of arabesques.",
  "staphylomatous - Of or pertaining to staphyloma; affected with staphyloma.",
  "sputum - That which is expectorated; a salival discharge; spittle; saliva.",
  "nonvocal - Not vocal; destitute of tone. -- n.  A nonvocal consonant.",
  "sparsim - Sparsely; scatteredly; here and there.",
  "consimilitude - Common resemblance. [Obs.] Aubrey.",
  "bromidiom - A conventional comment or saying, such as those characteristic of bromides. [Slang]",
  "outspend - Outlay; expenditure. [R.] A mere outspend of savageness. I. Taylor.",
  "expletively - In the manner of an expletive.",
  "musar - An itinerant player on the musette, an instrument formerly common in Europe.",
  "defunctive - Funereal. [Obs.] \"Defunctive music.\" Shak.",
  "crunk - To cry like a crane. [Obs.] \"The crane crunketh.\" Withals (1608).",
  "irishism - A mode of speaking peculiar to the Irish; an Hibernicism.",
  "immould - To mold into shape, or form. [Obs.] G. Fletcher.",
  "matrass - A round-bottomed glass flask having a long neck; a bolthead.",
  "wiliness - The quality or state of being wily; craftiness; cunning; guile.",
  "lexicographic - Of or pertaining to, or according to, lexicography. -- Lex`i*co*graph\"ic*al*ly, adv.",
  "ex-voto - An offering to a church in fulfillment of a vow.",
  "akinesia - Paralysis of the motor nerves; loss of movement. Foster.",
  "corporeally - In the body; in a bodily form or manner.",
  "backwoods - The forests or partly cleared grounds on the frontiers.",
  "battuta - The measuring of time by beating.",
  "dechristianize - To turn from, or divest of, Christianity.",
  "larviform - Having the form or structure of a larva.",
  "woodstone - A striped variety of hornstone, resembling wood in appearance.",
  "soldo - A small Italian coin worth a sou or a cent; the twentieth part of a lira.",
  "rabato - A kind of ruff for the neck; a turned-down collar; a rebato. [Obs.] Shak.",
  "disgustfulness - The state of being disgustful.",
  "anthropotomy - The anatomy or dissection of the human body; androtomy. Owen.",
  "eagle-winged - Having the wings of an eagle; swift, or soaring high, like an eagle. Shak.",
  "ungrave - To raise or remove from the grave; to disinter; to untomb; to exhume. [Obs.] Fuller.",
  "effectuous - Effective. [Obs.] B. Jonson.",
  "meedful - Worthy of meed, reward, or recompense; meritorious. \"Meedful works.\" Wiclif.",
  "embryotroph - The material from which an embryo is formed and nourished.",
  "locator - One who locates, or is entitled to locate, land or a mining claim. [U.S.]",
  "ermined - Clothed or adorned with the fur of the ermine. Pope.",
  "overply - To ply to excess; to exert with too much vigor; to overwork. Milton.",
  "ingrowth - A growth or development inward. J. LeConte.",
  "serotherapy - (a) Serum-therapy. (b) The whey cure.",
  "mordente - An embellishment resembling a trill.",
  "delaine - A kind of fabric for women's dresses.",
  "trochantine - The second joint of the leg of an insect, -- often united with the coxa.",
  "deskwork - Work done at a desk, as by a clerk or writer. Tennyson.",
  "potentiate - To render active or potent. Coleridge.",
  "diopter - An optical instrument, invented by Hipparchus, for taking altitudes, leveling, etc.",
  "lusern - A lynx. See 1st Lucern and Loup-cervier.",
  "haberdine - A cod salted and dried. Ainsworth.",
  "metallotherapy - Treatment of disease by applying metallic plates to the surface of the body.",
  "languishingly - In a languishing manner.",
  "delta current - The current flowing through a delta connection.",
  "diplanar - Of or pertaining to two planes.",
  "redactor - One who redacts; one who prepares matter for publication; an editor. Carlyle.",
  "treget - Guile; trickery. [Obs.] Rom. of R.",
  "consociational - Of or pertaining to a consociation. [U.S.]",
  "picayune - A small coin of the value of six and a quarter cents. See Fippenny bit. [Local, U.S.]",
  "siphuncle - The tube which runs through the partitions of chambered cephalopod shells.",
  "agrarianize - To distribute according to, or to imbue with, the principles of agrarianism.",
  "genearch - The chief of a family or tribe.",
  "enlink - To chain together; to connect, as by links. Shak.",
  "pervestigate - To investigate thoroughly. [Obs.]",
  "alnage - Measurement (of cloth) by the ell; also, a duty for such measurement.",
  "phlogotic - Of or pertaining to phlogisis.",
  "teacup - A small cup from which to drink tea.",
  "ooelogy - The science of eggs in relation to their coloring, size, shape, and number.",
  "indevout - Not devout. -- In*de*vout\"ly, adv.",
  "stepfather - The husband of one's mother by a subsequent marriage.",
  "oary - Having the form or the use of an oar; as, the swan's oary feet. Milton. Addison.",
  "piquancy - The quality or state of being piquant.",
  "showily - In a showy manner; pompously; with parade.",
  "fawe - Fain; glad; delighted. [Obs.] Chaucer.",
  "gardener - One who makes and tends a garden; a horticulturist.",
  "binarseniate - A salt having two equivalents of arsenic acid to one of the base. Graham.",
  "commandatory - Mandatory; as, commandatory authority. [Obs.]",
  "novelry - Novelty; new things. [Obs.] Chaucer.",
  "evitate - To shun; to avoid. [Obs.] Shak.",
  "semiform - A half form; an imperfect form.",
  "odontalgic - Of or pertaining to odontalgia. -- n.  A remedy for the toothache.",
  "believing - That believes; having belief. -- Be*liev\"ing*ly, adv.",
  "assimilatory - Tending to assimilate, or produce assimilation; as, assimilatory organs.",
  "bewash - To drench or souse with water. \"Let the maids bewash the men.\" Herrick.",
  "unfrankable - Not frankable; incapable of being sent free by public conveyance.",
  "excalfaction - A heating or warming; calefaction. [Obs.] Blount.",
  "pyretic - Of or pertaining to fever; febrile.",
  "refrangibility - The quality of being refrangible.",
  "hyracoidea - An order of small hoofed mammals, comprising the single living genus Hyrax.",
  "murmuration - The act of murmuring; a murmur. [Obs.] Skelton.",
  "removable - Admitting of being removed. Ayliffe. -- Re*mov`a*bil\"i*ty (-, n.",
  "rhizotaxis - The arrangement of the roots of plants.",
  "amatory - Pertaining to, producing, or expressing, sexual love; as, amatory potions.",
  "psalmographist - A writer of psalms, or sacred songs and hymns.",
  "hiation - Act of gaping. [Obs.] Sir T. Browne.",
  "rapscallion - A rascal; a good-for-nothing fellow. [Colloq.] Howitt.",
  "incommixture - A state of being unmixed; separateness. Sir T. Browne.",
  "palsgravine - The consort or widow of a palsgrave.",
  "cockler - One who takes and sells cockles.",
  "prevision - Foresight; foreknowledge; prescience. H. Spencer.",
  "trieterical - Kept or occurring once in three years; triennial. [R.] J. Gregory.",
  "engineman - A man who manages, or waits on, an engine.",
  "supputation - Reckoning; account. [Obs.]",
  "ridiculize - To make ridiculous; to ridicule. [Obs.] Chapman.",
  "demesmerize - To relieve from mesmeric influence. See Mesmerize.",
  "crosse - The implement with which the ball is thrown and caught in the game of lacrosse.",
  "hydrogode - The negative pole or cathode. [R.]",
  "elytroid - Resembling a beetle's wing case.",
  "sheldfowl - The common sheldrake. [Prov. Eng.]",
  "emblematist - A writer or inventor of emblems. Sir T. Browne.",
  "unlute - To separate, as things cemented or luted; to take the lute or the clay from. Boyle.",
  "fissirostres - A group of birds having the bill deeply cleft.",
  "schoolfellow - One bred at the same school; an associate in school.",
  "unnethes - With difficulty. See Uneath. [Obs.] Chaucer.",
  "prejudicacy - Prejudice; prepossession. [Obs.] Sir. H. Blount.",
  "agatine - Pertaining to, or like, agate.",
  "absumption - Act of wasting away; a consuming; extinction. [Obs.] Sir T. Browne.",
  "pancarte - A royal charter confirming to a subject all his possessions. [Obs.] Holinshed.",
  "pyla - The passage between the iter and optocoele in the brain. B. G. Wilder.",
  "ferforth - Far forth. [Obs.] As ferforth as, as far as. -- So ferforth, to such a degree.",
  "preliminarily - In a preliminary manner.",
  "ewe - The female of the sheep, and of sheeplike animals.",
  "hypotenuse - The side of a right-angled triangle that is opposite to the right angle.",
  "perdulous - Lost; thrown away. [Obs.] Abp. Bramhall.",
  "treasurership - The office of treasurer.",
  "scomber - A genus of acanthopterygious fishes which includes the common mackerel.",
  "alula - A false or bastard wing. See under Bastard.",
  "cohibition - Hindrance; restraint. [Obs.]",
  "intrauterine - Within the uterus or womb; as, intrauterine hemorrhage.",
  "arthrography - The description of joints.",
  "blonket - Gray; bluish gray. [Obs.] Our bloncket liveries been all too sad. Spenser.",
  "hazelly - Of the color of the hazelnut; of a light brown. Mortimer.",
  "championness - A female champion. Fairfax.",
  "neesing - Sneezing. [Obs.] \"By his neesings a light doth shine.\" Job xli. 18.",
  "endurable - Capable of being endured or borne; sufferable. Macaulay. -- En*dur\"a*ble*ness, n.",
  "prenostic - A prognostic; an omen. [Obs.] Gower.",
  "quicken tree - The European rowan tree; -- called also quickbeam, and quickenbeam. See Rowan tree.",
  "largifical - Generous; ample; liberal. [Obs.]",
  "propinyl - A hydrocarbon radical regarded as an essential residue of propine and allied compounds.",
  "unpaired - Not paired; not suited or matched. And minds unpaired had better think alone. Crabbe.",
  "dissertate - To deal in dissertation; to write dissertations; to discourse. [R.] J. Foster.",
  "jactancy - A boasting; a bragging. [Obs.]",
  "substraction - 1. Subtraction; deduction. [Obs.] 2. (Law)  See Subtraction, 3.",
  "roadway - A road; especially, the part traveled by carriages. Shak."
]