export default [
  "breviloquence - A brief and pertinent mode of speaking. [R.]",
  "hard-hearted - Unsympathetic; inexorable; cruel; pitiless. -- Hard\"-heart`ed*ness, n.",
  "legality - 1. The state or quality of being letter of the law.",
  "chinky - Full of chinks or fissures; gaping; opening in narrow clefts. Dryden.",
  "primerole - See Primrose. [Obs.] \"She was a primerole.\" Chaucer.",
  "miscompute - To compute erroneously. Sir T. Browne.",
  "apocodeine - An alkaloid, , prepared from codeine. In its effects it resembles apomorphine.",
  "conterranean - Of or belonging to the same country. Howell.",
  "afresh - Anew; again; once more; newly. They crucify . . . the Son of God afresh. Heb. vi. 6.",
  "corolline - Of or pertaining to a corolla.",
  "dudish - Like, or characterized of, a dude.",
  "crosspatch - An ill-natured person. [Colloq.] \"Crosspatch, draw the latch.\" Mother Goose.",
  "messiad - A German epic poem on the Messiah, by Klopstock.",
  "eudiometrical - Of or pertaining to a eudiometer; as, eudiometrical experiments or results.",
  "lowlihead - A lowly state. [R.] Tennyson.",
  "engravery - The trade or work of an engraver. [R.] Sir T. Browne.",
  "dibasicity - The property or condition of being dibasic.",
  "monetize - To convert into money; to adopt as current money; as, to monetize silver.",
  "traitorly - Like a traitor; treacherous; traitorous. [Obs.] \"Traitorly rascals.\" Shak.",
  "norfolk jacket - A kind of loose-fitting plaited jacket, having a loose belt.",
  "effectually - 1. With effect; efficaciously. 2. Actually; in effect. [Obs.] Fuller.",
  "fourbe - A trickly fellow; a cheat. [Obs.] Evelyn. Denham.",
  "genitals - The organs of generation; the sexual organs; the private parts.",
  "taur - The constellation Taurus. [Obs.] Chaucer.",
  "amzel - The European ring ousel (Turdus torquatus).",
  "obstructer - One who obstructs or hinders.",
  "trachytoid - Resembling trachyte; -- used to define the structure of certain rocks.",
  "hilling - The act or process of heaping or drawing earth around plants.",
  "ambilevous - Left-handed on both sides; clumsy; -- opposed to ambidexter. [R.] Sir T. Browne.",
  "rushed - Abounding or covered with rushes.",
  "toco - A toucan (Ramphastos toco) having a very large beak. See Illust. under Toucan.",
  "dialectically - In a dialectical manner.",
  "expletion - Accomplishment; fulfillment. [Obs.] Killingbeck.",
  "electro-gilt - Gilded by means of voltaic electricity.",
  "buckling - Wavy; curling, as hair. Latham.",
  "previously - Beforehand; antecedently; as, a plan previously formed.",
  "librarianship - The office of a librarian.",
  "outdated - Being out of date; antiquated. [Obs.] Hammond.",
  "diverticulum - A blind tube branching out of a longer one.",
  "malthusianism - The system of Malthusian doctrines relating to population.",
  "monoxide - An oxide containing one atom of oxygen in each molecule; as, barium monoxide.",
  "unfumed - Not exposed to fumes; not fumigated. Milton.",
  "reordain - To ordain again, as when the first ordination is considered defective. Bp. Burnet.",
  "exametron - An hexameter. [Obs.] Chaucer.",
  "jaspilite - A compact siliceous rock resembling jasper.",
  "nominately - By name; particularly; namely. [Obs.] Spelman.",
  "tableau vivant - Same as Tableau, n., 2.",
  "sondeli - The musk shrew. See under Musk.",
  "tubman - One of the two most experienced barristers in the Court of Exchequer. Cf. Postman, 2.",
  "tweezers - Small pinchers used to pluck out hairs, and for other purposes.",
  "aeolotropy - Difference of quality or property in different directions.",
  "everywhere - In every place; in all places; hence, in every part; throughly; altogether.",
  "betutor - To tutor; to instruct. Coleridge.",
  "miliola - A genus of Foraminifera, having a porcelanous shell with several longitudinal chambers.",
  "heavy-armed - Wearing heavy or complete armor; carrying heavy arms.",
  "rabbiting - The hunting of rabbits.  T. Hughes.",
  "ganja - The dried hemp plant, used in India for smoking. It is extremely narcotic and intoxicating.",
  "dismettled - Destitute of mettle, that is, or fire or spirit. [R.] Llewellyn.",
  "hexadactylous - Having six fingers or toes.",
  "blitheness - The state of being blithe. Chaucer.",
  "potassamide - A yellowish brown substance obtained by heating potassium in ammonia.",
  "testicle - One of the essential male genital glands which secrete the semen.",
  "heterogonous - Characterized by heterogony. -- Het`er*og\"o*nous*ly, adv.",
  "acuminose - Terminating in a flat, narrow end. Lindley.",
  "toothleted - Having a toothlet or toothlets; as, a toothleted leaf. [Written also toothletted.]",
  "zenithal - Of or pertaining to the zenith. \"The deep zenithal blue.\" Tyndall.",
  "complected - Complexioned. [Low, New Eng.]",
  "hareld - The long-tailed duck. See Old Squaw.",
  "diplomatically - According to the rules of diplomacy; in the manner of a diplomatist; artfully.",
  "chilognath - A myriapod of the order Chilognatha.",
  "pinaster - A species of pine (Pinus Pinaster) growing in Southern Europe.",
  "scotching - Dressing stone with a pick or pointed instrument.",
  "grundel - A groundling (fish). [Prov. Eng.]",
  "pleuritic - (a) Of or pertaining to pleurisy; as, pleuritic symptoms. (b) Suffering from pleurisy.",
  "rambooze - A beverage made of wine, ale (or milk), sugar, etc. [Obs.] Blount.",
  "tricuspidate - Three-pointed; ending in three points; as, a tricuspidate leaf.",
  "switchman - One who tends a switch on a railway.",
  "glires - An order of mammals; the Rodentia. -- Gli\"rine, a.",
  "electrostatic - Pertaining to electrostatics.",
  "about-sledge - The largest hammer used by smiths. Weale.",
  "anthropometrical - Pertaining to anthropometry.",
  "autophoby - Fear of one's self; fear of being egotistical. [R.] Hare.",
  "dicalcic - Having two atoms or equivalents of calcium to the molecule.",
  "crimeful - Criminal; wicked; contrary to law, right, or dury. [Obs.] Shak.",
  "tranation - The act of swimming over. [Obs.] Bailey.",
  "piedness - The state of being pied. Shak.",
  "abstractiveness - The quality of being abstractive; abstractive property.",
  "provencial - Of or pertaining to Provence in France.",
  "voyager - One who voyages; one who sails or passes by sea or water.",
  "thermotics - The science of heat. Whewell.",
  "wieldless - Not to be wielded; unmanageable; unwieldy. [R.] \"Wieldless might.\" Spenser.",
  "parturiate - To bring forth young. [Obs.]",
  "hoyman - One who navigates a hoy. A common hoyman to carry goods by water for hire. Hobart.",
  "reforge - To forge again or anew; hence, to fashion or fabricate anew; to make over. Udall.",
  "ingravidation - The state of being pregnant or impregnated. [Obs.]",
  "broncho - A native or a Mexican horse of small size. [Western U.S.]",
  "vulcanite - Hard rubber produced by vulcanizing with a large proportion of sulphur.",
  "oxlike - Characteristic of, or like, an ox.",
  "biseptate - With two partitions or septa. Gray.",
  "saporosity - The quality of a body by which it excites the sensation of taste.",
  "housling - Sacramental; as, housling fire. [R.] Spenser.",
  "rubescent - Growing or becoming red; tending to redness.",
  "photometrical - Of or pertaining to photometry, or to a photometer.",
  "potatory - Of or pertaining to drinking. Ld. Lytton.",
  "saturable - Capable of being saturated; admitting of saturation. -- Sat`u*ra*bil\"i*ty, n.",
  "absey-book - An A-B-C book; a primer. [Obs.] Shak.",
  "cyanotype - A photographic picture obtained by the use of a cyanide.",
  "sturiones - An order of fishes including the sturgeons.",
  "cubhood - The state of being a cub. [Jocose] \"From cubhood to old age.\" W. B. Dawkins.",
  "aplasia - Incomplete or faulty development.",
  "curvirostral - Having a crooked beak, as the crossbill.",
  "dubitate - To doubt. [R.] If he . . . were to loiter dubitating, and not come. Carlyle.",
  "rhizophora - A genus of trees including the mangrove. See Mangrove.",
  "unpen - To release from a pen or from confinement. \"If a man unpens another's water.\" Blackstone.",
  "ethically - According to, in harmony with, moral principles or character.",
  "aphakial - Pertaining to aphakia; as, aphakial eyes.",
  "dragman - A fisherman who uses a dragnet. Sir M. Hale.",
  "aborticide - The act of destroying a fetus in the womb; feticide.",
  "naik - A chief; a leader; a Sepoy corporal. Balfour (Cyc. of India).",
  "finedrawn - Drawn out with too much subtilty; overnice; as, finedrawn speculations.",
  "enstamp - To stamp; to mark as It is the motive . . . which enstamps the character. Gogan.",
  "vocalist - A singer, or vocal musician, as opposed to an instrumentalist.",
  "hypercritically - In a hypercritical manner.",
  "disjunctively - In a disjunctive manner; separately. Dr. H. More.",
  "millenarianism - The doctrine of Millenarians.",
  "malacozoic - Of or pertaining to the Malacozoa.",
  "helminthologist - One versed in helminthology.",
  "seerhand - A kind of muslin of a texture between nainsook and mull.",
  "forerecited - Named or recited before. \"The forerecited practices.\" Shak.",
  "orthodoxical - Pertaining to, or evincing, orthodoxy; orthodox.",
  "inbred - Bred within; innate; as, inbred worth. \"Inbred sentiments.\" Burke.",
  "whahoo - An American tree, the winged elm. (Ulmus alata).",
  "secreto-motory - Causing secretion; -- said of nerves which go to glands and influence secretion.",
  "selectedly - With care and selection. [R.]",
  "apopemptic - Sung or addressed to one departing; valedictory; as, apoplectic songs or hymns.",
  "changeableness - The quality of being changeable; fickleness; inconstancy; mutability.",
  "stonecutter - One whose occupation is to cut stone; also, a machine for dressing stone.",
  "tilt-yard - A yard or place for tilting. \"The tilt-yard of Templestowe.\" Sir W. Scott.",
  "pyuria - A morbid condition in which pus is discharged in the urine.",
  "mesmerization - The act of mesmerizing; the state of being mesmerized.",
  "denotation - The marking off or separation of anything. Hammond.",
  "syth - See Sith, Sithe. [Obs.] Chaucer. Piers Plowman.",
  "malvesie - Malmsey wine. See Malmsey. \" A jub of malvesye.\" Chaucer.",
  "prelateship - The office of a prelate. Harmar.",
  "coruscate - To glitter in flashes; to flash. Syn. -- To glisten; gleam; sparkle; radiate.",
  "aspersive - Tending to asperse; defamatory; slanderous. -- As*pers\"ive*ly, adv.",
  "incurableness - The state of being incurable; incurability. Boyle.",
  "abrook - To brook; to endure. [Obs.] Shak.",
  "insidiator - One who lies in ambush. [Obs.] Barrow.",
  "apnea - Partial privation or suspension of breath; suffocation.",
  "moccasined - Covered with, or wearing, a moccasin or moccasins. \"Moccasined feet.\" Harper's Mag.",
  "termes - A genus of Pseudoneuroptera including the white ants, or termites. See Termite.",
  "defalcator - A defaulter or embezzler. [Modern]",
  "anteport - An outer port, gate, or door.",
  "constitutionalist - One who advocates a constitutional form of government; a constitutionalist.",
  "hydrostatician - One who is versed or skilled in hydrostatics. [R.]",
  "vindemial - Of or pertaining to a vintage, or grape harvest. [R.]",
  "cubicular - Belonging to a chamber or bedroom. [Obs.] Howell.",
  "strobilaceous - (a) Of or pertaining to a strobile or cone. (b) Producing strobiles.",
  "tramming - The act or process of forming trams. See 2d Tram.",
  "sectility - The state or quality of being sectile.",
  "strophiolate - Furnished with a strophiole, or caruncle, or that which resembles it. Gray.",
  "endognath - The inner or principal branch of the oral appendages of Crustacea. See Maxilla.",
  "constrictive - Serving or tending to bind or constrict.",
  "emotiveness - Susceptibility to emotion. G. Eliot.",
  "commissarial - Of or pertaining to a commissary.",
  "quakerish - Like or pertaining to a Quaker; Quakerlike.",
  "safe-keeping - The act of keeping or preserving in safety from injury or from escape; care; custody.",
  "contrahent - Entering into covenant; contracting; as, contrahent parties. [Obs.] Mede.",
  "impardonable - Unpardonable. [Obs.] South.",
  "cephalotrocha - A kind of annelid larva with a circle of cilia around the head.",
  "slopshop - A shop where slops. or ready-made clothes, are sold.",
  "deep-read - Profoundly book-learned. \"Great writers and deep-read men.\" L'Estrange.",
  "insignificative - Not expressing meaning; not significant.",
  "plicated - Plaited; folded like a fan; as, a plicate leaf. -- Pli\"cate*ly, adv.",
  "stomatology - Scientific study or knowledge of the mouth.",
  "circummeridian - About, or near, the meridian.",
  "exuperation - The act of rising or coming into view. [Obs.] Baxter.",
  "claribella - A soft, sweet stop, or set of open wood pipes in an organ.",
  "releaser - One who releases, or sets free.",
  "abditory - A place for hiding or preserving articles of value. Cowell.",
  "subluxation - An incomplete or partial dislocation.",
  "callisthenics - See Calisthenic, Calisthenics.",
  "smaragdite - A green foliated kind of amphibole, observed in eclogite and some varietis of gabbro.",
  "water germander - A labiate plant (Teucrium Scordium) found in marshy places in Europe.",
  "saithe - The pollock, or coalfish; -- called also sillock. [Scot.]",
  "ringstraked - Ring-streaked. Cattle ringstraked, speckled, and spotted. Gen. xxx. 39.",
  "eluctate - To struggle out; -- with out. [Obs.] Bp. Hacket.",
  "jowter - A mounted peddler of fish; -- called also jouster. [Obs.] Carew.",
  "distraint - The act or proceeding of seizing personal property by distress. Abbott.",
  "calendographer - One who makes calendars. [R.]",
  "accompletive - Tending to accomplish. [R.]",
  "restorer - One who, or that which, restores.",
  "desecrator - One who desecrates. \"Desecrators of the church.\" Morley.",
  "typhous - Of or pertaining to typhus; of the nature of typhus.",
  "phyllophagous - Substituting on leaves; leaf-eating.",
  "damage feasant - Doing injury; trespassing, as cattle. Blackstone.",
  "martel - To make a blow with, or as with, a hammer. [Obs.] Spenser.",
  "splenalgia - Pain over the region of the spleen.",
  "underministry - A subordinate or inferior ministry. Jer. Taylor.",
  "fie - An exclamation denoting contempt or dislike. See Fy. Fuller.",
  "bladefish - A long, thin, marine fish of Europe (Trichiurus lepturus); the ribbon fish.",
  "avifauna - The birds, or all the kinds of birds, inhabiting a region.",
  "realization - The act of realizing, or the state of being realized.",
  "by-stroke - An accidental or a slyly given stroke.",
  "federative - Uniting in a league; forming a confederacy; federal. \"A federative society.\" Burke.",
  "muddily - , In a muddy manner; turbidly; without mixture; cloudily; obscurely; confusedly.",
  "anteriority - The state of being anterior or preceding in time or in situation; priority. Pope.",
  "cavin - A hollow way, adapted to cover troops, and facilitate their aproach to a place. Farrow.",
  "sunblink - A glimpse or flash of the sun. [Scot.] Sir W. Scott.",
  "exclusivism - The act or practice of excluding being exclusive; exclusiveness.",
  "circar - A district, or part of a province. See Sircar. [India]",
  "corvine - Of or pertaining to the crow; crowlike.",
  "anglewise - In an angular manner; angularly.",
  "sarn - A pavement or stepping-stone. [Prov. Eng.] Johnson.",
  "exampleless - Without or above example. [R.]",
  "dribber - One who dribs; one who shoots weakly or badly. [Obs.] Ascham.",
  "fen cricket - The mole cricket. [Prov. Eng.]",
  "margarone - The ketone of margaric acid.",
  "pellicular - Of or pertaining to a pellicle. Henslow.",
  "disaffectionate - Not disposed to affection; unfriendly; disaffected. [R.] Blount.",
  "portage group - A subdivision of the Chemung period in American geology. See Chart of Geology.",
  "racleness - See Rakelness. [Obs.] Chaucer.",
  "saccharum - A genus of tall tropical grasses including the sugar cane.",
  "bluepoll - A kind of salmon (Salmo Cambricus) found in Wales.",
  "chymist - See Chemic, Chemist, Chemistry.",
  "feazings - The unlaid or ragged end of a rope. Ham. Nav. Encyc.",
  "panteutonic - Of or pertaining to all the Teutonic races.",
  "disponer - One who legally transfers property from himself to another.",
  "irregularist - One who is irregular. Baxter.",
  "dentize - To breed or cut new teeth. [R.] The old countess . . . did dentize twice or thrice. Bacon.",
  "insupposable - Incapable of being supposed; not supposable; inconceivable.",
  "mawmetry - The religion of Mohammed; also, idolatry. See Mawmet. [Obs.] Chaucer.",
  "napoleon - A French gold coin of twenty francs, or about $3.86.",
  "insaturable - Not capable of being saturated or satisfied.",
  "undeadly - Not subject to death; immortal. [Obs.] -- Un*dead\"li*ness, n. [Obs.] Wyclif.",
  "formularize - To reduce to a forula; to formulate.",
  "ungown - To strip of a gown; to unfrock.",
  "acerbitude - Sourness and harshness. [Obs.] Bailey.",
  "aromatizer - One who, or that which, aromatizes or renders aromatic. Evelyn.",
  "opianic - Of, pertaining to, or designating, an organic acid obtained by the oxidation of narcotine.",
  "ostrogoth - One of the Eastern Goths. See Goth.",
  "accentuable - Capable of being accented.",
  "towardly - Same as Toward, a., 2. He's towardly and will come on apace. Dryden.",
  "lucifrian - Luciferian; satanic. [Obs.] Marston.",
  "sub judice - Before the judge, or court; not yet decided; under judicial consideration.",
  "exhilarating - That exhilarates; cheering; gladdening. -- Ex*hil\"a*ra`ting*ly, adv.",
  "isolable - Capable of being isolated, or of being obtained in a pure state; as, gold is isolable.",
  "oblongness - State or quality of being oblong.",
  "unsexual - Not sexual; not proper or peculiar to one of the sexes. De Quincey.",
  "peaceless - Without peace; disturbed. Sandys.",
  "unreadiness - The quality or state of being unready.",
  "overthwartness - The state of being overthwart; perverseness. [Obs.] Lord Herbert.",
  "epinglette - An iron needle for piercing the cartridge of a cannon before priming.",
  "vitriolize - To convert into a vitriol; to vitriolate.",
  "inched - Having or measuring (so many) inches; as, a four-inched bridge. Shak.",
  "vachery - 1. An inclosure for cows. 2. A dairy. [Obs. or Prov. Eng.] Prompt. Parv.",
  "renderer - 1. One who renders. 2. A vessel in which lard or tallow, etc., is rendered.",
  "attitudinarian - One who attitudinizes; a posture maker.",
  "distichous - Disposed in two vertical rows; two-ranked.",
  "opiniatrety - Obstinacy in opinious. [Written also opiniatry.] [Obs.]",
  "delineament - Delineation; sketch. Dr. H. More.",
  "tid - Tender; soft; nice; -- now only used in tidbit.",
  "understate - To state or represent less strongly than may be done truthfully.",
  "semicompact - Half compact; imperfectly indurated.",
  "chlorinate - To treat, or cause to combine, with chlorine.",
  "sanicle - Any plant of the umbelliferous genus Sanicula, reputed to have healing powers.",
  "facundious - Eloquement; full of words. [Archaic]",
  "studentship - The state of being a student.",
  "honk - The cry of a wild goose. -- Honk\"ing, n.",
  "knubs - Waste silk formed in winding off the threads from a cocoon.",
  "hemimorphic - Having the two ends modified with unlike planes; -- said of a crystal.",
  "pugh - Pshaw! pish! -- a word used in contempt or disdain.",
  "tumultuariness - The quality or state of being tumultuary.",
  "idem - The same; the same as above; -- often abbreviated id.",
  "undubitable - Indubitable; as, an undubitable principle. [Obs.] Locke.",
  "telegrapher - One who sends telegraphic messages; a telegraphic operator; a telegraphist.",
  "adiactinic - Not transmitting the actinic rays.",
  "abraum salts - A red ocher used to darken mahogany and for making chloride of potassium.",
  "vulpes - A genus of Carnivora including the foxes.",
  "retrovaccination - The inoculation of a cow with human vaccine virus.",
  "cymbium - A genus of marine univalve shells; the gondola.",
  "androecium - The stamens of a flower taken collectively.",
  "toxicologist - One versed in toxicology; the writer of a treatise on poisons.",
  "concludency - Deduction from premises; inference; conclusion. [Obs.] Sir M. Hale.",
  "amortisation - Same as Amortize, Amortization, etc.",
  "cultriform - Shaped like a pruning knife; cultrate.",
  "cankery - 1. Like a canker; full of canker. 2. Surly; sore; malignant.",
  "miamis - A tribe of Indians that formerly occupied the country between the Wabash and Maumee rivers.",
  "egotheism - The deification of self. [R.]",
  "embonpoint - Plumpness of person; -- said especially of persons somewhat corpulent.",
  "tosto - Quick; rapid. Pui tosto ( Etym: [It.] (Mus.), faster; more rapid.",
  "psalterium - (a) The third stomach of ruminants. See Manyplies. (b) The lyra of the brain.",
  "incompatibleness - The quality or state of being incompatible; incompatibility.",
  "orangeade - A drink made of orange juice and water, corresponding to lemonade; orange sherbet.",
  "frisket - The light frame which holds the sheet of paper to the tympan in printing.",
  "collectorate - The district of a collector of customs; a collectorship.",
  "philologic - Of or pertaining to philology. -- Phil`o*log\"ic*al*ly, adv.",
  "nooning - A rest at noon; a repast at noon.",
  "infoliate - To cover or overspread with, or as with, leaves. [R.] Howell.",
  "grobian - A rude or clownish person; boor; lout.",
  "tiar - A tiara. [Poetic] Milton. Tennyson.",
  "serr - To crowd, press, or drive together. [Obs.] Bacon.",
  "fiberless - Having no fibers; destitute of fibers or fiber.",
  "carpolite - A general term for a fossil fruit, nut, or seed.",
  "mismeter - To give the wrong meter to, as to a line of verse. [R.] Chaucer.",
  "rumper - A member or a supporter of the Rump Parliament. I. Disraeli.",
  "throatboll - The Adam's apple in the neck. [Obs. or R.] By the throatboll he caught Aleyn. Chaucer.",
  "transactor - One who transacts, performs, or conducts any business. Derham.",
  "barmaster - Formerly, a local judge among miners; now, an officer of the barmote. [Eng.]",
  "calmly - In a calm manner. The gentle stream which calmly flows. Denham.",
  "gummatous - Belonging to, or resembling, gumma.",
  "russianize - To make Russian, or more or less like the Russians; as, to Russianize the Poles.",
  "twinned - Composed of parts united according to a law of twinning. See Twin, n., 4.",
  "retrofracted - Refracted; as, a retrofract stem.",
  "heretog - The leader or commander of an army; also, a marshal. Blackstone.",
  "headachy - Afflicted with headache. [Colloq.]",
  "dextrous - Same as Dexterous, Dexterously, etc.",
  "full-orbed - Having the orb or disk complete or fully illuminated; like the full moon.",
  "genio - A man of a particular turn of mind. [R.] Tatler.",
  "mispickel - Arsenical iron pyrites; arsenopyrite.",
  "puppyhood - The time or state of being a puppy; the time of being young and undisciplined.",
  "unhelmet - To deprive of the helmet. Sir W. Scott.",
  "blepharitis - Inflammation of the eyelids. -- Bleph`a*rit\"ic (#), a.",
  "genericalness - The quality of being generic.",
  "homochromous - Having all the florets in the same flower head of the same color.",
  "syngenesian - Having the stamens united by the anthers; of or pertaining to the Syngenesia.",
  "euhemerize - To interpret (mythology) on the theory of euhemerism.",
  "blastocoele - The cavity of the blastosphere, or segmentation cavity.",
  "pallone - An Italian game, played with a large leather ball.",
  "baddish - Somewhat bad; inferior. Jeffrey.",
  "gluttonish - Gluttonous; greedy. Sir P. Sidney.",
  "sorbefacient - Producing absorption. -- n.  A medicine or substance which produces absorption.",
  "spindletail - The pintail duck. [Local, U.S.]",
  "substract - To subtract; to withdraw. [Obs.] Barrow.",
  "diapente - 1. (Anc. Mus.)  The interval of the fifth. 2. (Med.)  A composition of five ingredients.",
  "refractiveness - The quality or condition of being refractive.",
  "donate - To give; to bestow; to present; as, to donate fifty thousand dollars to a college.",
  "impedition - A hindering; a hindrance. [Obs.] Baxier.",
  "natatory - Adapted for swimming or floating; as, natatory organs.",
  "dentalism - The quality of being formed by the aid of the teeth.",
  "pencillated - Shaped like a pencil; penicillate.",
  "framer - One who frames; as, the framer of a building; the framers of the Constitution.",
  "geez - The original native name for the ancient Ethiopic language or people. See Ethiopic.",
  "photoprint - Any print made by a photomechanical process.",
  "tongued - Having a tongue. Tongued like the night crow. Donne.",
  "embolite - A mineral consisting of both the chloride and the bromide of silver.",
  "immorally - In an immoral manner; wickedly.",
  "infra-axillary - Situated below the axil, as a bud.",
  "totipresent - Omnipresence. [Obs.] A. Tucker.",
  "abortiveness - The quality of being abortive.",
  "shoddyism - The quality or state of being shoddy. [Colloq.] See the Note under Shoddy, n.",
  "subdecanal - Of or pertaining to a subdean or subdeanery.",
  "parallactical - Of or pertaining to a parallax.",
  "alternacy - Alternateness; alternation. [R.] Mitford.",
  "calle - A kind of head covering; a caul. [Obs.] Chaucer.",
  "tormenter - 1. One who, or that which, torments; a tormentor. 2. An executioner. [Obs.] Chaucer.",
  "demagogical - Relating to, or like, a demagogue; factious.",
  "lipyl - A hypothetical radical of glycerin. [Obs.] Berzelius.",
  "susceptive - Susceptible. I. Watts. -- Sus*cep\"tive*ness, n.",
  "effascination - A charming; state of being bewitched or deluded. [Obs.]",
  "shakefork - A fork for shaking hay; a pitchfork. [Obs.]",
  "contemner - One who contemns; a despiser; a scorner. \"Contemners of the gods.\" South.",
  "grille - A lattice or grating. The grille which formed part of the gate. L. Oliphant.",
  "ectorganism - An external parasitic organism.",
  "rongeur - An instrument for removing small rough portions of bone.",
  "saccharize - To convert into, or to impregnate with, sugar.",
  "vernacularly - In a vernacular manner; in the vernacular. Earle.",
  "hooky - Full of hooks; pertaining to hooks.",
  "melter - , One who, or that which, melts.",
  "oxalite - A yellow mineral consisting of oxalate of iron.",
  "feat-bodied - Having a feat or trim body. [Obs.] Beau. & Fl.",
  "metathorax - The last or posterior segment of the thorax in insects. See Illust. of Coleoptera.",
  "tonsilar - Of or pertaining to the tonsils; tonsilitic. [Written also tonsillar.]",
  "li bella - 1. A small balance. 2. A level, or leveling instrument.",
  "alkali waste - Waste material from the manufacture of alkali; specif., soda waste.",
  "gymnoplast - A cell or mass of protoplasm devoid of an envelope, as a white blood corpuscle.",
  "lackbrain - One who is deficient in understanding; a witless person. Shak.",
  "trichopterous - Of, pertaining to, or characterizing, the Trichoptera.",
  "home-driven - Driven to the end, as a nail; driven close.",
  "indoles - Natural disposition; natural quality or abilities.",
  "hylozoist - A believer in hylozoism. A. Tucker.",
  "trull - 1. A drab; a strumpet; a harlot; a trollop. Shak. 2. A girl; a wench; a lass. [Obs.]",
  "labialize - To modify by contraction of the lip opening.",
  "fruitive - Eujoying; possessing. [Obs.] Boyle.",
  "scatch - A kind of bit for the bridle of a horse; -- called also scatchmouth. Bailey.",
  "leprose - Covered with thin, scurfy scales.",
  "devilship - The character or person of a devil or the devil. Cowley.",
  "kneejointed - Geniculate; kneed. See Kneed, a., 2.",
  "umbrosity - The quality or state of being umbrose; shadiness. [Obs.] Sir T. Browne.",
  "zoographical - Of or pertaining to the description of animals.",
  "disapproval - Disapprobation; dislike; censure; adverse judgment.",
  "dianoialogy - The science of the dianoetic faculties, and their operations. Sir W. Hamilton.",
  "desecration - The act of desecrating; profanation; condition of anything desecrated.",
  "skaddon - The larva of a bee. [Prov. Eng.]",
  "illustriously - In a illustrious manner; conspicuously; eminently; famously. Milton.",
  "mirable - Wonderful; admirable. [Obs.] Shak.",
  "galloway - A small horse of a breed raised at Galloway, Scotland; -- called also garran, and garron.",
  "mesocoelia - The cavity of the mesencephalon; the iter.",
  "thermology - A discourse on, or an account of, heat. Whewell.",
  "expatiatory - Expansive; diffusive. [R.]",
  "magisterialness - The quality or state of being magisterial.",
  "goety - Invocation of evil spirits; witchcraft. [Obs.] Hallywell.",
  "subcelestial - Being beneath the heavens; as, subcelestial glories. Barrow.",
  "patellula - A cuplike sucker on the feet of certain insects.",
  "pentice - A penthouse. [Obs.] Sir H. Wotton.",
  "ordinaryship - The state of being an ordinary. [R.] Fuller.",
  "pulpiness - the quality or state of being pulpy.",
  "hircinous - 1. Goatlike; of or pertaining to a goat or the goats. 2. Of a strong goatish smell.",
  "psittaceous - Of or pertaining to the parrots, or the Psittaci. -- n.  One of the Psittaci.",
  "frondent - Covered with leaves; leafy; as, a frondent tree. [R.]",
  "cheapness - Lowness in price, considering the usual price, or real value.",
  "transiency - The quality of being transient; transientness.",
  "reargument - An arguing over again, as of a motion made in court.",
  "imperturbation - Freedom from agitation of mind; calmness; quietude. W. Montagu.",
  "shimmering - A gleam or glimmering. \"A little shimmering of a light.\" Chaucer.",
  "pine-clad - Clad or crowned with pine trees; as, pine-clad hills.",
  "momentaneous - Momentary. [Obs.] Hooker. \"Momentany as a sound.\" Shak.",
  "hypostrophe - (a) The act of a patient turning himself. (b) A relapse, or return of a disease.",
  "eclecticism - Theory or practice of an eclectic.",
  "recognizability - The quality or condition of being recognizable.",
  "lovemonger - One who deals in affairs of love.[Obs.] Shak.",
  "mesitylol - A crystalline substance obtained from mesitylene.",
  "irredeemability - The state or quality of being irredeemable; irredeemableness.",
  "worthful - Full of worth; worthy; deserving. Marston.",
  "literation - The act or process of representing by letters.",
  "pristinate - Pristine; primitive. [Obs.] \"Pristinate idolatry.\" Holinshed.",
  "septempartite - Divided nearly to the base into seven parts; as, a septempartite leaf.",
  "rypophagous - Eating, or subsisting on, filth.",
  "dough-kneaded - Like dough; soft. He demeans himself . . . like a dough-kneaded thing. Milton.",
  "helvetian - Same as Helvetic. -- n.  A Swiss; a Switzer.",
  "oughwhere - Anywhere; somewhere. See Owher. [Obs.]",
  "globate - Having the form of a globe; spherical.",
  "concertative - Contentious; quarrelsome. [Obs.] Bailey.",
  "slipslop - Weak, poor, or flat liquor; weak, profitless discourse or writing.",
  "pleuralgia - Pain in the side or region of the ribs.",
  "contradictional - Contradictory; inconsistent; opposing. [R.] Milton.",
  "semibarbarian - Half barbarous; partially civilized. -- n.  One partly civilized.",
  "albification - The act or process of making white. [Obs.]",
  "eutrophy - Healthy nutrition; soundless as regards the nutritive functions.",
  "demonologist - One who writes on, or is versed in, demonology.",
  "stewardship - The office of a steward. Shak.",
  "gammer - An old wife; an old woman; -- correlative of gaffer, an old man.",
  "queerish - Rather queer; somewhat singular.",
  "interspace - Intervening space. Bp. Hacket.",
  "multivalence - Quality, state, or degree, of a multivalent element, atom, or radical.",
  "beflower - To besprinkle or scatter over with, or as with, flowers. Hobbes.",
  "hailstone - A single particle of ice falling from a cloud; a frozen raindrop; a pellet of hail.",
  "whereform - From which; from which or what place. Tennyson.",
  "unresponsible - Irresponsible. Fuller. -- Un`re*spon\"si*ble*ness, n.",
  "zymase - A soluble ferment, or enzyme. See Enzyme.",
  "gigantical - Bulky, big. [Obs.] Burton. -- Gi*gan\"tic*al*ly, adv.",
  "carbon transmitter - A telephone transmitter in which a carbon contact is used.",
  "phytogeography - The geographical distribution of plants.",
  "patterer - One who patters, or talks glibly; specifically, a street peddler. [Cant, Eng.]",
  "extramission - A sending out; emission. [Obs.] Sir T. Browne.",
  "berrying - A seeking for or gathering of berries, esp. of such as grow wild.",
  "inadaptation - Want of adaptation; unsuitableness.",
  "high-principled - Possessed of noble or honorable principles.",
  "martialize - To render warlike; as, to martialize a people.",
  "tiny - Very small; little; puny. When that I was and a little tiny boy. Shak.",
  "impinguation - The act of making fat, or the state of being fat or fattened. [Obs.]",
  "marcid - 1. Pining; lean; withered. Dryden. 2. Characterized by emaciation, as a fever. Harvey.",
  "fearfulness - The state of being fearful.",
  "numismatologist - One versed in numismatology.",
  "counter-salient - Leaping from each other; -- said of two figures on a coast of arms.",
  "araneose - Of the aspect of a spider's web; arachnoid.",
  "laically - As a layman; after the manner of a layman; as, to treat a matter laically.",
  "lacrymary - See Lachrymary, Lachrymatory, Lachrymose.",
  "pantastomata - One of the divisions of Flagellata, including the monads and allied forms.",
  "ignobleness - State or quality of being ignoble.",
  "conversationist - One who converses much, or who excels in conversation. Byron.",
  "screwing - a. & n. from Screw, v. t. Screwing machine. See Screw machine, under Screw.",
  "misregulate - To regulate wrongly or imperfectly; to fail to regulate.",
  "nutlet - A small nut; also, the stone of a drupe.",
  "ent- - A prefix signifying within. See Ento-.",
  "close-tongued - Closemouthed; silent. \"Close-tongued treason.\" Shak.",
  "trant - To traffic in an itinerary manner; to peddle. [Written also traunt.] [Obs.]",
  "brome grass - A genus (Bromus) of grasses, one species of which is the chess or cheat.",
  "retchless - Careless; reckless. [Obs.] Dryden. --- Retch\"less*ly, adv. -- Retch\"less*ness, n. [Obs.]",
  "finitely - In a finite manner or degree.",
  "grith - Peace; security; agreement. [Obs.] Gower.",
  "stridor - A harsh, shrill, or creaking noise. Dryden.",
  "tentwort - A kind of small fern, the wall rue. See under Wall.",
  "actuation - A bringing into action; movement. Bp. Pearson.",
  "furriery - 1. Furs, in general. Tooke. 2. The business of a furrier; trade in furs.",
  "exauguration - The act of exaugurating; desecration. [Obs.]",
  "pumiciform - Resembling, or having the structure of, pumice.",
  "aftercast - A throw of dice after the game in ended; hence, anything done too late. Gower.",
  "indexically - In the manner of an index.",
  "ill-omened - Having unlucky omens; inauspicious. See Note under Ill, adv.",
  "ginging - The lining of a mine shaft with stones or bricks to prevent caving.",
  "antimonate - A compound of antimonic acid with a base or basic radical. [Written also antimoniate.]",
  "vociferance - Vociferation; noise; clamor. [R.] R. Browning.",
  "syncopal - Of or pertaining to syncope; resembling syncope.",
  "kneck - The twisting of a rope or cable, as it is running out. [Eng.]",
  "gymnolaema - An order of Bryozoa, having no epistome.",
  "courtyard - A court or inclosure attached to a house.",
  "sewster - A seamstress. [Obs.] B. Jonson.",
  "unconform - Unlike. [Obs.] Not unconform to other shining globes. Milton.",
  "endoplasma - Same as Entoplasm and Endosarc.",
  "gat-toothed - Goat-toothed; having a lickerish tooth; lustful; wanton. [Obs.]",
  "eyehole - A circular opening to recive a hook, cord, ring, or rope; an eyelet.",
  "melligenous - Having the qualities of honey. [R.]",
  "omnific - All-creating. \"The omnific word.\" Milton.",
  "tallow-face - One who has a sickly, pale complexion. Shak.",
  "iterant - Repeating; iterating; as, an iterant echo. Bacon.",
  "syllogistically - In a syllogistic manner.",
  "cymidine - A liquid organic base, C10H13.NH2, derived from cymene.",
  "odontogeny - Generetion, or mode of development, of the teeth.",
  "gote - A channel for water. [Prov. Eng.] Crose.",
  "eyebrow - The brow or hairy arch above the eye. Shak.",
  "circumfer - To bear or carry round. [Obs.] Bacon.",
  "corollaceous - Pertaining to, or resembling, a corolla; having the form or texture of a corolla.",
  "taleful - Full of stories. [R.] Thomson.",
  "hostie - The consecrated wafer; the host. [Obs.] Bp. Burnet.",
  "biparous - Bringing forth two at a birth.",
  "vaginicola - A genus of Infusoria which form minute vaselike or tubular cases in which they dwell.",
  "abortional - Pertaining to abortion; miscarrying; abortive. Carlyle.",
  "disquietness - Disturbance of quiet in body or mind; restlessness; uneasiness. Hooker.",
  "bordage - The base or servile tenure by which a bordar held his cottage.",
  "nurser - One who nurses; a nurse; one who cherishes or encourages growth.",
  "mutableness - The quality of being mutable.",
  "chiromantical - Of or pertaining to chiromancy.",
  "wareful - Wary; watchful; cautious. [Obs.]",
  "hyperopia - Hypermetropia. -- Hy`per*op\"tic, a.",
  "consectaneous - Following as a matter of course. Blount.",
  "scray - A tern; the sea swallow. [Prov. Eng.] [Written also sgraye.]",
  "striges - The tribe of birds which comprises the owls.",
  "houseroom - Room or place in a house; as, to give any one houseroom.",
  "tautochronous - Occupying the same time; pertaining to, or having the properties of, a tautochrone.",
  "ranchman - An owner or occupant of, or laborer on, a ranch; a herdsman. [Western U. S.]",
  "mussitation - A speaking in a low tone; mumbling. [Obs.]",
  "hypocarpogean - Producing fruit below the ground.",
  "incanton - To unite to, or form into, a canton or separate community. Addison.",
  "lacertian - Like a lizard; of or pertaining to the Lacertilia. -- n.  One of the Lacertilia.",
  "upheave - To heave or lift up from beneath; to raise. Milton.",
  "esophageal - Pertaining to the esophagus. [Written also .]",
  "bulgy - Bulged; bulging; bending, or tending to bend, outward. [Colloq.]",
  "antlia - The spiral tubular proboscis of lepidopterous insects. See Lepidoptera.",
  "kindler - One who, or that which, kindles, stirs up, or sets on fire.\"Kindlers of riot.\" Gay.",
  "empasm - A perfumed powder sprinkled upon the body to mask the odor of sweat.",
  "barway - A passage into a field or yard, closed by bars made to take out of the posts.",
  "towardness - Quality or state of being toward.",
  "globosely - In a globular manner; globularly.",
  "sirloin - A loin of beef, or a part of a loin. [Written also surloin.]",
  "petrosilicious - Containing, or consisting of, petrosilex.",
  "drabbet - A coarse linen fabric, or duck.",
  "tupman - A man who breeds, or deals in tups. [Prov. Eng.]",
  "fortin - A little fort; a fortlet. [Obs.]",
  "didascalic - Didactic; preceptive. [R.] Prior.",
  "overdeal - The excess. [Obs.] The overdeal in the price will be double. Holland.",
  "high-palmed - Having high antlers; bearing full-grown antlers aloft.",
  "saibling - A European mountain trout (Salvelinus alpinus); -- called also Bavarian charr.",
  "irresistless - Irresistible. [Obs.] Glanvill.",
  "larchen - Of or pertaining to the larch. Keats.",
  "unpeered - Having no peer; unequaled; unparalleled. \"Unpeered excellence.\" Marston.",
  "inexposure - A state of not being exposed.",
  "declivous - Descending gradually; moderately steep; sloping; downhill.",
  "interjectionalize - To convert into, or to use as, an interjection. Earle.",
  "enflesh - To clothe with flesh. [Obs.] Vices which are . . . enfleshed in him. Florio.",
  "yoke-toed - Having two toes in front and two behind, as the trogons and woodpeckers.",
  "kainit - Salts of potassium used in the manufacture of fertilizers.",
  "tuberiferous - Producing or bearing tubers.",
  "agential - Of or pertaining to an agent or an agency. Fitzed. Hall.",
  "feracious - Fruitful; producing abudantly. [R.] Thomson.",
  "mugient - Lowing; bellowing. [Obs.] Sir T. Browne.",
  "antipodean - Pertaining to the antipodes, or the opposite side of the world; antipodal.",
  "overseership - The office of an overseer.",
  "odalman - A man or woman having odal, or able to share in it by inheritance.",
  "supra-ilium - The cartilaginous cap at the sacral end of the ilium of some animals.",
  "tregetry - Trickery; also, a trick. [Obs.] Rom. of R.",
  "sarcoseptum - One of the mesenteries of an anthozoan.",
  "eelpot - A boxlike structure with funnel-shaped traps for catching eels; an eelbuck.",
  "defraudation - The act of defrauding; a taking by fraud. [R.] Sir T. Browne.",
  "cremor - Cream; a substance resembling cream; yeast; scum.",
  "kieserite - Hydrous sulphate of magnesia found at the salt mines of Stassfurt, Prussian Saxony.",
  "additory - Tending to add; making some addition. [R.] Arbuthnot.",
  "abderite - An inhabitant of Abdera, in Thrace. The Abderite, Democritus, the Laughing Philosopher.",
  "determinist - One who believes in determinism. Also adj.; as, determinist theories.",
  "goatskin - The skin of a goat, or leather made from it. -- a.  Made of the skin of a goat.",
  "unrobe - To disrobe; to undress; to take off the robes.",
  "apophlegmatizant - An apophlegmatic. [Obs.]",
  "wreath-shell - A marine shell of the genus Turbo. See Turbo.",
  "trochite - A wheel-like joint of the stem of a fossil crinoid.",
  "russify - To Russianize; as, to Russify conquered tribes.",
  "chincherie - Penuriousness. [Obs.] By cause of his skarsete and chincherie. Caucer.",
  "dyspeptical - Pertaining to dyspepsia; having dyspepsia; as, a dyspeptic or dyspeptical symptom.",
  "proparoxytone - A word which has the acute accent on the antepenult.",
  "restorationism - The belief or doctrines of the Restorationists.",
  "ordinator - One who ordains or establishes; a director. [R.] T. Adams.",
  "nowed - Knotted; tied in a knot, as a serpent.",
  "ekename - An additional or epithet name; a nickname. [Obs.]",
  "dashingly - Conspicuously; showily. [Colloq.] A dashingly dressed gentleman. Hawthorne.",
  "rarefiable - Capable of being rarefied. Boyle.",
  "candiot - Of or pertaining to Candia; Cretary.",
  "snuffy - 1. Soiled with snuff. 2. Sulky; angry; vexed. [Obs. or Scot.] Jamieson.",
  "cynarctomachy - Bear baiting with a dog. Hudibras.",
  "costal-nerved - Having the nerves spring from the midrib.",
  "underturn - To turn upside down; to subvert; to upset. [Obs.] Wyclif.",
  "lumbriciform - Resembling an earthworm; vermiform.",
  "chafewax - Formerly a chancery officer who fitted wax for sealing writs and other documents.",
  "undrape - To strip of drapery; to uncover or unveil.",
  "clapbread - Oatmeal cake or bread clapped or beaten till it is thin. [Obs.] Halliwell.",
  "cheese cloth - A thin, loosewoven cotton cloth, such as is used in pressing cheese curds.",
  "deodorizer - He who, or that which, deodorizes; esp., an agent that destroys offensive odors.",
  "plano-conical - Plane or flat on one side, and conical on the other. Grew.",
  "logician - A person skilled in logic. Bacon. Each fierce logician still expelling Locke. Pope.",
  "doryphora - A genus of plant-eating beetles, including the potato beetle. See Potato beetle.",
  "lorate - Having the form of a thong or strap; ligulate.",
  "celticism - A custom of the Celts, or an idiom of their language. Warton.",
  "unfrangible - Infrangible. [Obs.] \"Impassible and unfrangible.\" Jer. Taylor.",
  "finikin - Precise in trifles; idly busy. [Colloq.] Smart.",
  "forelie - To lie in front of. [Obs.] Which forelay Athwart her snowy breast. Spenser.",
  "miltonic - Of, pertaining to, or resembling, Milton, or his writings; as, Miltonic prose.",
  "sprinter - One who sprints; one who runs in sprint races; as, a champion sprinter.",
  "bachelorhood - The state or condition of being a bachelor; bachelorship.",
  "nonappearance - Default of apperance, as in court, to prosecute or defend; failure to appear.",
  "impoofo - The eland. [Written also impoofoo.]",
  "finchbacked - Streaked or spotted on the back; -- said of cattle.",
  "infecundous - Infertile; barren; unprofitable; unproductive. [Obs.] Glanvill.",
  "bernese - Pertaining to the city o -- n. sing. & pl.  A native or natives of Bern.",
  "furlong - A measure of length; the eighth part of a mile; forty rods; two hundred and twenty yards.",
  "saddlebow - The bow or arch in the front part of a saddle, or the pieces which form the front.",
  "proletariate - The lower classes; beggars. \"The Italian proletariate.\" J. A. Symonds.",
  "henfish - (a) A marine fish; the sea bream. (b) A young bib. See Bib, n., 2.",
  "picts - A race of people of uncertain origin, who inhabited Scotland in early times.",
  "unbraid - To separate the strands of; to undo, as a braid; to unravel; to disentangle.",
  "quadriga - A car or chariot drawn by four horses abreast.",
  "alcyonic - Of or pertaining to the Alcyonaria.",
  "sabbatism - Intermission of labor, as upon the Sabbath; rest. Dr. H. More.",
  "baronetage - 1. State or rank of a baronet. 2. The collective body of baronets.",
  "parodist - One who writes a parody; one who parodies. Coleridge.",
  "acutifoliate - Having sharp-pointed leaves.",
  "pachycarpous - Having the pericarp thick.",
  "colaborer - One who labors with another; an associate in labor.",
  "sectorial - Adapted for cutting. -- n.  A sectorial, or carnassial, tooth.",
  "annotatory - Pertaining to an annotator; containing annotations. [R.]",
  "vestigial - Of or pertaining to a vestige or remnant; like a vestige.",
  "sparseness - The quality or state of being sparse; as, sparseness of population.",
  "teinland - Land granted by the crown to a thane or lord. Burrill.",
  "timeliness - The quality or state of being timely; seasonableness; opportuneness.",
  "foreallege - To allege or cite before. Fotherby.",
  "two-forked - Divided into two parts, somewhat after the manner of a fork; dichotomous.",
  "fractural - Pertaining to, or consequent on, a fracture. [R.]",
  "malacostracan - One of the Malacostraca.",
  "gibaro - The offspring of a Spaniard and an Indian; a Spanish-Indian mestizo. [Sp. Amer.]",
  "gimmer - A piece of mechanism; mechanical device or contrivance; a gimcrack. [Obs.] Bp. Hall. Shak.",
  "liquescent - Tending to become liquid; inclined to melt to melt; melting.",
  "porismatic - Of or pertaining to a porism; poristic.",
  "seten - obs. imp. pl. of Sit. Sat. Chaucer.",
  "interfretted - Interlaced; linked together; -- said of charges or bearings. See Fretted.",
  "experient - Experienced. [Obs.] The prince now ripe and full experient. Beau & Fl.",
  "schappe - A silk yarn or fabric made out of carded spun silk.",
  "striving - from Strive. -- Striv\"ing*ly, adv.",
  "lithographer - One who lithographs; one who practices lithography.",
  "fasciculated - Grouped in a fascicle; fascicled.",
  "calcariferous - Lime-yielding; calciferous",
  "measurer - One who measures; one whose occupation or duty is to measure commondities in market.",
  "monozoa - A division of Radiolaria; -- called also Monocyttaria. -- Mon`o*zo\"ic, a.",
  "incontentation - Discontent. [Obs.] Goodwin.",
  "airwards - Toward the air; upward. [R.] Keats.",
  "tose - To tease, or comb, as wool. [Obs.or Prov. Eng.]",
  "dragnet - A net to be drawn along the bottom of a body of water, as in fishing.",
  "semicolumnar - Like a semicolumn; flat on one side and round on the other; imperfectly columnar.",
  "stomachous - Stout; sullen; obstinate. [Obs.] With stern looks and stomachous disdain. Spenser.",
  "egyptologist - One skilled in the antiquities of Egypt; a student of Egyptology.",
  "rurally - In a rural manner; as in the country.",
  "verriculate - Having thickset tufts of parallel hairs, bristles, or branches.",
  "scrapbook - A blank book in which extracts cut from books and papers may be pasted and kept.",
  "pig-sticking - Boar hunting; -- so called by Anglo-Indians. [Colloq.] Tackeray.",
  "overpaint - To color or describe too strongly. Sir W. Raleigh.",
  "legitimism - The principles or plans of legitimists.",
  "unobservance - Want or neglect of observance; inobservance. Whitlock.",
  "refuter - One who, or that which, refutes.",
  "plate-gilled - Having flat, or leaflike, gills, as the bivalve mollusks.",
  "fiaunt - Commission; fiat; order; decree. [Obs.] Spenser.",
  "galericulate - Covered as with a hat or cap. Smart.",
  "brevirostral - Short-billed; having a short beak.",
  "princekin - A petty prince; a princeling. The princekins of private life. Thackeray.",
  "gharry - Any wheeled cart or carriage. [India]",
  "octahedrite - Titanium dioxide occurring in acute octahedral crystals.",
  "stockbroker - A broker who deals in stocks.",
  "dag-tailed - Daggle-tailed; having the tail clogged with daglocks. \"Dag- tailed sheep.\" Bp. Hall.",
  "cirriform - Formed like a cirrus or tendril; -- said of appendages of both animals and plants.",
  "interamnian - Situated between rivers. [R.] \"An interamnian country.\" J. Bryant.",
  "duskness - Duskiness. [R.] Sir T. Elyot.",
  "sanguinolent - Tinged or mingled with blood; bloody; as, sanguinolent sputa.",
  "brusqueness - Quality of being brusque; roughness joined with promptness; blutness. Brit. Quar.",
  "liminess - The state or quality of being limy.",
  "lobefoot - A bird having lobate toes; esp., a phalarope.",
  "hordock - An unidentified plant mentioned by Shakespeare, perhaps equivalent to burdock.",
  "applot - To divide into plots or parts; to apportion. Milton.",
  "heartiness - The quality of being hearty; as, the heartiness of a greeting.",
  "-gerous - A suffix signifying bearing, producing; as, calcigerous; dentigerous.",
  "rabbler - A scraping tool for smoothing metal.",
  "umbellated - Bearing umbels; pertaining to an umbel; umbel-like; as, umbellate plants or flowers.",
  "imborder - To furnish or inclose with a border; to form a border of. Milton.",
  "bluff-headed - Built with the stem nearly straight up and down.",
  "bluff-bowed - Built with the stem nearly straight up and down.",
  "warmful - Abounding in capacity to warm; giving warmth; as, a warmful garment. [R.] Chapman.",
  "diseasement - Uneasiness; inconvenience. [Obs.] Bacon.",
  "understood - imp. & p. p. of Understand.",
  "ilixanthin - A yellow dye obtained from the leaves of the holly.",
  "involvedness - The state of being involved.",
  "pimpillo - A West Indian name for the prickly pear (Opuntia); -- called also pimploes.",
  "linearly - In a linear manner; with lines.",
  "tautophony - Repetition of the same sound.",
  "yowe - A ewe. [Prov. Eng. & Scot.] G. Eliot.",
  "disobeisance - Disobedience. [Obs.] E. Hall.",
  "laterite - An argillaceous sandstone, of a red color, and much seamed; -- found in India.",
  "hydruret - A binary compound of hydrogen; a hydride. [Obs.]",
  "smicket - A woman's under-garment; a smock. [Obs. or Prov. Eng.] Johnson.",
  "repopulation - The act of repeopling; act of furnishing with a population anew.",
  "amygdaline - Of, pertaining to, or resembling, almonds.",
  "repedation - A stepping or going back. [Obs.] Dr. H. More.",
  "smearcase - Cottage cheese. [Local, U. S.]",
  "cetology - The description or natural history of cetaceous animals.",
  "convalescently - In the manner of a convalescent; with increasing strength or vigor.",
  "forebodement - The act of foreboding; the thing foreboded.",
  "fluxility - State of being fluxible.[Obs.]",
  "distillate - The product of distillation; as, the distillate from molasses.",
  "cockyolly bird - A pet name for any small bird.",
  "chief baron - The presiding judge of the court of exchequer.",
  "fluidness - The state of being flluid; fluidity.",
  "nolleity - The state of being unwilling; nolition. [R.]",
  "impassivity - The quality of being insusceptible of feeling, pain, or suffering; impassiveness.",
  "federary - A partner; a confederate; an accomplice. [Obs.] hak.",
  "porrection - The act of stretching forth.",
  "rhus - A genus of shrubs and small treets. See Sumac.",
  "bilaterality - State of being bilateral.",
  "lollingly - In a lolling manner. Buckle.",
  "murage - A tax or toll paid for building or repairing the walls of a fortified town.",
  "mucopurulent - Having the character or appearance of both mucus and pus. Dunglison.",
  "crop-ear - A person or animal whose ears are cropped.",
  "sightsman - One who reads or performs music readily at first sight. [R.] Busby.",
  "unprovident - Improvident. [Obs.] \"Who for thyself art so unprovident.' Shak.",
  "improportionable - Not proportionable. [Obs.] B. Jonson.",
  "irreversibleness - The state or quality of being irreversible.",
  "totalis - The total. I look on nothing but totalis. B. Jonson.",
  "invigilance - Want of vigilance; neglect of watching; carelessness.",
  "agnomination - 1. A surname. [R.] Minsheu. 2. Paronomasia; also, alliteration; annomination.",
  "detrusion - The act of thrusting or driving down or outward; outward thrust. -- De*tru\"sive, a.",
  "chalky - Consisting of, or resembling, chalk; containing chalk; as, a chalky cliff; a chalky taste.",
  "quodlibetarian - One who discusses any subject at pleasure.",
  "hell-haunted - Haunted by devils; hellish. Dryden.",
  "high-reaching - Reaching high or upward; hence, ambitious; aspiring. Shak.",
  "intransmutability - The quality of being intransmutable.",
  "puerperal - Of or pertaining to childbirth; as, a puerperal fever.",
  "chondrometer - A steelyard for weighting grain.",
  "urceolus - Any urn-shaped organ of a plant.",
  "nudibrachiate - Having tentacles without vibratile cilia. Carpenter.",
  "orphic - Pertaining to Orpheus; Orphean; as, Orphic hymns.",
  "obsoletism - A disused word or phrase; an archaism. Fitzed. Hall.",
  "digitation - A division into fingers or fingerlike processes; also, a fingerlike process.",
  "selfist - A selfish person. [R.] I. Taylor.",
  "meningeal - Of or pertaining to the meninges.",
  "brigandish - Like a brigand or freebooter; robberlike.",
  "fraudulence - The quality of being fraudulent; deliberate deceit; trickishness. Hooker.",
  "asphalte - Asphaltic mastic or cement. See Asphalt, 2.",
  "umbellate - Bearing umbels; pertaining to an umbel; umbel-like; as, umbellate plants or flowers.",
  "incompletion - Want of completion; incompleteness. Smart.",
  "deplication - An unfolding, untwisting, or unplaiting. [Obs.] W. Montagu.",
  "afrite - A powerful evil jinnee, demon, or monstrous giant.",
  "galvanographic - Of or pertaining to galvanography.",
  "bibliopolistic - Of or pertaining to bibliopolism. Dibdin.",
  "unchain - To free from chains or slavery; to let loose. Prior.",
  "knickerbockers - The name for a style of short breeches; smallclothes.",
  "incorrection - Want of correction, restraint, or discipline. [Obs.] Arnway.",
  "debituminization - The act of depriving of bitumen.",
  "concordable - Capable of according; agreeing; harmonious.",
  "sompne - To summon; to cite. [Obs.] Chaucer.",
  "mechanographist - An artist who, by mechanical means, multiplies copies of works of art.",
  "anenterous - Destitute of a stomach or an intestine. Owen.",
  "forequoted - Cited before; quoted in a foregoing part of the treatise or essay.",
  "paganish - Of or pertaining to pagans; heathenish. \"The old paganish idolatry.\" Sharp",
  "fleshiness - The state of being fleshy; plumpness; corpulence; grossness. Milton.",
  "dulcoration - The act of sweetening. [R.] Bacon.",
  "self-centration - The quality or state of being self-centered.",
  "rectinerved - Having the veins or nerves straight; -- said of leaves.",
  "anglice - In English; in the English manner; as, Livorno, Anglice Leghorn.",
  "hordein - A peculiar starchy matter contained in barley. It is complex mixture. [R.]",
  "quinquepartite - 1. Consisting of five parts. 2. (Bot.)  Divided into five parts almost to the base.",
  "anodon - A genus of fresh-water bivalves, having to teeth at the hinge. [Written also Anodonta.]",
  "nemato- - . A combining from Gr. nhema, nhematos, a thread.",
  "devoration - The act of devouring. [Obs.] Holinshed.",
  "mowburn - To heat and ferment in the mow, as hay when housed too green.",
  "peloric - Abnormally regular or symmetrical. Darwin.",
  "landtag - The diet or legislative body; as, the Landtag of Prussia.",
  "armipotent - Powerful in arms; mighty in battle. The temple stood of Mars armipotent. Dryden.",
  "acrobatism - Feats of the acrobat; daring gymnastic feats; high vaulting.",
  "scholiastic - Of or pertaining to a scholiast, or his pursuits. Swift.",
  "muset - A small hole or gap through which a wild animal passes; a muse. Shak.",
  "camberkeeled - Having the keel arched upwards, but not actually hogged; -- said of a ship.",
  "reclusely - In a recluse or solitary manner.",
  "fetiferous - Producing young, as animals.",
  "restauration - Restoration. [Obs.] Cower.",
  "gralloch - Offal of a deer. -- v. t.  To remove the offal from (a deer).",
  "souple - That part of a flail which strikes the grain. Knight.",
  "satyric - Of or pertaining to satyrs; burlesque; as, satyric tragedy. P. Cyc.",
  "ornithic - Of or pertaining to birds; as, ornithic fossils. Owen.",
  "superinspect - To over see; to superintend by inspection. [R.] Maydman.",
  "mullagatawny - An East Indian curry soup.",
  "chider - One who chides or quarrels. Shak.",
  "telephony - The art or process of reproducing sounds at a distance, as with the telephone.",
  "argillo-areenaceous - Consisting of, or containing, clay and sand, as a soil.",
  "meritot - A play of children, in swinging on ropes, or the like, till they are dizzy.",
  "organotrophic - Relating to the creation, organization, and nutrition of living organs or parts.",
  "pressirostral - Of or pertaining to the pressirosters.",
  "sinless - Free from sin. Piers Plowman. -- Sin\"less*ly, adv. -- Sin\"less*ness, n.",
  "intermembranous - Within or beneath a membrane; as, intermembranous ossification.",
  "guileless - Free from guile; artless. -- Guile\"less*ly, adv. Guile\"less*ness, n.",
  "kaynard - A lazy or cowardly person; a rascal. [Obs.] Chaucer.",
  "bateful - Exciting contention; contentious. [Obs.] \"It did bateful question frame. \" Sidney.",
  "ovato-acuminate - Same as Ovate-acuminate.",
  "cricoid - Resembling a ring; -- said esp. of the cartilage at the larynx, and the adjoining parts.",
  "berhyme - To mention in rhyme or verse; to rhyme about. Note: [Sometimes use depreciatively.] Shak.",
  "portsale - Public or open sale; auction. [Obs.] Holland.",
  "conchometry - The art of measuring shells or their curves; conchyliometry.",
  "brills - The hair on the eyelids of a horse. Bailey.",
  "gaber-lunzie - A beggar with a wallet; a licensed beggar. [Scot.] Sir W. Scott.",
  "siemens-martin process - See Open-hearth process, etc., under Open.",
  "inexplicableness - A state of being inexplicable; inexplicability.",
  "vitriolization - The act of vitriolizing, or the state of being vitriolized; vitriolation.",
  "ruralist - One who leads a rural life. Coventry.",
  "cuttoo plate - A hood over the end of a wagon wheel hub to keep dirt away from the axle.",
  "stalworthness - The quality or state of being stalworth; stalwartness; boldness; daring. [Obs.]",
  "regardable - Worthy of regard or notice; to be regarded; observable. [R.] Sir T. Browne.",
  "ramberge - Formerly, a kind of large war galley.",
  "aluminize - To treat impregnate with alum; to alum.",
  "raghuvansa - A celebrated Sanskrit poem having for its subject the Raghu dynasty.",
  "slowworm - A lecertilian reptile; the blindworm.",
  "quincuncially - In the manner or order of a quincunx.",
  "unprudential - Imprudent. [Obs.] \"The most unwise and unprudential act.\" Milton.",
  "selenographic - Of or pertaining to selenography.",
  "bedrop - To sprinkle, as with drops. The yellow carp, in scales bedropped with gold. Pope.",
  "multicellular - Consisting of, or having, many cells or more than one cell.",
  "fetisely - Neatly; gracefully; properly. [Obs.] Chaucer.",
  "custodier - A custodian. [Scot.] Sir W. Scott.",
  "choleic - Pertaining to, or obtained from, bile; as, choleic acid.",
  "chuprassie - A messenger or servant wearing an official badge. [Anglo- Indian]",
  "podoscaph - A canoe-shaped float attached to the foot, for walking on water.",
  "instar - To stud as with stars. [R.] \"A golden throne instarred with gems.\" J. Barlow.",
  "professorialism - The character, manners, or habits of a professor. [R.]",
  "volante - A cumbrous two-wheeled pleasure carriage used in Cuba.",
  "colloidality - The state or quality of being colloidal.",
  "faintling - Timorous; feeble-minded. [Obs.] \"A fainting, silly creature.\" Arbuthnot.",
  "nandine - An African carnivore (Nandinia binotata), allied to the civets. It is spotted with black.",
  "cephalism - Form or development of the skull; as, the races of man differ greatly in cephalism.",
  "strix - One of the flutings of a column.",
  "stabilitate - To make stable; to establish. [Obs.] Dr. H. More.",
  "nonmanufacturing - Not carrying on manufactures.",
  "saddled - Having a broad patch of color across the back, like a saddle; saddle-backed.",
  "mispronounce - To pronounce incorrectly.",
  "bastioned - Furnished with a bastion; having bastions.",
  "deturpate - To defile; to disfigure. [Obs.] Jer. Taylor.",
  "hemihedrism - The property of crystallizing hemihedrally.",
  "prescriptibility - , The quality or state of being prescriptible. Story.",
  "cockloft - An upper loft; a garret; the highest room in a building. Dryden. Swift.",
  "stayless - Without stop or delay. Mir. for Mag.",
  "pacificatory - Tending to make peace; conciliatory.  Barrow.",
  "siththen - See Sithen. [Obs.] Siththen that the world began. Chaucer.",
  "albe - Although; albeit. [Obs.] Albe Clarissa were their chiefest founderess. Spenser.",
  "orsedew - Leaf metal of bronze; Dutch metal. See under Dutch.",
  "anconeus - A muscle of the elbow and forearm.",
  "classicism - A classic idiom or expression; a classicalism. C. Kingsley.",
  "blenk - To blink; to shine; to look. [Obs.]",
  "weiss beer - A light-colored highly effervescent beer made by the top- fermentation process.",
  "remordency - Remorse; compunction; compassion. [Obs.] Killingbeck.",
  "vaginopennous - Having elytra; sheath-winged. [R.]",
  "irrelapsable - Not liable to relapse; secure. Dr. H. More.",
  "proteranthous - Having flowers appearing before the leaves; -- said of certain plants. Gray.",
  "insanability - The state of being insanable or incurable; insanableness.",
  "haruspice - A diviner of ancient Rome. Same as Aruspice.",
  "fratery - A frater house. See under Frater.",
  "popping - a. & n. from Pop. Popping crease. (Cricket) See under Crease.",
  "hookedness - The state of being bent like a hook; incurvation.",
  "furcate - Forked; branching like a fork; as, furcate twigs.",
  "consuetude - Custom, habit; usage. [R.] To observe this consuetude or law. Barnes .",
  "suggillate - To beat livid, or black and blue. Wiseman.",
  "hard-labored - Wrought with severe labor; elaborate; studied. Swift.",
  "faule - A fall or falling band. [Obs.] These laces, ribbons, and these faules. Herrick.",
  "adventuress - A female adventurer; a woman who tries to gain position by equivocal means.",
  "mendicancy - The condition of being mendicant; beggary; begging. Burke.",
  "desilver - To deprive of silver; as, to desilver lead.",
  "autopsic - Pertaining to autopsy; autoptical. [Obs.]",
  "foreprize - To prize or rate beforehand. [Obs.] Hooker.",
  "undermaster - A master subordinate to the principal master; an assistant master.",
  "resale - A sale at second hand, or at retail; also, a second sale. Bacon.",
  "gaditanian - Of or relating to Cadiz, in Spain. -- n.  A native or inhabitant of Cadiz.",
  "apozem - A decoction or infusion. [Obs.] Wiseman.",
  "bickering - 1. A skirmishing. \"Frays and bickerings.\" Milton. 2. Altercation; wrangling.",
  "perilymphangial - Around, or at the side of, a lymphatic vessel.",
  "anaglyptics - The art of carving in low relief, embossing, etc.",
  "forewite - To foreknow. [Obs.] [Written also forwete.] Chaucer.",
  "electrolyzable - Capable of being electrolyzed, or decomposed by electricity.",
  "enormousness - The state of being enormous.",
  "boshvark - The bush hog. See under Bush, a thicket.",
  "citicism - The manners of a cit or citizen.",
  "stultiloquent - Given to, or characterized by, silly talk; babbling. -- Stul*til\"o*quent*ly, adv.",
  "exalter - One who exalts or raises to dignity.",
  "flintware - A superior kind of earthenware into whose composition flint enters largely. Knight.",
  "redistrict - To divide into new districts.",
  "ship-rigged - Rigged like a ship, that is, having three masts, each with square sails.",
  "surliness - The quality or state of being surly.",
  "druidess - A female Druid; a prophetess.",
  "heritability - The state of being heritable.",
  "distinguishingly - With distinction; with some mark of preference. Pope.",
  "cinerescent - Somewhat cinereous; of a color somewhat resembling that of wood ashes.",
  "erysipelatous - Resembling erysipelas, or partaking of its nature.",
  "spiciferous - Bearing ears, or spikes; spicate. [Obs.] Bailey.",
  "expoliation - See Exspoliation. [Obs.] Bp. Hall.",
  "equilibrity - The state of being balanced; equality of weight. [R.] J. Gregory.",
  "reservatory - A place in which things are reserved or kept. Woodward.",
  "zooephaga - An artificial group comprising various carnivorous and insectivorous animals.",
  "personation - The act of personating, or conterfeiting the person or character of another.",
  "wonderland - A land full of wonders, or marvels. M. Arnold.",
  "comportable - Suitable; consistent. [Obs.] \"Some comportable method.\" Wotton.",
  "ferreous - Partaking of, made of, or pertaining to, iron; like iron. [Obs.] Sir T. Browne.",
  "wristband - The band of the sleeve of a shirt, or other garment, which covers the wrist.",
  "hawk-eyed - Having a keen eye; sharpsighted; discerning.",
  "vainness - The quality or state of being vain.",
  "megalomania - A form of mental alienation in which the patient has grandiose delusions.",
  "habitance - Dwelling; abode; residence. [Obs.] Spenser.",
  "veratralbine - A yellowish amorphous alkaloid extracted from the rootstock of Veratrum album.",
  "pyroacid - An acid obtained by sybjecting another acid to the action of heat. Cf. Pyro-.",
  "sedation - The act of calming, or the state of being calm. [R.] Coles.",
  "trounce - To punish or beat severely; to whip smartly; to flog; to castigate. [Colloq.]",
  "informatory - Full of, or conveying, information; instructive. [R.] London Spectator.",
  "mincingly - In a mincing manner; not fully; with affected nicety.",
  "herling - The young of the sea trout. [Prov. Eng.]",
  "decreation - Destruction; -- opposed to creation. [R.] Cudworth.",
  "jinrikisha - A small, two-wheeled, hooded vehicle drawn by one more men. [Japan]",
  "vastity - Vastness. [Obs.] The huge vastity of the world. Holland.",
  "vaticinate - To prophesy; to foretell; to practice prediction; to utter prophecies.",
  "empearl - To form like pearls; to decorate with, or as with, pearls; to impearl.",
  "disinheritance - The act of disinheriting, or the condition of being; disinherited; disherison.",
  "plasmation - The act of forming or molding. [R.] Grafton.",
  "filigrain - Filigree. [Archaic] With her head . . . touches the crown of filigrane. Longfellow.",
  "irregeneration - An unregenerate state. [Obs.]",
  "menild - Covered with spots; speckled; variegated. [Obs.]",
  "cricothyroid - Of or pertaining both to the cricoid and the thyroid cartilages.",
  "albuminimeter - An instrument for ascertaining the quantity of albumen in a liquid.",
  "mitome - The denser part of the protoplasm of a cell.",
  "sacrific - Employed in sacrifice. [R.] Johnson.",
  "glandule - A small gland or secreting vessel.",
  "viniculture - The cultivation of the vine, esp. for making wine; viticulture.",
  "fogginess - The state of being foggy. Johnson.",
  "powder-posted - Affected with dry rot; reduced to dust by rot. See Dry rot, under Dry. [U.S.]",
  "foliaged - Furnished with foliage; leaved; as, the variously foliaged mulberry.",
  "autochthonism - The state of being autochthonal.",
  "eleme figs - A kind of figs of superior quality.",
  "colorific - Capable of communicating color or tint to other bodies.",
  "self-justifier - One who excuses or justifies himself. J. M. Mason.",
  "grillade - The act of grilling; also, that which is grilled.",
  "senatorian - Senatorial. [R.] De Quincey.",
  "unroof - To strip off the roof or covering of, as a house. Shak.",
  "unanchor - To loose from the anchor, as a ship. De Quincey.",
  "metrochrome - An instrument for measuring colors.",
  "epileptoid - Resembling epilepsy; as, epileptoid convulsions.",
  "interfolded - Intertwined; interlocked; clasped together. Longfellow.",
  "japery - Jesting; buffoonery. [Obs.] Chaucer.",
  "bimensal - See Bimonthly, a. [Obs. or R.]",
  "meminna - A small deerlet, or chevrotain, of India.",
  "elemi figs - A kind of figs of superior quality.",
  "shag-rag - The unkempt and ragged part of the community. [Colloq. or Slang.] R. Browning.",
  "peninsulate - To form into a peninsula. South River . . . peninsulates Castle Hill farm. W. Bentley.",
  "roscid - Containing, or consisting of, dew; dewy. [R.] Bacon.",
  "cenanthy - The absence or suppression of the essential organs (stamens and pistil) in a flower.",
  "childing - Bearing Children; (Fig.) productive; fruitful. [R.] Shak.",
  "cognizant - Having cognizance or knowledge. (of).",
  "foresighted - Sagacious; prudent; provident for the future. Bartram.",
  "socratist - A disciple or follower of Socrates.",
  "humiri - A fragrant balsam obtained from Brazilian trees of the genus Humirium.",
  "doupe - The carrion crow. [Written also dob.] [Prov. Eng.]",
  "drupelet - A small drupe, as one of the pulpy grains of the blackberry.",
  "deceptivity - Deceptiveness; a deception; a sham. [R.] Carlyle.",
  "lock hospital - . A hospital for the treatment of venereal diseases. [Eng.]",
  "vesicouterine - Of or pertaining to the bladder and the uterus.",
  "haematocrystallin - Same as Hematocrystallin.",
  "octogynian - Having eight pistils; octagynous.",
  "underchaps - The lower chaps or jaw. Paley.",
  "codist - A codifier; a maker of codes. [R.]",
  "swaddler - A term of contempt for an Irish Methodist. Shipley.",
  "dyingly - In a dying manner; as if at the point of death. Beau. & Fl.",
  "saraswati - The sakti or wife of Brahma; the Hindoo goddess of learning, music, and poetry.",
  "drowner - One who, or that which, drowns.",
  "ossivorous - Feeding on bones; eating bones; as, ossivorous quadrupeds. Derham.",
  "wofully - In a woeful manner; sorrowfully; mournfully; miserably; dolefully.",
  "aquapuncture - The introduction of water subcutaneously for the relief of pain.",
  "reinfund - To flow in anew. [Obs.] Swift.",
  "unbeing - Not existing. [Obs.] \"Beings yet unbeing.\" Sir T. Browne.",
  "euphonism - An agreeable combination of sounds; euphony.",
  "salamandroid - Like or pertaining to the salamanders.",
  "geminy - Twins; a pair; a couple. [Obs.] Shak.",
  "-ful - A suffix signifying full of, abounding with; as, boastful, harmful, woeful.",
  "-in - A suffix. See the Note under -ine.",
  "barroom - A room containing a bar or counter at which liquors are sold.",
  "marena - A European whitefish of the genus Coregonus.",
  "comparation - A making ready; provision. [Obs.]"
]